### ISSUE TITLE
Autofill API 26

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1]
In progress : https://github.com/Kunzisoft/KeePassDX/tree/feature/Autofill

**Comment by rugk** [comment]
Ah, that is this new Android 7 API?

**Comment by J-Jamet** [comment]
It's an Oreo feature API 26. ;) I'll add an option to disable notifications.

**Comment by KOLANICH** [comment]
How about the old pre-21 API?

**Comment by J-Jamet** [comment]
I can create a custom keyboard to copy fields. But the other features must be developed.

**Comment by J-Jamet** [comment]
Done in 2.5.0.0beta5, to improve with search.

**Comment by KOLANICH** [comment]
>I can create a custom keyboard to copy fields. But the other features must be developed.

Custom keyboard has terrible usability. I guess we need something better. There were password managers ([old versions of Lastpass](https://blog.lastpass.com/2017/11/lastpass-android-accessibility-services.html/)) utilizing accessibility api somehow,  or somethinglike https://stackoverflow.com/questions/8696489/android-simulate-key-press or both.

**Comment by rugk** [comment]
> utilizing accessibility api somehow

That's disallowed by Google, so you could get kicked out of the Play Store if it is implemented there. (could, of course, however be implemented in a separate build for F-Droid)

**Comment by J-Jamet** [comment]
Unfortunately, the Accessibility API can not be used to deploy to the Play Store. I am looking for the best solution but I'll have to compromise anyway. :/

**Comment by KOLANICH** [comment]
>That's disallowed by Google, so you could get kicked out of the Play Store

I have heard that they [have reconsidered](https://www.androidpolice.com/2017/12/07/google-pauses-accessibility-app-ban-considers-responsible-innovative-uses-accessibility-services/)
