### ISSUE TITLE
Lock the database when the screen shuts off

### ISSUE THREAD

**Issue by darhma** [Kunzisoft/KeePassDX#10]
Add an option to the application timeout to lock the database when the screen shuts off

**Comment by J-Jamet** [comment]
OK for this feature. Will be available soon.

**Comment by J-Jamet** [comment]
Link to 6bb0b1a7e76876e1c7205c8497a8b38b9bfa5763

**Comment by J-Jamet** [comment]
Done in **2.5.0.0beta3**
