### ISSUE TITLE
Need an easy way to force a sync with Cloud

### ISSUE THREAD

**Issue by freMea** [Kunzisoft/KeePassDX#100]
App version | OS 
------------------ | ---- 
2.5.0.0beta9-free | Android 6.0.1

### Steps to reproduce

1. Open a DB from GDrive
2. In an other device, edit (add new entry for test) and sync the same DB with Keepass or else.
3. Check the GDrive file modification date is related to this last sync.
4. The only way to get the modifications in DX is to close the DB and open it again. And this sometimes fails to get the modifications if opened via the DX recent files before 5 minutes elapsed. Or you have to close/reopen the DB twice via recent file to get the changes.

### Steps to reproduce

1. Open a DB from GDrive
2. Delete an entry in DX. The DB is saved.
3. Close the DB and reopen in DX. Modifications are applied correctly.
4. Open the GDrive in another device with Keepass or else.
5. Modifications are applied correctly only if you proceed about 5 minutes later you applied and saved modifications in DX. It seems DX sync the DB in background without notify user when it is actually done.

## Other issues
The name of the previous GDrive kdbx in recent file is not really obvious
![GitHub Logo](https://i.snag.gy/9vlFun.jpg)

## Expectations

We need a menu entry to force the DB to sync with the cloud or the local file.

**Comment by J-Jamet** [comment]
I have not yet developed (or tested) real-time synchronization with clouds.
It will be necessary to check external modifications on the files to avoid the operations of simultaneous writing.
For the current version: KeePass DX saves (with a thread) the database after each change, there is no deferred service. So if you have to wait 5 minutes, I see two explanations : 
 - the content provider does not update in real time the links provided by the file manager
 - there is a latency between the different synchronization entities
In any case, the synchronization is not done yet and it's a big job, I also have to check the simultaneous changes to make a merge of data. (Https://keepass.info/help/base/multiuser.html)

**Comment by patarapolw** [comment]
It is the same possible sync issue as https://www.reddit.com/r/KeePass/comments/a2pyeu/some_questions_about_keepass_on_google_drive/eb0pf80 ?

> From glancing at the FAQ, it looks like it has the same flaw almost every other mobile app has: it saves to cloud files directly, instead of doing a sync operation. KeePass2Android is the only mobile app I know for sure does this. Why is this a problem? If you ever edit your database on your PC while offline (perhaps the Drive desktop client crashed, or needs you to login again or something), then edit your database on your mobile app before the desktop client can sync, you create a conflict. You have two versions of your database file and Drive doesn't know how to merge them. Only KeePass knows how to merge them.

I use KeepassXC on desktop (Mac), BTW.

**Comment by J-Jamet** [comment]
Same as #840, I'm closing this issue. In version 3.2, it will be enough to press the merge button.
