### ISSUE TITLE
Optimize magic keyboard interaction

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#1000]
**Is your feature request related to a problem? Please describe.**
After selecting the entry in the database, click the notification of the magic keyboard, the keyboard will automatically switch to the magic keyboard.

**Describe the solution you'd like**
After selecting the entry in the database, click the notification of the magic keyboard, the keyboard will automatically switch to the magic keyboard.

**Describe alternatives you've considered**
1. Run the application that needs to be populated；
2. Unlock the database and select the entry；
3.  At this point, you can see "Entry available for magic keyboard" in the notification bar；
4.  Clicking on this notification, I hope to switch directly to the magic keyboard.

**Additional context**
Clicking on the above notification will not automatically switch to the magic keyboard.
At present, you need to select the magic keyboard through the input method selector of the system.

**Comment by J-Jamet** [comment]
Android does not allow automatic switching from another active keyboard with special root permission.
Linked to #643 #311

**Comment by J-Jamet** [comment]
But it is possible to ask the user to select the keyboard manually when pressing the notification. But it is possible to ask the user to select the keyboard manually when pressing the notification (same behavior as [Keyboard Switcher](https://play.google.com/store/apps/details?id=com.kunzisoft.keyboard.switcher))

**Comment by Vstory** [comment]
> Android does not allow automatic switching from another active keyboard with special root permission.

😭

> But it is possible to ask the user to select the keyboard manually when pressing the notification. But it is possible to ask the user to select the keyboard manually when pressing the notification (same behavior as [Keyboard Switcher](https://play.google.com/store/apps/details?id=com.kunzisoft.keyboard.switcher))

I recommend integrating the functionality of the application.
KeePassDX supports, when the notification bar shows "Magic keyboard contains available items", click on the notification, and the input method switch selection window will pop up.

In this way, there is no need to trigger the input method and switch directly to the magic keyboard.
Otherwise, trigger the input method and press and hold the space in the notification bar or the input method selector to switch

**Comment by Vstory** [comment]
@J-Jamet 

1.  I manually unlocked the database and copied the password of an entry. After that, the item is displayed in the notification bar.
2.  At this point, I switched to the magic keyboard. The magic keyboard will not select the items currently available in the notification bar. I have to select the entry through the magic keyboard again.

Can you change the logic of the magic keyboard? The notification bar shows that there is an item available, switch to the magic keyboard, and the item is automatically selected.

**Comment by J-Jamet** [comment]
I can't reproduce the behavior you describe.
1. Copying the password of an entry has nothing to do with the notification display. It is displayed only if there is data in entry to be added when the "Settings - Form filling - Magikeyboard settings - Entry selection" option is enabled.
2. For me, the entry is well selected in the Magikeyboard.

> Can you change the logic of the magic keyboard? The notification bar shows that there is an item available, switch to the magic keyboard, and the item is automatically selected.

As I said before, I can't automatically change the keyboard if there is another one already activated without special permission. I can only suggest to the user to change it.

**Comment by Vstory** [comment]
> Copying the password of an entry has nothing to do with the notification display. 

Settings -> Form filling -> Clipboard notification
This notification is not an item selection notification of the magic keyboard.
[keepassdx.properties.zip](https://github.com/Kunzisoft/KeePassDX/files/6561612/keepassdx.properties.zip)


When the clipboard notification is triggered, when I manually switch to the magic keyboard input method, can the item be automatically selected?
![Screenshot_2021-05-28-21-34-59-382_com tencent mobileqq_Mosaic_21_37_50](https://user-images.githubusercontent.com/20795557/120002897-d1143a80-c007-11eb-83fc-5216fa8d2acf.jpg)

Meaning, after the clipboard notification(Settings -> Form filling -> Clipboard notification) is triggered. At this time, I manually switched to the magic keyboard.
The magic keyboard can select the items displayed in the clipboard notification by default, without having to select it again.

![Screenshot_2021-05-28-21-35-06-264_com tencent mobileqq_Mosaic_21_38_13](https://user-images.githubusercontent.com/20795557/120002902-d3769480-c007-11eb-8e7a-931e08acc1a8.jpg)

**Comment by Vstory** [comment]
> As I said before, I can't automatically change the keyboard if there is another one already activated without special permission. I can only suggest to the user to change it.

I understand. I did not ask for automatic keyboard switching.
The magic keyboard can select the items displayed in the clipboard notification by default without having to select the item again.

Why don't I use "Settings-Form filling-Magikeyboard settings-Entry selection"?

**Comment by J-Jamet** [comment]
The clipboard and the magikeyboard are two independent features.
I don't recommend to use the clipboard especially if you use the magikeyboard.

**Comment by Vstory** [comment]
> The clipboard and the magikeyboard are two independent features.
> I don't recommend to use the clipboard especially if you use the magikeyboard.

Thank you. 
There may be a problem with my usage, I am considering the solution you mentioned.
