### ISSUE TITLE
Auto-save information problem in auto-fill

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#1001]
**Describe the bug**
After using auto-fill, searching for items and selecting them, if saving information is enabled, there are some problems when writing data.
It will not merge with the existing field values, but instead add a new custom field.
For example, the original field is: `AndroidApp`, then add `AndroidApp_1`

**To Reproduce**
1. Prepare an entry, and create a field AndroidApp, and write the value.
2.  Turn on the data saving options of auto-fill and magic keyboard.
3.  Try to autofill, trigger the selection of entries, and then try to reproduce the problem.

**Expected behavior**
Merged with existing custom field values.

- Such as URL: 
Original url:  `A`, New url: `B`
After the merger: `A,B`

- Such as AndroidApp: 
Original: `com.aaa`, New: `com.bbb`
After the merger: `com.aaa,com.bbb`

**KeePass Database**
 - Created with: Windows KeePass 2.48.1
 - Version: KeePass 2-KDBX4.1
 - Location: Local Disk
 - Size: 6.65M
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 2.10.2(79)
 - Build: Pro
 - Language: Chinese

**Android (please complete the following information):**
 - Device: XiaoMi Note 3
 - Version: 9.0

**Comment by J-Jamet** [comment]
This is not a bug, it's the behavior we defined to register several applicationId to be consistent with other KeePass applications.
Why do you want it to be in the same field?

**Comment by Vstory** [comment]
> Why do you want it to be in the same field?

For some applications (A, B, C), they use the same account.
And I don't like to append "_1", "_2" after the field.
Like AndroidApp, AndroidApp_1, AndroidApp_2.

**Comment by J-Jamet** [comment]
What are the other applications?
This was decided in the KeePassXC thread with other KeePass creators.  https://github.com/keepassxreboot/keepassxc/discussions/6229#discussioncomment-432102

**Comment by Vstory** [comment]
> This was decided in the KeePassXC thread with other KeePass creators. [keepassxreboot/keepassxc#6229 (comment)](https://github.com/keepassxreboot/keepassxc/discussions/6229#discussioncomment-432102)

Thank you. I have read and understood.
But I will not use this method, I prefer my current usage. ApplicationId [n], when there are too many custom fields, it will not be "concise" enough.

> What are the other applications?
I have quite a few applications that require the same account.
