### ISSUE TITLE
Paste in the password field

### ISSUE THREAD

**Issue by chilliger** [Kunzisoft/KeePassDX#1002]
Several times now I wanted to paste from the clipboard in the password field of an entry but the field does not provide this option. Why? 

Its pretty anoying to type the password when you can simply copy it from an other source.

**Comment by Vstory** [comment]
Check the permission of the gboard clipboard, whether you have permission to read and write the clipboard in the background.

**Comment by chilliger** [comment]
I do not see such an option
<img src="https://user-images.githubusercontent.com/2310896/120163426-c9b48300-c1f9-11eb-80f2-6372a899f241.png" width="325"> <img src="https://user-images.githubusercontent.com/2310896/120163501-dd5fe980-c1f9-11eb-8c66-77340808fe5a.png" width="325">

**Comment by Vstory** [comment]
I encountered this problem in other applications. [AdAway](https://github.com/AdAway/AdAway)
The paste function cannot work in the input box for adding a blacklisted domain name. If you switch to the input box of another application, everything is normal.

**Comment by chilliger** [comment]
Im closing this. I encounter inconsistent behavior. This is clearly a OS issue.
