### ISSUE TITLE
Ability to ignore/blacklist entries form autofill auto0-search result?

### ISSUE THREAD

**Issue by azfar** [Kunzisoft/KeePassDX#1006]
Is there any way to exclude some entries from auto search results, I have some credentials applicable to same domain but only one of them is primary which I want to appear in autosearch.

**Comment by J-Jamet** [comment]
The automatic search is based on the requested information, so the result matches these criteria. If you only want one entry, just select it next. Can you indicate in which case you want to add a selection criterion to block search items?

**Comment by azfar** [comment]
My use-case is slightly complex, being a sysadmin I have to manage dozens of credentials for various businesses (group companies) for same services/domains multiple time, hundreds of clients' credentials along with personal and family's but not all I want to appear in autofill search results that's why I am looking for something baaed on tag, custom attribute etc but off-course when I need to locate them  they should appear in normal (manual) search.

**Comment by lohgun** [comment]
I'm in a similar situation as @azfar.
On the desktop version I can exclude some entries by setting these group's properties to false:

```xml
<Group>
    [...]
    <EnableAutoType>false</EnableAutoType>
    <EnableSearching>false</EnableSearching>
    [...]
</Group>
```
I think _KeePassDX_ should respect them by default and, in the menu of result activity, there should be option like "_Search all entries_" to override the search limitation.

I tried to keep two separate DBs, but it's bothersome, at lest for me :wink: , to work switching back and forth when I need the auto fill function. Besides some entries don't even contain password, but are used to store SSL keys or VPN certificates.

**Comment by cbiere** [comment]
I think my use case is different but a subset of the same issue. I've noticed that when I try to login into webmail, KeePassDX suggests entries which contain an email address for the same domain. This happens unless the email address is also the username in which case the entry is ignored.

Example: Log into https://example.org/ using Chrome or similar browser.
KeePass entry "Mobile Provider" contains the attribute email with value whatever@example.org, URL is completey unrelated and username is a  phone number.
Result: Autosearch causes match for "Mobile Provider".

**Comment by J-Jamet** [comment]
@cbiere What you describe is another issue related to Autofill. Please open another issue if you still have the problem with version 3.3.0

@azfar & @lohgun Now it is possible to select search by group -> "Searchable" parameter.
