### ISSUE TITLE
Ability to search into Custom Fields and URL (Chrome Browser extension) instead of Title/Group

### ISSUE THREAD

**Issue by azfarhashmi** [Kunzisoft/KeePassDX#1007]
The Chrome Browser extension looks into Title, Group and Username, it would be much better (and better control) if it can also support Custom Fields and URL instead of those.

**Comment by azfar** [comment]
pls disregard it, posted in wrong keepass fork.

**Comment by J-Jamet** [comment]
There is no KeePassDX extension for Chrome.
