### ISSUE TITLE
Feature Request: Database Synchronization

### ISSUE THREAD

**Issue by MisterY** [Kunzisoft/KeePassDX#1008]
**Is your feature request related to a problem? Please describe.**

When doing manual database synchronization via network, there will inevitably come situations where we've made changes on both sides and need to synchronize the entries.
This request is not for the network synchronization (which I find rclone to be a good solution for) but the actual database synchronization that KeePass supports, i.e. - merging the entries from two different databases into one.
In KeePassDX it is called Merge from Database.

**Describe the solution you'd like**

I'd like to be able to merge entries from another kdbx file. My main use case is having two conflicting copies of the network-synced database file and wanting to merge the (potential) changes from both of them.

**Describe alternatives you've considered**
 
Doing this on desktop.

**Comment by J-Jamet** [comment]
Duplicate #840
