### ISSUE TITLE
Stuck in edit screen

### ISSUE THREAD

**Issue by freMea** [Kunzisoft/KeePassDX#101]
App version | OS 
------------------ | ---- 
2.5.0.0beta9-free | Android 6.0.1

## Steps to reproduce
1. Edit or create an new entry in a DB from GDrive
2. After clicking the **save** button you can not go back with hardware button or the arrow from the app. You are stuck in edit screen.
3. You have to close the app via the Android recent apps screen.
4. Reopen the app and DB. The changes were applied.

**Comment by J-Jamet** [comment]
Linked to #100

**Comment by J-Jamet** [comment]
Fixed in version 2.5.0.0beta16
