### ISSUE TITLE
Don't auto change keyboards/clear entry after magickeyboard press of password

### ISSUE THREAD

**Issue by afonsoc12** [Kunzisoft/KeePassDX#1012]
**Is your feature request related to a problem? Please describe.**
1. When looking for a password, I change to Magickeyboard and press the "key" button to find for an entry. After selecting an entry from KeepassDX, it automatically changes back to default keyboard, and I have to change it again.

2. When I press the password button of magickeyboard, it automatically presses enter (Is this expected behaviour?)
However, when I am next prompted with a TOTP field, it changes the keyboard to the default one, and deletes the entry. So I have to go change keyboards twice and select the entry twice.

**Describe the solution you'd like**
1. Not auto change keyboard, only when button is pressed or force magickeyboard when an entry is available
2. Not auto-delete entry after password pressed (and the keyboard automatically presses enter)

**Other (minor) Bug**
Some TOTP sequences which have one box per character, do not correctly parse from TOTP. An example is authelia TOTP. W
![WhatsApp Image 2021-06-01 at 00 16 19](https://user-images.githubusercontent.com/20598780/120248341-a4ae2780-c26e-11eb-913f-d12b1daed38f.jpeg)

**Additional context**
Thanks for solving #997! Haven't tested it yet, but found it delivered on play store

**Comment by J-Jamet** [comment]
1/2 - Settings - Form filling - Magikeyboard settings - Auto key action (section Keys and Switch keyboard)
Other: Any easy form to test?

**Comment by afonsoc12** [comment]
I only remember that issue in Authelia (not easy for you to test), but I had the problem before with another website I don´t remember. I'll close for now and let you know if it comes up again
