### ISSUE TITLE
Autofill issues on MIUI (maybe stock Android as well)

### ISSUE THREAD

**Issue by TobiPeterG** [Kunzisoft/KeePassDX#1013]
Hey guys,
I have issues with the autofill functionality of KeePassdx on Android. When I press on the autofill pop-up, just *nothing* happens (it should open the app). But when I unlock my database first and go back to the app and click on the prompt, it lets me choose an entry / fills the fields perfectly fine. 
I'm on the beta branch on the play store, the issue exists since some months now (when I got this phone, don't know, if it worked at some point before). 

Can this issue be confirmed?

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/682
Read the wiki carefully https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill
