### ISSUE TITLE
Magic Keyboard interface

### ISSUE THREAD

**Issue by Civilian-No-001** [Kunzisoft/KeePassDX#1015]
Is it possible to change the interface of the Magic Keyboard?

Increase the height like other input methods, 
add letters to make it more like "input method", 
maybe even add special characters, 
auto dark mode and bottom bar immersion.

When the automatic input is finished, if I want to make a small change to what has been entered, then I need to switch to another keyboard.

Thanks

**Comment by J-Jamet** [comment]
Duplicate as #528 #581 #703 #813

Adding a full keyboard compatible with each language will not bring any added value, only a lot of work and unnecessary maintenance.
Increasing the size of the keyboard just to take up space, I don't see the point.

Switching to another keyboard would be the same if it is internal to the application.
