### ISSUE TITLE
Fingerprint unlock Stuck after App exit

### ISSUE THREAD

**Issue by Jake472829439** [Kunzisoft/KeePassDX#1018]
**Describe the bug**
Sometimes when closing the app keepass DX (pro), the fingerprint unlock appears and i'm Not Able to Close that Window. I have to restart my device.

**To Reproduce**
Happen not on every app exit. Appear to be more often when clicking "Back" Button in a short time multiple times to close the app.

**KeePass Database**
 - Created with: [e.g Windows KeePass 2.xx]

**KeePassDX (please complete the following information):**
 - Version: 2.10.2
 - Language: German

**Android (please complete the following information):**
 - device: Xiaomi Mi 9SE (MIUI 12.0.4 EMEA / Android 10)

**Comment by Jake472829439** [comment]
![Screenshot_2021-06-08-21-47-58-285_com mi android globallauncher](https://user-images.githubusercontent.com/85586033/121252259-14906380-c8a8-11eb-92d3-fd9ec269c62f.jpg)

**Comment by J-Jamet** [comment]
This happens because the system fingerprint dialog is asynchronous and launched when the password screen is displayed. I will try to correct the theoretical async problem.

**Comment by Jake472829439** [comment]
Hi

Thank you for the answer.
It is not that often because I close the app slowlier now ;-)
At other apps there is not that issue, thats why I opened that ticket.

Best regards
Jakob

Jérémy JAMET ***@***.***> schrieb am Mi., 9. Juni 2021, 08:14:

**Comment by J-Jamet** [comment]
Can you tell me if the issue is resolve?

**Comment by Jake472829439** [comment]
Hi

Issue happened not every time, but I can confirm the issue not happened
last few days any more

Jérémy JAMET ***@***.***> schrieb am Sa., 19. Juni 2021,
10:18:

**Comment by J-Jamet** [comment]
OK, because the resolution of this problem seems to create other problems for other users, I will try to condition the resolution so that everyone is happy but maybe I will not be able to, so I will keep you informed of the evolution.

**Comment by Jake472829439** [comment]
I will also Switch from Xiaomi Mi9SE to Google Pixel 5 next week, so maybe
the Problem will be solved for me then automatically 😅

Jérémy JAMET ***@***.***> schrieb am Sa., 19. Juni 2021,
11:12:
