### ISSUE TITLE
Improve Magikeyboard options descriptions

### ISSUE THREAD

**Issue by djibux** [Kunzisoft/KeePassDX#1022]
The [Magikeyboard wiki entry](https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard) is really clear.
I find that in the app, the options descriptions are harder to understand.  I wanted to improve the French translation, but I believe the English strings should be improved as well.

**Describe the solution you'd like**
Examples of strings I would feel clearer:
- "Show input fields in Magikeyboard when viewing an entry" –> "When viewing an entry in KeePassDX, populate Magikeyboard with that entry"
- "Automatically search for shared information to populate the keyboard" –> "When sharing a URL to KeePassDX, filter the entries using that URL domain"

I can provide a PR.

**Comment by J-Jamet** [comment]
Your proposals are much better. You can make a pull request if you want. If I fix bugs before the big 3.0.0 update, it will be integrated in minor versions.
