### ISSUE TITLE
Copy field references are not resolved

### ISSUE THREAD

**Issue by fritut08** [Kunzisoft/KeePassDX#1027]
**Describe the bug**
If an entry A in the database references, for example, the password of another entry B which in turn references the password of an entry C, pasting the password of A does not fully resolve the reference to C but only pastes the reference in entry B, such as {REF:P@I:UUIDOFENTRYC}.

**To Reproduce**
1. Unpack attached zip file.
2. Move database.kdbx to phone.
3. Open database.kdbx in KeePassDX using password **password**.
4. Try pasting the password of Entry A.

[Database.zip](https://github.com/Kunzisoft/KeePassDX/files/6650359/Database.zip)

**Expected behavior**
It should correctly resolve the references and paste the password of Entry C which is **alongpassword**. Instead it will paste the reference of said password **{REF:P@I:3DFB0E9EF0FFA547A115F1E10CF4B911}**.

**KeePass Database**
 - Created with: Windows KeePass 2.48
 - Version: 2
 - Location: anywhere, does not matter
 - Size: 2.29 KB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.10.3
 - Build: Free
 - Language: German

**Android (please complete the following information):**
 - Device: Galaxy S20 FE 5G
 - Version: 11

**Comment by J-Jamet** [comment]
Thanks, I'll look into it.
