### ISSUE TITLE
Biometric access and organization

### ISSUE THREAD

**Issue by Gottarocket** [Kunzisoft/KeePassDX#1030]
After new update I cant login with fingerprint it just freezes when I do so and I need to manually enter password 
Also I had organized all user password under groups which is all messed up now

**Comment by J-Jamet** [comment]
Linked to #1029 

You did not fill out the bug form. I have no context so I can't deduce anything. Please fill out the bug template correctly indicating if you are using a particular file manager, what is your device, the android version and a procedure to reproduce.

**Comment by J-Jamet** [comment]
> Also I had organized all user password under groups which is all messed up now

For that I do not see, I have not changed anything in the display of the groups.

Can you upload a test database that reproduces the problem?

**Comment by J-Jamet** [comment]
Without new precision I close the issue because is solved in #1029.
