### ISSUE TITLE
Program forgot everything

### ISSUE THREAD

**Issue by akovia** [Kunzisoft/KeePassDX#1042]
**Describe the bug**
Program has been working perfectly for nearly 2 months now. I went to log into my amazon though my browser using the magikeyboard and it states that it lost it's link. **"Access to the file revoked by the file manager"**

I read the wiki and opened my DB again from within GDrive. Only now when I try to log into amazon, there is no option to auto fill the password any longer.

**To Reproduce**
1. Setup and use the program for a month or two
2. Wait for it to forget the DB link
3. Try to re-establish the link
4. Try to log into a website that was previously configured

**Expected behavior**
Be prompted to auto-fill PW when logging into websites

**KeePass Database**
 - Created with: ?
 - Version: KeePass 2 KDBX4.0
 - Location: Remote file retrieved with GDrive app
 - Size: 85KB
 - Contains attachment: I think so

**KeePassDX (please complete the following information):**
 - Version: 2.10.5 
 - Build: Pro
 - Language: English

**Android (please complete the following information):**
 - Device: GalaxyS20
 - Version: 11

**Additional context**
 - Browser for Autofill: Brave 1.26.74

So I've read the wiki about re-linking and I know I've selected the same DB, but it's like I'm starting from scratch again. Is this the expected behavior? If this is how it works, it doesn't seem worth the trouble. I guess I just need to copy and paste from now on?

**Comment by J-Jamet** [comment]
> Only now when I try to log into amazon, there is no option to auto fill the password any longer.

There can be two reasons for this, either your database no longer contains the url or applicationId metadata linked to your form. Or it is a problem with the autofill service of your device.

In the first case, check that you are not using an old version of your database. Google Drive has a known bug that does not synchronize the file cache and keeps an old version. You have to empty the Google Drive application's cache in this case.

In the second case, it is possible that autofill is temporarily unavailable on your device or that the application with the form has changed its behavior.

> So I've read the wiki about re-linking and I know I've selected the same DB, but it's like I'm starting from scratch again. Is this the expected behavior?

Clearly not, but I can't force a third party app to provide the right data.

> If this is how it works, it doesn't seem worth the trouble. I guess I just need to copy and paste from now on?

Copy / Paste what? You can use the Magikeyboard when the autofill is no longer available.

**Comment by akovia** [comment]
Thanks for the swift reply. I was in a bit of a panic when this happened as I was in a time crunch and of course nothing worked. 

It seems clearing the cache did the trick. I tried another website it had memorized from before and it prompted me this time. Might consider adding this nugget to the wiki. 

Is there a **best** configuration with any cloud service to ensure this doesn't happen? Or is there no way around the inevitable loss of connection to the DB files? I'm using GDrive as you saw, but I would use something else if I didn't have to worry about this again.

Thanks again!

**Comment by J-Jamet** [comment]
> Is there a best configuration with any cloud service to ensure this doesn't happen? Or is there no way around the inevitable loss of connection to the DB files?

Maybe, I didn't test everything on third party apps. Eventually there will be a file manager made for it but I have to finish KeePassDX already.
