### ISSUE TITLE
Add subdomain-search to autofill-wikientry

### ISSUE THREAD

**Issue by newhinton** [Kunzisoft/KeePassDX#1044]
**Is your feature request related to a problem? Please describe.**
I had problems with autofill where it would not deliver the proper entries.
This was due to me having multiple credentials for a tld. I could not find why this was the case, until i found #728 which said my usecase was already implemented, and #647 which hinted at the subdomain setting.

**Describe the solution you'd like**
I think it would be a great idea to add this functionality to the wikientry for autofilling, or link from autofilling to an approriate article so that users with this issue will find it more easily

**Describe alternatives you've considered**
Make the setting enabled by default or add a "more" button to the resultlist

**Comment by J-Jamet** [comment]
Added to the magikeyboard and autofill wiki, the option is not enabled by default because it parses a list to differentiate subdomains, which can lower search performance.
