### ISSUE TITLE
Cannot block Autofill, if popup window does not have package name but "PopupWindow:[7letters/digits]"

### ISSUE THREAD

**Issue by bege10** [Kunzisoft/KeePassDX#1046]
**Describe the bug**
In the search window of the app "3C All-in-one Toolbox" (ccc71.at.free, Play Store or Aurora Store) the title of the autofill popup often shows instead of the package name "PopupWindow:[7letters/digits]". This cannot be entered into the block list and thus the popup often appears inappropriately.

**To Reproduce**
1. Open 3C Toolbox > App Manager
2. Click on search button
3. Either the autofill popup does not appear because the package is in black list, or - more often - the popup shows up with the described title.

**Expected behavior**
No autofill popup in this app.

**KeePass Database**
 - Created with: Windows KeePass 2.48.1 64 bit
 - Version: [e.g. 2]
 - Location: external SD card
 - Size: 770 kB
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 2.10.5
 - Build: libre
 - Language: German

**Android (please complete the following information):**
 - Device: Fairphone 3
 - Version: /e/OS (based on FairphoneOS, LineageOS for microG, Android 10)

**Additional context**
If I choose Keepass2Android as autofill service the autofill popup does not appear.

**Comment by J-Jamet** [comment]
If you test the new beta 3.0.0 of the playstore, the problem should not occur anymore. Can you confirm?

**Comment by bege10** [comment]
I have the app installed from F-Droid. After updating to 3.0.0_beta02 the problem remains. Is the Play Store version different?

**Comment by J-Jamet** [comment]
The stable version 3.0.0 is released on the store and in the repo.

**Comment by bege10** [comment]
Yes, 3.0.0 fixes the issue. Thank you very much!
