### ISSUE TITLE
Database creation offers a dropdown selection for only one option

### ISSUE THREAD

**Issue by PacoBell** [Kunzisoft/KeePassDX#105]
Upon database creation, there appears to be an option to select alternate database formats, but you only currently show ".kdbx". Is this in preparation for additional database formats? Otherwise, it's a useless and confusing option and should be eliminated.

**Comment by J-Jamet** [comment]
It was just to be generic, because before we could create .kdb files. I don't know if in the future it will be files with other extensions. But I can delete the selection visually

**Comment by J-Jamet** [comment]
Fixed in version 2.5.0.0beta11
