### ISSUE TITLE
KeePassDX cannot open the database normally for input

### ISSUE THREAD

**Issue by Gloryandel** [Kunzisoft/KeePassDX#1050]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**KeePass Database**
 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android (please complete the following information):**
 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]
After the latest version is updated, the input is different from the previous version, and the previous version can be input without opening the database. If you open the database manually, you might as well enter the account and password manually.

**Comment by J-Jamet** [comment]
Your issue is incomprehensible, please fill in the template correctly and explain step by step what your problem is by indicating precisely the tools and versions used.
