### ISSUE TITLE
Copy TOTP to clipboard when autofilling username/password

### ISSUE THREAD

**Issue by dfunkt** [Kunzisoft/KeePassDX#1053]
**Is your feature request related to a problem? Please describe.**
When autofilling info using the keyboard inline method on a site/app you always have to go back to the KeepassDX app in order to copy the TOTP which creates extra friction.

**Describe the solution you'd like**
Copy TOTP to clipboard when autofilling username/password when using the keyboard inline method.

**Additional context**
This is the way Bitwarden and 1Password seem to do it, at least on Android.

**Comment by J-Jamet** [comment]
Duplicate #912 , linked #553
