### ISSUE TITLE
Not possible to save entry after orientation change

### ISSUE THREAD

**Issue by uduerholz** [Kunzisoft/KeePassDX#1057]
With the current development branch the save button for a new entry seems to have no associated action
after rotating the entry edit view from portrait to landscape orientation and back again.

**KeePassDX **
 - Version: 3.0.0 (branch "develop")
 - Build: Free

**Android **
 - Device: Fairphone 3
 - Version: Android 10

**Comment by J-Jamet** [comment]
Thanks, I'll fix that.
