### ISSUE TITLE
Support for setting-up TOTP using built-in QR Code scanner

### ISSUE THREAD

**Issue by Lumenbolt** [Kunzisoft/KeePassDX#1059]
**Is your feature request related to a problem? Please describe.**
I think it'd be great to have a QR Code scanner to set up TOTP for an entry alongside typing down the TOTP code (Helpful when I have the code displayed on another machine)
_Keepass2Android_ has implemented this via a plugin available in Play Store.

**Describe the solution you'd like**
To have an option to scan TOTP QR Code while setting it up for an entry.

**Describe alternatives you've considered**
Copy the `otpauth://totp/.... ` code from a third-party QR Code scanner and add it on the entry as an attribute with _otp_ as its name.

**Comment by J-Jamet** [comment]
The subject has already been addressed and it will not be implemented a QR reader while it is enough to download a compatible application to properly delineate the recognition tasks of future formats.

The recognition of link sharing without copying from a dedicated application is implemented and should work.
https://github.com/Kunzisoft/KeePassDX/wiki/OTP#qr-code

Linked to https://github.com/Kunzisoft/KeePassDX/issues/729 #893 #434
Duplicate #556
