### ISSUE TITLE
Doesn't work with Yandex.Key?

### ISSUE THREAD

**Issue by li568265102** [Kunzisoft/KeePassDX#1061]
The Yandex.Key OTP displayed by KeePassDX is 8 digits, which should be 8 letters.
Somebody created KeeYaOtp plugin for Yandex.Key: https://github.com/norblik/KeeYaOtp
KeePassOTP also used his code：https://github.com/Rookiestyle/KeePassOTP
Can you use code from KeeYaOtp and add it to KeePassDX?it will be nice.

**Comment by J-Jamet** [comment]
Duplicate #785

Implementing proprietary formats has never been part of my philosophy. If you really want me to do it, I can give you a quote.
