### ISSUE TITLE
Not always possible to save form data

### ISSUE THREAD

**Issue by uduerholz** [Kunzisoft/KeePassDX#1064]
With the current development branch it seems that it is not possible to save new form data entered by the user. 
When the autofill framework asks to save the data and the user confirms, a toast is shown claiming that the 
database is only readable, even if is was opened writable.

**KeePassDX**
Version: 3.0.0 (branch "develop")
Build: Free

**Android**
Device: Fairphone 3
Version: Android 10

**Comment by J-Jamet** [comment]
Thanks, I didn't see the problem, it came from the check that was done before the service delivered the database.

Refactoring to deliver the database exclusively through the service was necessary but can cause this kind of bug.
