### ISSUE TITLE
SecurityException: Permission Denial

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1066]
From #1065 

I can't re-open my databases, only at the first time.

I thought it was an Android permission problem (I have had my databases stored in the internal memory of the phone), but even moving them to the SD memory the error persists.

![java.lang SecurityException: Permission Denial](https://user-images.githubusercontent.com/1930100/131277823-5a04c994-611b-4faa-ab2a-2df3be98ee0b.png)

`java.lang SecurityException: Permission Denial`

My phone: HONOR 10 Lite running Android 10 (EMUI 10.0).
KeePassDX_3.0.0_beta01

Default Android's file manager.

When I open the database the first time in the app. But I've realized this: having the database and key file registered, I have to re-associate the key file without having to re-enter the database password, every time I have to open the database.

**Comment by J-Jamet** [comment]
The issue is present because non-permanent URIs are now unbound from the file manager and only database URIs are considered persistent URIs. Not requiring the unbinding of saved key file URIs should solve the problem.

For those who test the beta, you must reselect your key file at each unlock.

**Comment by Bob-465** [comment]
I reported the same problem last night. I also found the solution. The problem lies in using the key file. Reselecting the key file currently solves the problem.

**Comment by J-Jamet** [comment]
Version 3.0.0_beta02 fix this issue.
