### ISSUE TITLE
Layout not as expected with Android 8.1

### ISSUE THREAD

**Issue by uduerholz** [Kunzisoft/KeePassDX#1068]
With the current development branch the layout shown is "missing" the background in some parts.

**KeePassDX**
Version: 3.0.0_beta2 (branch "develop")
Build: Free

**Android**
Device: Emulator, Nexus 5 (API 27)
Version: 8.1

![screenshot01](https://user-images.githubusercontent.com/81411344/131334617-a70c7ef9-563b-4d0a-8fa4-98768651a371.png)![screenshot02](https://user-images.githubusercontent.com/81411344/131334656-bf8a0252-9816-495c-858c-1cbd08746f88.png)![screenshot03](https://user-images.githubusercontent.com/81411344/131334669-2ef14a72-36eb-4084-a855-065b29be4076.png)

**Comment by J-Jamet** [comment]
This is a known problem and I don't have a solution for it. It happens only for Android version 8 for the first launch. If the application is killed and reopened, the problem does not happen anymore.
Duplicate #509
