### ISSUE TITLE
Java.lang.SecurityExpaction permission denia

### ISSUE THREAD

**Issue by maximustheone** [Kunzisoft/KeePassDX#1071]
Since Version 3.0.0 beta01
The automatic fingerprint log in is faulty because i guess the key file path when using the fingerprint quick login
Looks different to the normal keyfile path.
As example something like /document/primary/folder/keyfile... but it schould be
keyfile....

When trying to open the database by Fingerprint biometric then it says:
Java.lang.SecurityExpaction permission denial : read....

and wount open the database.

This just happens right after the update to the 3.0.0 beta01 version.
The database opens by re-chose the real keyfile location,tho.

Cheers
maximus

**Comment by J-Jamet** [comment]
Thank you. The problem has already been fixed in version 3.0.0_beta02.

Duplicate #1066 #1067

**Comment by maximustheone** [comment]
Oh thank you.

**Comment by boggle247** [comment]
Awesome! Thanks for the fix. I just noticed this as my device updated to the beta01. Thanks for jumping on this so quickly
