### ISSUE TITLE
Autofill button does not work

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1072]
**Describe the bug**
When the application is no longer in use, clicking on the autofill button does nothing.
The behavior returns to normal when the application is launched from its icon.

**KeePass Database**
 - 3.0.0_beta03

The problem is to reproduce the behavior for debugging, if someone has a procedure to reproduce the problem every time. Please write it in comment! :)

**Comment by uduerholz** [comment]
Can you give some more details? ;-)

**Comment by J-Jamet** [comment]
Actually not much.
Android 11 emulator with Play Store, development build at 3.0.0_beta03 tag.
I was doing tests, everything was OK, then I did something else. And back on the computer, when I wanted to test a form with the autofill, the click on the button "Sign in with KeePassDX" did nothing (but there was visual feedback on the button so the event was well captured.)
I simply tapped the KeePassDX application icon again, switched back to the form, and it worked.
So maybe it's a problem in the PendingIntent, or the state of the database or just a bug in my system.

**Comment by uduerholz** [comment]
So, the form was still open? Then I would guess it was simply a timeout from the autofill framework.

**Comment by J-Jamet** [comment]
Yes, you may be right. But I find this behavior very confusing, the view should disappear?

**Comment by J-Jamet** [comment]
I close the issue, if someone else has the problem I will reopen it. (Thanks for your answer ;))
