### ISSUE TITLE
Scrolling inside notes

### ISSUE THREAD

**Issue by bushrang3r** [Kunzisoft/KeePassDX#1073]
**Describe the bug**
Can no longer scroll inside the notes section when viewing or editing. 

**To Reproduce**
1. View a saved item that has long form text entered in the notes section. 
2. Cannot scroll down to see entire note.
3. The same thing happens when trying to edit the note.

**Expected behavior**
Scroll down within the notes section when viewing and editing notes.

**KeePass Database**
 - Created with: Android
 - Version: KeePass 2 - KDBX3.1
 - Location: Local on device
 - Size: 21kb
 - Contains attachment: No

**KeePassDX:**
 - Version: 3.0.0_beta01
 - Build: Free
 - Language: English

**Android:**
 - Device: Redmi NOTE 8 Pro
 - Version: 11

**Comment by J-Jamet** [comment]
I completely rebuilt the view system dynamically with templates.
There is now a limit of 40 lines, I'll see if I can add a scroll inside the edit text.

**Comment by bushrang3r** [comment]
Ok, thank you.
I hope you can, because I can't see all of my notes anymore. I could re-install the old version if necessary.

**Comment by bushrang3r** [comment]
Thank you J-Jamet sir!
Looking forward to the next release 😊

**Comment by bushrang3r** [comment]
I installed 3.0.0 and scrolling notes is possible when viewing, but when editing, scrolling down is only possible by pulling the cursor down. Would it be possible to remove the line limit when editing too?
