### ISSUE TITLE
Magikeyboard "Clear at closing" + "Entry selection" causes app to lock while in use

### ISSUE THREAD

**Issue by chenxiaolong** [Kunzisoft/KeePassDX#1075]
**Describe the bug**

In the Magikeyboard settings, when the "Clear at closing" and "Entry selection" options are enabled, the app will lock 30 seconds after opening an entry (when the magikeyboard notification disappears).

**To Reproduce**
1. Go to Magikeyboard settings and enable "Clear at closing" and "Entry selection"
2. Unlock a database
3. Tap on any entry
4. The database locks after 30 seconds (magikeyboard timeout)

**Expected behavior**

It took a while for me to figure out why the app was locking while it was in use. Tapping the screen does not extend the timer.

I think it could potentially be a bit more user friendly with one of these options?
* Change Magikeyboard entry selection to happen when app moves to the background instead of when an entry is opened
* Change Magikeyboard timer to not begin while the app is in the foreground

**KeePass Database**
 - Created with: KeePassXC
 - Version: 2.6.6
 - Location: Local file (synced via Syncthing)
 - Size: 95KiB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Versions:
   - 2.10.5 (Pro from Play Store)
   - 3.0.0beta3 (Pro from Play Store)
   - cc3204453e971d452d8b448dfd5fd79946fa3948 (compiled from source)
 - Language: English

**Android (please complete the following information):**
 - Device:
   - Samsung Galaxy S21 Ultra
   - Samsung Galaxy Tab S7+
 - Version: Android 11 on both devices

**Comment by J-Jamet** [comment]
This is not a bug, it is the normal operation of these options when enabled.

If the expected behavior is to understand the operation, perhaps the setting description should simply be rephrased.

> Change Magikeyboard entry selection to happen when app moves to the background instead of when an entry is opened
> Change Magikeyboard timer to not begin while the app is in the foreground

Background and foreground has nothing to do with filling the keyboard with an entry. Disable the setting "Settings - Magikeyboard settings - Entry selection"  if you don't want the Magikeyboard to be populated automatically with the entry you are viewing.

**Comment by chenxiaolong** [comment]
Thanks for the quick reply!

> If the expected behavior is to understand the operation, perhaps the setting description should simply be rephrased.

That seems reasonable to me if the current behavior is intended.

> if you don't want the Magikeyboard to be populated automatically with the entry you are viewing.

For my use case, I was expecting Magikeyboard to be populated with the entry I was viewing, but I didn't expect that the main app would be locked as a side effect of the Magikeyboard timeout while I was still in the app. (As an example of my use case, from the main app, I opened the entry I wanted to be populated in the keyboard, but spent a little too long reading the notes section.)

**Comment by J-Jamet** [comment]
> That seems reasonable to me if the current behavior is intended.

Since you didn't understand the sentences, what proposal would you make?

> For my use case, I was expecting Magikeyboard to be populated with the entry I was viewing, but I didn't expect that the main app would be locked as a side effect of the Magikeyboard timeout while I was still in the app. (As an example of my use case, from the main app, I opened the entry I wanted to be populated in the keyboard, but spent a little too long reading the notes section.)

In this case, why do you activate the Magikeyboard timeout?

**Comment by chenxiaolong** [comment]
> In this case, why do you activate the Magikeyboard timeout?

That's a very good point I didn't consider. I can just rely the main app timeout.

I though about the setting descriptions a bit and I can't think of a good way to reword it while keeping it brief. Would you consider adding a small section to the FAQ wiki page instead? Maybe something like:

Q: Why did the app lock before the timeout duration has elapsed?
A: If `Settings → Form filling → Magikeyboard settings → Entry selection` and `Settings → Form filling → Magikeyboard settings → Timeout` are both enabled, the opening an entry will load it into magikeyboard and begin the magikeyboard timeout for clearing the entry. Once the magikeyboard timeout has elapsed, the database will be locked, which may happen sooner than the main app timeout set in `Settings -> App settings -> Timeout`.

**Comment by J-Jamet** [comment]
Done : https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-did-the-app-lock-before-the-timeout-duration-has-elapsed
