### ISSUE TITLE
Options for links

### ISSUE THREAD

**Issue by exoticflower85** [Kunzisoft/KeePassDX#1082]
Please make it so that links don't open right away when you tap on them but rather show a menu with options like Open, Copy, etc. Sometimes I need to open a link in a different browser and, at least on my phone, it never works the first time.

**Comment by J-Jamet** [comment]
The KeePassDX application is not responsible for the intent requests used for URLs on your device.
The URLs must be opened with a browser configured by default on your device. You just have to change this configuration.
It is possible to copy the URL by doing a long click to display the contextual menu for text selection.

**Comment by exoticflower85** [comment]
> It is possible to copy the URL by doing a long click to display the contextual menu for text selection.

It is possible. But look how it behaves when you do it

https://user-images.githubusercontent.com/13087157/132300772-36a60953-141b-44a0-bfcb-f42aac8fbef9.mp4

**Comment by J-Jamet** [comment]
If the contextual menu of your device does not suit you, just use the copy button next to the text. That's what it's for.

**Comment by exoticflower85** [comment]
There's no such button next to links

**Comment by J-Jamet** [comment]
OK, the button has been added in version 3.0.0. The stable version will be released in a few days, so your problem will be solved with this version. Please indicate the version number and the context of your application when you open an issue ;)
