### ISSUE TITLE
Spacing between list items and bold text

### ISSUE THREAD

**Issue by Thndr** [Kunzisoft/KeePassDX#1085]
**Describe the bug**
The position of items in the list do not change no matter the size of the list items, this makes smaller list item sizes not compact and looks odd with large spacing between items.

**To Reproduce**
1) Change list item size
2) Observe the icons and text get smaller, but the item location stays the same causing spacing between items to increase

**Expected behavior**
Icons and text gets smaller, and items compact based on size

**KeePassDX (please complete the following information):**
 - Version: 3.0 b2
 - Build: Fdroid
 - Language: English

**Comment by rogers1106** [comment]
Then bold font should also be optional. For me it's harder to read.

**Comment by J-Jamet** [comment]
For small item margin, okay, because it's a historical option. (And I could delete it because it is boring to maintain)

But I'm definitively not going to add a setting for bold text, the first time I've heard that it makes text hard to read...

**Comment by rogers1106** [comment]
Ok, but the new bold text looks (sorry) old-school. I will most probably get used to it. 😀

**Comment by J-Jamet** [comment]
The best is to ask the community, this is the setting I do not want to put (because there is no need for it), not choose the best solution.
Who prefers bold in list entries? (poll :+1: / :-1: )

**Comment by Thndr** [comment]
@J-Jamet I'm unsure if before 3.0 I was using the item size feature to make the listing compact, but I assumed the spacing between items would adjust based off from size as it does with multiple other programs.

My main issue is the fact after upgrading to 3.0 the list of items are not as compact as it was before I upgraded. Even with the Large list item setting in 2.10 it lists 15 items and medium and small would list more, while 3.0 only lists 13 no matter the size.

If the solution to this is to have a default item size and then the UI has a zoom level rather than different spacing based off from item size then that could possibly work.

**Comment by J-Jamet** [comment]
This also allows to respect the google requirements for the size of clickable elements and allows a better visibility.
Why is the number of elements displayed simultaneously on the screen so important to you?
