### ISSUE TITLE
Unable to search entries on sub-groups

### ISSUE THREAD

**Issue by Generator** [Kunzisoft/KeePassDX#1090]
**Describe the bug**
With KeePassDX 3.0 certain sub-groups doesn't show on search.

**Example:**
- Root:
  - GroupA
    - GroupA.1
      - Entry1
      - Entry2
      - Entry3
    - GroupA.2
      -  Entry1
      - ...
    - GroupA.3
      -  Entry1
      - ...
  -  GroupB
     - Entry1
     - ...
  - GroupC
    - Entry1
    - ...

Entries from GroupA and his sub-groups don't show on search.

**Expected behavior**
With KeePassDX <3.0 there's no issue with search

**KeePass Database**
 - Created with: Linux KeePass2
 - Version: KeePass2 - KDBX 4.0
 - Location: Local/Device
 - Size: 1.1MB
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 3.0
 - Build: Free (Google Play)
 - Language: Portuguese

**Android:**
 - Device: Xiaomi Redmi Note 8T
 - Version: Android 11 (AOSP)

**Comment by J-Jamet** [comment]
I just tested by doing an architecture as you indicate and I have no problem. Can you upload a test database that reproduces the issue?

**Comment by Generator** [comment]
I've tried to recreate de issue with a new database with older version of KeePass2 (2.14), but without success.  

GroupA (and his sub-groups) contain 97% of all entries, only websites, that group was one of the fisrt created with an older version of KeePass2, and later upgraded to KDBX4/Argon2.

However i've found something, on current database, i've created a new group, and move the entries from GroupA  (not sub-groups) to the new group, and now the search works with all entries.  
The issue is probably with some entry, i'll try moving one by to back to GroupA and find which one is causing the issue.

**Comment by J-Jamet** [comment]
OK, so it must be a formatting or metadata problem. Try to export your database in XML and then re-import it with KeePass2. This allows you to rebuild a database from scratch and do a clean formatting.

**Comment by Generator** [comment]
The issue with my db i already fixed creating another group and move all subgroups and entries to new group.

Just can't replicate the issue with other db.

You can close this issue if you want. If i replicate the issue with a sample db ill post it here.
