### ISSUE TITLE
Can't Load Database

### ISSUE THREAD

**Issue by BigNdets** [Kunzisoft/KeePassDX#1094]
I can't open my database. I get the following error message: "could not load your database java.lang.NegativeArraySizeException: -1"

My setup:
OS: Android 10.
Keepassdx version: 3.0.0_beta02 
KeePassdx build: Libre
Security: Secured with password and keyfile(stored in my device local storage).
File manager: System Default

**Comment by IsaacDLS** [comment]
You have to click the Keyfile button, below the Password. Then select your keyfile. It seems there is some funky bug in regards to  file paths

**Comment by J-Jamet** [comment]
The problem seems to come from your database. But have you tried reselecting your database and key files?
Is the problem reproducible with version 2.10.5 of the application or with a backup of your database?

**Comment by J-Jamet** [comment]
Have you tried to open and save your database with a non-open source application from the store? I had this error once in this case, to see if your database is corrupted, try to open it with KeePass2 on PC.

**Comment by IsaacDLS** [comment]
> The problem seems to come from your database. But have you tried reselecting your database and key files?
> Is the problem reproducible with version 2.10.5 of the application or with a backup of your database?

Reselecting the keyfile works. The problem exists on 3.0.0 beta2 and beta3.

I haven't tried it on 2.10.5.

**Comment by J-Jamet** [comment]
OK, so it's the same problem already solved.
#1066 #1067 #1071
