### ISSUE TITLE
line separators and sparse layout

### ISSUE THREAD

**Issue by droopy4096** [Kunzisoft/KeePassDX#1095]
**Is your feature request related to a problem? Please describe.**
With latest update entry list layout became "sparse" with addition of line separators and extra spacing between entries. This causes more scrolling and generally poorer management of screen real estate for people that are used to more dense presentation.

**Describe the solution you'd like**
An option to choose between old "dense" and "sparse" layouts would go a long way to accomodate those who struggle with dense layouts and those who prefer them.

**Describe alternatives you've considered**
reducing font size doesn't help as font size at present is the one I'd prefer but spacing makes things less usable.

**Additional context**
None

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1085
