### ISSUE TITLE
Update Argon2 default parameter to RFC recommended values

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#1098]
[RFC 9106](https://www.ietf.org/rfc/rfc9106.html#name-parameter-choice), which describes Argon2 published a few days ago, recommends Argon2id, 3 iterations, 4 lanes, 64 MiB of RAM as a uniformly safe option when the available memory is limited. 
Argon2id probably shouldn't be the default for compatibility with other KeePass clients, but the three parameters of Argon2 could be adopted.

Off-topic, I noticed that the spec specifies the amount of memory as integer number of kibibytes from 8*p to 2^(32)-1. It's strange that KeePass allows you to enter this value in bytes. Maybe Dominik misread kibibytes as bytes.

**Comment by J-Jamet** [comment]
I tried on my Galaxy S (i9000) with the settings you indicate and the save takes 23 seconds. That's too long, so I decreased the memory to 16 MiB and the save takes 4 seconds.

So I change the default settings to : 

Iterations : 2 -> 3
Memory : 1 MiB -> 16 MiB
Parallelism : 2 -> 4

**Comment by J-Jamet** [comment]
> Off-topic, I noticed that the spec specifies the amount of memory as integer number of kibibytes from 8*p to 2^(32)-1. It's strange that KeePass allows you to enter this value in bytes. Maybe Dominik misread kibibytes as bytes.

Yes, it may be a mistake, but it doesn't matter if the algorithm is executed correctly.
