### ISSUE TITLE
Could Not Load Your Database

### ISSUE THREAD

**Issue by Bantul-the-great** [Kunzisoft/KeePassDX#1099]
**### _Issue:_**
After deleting a database file/instance from the KeepassDX homepage, other kdbx files are not opening. It shows an error message - "Could not load your database. java.lang.securityexception:Permission Denial:reading com.android.externalstorage. External Storage Provider uri content://com.android.external storage.docu........."

### **_Steps:_**
1. 'Open' KeppassDX.
2. Supoose 3/4 databases files are listed there.. Tap on the right drop down arrow on any of the files. Tap on 'Delete' icon. After it disappears, you become unable to open any other files listed out there... 
3. When you tap on any file, it asks for the credentials(password or fingerprint alongwith the keyfile). After filling up tap on 'OPEN'.
4. The above-quoted error message appears for 3/4 seconds..

### **_My Experience:_**
I have cleared the recent tasks, cleared the cache of the KeepassDX app, then rebooted the phone. No way to fix.
At last I cleared both the app cache and data and configured it again as before.. It started working fine again as usual... But again whenever I repeat the delete operation for any file, the other files become unable to open...

### **_KeepassDX:_**
Version::3.0.0_beta03
Source::F-Droid
Language::English

### **_Android:_**
Redmi note 7s
Everything updated.

![IMG_20210912_121325](https://user-images.githubusercontent.com/88554859/132976842-f0ff7569-9311-426b-b725-e825f19a3f26.jpg)
![IMG_20210912_121359](https://user-images.githubusercontent.com/88554859/132976845-3c917e38-b3dc-4716-b7fe-4da882a3357a.jpg)
![IMG_20210912_121451](https://user-images.githubusercontent.com/88554859/132976847-83b2d104-c756-4627-a126-e25d899888ae.jpg)

**Comment by J-Jamet** [comment]
Reselect the key files.

Duplicate #1066 #1067 #1071 #1094
