### ISSUE TITLE
Upstream update

### ISSUE THREAD

**Issue by Dionis0s** [Kunzisoft/KeePassDX#11]
Please update to v2.2.0.8

https://github.com/bpellin/keepassdroid/blob/HEAD/CHANGELOG

Thank you! Nice job!! :) 👍

**Comment by J-Jamet** [comment]
It's already done in branch https://github.com/Kunzisoft/KeePassDX/tree/upstream-update, 
I have to finish the other features and make the merges for the release of the beta. ;)

**Comment by J-Jamet** [comment]
Upstream merge done for 2.2.0.9

**Comment by J-Jamet** [comment]
Keepassdroid 2.2.0.9 commits are in Keepass DX 2.0.0.5beta3 now! ;)

**Comment by gerardo-junior** [comment]
#14
