### ISSUE TITLE
Magikeyboard - URL Button not working

### ISSUE THREAD

**Issue by giwrgosmant** [Kunzisoft/KeePassDX#1100]
**Describe the bug**
Magikeyboard URL button of an entry doesn't work.

**To Reproduce**
1. Open one browser.
2. Switch to Magikeyabord and click the button to open the database.
3. Choose an entry you want and now click the URL button on Magikeyboard.
4. Nothing happens.

**Expected behavior**
It should copy the URL on the browser.

**KeePassDX (please complete the following information):**
 - Version: 3.0.0
 - Language: Greek

**Android (please complete the following information):**
 - Device: POCO F1
 - Version: Android 11 - Pixel Experience OS

**Additional context**
The issue tested with Brave Browser and Chrome Browser.
Check the screenshot below:
![KeePassDX Issue - URL Button](https://user-images.githubusercontent.com/51835189/132989941-9cec6012-ee21-4cc8-b83d-642d240dc5b0.png)

**Comment by J-Jamet** [comment]
Just check and it works fine.
Are you sure that the entry you select in the Magikeyboard has a non-empty URL field?

**Comment by giwrgosmant** [comment]
> 
> 
> Just check and it works fine.
> Are you sure that the entry you select in the Magikeyboard has a non-empty URL field?

Yes the entry doesn't have any empty in URL field. I just tried in my old device Galaxy S4 running LineageOS 18.1 at Bromite Browser with a test database I just created. Same thing happing, I press it and nothing,
Check screen record video [here](https://mega.nz/file/7o8mhAKL#R73INCEgL9Edqqz-szS732cPzF49pnHEaC0i4UfAWxA).

**Comment by J-Jamet** [comment]
OK, I see what's wrong.
You have the `Settings - Magikeyboard settings - Auto Key Action` option enabled and when the content is copied to the URL field in your browser, running the action command in this case deletes the content of the field.
It should work if you disable this option.
I will try to remove the action for the URL field when the setting is enabled.

**Comment by giwrgosmant** [comment]
> 
> 
> OK, I see what's wrong.
> You have the `Settings - Magikeyboard settings - Auto Key Action` option enabled and when the content is copied to the URL field in your browser, running the action command in this case deletes the content of the field.
> It should work if you disable this option.
> I will try to remove the action for the URL field when the setting is enabled.

You are right! thanks! 👍 However since this option (auto key action) is useful, there is no way to make it work like copy the URL and then go, instead of just copy? Not a big a deal tho if it's not possible.

**Comment by J-Jamet** [comment]
It should already be behaving like this. Because the action is determined by the field itself, but it seems that in the browser you are using, the action is just not the Go action (or maybe it's a security I don't know). So the easiest way is to disable it for this element.

**Comment by giwrgosmant** [comment]
> It should already be behaving like this. Because the action is determined by the field itself, but it seems that in the browser you are using, the action is just not the Go action (or maybe it's a security I don't know). So the easiest way is to disable it for this element.

I tried on Brave, Bromite and Chrome. So basically in any chromium browser the behave is same 😝
If there is a way to make it work like it should, would be awesome but if too much headache then it's fine to just disable for this element. Not a big deal. 🙃
Thanks!

**Comment by J-Jamet** [comment]
There is a bug because a method has been interchanged, the bug will be fixed for the next version.
