### ISSUE TITLE
Database closing even after no time off

### ISSUE THREAD

**Issue by Thewisem** [Kunzisoft/KeePassDX#1101]
**Describe the bug**
The database is closing even though I have disabled time off
**To Reproduce**
1. Go to Keepass
2. Click on an entry
3. Go outside the app
4. Wwit for some time

**Expected behavior**
To not close because I disabled it.
**KeePass Database**
 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app] SD card
 - Size: [e.g. 150Mo] 700kb
 - Contains attachment: [e.g. Yes] no

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta23] 3.0.0
 - Build: [e.g. Free] free
 - Language: [e.g. French] English

**Android (please complete the following information):**
 - Device: [e.g. GalaxyS8] Samsung Galaxy Tab A
 - Version: [e.g. 8.1] 7.1.1 Nougat

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]
![Screenshot_20210912-171659_1_1](https://user-images.githubusercontent.com/74511929/132991501-7b65ddf1-9789-40f1-a8bf-655afd7e9711.jpg)

**Comment by J-Jamet** [comment]
The different timeouts of the application, the clipboard and the magikeyboard have been checked and tested.
Please be more precise about the nature of your problem with the settings activated, which timeout is activated without being enables in the settings? You are not specific enough about the issue. 

https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-did-the-app-lock-before-the-timeout-duration-has-elapsed

You may have enabled timeout settings.
I just checked and I don't see any bug. I close the issue
