### ISSUE TITLE
Shows old deleted .kdbx files

### ISSUE THREAD

**Issue by Aaxiruz** [Kunzisoft/KeePassDX#1103]
**Describe the bug**
When I go to open existing database it shows me old deleted .kdbx files which confuses me

**To Reproduce**
1. Go to 'Open existing database'

**Expected behavior**
To show just the one I use and have not deleted.

**KeePassDX (please complete the following information):**
 - Version: [Latest]
 - Build: [Free]
 - Language: [English]

**Android (please complete the following information):**
 - Device: [Oppo A31]
 - Version: [9]

**Comment by Aaxiruz** [comment]
![Screenshot_2021-09-13-13-26-55-67.jpg](https://user-images.githubusercontent.com/69917330/133046788-8dbc7e57-875e-477e-a2c3-358ae56049e2.jpg)

**Comment by J-Jamet** [comment]
The application you took in screenshot is not KeePassDX.

You can see it because it doesn't even correspond to a proposed theme.
It is the File application of your device, so it is this application that has this behavior.
