### ISSUE TITLE
Inactivit Timer does reset itself to 0.0.0.0 after opening the dialog some times

### ISSUE THREAD

**Issue by kraoli** [Kunzisoft/KeePassDX#1107]
**Describe the bug**
Inactivity Timer does lose it value and reset to zero after opening it some times. 

**To Reproduce**
1. Go to Settings
2. Click on "Inactivity Time" (sorry, can't enable the english version to use the exact wording)
3. Set e.g. 1 min
4. Click ok
5. open it again
6. Click ok
7. open it again
8. result: the timer is reset to zero

**Expected behavior**
The timer should not reset itself and should keep the setting, regardless how often you open it. 

KeePass Database

    Created with: [keepass DX pro]
    Location: [local]
    Size: [2]
    Contains attachment: [no]

KeePassDX (please complete the following information):

    Version: [3.0.0]
    Build: [pro]
    Language: [german]

Android (please complete the following information):

    Device: Samsung a52
    Version: [11]

**Comment by J-Jamet** [comment]
I have to retest but there is no reason for a timer to drop to 0 if it is activated. On the other hand it is well reset to 0 if you disable the feature, which is normal since the value is not stored anymore if you disable the setting.

**Comment by J-Jamet** [comment]
Indeed I have just tested it is a bug, I will correct it for the next version.

**Comment by kraoli** [comment]
Wow that fast a quick handling of the issue, many thanks! :)
