### ISSUE TITLE
Inactivity Timer to lock database doesn't work reliable

### ISSUE THREAD

**Issue by kraoli** [Kunzisoft/KeePassDX#1109]
**Describe the bug**
Sorry, I can't give good information here. I just notice that the time values set at "Settings/Inactivity Time" are not accurate sometimes. Sometimes it's too fast, sometimes it takes way longer. 

I'm sorry, so far it seems a bit sporadic to me. I hope it's at least helpful to give this topic some more attention. Seems that there are some reports in that direction in the tracker, when I'm not mistaken? 

I bought the pro version to support this great open-source project anyhow, but stuff like this worries me quite a lot. 

Any idea? 

**To Reproduce**
1. Go to 'Settings/inactivity time'
2. try a values and confirm with ok, wait (I tried various from 5sec to 15min) 
3. Sometimes it's locking the database a lot quicker, sometimes it seems not to work or take longer (I did wait additional minutes after my second alarm click showed me that the time was exceed by DX) and sometimes it seems to work ok.

**Expected behavior**
Most important, 100% reliable. I must have faith that this works every time. It should never exceed the value without an unlock (doesn't need to be 100% accurate, but it should not exceed more than a couple of seconds).

It should not lock much faster, but this is just an inconvenience not so much of a security problem. 

KeePass Database

    Created with: [keepass DX pro]
    Location: [local]
    Size: [2]
    Contains attachment: [no]

KeePassDX (please complete the following information):

    Version: [3.0.0]
    Build: [pro]
    Language: [german]

Android (please complete the following information):

    Device: Samsung a52
    Version: [11]

**Comment by J-Jamet** [comment]
Are you sure you are not in one of the cases described in the wiki?
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-did-the-app-lock-before-the-timeout-duration-has-elapsed

**Comment by J-Jamet** [comment]
- In case the time is longer than expected:

  - keep in mind that every time you touch the screen, the timer is reset. This time does not correspond to the total opening time of the application.

- In case the time is shorter than expected:

  - there are several timers in KeePassDX, so check if there is another one running as described in the previous comment.

**Comment by J-Jamet** [comment]
For now, KeePassDX still uses Android API 30 but in version 31 it will be necessary to ask the user if the timer should be accurate or not.
Currently, the code uses the [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager) with the [setExact](https://developer.android.com/reference/android/app/AlarmManager#setExact(int,%20long,%20android.app.PendingIntent)) method.

https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission
https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-acceptable-use-cases

**Comment by kraoli** [comment]
I'll check if it's one of the cases from the wiki. I will report my results in the next one or two days.

**Comment by kraoli** [comment]
So far I've not experienced the issue again. 

I  checked the wiki, I did not use the Magic keyboard. 

I think it might be that https://github.com/Kunzisoft/KeePassDX/issues/1107 was the problem, I played around with the timer and maybe in some cases it was deactivated due to this bug without noticing it.

**Comment by kraoli** [comment]
Just in the moment I wrote it I experianced it again. :-)

I was while writing a longer note in an entry. 

Is it possible that the inactivity timer isn't reset in some cases? 

Maybe it's helpful to know in which cases the inactivity timer will be be reset? I have not found any info about that so far.

**Comment by J-Jamet** [comment]
The timer is reset when you touch most of the views on the screen. In the code, I have to add methods to capture the cascading events of the children of the views of each activity and fragment.

Typing text is not a capture event in this case, I can think about it but it's a huge of work especially since the views are now generated on the fly with the templates, so we'll have to add listeners on top of it, I'm afraid it's going to decrease the performance.

For your previous comment, yes, it must have been a bug with the 0.0.0.0. And the + - 2 seconds is very acceptable.

I thought of displaying a permanent counter, but as the associated notification view has to be refreshed every second, I think it will consume battery for long display times. It's to test, but the problem is that this simple test for this feature will last several days in real time. And as Android explains well in its documentation that the timer will not necessarily be very precise, the interest is very limited.

**Comment by J-Jamet** [comment]
I added the permission in KeePassDX v3.1 which allows to have an exact alarm, it should work better. A warning indicates in the timeout settings if the permission is enabled.
