### ISSUE TITLE
GeneratePasswordDialog disappear on orientation change.

### ISSUE THREAD

**Issue by patarapolw** [Kunzisoft/KeePassDX#111]
A quick fix for me would be to disable orientation change.

**Comment by J-Jamet** [comment]
Yep It's done in develop branch. I recreate de deprecated loading view and lock orientation during the loading. There is no other way, otherwise we lose dialogue when the thread is activated.

**Comment by J-Jamet** [comment]
Fixed in version 2.5.0.0beta11
