### ISSUE TITLE
After delete custom icons, it's database size is not reduced

### ISSUE THREAD

**Issue by Pranab009** [Kunzisoft/KeePassDX#1113]
**Describe the bug**
After delete custom icons, it's database size is not reduced

**To Reproduce**
1. 'Add some custom icons'
2. 'set some icons'
3. 'then delete all icons'
4. 'check database size before add icons, after icons add, after delete icons'

**Expected behavior**
It's database size is not reduced although you delete all custom icons.

**KeePass Database**
 - Created with: [e.g Android KeePass 3.00]
 - Version: [e.g. 3.00]
 - Location: [e.g. Remote file retrieved with internal storage]
 - Size: [e.g. 106kb]
 - Contains attachment: [e.g. no]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 3.0.0 beta3]
 - Build: [e.g. Free]
 - Language: [e.g. English]

**Android (please complete the following information):**
 - Device: [e.g. in 1]
 - Version: [e.g. 10]

**Additional context**

**Comment by J-Jamet** [comment]
Deleted icons are normally removed from the database. Your feedback is not precise enough, if the icons were not big, they probably did not have a big impact on the size of your database.
Can you send examples of databases for which you can conclude that icon removal does not work?

**Comment by Pranab009** [comment]
You can try it.
Create a database and add some custom icons and set in any one entry then delete all custom icons. Now you just check before and after database size.
In my experience
Before add custom icons database size was 87kb and after delete all icons it's size is 102 kb.
 It's size increased although i delete icons.
I'm cleared "bin" and cleared 
"removed unlike data"
although database size is not reduced it's past size.
Please tell me any tip

**Comment by J-Jamet** [comment]
Can you upload a database before and after your deletions, I will look at what they contain.

**Comment by Pranab009** [comment]
Sorry sir this is my fault recently I'm check my database  
and there was some icons are present there.(but i delete all) thats why my database size was not reduced after icon delete. Now i delete once again and it's size reduced.


I know it take too much time.
I'm extremely sorry once again for that. Please don't mine.

**Comment by Pranab009** [comment]
Sir i have one request Please add some built in colorful icons.
![computer](https://user-images.githubusercontent.com/65340361/133656564-66f7c4c4-2829-4fc3-a9fb-7b0663531327.png)

![cyber-security (1)](https://user-images.githubusercontent.com/65340361/133656576-cf783ac3-b06e-4242-8069-2d7523239c1d.png)

![cyber-security (4)](https://user-images.githubusercontent.com/65340361/133656578-7587d053-4aad-4492-ac1d-09f8012ab636.png)

![cyber-security (3)](https://user-images.githubusercontent.com/65340361/133656583-919c65bc-63f9-4e6a-923a-3a7a1d4b6137.png)

![cyber-security](https://user-images.githubusercontent.com/65340361/133656590-b2c9c4f9-30b5-4d3f-a5e6-eec91f6256f9.png)

![data-encryption](https://user-images.githubusercontent.com/65340361/133656598-85a65ab7-8e1e-4a1b-99c2-f2e4bbd2191f.png)

![data-security](https://user-images.githubusercontent.com/65340361/133656602-1213a79f-e650-4833-9546-db26fc14931a.png)

![Uploading distribution.png…]()
