### ISSUE TITLE
Add colorful icons

### ISSUE THREAD

**Issue by Pranab009** [Kunzisoft/KeePassDX#1117]
**Is your feature request related to a problem? Please describe.**
Sir please add some colorful icons. 
**Describe the solution you'd like**
This app ui is too good.but icons are very basic. If possible 
then please add some colorful icons.
**Describe alternatives you've considered**
I know custom icon option is available but make it own (built-in).

**Additional context**

![spyware](https://user-images.githubusercontent.com/65340361/134312475-8f3a86ea-7b3c-44b3-a0e3-dfc2817b8921.png)

![vault](https://user-images.githubusercontent.com/65340361/134312582-1d4df4e2-fe4c-4ba0-ae8f-794de5d61b8a.png)

![vault (1)](https://user-images.githubusercontent.com/65340361/134312594-633ef72d-2abc-4482-84e2-7a054bf3eae7.png)

![shield](https://user-images.githubusercontent.com/65340361/134312600-dd971e04-4985-45a1-b531-315b10163ff1.png)

![shield (7)](https://user-images.githubusercontent.com/65340361/134312602-2b5e4fff-9c21-4cb4-a5d4-83cba68a0edc.png)

![shield (4)](https://user-images.githubusercontent.com/65340361/134312613-a32395b7-b4ab-4579-9a6c-f9636d138d1f.png)

![secure](https://user-images.githubusercontent.com/65340361/134312624-f2e711a8-156a-4423-bcc1-b0f585bef4ab.png)

![password](https://user-images.githubusercontent.com/65340361/134312628-16113cb9-bb7f-4740-afd2-a519e322ea74.png)

![password (4)](https://user-images.githubusercontent.com/65340361/134312636-ce61d4f3-fb59-4eed-8be7-b4ee9a8a54a7.png)

![padlock](https://user-images.githubusercontent.com/65340361/134312638-56d0ae4d-fb4f-4229-a622-646fbeaf9f3b.png)

![padlock (1)](https://user-images.githubusercontent.com/65340361/134312646-018d02cb-3972-4aad-b014-d7b5ab2d7c5d.png)

![encrypted (3)](https://user-images.githubusercontent.com/65340361/134312654-3f2ab272-c831-4a3f-b6b5-ef7dcdf3df15.png)

**Comment by J-Jamet** [comment]
I will not add these icons to the default packs because :

- There is no consistency with the existing icons
- The default icons are part of the kdbx file type, so you have to contact all KeePass application creators to create a new file standard
- It would take more space when there is no need and importing them as custom icons is enough

**Comment by Pranab009** [comment]
Ok.  Thankyou.♥

**Comment by Pranab009** [comment]
Sir please add custom icon packs.
Not single icon images.
(total packs)
Default icons pack is enough just add colors in it and make colorful icon pack.

**Comment by Pranab009** [comment]
Ok
