### ISSUE TITLE
Support for referenced passwords

### ISSUE THREAD

**Issue by cscnk52** [Kunzisoft/KeePassDX#1126]
I have two accounts with the same password in the same database, I need the password of one of them to be synchronized with the other one, i.e. to support referenced passwords, thanks

**Comment by J-Jamet** [comment]
The KeePass field references should work, I have tested them and I have no problems.
https://keepass.info/help/base/fieldrefs.html

**Comment by J-Jamet** [comment]
Maybe it's a problem with the templates. How do you make your references?
