### ISSUE TITLE
Round icon bug

### ISSUE THREAD

**Issue by zmz125000** [Kunzisoft/KeePassDX#113]
tested on Android 8.1 & Android P
https://i.imgur.com/IuEzNDx.jpg

**Comment by J-Jamet** [comment]
Ho, thanks. This is a layer error. I correct that quickly.

**Comment by J-Jamet** [comment]
I usually leave issues open until release, so that other users see the bug in "completed developments" to avoid dupplication. But it is a minor bug that is not very serious, we can let it close. Thank you for the return.
