### ISSUE TITLE
Inherit Icon from Template 

### ISSUE THREAD

**Issue by TippyLion28** [Kunzisoft/KeePassDX#1130]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When I create a new entry based on a template, I want the new entry to have the same icon as the template. 

**Describe alternatives you've considered**
N/A

**Additional context**
Happy to provide further information if the above is unclear.

**Comment by TippyLion28** [comment]
If not the default, then at least having the option would be satisfactory. I'm new to KeepassDX, so not confident that I know the best solution. 

P. S. Loving the app so far, bar this minor issue :)

**Comment by J-Jamet** [comment]
Do you want it to be an inheritance at entry creation or a passive inheritance ?

 - **Creation inheritance** : The icon will be changed immediately when the entry is created and will correspond programmatically to the same as the template but will not be linked.
 - **Passive inheritance** : The icon programmatically match the icon inherited from the parent group or from the key if the icon of the parent group is the default. On the other hand, if a template (other than the standard template) is selected for this entry, it will inherit the template icon when displayed. This allows you to change all the icons at once by changing only the template icon.

**Comment by J-Jamet** [comment]
Personally I find solution 2 more logical but I prefer to ask.

**Comment by J-Jamet** [comment]
> I'd say the word template implies the first option being true

OK, that's enough for me. I'll implement the first one and that way there won't be any incompatibility with the other programs.
