### ISSUE TITLE
Database corrupted on saving new entry

### ISSUE THREAD

**Issue by lucidtanooki** [Kunzisoft/KeePassDX#1132]
**Describe the bug**

Adding new database entries sometimes corrupts the database. Happened several times now.

**To Reproduce**
1. Save a new entry
2. Close the database
3. try to unlock the database
4. `java.io.IOException: javax.crypto.B...`

**Expected behavior**
Database opens fine.

**KeePass Database**
 - Created with: older KeePassDX version
 - Version: Cannot look it up, since it is corrupted
 - Location: SD or internal makes no difference
 - Size: < 1 MB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 3.0.2 from F-Droid
 - Build: F-Droid
 - Language: German

**Android (please complete the following information):**
 - Device: GalaxyS8
 - Version: Android 9

**Additional context**
 - Browser for Autofill: Fennec latest

**Comment by lucidtanooki** [comment]
The used file manager is: Default file manager of Samsung Galaxy S8 for such stuff. I think it's the built in Android thingy.

**Comment by lucidtanooki** [comment]
Database version is: KeePass2 - KDBX3.1

**Comment by J-Jamet** [comment]
Maybe the same as #1201 if it was a v1 database. Since it's fixed in version 3.1.0, I'm closing this issue.
