### ISSUE TITLE
Application crash while pasting a huge text as a note. 

### ISSUE THREAD

**Issue by JahidFariz** [Kunzisoft/KeePassDX#1135]
**Describe the bug**
I used to store public pgp keys as a secure note on keepassDx. It is a huge pseudo random text a.k.a (public PGP keys). It has more than around one thousand characters. Nowadays this application keep crashing while pasting a huge text from the clipboard to notes field. 

**To Reproduce**
1. Click on '+' button.  Then add a new entry. 
2. Scroll down to bottom  'Notes field.'
3. Pasting the copied text on notes field. 
4. And last after pasting the text, it crash. 

**Expected behavior**
I wish to save the text without the limits. 

**KeePassDX:**
 - Version: [3.0.2]
 - Build: [89 Free F-Droid]
 - Language: [English System Default]

**Android:**
 - Device: [Oppo F1 Plus]
 - Version: [5.1]

**Comment by J-Jamet** [comment]
No answer
