### ISSUE TITLE
the app can't store DB password using fingerprint after fingerprint was changed

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#1137]
To reproduce:
1. Enable fingerprint sensor on your phone and configure it.
2. Unlock a DB and store it's password using fingerprint sensor on your device.
3. Remove that fingerprint from phone settings and add a new one.
4. Try to unlock the DB. The app will say that key for extended unlocking cannot be read so you have to remove it.
5. Now input main password and tap fingerprint button sgain. You wll see a caption saying that you must type master password and then tap this button. So now you can't use this sensor to unlock the DB. A way to walk around the problem is to clear app data.

Version: 3.0.2pro from Google play.
Device: Xiaomi Redmi Note 8T running on MIUI 12.0.5.

**Comment by J-Jamet** [comment]
It is difficult to check at step 4 that the fingerprint has been modified, so you have to delete the key manually.
It is not necessary to clear app data if you use the key deletion system in the settings.

https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking#errors

**Comment by zveber** [comment]
Of course you have to clear old key but anyway you can't add a new one. Only cleaning app data helps me here.

**Comment by zveber** [comment]
I just tried it and still have the same problem. Hm... Maybe its MIUI's fault?..

**Comment by seitekobold4** [comment]
> Have you tried `Settings → Advanced Unlock → Delete encryption keys`?

Worked for me.

**Comment by cjk28** [comment]
cheers for the detailed response! re. once a year, I think some people find the fingerprint detection gets worse over time, and removing and adding the fingerprint can fix it, or even adding the same finger multiple times. but yeah it should be rare.

**Comment by J-Jamet** [comment]
I made changes to improve the fingerprint experience in version 3.0.3

**Comment by regs01** [comment]
Huawei P30. Fingerprint doesn't work with this app after readding one finger. Tried Remove encryption keys multiple times, disabling, reenabling biometric unlock in settings, resaving database. Every other application required reenabling fingerprint, but working.
