### ISSUE TITLE
Template compatibility

### ISSUE THREAD

**Issue by alejandracios** [Kunzisoft/KeePassDX#1138]
If you have KPEntryTemplates on your keepass (PC) what in this plugin is meant to show lines, is translated into KeepassDX template as characters. So if you have set to show 5 lines into the windows version, then only 5 characters will be shown on the android app. 

I'm wondering if there is a way to have both options, lines and characters to have full compatibility 

Thanks

**Comment by J-Jamet** [comment]
Normally it should be the same behavior but there may be differences. Can you tell me which template field is the problem?
