### ISSUE TITLE
Search context is lost if going back

### ISSUE THREAD

**Issue by alexanderadam** [Kunzisoft/KeePassDX#1141]
**Describe the bug**

If I search something, confirm (so that I'm on the `Search results` view), select an entry and then go back, the search context is lost.
Instead I'm on the regular overview

**To Reproduce**
Steps to reproduce the behaviour:
1. search something and confirm
2. Click on an entry to see its details
3. use the native back button to go back to search results overview again

**Expected behaviour**

Being on the search results view again.

**KeePassDX (please complete the following information):**
 - Version: `3.0.2`
 - Build: libre
 - Language: English

**PS:** As usual: thank you sooo much for KeePassDX! :raised_hands:

**Comment by J-Jamet** [comment]
This is the behavior of version 3 because it solves workflow bugs, keeping a search history is more complicated because it requires storing search context information, which is not a priority at the moment.
