### ISSUE TITLE
Android backup and cloud storage

### ISSUE THREAD

**Issue by cjk28** [Kunzisoft/KeePassDX#1144]
**Describe the bug**
after factory resetting your device and restoring backed up app data, keepass remembers the path of the old database, which is invalid after a reset if the path was to a database stored in onedrive. (e.g. /document/content://com.microsfot.skydrive.content.metadata/drive/id/1/item.... (cant see the rest but assume there is some randomly generated characters that are generated at the time of accessing the database via onedrive for the first time on the device.

**To Reproduce**
1. have your database stored in onedrive (via android file manager integration with onedrive app)
2. have android backup enabled (e.g. via google one)
3. factory reset phone
4. setup phone and sign in to google account to restore app data etc
5. open keepassdx
6. keepass shows "access to the file revoked by the file maanger. if you attempt to open the database then you get permission denial opening provider com.microsoft...

**Expected behavior**
keepassDX shouldnt back up the path to a cloud storage database (at least onedrive, havent tried others)

**KeePass Database**
 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android (please complete the following information):**
 - Device: noka xr20
 - Version: 11

**Additional context**
even after going back and re-adding my database, keepass still attempts to open the old invalid one when opening the app, until i go back to the database selection page and star my newly added one
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
Unfortunately KeePassDX does not distinguish between a URI that is static and a URI that is not.
This is useful if the application is deleted and reinstalled on the same system but as the backup is often used during a device change or a factory reset, the URI will always be invalidated. 
So I think you are right, maybe the best would be to remove the URI from the backup.

**Comment by J-Jamet** [comment]
I just modified the backup XML  : 

```
<full-backup-content>
    <include domain="sharedpref" path="."/>
    <include domain="database" path="."/>
    <exclude domain="database" path="com.kunzisoft.keepass.database"/>
</full-backup-content>
```

It should theoretically work but it is difficult to test the backup system. So I'll put it online with this configuration and you'll tell me if it's OK.

**Comment by J-Jamet** [comment]
It should be OK with version 3.0.3.
