### ISSUE TITLE
the app automatically locks while it displays an entry

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#1150]
The app locks itself while you watching content of some entry. If you don't open an entry it won't happen. It happens even if you will disable all ways of locking.

To reproduce:
1. Start the app.
2. Open any entry for viewing.
3. Wait some time (a minute or so).

Version: `3.0.2 pro ` from Google play.
Device: Realme 8 pro with Android 11.

**Comment by J-Jamet** [comment]
It's really weird, I can't reproduce this problem. There must be a trigger that locks the database, it can't be done without anything.

**Comment by zveber** [comment]
My new phone is slightly weird 😁. I just cleared app data, restored settings and the problem has gone. Sorry for bothering.
