### ISSUE TITLE
Can't copy emails contained in notes or other links

### ISSUE THREAD

**Issue by aisbergde** [Kunzisoft/KeePassDX#1152]
**Describe the bug**
If the note contains emails then they are rendered as emails, they are promoted as links. But it is not possible to copy them. I want to be able to copy any part of notes, also if the program promotes them as link

**To Reproduce**
1. Create entries with notes
2. Include emails, web sites and other parts which are promoted as links
3. Mark them
4. You don't get the normal context menu which allows to copy (past, insert,...)

**Expected behavior**
It should be possible to copy any part of notes

**KeePass Database**
How to know? There is no entry in the context menu of the used database 
 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX (please complete the following information):**
 - Version: 3.0.2
 - Build: free
 - Language: German

**Android (please complete the following information):**
 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**
Possible work around
- edit the entry to be able to copy
- open in Keepass2android to be able to copy any part of notes

**Comment by zveber** [comment]
I just tried to select a part of a note. To do it I had to make a long tap on a word in reading mode. At least it does work on my phone.

**Comment by aisbergde** [comment]
there are "normal" parts in the note and parts, which are automatically rendered as "implicit link" (for example emails, following the syntax aaa@bbb.ccc)
- When I long press any normal part, then I get the normal context menu and I can copy the selected part.
- When I short press an implicit link I get the 'open with' selector, there is no "copy to clipboard", I get only apps registered for the link.
- When I long press on an implicit link, I feel a "haptic feedback", but nothing opens. It is like something happens, but the context menu is suppressed.

My system:
Pocophone X3
Modell M2102J20SG
MIUI Global 12.5.3
12.5.3.0(RJUEUXM)
Android version 11 RKQ1.200826.002
Android security update 2021-09-01

**Comment by J-Jamet** [comment]
> When I long press on an implicit link, I feel a "haptic feedback", but nothing opens. It is like something happens, but the context menu is suppressed.

I confirm that it works without problems on my devices. It is a problem of your system that does not display the selection actions.

**Comment by J-Jamet** [comment]
To bypass the problem, you can select text without link and move the sliders to select text with link.
