### ISSUE TITLE
Autofill not working in Firefox 94.1.1

### ISSUE THREAD

**Issue by Qwerty-Space** [Kunzisoft/KeePassDX#1154]
**Describe the bug**

**To Reproduce**
1. Go to any website
2. Try to login
3. No autofill pop-up

**Expected behavior**

**KeePassDX (please complete the following information):**
 - Version: 3.0.2
 - Build: free
 - Language: English

**Android (please complete the following information):**
 - Device: OnePlus 5
 - Version: 8.0

It works on the DDG browser, but not on Firefox.

**Comment by J-Jamet** [comment]
Linked to #725
