### ISSUE TITLE
don't ask for password if biometric unlocking is configured

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#1155]
**Is your feature request related to a problem? Please describe.**
Sometimes when you tap on KeePassDX icon at start screen it tries to unlock the starred DB from the list with it's password, so you see keyboard. But it is weird because you configured biometric unlocking for it, so the app should ask your fingerprint.

The same happens if you turned on `App settings -> Lock -> Show lock button` and locked DB with it.

**Describe the solution you'd like**
Don't show keyboard if biometric unlocking is configured.

**Comment by J-Jamet** [comment]
I don't understand the request at all.

> Sometimes when you tap on KeePassDX icon at start screen
 
 The application icon is only visible in the password screen if advanced unlocking is disabled.

> it tries to unlock the starred DB from the list with it's password

I don't understand, the database opening action can't be done by itself.  You need to either scan your fingerprint or make a scheme if the prompt opens.

> The same happens if you turned on App settings -> Lock -> Show lock button and locked DB with it.

I don't see what this has to do with the issue you're trying to explain, it's an option that only serves to hide the lock icon when a database is already open.
