### ISSUE TITLE
Magikeyboard TOPT doesn't full fill the numbers on Epic Games website.

### ISSUE THREAD

**Issue by giwrgosmant** [Kunzisoft/KeePassDX#1158]
**Describe the bug**
In the Epic Games Store website, when I am trying to fill the TOTP with Magikeyboard, it fills only the 1 number and stops.
I don't know if it's the issue of the specific website since I only encounter it on it.

**To Reproduce**
1. Go to Epic Games Store website.
2. If you have account login and trying to fill the TOPT with Magikeyboard.

**Expected behavior**
It should fill the full TOPT numbers.

**KeePassDX (please complete the following information):**
 - Version: 3.0.2
 - Build: Free (Play Store)
 - Language: Greek

**Android (please complete the following information):**
 - Device: POCO F1
 - Version: Android 11

**Comment by J-Jamet** [comment]
Indeed, it is because the epic game site has a form by number. I will try to improve the automatic character information system by reusing the KeePass autotype system.

https://keepass.info/help/base/autotype.html

It will take time because the whole system of parse and keystroke simulation must be created.

**Comment by J-Jamet** [comment]
I found a generic workaround for this problem.
You just have to do a long press on the OTP button of the Magikeyboard in version 3.3.1. This will send the characters one by one with a tab between each.
This will allow to wait for the auto-type implementation.

**Comment by J-Jamet** [comment]
Despite my efforts I can't get the keyboard to work with this form, maybe there is javascript bugging the keyboard inputs. If anyone has a solution, I'm interested.

**Comment by J-Jamet** [comment]
The TOTP form has been corrected by the Epic Games team.
