### ISSUE TITLE
"Create entry" button in keyboard with autofill

### ISSUE THREAD

**Issue by dennis90a** [Kunzisoft/KeePassDX#1159]
**Is your feature request related to a problem? Please describe.**
Autofill already exists, this is more of an enhancment

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
Use normal autofill

**Additional context**
Password store has this cool feature when you see a 'Create entry button in the keyboard“. When clicked, it prompted for a new entry. And when long pressed, it allowed me to browse through existing passwords. In my case I was using florisboard, and this only works when autofill is enabled.

![Screenshot_20211114-120527_Privacy_Browser](https://user-images.githubusercontent.com/90372818/141670461-5dc5b975-b483-4d09-9f33-1bf72d162160.png)

I think keepassdx should also have this

**Comment by J-Jamet** [comment]
The "Sign in with KeePassDX" button allows more flexibility as it allows you to select an existing entry or to select the location in a group. It would be faster for sure with "Create entry" but could only ask for the currently opened group and would add a button next to the existing one.
