### ISSUE TITLE
Can't save to DavX5 with WebDAV protocol

### ISSUE THREAD

**Issue by Offerel** [Kunzisoft/KeePassDX#1160]
**Describe the bug**
I opened a kdbx file with standard files application to KeepassDX. The file is from a WebDAV share and the WebDAV share is mounted via DavX5. If I try to save a change, i get the message that the database can't be saved. I don't know if this is a bug from KeepassDX or DavX5.

**To Reproduce**
1. Install DavX5
2. Mount the WebDAV file share from within DavX5
3. Open KeepassDX
4. Open a kdbx file via standard files application and choose file from WebDAV share
5. Make some change to the database
6. Try to save the change
7. Save will fail

**Expected behavior**
Save is successful

**KeePass Database**
 - Location: [Remote via DavX5]
 - Size: [400kb]
 - Contains attachment: [Yes]

**KeePassDX (please complete the following information):**
 - Version: [actual version from f-droid]

**Android (please complete the following information):**
 - Device: [GalaxyS20FE]
 - Version: [11]

**Comment by J-Jamet** [comment]
I don't know DavX5, but the only thing I can do at the moment is to add the behavior of this application to the [wiki](https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync).
After that when I will make the file manager application which will integrate WebDAV, it will be easier to use. https://github.com/Kunzisoft/KeePassDX/issues/840

**Comment by Offerel** [comment]
With other applications, using SAF, i can save without problems to this WebDAV share. For example [andOTP](https://cloudflare.f-droid.org/de/packages/org.shadowice.flocke.andotp/) saves backups directly to this mount.

If i understand this right, DavX5 [Google](https://play.google.com/store/apps/details?id=at.bitfire.davdroid) or [F-Droid](https://cloudflare.f-droid.org/de/packages/at.bitfire.davdroid/), mounts a DAV fileshare directly in to the standard built-in Android files ap. Its up to the app to read and/or write to such a folder. According to https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync it should be possible to write to content://com.android.externalstorage.documents/. But maybe im wrong. Hopefully, you fid a way to support writing a db to a webdav, either via your filemanager or SAF.

**Comment by rfc2822** [comment]
DAVx5 uses directly streamed WebDAV without a file buffer. This allows to directly stream files of any size. However, only the `r` and `w` modes are supported; `rw` (random access) is not supported because it's not defined in WebDAV (there are extensions, but must servers don't have them and they can't be detected automatically).

However, for just saving a backup, w should be enough (or r for restoring), so this should worked with WebDAV. So I suggest to use `w` or `r`, which should be enough in your case and allow direct WebDAV backups.

**Comment by J-Jamet** [comment]
`rw` is no longer used by default

**Comment by Offerel** [comment]
Can confirm that this is working fine now. Many thx.
