### ISSUE TITLE
Location of save-backup files?

### ISSUE THREAD

**Issue by ohuf** [Kunzisoft/KeePassDX#1168]
While we have the option to create a "database backup before save", there's no mentioning in the wiki where those files reside? I need to extract an old backup in order to do a diff (had a split-brain situation due to a sync error).
Any help?

**Comment by J-Jamet** [comment]
You must be mistaken, there is no "database backup before save" option in KeePassDX.
The application is only a file editor, it's up to you to know where the files you edit are stored.
