### ISSUE TITLE
Can't use KeePassDX Android notification pull-down to copy current Password to the clipboard

### ISSUE THREAD

**Issue by JazzTech** [Kunzisoft/KeePassDX#1169]
On the OnePlus 7 Pro running Oxygen OS version 11.0.3.1GM21AA, I can't access the password for the selected KeePass item. From the Android Notification pull-down, I can tap on the "Select to copy Username to clipboard", and the username is successfully copied to the clipboard. However, after pasting the username onto a webpage, the Notification pull-down doesn't change to "Select to copy Password to clipboard". The password isn't easily available through the Notification pull-down anymore.

**To Reproduce**
1. Open up a login webpage to past username and password
2. Open up KeyPassDX and unlock a KDBX password database
3. Search and select the KeePass entry for the website
4. Pull down the Notification list
5. Select the KeePassDX "Select to copy Username to clipboard" item in the Notification list
6. The Username time-out bar appears and starts counting down
7. Do a long-press in the Username field on the webpage.
8. The Android standard "Paste" pop-up option appears
9. Select the "Paste" option
10. The username in the clipboard is pasted into the Username field on the webpage
11. Error => The KeePassDX selected entry's Username item in the Notification pull-down still shows the Username time-out bar

**Expected behavior**
At Step 11 above, the Notification pull-down should have changed to the "Select to copy Password to clipboard"

**KeePass Database**
 - Created with: Windows KeePass 2.49
 - Version: 2.49
 - Location: Remote file retrieved from the Sync.com Android application
 - Size: 194 kB
 - Contains attachment: No

**KeePassDX**
 - Version: 3.0.2
 - Build: Free
 - Language: English

**Android**
 - Device: OnePlus 7 Pro
 - Version: OygenOS v11.0.3.1GM21AA

**Additional context**
 - Browser for Autofill: Opera v65.2.3381.61420

**Comment by J-Jamet** [comment]
You have probably not activated the clipboard trust for sensitive data.
https://github.com/Kunzisoft/KeePassDX/wiki/Clipboard#trust

**Comment by JazzTech** [comment]
Thanks, @J-Jamet, that was the cause of my problem!
