### ISSUE TITLE
Request: database nicknames

### ISSUE THREAD

**Issue by zaccaccino** [Kunzisoft/KeePassDX#117]
Loving what you've done so far! Looks very smooth.
Google drive sync works quite well, however, the title of recent databases only reference doc numbers. So it's a bit hard to choose what the recent ones actually were.
Edit: I'm not sure how to tag this as a request, I'm new, sorry.

**Comment by J-Jamet** [comment]
Thank you for the feedback. I'll look at how to change the display of items in the list when I develop the synchronization. The names are those of the content provider, if I can't get the name of the file, I may put an alias system.

(No worries, I add the labels of the issues manually)

**Comment by aaronbronow** [comment]
+1
I have a DB open from OneDrive and the name is just the query string of the file. Would be nice to have the DB list show the name of the file or an alias.

**Comment by Edwin-VC** [comment]
Same feature request here. I use two DBs both stored on OneDrive. Now they have the  same query string as 'name'.

**Comment by J-Jamet** [comment]
It is now possible to add aliases to databases in version 2.5.0.0beta23
