### ISSUE TITLE
Templates does replace values

### ISSUE THREAD

**Issue by Gottarocket** [Kunzisoft/KeePassDX#1171]
**Describe the bug**
This may be dumb or i may be doing it wrong . i created a new database so I can only have credit cards there but templates edited show same value as text in all places even when its edited 
**To Reproduce**
1. Go to Templates
2. Click on Credit cards
3. Edit and change ccv number and all details with your data
4. Hit right mark to save values as still shown as default  text instead of new value 

**Expected behavior**
Values need to be replaced with new entry
**KeePass Database**
 - Created with: KeepassDX
 - Version: 3.0.2
 - Location: local
 - Size: 3kb
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 3.0.2
 - Build: Free
 - Language: English

**Android (please complete the following information):**
 - Device: 
 - Version: 

**Additional context**

Shows history of all edits done again and again but history also has default value
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
I don't understand the problem.
In your procedure, you try to replace the "Credit Card" template, and you put your personal information there. OK, but how do you do it? Do you use the `default` parameter as it is written in the wiki? https://github.com/Kunzisoft/KeePassDX/wiki/Templates
Please be more specific, as I just tested and the `default` parameter work fine. Creating a new entry with the selected template fills the default fields well.

**Comment by Gottarocket** [comment]
Sorry I am confused on  replacing values . Can you just provide what to enter on cvv to make it save 3 digit no i add ? I will follow the other steps . I tried to change on keepassxc but there is no option to change value there too under attributes

**Comment by J-Jamet** [comment]
> Can you just provide what to enter on cvv to make it save 3 digit no i add ?

This is not possible for the moment, only a generic string is supported `text`. This is due to the language of the original plugin.

**Comment by Gottarocket** [comment]
Np . I just saw a issue where credit card autofill was asked did they change values or was it something else

**Comment by J-Jamet** [comment]
The autofill linked to credit cards is not linked to templates. It only adds a custom field to the selected entry.
