### ISSUE TITLE
java.lang.Security.Exception may be raised when opening a database file

### ISSUE THREAD

**Issue by rougemeilland** [Kunzisoft/KeePassDX#1172]
**Describe the bug**

When I open the KeyPassDX screen when the app or web browser asks me to enter my password, I sometimes see the message "java.lang.Security.Exception: Permission Denial: Opening ..." at the bottom of the screen. ..

**To Reproduce**

1. Display the password entry screen for some application.
2. The item "Login with KeyPassDX" of KeyPassDX is displayed on the password input screen of the application. Select it.
3. The KeyPassDX authentication screen will be displayed, so authenticate. (I have fingerprint authentication)
4. After a brief "Loading database" message, the message "java.lang.Security.Exception: Permission Denial: Opening ..." appears at the bottom of the KeyPassDX screen.

**Expected behavior**

In step 4 above, I expect it to work as one of the following:
- Password suggestions are displayed on the original application.
- KeyPassDX starts automatically, after which the password entry selection screen is displayed.

**KeePass Database**
 - Created with: Windows KeePass 2.49 64bit
 - Version: KeyPass 2 KDBX3.1
 - Location: My Drive on Google Drive
 - Size: 51KB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 3.0.2
 - Build: Free
 - Language: Japanese

**Android (please complete the following information):**
 - Device: SONY Xperia XZ3 au SOV39
 - Version: 10

**Additional context**
- The conditions for reproducing this phenomenon are unknown.
- If this happens, you can get the password by starting KeyPassDX once and starting over from "Open existing database file". This phenomenon does not occur for a while after that.
- This phenomenon did not occur before, but it has started to occur for several weeks.
- It may be irrelevant, but I feel that this phenomenon is likely to occur after I do the following actions. Maybe it's a problem related to network switching. Or it may be due to the passage of time.
  - Entering and exiting the place where the wifi router is installed (home, drug store, etc.)
  - Move in a place where multiple wifi routers are installed

**Comment by J-Jamet** [comment]
Are you using a key file? If so, it was just an old bug that has already been fixed, just reselect the key file. #1066 #1067 #1071 #1094 #1099

This can also happen because a file has been untied from its URI. It is possible that changing the password with a key file causes this problem, it has been fixed in version 3.0.3.

**Comment by rougemeilland** [comment]
Thank you for your comment immediately.

No, I'm using a password instead of a key file to authenticate to open the database file.
I have never used a key file before.

**Comment by J-Jamet** [comment]
Okay, in this case I think it is a problem in losing the URI link of the database file. It must be related to Google Drive. I know there are security changes on this drive app, I'll have to test to find out what the exact cause is. But as you say, if it works by reselecting the file it's already a good thing.

**Comment by FelixBenning** [comment]
I have the same issue on a pixel 4a, also using google drive. My workaround is to open the keepass app directly, go back and reselect the database file, open it and then go back to the app where the password is needed.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/discussions/1089#discussioncomment-1985550
