### ISSUE TITLE
KeePassDX Still Shows Key File Location

### ISSUE THREAD

**Issue by faxotherapy** [Kunzisoft/KeePassDX#1175]
**Describe the bug**
Tapping the Keyfile field will directly show the previous location where I retrieved the key file. Knowing the password, I'd just need to try one by one all the files in this folder to try to unlock the database, which is very problematic.

Even though “Remember keyfile locations” is toggled off, the issue persists.

**To Reproduce**
1. Select kdbx file
2. Input password
3. Tap Keyfile field. From this moment, the file explorer will show up from the folder where I retrieved the same key file during the previous use of KeePassDX. Because of this, I'd just need to select the only file there is in this folder, since I only have this file in the folder.

**Expected behavior**
When tapping the Keyfile field, KeePassDX should initialize the file explorer and start from, e.g., the Home folder or any other folder chosen from the user.

**KeePass Database**
 - Created with: MacOS Mojave, KeePassXC
 - Version: 2.6.6
 - Location: loaded locally
 - Size: 700 ko
 - Contains attachment: Yes, text files

**KeePassDX (please complete the following information):**
 - Version: 3.0.2
 - Build: Libre
 - Language: English

**Android (please complete the following information):**
 - Device: Pixel 4a
 - Version: 11

**Comment by J-Jamet** [comment]
The KeePassDX code does not require any particular location when requesting to read a file. And it does not save the location either, even when the option is activated, but only the URI of the file.

Code : https://github.com/Kunzisoft/KeePassDX/blob/045049243caa874c905a60a18d58903923b3d825/app/src/main/java/com/kunzisoft/keepass/activities/PasswordActivity.kt#L150
https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/activities/helpers/ExternalFileHelper.kt

So I think it's just the file manager you are using (the _File_ app seems to do that but not _Material Files_) that remembers the last requested location. Change the file manager if you want a different behavior.

**Comment by faxotherapy** [comment]
Hi @J-Jamet, thx for your prompt reply. Could you please tell me how to set the default file manager?

**Comment by J-Jamet** [comment]
In the new versions of Android, it seems that alternative file managers that receive the intent ACTION_OPEN_DOCUMENT are no longer allowed by the system but you can try [MaterialFiles](https://github.com/zhanghai/MaterialFiles).

Since the default manager retains the last saved location, I think the easiest solution is to open another folder. In any case, I can't change this behavior in KeePassDX.

**Comment by faxotherapy** [comment]
Or, in my case, why not hosting the key file on a remote server (e.g. via SSHFS), then umount the file system afer use so that if one gets the chance to open the file manager from KeePassDX, the opportunist does not easily obtain access to the key file as the file system hasn't been automatically be mounted…

**Comment by J-Jamet** [comment]
Yes, this is also a method that works.
