### ISSUE TITLE
Material design 3

### ISSUE THREAD

**Issue by Ilithy** [Kunzisoft/KeePassDX#1183]
Hi,
just a question about the aesthetics of the application, do you plan to use the new material design 3?

_"Android 12 brings a fresh new design language to Google's mobile OS. Called Material You, it adapts to your wallpaper and applies the theme across all elements, such as buttons, sliders, widgets, notification shade, icons, animations [...]"_

I know that aesthetics is not the priority (it goes logically to the resolution of bugs), and, not being a coder, I could not estimate the difficulty of integration of it, but this would significantly improve the color management in the application, and would improve even more the user friendly side, 
What do you think?

Thank you.

**Comment by J-Jamet** [comment]
https://m3.material.io/libraries/mdc-android/getting-started

It requires structural changes and the library is in Alpha version. I don't like this policy of Google to change the libraries too often and to change the code recommendations every 6 months. It can be a good addition but it's not in a hurry and I have to check the feasibility not to add bugs.

**Comment by Ilithy** [comment]
Thank you for answering me, this is clearly not a hot point to make, I was not aware of this libs issue, thanks for the clarification.

I close, no need to pollute more than necessary, very good year to you

**Comment by J-Jamet** [comment]
We can leave it open, it will be a good addition but in the future.
