### ISSUE TITLE
Unable to open a new kbdx file with empty password

### ISSUE THREAD

**Issue by abda11ah** [Kunzisoft/KeePassDX#1184]
Hi,
I tried to create a new kbdx file that is passwordless.
It worked.

But the app can't further open it (in another session) because of password needed.

In another ticket :
https://github.com/Kunzisoft/KeePassDX/issues/1140

You said :
"Passwords are not required in KeePassDX, just disable the password switch button."

But as i see, it is not possible to open the database when the switch button is off because the "OPEN" button got disabled.

![Screenshot_20211226-064834185](https://user-images.githubusercontent.com/1699034/147400350-a0be6134-40c9-4a13-ab99-59bb0a007601.jpg)
![Screenshot_20211226-064825695](https://user-images.githubusercontent.com/1699034/147400351-796ecf83-2ddf-4171-95ea-f972f5eeb5f2.jpg)

**Comment by J-Jamet** [comment]
_Settings - App settings - Allow no master key_

Or use the validation key with your keyboard
