### ISSUE TITLE
Question: how / where are autofill suggestions  for apps stored?

### ISSUE THREAD

**Issue by alexanderadam** [Kunzisoft/KeePassDX#1187]
I'm not quite sure whether this simply isn't working for me or whether I'm looking in the wrong spots.

So if an app has an input, I'm seeing [`Sign in with KeePassDX`](https://github.com/Kunzisoft/KeePassDX/search?q=autofill_sign_in_prompt) on my keyboard.
When I type on it and select a KeePass entry, I'm seeing [`Autofill suggestions added`](https://github.com/Kunzisoft/KeePassDX/search?q=autofill_inline_suggestions_keyboard).

Now KeePassDX will suggest this entry as long as I'm not closing KeePassDX.
But if I close KeePassDX I have to redo that procedure. Therefore it seems that whatever `added` means in `Autofill suggestions added`, doesn't seem to be persisted in the KeePass database.
And I'm also unable to see any property if I have a look at the particular entry in the database (i.e. in KeePassXC — see screenshots).

![Screenshot of additional attributes in KeePassXC](https://user-images.githubusercontent.com/372620/147660852-b5a8f765-a0d5-44f0-8c2a-8e80a15d1bae.png)
![Screenshot of properties in KeePassXC](https://user-images.githubusercontent.com/372620/147660994-3c7bf069-0802-4d5d-9280-c35e3fb9a040.png)

**Comment by J-Jamet** [comment]
What do you mean by "autocompletion reference"?

If it's the `URL` of a website it's in the basic "URL" field, otherwise it's a custom field if it's already filled or if it's for an `applicationId` (in `AndroidApp` custom field).

Auto-Type is not used in KeePassDX. https://github.com/Kunzisoft/KeePassDX/issues/1167

If you are talking about automatic keystrokes for filling in particular forms, this is not yet supported.

**Comment by alexanderadam** [comment]
I'm very sorry. I obviously used the wrong term. I meant `Autofill suggestion`.

So if an app has an input, I'm seeing [`Sign in with KeePassDX`](https://github.com/Kunzisoft/KeePassDX/search?q=autofill_sign_in_prompt) on my keyboard.
When I type on it and select a KeePass entry, I'm seeing [`Autofill suggestions added`](https://github.com/Kunzisoft/KeePassDX/search?q=autofill_inline_suggestions_keyboard).

Now KeePassDX will suggest this entry as long as I'm not closing KeePassDX.
But if I close KeePassDX I have to redo that procedure. Therefore it seems that whatever `added` means in `Autofill suggestions added`, doesn't seem to be persisted in the KeePass database.
And I'm also unable to see any property if I have a look at the particular entry in the database.

**PS:** I try to update the post accordingly
**PPS:** Thank you for your fast response! :raised_hands:

**Comment by J-Jamet** [comment]
> Now KeePassDX will suggest this entry as long as I'm not closing KeePassDX.

If you stay on the same form page the suggestion will always be the same. But if you reload the form page and you still have the suggestion, it means that the saving of the `URL` or the `AndroidApp` worked well.

`Settings - Form filling - Autofill settings - Save search info` must be activated to save the information permanently in a writable database.

**Comment by alexanderadam** [comment]
> `Settings - Form filling - Autofill settings - Save search info` must be activated to save the information permanently in a writable database.


This was and still is activated. But I cannot see any change within properties or additional attributes anyway. So I'm still not quite sure where it would write that information.

> > Now KeePassDX will suggest this entry as long as I'm not closing KeePassDX.
> 
> If you stay on the same form page the suggestion will always be the same.

But usually Android apps will be closed at one point. I mean, I won't stay on the Twitter/Banking/E-Mail login screen etc. At one point I will touch the `Sign in` button and leave the form. Right?
And the Twitter/Banking/Email app might also be closed anyway. So It's rather unusual to stay forever on the same form page of an app. Or am I missing something here?

> But if you reload the form page and you still have the suggestion, it means that the saving of the `URL` or the `AndroidApp` worked well.

Okay, so this means that it didn't work well, right?
Because I have to select the entry every time again if KeePassDX is closed at one point.

**Comment by J-Jamet** [comment]
> This was and still is activated. But I cannot see any change within properties or additional attributes anyway. So I'm still not quite sure where it would write that information.

The URL field is filled or a custom AndroidApp field. If you don't see any change, it might be that your database is read-only.

> But usually Android apps will be closed at one point. I mean, I won't stay on the Twitter/Banking/E-Mail login screen etc. At one point I will touch the Sign in button and leave the form. Right?
And the Twitter/Banking/Email app might also be closed anyway. So It's rather unusual to stay forever on the same form page of an app. Or am I missing something here?

I'm just saying that as long as you stay on a form and the autofill offers an entry. Even if the database is closed, the autofill will still propose the entry if the page is not reloaded because the autofill service will have the information.

> Okay, so this means that it didn't work well, right?
Because I have to select the entry every time again if KeePassDX is closed at one point.

I have done many tests and it works for me every time. So I don't know why it doesn't work for you. I only have to enter the main password of the database and the autofill proposes the entry directly after that.

**Comment by alexanderadam** [comment]
I think I see what the problem is! I expected the database to be written but this didn't happen since I had to save the database _manually_ afterwards.
`Autosave database` wasn't activated (is it activated or deactivated by default). Should this setting also lead to autosaving in the filesystem once I select the Autofill suggestion?

**Comment by J-Jamet** [comment]
Yes indeed, the automatic save is carried out only if the `Autosave database` setting is activated.

**Comment by alexanderadam** [comment]
Then maybe the confirmation message could be extended with something like "It will be stored if you save the file _manually_" if this setting isn't activated.

This way the user would know what's going on.
Is `Autosave database` activated or deactivated by default?

**Comment by J-Jamet** [comment]
> Then maybe the confirmation message could be extended with something like "It will be stored if you save the file manually" if this setting isn't activated.

What confirmation message are you talking about?

> Is Autosave database activated or deactivated by default?

https://github.com/Kunzisoft/KeePassDX/blob/3dd9ef55640af284942e95d1c9f428d7fd915eed/app/src/main/res/values/donottranslate.xml#L69
So yes

> Did I mention that you're giving great support on GitHub? You're a great maintainer! +1

Ty

**Comment by alexanderadam** [comment]
> > Then maybe the confirmation message could be extended with something like "It will be stored if you save the file manually" if this setting isn't activated.
> 
> What confirmation message are you talking about?

The message [`Autofill suggestions added`](https://github.com/Kunzisoft/KeePassDX/search?q=autofill_inline_suggestions_keyboard).

> > Is Autosave database activated or deactivated by default?
> 
> https://github.com/Kunzisoft/KeePassDX/blob/3dd9ef55640af284942e95d1c9f428d7fd915eed/app/src/main/res/values/donottranslate.xml#L69
> 
> So yes

Perfect :+1:

**Comment by J-Jamet** [comment]
> The message Autofill suggestions added.

This message only indicates that the autofill suggestion has been added when inline autofill is enabled because the suggestion may appear in a keyboard that may not be directly visible. (so it is not appropriate if the message is added here.)
