### ISSUE TITLE
Make Secured Note more readable

### ISSUE THREAD

**Issue by Ilithy** [Kunzisoft/KeePassDX#1189]
**Is your feature request related to a problem? Please describe.**
It is impossible to organize secured notes easily, because it is impossible to make a line break; whereas it is possible in the notes of standard entries.

**Describe the solution you'd like**
If it were possible, the secured notes field would react identically to the standard notes field (jump and line break possible)

Thanks

**Additional context**
To explain, when I talk about jump and line break, it means a press on the enter key of the keyboard while editing a field; as a result, it creates "river notes", which is very unreadable.

If you press the enter key on the keyboard while editing a secured note, you go on to edit the next field, this is not the case in basic notes (additional notes in an entry)

The problem that this poses is perhaps marginal among users.

**Comment by Ilithy** [comment]
Hello,
It's very strange, because I have just redone the manipulation, and it reacts identically, in the edition of a secure note (), used the key input skipped to edit the following fields, unfortunately I can't create a screenshot, nor do a video capture of the manipulation, otherwise it's not the end of the world, I just won't use the secure note model.
thank you.

**Comment by J-Jamet** [comment]
First, what do you mean by "Secure note model"?

The basic KeePass format only allows for standard notes. Then you can use templates but it comes back to what I said before, where you must be missing a template option.

**Comment by Ilithy** [comment]
By this I mean:
Click on the floating "+" button

Click on add an entry

In the edit entry window at the top,
Select the "Secure Note" template

Then try the manipulation (i.e. edit the "note" field, and use the enter keyboard button to skip a line, for example).

Sorry, I should have been clear from the beginning, is my explanation more understandable? Thanks again for your help

**Comment by J-Jamet** [comment]
That's what I was saying. "Secure Note" has never been part of the default templates of KeePassDX. The default template created with a new database is called "Note" and has the right options. 

So either you created this template manually or it was created from another application.

You just have to add the option `{lines:many}` in the template attribute to solve the problem
