### ISSUE TITLE
Question on INTERNET ACCESS / App connecting to ip

### ISSUE THREAD

**Issue by FlowerWarrior** [Kunzisoft/KeePassDX#1190]
I did a virustotal.com scan of the apk file and it connects to this ip and github domain. Why is that? (seems like a big security concern) And how to make the app fully offline in source code?

![image](https://user-images.githubusercontent.com/84773603/147973387-d24991d2-2747-40d5-9625-ec640effc959.png)

**Comment by J-Jamet** [comment]
KeePassDX never connects to internet and does not even have the permissions to do so. I don't know your tool but it just detected URL links that redirect to github and the official website for help.

**Comment by FlowerWarrior** [comment]
Alright, thanks for claryfing.
