### ISSUE TITLE
After update to Android 12 login credentials from KeePassDX do not work anymore

### ISSUE THREAD

**Issue by bad-ch** [Kunzisoft/KeePassDX#1191]
Since I have updated the Android version to 12 the credentails from my database do not work anymore. With Syncthing I synchronize my password db between different plattforms. My Windows environment is still able to open the database, but on the Android it is not possible anymore. Any ideas ? The only thing which has changed is the Android OS.

I see the message Retrieving database key ... after some seconds I get the error message "Could not read credentials". I have tried my fingerprint and the password.

KeePassDX version 3.0.4 (2MB)
Device Samsung S20+

**Comment by bad-ch** [comment]
My data and cache from the app is deleted as well, after a new read of the database it still not works

**Comment by J-Jamet** [comment]
Are you using a key file? Maybe it's related to #1188?

**Comment by bad-ch** [comment]
I agree it seems to be related to that issue (sorry), I use an image as an additional key, but the path is correct. After I clean up my app data I have to enter my password and my key file, but I have the same behavior.

**Comment by J-Jamet** [comment]
And when you rename the extension of your key file to .bin, does it work?

**Comment by bad-ch** [comment]
He Thx, if I rename the jpg file to a bin it works, it seems to be a new security feature from Android which cause this problem ?? However this workaround is fine for me. Thx again :o)

**Comment by bad-ch** [comment]
I think it's time for a donation

**Comment by J-Jamet** [comment]
Thank you. It's nice.
