### ISSUE TITLE
Confirm reload dialog if local modification

### ISSUE THREAD

**Issue by shockergit** [Kunzisoft/KeePassDX#1196]
Please add a confirm dialog while deleted history and reload database. A confirm dialog will stop accidental deletion and reloading of entries.

**Comment by J-Jamet** [comment]
For the reload of the database, I understand, I will do it to accompany the merge.

But for deleting a entry history I don't understand, you knowingly went into the history so pressing the delete button without doing it on purpose is really like pressing all the buttons at random?

**Comment by shockergit** [comment]
> For the reload of the database, I understand, I will do it to accompany the merge.
> 
> But for deleting a entry history I don't understand, you knowingly went into the history so pressing the delete button without doing it on purpose is really like pressing all the buttons at random?

sometimes accidents happens lol
