### ISSUE TITLE
Clipboard Doesn't Clear

### ISSUE THREAD

**Issue by seniorm0ment** [Kunzisoft/KeePassDX#1198]
Clipboard duration I have at 10sec to give time to copy paste.
However they do not clear, using AnySoftKeyboard from FDroid

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/Clipboard#compatibility

The description of the feature is clear and does not indicate that the clipboard will be deleted :`Lock the database when the clipboard duration expires or the notification is closed after you start using it`

**Comment by seniorm0ment** [comment]
Apologies, did not see that.
Would clipboard clearing be possible, or is it not possible due to the way it works? I know it can be done on desktop.

**Comment by J-Jamet** [comment]
The program already tries to delete the copied item from the clipboard but in most cases there is a history built directly into the OS or keyboard from which items can only be deleted manually.
