### ISSUE TITLE
Database in google drive issue

### ISSUE THREAD

**Issue by gerardo-junior** [Kunzisoft/KeePassDX#12]
Hello, I leave my database in Google drive and open it with android folder manager, trying to add a new password corrupted my database.

Android 7.1.2
KeepassXD 2.5.0beta-libre

Sorry for the english of the google translator

**Comment by J-Jamet** [comment]
Hello, It's an issue solved in KeepassDroid 2.0.0.9 and will be solved in the next beta. To uncorrupt your database : DL KeepassDroid -> Go in Settings and Key encryption rounds before corruption

**Comment by gerardo-junior** [comment]
Great to know! :)

Great job to everyone involved, very useful app and well done

**Comment by J-Jamet** [comment]
Must be ok with the new version **2.5.0.0beta3** but to confirm.

**Comment by gerardo-junior** [comment]
Would not it be possible to add as the apk in the github release session?

**Comment by J-Jamet** [comment]
Sorry, I do not understand what you want. But the new apk is released in PlayStore and takes a little longer for fdroid (It requires a validation of the commit and a build by the server)

**Comment by gerardo-junior** [comment]
Sorry for English, I asked could add apk as a release in github

**Comment by J-Jamet** [comment]
I'm looking to put the APK in the release. ;)

**Comment by gerardo-junior** [comment]
Good news, everything is working correctly, when the f-drive validate, and update the version -libre I come here gives the most feedback but i think you can already close the issue.

**Comment by gerardo-junior** [comment]
finally, f-droid updated everything ok with the -libre version
