### ISSUE TITLE
invalid algorithm opening keepass-xc database

### ISSUE THREAD

**Issue by mradzkii** [Kunzisoft/KeePassDX#120]
tried opening one of my keepasscx databases, but it gives Invalid algorithm

**Comment by J-Jamet** [comment]
Links to https://github.com/Kunzisoft/KeePassDX/issues/116
I'll try to fix it in the next version.

**Comment by J-Jamet** [comment]
OK, as said in https://github.com/Kunzisoft/KeePassDX/issues/116, the problem is linked to KeePassXC and the deprecated version of the database and probably will not be fixed, just update the KDF from your database with KeePassXC.
