### ISSUE TITLE
Biometric bug samsung s10

### ISSUE THREAD

**Issue by yakuza8702** [Kunzisoft/KeePassDX#1200]
**Describe the bug**
There will be an error "There too many operation" when changing database in quick succession using biometric and to re enable it again i need to restart the phone.

My database is split in 2 1st is autofill and 2nd is totp. But if i open only one database the bug would not appear only when changing between 2 database where the bug "too many operation" will appear.

Even clearing cache and data would not resolve it only full reboot can resolve it.

**To Reproduce**
1. Go to database 1 choose 1 entry exit
2. Go to database 2 choose 2nd entry
3. Repeat the step for 6 times it happen randomly

**Expected behavior**
Biometric work without the need of restarting the phone

**KeePass Database**
 - Created with: Windows KeePass 2.5

**KeePassDX (please complete the following information):**
 - Version: 3.0.4
 - Build: Free

**Android (please complete the following information):**
 - Device: Samsung galaxy s10+
 - version : Android 11

**Comment by J-Jamet** [comment]
I can't do anything about it, the error comes from the biometric API of your system that manages the storage and distribution of biometric keys. Your system is simply indicating that there are too many operations. The problem will be solved when we can open several databases at the same time, this is planned but will take time to be implemented.

Linked to https://github.com/Kunzisoft/KeePassDX/issues/209

**Comment by J-Jamet** [comment]
Maybe the same as #1269
