### ISSUE TITLE
Support only the four latest major releases

### ISSUE THREAD

**Issue by metonimie** [Kunzisoft/KeePassDX#1203]
**Is your feature request related to a problem? Please describe.**

KeepassDX is a password manager hence contains really sensitive information. It shouldn't support unsupported Android versions anymore since they are completely insicure to use. The latest four major releases are the ones which receive security updates in order to patch known vulnerabilites every month. Run a sensitive application within an insecure environment will open security concerns. Users should not be able to do that.

**Describe the solution you'd like**
Right now, keepassdx still supports Android 4.0.3 (SDK 15). Instead the minsdk should be bumped to skd 28 (Android 9).

**Describe alternatives you've considered**

**Additional context**

**Comment by J-Jamet** [comment]
I don't understand the request. Historically it is the minimum version of Android that is supported, if I increase the minimum version, users of old devices will just be able to install old versions of KeePassDX without the KeePassDX updates. So if your problem is that your phone has an old OS, update it or buy a new device.

**Comment by Ilithy** [comment]
@J-Jamet : I don't think that's it, I think he wants keepassDX to support only the last four versions of Android (so Android 9, 10, 11 and 12) excluding the older ones (preventing the installation of keepassDX on the latter), on a properly secured OS, I don't see any interest in it, the weakness being at the level of the OS, not the software running on it.

**Comment by J-Jamet** [comment]
I get it. But preventing installation on old devices for new versions of KeePassDX would just restrict installation to old versions. So people who can't afford a device or upgrade would just be blocked. What is worse? that the application and the OS are not up to date or that just the OS is not up to date? Also nothing prevents a person from patching himself an OS that is no longer maintained by an external entity.

**Comment by Ilithy** [comment]
> 

I agree, this is also my point of view.

**Comment by grrrrr** [comment]
I'd be of the same opinion as OP, albeit with a bit more support for older devices, that you should only support official supported devices but I totally get your point @J-Jamet, that not everyone can or wants to upgrade phones. Though ~11 years old is pushing it for the life of a device and appears to only have a [0.5% market usage](https://www.appbrain.com/stats/top-android-sdk-versions)

There is one thing you have overlooked

* google play needs a minsdk of 19 (aka Android 4.4) 
* F-droid needs a minsdk of 22 (aka Android 5.1)
* NeoStore needs a minsdk of 23 (aka Android 6)
* Droid-ify needs a minsdk of 23 (aka Android 6)
* Aurora store needs a minsdk of 19 (aka Android 4.4) 

So for those on minsdk 15-18 devices (Android 4.0.3 and 4.0.4) the only way they can get keepassDX is via the releases page on GitHub as they can't install any of the stores.  I don't know if you have stats on this but I would think this subset of users is quite low and it is not obvious that they need to sideload to get keepassDX

So I'd suggest one of two things

1 Bump the minsdk to match Google's requirement,  currently 19
or
2 Add a note on the website that Android 4.0.3 to 4.3 users need to side load the apk from the release page on the repo.

**Comment by J-Jamet** [comment]
> 1 Bump the minsdk to match Google's requirement, currently 19

I have no technical reason to do so at the moment. I will do so if I have code to add that requires new conditions on the old devices, but that code is already there, so until I have that constraint, I see no reason to change the minSDK at the moment. (Unless you've seen a security hole in KeePassDX for an older device and don't want it to be filled with updates.)

>  2 Add a note on the website that Android 4.0.3 to 4.3 users need to side load the apk from the release page on the repo.

I haven't checked to see if the new versions of KeePassDX are still offered on the stores of the old devices. For me, the minSdk you put for each store is the minimum for uploading a new application, not an application whose minSDK has already been defined.
