### ISSUE TITLE
Autofill doesn't work in browsers

### ISSUE THREAD

**Issue by iamrealmarsel** [Kunzisoft/KeePassDX#1206]
Hi there !

**Describe the bug**
Autofill doesn't work in browsers, pop-up doesn't appear on form.
Tested on Chrome 97, Chrome Beta 98, Firefox 95.2, Brave 1.34. 
But autofill works in apps!

**To Reproduce**
1. Go to https://www.chess.com/login_and_go or any other site.
2. Click on username field.
3. Nothing appears.

**Expected behavior**
The appearance of a pop-up with selection of entry, as it works in apps.

**KeePass Database**
 - Created with: macOs KeePassXC
 - Version: 2.6.6
 - Location: Remote file retrieved with GDrive app
 - File provider (`content://` URI): `content://com.google.android.apps.docs.storage/document/acc=2;doc=encoded=...`
 - Size: 2.61 kB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 3.0.4
 - Build: Free
 - Language: English

**Android (please complete the following information):**
 - Device: Huawei PIC-LX9
 - Version: 8.0.0

**Screenshots**

**Firefox 95.2**
![firefox](https://user-images.githubusercontent.com/20097612/150433539-8c959fba-594e-451d-adaf-745bd030144f.jpg)

**Chrome 97**
![chrome](https://user-images.githubusercontent.com/20097612/150433525-3ffebb14-2f9a-4c8f-b461-456f4a6529c6.jpg)

**Brave 1.34**
![brave](https://user-images.githubusercontent.com/20097612/150433534-b2cb6b80-cbf5-42fc-a150-272269cd7753.jpg)

**How it works in app Chess**
![app-step1](https://user-images.githubusercontent.com/20097612/150433544-ebaf8ffe-ea4d-48ab-aaff-9ad1c62f659e.jpg) ![app-step2](https://user-images.githubusercontent.com/20097612/150433532-052375af-974b-4b10-8714-c80cf09f3636.jpg) ![app-step3](https://user-images.githubusercontent.com/20097612/150433536-3e58e5e4-0329-43a9-9f7e-0a53274794b3.jpg)

I use Chrome and would like autofill to work on it.

**Comment by J-Jamet** [comment]
I just tested with all the browsers mentioned on the site https://www.chess.com/login_and_go and I have no problem.
So it means that the KeePassDX code is not at fault. I think there is a problem with the autofill service on your device not working for webviews.
Try rebooting your device, that's the only quick advice I can give. :/ Otherwise maybe update your system.

**Comment by iamrealmarsel** [comment]
Got it, thanks, I'll keep looking for solutions.

**Comment by iamrealmarsel** [comment]
@J-Jamet Hi! I tested a couple of proprietary apps and one of them worked for me, i mean autofill in google chrome. To do this, i had to go to accessibility and enable the app there.

Accessibility menu and result in Chrome:
![access1password](https://user-images.githubusercontent.com/20097612/150606795-727d84a1-9ad7-42ab-b556-5f3c2c73000d.jpg) ![autofill1password](https://user-images.githubusercontent.com/20097612/150606858-a2f5becd-497c-4be9-b50a-bdb60c3e6361.jpg)

This app is 1Password and here on their website it says:
![Screen Shot 2022-01-22 at 12 55 07 AM](https://user-images.githubusercontent.com/20097612/150607157-28de9601-7c0d-42c5-aa2d-aafdabd396c2.png)

Do you have a similar feature ?

**Comment by J-Jamet** [comment]
Accessibility service will not be implemented in KeePassDX for the reasons mentioned in the wiki and the previous issues :
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#why-not-use-the-accessibility-service
https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-629761239

If you do not find a solution with the Autofill service of your device. You can use the Magikeyboard which is made to fill this gap.
https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

**Comment by iamrealmarsel** [comment]
Yes, i started using magikeyboard, thanks
