### ISSUE TITLE
Support for SFTP server as storage

### ISSUE THREAD

**Issue by Larandar** [Kunzisoft/KeePassDX#121]
It's the most important feature in my opinion, as I don't trust my password to anyone but me.

**Comment by J-Jamet** [comment]
Linked to #118

**Comment by J-Jamet** [comment]
KeePassDX uses the connection capacity of your file manager. So we have to find or create file managers compatible with the SFTP protocol.

**Comment by J-Jamet** [comment]
Externalized in https://github.com/Kunzisoft/FileSync/issues/2
