### ISSUE TITLE
References: Faulty resolutions of {REF:U@T:Prefix - Title Name}

### ISSUE THREAD

**Issue by AdrianDC** [Kunzisoft/KeePassDX#1212]
**Describe the bug**
Some of my database entries use references to other entries,
for example the WiFi network name and password for my Smart Life entry.

While used on Linux with KeePassXC, the reference results in correct values.

On Android with KeePassDX, this specific reference breaks completely,
and after extensive tests, I managed to reproduce the issue in the attached database.

The syntax `{REF:U@T:Prefix - Title Name}` breaks KeePassDX's reference and links the first created entry
(my `Prefix - Title Name` with two words after the dash appears to create the bug in KeePassXC every time).

**To Reproduce**
1. Open the database on Linux with KeePassXC for example and check the references of `Group B` / `Application - Network WiFi`
2. See correct `wifiUser` as the user and `wifiPassword` from the `Network - Box WiFi` referenced entry
3. Open the database on Android with KeePassDX and check the same references
4. See faulty `firstUser` as the user and `firstPassword` from the `First created entry` initial database entry

**Expected behavior**
Referenced values should be resolved correctly, the same way as KeePassXC on Linux.

**KeePass Database**
 - Created with: Linux KeePassXC 2.6.6
 - Version: 2.6.6
 - Location: [test.kdbx.zip](https://github.com/Kunzisoft/KeePassDX/files/7929423/test.kdbx.zip)
 - File provider (`content://` URI): /
 - Size: 2.5kB
 - Contains attachment: No

**KeePassDX :**
 - Version: 2.9.13
 - Build: Free
 - Language: French

**Android :**
 - Device: Samsung A40
 - Version: 11

**Comment by J-Jamet** [comment]
You are using an old version of the app. I just tested your database with version 3.1.0 and it works very well, I remember I completely refactored the reference system to avoid problems and optimize performance.
So you just need to update KeePassDX.

(NB : mdp database = "test")

**Comment by AdrianDC** [comment]
Thanks for the feedback !

You are absolutely correct, I was on a 2.9.13 version from February 2021, the latest 3.1.0 release works just fine.

I moved to the GitHub APK a year ago because of an issue not resolved on the PlayStore version,
but I forgot about it since then and thought I was up to date, PlayStore updates being all done,
and also having a "Copyright 2022" in the About screen
(which is probably automatic and not hardcoded).

Should have checked before reproducing the issue with a brand new database and creating the issue.
