### ISSUE TITLE
website favicon or icon

### ISSUE THREAD

**Issue by sheikh-azharuddin** [Kunzisoft/KeePassDX#1214]
**Is your feature request related to a problem? Please describe.**

After entering credential in a website , when keepass is showing the prompt to save the credentials it should also save website icon/favicon or while saving it should fetch from internet just like other password manager such as lastpass.
This will help to identify the credential and website

**Describe the solution you'd like**
Keepass should fetch the icon/favicon from the website while saving it

**Describe alternatives you've considered**

**Additional context**

**Comment by Ilithy** [comment]
Hi,
 (I am a simple user)

The developer does not want to develop a password manager using the internet (in the same way, no online synchronization, which will be done via a separate app), it is a guarantee of security of the data that the application processes, (in the same spirit, it requires the least permissions possible).

For favicons, the developer has made available on the [app website](https://www.keepassdx.com/) a tool to retrieve favicons, download and then simply select them as an icon for the entry.

**Comment by sheikh-azharuddin** [comment]
> Hi, (I am a simple user)
> 
> The developer does not want to develop a password manager using the internet (in the same way, no online synchronization, which will be done via a separate app), it is a guarantee of security of the data that the application processes, (in the same spirit, it requires the least permissions possible).
> 
> For favicons, the developer has made available on the [app website](https://www.keepassdx.com/) a tool to retrieve favicons, download and simply select them as an icon for the entry.

Thanks but again downloading icons for each entry is a painful task...anyway I guess nothing much can be done here...but I still hope if the app can still allow to retrieve website favicon after obtaining user consent or show prompt each time trying to download that way all download will be as per user consent

**Comment by J-Jamet** [comment]
Duplicate #596

**Comment by J-Jamet** [comment]
Indeed, I would like not to add the internet permissions. But if you find a technical solution with autofill, please let me know.
Linked to #1146
