### ISSUE TITLE
kdbx4 tag in kdbx3 database

### ISSUE THREAD

**Issue by keepassium** [Kunzisoft/KeePassDX#1222]
**Describe the bug**

KeePassDX 3.2.0 beta 3 [writes](https://github.com/Kunzisoft/KeePassDX/blob/ba0e87f32a8fb23631d07c8093d778e07f57fb52/app/src/main/java/com/kunzisoft/keepass/database/file/output/DatabaseOutputKDBX.kt#L233) `Meta/SettingsChanged` tag to all kdbx databases. But that tag was introduced in kdbx 4.0, it does not belong to kdbx 3 databases.

**To Reproduce**
1. Open a kdbx3 database
2. Save it

**Expected behavior**
The saved database should not include the `SettingsChanged` tag in the `Meta` element.

**KeePassDX:**
 - Version: 3.2.0 beta 3

**Additional context**

The issue was first reported to me (thanks, Billy!) when KeePassium refused to load a database written by KeePassDX. It seems [this line](https://github.com/Kunzisoft/KeePassDX/blob/ba0e87f32a8fb23631d07c8093d778e07f57fb52/app/src/main/java/com/kunzisoft/keepass/database/file/output/DatabaseOutputKDBX.kt#L233) should be conditional, based on DB format.

**Comment by J-Jamet** [comment]
You are right, this is an issue that was added during the merge functionality. This will be fixed for version 3.2.0 beta4.

**Comment by J-Jamet** [comment]
3.2.0 beta4 is on the Play Store

**Comment by keepassium** [comment]
Thanks, Jérémy. I guess this can be closed, then :)

**Comment by J-Jamet** [comment]
Thank you for reporting this issue
