### ISSUE TITLE
autofill credit/debit card

### ISSUE THREAD

**Issue by sheikh-azharuddin** [Kunzisoft/KeePassDX#1223]
**Is your feature request related to a problem? Please describe.**

Currently only password autofill works but not credit card or debit card field..please add this feature

**Describe the solution you'd like**

Keepass should be able to fill credit card also in website/app

**Comment by uduerholz** [comment]
This feature is already implemented. Which website/app do you use?
Have you entered the credit card data based on the provided template?

**Comment by sheikh-azharuddin** [comment]
> This feature is already implemented. Which website/app do you use? Have you entered the credit card data based on the provided template?

Not working in website and apps..tested in flipkart app and below site
https://www.roboform.com/filling-test-all-fields

Yes i have added the card using template

**Comment by uduerholz** [comment]
The website you linked to doesn't use so-called autofill hints. 
For the autofill to work, the HTML code or the Android App must provide autofill hints (there are some exceptions where the KeePassDX app tries "to guess" which e.g. text input fields to fill, but these exceptions 
do not apply for credit card fields.)
Probably the flipkart app also doesn't provide autofill hints (I haven't checked).

As background info, you can read more here:
https://html.spec.whatwg.org/#autofill
or here:
https://developer.android.com/guide/topics/text/autofill-optimize#hints

As a user of KeePassDX there is not much you can do, I am afraid, except make sure that the autofill service "works" in general.

**Comment by sheikh-azharuddin** [comment]
> 

Ok np then..I will close the case.. Thanks
