### ISSUE TITLE
Improve the message that file manager is required to open existing database

### ISSUE THREAD

**Issue by whereismybugfix** [Kunzisoft/KeePassDX#1224]
Hey all,

First of all, thanks for this great app. It's really hard to think how big audience this app has, how better it is among rivals, and how useful it is for everybody.

I've got potential improvement to cover pretty rare case that can occur if you use debloated device that lacks standard Android "Files" application. In such case if I open the app, I see the message
![SmartSelect_20220130-161802_Video Player](https://user-images.githubusercontent.com/76237634/151722345-06fd176c-4df0-4429-a8d8-0275214d0aca.jpg)
If I click on it, it leads me to a Wiki page [File Manager and Sync](https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync). Which is fine, however, if I'm not that experienced, I wouldn't be able to find what the root cause of the problem is. To help that, I added some information on how to resolve it in the end of the wiki page.

To improve user experience, I would recommend put a little bit more details in the app's message and tell users to check the presence of "Files" on their devices.

**Comment by J-Jamet** [comment]
> To improve user experience, I would recommend put a little bit more details in the app's message and tell users to check the presence of "Files" on their devices.

If one day the default application is renamed and is no longer 'Files', a new version will have to be made just for that. Here the problem is now well explained in the wiki, I find it sufficient, thank you for the doc update. ;)
