### ISSUE TITLE
Updated translations from Weblate

### ISSUE THREAD

**Issue by xesarni** [Kunzisoft/KeePassDX#1227]
I've noticed that some translations from Weblate are not always updated before the new version is released. For instance, the Polish translation was completed 5 days ago (100%), but the newest version of KeePassDX (3.2.0) contains untranslated strings.

**Comment by J-Jamet** [comment]
I merge translations for Beta versions or those in development.
There have been several beta versions for a production version 3.2.0, I just didn't merge for the last build to not integrate any bug.
The translation made in 5 days is very recent, it will be simply added in the next build.
