### ISSUE TITLE
Databases is not synced back to OneDrive

### ISSUE THREAD

**Issue by madlabman** [Kunzisoft/KeePassDX#1228]
**Describe the bug**
I have KeePassDX configured to use database from OneDrive.
The app shows modified date as Jan 16, 2022 but I have a recent updates to the database, e.g. Feb 2.
Nor Save nor Merge options do not trigger uploading updated database.

**Expected behavior**
Database uploaded to the cloud after save.

**Question**
Is there any way to enforce synchronization?
How can I extract cached version of database to not to lose changes were made?

**KeePass Database**
 - Created with: Windows KeePass, version unknown
 - Version: 2
 - Location: Remote file retrieved via OneDrive
 - File provider: `content://com.microsoft.skydrive.content.StorageAccessProvider`
 - Size: 28kB
 - Contains attachment: No

**KeePassDX**
 - Version: 3.2.0
 - Build: Free
 - Language: English

**Android**
 - Device: Galaxy S10e
 - Version: 12

**Comment by J-Jamet** [comment]
> Is there any way to enforce synchronization?
> How can I extract cached version of database to not to lose changes were made?

To both of these questions, I don't know. They must be options in OneDrive, but I don't use that application.

> Nor Save nor Merge options do not trigger uploading updated database.

KeePassDX only reads the information that OneDrive gives it, if there is no new data, it is a behavior of OneDrive (but not the one you want apparently :D).
More information on how it works: https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
I'm thinking about the FileSync application to bypass this kind of problem.

If anyone can give advice on this closed service, it is welcome.

**Comment by J-Jamet** [comment]
The sync must be done separately, an issue is open here: https://github.com/Kunzisoft/FileSync/issues/3
