### ISSUE TITLE
Fingerprint hardware not detected.

### ISSUE THREAD

**Issue by p3yot3** [Kunzisoft/KeePassDX#123]
When attempting to use the fingerprint feature, I get a message saying:  "Can not start this feature. The hardware is not detected".

All other apps work fine with fingerprint.

Android 6 (Mediatek)
Homtom HT20 Pro running Magisk 16.4

**Comment by J-Jamet** [comment]
Typically, when the fingerprint recognition hardware is not recognized it is that the phone does not use the google recognition API but a proprietary system. Can you tell me the name of another downloaded application (preferably open source) for which the fingerprint works? (to see how it works)
I have to solve other problems related to the fingerprint keys, I'll do everything at the same time. #114

**Comment by p3yot3** [comment]
Magisk fingerprint works fine for SU confirmation & is also open source:

https://github.com/topjohnwu/Magisk

Other apps that work but are not open source are Authenticator Plus & Revolut.  Let me know if you need any more info.

**Comment by gradinaruvasile** [comment]
Working open source apps:
AndOTP - this one uses "Device authentication" which includes fingerprint if activated 
Nextcloud (auth only)
Magisk (auth only)

**Comment by simbalion** [comment]
I was able to use the fingerprint feature when running LineageOS but when I went back to OxygenOS (OnePlus 2 Official ROM) I see this error.

**Comment by J-Jamet** [comment]
The Magisk code uses regular FingerprintManager and not FingerprintManagerCompat, I changed the compat classes. Tell me if this version works for you ? : 
[KeePassDX_TEST_2018071001.apk.zip](https://github.com/Kunzisoft/KeePassDX/files/2179802/KeePassDX_TEST_2018071001.apk.zip)

**Comment by p3yot3** [comment]
Yup - that works perfectly!

**Comment by J-Jamet** [comment]
The change has been implemented in the new version 2.5.0.0beta12, tell me if it's OK.

**Comment by p3yot3** [comment]
Yup, that's got it. It now remembers the password when fingerprint is used - great work!

Will test some more......

**Comment by nishp77** [comment]
for me I'm using galaxy s6, I have rooted using magisk the fingerprint is not detected, any solution?
