### ISSUE TITLE
Custom field name translated unexpectedly

### ISSUE THREAD

**Issue by MkQtS** [Kunzisoft/KeePassDX#1232]
**Describe the bug**
I use Simplified Chinese. There is an entry with a custom field name `TOKEN` in my database. The word `TOKEN` is exactly in English with all capital letters, but displayed as `令牌` in the App. `令牌` is just what `TOKEN` means in Chinese. Official Keepass application on Windows can display it correctly.

**To Reproduce**
1. Save a kdbx file with a custom field name `TOKEN`
2. Use Simplified Chinese
3. Open the kdbx file
4. See error: `TOKEN` was displayed as `令牌`

**Expected behavior**
`TOKEN` was correctly displayed.

**KeePass Database**
 - Created with: Windows KeePass 2.50
 - Version: KDBX4.0
 - Location: Local file
 - File provider: com.google.android.documentsui
 - Size: 0.96MB
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 3.2.0
 - Build: f-droid
 - Language: Simplified Chinese

**Android (please complete the following information):**
 - Device: POCO F2 Pro
 - Version: Android 12, MIUI 13

**Comment by J-Jamet** [comment]
This happens because this field is used to generate OTP tokens.
I'll see if I can disassociate the machine translation for this kind of fields.
