### ISSUE TITLE
KeePassDX removes properties from entry

### ISSUE THREAD

**Issue by iamrealmarsel** [Kunzisoft/KeePassDX#1236]
Hi!

**Describe the bug**
On desktop, I use KeePassXC, it adds special info to the properties of entry. This is necessary in order to automatically display the login/password into the site form. When I use KeePassDX and change something in the entry, then after saving, all properties are removed from the entry.

This property is removed:
![Screen Shot 2022-02-11 at 3 23 39 AM](https://user-images.githubusercontent.com/20097612/153519500-60fc370c-cd2d-4ac3-a7b0-d61aacedfa3c.png)

**Comment by iamrealmarsel** [comment]
Yes^ sure

**KeePass Database**
 - Created with: macOs KeePassXC 2.6.6
 - Location: Remote file retrieved with Google Drive app

**KeePassDX**
 - Version: 3.1.0
 - Build: Free
 - Language: English

**Android**
 - Device: Huawei PIC-LX9
 - Version: 8.0.0

**Comment by J-Jamet** [comment]
Bug fixed in 3.3.0
