### ISSUE TITLE
Repair utility for corrupt database

### ISSUE THREAD

**Issue by Jrchintu** [Kunzisoft/KeePassDX#1240]
**Is your feature request related to a problem? Please describe.**
Recently my database got corrupted after saving it, i had added 200byte file as an attachment and saved db. But after trying to unlock database i used to get this message:
`No memory to load your entire database`
Despite having 2GB free ram.

**Describe the solution you'd like**
Since i had encountred such situation, same can happen with others too. Also official keepass for windows provide a utility to repair such corrupt db and one can repair the corrupt database (if computer is acessable). it would be good for user to have a quick solution to attempt to repair database (incase of unacessablity to pc) while in sudden hurry for password. so i request to add something internally or externally for repairing corrupt database

**Describe alternatives you've considered**
There are currently no better possible alternative than repair utility, still basic reference to quick corrupt repair tools can be provided

**Additional context**
This if full error:
`E/com.kunzisoft.keepass.activities.PasswordActivity(24503): No memory to load your entire database. java.lang.OutOfMemoryError: Failed to allocate a 757935424 byte allocation with 25165824 free bytes and 507MB until OOM, target footprint 29878800, growth limit 536870912`

**Comment by J-Jamet** [comment]
I don't know what your miracle utility is, but in practice, a database can be corrupted in many ways. In the case of insufficient memory, I think the KDF runs and never finds the right decryption key so it saturates the memory doing loops.

If the decryption key can't be found, I don't even see how to initiate a content repair.
In most cases, the program already tries to automatically reformat the content to order and compress it at each save. But if you give other technical tricks than the ones already in place, I'm willing to implement them.

For me, the solution is simple and consists in making regular backups https://github.com/Kunzisoft/KeePassDX/wiki/Backup
