### ISSUE TITLE
Only one KeePassDX app in the Play Store

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1257]
I have several pieces of feedback that indicate that the presence of multiple KeePassDX apps on the Play Store is confusing, which I understand very well.
So I've been thinking about the problem and I figure it's time to replace the KeePassDX Pro app with a contributor app that will unlock themes from the main KeePassDX app and will also unlock future content from new other apps.

Benefits :
 - Better understanding for new users.
 - No need to export settings when purchasing the pro version
 - Unlocks future content of new applications that will be deployed (ie: all closed APIs of the FileSync application. See https://github.com/Kunzisoft/KeePassDX/issues/840#issuecomment-955169250)
 - Facilitates the deployment of KeePassDX, which will save me a lot of time that I can allocate to the creation of new features.

Inconveniences:
- Current users of the Pro version will have to download KeePassDX and remigrate the settings to the normal version.

So I wanted to ask you if the redownloading of the normal version was a major block for users of the Pro version?

**Comment by Ilithy** [comment]
Hi,
for me (owner and user of the pro version and the Libre version of Fdroid) it does not bother me, especially since the addition of the import/export of the properties of the app, No problem

Small subsidiary question, would it be possible to add to the Free and Libre versions of fdroid and github a key system (users could buy it on your site), to upgrade it to Pro which will allow to unlock all the elements of the pro version? (the themes, but also totp code and future "premium" features?
This would be extra for users without the google play store, but wanting the pro version of keepassDX.
_[InviZible Pro app developer's uses this](https://github.com/Gedsh/InviZible)_

**Comment by J-Jamet** [comment]
Okay, thanks for the answer.
The integration of validation code would require a server connection to check the validity. Here, I think there is no need, the new integration of the procedure I provide will unlock the Steam TOTP in the Libre version (I had visually disabled the Steam selection because I think it should follow the standards but the token generation algorithm works in any case) so the Pro version will also be with the Libre version.
But it's psychological because there are all the features of KeePassDX in any case.

**Comment by Ilithy** [comment]
Thank you for this answer, it's nice to hear.
So that said, I can only see the advantages of your simplification idea.

**Comment by uduerholz** [comment]
I am not sure I understand your proposal. If you replace the pro version with a contributor app, there will still be two apps in the play store, right?
How will this technically work? How do you want to unlock future content?

Maybe it's even easier to have only one app with all features (in the play store and f-droid) and find some
other way for people to contribute financially.

**Comment by J-Jamet** [comment]
Technically, there will be two applications but the pro version will only be a thank you activity. I had thought of simply checking the presence of the pro version with the id package when starting KeePassDX. If it is the case, a preference is saved and you can even delete the contribution application.

For future open source applications, the principle remains the same and there is no need to deploy two applications each time. 

(Also, I would like to make it clear that all the features are present in the basic package. Pro or contribution app is only to help, and it only unlocks visual content.)

**Comment by J-Jamet** [comment]
Technically, there will be two applications but the pro version will only be a thank you activity. I had thought of simply checking the presence of the pro version with the id package when starting KeePassDX. If it is the case, a preference is saved and you can even delete the contribution application.

For future open source applications, the principle remains the same and there is no need to deploy two applications each time. 

(Also, I would like to make it clear that all the features are present in the basic package. Pro or contribution app is only to help, and it only unlocks visual content.)

Another advantage. For the uneducated users who download paid applications from obscure stores to get them for free will not come across a corrupted, virus filled KeePassDX Pro program if it is already installed with the normal version from the Play Store.

**Comment by uduerholz** [comment]
Probably many users of the pro version will not read this issue here.

**Comment by J-Jamet** [comment]
Surely but I can only do my best to communicate. Otherwise I can make an intermediate pro version which will indicate this migration at startup.

**Comment by uduerholz** [comment]
Yes, I think that's a good idea.

**Comment by anonymous-user** [comment]
I am fine with this solution. I already use other apps that function similarly with the main free app and then an unlocker pro app. 

Having to move settings between the Pro and Free version is an inconvenience but not a deal breaker.

**Comment by J-Jamet** [comment]
> The question is, in the case of reinstalling the application, do I always have to have a backup of my KeePassDX (Pro) configuration?

No, you don't have to import any configuration specifically. It's just so you don't have to reconfigure everything during the migration because there are a lot of settings.
Concretely, main KeePassDX app automatically switches to Pro version internally if it detects the Contributor Pro application (which is still KeePassDX Pro since Google has not yet validated the changes)

It doesn't change the payment methods, it's just that the paid application is now just a content unlocker.

**Comment by gabeweb** [comment]
> (...) that the paid application is now just a content unlocker.

Ok, so, it's necessary install the new KeePassDX before uninstall the old KeePassDX Pro.

**Comment by J-Jamet** [comment]
Yes

**Comment by JohnLGalt** [comment]
I just did this, and all seems well. After importing the settings exported from DX Pro, the regular app immediately showed Pro and everything was preserved.

Thanks!

**Comment by anonymous-user** [comment]
My Pro app just updated to the contributor app. Also I noticed a couple minor things:

1. The contributor app still has a beta program. Don't know if this is still necessary. 

2. It still registers as an auto fill app. So now we can select either KeePass or the Contributor app.

**Comment by J-Jamet** [comment]
The current version still allows you to use all features in case an automatic upgrade is performed, so you can still unlock a database offline. The next version of Contributor Pro will be much lighter and will contain only what is necessary. I plan to make the full transition in 1 month, to give users time to migrate.
Beta is not necessary anymore, it's just a transition during the migration, I will disable it.

**Comment by dhammel** [comment]
@J-Jamet Is the Contributor Pro part of the KeePassDX src? It's not listed as a build variant. Checking the src manually, I do not even see references to it, unless I overlooked. 

Do you have any other way of users donating to you outside of google play? Maybe through PayPal, CryptoCurrency like btc or xmr? Some people, especially those with Huawei devices or those who have de-googled devices don't have play store.

**Comment by J-Jamet** [comment]
@dhammel 

> Is the Contributor Pro part of the KeePassDX src?

Yes, the source code is in this branch : https://github.com/Kunzisoft/KeePassDX/tree/Pro_to_contribute I will probably remove all the code related to the database opening, it will make a very light APK.

> Do you have any other way of users donating to you outside of google play? Maybe through PayPal, CryptoCurrency like btc or xmr?

Yes, of course : https://www.keepassdx.com/#donation

For unlocking themes after a donation by paypal or cryptocurrency, don't hesitate to send me an email, I will send you the procedure for the Libre version. _(I'm thinking of making an auto system with a zero knowledge proof procedure but I haven't implemented it yet.)_

**Comment by dhammel** [comment]
> Yes, the source code is in this branch : https://github.com/Kunzisoft/KeePassDX/tree/Pro_to_contribute I will probably remove all the code related to the database opening, it will make a very light APK.

It does appear that I overlooked then. I do believe that removing all unnecessary code overtime would be a good thing.

> For unlocking themes after a donation by paypal or cryptocurrency, don't hesitate to send me an email, I will send you the procedure for the Libre version. (I'm thinking of making an auto system with a zero knowledge proof procedure but I haven't implemented it yet.)

I already have access to the contributor apk via google play as well as I've now self-compiled it, so I will be donating just to say thank you :)

Currently waiting for f-droid to update from 3.3.1 to 3.3.2, then I will switch to that as to avoid having to self-compile it after each update.

**Comment by cbiere** [comment]
When KeePassDX Pro was missing on my phone this morning, I was pretty irritated. Then I checked my playstore library and recognized the app by its green icon and realized the name had changed. Maybe I didn't get the memo. IMHO, it would have been optimal migrating in smaller steps: first push an update that announces the upcoming changes, then later push another update changing the name but keeping KeePassDX in it and finally changing the name and removing the unnecessary, duplicated functionality. Not a complaint, just my opinion.

**Comment by J-Jamet** [comment]
Currently, the Contributor Pro application still has all the functionality it had before (as KeePassDX Pro). So it is possible to use the application even if the dialog is displayed every time.
I changed the name maybe too quickly but at least it allows users to see the change (for users who don't often open their database, they can at least visually see a change with the automatic updates).
I thought a lot about how to make this migration smoothly but there is always a time when current users have to migrate so I might as well do it as soon as possible.

**Comment by J-Jamet** [comment]
The new Contributor Pro 4.0 update is much lighter, allows one-click export of settings and there are no longer services with the same name for Autofill and Magikeyboard.

**Comment by Eyion** [comment]
Are the features of the free and premium versions the same? Or, does the premium version have more features?

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#what-is-keepassdx-pro--contributor-pro

It has the same features. With access to non-standardized or non-free protocols. The main goal is to help KeePassDX developments, without that, no new feature or bug fix.

I know that people are used to free stuff in exchange of their personal data but I realize that people just don't understand the importance of supporting open source projects (especially in security applications) and the work behind it.
