### ISSUE TITLE
Google 2FA support

### ISSUE THREAD

**Issue by TippyLion28** [Kunzisoft/KeePassDX#1258]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support Google 2FA TOTP codes

**Describe alternatives you've considered**
N/a

**Additional context**
I can't imagine this hasn't already been asked for before, but couldn't find anything in issues

**Comment by uwekoegel** [comment]
TOTP is allready supported checkout the wiki: https://github.com/Kunzisoft/KeePassDX/wiki/OTP

**Comment by TippyLion28** [comment]
I am stupid :) thank you
