### ISSUE TITLE
App doesn't show new entries after adding them on desktop

### ISSUE THREAD

**Issue by DavidKutu** [Kunzisoft/KeePassDX#1259]
**Steps to reproduce**

1. Create database with one entry on desktop (KeePassXC)
2. Save database on cloud storage (Dropbox)
3. Install KeePassDX and open database
4. It works
5. Add an entry on desktop
6. Wait for cloud storage to update
7. Open KeePassDX
8. New entry is not displayed

**Comment by J-Jamet** [comment]
KeePassDX only opens and edits the data provided by the content provider of the Cloud application you use. Try to delete the cache of the Cloud application, it should solve your problem.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

Linked #1235 #840 #342
