### ISSUE TITLE
Placement of "open" button collides with fingerprint sensor

### ISSUE THREAD

**Issue by SeWieland** [Kunzisoft/KeePassDX#126]
I'm currently using a Galaxy S5 where it is still necessary to swipe over the fingerprint sensor.
Therefore, I'm always hitting the "open" button with no password entered first, resulting in an error message.

![phone](https://user-images.githubusercontent.com/26410655/40834060-04c53a76-6590-11e8-8834-63cadab787cb.png)

This is pretty annoying and actually preventing me from switching from keepass2android.
I think there are quite some more phones in use, which have their fingerprint sensor placed very near to that button.
Could there be some option implemented to grey out the opening button if no password is provided?

**Comment by J-Jamet** [comment]
No problem, I can implement this feature.

**Comment by J-Jamet** [comment]
Ok, developments for this feature are complete, it will be available in the next update.
![screenshot from 2018-06-25 10-30-17](https://user-images.githubusercontent.com/19224038/41839687-2fbf0e8c-7864-11e8-9e57-7f3ea14123e6.png)
![screenshot from 2018-06-25 10-32-06](https://user-images.githubusercontent.com/19224038/41839694-344da698-7864-11e8-8813-2818620f7dc3.png)

**Comment by J-Jamet** [comment]
The feature is available in the version 2.5.0.0beta12
