### ISSUE TITLE
How to use advanced unlock?

### ISSUE THREAD

**Issue by lollita** [Kunzisoft/KeePassDX#1260]
I would to use "Device credential unlocking" with schema (not fingerprint) but when I open the database, it not have any "advanced unlock prompt by clicking the advanced unlock button".
Why? How to do?

**Comment by J-Jamet** [comment]
> Why?

I don't know,  you did not indicate any reproduction procedure, nor the version of KeePassDX, nor the device you are using.


> How to do?

https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

Have you set up a secure lock system with scheme for your device?

**Comment by lollita** [comment]
Last version KP.
Android 9.
I tried to follow those instructions.
Yes, I Have set up a secure lock system with scheme for my device.
I have to swith with a gesture to unlock my device.

**Comment by lollita** [comment]
After device rebbot it works! ty.
