### ISSUE TITLE
Empty the Magikeyboard memory when the main service is killed

### ISSUE THREAD

**Issue by dmework** [Kunzisoft/KeePassDX#1261]
Automatically switch back to the previews keyboard when KeepassDX is closed through pressing "close all" in android

**Comment by J-Jamet** [comment]
"Close all" kills open applications without sending an event. I recommend you to use the notification to close the database, either the lock button (which sends a close broadcast).
For the keyboard to be emptied on an application kill, the keyboard service would have to be the same as the database service, which is not the case.
The keyboard timeout feature is there to solve this problem.
I will however think about a way to empty the keyboard in case of an application kill but I need to do a feasibility study.
