### ISSUE TITLE
I not see the crossed out key

### ISSUE THREAD

**Issue by lollita** [Kunzisoft/KeePassDX#1262]
> It is possible to delete the encrypted unlocking content of a database with the "crossed out key" icon.

I not see this icon. Where it is?

**Comment by J-Jamet** [comment]
On the credentials screen of a database, if your screen cannot display the whole menu, on the three dots and  you can see "Delete advanced unlock key" but you won't see the icon.

**Comment by J-Jamet** [comment]
I'm just updating the wiki.

**Comment by lollita** [comment]
ty
