### ISSUE TITLE
ability to Select multiple entries from search and preform copy,  cut , and delete

### ISSUE THREAD

**Issue by Onering20** [Kunzisoft/KeePassDX#1263]
**Is your feature request related to a problem? Please describe.**
I had migrated my passwords from my browsers and by default they all end in one folder. I am trying to consolidate passwords from the same website (www.sample.com, login.sample.com, secure.sample.com)  [search multi-select & delete]

Follow up with sorting into a logical folder structure [search multi-select & cut|copy]

And finally Update [works fine]

**Describe the solution you'd like**
I would like to be able to long press to start a multi-select in the search results and have the options in the . . . Menu to perform the copy cut and delete operations 

**Describe alternatives you've considered**
Alternatively being able to set a text filter on the database view to narrow down the visible entries and use the already implemented copy cut and delete operations

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/891

**Comment by deepu2** [comment]
Yes, it makes it much easier to manage the database
