### ISSUE TITLE
Database file not syncing through Dropbox

### ISSUE THREAD

**Issue by Android-X13** [Kunzisoft/KeePassDX#1264]
After I installed KeePassDX, I opened my already existing database file from the Dropbox storage and everything was fine (all entries were as expected).

However any changes I make through KeePassXC on my computer do not reflect in KeePassDX. For example I created a "Test" entry via KeePassXC, saved/closed the database, made sure that Dropbox picked up the changes in the db file, and then opened KeePassDX on Android but the entry has not been added.

Dropbox is connected and working in both machines, Internet connection is working. I also verified though Keepass2Android, which immediately picked up the changes and the Test entry was visible.

What I tried:
- Reloading the database from inside KeePassDX
- Merging the database from inside KeePassDX
- Manually removing the database from KeePassDX history and re-opening it
- Deleting KeePassDX cache
- Deleting KeePassDX data

But the Test entry is never shown.

On the other hand if I make a change via KeePassDX and save the database, this is reflected in KeePassXC on the computer.

KeePassDX 3.3.1 (libre build from F-Droid)

**Comment by J-Jamet** [comment]
Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/1235

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
https://github.com/Kunzisoft/KeePassDX/issues/840
https://github.com/Kunzisoft/KeePassDX/issues/342

The problem comes from the Dropbox application. Clear the cache of this application.

**Comment by J-Jamet** [comment]
> So my understanding is that Keepass2Android uses proprietary Dropbox API to circumvent this problem, is that correct? If yes then it's good that you don't implement it... as long as there is some way to make cloud/remote sync work.

Yes. The solution to using proprietary cloud services that do not properly implement their file provider is to create a separate file manager application that implements the API. https://github.com/Kunzisoft/FileSync/issues/5
