### ISSUE TITLE
Cancel Advanced Unlock keys on quit

### ISSUE THREAD

**Issue by strider72** [Kunzisoft/KeePassDX#1265]
Quitting the program (square Android button and swipe up), or reboot, should cancel any Advanced Unlock keys.

I generally expect an outright quit, or a system reboot, to lock apps down a bit. I was surprised when quitting KeepPassDX didnt kill the Advanced Unlock.

Please and thank you! :-D

**Comment by J-Jamet** [comment]
The functionality has already been developed, it is the temporary advanced unlocking. (_Settings - Advanced unlocking - Temp advanced unlocking_)

> Quitting the program (square Android button and swipe up

Square Android button and swipe up does not leave an application, it removes the content of the RAM for the current activity. If a background service is available (like for KeePassDX), it remains active.
You need to remove the service from the temporary advanced unlock, for that you just have to press the corresponding notification.

>  or reboot, should cancel any Advanced Unlock keys.

This is the case for temporary advanced unlocking.

> I generally expect an outright quit, or a system reboot, to lock apps down a bit. I was surprised when quitting KeepPassDX didnt kill the Advanced Unlock.

The phone's keystore is a secure area of the device and is not deleted at every reboot.
https://developer.android.com/training/articles/keystore

**Comment by strider72** [comment]
Maybe I'm not understanding.  When Temporary Advanced Unlocking is turned on, when exactly does it relock?  Under what circumstances?

**Comment by J-Jamet** [comment]
> When Temporary Advanced Unlocking is turned on

It depends on what you mean.
For the feature: when you activate it in the settings.
For the service instance: when the first database is linked to a biometric or a device credential

> when exactly does it relock?  Under what circumstances?

I don't understand what you mean by relock. 
If you are talking about deleting keys in the temporary service: when you press the notification to clear the service data or when the service is stopped in any way (e.g. when rebooting the device)

**Comment by strider72** [comment]
I'll rephrase: what is the functional difference between turning on Temporary Advanced Unlocking in settings vs not doing so?

**Comment by J-Jamet** [comment]
**Norman Advanced Unlocking** : Stores encrypted biometric (or device unlock) keys in the secure [KeyStore](https://developer.android.com/training/articles/keystore) of the device, remains in this memory until the key is manually deleted, or if the application is uninstalled.

**Temporary Advanced Unlocking** : Creates a temporary service that contains the encrypted biometric (or device unlock) keys in a temporary database included in this service. It allows to delete the biometric keys simply if the service is stopped (for example after a timeout or after a click on the notification or if the device is stopped).

In both cases, the deletion of keys by database file is done from the KeePassDX menu.
