### ISSUE TITLE
Always switch to last keyboard when searching Magikeyboard entry and back

### ISSUE THREAD

**Issue by rugk** [Kunzisoft/KeePassDX#1267]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use the magikeyboard, because I need to select an entry.

Because when I do that, I need to do the following:
1. I select the Magikeyboard and tap on that key icon or whatever it is…
2. I click into the search field (because you really cannot expect me to scroll though that huge list of passwords by hand, can you?).
3. I now see that the MagiKeyboard is still enabled... -> I need to switch it back to my default one.
4. I find and select my entry.
5. I am back and the keyboard opens. I now see that my default keyboard is selected even though I obviously want to continue with filling in my password. -> I need to switch back to Magikeyboard.
6. I press the corresponding buttons to fill in my password.

**Describe the solution you'd like**
Step 3 and 5 could be omitted as they are just annoying, i.e. automatically switch back and forth between my keyboard during magikeyboard usage. While we are it, maybe also step 2 (the search input could be pre-selected, but that's another topic and maybe would be good to be as an IMHO opt-out setting).

Actually, this should involve two things:
* When the keyboard is used in KeePassDX itself, and it is a magikeyboard you may _always_ switch back to the previous one. I see just no use case for not doing so – after all, what do you want to do there, fill a password from KeePassDX into itself? 🤪
* When the "Magikeyboard selection screen" is closed, always switch back to the Magikeyboard again. Again this can be done always, no matter how much the user may have manually switched in between. I as a user, obviously want to continue what I just did when I exit that screen (via selecting an entry at least, if I cancel it or do sth. else somehow, I obviously do _not_ want that), i.e. fill in my password etc.

**Describe alternatives you've considered**
Manual keyboard switching, which is annoying and a bad UX IMHO.

**Additional context**
🤷‍♂️

**Comment by J-Jamet** [comment]
> When the keyboard is used in KeePassDX itself, and it is a magikeyboard you may always switch back to the previous one. I see just no use case for not doing so – after all, what do you want to do there, fill a password from KeePassDX into itself? 🤪

Imagine your second point is not feasible and the user unlocks the database with a fingeprint.
Imagine a new feature is developed and it's possible to open two databases at the same time and the first one contains the main credential of the second one.
But I agree, it is a parameter to add and activate by default.

> When the "Magikeyboard selection screen" is closed, always switch back to the Magikeyboard again. Again this can be done always, no matter how much the user may have manually switched in between. I as a user, obviously want to continue what I just did when I exit that screen (via selecting an entry at least, if I cancel it or do sth. else somehow, I obviously do not want that), i.e. fill in my password etc.

Same #643
#311

**Comment by rugk** [comment]
> Imagine your second point is not feasible and the user unlocks the database with a fingeprint.

I fail to see what a fingerprint changes here. Fingerprint unlock can be done without any involvement of any keyboard.

> Imagine a new feature is developed and it's possible to open two databases at the same time and the first one contains the main credential of the second one.

Well… yeah… in two windows or so, that could be a problem. But well… if a new feature is being developed this needs to be taken into account obviously. We cannot speculate about future problems, if we don't even know how it _may_ look (there are many ways I could imagine for such a feature's UX). In the worst case, one just needs to disable this feature here if the other one is enabled…

**Comment by J-Jamet** [comment]
> fail to see what a fingerprint changes here. Fingerprint unlock can be done without any involvement of any keyboard.

The user stayed on the magikeyboard and didn't need to switch because he uses the fingerprint unlock. If we force him, he will have to reswitch manually.

> We cannot speculate about future problems, if we don't even know how it may look

I have to think about future features to design an application and create the code architecture.

**Comment by J-Jamet** [comment]
I would even say that anticipating the problems is mandatory to be a good developer.

**Comment by rugk** [comment]
> The user stayed on the magikeyboard and didn't need to switch because he uses the fingerprint unlock. If we force him, he will have to reswitch manually.

I guess we have a misunderstanding here, because actually I used biometric unlock when I had this issue… 😖

Yeah, sure, anticipating problems is good, sure. The thing is just whether we need to solve it right now or can safely say it is a topic for later. (As said, at worst just disable the feature if there is a conflicting feature, I see nothing wrong with that – there is one more feature users can use when they can. We don't even know yet how many users would want two DBs opened at the same time.)

---

So about fingerprint unlock, I guess you mean I needed to enter my password. But no, the issue is about an already open DB (i should have probably clarified that)…

Between 1. and 2. there is no password screen, there is just me wanting to search for my password… and having
The problems arising with the password input that could be between 1. and 2. are indeed ones that may need to be taken into account. Though… I'd say you can also switch to the default keyboard then, nobody wants to use the magikeybord for entering passwords in KeePassDX itself – unless (and that may be a legitimate rare use case) you have weird ways of "chaining" DBs, i.e. you store passwords of different KDXDB's in a KDXDB.

(just thinking out loud)

**Comment by J-Jamet** [comment]
Indeed, I misunderstood your workflow, I omitted the search, I thought it was to enter the credentials with the keyboard.

In any case, I agree it is to be improved, I will add a setting so that the keyboard changes itself when arriving at the credential screen and a direct keyboard change when the search field is selected.

I was also thinking about a method to send the applicationId directly in the selection mode to avoid searching.

**Comment by rugk** [comment]
> I was also thinking about a method to send the applicationId directly in the selection mode to avoid searching.

That would not work for browsers with websites, would it?

Anyway, of course a good – though kinda separate – idea.

**Comment by J-Jamet** [comment]
> That would not work for browsers with websites, would it?

At the moment, I don't know, it would use the [EditorInfo PackageName](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#packageName), but I haven't tested it yet to know what it really returns depending on the application. Chances are it will return the browser package and not a URL.
But since there is already a method for the web domain of a browser it doesn't matter. https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard#usage-c
