### ISSUE TITLE
Fingerprint problem: Failed to delete entry

### ISSUE THREAD

**Issue by Therhokar** [Kunzisoft/KeePassDX#127]
Fingerprint not working, showing "Failed to delete entry: com.kunzisoft.keepass.fingerprint.key" when entering the password.
Version: 2.5.0.0beta11-libre
Device: Xiaomi MIX 2
System: LineageOS 15.1
File location: Android/data/com.kunzisoft.keepass.libre/Storage/

**Comment by J-Jamet** [comment]
Seems to come from google API, it's weird, no entries should be deleted while password is being entered. I'll look in more detail with other fingerprint issues.

**Comment by wh0isit** [comment]
Nexus 6P w AICP (Lineage based) 8.1.0 here.
Any chance you have a rom setting toggled to bypass the PIN entry on device reboot? Ever since disabling that, I've had no issues with KP.
Before that I could fix it temporarily by visiting android settings / security / fingerprint. (Then enter PIN).

**Comment by Therhokar** [comment]
Nope. Nor can I temporarily fix by entering the PIN in "Fingerprint".

**Comment by J-Jamet** [comment]
Can you tell me if this APK [KeePassDX_TEST_2018071001.apk.zip](https://github.com/Kunzisoft/KeePassDX/files/2179802/KeePassDX_TEST_2018071001.apk.zip) solve your problem ?

**Comment by Therhokar** [comment]
Not from a direct update. Reinstalled it and now it works fine.
