### ISSUE TITLE
Show totp in 2-digit grouping

### ISSUE THREAD

**Issue by Bugaddr** [Kunzisoft/KeePassDX#1270]
**Is your feature request related to a problem? Please describe.**
Reading things by breaking it in parts make it easy to remember, since currently totp are shown as 6 digit grouped, it seems sometime hard to remember in hurry. Breaking it in 3 parts with 2-digit each makes it easy to remember while typing (incase you dont want to use clipboard)

**Describe the solution you'd like**
Totp can be shown in group of three 2-digits-number.

**Describe alternatives you've considered**
No visible alternative currently.

**Additional context**
Same approach has been used by [aegis](https://github.com/beemdevelopment/Aegis) app, also remember to add no changes to default copy-paste behaviour, many site dont support whitespace in totp.

**Comment by J-Jamet** [comment]
To keep the same convention as Aegis, I think it is better to divide every 3 digits.

**Comment by Bugaddr** [comment]
Thanks @J-Jamet i will close this issue by quotting https://github.com/Kunzisoft/KeePassDX/commit/3f6a6c864aba5b308f374398e77a43656a8817fe as solution, thanks :).
