### ISSUE TITLE
Create screenshots for XDA thread

### ISSUE THREAD

**Issue by giwrgosmant** [Kunzisoft/KeePassDX#1275]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Hello @J-Jamet, I want to suggest to create an [XDA thread in Apps section](https://forum.xda-developers.com/f/android-apps-and-games.530/) to let more people know about KeePassDX and get extra feedback maybe. What do you think about it? 🤔

**Comment by J-Jamet** [comment]
I will probably not be as active in answering questions as I am on Github, but if it allows users to better understand how the application works, I have no problem with it.

**Comment by J-Jamet** [comment]
https://forum.xda-developers.com/t/app-4-0-keepassdx-open-source-password-manager.4417803/

**Comment by giwrgosmant** [comment]
> https://forum.xda-developers.com/t/app-4-0-keepassdx-open-source-password-manager.4417803/

That's perfect, I am Recognized Contributer & Translator with name Retrial in XDA.
I will try to help with questions as much I can and I am knowledge.
If you want also reserve #2 and maybe #3 for feature OP post or for Screenshots etc.

**Comment by J-Jamet** [comment]
OK, I'll do it when I have time, I have to redo the screenshots for the next deployment in any case.
