### ISSUE TITLE
Option to hide Created/Modified and History from entries

### ISSUE THREAD

**Issue by caveman1973** [Kunzisoft/KeePassDX#1278]
I think it would be cleaner to not show that much information. 

Since the information might come in handy under some exceptions, not removing, just hiding it would be great. 

Please add an option under Settings.

**Comment by J-Jamet** [comment]
The beta version 3.3.3 allows to separate this information in two different tabs. Have you tried it?

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/commit/5282deb08897b9393e3ada3347ddcc799a3b8134

**Comment by J-Jamet** [comment]
As I implemented a similar concept in version 3.3.3, I close this issue.
