### ISSUE TITLE
Contribute modal gets in the way of actually enabling a feature

### ISSUE THREAD

**Issue by xenithorb** [Kunzisoft/KeePassDX#128]
"This **visual feature** is available thanks to your generosity" ...

User-wise this is really confusing. Given the word "available," I'm going to go ahead and assume that you didn't sprinkle in features that don't work just to pop up a "pay us" button? 

Assuming that this is just a bug, then the problem is that this pop-up prevents the option selection from actually activating. 

For example:

1. Form filling -> Magikeyboayd (sic) - Slightly different wording than above but still can't enable the feature (note the spelling error in Magikeyboayd as well) 

2. Appearance -> Select a theme -> { Classic Dark Theme, Red Volcano Theme, Purple Pro Theme }  - these themes pop-up the contribute modal that only allows you to press cancel or contribute and then doesn't actually change the theme.

**Comment by J-Jamet** [comment]
The visual features are available in the application KeePass DX Libre after performing a key combination or directly in KeePass DX Pro. It's just to have cool visuals after helping me and encourage to go on F-Droid. I said it in the readme, the basic features remain free... I give the trick of unblocking themes to contributors, do not hesitate to send me an email if I forgot or look at the source code. ;)

KeePass is in beta, and as it is written in the popup, I am on the development of the Magikeyboard feature, and it's not so easy and take time, it will be available when it is completed and tested. The explanation of the popup is not clear for you? How would you formulate it?

This open source project, I do it on my free time by coding what the users ask, so I encourage users to contribute for the features they ask me. And I provide themes (which may not be there) as a bonus. If my goal was to make money, I would have made a mini game with closed code full of ads. But you're right, I don't know why I don't do like everyone else, it's easier ... :/

**Comment by xenithorb** [comment]
It's the theme one that confuses me. "This visual feature is available thanks to your generosity" 

Frames it more as "Hey people contributed and I made this, so it'd be cool if you contribute to", and then you'd expect it to work anyway. It doesn't really, in my opinion, convey the "Hey you _need to give me money_ in order to use this feature" message - which is totally fine, there's nothing inherently wrong with that, I just legitimately thought it was a bug. 

The other one, for Magickeyboard "This feature is under development and **requires** your contribution to be available soon," (emphasis mine in this case) is clearer now that you've explained the intention, but given the previous experience with the Themes as I explained in the prior paragraph, I think that mentality lingered onto trying to turn on this feature so I assumed the same thing.

Once again there's nothing wrong with being paid for your work or asking for donations (which is essentially what you're doing) and I thank you for putting up your work on F-Droid and making it available the world.

**Comment by J-Jamet** [comment]
Thank you for the feedback, in this case I would change the comments of the popups to be more precise and avoid confusion. Otherwise, there are many ways to contribute that are also excellent, there is the donation, feedback, translations or contributions to the code, any help is ok! :)

**Comment by nate2014jatc** [comment]
Pardon, but did you actually say that you explicitly hid the method for accessing functionality behind a pay-wall?
This is not mentioned anywhere in your F-Droid description.

> are available in the application KeePass DX Libre after performing a key combination or directly in KeePass DX Pro.

> I give the trick of unblocking themes to contributors,

**Comment by J-Jamet** [comment]
No, I'm not saying that. I repeat but no functionality is hidden! I simply add completely optional and additional themes to contributors (translation, code creation, donation or any help).
What functionality do you think is hidden? Everything is open source, you can check.

**Comment by Ilithy** [comment]
Excuse me, I am for the support of projects like yours, which is excellent, and I agree with your idea of a slight added value to thank your donators.
But it's true that the popup window that appears  when you change the theme in the free version is not very explicit, at least in french, Nowhere does it say that this option is paid for, until you're on the awning.

here is the popup (in fr):

"Contrairement à beaucoup d'application de gestion de mot de passe, cette application est sans publicité, libre sous licence copyleft et ne collecte pas de données personnelles sur ses serveurs peu importe la version que vous utilisez."

(En, translate)
"Unlike many password management applications, this application is ad-free, free under copyleft license and doesn't collect personal data on its servers no matter what version you're using."
The button displays download, and redirects to the paid version of KeepassDX.

It would be a clear statement of your intent to do so:

(Fr)
"Contrairement à beaucoup d'application de gestion de mot de passe, cette application est sans publicité, open source sous licence copyleft.
Néanmoins, pour continuer à développer KeepassDX (ce qui prend énormément de temps et de travail), certaines options optionnel, tel que les thèmes, ne sont accessible uniquement aux personne soutenant le projet, en achetant la version pro. Aucune données personnelles n'est collectées, sous quelques formes que cela soit, peu importe la version (gratuite ou pro) que vous utilisez."

(Avec un bouton soutenir, qui redirige comme le précédent)

(En, translate)

"Unlike many password management applications, this application is ad-free, open source and copyleft licensed.
Nevertheless, to continue developing KeepassDX (which takes a lot of time and work), some optional features, such as themes, are only available to the people supporting the project, by purchasing the pro version. No personal data is collected, in any form whatsoever, no matter which version (free or pro) you use."

(With a support button, which redirects like the previous one)

What do you think?

(PS: I don't want a key, I already bought the pro version ;-))

Thank you.

**Comment by nate2014jatc** [comment]
I agree with @Ilithy, I appreciate the work you have done here, and I wholeheartedly support donation buttons, but the way the text reads in English is also misleading.
I apologize if I came off as rude, I was simply taken aback by the idea of a pay wall in an F-Droid app.

If I may, I would suggest a change to the modal text in English to more closely resemble llithy's suggestion.
Their text provides a clearer picture of what you appear to be communicating, whereas the existing text is ambiguous enough that this issue has been brought up a couple of times. 
I thank you again for the work you have put into this app, it seems very nice, and I am pleased with the "Night" theme.

Are you doing the English localizations yourself? I am not skilled in writing applications, but I occasionally write technical documents where clarity of meaning is very important, and I would like to try and help with localization if you need it. 
I again must apologize for being too harsh

**Comment by J-Jamet** [comment]
Thank you @nate2014jatc & @Ilithy  for your feedback, and do not apologize, there is no problem. ;) (You are not rude, I can also be on the defensive because I receive very strange emails.)

In French, there is a bug because a user (@Éfrit) on WebLate replaced the previous text, by "Algorithms". I do not know why.
I agree to modify it (in french & english) to remove the ambiguity.

@nate2014jatc If you want to help translate the application and the wiki, it would be very nice. I am French and English is not my native language, so I can make mistakes. :/
