### ISSUE TITLE
materialfiles crashes in combination with keepassdx

### ISSUE THREAD

**Issue by Joppla** [Kunzisoft/KeePassDX#1280]
See also: https://github.com/zhanghai/MaterialFiles/issues/727

Since last weeks MaterialFiles crashes. 

It happens when my browser try to open KeePassDx to get username and password. The database file for KeePassDx is in the cloud and it use MaterialFiles to connect to it.

When I open KeePassDX MaterialFiles crash also.

Only when I first open MaterialFiles and than KeePassDX everything works fine.

I don't know if the problem is in MaterialFiles or in KeePassDX but it is anoying.

Hopefully can somebody find the solution.

PS my Samsung G S9 works with android 10.

Describe the bug**

**To Reproduce**

**Expected behavior**

**KeePass Database**

 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android:**

 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1277 https://github.com/zhanghai/MaterialFiles/issues/716
