### ISSUE TITLE
App doesn't come up despite Sign in with KeePassDX on keyboard

### ISSUE THREAD

**Issue by cbiere** [Kunzisoft/KeePassDX#1281]
**Describe the bug**

The app doesn't come up or offer an entry despite "She gn in with KeePassDX" being shown on the standard keyboard.

**To Reproduce**

1. Go to https://myaccount.nytimes.com/auth/login (or any web login )in Google Chrome
2. Click on Sign in with KeePassDX

However, it does work if I use Magickeyboard and the select an entry. When I switch back to normal keyboard and switch the input field, there's a suggestion by KeePassDX. Just starting KeePassDX and unlocking the database doesn't seem to be sufficient.

**Expected behavior**

KeePassDX should come forward and ask to unlock the database. Then it should suggest the stored credentials 

**KeePass Database**

 - Created with: Windows KeePass 2.42
 - Version: 2
 - Location: Internal storage
 - File provider (`content://` URI): content://com.android.externalstorage.documents/document/primary%3AKeePass%2FKeePass-Database.kdbx
 - Size: 257 kB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.3.2 
 - Build: free
 - Language: English

**Android:**

 - Device: Xiaomi Redmi Note 10 Pro
 - Version: MIUI Global 13.0.3 stable (Android 12)

**Additional context**

 - Browser for Autofill: Chrome 99.0.4844.73

**Comment by J-Jamet** [comment]
I think you haven't enabled the special permissions added in MIUI for Xiaomi devices.
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#set-up

**Comment by cbiere** [comment]
Oops. You're right. I've enabled all permissions except "Display pop-up windows while running in the background". Now it's enabled:
![Screenshot_2022-03-26-16-07-26-793_com miui securitycenter](https://user-images.githubusercontent.com/8558711/160245586-3cfc38ab-037b-4ff9-aec0-a13b93c92c12.jpg)

Thanks for the quick response. Now, it's working perfectly.
