### ISSUE TITLE
'access to the file by the file manager

### ISSUE THREAD

**Issue by yoe** [Kunzisoft/KeePassDX#1283]
I sync a KeePassXC password database using Nextcloud, to my laptop and a number of desktops as well as to my phone.

On the phone, I installed KeePassDX to use the password database. It used to be the case that I could just start KeePassDX and unlock it using the biometric scanner on my phone, but as of a few weeks ago, this is no longer the case; every time I open KeePassDX, it now gives the above error message and requires me to reselect the actual file to open.

I'm not sure whether this has started since a change in KeePassDX, one in the Nextcloud Android app, or one in my Android system, but needless to say it is highly annoying.

If you need any further information, please let me know and I'll happily provide it.

**Comment by J-Jamet** [comment]
You didn't read the wiki, you didn't read the other threads and you didn't fill in the bug template.
Duplicate :
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#explanation
https://github.com/Kunzisoft/KeePassDX/discussions/1089
https://github.com/Kunzisoft/KeePassDX/issues/1233

**Comment by J-Jamet** [comment]
The loss of the file manager link is due to the content provider of the file manager. You have to check with NextCloud why it has invalidated the link provided.
As a reminder, the FileSync application is under study to solve this kind of problem.
