### ISSUE TITLE
Problem opening the database

### ISSUE THREAD

**Issue by Monster-is-secret** [Kunzisoft/KeePassDX#1286]
![التقاط](https://user-images.githubusercontent.com/95308840/161654764-9e01ca11-deab-4b73-8aea-d2f5ac956829.PNG)
This is a database created on the phone. Suddenly Atta is there. I do not know the reason. I tried to open the database from my computer and my old phone, but it won't open

**Comment by J-Jamet** [comment]
Too little information, please complete the bug template correctly. I would say at first sight that the file was copied wrong.
https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
