### ISSUE TITLE
Biometric unlocking is cannot be enabled

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#1296]
1. Clear app data.
2. Start the app.
3. Choose some existing DB 
4. Type it's password.
5. Push biometric unlocking.
6. Now enable biometric unlocking. As soon as you turn it on the app will show it's starting screen. And unlocking actually is still disabled. Biometric unlocking has worked with no problems.

App version is 3.4.1.

**Comment by J-Jamet** [comment]
I can't reproduce the problem, I don't have any log in this sense and especially the biometric API hasn't been modified for a long time so I advise you rather to check if your device hasn't put a bugged update or to delete the key from the Keystore.

**Comment by zveber** [comment]
As I see now I cannot open any DB even just with simple unlocking. For example the attached DB (it's password is *test*). Maybe it's a weird problem of my phone...

[test.zip](https://github.com/Kunzisoft/KeePassDX/files/8494953/test.zip)

**Comment by J-Jamet** [comment]
I just tested your database and I have no problem opening it in the standard way or with biometric recognition.
Maybe it's the same problem as :  https://github.com/Kunzisoft/KeePassDX/issues/1269

**Comment by zveber** [comment]
I I just tried to run *3.3.3* from F-Droid and it works without these problems.

**Comment by J-Jamet** [comment]
Maybe it's from an unrecognized theme setting, I have crash reports of this on some devices.

**Comment by J-Jamet** [comment]
3.3.3 is a rather old version, can you try more recent versions. Can you tell me what device you are using?

**Comment by zveber** [comment]
My phone is Realme 8 pro.

On `3.4.1` I can't open a DB at all.

On `3.4.0` I could do it but there was a problem with selection of an entry in magikeyboard (when you selected an entry the app showed it's content instead of selecting).

On `3.3.3` I could choose an entry with magikeyboard.

Every time I used the app from Google Play.

**Comment by J-Jamet** [comment]
> On 3.4.1 I can't open a DB at all.

I haven't touched the methods of opening the database, so this is very strange.

> On 3.4.0 I could do it but there was a problem with selection of an entry in magikeyboard (when you selected an entry the app showed it's content instead of selecting).

This problem is fixed : https://github.com/Kunzisoft/KeePassDX/projects/66

> On 3.3.3 I could choose an entry with magikeyboard.

Okay, but what does this have to do with your biometric problem?

**Comment by zveber** [comment]
Bow I can open all my DBs. And even can do it using biometric. Sorry for disturbance.

**Comment by J-Jamet** [comment]
Not a problem
