### ISSUE TITLE
MagicKeyboard became harder to fill with the last 2 updates

### ISSUE THREAD

**Issue by giwrgosmant** [Kunzisoft/KeePassDX#1297]
**Describe the bug**

With the last 2 updates (3.4.0 and 3.4.1), it became harder to use MagicKeyboard to fill the sites.

Before the last 2 updates, I simply open the Browser>going to the site I want to login>Long Press space bar in keyboard to switch to MagicKeyboard>open the database> select the entry and it automatically minimized KeePassDX and redirect me to the browser with the MagicKeyboard ready to fill.
With the last 2 updates it needs to press extra buttons to select the entry and also to fill the magickeyboard.

**To Reproduce**

1. Go to Browser on site you want to login
2. Click on space bar in Keyboard to switch to MagicKeyboard
3. Open the database and select the entry
4. It doesn't automatically minimized and redirect you to Browser with MagicKeyboard ready to fill, it need to press extra buttons.

**Expected behavior**
It should automatically minimzed and be ready to fill.

**KeePassDX:**

 - Version: 3.4.1
 - Build: Google Play
 - Language: Greek

**Android:**

 - Device: POCO F1
 - Version: Android 12.1 / crDroid ROM

**Additional context**
Let me know, if u didn't understand correctly what I mean. I will try to shoot a video.

**Comment by J-Jamet** [comment]
I understand what you mean but I can't reproduce the problem. The function to minimize the application to access the form works fine on my devices.

If you can make a video, why not. The 3.4.2 version is being deployed, it does not touch the function you are talking about but there is a correction of the instances in the background.
I think there are different behaviors depending on the device.

**Comment by giwrgosmant** [comment]
> I understand what you mean but I can't reproduce the problem. The function to minimize the application to access the form works fine on my devices.
> 
> If you can make a video, why not. The 3.4.2 version is being deployed, it does not touch the function you are talking about but there is a correction of the instances in the background. I think there are different behaviors depending on the device.

I created a new test database and shoot a video. Check [here](https://mega.nz/file/L41FkRRC#Y_bzO4Tcx-0taFh6qqkxLwE0uKzNRoVNqEJlWCNxM_k). It needs too many extra steps, 1. when I open the database it doesn't redirect me to the entries and I have to press "back", 2. selecting the entry do nothing I have to go to home via gesture and select to open the browser again, 3. when i go again to browser i have to choose again the MagicKeyboard.

The thing is with this started to happens from the version 3.4.0 in my device before that it was better.

Sorry for the bad quality is from old phone since I couldn't screen record the KeePassDX due to security (black screen - btw it would be nice for a **toogle** to not make screen black for screenshots or screen record for situation like that). (I will delete the video after you check it out)

**Comment by J-Jamet** [comment]
I think you have not activated the setting: `Settings - Form filling - Magikeyboard settings - Select shared info`

If it is not activated, it allows you to do a search with either the package name or the URL but does not allow selection.

If you do a long click on the key button, you ask to search on an empty element so it is useless in this case (I will think about how to improve this case).  You need to do a single click on the key button to fill the search field.

**Comment by giwrgosmant** [comment]
> I think you have not activated the setting: `Settings - Form filling - Magikeyboard settings - Select shared info`
> 
> If it is not activated, it allows you to do a search with either the package name or the URL but does not allow selection.
> 
> If you do a long click on the key button, you ask to search on an empty element so it is useless in this case (I will think about how to improve this case). You need to do a single click on the key button to fill the search field.

Oh you are right, this was disabled. When I was looking at these settings I though it was something else about URL, so I didn't enabled it. I guess after the update to 3.4.0 some things changed there and I had to enable this option.
Thanks a lot, you saved me from a headache 😛

**Comment by J-Jamet** [comment]
I'm updating the wiki to put this first in the explanations.

**Comment by giwrgosmant** [comment]
@J-Jamet Sorry for my reply after closed this didn't wanted to open another issue just for this, but what do you about a toogle to allow screen recording in KeePassDX which I mentioned above?
It will save time and help with the explanation of a reported bug in some situations.
