### ISSUE TITLE
The 3.4.0 update broke the magickeyboard

### ISSUE THREAD

**Issue by AskOld-ich** [Kunzisoft/KeePassDX#1299]
**Describe the bug**

After 3.4.0. (inclusive(-ding)) I can't just select an account for the magickeyboard :(

Now KeePassDX asks some technical tags, please no, God, please :(

**Comment by lucamp** [comment]
# Steps

Choose magic keyboard
Select key icon (to choose login)

# current behaviour
keepassdx starts in saving/editing mode instead of selecting mode

# workaround (without OTP features)
Enable android autocomplete feature for keepassdx

**Comment by J-Jamet** [comment]
This is not a technical tag but the current package name for the open application. If you just want a search without this element. Just do a long click on the key button. Read the wiki carefully.

https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

**Comment by J-Jamet** [comment]
3.4.2 fixes all the Magikeyboard bugs.

**Comment by DarkNekoyama** [comment]
> This is not a technical tag but the current package name for the open application. If you just want a search without this element. Just do a long click on the key button. Read the wiki carefully.
> 
> https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

Have the same problem as the post creator, the long press on the key unfortunately brings nothing, because Keepass opens exactly as if I would open it the normal way, Instead of going into the search mode.
This makes it impossible to use Magikeyboard.

**Comment by J-Jamet** [comment]
Point 2 in the wiki configuration

Check that the setting "Settings → Form filling → Magikeyboard settings → Select shared info" is enabled, otherwise the information will be searched but not returned to the Magikeyboard.

**Comment by J-Jamet** [comment]
Version 3.4.1 & 3.4.2 solves the Magikeyboard issues.
