### ISSUE TITLE
Detach fork from main repo

### ISSUE THREAD

**Issue by rugk** [Kunzisoft/KeePassDX#13]
Maybe detach this repo from the "original" version?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as you likely drive the project into another direction…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. allows searching in this repo on GitHub and
5. it just looks much nicer

**Comment by J-Jamet** [comment]
OK with that. :) However, I had something practical for updates : "This branch is *** commits ahead of bpellin:master." but it should be ok, with the upstream branch.

**Comment by rugk** [comment]
I think you can still get to the diff/PR view of GitHub and then it also shows you how many commits you are ahead…
