### ISSUE TITLE
Re-starts of app on opening file or enabling biometrics 

### ISSUE THREAD

**Issue by CapSel** [Kunzisoft/KeePassDX#1303]
With version 3.4.1 I can't open database. After entering password app restarts to the initial view.

Enabling biometrics causes same effect.

With 3.4.0 both work fine.

**Comment by J-Jamet** [comment]
I think it's related to an activity TAG on version 3.4.1, have you tried version 3.4.2 to see if the problem was resolved?

**Comment by CapSel** [comment]
Yes, it works with 3.4.2. Can you push this version to F-Droid?

**Comment by J-Jamet** [comment]
No I can't. F-Droid uses a server that retrieves the code directly from the Git repo. The repo already has the TAG, you have to wait for the server to get the sources and builds automatically.

**Comment by CapSel** [comment]
OK, thank you.
