### ISSUE TITLE
TOTP/2FA Idea with Notifications

### ISSUE THREAD

**Issue by cyl3x** [Kunzisoft/KeePassDX#1307]
**Is your feature request related to a problem? Please describe.**
I use 2FA a lot and always have to paste the tokens manually, because KeePassDX cannot fill/suggest it automaticlly

**Describe the solution you'd like**
If you copy manually usernames/passwords/totp from an entry, you get a notification/popup where you can copy all other fields. It would be nice to have this notification also when you autofill and there is an totp field for the entry.

**Describe alternatives you've considered**
If its not possible to create notification when you autofill with ex. gboard, my next idea would to automaticlly open the last entry you autofilled with when you open the app

**Additional context**
-

**Comment by J-Jamet** [comment]
Duplicate #553 #1208

https://github.com/Kunzisoft/KeePassDX/issues/553#issuecomment-912936390

Linked to https://github.com/Kunzisoft/KeePassDX/issues/1287
