### ISSUE TITLE
Delete an entry from the search

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1308]
**Is your feature request related to a problem? Please describe.**

Allow to delete an entry from the search by doing a long click

**Comment by fuelflo** [comment]
I'd appreciate this function.
Alternatively we one could also enable to delete an entry while looking at a second single entry or while editing an entry. Currently you can't delete the whole entry while editing it. You'd have to exit to the main view, SCROLL to that entry and then mark by long press and delete.
