### ISSUE TITLE
 conflicted copies on a Dropbox 

### ISSUE THREAD

**Issue by wombalton** [Kunzisoft/KeePassDX#1312]
I use Dropbox to sync my database across devices. 
When I edit my database with keepassdx on my phone i get a conflicted copy with the current time and date. The next time I open the keepassdx app, the changes are not there. then I have to manually merge the new file with the old one and save the database withthe save button two or more times  until no error message is shown.

**Comment by J-Jamet** [comment]
You clearly state that Dropbox does not handle file conflicts properly.
I have no connection with the Dropbox company, so I have no influence on the bugs and development of their application.
You should contact them directly or help with FileSync.

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
https://github.com/Kunzisoft/FileSync/issues/5
