### ISSUE TITLE
en_GB translation

### ISSUE THREAD

**Issue by JohnVeness** [Kunzisoft/KeePassDX#1314]
Hi. Please can you add a translation for en_GB, i.e. British English? That way I can change color to colour etc!

To be clear, I am happy to use Weblate to translate the strings myself, but I think only you can enable a new language.

**Comment by J-Jamet** [comment]
This is the link for this : https://hosted.weblate.org/projects/keepass-dx/strings/en_GB/

Thank you! :)

**Comment by JohnVeness** [comment]
Thanks. I have translated the strings that I think need translating. Do I need to copy (unchanged) all the other entries too?

**Comment by J-Jamet** [comment]
Nah it's ok, we can write them down as identical but it's not a problem, by default it will take on the base file.
