### ISSUE TITLE
Backup Database on successful load 

### ISSUE THREAD

**Issue by Onering20** [Kunzisoft/KeePassDX#1316]
**Is your feature request related to a problem? Please describe.**
I had my data base corrupt after messing with attachments (assuming this was the issue based on other posts).  Last proper backup is over a month old. 

**Describe the solution you'd like**
On a successful load of database it writes/overwrites a file of the same name &.bak or similar as a copy in the same folder or in a app folder. Changes made to the database during the following session are not made to the backup

On a failed load (database corrupt) offer to restore from the backup (backup file is not removed by this operation 

At worst lose one session of progress not a month

**Describe alternatives you've considered**
A warning about attachments and possibly a copy of the database without the unstable elements

**Comment by J-Jamet** [comment]
The backup system must be done externally, as explained in the wiki.
https://github.com/Kunzisoft/KeePassDX/wiki/Backup
It will be possible to configure the backups in FileSync and KeePassDX should remain a simple editor.
https://github.com/Kunzisoft/FileSync

On the other hand, if you have a problem with the attachments, it should be identified, I haven't noticed any problem there.
Can you upload a database and a procedure to reproduce your corruption problem?

**Comment by J-Jamet** [comment]
Same as #1346 and no response
