### ISSUE TITLE
Check security

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1318]
Most of the results generated by automatic diagnosis are false positives but still allows to check some points.

This indicates hash algorithms that are either used to check the internal integrity of the files or indicate library methods that are not used so not really relevant.

The algorithms used in KeePass database are standardized by the format and are secure but it is recommended to use Argon2id as KDF if the other KeePass apps you use are compatible.

I will however check the secure random and add filterTouchesWhenObscured="true" to prevent TapJacking.

https://appsweep.guardsquare.com/builds/b8134287-5fda-4ac7-bf06-49a9247f619e

**Comment by J-Jamet** [comment]
AppSweep auto monitoring : 
- **SHA1PRNG** : PRNGFixes has been implemented to overcome this problem but the parser detects it anyway. -> https://android-developers.googleblog.com/2013/08/some-securerandom-thoughts.html
- **void Signature.initSign(PrivateKey,SecureRandom)** :  Just detected in `BouncyCastle` which is a generic encryption library but the impacted methods are not used so is not a problem
- **hashing algorithm** : Same as before but for the `org.apache.commons.codec` library, the methods are not used but need the library for other methods
- **AES/ECB/NoPadding** : Manual ECB method is only used if the native transformation method is not recognized by the system and a first exception is caught. In any case, there are transformation rounds for your AES encrypted database (uses the standard KeePass format). You can use Argon2id (new recommended) in your database if you are still not reassured.
- **Tapjacking** : I'm working on it. Can happen if you allow the permissions of other applications to be placed above the others. So if you knowingly allowed an app (even if you didn't know that was a malware) to do so.
- **Classes contain Kotlin Metadata** : Quote -> "Kotlin Metadata may give important information to a reverse engineer". The joke is that the code is open source, you can do as much reverse engineering as you want, it is even recommended.
- **Legacy cryptographic classes used**: Library and normal methods, not a problem.
- **The app logs information**: If you see logs with sensitive information it is very surprising. After that I'm not immune to a mistake but tell me exactly what one.
- **Cipher AES/CBC/PKCS7Padding is used that requires a non-predictable IV** : SecureRandom is used

So please don't just send me a line to an automatic detector in an anonymous email because you are afraid.
I'm always ready to fix security problems and bugs. I try to improve the architecture with each update, the code is open but the criticism must be constructive.

Other applications don't bother to put their code open source and to do such frequent monitoring (even in the KeePass ecosystem, a non-open source application can have leaks, even if there is no network connection).
So I'm doing my best here, if you see any misinterpretation or error in the code, feel free to open the debate.

**Comment by Bugaddr** [comment]
Thanks j-jamet for those quick fix, what exactly did this anonymous message said. Like is it a promotional message (maybe some company do that) or its specially written by someone (maybe security professional) to explain those problem. Afaik, tapjacking is considred somewhat critical so maybe more info may have been provided, if so please consider sharing that.

**Comment by J-Jamet** [comment]
There was no real explanation, it was very succinct, implying, "deal with it." :D
I still would have liked more detail because many developers would have just spammed it. But the important thing is to have identified and improved a security element.
