### ISSUE TITLE
Unable to create a database on SD card

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#132]
The app was granted permission to write to card but it just comes up with an error saying it doesn't have 
permission. AT&T Samsung Galaxy S9+ Android 8.0.0

**Comment by gtlt** [comment]
Same here with Android 8.1 (lineageos unofficial build).

**Comment by gtlt** [comment]
Not working on my system. But a workaround is to create it on internal storage and move db file to sdcard after that. It then possible to open it.

**Comment by 2011** [comment]
I too would like to see the ability to create databases on external SD cards (and even external USB drives).

Unfortunately, writing to external storage is actually rather complicated (and the methods have changed a lot over various versions of android).

Some of this is explained here (if you are not already familiar with it), though I have seen other pages with even more detailed information.

https://developer.android.com/training/data-storage/files
