### ISSUE TITLE
Inline autofill not opening keepassdx

### ISSUE THREAD

**Issue by BobIsMyManager** [Kunzisoft/KeePassDX#1326]
**Describe the bug**

When I press the button on the inline autofill to select an entry, the keyboard just closes.

**To Reproduce**

1. Go to a login page
2. Click on the inline autofill button
3. Nothing happens

**Expected behavior**

I should be able to chose an entry

**KeePass Database**

 - Created with: Linux KeePassXC 2.6.6
 - Version: 4.1
 - Location: sd card
 - File provider `content://com.android.externalstorage.documents/document/FF21-171E:backups/keepass/Passwords.kdbx`
 - Size: 276kb
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.4.3
 - Build: fdroid
 - Language: English

**Android:**

 - Device: Redmi Note 9 Pro
 - Version: 11

**Additional context**

 - Browser for Autofill: fennic (firefox fdroid) 100.1.1
 - It also seems that gboard is the only keyboard that has the overlay prompt to use the password set to that site
 - I have tested this with other autofill providers (bitwarden), and it works fine

https://user-images.githubusercontent.com/70704875/167956986-84c511f0-2c7f-4c5d-bf2c-5bce92dcdd72.mp4

**Comment by J-Jamet** [comment]
Xiaomi add unnecessary permissions.
You haven't read the wiki to configure the feature : https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#set-up

Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1281
Linked to https://github.com/Kunzisoft/KeePassDX/issues/1166

> It also seems that gboard is the only keyboard that has the overlay prompt to use the password set to that site

The keyboard used must contain the code to manage the inline autofill.

**Comment by BobIsMyManager** [comment]
Thanks, I did not see those!
