### ISSUE TITLE
feature request: store db in internal storage

### ISSUE THREAD

**Issue by punksta** [Kunzisoft/KeePassDX#133]
I think it'd be good to have this option while creating of new db file. We still can share db files using content-provider

**Comment by t-m-w** [comment]
As a workaround, you can store the key file in another app you trust that supports the Storage Access Framework, and then browse to it in KeePassDX. This is better than having it floating around in the Internal Storage area where any app can access it; at least you, the user, have to be proactive about browsing to it in order for another app to have permission to access it. I used Termux for this, but there may be better ideas.

**Comment by nclmde** [comment]
> As a workaround, you can store the key file in another app you trust that supports the Storage Access Framework, and then browse to it in KeePassDX. This is better than having it floating around in the Internal Storage area where any app can access it; at least you, the user, have to be proactive about browsing to it in order for another app to have permission to access it. I used Termux for this, but there may be better ideas.

File security of the key file is requested in #186 . I think this suggestion should have been made there

**Comment by t-m-w** [comment]
> > As a workaround, you can store the key file in another app you trust that supports the Storage Access Framework, and then browse to it in KeePassDX. This is better than having it floating around in the Internal Storage area where any app can access it; at least you, the user, have to be proactive about browsing to it in order for another app to have permission to access it. I used Termux for this, but there may be better ideas.
> 
> File security of the key file is requested in #186 . I think this suggestion should have been made there

I agree. I believe that's where I meant to make it, but I got lost somewhere... I will make it there, too.

**Comment by J-Jamet** [comment]
The functionality is part of a file manager application. You can continue the discussion in the FileSync project : https://github.com/Kunzisoft/FileSync/issues/7
