### ISSUE TITLE
Autofill registration with Chrome

### ISSUE THREAD

**Issue by OR120** [Kunzisoft/KeePassDX#1332]
After opening the webpage in the browser and entering the password, the login is successful, and a pop-up window will not prompt you to ask whether to save the password.

The permission is already allowed, the pop-up window authorization has been allowed, and the mobile phone is MI device-MIUI13 development version

webpage is all，example https://pianyuan.org/

in the chrome browser version 101.0.4951.61

**Comment by J-Jamet** [comment]
Please fill in the bug template correctly : https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

> After opening the webpage

Which one?

>  in the browser

Which one?

> and a pop-up window will not prompt you to ask whether to save the password.

Only works with browsers that have built-in autofill.

https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#compatibility-mode

**Comment by OR120** [comment]
> Please fill in the bug template correctly : https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
> 
> > After opening the webpage
> 
> Which one?
> 
> > in the browser
> 
> Which one?
> 
> > and a pop-up window will not prompt you to ask whether to save the password.
> 
> Only works with browsers that have built-in autofill.
> 
> https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#compatibility-mode

**Comment by J-Jamet** [comment]
> chrome browser version 101.0.4951.61

Chrome browser does not have native autofill.

**Comment by OR120** [comment]
> > chrome 浏览器版本 101.0.4951.61
> 
> Chrome 浏览器没有原生自动填充功能。

This is not the case. My chrome browser will have a filled window in the input box, that is, it works normally. However, if I manually enter the account password on an unfamiliar website, it will not pop up asking whether to save the password. Then I tested some more Video software, manually enter the login, after the login is successful, a pop-up window will pop up asking whether to save the password, which is very strange

**Comment by OR120** [comment]
> > chrome browser version 101.0.4951.61
> 
> Chrome browser does not have native autofill.

this is chrome browser![Screenshot_2022-05-14-17-15-55-445_com android ch](https://user-images.githubusercontent.com/45073607/168419742-2f2b611c-658e-462b-ad4e-23a8defca731.jpg)

![Screenshot_2022-05-14-17-15-45-684_com android ch](https://user-images.githubusercontent.com/45073607/168419781-10bcac21-694c-4603-a58c-b71f8f9f215d.jpg)

This is another app, not a browser. After entering the password, it will pop up whether to remember the password, but chrome will not pop up

![Screenshot_2022-05-14-17-23-13-763_com czx axbapp](https://user-images.githubusercontent.com/45073607/168419815-907cce57-f204-4020-ae22-7886923dfe74.jpg)

**Comment by J-Jamet** [comment]
**Registration mode cannot be used with Chrome because it does not have native Autofill.**

The second screenshot shows the compatibility mode, that is to say that a compatibility service (that is not part of Chrome) passes on the page to display the popup. But the compatibility service that is managed by the system does not manage the registration of an entry.

In the third screenshot, the application you are using manages metadata in these forms that are recognized by the native autofill service. So the registration can be used.

Chrome has deliberately removed the native autofill from its browser in favor of centralized password storage in a Google account : https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-627224788
I'll let you make your own conclusions about that.

**Comment by OR120** [comment]
> **注册模式无法与 Chrome 一起使用，因为它没有原生自动填充功能。**
> 
> 第二个屏幕截图显示了兼容性模式，也就是说，兼容性服务（不是Chrome的一部分）在页面上传递以显示弹出窗口。但是，由系统管理的兼容性服务不管理条目的注册。
> 
> 在第三个屏幕截图中，您正在使用的应用程序管理这些表单中的元数据，这些表单由本机自动填充服务识别。因此，可以使用注册。
> 
> Chrome故意从浏览器中删除了本机自动填充功能，转而将密码集中存储在Google帐户中：[#551（评论）](https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-627224788)我会让你对此做出自己的结论。

In that case, please, do you have any recommended browsers? I want to give it a try, after all the ones I use are not working properly,
![QQ图片1](https://user-images.githubusercontent.com/45073607/168420651-c5f9eca2-9d20-4426-8fa7-5039e4d8c3ad.jpg)

![QQ图片2](https://user-images.githubusercontent.com/45073607/168420668-ee939910-91ea-4b25-8c73-e4ca31917761.jpg)

**Comment by J-Jamet** [comment]
I recommend that you simply do your own comparisons to find the one that best suits your needs. ;)

**Comment by OR120** [comment]
> 我建议您简单地进行自己的比较，以找到最适合您需求的比较。;)

thanks
