### ISSUE TITLE
Do not overwrite KeeShare settings created by other KeePass programs

### ISSUE THREAD

**Issue by nirvinm** [Kunzisoft/KeePassDX#1335]
**Describe the bug**
KeePassXC and KeePass supports KeeShare to support synchronizing entries between two different databases. This is achieved through the KeeShare settings (which include the KeeShare file path and a password) associated with a group. Currently, whenever a KeePass database is edited by KeePassDX, the KeeShare settings are overwritten and gets lost when reopened in other KeePass programs.

**To Reproduce**
1. Create a KeePassXC database in desktop
2. Create a group under Root and enable KeeShare by configuring a file path and a password.
3. Open the KeePass database in KeePassDX
4. Create a new entry anywhere using KeePassDX
5. Reopen the database in KeePassXC.

**Expected behavior**
KeeShare settings should not have been overwritten.

**KeePass Database**
 - Created with: [e.g Linux / KeePassXC]
 - Version: [e.g. 2.7.1]

**KeePassDX:**
 - Version: [e.g. 3.4.4]
 - Build: [e.g. Free]
 - Language: [e.g. English]

**Android:**
 - Version: [e.g. All]

**Comment by J-Jamet** [comment]
Linked to #915 #549
