### ISSUE TITLE
[2.4.4] No touch input on some devices

### ISSUE THREAD

**Issue by storm64** [Kunzisoft/KeePassDX#1336]
**Describe the bug**

After opening the app no touch input is recognised, which makes it unusable.  
Even if unlocked through the fingerprint prompt or at selection through Magikeyboard, no touch is recognised.

**To Reproduce**

1. Open the app
2. Click on anything
3. Nothing happens

**Expected behavior**

Touch should be recognised...

**KeePass Database**

 - Version: V2-KDBX3. 1
 - Location: local
 - File provider: `content://com.android.externalstorage.documents/... `
 - Size: different
 - Contains attachments: Yes

**KeePassDX:**

 - Version: 2.4.4
 - Build: F-Droid
 - Language: german

**Android:**

Bug occurres on:
 - Device: OnePlus 7T Pro  
   Version: 10 (RR 8.7.3)
   Database: A
 - Device: Xiaomi Mi A2 Lite (daisy)  
   Version: 9 (RR 7.0.1)
   Database: B

Bug does not occurre on:
 - Device: SM-P605 (lt03lte)  
   Version: 7.1.2 (RR 5.8.5)
   Database: A (same as on OnePlus 7T Pro)

**Additional context**

Even after a force quit of the app, app cach removal or a complete phone restart, no touch is recognised.

**Comment by J-Jamet** [comment]
There's a simple reason for that. The security of the application has been improved, it is no longer possible to press the buttons if another application applies an overlay on the keys of the application. This prevents TapJacking for password recovery by other applications.
Make sure you don't have any application that overlay KeePassDX to recover key presses.
If you haven't installed any other apps, then there's just a huge security issue on the Xiaomi and OnePlus in the stock ROM.

Linked to https://github.com/Kunzisoft/KeePassDX/issues/1318

**Comment by storm64** [comment]
Thank you for the fast feedback.

In deed the problem occurs only if the "Smart pixels" setting is enabled.
This setting disables a specified percentage of pixels of the screen to save battery.
