### ISSUE TITLE
KeePassDX kdbx File not synced

### ISSUE THREAD

**Issue by Tommy-01** [Kunzisoft/KeePassDX#1337]
## Overview
After changing something in the Keepass kdbx file using KeePassDX (like adding a new entry), saving and closing the file, it wont get synchronized by the Android Nexcloud client.
Maybe because KeepassDX tries to hide any changes on the file for security reasons?

## Steps to Reproduce
1. Open the KeePass DB
2. Change something in the DB
3. Save and close the DB

## Expected Behavior
The Android Nextcloud Client synchronizes the .kdbx file

## Actual Behavior
The Android Nextcloud Client did not synchronizes the .kdbx file.
Even if i start the synchronization manually. It says there is no change on this file.

Operating System: Linux
Desktop Env: Cinnamon
**KeePass Database**

 - Created with: Linux
 - Location: Local NAS
 - Size: 12kB

**KeePassDX:**

 - Version: 3,4,4
 - Build: libre
 - Language: German

**Android:**

 - Device: Pixel 3
 - Version: 12

**Additional context**

**Comment by J-Jamet** [comment]
> Maybe because KeepassDX tries to hide any changes on the file for security reasons?

No, it's just that the Nextcloud cache doesn't allow new external modifications. Make a clear of the NextCloud cache.
