### ISSUE TITLE
can't select settings and some items fromsaved list

### ISSUE THREAD

**Issue by jithinjames916** [Kunzisoft/KeePassDX#1341]
Setting button on database selection screen,
Swip button not working,
Settings in menu pannel also not working,
Can't select new items(resently save) from the list...
Device:- nokia  3.2
Android version 11

Keepassxd is the best passwd mgr out there... please do the needful

**Comment by J-Jamet** [comment]
I don't understand the procedure for reproducing the bug.

Can you fill the template bug (https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and describe the problem more precisely.

**Comment by J-Jamet** [comment]
Maybe related to https://github.com/Kunzisoft/KeePassDX/issues/1336

In any case, I can't guess your problem with your rebus description.
