### ISSUE TITLE
Setting for filterTouchesWhenObscured

### ISSUE THREAD

**Issue by fohfuu** [Kunzisoft/KeePassDX#1342]
**Is your feature request related to a problem? Please describe.**
I use accessibility apps such as autoclickers to help me use my devices. This is to prevent my hands and wrists from repetitive strain injuries and my fingers. In the new update, the database is unusable with these apps active on the screen.

**Describe the solution you'd like**
Add an advanced settings option that allows the user access the database while accessibility apps are being used.

**Describe alternatives you've considered**
Add a toast or other on-screen notice that states the app is not usable when other apps are displayed on the screen.

**Additional context**
Some kind of notification or warning is necessary, as otherwise, it just seems like the app has frozen/crashed for no reason.

I don't blame a dev team for trying to make their app less vulnerable. This issue is ultimately with the Android OS and Google's poor attempts to fix it.

**Comment by J-Jamet** [comment]
I understand your frustration, I will add an option in the next version to disable filterTouchesWhenObscured

**Comment by J-Jamet** [comment]
Unfortunately, there isn't really a way to globally detect if a view is hidden so I'll update the wiki and put a note when I make the presentation screens.

**Comment by J-Jamet** [comment]
I just tested _Auto Clicker - Automatic tap_ and I have no problem using the accessibility service with KeePassDX. Can you give a concrete use case for your problem?

**Comment by J-Jamet** [comment]
In the title you indicate **"Display over apps" compatibility** but in the description you only mention the accessibility service. 
These are two very different things.

According to my tests, the accessibility service works well and it is normal that the overlays overlaid on the keys (especially the transparent ones) do not capture the button events.
Make sure you have not set any overlays filters on the screen.

**Comment by fohfuu** [comment]
I'm not sure what the problem must be, then. In 3.4.4, for me, any app that has "display over other apps" active causes the app to stop responding, including the floating controls for my autoclicker. Maybe it's an Android 9 thing, or a phone-specific bug. It's a Motorola so that happens.

Either way, thank you for promptly addressing the issue. I wasn't really expecting that this *could* be fixed.
