### ISSUE TITLE
Inline Autofill Only

### ISSUE THREAD

**Issue by E0697** [Kunzisoft/KeePassDX#1350]
**Is your feature request related to a problem? Please describe.**
No

**Feature Description**
When inline autofill is enabled, a popup window shows up after unlocking the database, but uses inline suggestions when open.
Can we get an "inline only" option, and it would show the item selection window (if no matching items were found) after unlocking the database.

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1166

Wiki explanation : https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#inline-suggestions
