### ISSUE TITLE
Avoid switching away from Magikeyboard without user interaction

### ISSUE THREAD

**Issue by anon8675309** [Kunzisoft/KeePassDX#1351]
This ticket is to only switch from the Magikeyboard to the previous one when a user clicks in a text box such as the search box. The goal is to avoid having to switch to the magikeyboard twice to enter a single password.

The use case is selecting a password entry from Magikeyboard. 

Current workflow (without search):  
1. In another app, switch to Magikeyboard
2. Tap the lock icon in Magikeyboard
3. KeePassDX opens
4. Search text input field is selected (at least, this is true if there are multiple entries for that app) and keyboard switches to the previous keyboard
5. Entry is selected and user is returned to the previous app
6. Keyboard is still set to the previous keyboard (i.e. not Magikeyboard)

**Describe the solution you'd like**
Desired flows are as follows:

Without search:  
1. In another app, switch to Magikeyboard
2. Tap the lock icon in Magikeyboard
3. KeePassDX opens
4. Entry is selected and user is returned to the previous app
5. Keyboard is still set to Magikeyboard

With search:  
1. In another app, switch to Magikeyboard
2. Tap the lock icon in Magikeyboard
3. KeePassDX opens
4. Click in the search text input field
5. Keyboard switches to the previous keyboard so the user can type in search terms
6. Entry is selected and user is returned to the previous app
7. Keyboard is still set to the previous keyboard (i.e. not Magikeyboard) Note: the desired behavior for this last step may be changed by #311, for users who grant the required permission

**Describe alternatives you've considered**
Long tap on the lick icon of Magikeyboard to avoid having the search text input box selected, and thus avoiding the undesired switch away from the Magikeyboard. This workaround is effective, but being able to tap (instead if long tap) and having a filtered view would be preferable. I consider this more of a feature than a bug, as it is just an improvement, not really an error.

**Additional context**
This ticket came about from a [conversation](https://github.com/Kunzisoft/KeePassDX/issues/311#issuecomment-1148953196) on #311.

**Comment by TippyLion28** [comment]
I would also be interested in a solution to this, or at least a toggle to disable search as the default selection screen.

**Comment by moya2162** [comment]
Commenting to state i too am interested in a solution to this. The flow as described by anon is what I would expect as well.

**Comment by J-Jamet** [comment]
I've added a condition that allows the searchView not to be focused if it's an auto search. This means that the keyboard can only be changed if the field is focused.

**Comment by anon8675309** [comment]
Thanks, I'm looking forward to it. Donation is on the way. :-)

**Comment by J-Jamet** [comment]
Appreciated
