### ISSUE TITLE
Password strength indicator when viewing or editing an entry

### ISSUE THREAD

**Issue by abiud254** [Kunzisoft/KeePassDX#1355]
**Is your feature request related to a problem? Please describe.**
NO

I saw that this feature was talked about in the past but was only added to the password generator. 

**Describe the solution you'd like**
The strength indicator or entropy to also be included in the entry view or when editing an entry and not just the generator.

**Comment by J-Jamet** [comment]
I've just added the entropy indicator to the password edit view.
I'll see about just adding a colored dot in the password view. :)
