### ISSUE TITLE
Less no. of special characters in pass gen

### ISSUE THREAD

**Issue by suga-daddy** [Kunzisoft/KeePassDX#1360]
**Is your feature request related to a problem? Please describe.**
A lot of websites have a small set of allowed special characters. Something like (#@%$*&) so when i generate a password using the password generator it includes a lot of disallowed characters. In the end I have to generate a password without special char and add them manually

**Describe the solution you'd like**
Maybe a another option with less number of special characters. 

**Describe alternatives you've considered**
or maybe a user preset of available characters in the password gen.

**Comment by J-Jamet** [comment]
You can already define the allowed characters for password generation in the fields "Consider characters" and "Ignore Characters".

**Comment by suga-daddy** [comment]
Oh sorry. Didnt see that before. my bad.
