### ISSUE TITLE
Don't erase the master password after wrong attempt at the unlock screen

### ISSUE THREAD

**Issue by pinckpockett** [Kunzisoft/KeePassDX#1365]
When typing in master password on the unlock screen. Do not erase the entire input when typed incorrectly. But instead just say "cannot read credentials". And make you type in the correct password like on KeepassXC.
This is time consuming. Having to type in the entire password again if one letter was incorrect or not uppercase. Or another reason. 
There is an option to show password which I use.
But sometimes I will make a mistake. I am only human.

If you type the wrong master password, can the incorrect password just stay there? Then you can change a mistake or add a part you didn't include. Instead of having to type it all again.
KeepassXC does this and it is very helpful.
Or is this an android thing that cannot be changed?

**Comment by artistic-nucleus** [comment]
This feature is already available, go to Settings > App settings and turn off "Delete password"
