### ISSUE TITLE
Can't paste outside text

### ISSUE THREAD

**Issue by Pranab009** [Kunzisoft/KeePassDX#1368]
**Is your feature request related to a problem? Please describe.**
Why I can't paste outsider (3rd party) text.

**Describe the solution you'd like**
Please enabled this.
**Describe alternatives you've considered**
If you copy anything from note or any app to keepassdx app then this app can't allow to paste.
Please fix it
**Additional context**

**Comment by J-Jamet** [comment]
Your bug report is not correctly filled in.
The problem does not come from the application but has been identified on some Xiaomi devices because of the manufacturer's overlay.
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1152
