### ISSUE TITLE
Problem to open a KeePassDX file remotely

### ISSUE THREAD

**Issue by Mwaye** [Kunzisoft/KeePassDX#1369]
Hi,

_(Sorry for my bad english)_

**Describe the bug**

When I want to open my keepassdx file with my Xiaomi Mi11 _(Android 12 and MIUI 13)_, keepassdx bug and says "file format is not recognized" _("impossible de reconnaitre le format de la base de données" is the exact message - french language)_. The problem appear only with wifi connexion _(so LAN access to my file)_.
Problem exist since few weeks, before it was working great
No problem on my xiaomi when using data _(so web access to my file)_.
No problem on my Sansung Android 11 with data or wifi connexion.

**To Reproduce**

0. Wifi on and connected to my home SSID
2. Launch KeePassDX and select the file.
3. Enter the password (or fingerprint)
4. The DataBase try to open and error message appear.
5. See error "file format is not recognized"

**Expected behavior**

When open on another device or on my Xaomi device but with data connexion, the database open correctly.

**KeePass Database**

 - Created with: Debian KeePassXC (4 years ago)
 - Location: My own NextCloud
 - Size: 250 Ko
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 3.4.5
 - Build: [Free
 - Language: French

**Android:**
 - Device: Xiaomi Mi 11
 - Version: Android 12 - MIUI 13

I don't find any answer on the web. Sorry if this problem has already be asked.
Thanks in advance for any help.

Bests regards,
Benjam

**Comment by J-Jamet** [comment]
I'm pretty sure you are trying to open a file from a content provider that has network requirements. For example, if you try to open a file provided by Google Drive with a URI of type "content://com.google.android.apps.docs.storage/
", there may be problems like this. Choose another file manager for example by opening the file from a local location.

**Comment by Mwaye** [comment]
Good evening,

_I probably explained my problem badly (because of my bad English, so I use Google translate, even if I don't like it)._

**My network config hosting the file :**
- My personal nextcloud is accessible in LAN and WAN via WebDAV.
- Local redirection of the nextcloud address or my OPNsense.

**The problematic phone config :**
- Xiaomi mi 11 am Android 12 with MIUI 13 (+Root).

**description of the problem :**
- I have no problem with remote access whether from my 2 telephones or all my computers or even from an additional computer that I would configure.
- The problem is, conversely, only from a single phone and only from my local network (using WiFi, not using data and therefore not from the Internet).

**So to re-explain with some details :**
- if I try to open my keepass file from any computer (personal, professional, public...) or telephone (personal or professional) from the Internet (WAN), I have no problem; the database linked to the file opens without any problem.
- if I try to open it from my local area network (LAN), I have no problem on my personal computer, on my professional computer and on my professional phone.
- on the other hand from my personal phone (Xiaomi mi 11, Android 12, MIUI 13) impossible to access the file from my LAN but it works without problem from the WAN (operator data access).
- the applications installed are the same on the 2 phones (mix explorer, nextcloud client, nova launcher, keepassdx...)

So I don't understand the problem at all.
It may be a right issue on the phone and the app on the Xiaomi, but I can't find it.

Thanks for your help.
Good for you,

Benjamin

**Comment by J-Jamet** [comment]
All the behaviors you describe are outside the scope of KeePassDX which does not provide the file data. KeePassDX doesn't care if there is internet or LAN access, the only thing it needs is access to the file data from the URI of the content provider you use (here Nextcloud). So I advise you to look at the NextCloud app configuration instead to find out where your problem comes from.

If KeePassDX does not recognize the data sent by the stream, it is simply not recognizable, so the content provider is in a state that makes it impossible to read the data (maybe a bad cache during a network change or something like that, I don't know), but KeePassDX cannot do anything about it.

I recommend you to read carefully the wiki page about synchronization to understand how KeePassDX works: https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

If you detect unwanted behavior of the NextCloud application, it is quite possible to update the wiki accordingly.

**Comment by Mwaye** [comment]
Hi,

Thanks for your answer.
I will search around NextCloud app if you think problem come from it.
It's really a weird problem and I don't understand.

Thanks again.
Best regards,

**Comment by Mwaye** [comment]
Hi,

Just to close this post. I found the prunelle and no link with KeePassDX directly. Problem was due to the probate DNS fonction enable on phone.

Thanks for your answer and help.
Best regards,
