### ISSUE TITLE
feature request: add YubiKey OTG 2FA (challenge-response mode)

### ISSUE THREAD

**Issue by wildy** [Kunzisoft/KeePassDX#137]
Hi.

KeePassXC has a mode when it relays the password as an input to a YubiKey in challenge-response mode, and I believe Keepass2Android has a similar thing, but only for NFC and a YubiKey NEO.

Since the majority of the users is still stuck with YK4/Nano, it would make sense to implement challenge-response mode over USB OTG, which is widely used, despite being a bit inconvenient at times.

I've been a long time user of KeePassXC on the desktop platforms, and would very much like to see the similar feature on Android.

**Comment by J-Jamet** [comment]
Link to #https://github.com/Kunzisoft/KeePassDX/issues/8 , It is planned but still work to be done before implementing this feature.
