### ISSUE TITLE
Insecure database location - use of private storage

### ISSUE THREAD

**Issue by Jowat97** [Kunzisoft/KeePassDX#1376]
The databases are stored on the regular shared storage, where every other app with access to your data could also access the (encrypted) database as well. But android supports private storage, where only the specific app has access to. It would be very nice to have the possibility to store the database within the private storage. I know, that the database itself is encrypted, nevertheless it would increase the security. It could be added as an optional feature, since it would be harder to replace the database for example.

**Comment by J-Jamet** [comment]
The file is stored wherever you want on the application providing the file, depending on the choice of application you make obviously : https://github.com/2bllw8/anemo

Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/1157
