### ISSUE TITLE
After editin an entry it is not possible to go back

### ISSUE THREAD

**Issue by spocky2** [Kunzisoft/KeePassDX#138]
Hello,
i use KeePassDx with a Database stored on Google Drive.
When i edit an existing entry and after saving it ist not possible to go to back to parent window.
The only way to get out of this modus is to close the app and reopen it again.

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/100

**Comment by J-Jamet** [comment]
Fixed in version 2.5.0.0beta16
