### ISSUE TITLE
Hide clipboard text when copy entry field

### ISSUE THREAD

**Issue by guilpaoff** [Kunzisoft/KeePassDX#1386]
When I copy a password it is displayed in clear text in the bottom right corner of the screen. Apparently you need to activate something but it is beyond my capabilities... Thanks

https://mobile.twitter.com/w0nderfall/status/1561878774769131520

**Comment by J-Jamet** [comment]
I checked and the functionality is well implemented. Checked that you copy in the clipboard a protected data (for custom fields) or a password.
https://github.com/Kunzisoft/KeePassDX/blob/0ef574d67525073a6536bd3b0fe554b9190bd599/app/src/main/java/com/kunzisoft/keepass/timeout/ClipboardHelper.kt#L70

In any case it is not recommended to use the clipboard, use the Magikeyboard instead.
https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

**Comment by guilpaoff** [comment]
Okay I'll use the magickeyboard now

**Comment by J-Jamet** [comment]
I just saw a bug that did not put the tag when you clicked on the copy icon, on the other places it works, I just fixed it.

**Comment by guilpaoff** [comment]
> 

Thank you very much

**Comment by guilpaoff** [comment]
Thanks you very much

**Comment by Eyion** [comment]
> In any case it is not recommended to use the clipboard, use the Magikeyboard instead. https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

While trying to use the Magikeyboard, the problem is that it doesn't work.

**Comment by J-Jamet** [comment]
@Eyion I don't understand the remark, there is no clipboard in the Magikeyboard.

**Comment by J-Jamet** [comment]
This thread has nothing to do with that, please open a clean bug report with the template.
