### ISSUE TITLE
Some devices doesn't clear the clipboard

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#139]
- [x] Add a warning dialog
- [x] Add new deletion method for API 28
~- [ ] Detect the devices with this issue to remove all the "clipboard cleared" elements (Toast...)~
Detect compatible devices is not possible easily from the application, the removal toast has simply been removed.

https://stackoverflow.com/questions/23418543/clear-all-clipboard-entries

**Comment by WAR10CKfreeworld** [comment]
Can confirm this bug appears on Samsung Galaxy S10e.

**Comment by Utico** [comment]
> 
> 
> Can confirm this bug appears on Samsung Galaxy S10e.

I'm still getting this even after the update. I am however using a Galaxy S10.

**Comment by J-Jamet** [comment]
I can't do anything, Samsung phones use a specific clipboard that prevents deletion of copies, so you have to delete the clipboard manually. I do not recommend using this feature to copy passwords. Use the Magikeyboard instead.
