### ISSUE TITLE
KeePassDX does not remember last database

### ISSUE THREAD

**Issue by Af0x** [Kunzisoft/KeePassDX#1394]
Hello,

my KeePassDX app does not remember the last opened database and always tries to open an already deleted file.

KeePassDX 3.4.5 installed with f-droid.

Best regards

**Comment by J-Jamet** [comment]
KeePassDX saves well the latest URIs of open databases. You can display the links broken by your file manager with : 
`Settings -> App settings -> Hide broken database links`

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#explanation

**Comment by Af0x** [comment]
I removed all broken links but still it tries to open the non existent database on startup.

**Comment by Af0x** [comment]
Nevermind, I just reinstalled the app and will monitor how it behaves in this regard. Thanks & best regards
