### ISSUE TITLE
Toolbar not working with MIUI

### ISSUE THREAD

**Issue by ch-dillen** [Kunzisoft/KeePassDX#1395]
Hello,

I'm using KeepassDX 3.4.5 (German) on my Andorid phone (Pocophone, with MIUI 12.0.3 and Android 10)

After opening Database I see all my folders and entries and can navigate withtin the folders.

But I cannot Search or Sort using the top menu icons. 
also no reaction on the 3 bars or 3 dots. 
Seems the to menu bar is "dead".

Any ideas how to overcome.

Christof.

**Comment by J-Jamet** [comment]
Same as https://github.com/Kunzisoft/KeePassDX/issues/1375
Seems to happen only with MIUI, personally I can't reproduce the problem.
