### ISSUE TITLE
AutoOpen Support and Switching Databases While Open

### ISSUE THREAD

**Issue by seniorm0ment** [Kunzisoft/KeePassDX#1398]
The ability to support AutoOpen https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening
Would be amazing.

As well as being able to switch databases without needing to close the other one.

It's annoying to need to unlock a db, get a password, close it, open another one, close it, then go back into the original one to get more stuff.
KeeoassXC on desktop can just use autoopen, opens both databases, and you can use tabs to switch between the two open databases."

**Comment by J-Jamet** [comment]
Duplicate #915
Linked to https://github.com/Kunzisoft/KeePassDX/issues/209
