### ISSUE TITLE
Problem in layout of new version [2.5.0.0beta3]

### ISSUE THREAD

**Issue by gerardo-junior** [Kunzisoft/KeePassDX#14]
Problem with folder icon of new version

> Android 7.1.2
> KeepassXD 2.5.0.0beta3
> Resolution 1920x1080 
> Device: MOTO G4 (without fingerprint reader)

![indice](https://user-images.githubusercontent.com/9096410/33962852-a8d7cb5e-e031-11e7-9d0a-629b4f30b01c.jpeg)

**Comment by J-Jamet** [comment]
Can you tell me how you would see the new interface, which would be the most convenient for you (ergonomically) ?

**Comment by gerardo-junior** [comment]
I'll take a closer look but you have the .psd layouts or some specific styleguide for that app. I'm a developer but I can do some desgin things and i can start contributing to this.

**Comment by J-Jamet** [comment]
I don't use proprietary programs at all. I specialized in open source computer graphics and I created my files with Inkscape, Krita or The Gimp on linux (I always favor vector images and not really need a mock here). It was just to find out if you wanted something in particular but I'm going to change the layout of the elements to be more ergonomic.

**Comment by gerardo-junior** [comment]
no problem, where do I find the .svg's? in the art folder only has the bitmap.

and I'm a fan of taking that part out and putting a database listing found on the device, sort of what vlc does with songs.

and in that button below, when clicking it expander type google inbox with create, open and etc

**Comment by J-Jamet** [comment]
The new ergonomics is OK for you? The whole green part is retractable according to the list.
![device-2018-01-12-205818](https://user-images.githubusercontent.com/19224038/34893088-fbe81dd2-f7db-11e7-9b79-91aa9f093307.png)

**Comment by gerardo-junior** [comment]
@J-Jamet I think it's better 

but i'm a fan of taking out this button, open automatically. but would have to review flow

**Comment by J-Jamet** [comment]
There is a small problem for automatic opening, it only works if a file manager is installed on the device. For the database listing found on the device, it requires more work and no time for the moment. :/ 
I'll already change the list to display only the file names with an information button for each (With RecyclerView)
