### ISSUE TITLE
Downloading attachment button doesn't work

### ISSUE THREAD

**Issue by SomeTroglodyte** [Kunzisoft/KeePassDX#1401]
**Describe the bug**

I have some ID card images (jpegs) attached, created on desktop. I can view them within KeePassDX, but not extract them.

**To Reproduce**

0. Open DB created in original desktop keepass (Database version, Data compression Gzip)
0. Open entry containing attachments
1. Tap icon to the right of name/size/Gzip of an attachment
2. No new file anywhere, no pertinent logcat message

**Expected behavior**

I'd expect a file in `Internal shared storage/Download` or `Internal shared storage/Documents`

**KeePass Database**

 - Created with: desktop KeePass, last saved by Linux keepass2 [2.45+dfsg-1\~ubuntu20.04\~ppa1]
 - Version:  `V2 - KDBX3.1`
 - Location: `Internal shared storage/Documents`
 - File provider : `content://com.android.externalstorage.documen/document/primary%3ADocuments%2FKeepass-rh.kdbx`
 - Size: 6.14 Mo
 - Contains attachment: Oui bien sûr

**KeePassDX:**

 - Version: git clone as of a few minutes ago run from Android Studio 2021.2.1 Patch 2, originally whatever F-Droid offers today (I guess the 3.5.0 Beta01 it shows refers to what the debugger installed, and I had been trying 3.4.5 before)
 - Build: Free
 - Language: English

**Android:**

 - Device: Xiaomi Mi10T = M2007J3SG
 - Version: 12, LOS/µG, 19-20220821-microG-apollon (_NO_ GApps)

**Additional context**

As hinted, same observation using latest F-Droid build or run from current source in the debugger. Clearing logcat and hitting the button results in just two fresh logcat lines:
```
2022-09-13 21:43:25.829 8460-8460/com.kunzisoft.keepass.free D/TimeoutHelper: Record app timeout
2022-09-13 21:43:25.830 8460-8460/com.kunzisoft.keepass.free D/TimeoutHelper: TimeoutHelper start
```
Breakpoints on [AttachmentFileBinderManager.startDownloadAttachment](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/tasks/AttachmentFileBinderManager.kt#L130), on [AttachmentFileBinderManager's listener's onAttachmentAction](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/tasks/AttachmentFileBinderManager.kt#L52), or [here](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/services/AttachmentFileNotificationService.kt#L94) or [here](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/services/AttachmentFileNotificationService.kt#L119) or [here](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/services/AttachmentFileNotificationService.kt#L133) or [here](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/services/AttachmentFileNotificationService.kt#L325) or [here](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/services/AttachmentFileNotificationService.kt#L415)  - none ever hit. Sorry for the shotgun approach, didn't really analyze the code except a global search and some 'Find Usages'.

The only error in logcat happens on opening the entry, but doesn't necessarily seem related: `2022-09-13 21:52:31.261 8460-8460/com.kunzisoft.keepass.free E/ft.keepass.fre: No package ID ff found for ID 0xff4caf50.`.

Same database, in February (so the desktop app that last saved it might have been a version or two older), on a Mi8 running LOS16, opened in Crocoll's app, worked. This time around I wish to make do without Aurora store, so that test is outdated - if you insist I could do a current comparison.

Of course, any debug instructions welcome.

**Comment by J-Jamet** [comment]
It's a little bug, it seems that the download icon doesn't get the event correctly but it works if you click on the name. So it's just a view event problem.

Click on the name on the left while waiting for the fix.
