### ISSUE TITLE
Magikeyboard enhancement

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#141]
- [x] Timeout to clear the keyboard entry
 - [x] Vibration
 ~- [ ] Vibration duration~
 - [x] Long press to select another keyboard
 - [x] Add the new flow (#182)
 - [x] Follow the app timeout
 - [x] Add the current entry name to the keyboard view

**Comment by juwancase** [comment]
This should be obvious to you, if you're going to implement the keyboard timeout, the default  should follow the "App timeout" if the user has changed the app timeout.

**Comment by J-Jamet** [comment]
The Magikeyboard is much better with the new release. :)
