### ISSUE TITLE
Can't copy password-fields? 

### ISSUE THREAD

**Issue by jivarson** [Kunzisoft/KeePassDX#1410]
Must be missing something here?

In version 3.5.0 Beta01 (Pro) there's no option to copy a Password-field?

There's just the Eye-icon, whereas other fields have the clipboard icon.
I get that copying passwords sucks and that autofill should be used, but is this behavior really intended?

**Comment by J-Jamet** [comment]
This feature has not been changed. "Settings - Form filling - Clipboard trust"
