### ISSUE TITLE
YubiKey authentication crashes every first time the device is plugged and used.

### ISSUE THREAD

**Issue by J053Fabi0** [Kunzisoft/KeePassDX#1411]
**Describe the bug**

Every first time you use the YubiKey the driver crashes, just after asking "Allow Key Driver to access YubiKey OTP+FIDO+CCID".
In order to use it I have to try again. What I think it makes it crash is when it asks for permission to use it.
My YubiKey is configured to not require touching.

I leave a video here:
https://i.ibb.co/MnFjtX5/Screen-Recording-20220927-103405-Kee-Pass-DX.gif

**To Reproduce**

1. Insert YubiKey.
2. Try opening the database.
3. Click Ok when the driver app asks if it can use the YubiKey.
4. See the error.

**Expected behavior**

1. Insert YubiKey.
2. Try opening the database.
3. Click Ok when the driver app asks if it can use the YubiKey.
4. Not see the error.

**KeePass Database**

 - Created with: KeePassXC 2.7.1 Linux.
 - Location: database file located in the Android phone.

**KeePassDX:**

 - Version: 3.5.0 Beta01
 - Build: libre
 - Language: English

**Android:**

 - Device: Galaxy S21 Ultra 5G
 - Version: SM-G9980

**Additional context**

 - YubiKey: 5C1 5.4.3
 - Slot 2: OTP, Challenge-response, no touch required.
 - Key Driver: 0.1.3

**Comment by J-Jamet** [comment]
The problem comes from the Key Driver application still under development. The associated issue is https://gitlab.com/kunzisoft/android-hardware-key-driver/-/issues/1
I'm closing this one.
