### ISSUE TITLE
On back button press app comes to same screen and doesn't lock

### ISSUE THREAD

**Issue by ryg-git** [Kunzisoft/KeePassDX#1412]
**Describe the bug**

If user has enabled `Press 'Back' to lock` in settings, and user discards the add entry screen then app will not lock on back button press.

**To Reproduce**

1. Go to Settings > App settings
2. Under 'Lock' section enable `Press 'Back' to lock` setting.
3. Then try to create a new entry by clicking `Add entry`.
4. Discard the entry creation midway by tapping `DISCARD` in Alert dialog.
5. Now try to lock the db by pressing back button on initial screen.
6. You will notice that the app is coming back to same screen instead of locking the db.

**Expected behavior**

The app should lock the db on back press even if user discards the entry creation.

**KeePass Database**

 - Created with: KDBX3.1
 - Version: V2
 - Location: Device Internal Storage

**KeePassDX:**

 - Version: 3.5.0 Beta01
 - Build: Free
 - Language: English

**Android:**

 - Device: Realme GT Neo 2
 - Version: 12

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by ryg-git** [comment]
If it is okay I would like to work on this issue

**Comment by J-Jamet** [comment]
> If it is okay I would like to work on this issue

Yes of course, it's a problem to be solved in the current version 3.5.0 so I'll merge your code as soon as it's OK.
