### ISSUE TITLE
Cant install the hardware key driver "Problem parsing package" from official gitlab

### ISSUE THREAD

**Issue by aboss10123** [Kunzisoft/KeePassDX#1413]
**Describe the bug**

Since the latest update brings support for yubikeys, I have recently tried installing the package from the releases page in gitlab https://gitlab.com/kunzisoft/android-hardware-key-driver. However, since it was a zip file I had to rename it to apk to install (A few other apps do this on gitlab so I assumed this was the way to do it as well). However, on android 13 it says there was a problem parsing this package and I am not sure why none of the versions worked even though it was updated about a week ago.

My device is pixel 6 with graphene OS on android 13. The play store version works fine if that means anything but however for those who wish to install it from git I am afraid I am not having luck with that. Also there is a typo in the most recent release when it was said APL instead of APK I don't know if this was on purpose or if it refers to something totally different.

Regards,

**Comment by J-Jamet** [comment]
The zip file should not be renamed but opened and unzipped as it contains a folder architecture with a debug APK inside.
Thank you for opening the issue on the right project (here, the gitlab one).

**Comment by J-Jamet** [comment]
Duplicate https://gitlab.com/kunzisoft/android-hardware-key-driver/-/issues/1
