### ISSUE TITLE
Publishing of apk signatures 

### ISSUE THREAD

**Issue by shift18** [Kunzisoft/KeePassDX#1416]
Hi

Could you please publish the apk certificate digest for all different platform/releases so one can manually verify the authenticity of your app?
Ideally you would publish this information separately from the apk's themself and on several different platforms.

example output from apksigner
apksigner verify --print-certs Signal-Android-website-prod-universal-release-5.50.4.apk
Signer #1 certificate DN: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Signer #1 certificate SHA-256 digest: 29f34e5f27f211b424bc5bf9d67162c0eafba2da35af35c16416fc446276ba26
Signer #1 certificate SHA-1 digest: 45989dc9ad8728c2aa9a82fa55503e34a8879374
Signer #1 certificate MD5 digest: d90db364e32fa3a7bda4c290fb65e310

Thank you.

**Comment by J-Jamet** [comment]
**F-Droid** (com.kunzisoft.keepass.libre) : 
DN: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
SHA-256 digest: c810aab7efa4d5ad3fc2941fdf5f99b88a3b73f86219715627edb4dabac541a4
SHA-1 digest: 733c4dab72766b758c25549ca3f25327ad39c5b8
MD5 digest: 2bbdc4d3b9108c9daf086790b8682227

**Github** (com.kunzisoft.keepass.free) : 
DN: CN=Jeremy JAMET, OU=Kunzisoft, O=Kunzisoft, L=Rennes, ST=FRANCE, C=FR
SHA-256 digest: 7d55b8af210381aabf960f07e17cf7857b6d2a642ca2da6bf0bdf1b200362f04
SHA-1 digest: d828ca050f62e28f608a9e54c8a15c98a1079659
MD5 digest: 03a419a7f89a8502efbe93ee2299d455

**Play Store** (com.kunzisoft.keepass.free) : 
DN: CN=Android, OU=Android, O=Google Inc., L=Mountain View, ST=California, C=US
SHA-256 digest: 46d515d5f41572420cef30c07b526bf2c40fc4a113ef191f4f9df9012e091f35
SHA-1 digest: 31ca5b5ca339fed586d3d8c37a6a40ef72039615
MD5 digest: 8b46aa3cba9988bf16c31f18dc1df6e9

**Comment by shift18** [comment]
Thanks!
