### ISSUE TITLE
kdbx 4.1 Support?

### ISSUE THREAD

**Issue by DorianVasco** [Kunzisoft/KeePassDX#1419]
I can't open my recent kdbx files anymore .. saved with recent version of KeePassXC 2.7.1 on Windows.
Are 4.1 files not supported yet?

**Comment by Havokdan** [comment]
https://github.com/Kunzisoft/KeePassDX/releases/tag/2.10.0

"(...)Manage new database format 4.1(...)"

I should bear...

**Comment by J-Jamet** [comment]
KeePass 4.1 format is well supported. Check that it is not a transfer problem between your PC and your phone.

**Comment by DorianVasco** [comment]
ok, whatever went wrong here, I saved my kdbx file again with the latest KeePassXC into my nextcloud and now it worked fine, as expected.
