### ISSUE TITLE
FileNotFoundException or Access revoked by file manager error (built in file manager)

### ISSUE THREAD

**Issue by Akhilesh-T** [Kunzisoft/KeePassDX#1423]
The access to the database is revoked frequently on this app.

My database is stored in google drive and I use biometrics to unlock it. I read on wiki that `several file managers offer links with a limited duration or with break conditions`. However, I do not use any third party file manager for this purpose. And interestingly, I have never had such issues with **Keepass2Android** app.

The unlocking works initially but is revoked automatically after a few hours.

**Comment by J-Jamet** [comment]
Google Drive is a third party file manager.
KeePass2Android uses cloud API integration directly in its code : https://github.com/Kunzisoft/KeePassDX/issues/342

The unlocking works initially but is revoked automatically after a few hours : You can contact the Google Drive team to change this behavior.
A workaround is planned with the creation of a dedicated file manager application : https://github.com/Kunzisoft/FileSync
Feel free to read the content of the issues and review the wiki for more information.
