### ISSUE TITLE
Autofill Service not working

### ISSUE THREAD

**Issue by karotte512** [Kunzisoft/KeePassDX#1426]
I recently upgraded to a Pixel 7 Pro (Android 13) and I'm not able to get the Autofill Service running.
At any login page there is no popup appearing above the Keyboard to use KeePassDX.

I used export/import to transfer the settings of KeePassDX to the new phone, set KeepassDX as the default Autofill Service (obviously) and disabled battery optimisation.

On my old phone I had the same issue occasionally, but on the new phone the autofill suggestion never showed even up once.

Am I missing something? Or is anyone having similar problems?

**Comment by J-Jamet** [comment]
Please fill in the bug template correctly, indicating the browser used, its version and the form tested.
The autofill is to be refactored because there are forms not detected, but it should at least still be displayed on some forms.
If you have nothing at all, it may be a bad update or a service activation problem.

**Comment by karotte512** [comment]
Describe the bug
When opening any App, there is no suggestion to use Autofill at the login page

To Reproduce
Try logging in, in any App

KeePass Database

Created with: V2 - KDBX 4.1
Location: stored locally on the device

KeePassDX (please complete the following information):

Version: 3.4.5
Build: Free
Language: German

Android (please complete the following information):

Device: Pixel 7 Pro
Version: 13

Additional context
Add any other context about the problem here.

I'm not sure what you mean with what browser I used, the problem occurs in every app with an login page (and also with logins within the browser)
I added screenshots to show the difference between the old and the new phone in the same app.
Please let me know if you need any further information.
Thank you! :)

![old](https://user-images.githubusercontent.com/46969921/197863300-bb188050-d794-4857-8461-fd4a64ea92b4.jpg)
![new](https://user-images.githubusercontent.com/46969921/197863358-924a8fc9-4017-49a3-9e55-e26ba3d68ad8.png)

**Comment by Onkeljoes** [comment]
Hi.
I had the same issue. Did you use the KeePass dx internal backup and restore function to transfer the settings to your new phone?
If so - try a fresh installation without restoring the settings. This solved the issue for me.

**Comment by karotte512** [comment]
Thanks for the advice, I did use the backup/restore function. 
A fresh installation of the app without restoring solved the issue.

**Comment by Onkeljoes** [comment]
Glad I could help. :)
This more or less confirms my feeling that the backup/restore function has an issue / bug. I guess this is at least a good starting point when trying to solve it.

**Comment by J-Jamet** [comment]
I will check if there are bugs with the backup and restore functions. Don't hesitate to put your backup configuration that doesn't work in order to facilitate the resolution.

**Comment by newhinton** [comment]
I am not sure if this is the right ticket, but with fenix 111.1 i ca trigger the password promt only on clicking the password input, not the username. One example is reddit.com.

Using Lineageos 18.1 (Android 11)

Is this a firefox-issue?


If i use android's webview inside an app, keepass works as expected.

**Comment by J-Jamet** [comment]
Fixed with https://github.com/Kunzisoft/KeePassDX/issues/1665#issuecomment-1793425464
