### ISSUE TITLE
Can not re-enable Biometric unlock

### ISSUE THREAD

**Issue by AdKiller** [Kunzisoft/KeePassDX#1427]
After disabling device's fingerprint unlock & deleting stored fingerprint, and re-enabling it, can not enable biometric unlock in KeePassDX anymore.

**To Reproduce**

- Enable device's fingerprint unlock
- Enable biometric unlock in KeePassDX (it worked fine)
- Disable device's fingerprint unlock
- Enable device's fingerprint unlock
- KeePassDX biometric can not be enabled anymore.
after opening database it says: 
"This database does not have stored credential yet."
"Type in the password and then click this button. (fingerprint icon)" <-- did that, but nothing happens.

**KeePass Database**

 - Created with: [e.g Windows KeePassXC 2.7]
 - Location: [SD card]
 - Size: [13 KB]
 - Contains attachment: [e.g. No]

**KeePassDX:**

 - Version: [3.4.5]
 - Build: [Free]
 - Language: [English]

**Android:**

 - Device: [Samsung Galaxy S7]
 - Version: [8.0.0]

**Additional context**

Tried delete from keystore, disabling/enabling biometrics, clear cache and data of the app.

I could successfully re-enable biometrics unlock in other apps that I use.

**Comment by J-Jamet** [comment]
> "Type in the password and then click this button. (fingerprint icon)" <-- did that, but nothing happens.

If nothing happens, it means that the KeyStore of your device does not accept the generation of keys linked to the fingerprint.
The application cache is not linked.
How did you try to remove the key from the KeyStore?

**Comment by AdKiller** [comment]
> > "Type in the password and then click this button. (fingerprint icon)" <-- did that, but nothing happens.
> 
> If nothing happens, it means that the KeyStore of your device does not accept the generation of keys linked to the fingerprint. The application cache is not linked. How did you try to remove the key from the KeyStore?

In the settings of KeePassDX. Is there any other method?

**Comment by J-Jamet** [comment]
By deleting the file in /data/misc/keystore/user_0/ https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking#errors

**Comment by J-Jamet** [comment]
But this is a last resort. There are big problems with Samsung because the internal API code with Keystore is not correctly implemented: https://github.com/Kunzisoft/KeePassDX/issues/1269

**Comment by AdKiller** [comment]
I should add that I could successfully re-enable biometrics unlock in other apps that I use.

**Comment by J-Jamet** [comment]
Most other applications do not use the KeyStore in the same way.

**Comment by J-Jamet** [comment]
Do you have PIN, Password or schema protection activated when the phone is locked?

**Comment by AdKiller** [comment]
Schema protection was activated. the only solution was uninstalling and reinstalling KeePassDX.

**Comment by J-Jamet** [comment]
Good if it works now, but I don't see why deleting the keys didn't work but uninstalling and reinstalling did.
Have you restarted your device in the meantime?
