### ISSUE TITLE
Larger tab button

### ISSUE THREAD

**Issue by MkQtS** [Kunzisoft/KeePassDX#1428]
**Is your feature request related to a problem? Please describe.**

Currently, the main and advanced button are a little small, not convenient for a mobile touch screen.

![image](https://user-images.githubusercontent.com/81752398/197980322-39d81544-8a53-40d4-8132-6cc14c207790.png)

**Describe the solution you'd like**

Larger buttons would be nice, like [NewPipe](https://github.com/TeamNewPipe/NewPipe)

![image](https://user-images.githubusercontent.com/81752398/197981179-e446bfa6-22ad-400c-bbe3-3ed812b55470.png)

The pic shows the *Comments* and *Description* button on NewPipe video page. For KeePassDX, the *Lock* button can be placed above the bottom bar.

**Comment by J-Jamet** [comment]
Tabs have been enlarged by *2 in width.
