### ISSUE TITLE
Fingerprint doesn't not unlock database in Beta 13

### ISSUE THREAD

**Issue by PAFsec** [Kunzisoft/KeePassDX#144]
Hi,

First, thank you for your work. It is amazing.

The fingerprint "listening" feature in order to unlock the databases doesn't work since the Beta 13.

Do you have any idea ?

Have a great day and keep on the good work!! :)

**Comment by J-Jamet** [comment]
Hello,
I changed the fingerprintmanager implementation that was not detected by some users of the old version. If it prevents some other users from having access to it is annoying ... Have you tried to delete the keys of fingerprints in the settings?

**Comment by PAFsec** [comment]
Hello !

It actually now works after deleting the old keys !

Thank you !!
