### ISSUE TITLE
Passcodes unreadable at night

### ISSUE THREAD

**Issue by strider72** [Kunzisoft/KeePassDX#1441]
When the phone is on Dark mode, the special characters on passwords are dark blue on black. This is very difficult to read.  Add in "Night light", where the phone color shifts toward red late at night, and this become practically black on black.

Please lighten the shade of special characters when the phone is in dark mode.

**Comment by J-Jamet** [comment]
@strider72 Which theme do you use?

**Comment by strider72** [comment]
> @strider72 Which theme do you use?

Classic
