### ISSUE TITLE
Can't modify or open database on KeepassDX

### ISSUE THREAD

**Issue by hectour3** [Kunzisoft/KeePassDX#1442]
I recently moved to Android and wanted to use my Keepass database with KeepassDX. When I first open the file everything is fine, but when trying to add a new entry it gives an error that the file can not be saved. After locking and then trying to unlock the database again I get the error "Could not load your database. java.lang.NegativeArraySizeException: -1" . Once this error occurs it stays and the only way to open the database is to redownload it fresh from my cloud provider.

I created the file with KeepassXC and set the encryption level at its highest. It uses KDBX 4. Most of the data in it was imported from 1Password.

**Comment by J-Jamet** [comment]
Your problem is undoubtedly with your cloud provider, can you tell us what it is? In order to fill in the wiki summary table in detail.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by hectour3** [comment]
I m pretty sure that is not the problem. I tried to create an entry when the file is saved on ProtonDrive, and then it indeed gives me the error that the file could not be saved rightaway. I then put a fresh copy of the file in my downloads folder, opened it, tried to add an entry. It tries to save it for about 10 seconds and gives me the warning not to kill the app. I then get the error that the file could not be saved. If I then lock the file and try to unlock it again it gives me the error "Could not load your database. java.lang.NegativeArraySizeException: -1"

**Comment by J-Jamet** [comment]
It's weird, I've never had this kind of problem with a local file. The exceptions raised with "Could not load your database." can be a database content provider issue but also a key file issue, can you tell me what is the format of the URI you are trying to open? (ie : "content://...)

**Comment by hectour3** [comment]
content://com.android.providers.downloads.documents/document/17

It seems that the error "Could not load your database. java.lang.NegativeArraySizeException: -1" is the result of a corruption of the file. When I put a fresh copy in the downloads directory it opens fine. The error occurs after I have tried to add a new entry, which fails, and then try to open the file again after locking.

**Comment by J-Jamet** [comment]
To resolve the bad formatting of your .kdbx file you can use KeePass2 for PC, export your database in xml and reimport it, which will rebuild the database.
