### ISSUE TITLE
Add Google Drive support 

### ISSUE THREAD

**Issue by Wetzel402** [Kunzisoft/KeePassDX#1445]
**Is your feature request related to a problem? Please describe.**
I really like the modern look of KeePassDX and would like to move to it over KeePass2Android but because I use Google Drive to host my database I cannot.

**Describe the solution you'd like**
Add Google Drive database support similar to the KeePass2Android project.

**Describe alternatives you've considered**
Opening the database using the file picker which can cause issues.  Plus, for some reason Google Drive doesn't even appear on my current phone's file picker.

**Comment by J-Jamet** [comment]
Topic covered dozens of times : https://github.com/Kunzisoft/KeePassDX/issues/342
Linked to https://github.com/Kunzisoft/FileSync/issues/4
