### ISSUE TITLE
apksigner verify returning non-matching certificates

### ISSUE THREAD

**Issue by ash-teach** [Kunzisoft/KeePassDX#1448]
Published certificates for [KeePassDX-3.4.5.apk](https://github.com/Kunzisoft/KeePassDX/releases/tag/3.4.5) release are as follows

> MD5 : 4e2eb47d58e610ebe1bf7183225650ec
> SHA1 : bcd6f11bb2215bf173b9ceaa329a8c106aa6644b
> SHA256 : ed87a643bca3259abe58aa1ecb8ae45cce6f7701e1fa436458fcc41cdad2859a
> CRC32 : f99e1a6a

Output from apksigner verify is as follows:

> SHA-256 digest: 7d55b8af210381aabf960f07e17cf7857b6d2a642ca2da6bf0bdf1b200362f04
> SHA-1 digest: d828ca050f62e28f608a9e54c8a15c98a1079659
> MD5 digest: 03a419a7f89a8502efbe93ee2299d455

Using Android Build Tools 30.0.3

**Comment by J-Jamet** [comment]
Don't confuse the hash of APK files with the hash of apk signing certificates.

The signatures of the APK will always be the same and are in the following issue : 
https://github.com/Kunzisoft/KeePassDX/issues/1416

The hashes of the files of each apk version allow to verify that a file has been downloaded correctly.
