### ISSUE TITLE
Feature: Pressing Enter after password is entered should open database

### ISSUE THREAD

**Issue by ecki** [Kunzisoft/KeePassDX#145]
On a Chromebook with no touch but keyboard it would be much more convinient if you can press enter and the password for a remebered database is accepted (instead of navigating to the open button). Also it looks like the tab focus could be a bit better (password, keyfile, open and only then checkboxes)

**Comment by J-Jamet** [comment]
Very well, to be honest, I have not yet tested the chromebook, I will have to install a test system for this platform. But you're right, it will be better for the user experience.

**Comment by ecki** [comment]
Besides the enter key it does seem to be working pretty well on the No-Touch Chromebook.

I am not sure but I have the impression it is terminated more often than on a Android Mobile but maybe its just the way I use it (the back button on the android windows seems to terminate the application)

**Comment by J-Jamet** [comment]
I improved the views but I can not really tested with my emulator, tell me if it's ok with the new version.
