### ISSUE TITLE
Advanced unlocking stopped working 

### ISSUE THREAD

**Issue by tamiroff** [Kunzisoft/KeePassDX#1450]
**Describe the bug**
Since a recent update the credentials disappeared and I can not configure a new one. 
I always get the message "this database doesn't have stored credentials yet"
Even though I disable enable the device credentials unlocking and the biometric unlocking. 

**To Reproduce**

**Expected behavior**

**KeePass Database**

 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android:**

 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by marsch1975** [comment]
I had the same issue. After a while it was working doinf it over and over again... Now I changed the Database and it all began again. I'm very fed up....

**Comment by marsch1975** [comment]
OK, I found out what I did a few weeks ago when it was finaly working...

After typing in the Password on the first dialog screen after opening the app and activating the biometric unlocking you have to type on the fingerprint logo on top of the password... 

That's not very understandable and other apps do not work that way thtat's why your not expecting it that way...

**Comment by J-Jamet** [comment]
Other applications often use a server-based authentication system, which is not the case with KeePassDX which uses a completely local biometric unlock with a KeyStore. And even if the biometric recognition feature is enabled, you have to define which databases should benefit from it or not. Everything is in the wiki.
