### ISSUE TITLE
How to change the keyfile?

### ISSUE THREAD

**Issue by Lemon-in-Suspense** [Kunzisoft/KeePassDX#1451]
I have secured my database with a master password and a keyfile (generated from OpenKeyChain). Now I want to change the keyfile to something else. Kindly guide me on how to change the keyfile for the database. Also, some keyfile ideas are welcomed...

**Comment by J-Jamet** [comment]
Open the database, then Settings - Master key - Change master key

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/1290
