### ISSUE TITLE
Improving the addition of tags

### ISSUE THREAD

**Issue by Lemon-in-Suspense** [Kunzisoft/KeePassDX#1452]
While trying to add tag to the entry for the first time, I am unable to do so. I typed the desired tag name and saved but the tag isn't being saved.
![Imagepipe_0](https://user-images.githubusercontent.com/118636660/204637550-36504b7a-8738-4461-9f58-fc25b2db70a1.jpg)

**Comment by J-Jamet** [comment]
I understand that it is not obvious, but you have to press enter or "," so that the text of the tag turns into a thumbnail.

**Comment by Lemon-in-Suspense** [comment]
> I understand that it is not obvious, but you have to press enter or "," so that the text of the tag turns into a thumbnail.

It worked! Thanks for your help.
