### ISSUE TITLE
Nextcloud integration?

### ISSUE THREAD

**Issue by falconws** [Kunzisoft/KeePassDX#1453]
KeePass2Android has Nextcloud integration included.
Does KeePassDX have same feature?
I want to put keepass db file on Nextcloud server and sync it.

**Comment by J-Jamet** [comment]
Same as https://github.com/Kunzisoft/KeePassDX/issues/342
Nexcloud is planned on the FileSync application https://github.com/Kunzisoft/FileSync
More info : https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by melroyvandenberg** [comment]
I only see an initial commit on "[FileSync](https://github.com/Kunzisoft/FileSync)"? No updates?

**Comment by J-Jamet** [comment]
I have the architecture of the application in mind, but I just don't have the time to develop it and I always have a more urgent project. It's obviously planned, I'm just working on my free time.

**Comment by teras** [comment]
Hello @J-Jamet and thank you for this awesome app. Still I believe this issue should remain open, since practically is not "fixed" yet. This is a feature that I miss too, and it wasn't possible to find it, unless I removed the "open only" filter. Nobody wants to pollute the issue tracker, right?

**Comment by J-Jamet** [comment]
Opened issue : https://github.com/Kunzisoft/FileSync/issues/11
