### ISSUE TITLE
loss of unsaved items after self-locking the smartphone

### ISSUE THREAD

**Issue by baudav** [Kunzisoft/KeePassDX#1457]
**Describe the bug**
New entries added to a database are lost when the smartphone screen is turned off (and locked)
I opened a database for writing.. created several new entries... then busy continuing the connection on the PC.. the smartphone locked itself.. When unlocking the smartphone, the entries placed in the database do not exist more.

**To Reproduce**
-Open database (read/write access)
-add new entry
-wait for the screen to turn off (lock)
-unlock it

**Expected behavior**
-after unlock, not loss record added.. perhaps request code to unlock database
-or immediate save database, or temporary database to not loss record added

**KeePass Database**

 - Created with: KeePassDX3.4.5
 - Version: 2
 - Location: local
 - File provider (`content://` URI):content://com.android.externalstorage.documents/document/home:database.kdbx
 - Size: 2,6Ko
 - Contains attachment: no

**KeePassDX:**

 - Version: 3.4.5
 - Build: Free
 - Language: French

**Android:**

 - Device: MiMix3
 - Version: 10  (MIUI 11.0.5)

**Comment by J-Jamet** [comment]
This is not a bug, if you add an entry and validate it, the autosave event is triggered. Maybe you have disabled the autosave setting.
In this case when you validate an entry or any action, the auto-save event is not triggered. If the screen turns off (and the option to close the database is enabled) then the database is closed but not saved. Rather logical.

-> Setting - App settings - Auto save database
-> Setting - App settings - Screen lock

**Comment by J-Jamet** [comment]
> -after unlock, not loss record added.. perhaps request code to unlock database

Not possible, unlocking the database indicates it is closed

>  -or immediate save database, or temporary database to not loss record added

This is already the case, the setting is activated by default
