### ISSUE TITLE
No guarda las plantillas 

### ISSUE THREAD

**Issue by julgon2012** [Kunzisoft/KeePassDX#1459]
**Describe the bug**

No guarda las plantillas. 

**To Reproduce**

**Expected behavior**

**KeePass Database**

 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android:**

 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
Please fill in the bug report correctly, in English if possible, an automatic translator does the trick.
