### ISSUE TITLE
AU keys are not deleted after expiration time is over.

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#1467]
Description 

If I set biometric unlocking with AU expiration time duration. It's not works as expected. Keys are resides in memory longer than expiration time.

To Reproduce

1. Go to settings. Choose Advanced unlocking.
2. Enable Biometric unlocking.
3. Enable Temp advanced unlocking.
4. Choose Advanced unlocking expiration. Set desired time duration.
5. Back to the credential screen. Enter Password, tap fingerprint icon and touch the fingerprint sensor.
Database is opened now. You can unlock your database anytime for the 

Expected behavior

If I set AU expiration timer to 1 hour. It is expected to delete all keys after 1 hour. But it takes longer than 1 hour to delete all keys. It seems timer is not working properly. It is also true when timer set to 1 day.

KeePass Database

 - Created with: KDBX4.1
 - Version: 3.4.5
 - Location: Internal phone storage
 - Contains attachment: No

KeePassDX:

 - Version: 3.4.5
 - Build: Free
 - Language: English 

Android:

 - Device: moto g52
 - Version: 12

**Comment by J-Jamet** [comment]
Android does not allow the use of exact alarms if the associated permission is not validated by the user.
And even in this case, the alarm may not be accurate because it may be delayed by a manufacturer's overlay.

https://developer.android.com/training/scheduling/alarms

**Comment by J-Jamet** [comment]
Linked #1435

**Comment by J-Jamet** [comment]
Fixed with precise timestamp
