### ISSUE TITLE
Add material you support

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#1469]
**Is your feature request related to a problem? Please describe.**
No, my feature request is related to enhancement in the user experience. The app feels out of date whereas most stock apps present in Android 13 support it.

**Describe the solution you'd like**
Upgrade the design language to Material design 3.

**Describe alternatives you've considered**
None of the alternatives that are as feature rich as KeePassDX support this.

**Additional context**
None

**Comment by giwrgosmant** [comment]
+1 Material You would be awesome.

**Comment by J-Jamet** [comment]
I would also like to put the feature, however, I need to refactor the themes and I prefer to focus on more urgent features at first but I'll ship it as soon as I can.

**Comment by giwrgosmant** [comment]
> I would also like to put the feature, however, I need to refactor the themes and I prefer to focus on more urgent features at first but I'll ship it as soon as I can.

Sure, take your time it's not something very important. It's good to know this is in your plans 👍
Thanks 🙂

**Comment by J-Jamet** [comment]
I'm working on the migration from Material 2 to Material 3 before I can use Material You, and there's a lot of work to do. I'm already trying to clean up the themes, so it won't be finished right away, but it's coming along.

**Comment by J-Jamet** [comment]
There's still work to be done, but 90% of the migration to Material3 has been completed, so I hope you enjoy it.
The notion of a dynamic theme with Material You has not yet been introduced, but will be shortly.
