### ISSUE TITLE
Feature: Search should be always available

### ISSUE THREAD

**Issue by ecki** [Kunzisoft/KeePassDX#147]
When in search results or in a entry there is no search dialog. This does make some navigational sense but I feel that search is such an important often used function that it should be available on each screen without the need to click "back" up to two times. Especially since pressing it one too many logs you out of the database.

On the search results screen the lock application icon is also missing.

**Comment by J-Jamet** [comment]
Totally agree, the refactoring of the research is planned. I will try to make it dynamic with the results below the search, but I must before implement a content provider on a data system that I must standardize.
Linked to https://github.com/Kunzisoft/KeePassDX/issues/26

**Comment by J-Jamet** [comment]
Done in beta16
