### ISSUE TITLE
Add an option to open a database by default rather than opening the database selector

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#1470]
**Is your feature request related to a problem? Please describe.**
Yes, KeePassDX while opening a database file(.kdbx) opens the selector and in day to day use this seems so annoying.

**Describe the solution you'd like**
I would like KeepassDX to add an option to open a databse file by default by adding a toggle for the feature and a selector to select the file which we want to open automatically while opening KeePassDX.

**Describe alternatives you've considered**
As of now every other password manager including open source keepass based password managers like KeePassXC.

**Additional context**
None

**Comment by J-Jamet** [comment]
Select the star on wanted database file.
