### ISSUE TITLE
PIN other that password

### ISSUE THREAD

**Issue by lollita** [Kunzisoft/KeePassDX#1474]
Many services as well as password periodically ask for a pin. 
Is it possible to manage this situation?

**Comment by J-Jamet** [comment]
The requested feature is not precise enough. Currently, the PIN of the device is already taken into account in the advanced unlock.
https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

Linked https://github.com/Kunzisoft/KeePassDX/issues/687
Linked https://github.com/Kunzisoft/KeePassDX/issues/1430

**Comment by lollita** [comment]
I don't refer to unlock app by a pin.
F.e. Bank ask user and password to login and after a "pin" to authorize operation.

**Comment by J-Jamet** [comment]
KeePass does not use a server-based authentication system like a bank might do.
Here it is a simple encrypted file that uses symmetric encryption.

A PIN is simply a sequence of characters limited to 4 digits, if you want to set the master password with only 4 digits to unlock your database, you can already do it.
It is just not recommended, unless you have other factors (key files and yubikey)

If you want to use the device PIN to retrieve the password from your database, you should use advanced unlock.

**Comment by lollita** [comment]
I not refer to server-based.
My bank i fixed:
user: myuser
password: my pwd
pin: 12345

I log with user and password, and to authorize a transfer I put every 12345.

**Comment by J-Jamet** [comment]
KeePassDX does not transfer any data over the network. There is no point in putting a PIN once the database is decrypted, the data is only accessible locally once deciphered, there is no external transfer validation to do.

**Comment by lollita** [comment]
you did not understand nothing!

**Comment by J-Jamet** [comment]
Explain to me.
