### ISSUE TITLE
Upper buttons are blocked (hidden notch in xiaomi)

### ISSUE THREAD

**Issue by TdslPhoenix** [Kunzisoft/KeePassDX#1475]
Description:
The top buttons such as more options, search, sort and go back are blocked from the first moment the application is opened
And as added the time, the wifi status (in the notch area they disappear when opening the app)

How to replicate it:
In the xiaomi application "settings> display> control center and notification shade> hide notch"
Select any of the 2 options
"don't hide"
either
"hide without moving status bar"

How to solve it
In the xiaomi application "settings> display> control center and notification shade> hide notch"
But this time selecting the option "hide and move the status bar"
Another option is to turn the phone 90 degrees so that the buttons are not close to the notch (although if you turn 90 to the left, for example, the button that is next to the notch is useless, but at least the other ones work).
Note
Unfortunately the area with the notch is rendered useless and is wasted screen space.
Maybe making the app not overlap the notches could be a solution (at least for the xiaomi cell phones that I saw many mentioned the same error)

- Created with: [ Android 10, MIUI 12,0,3 KeePass 3.4.5]
-phone model: [Xioami Mi 8 lite]

**Comment by J-Jamet** [comment]
Sorry but for me it's a Xiaomi issue. I don't really what to do in KeePassDX.
Another workaround would be to activate the screenshot mode but this is dangerous.

**Comment by J-Jamet** [comment]
Linked to #1458 https://github.com/Kunzisoft/KeePassDX/issues/1395 & https://github.com/Kunzisoft/KeePassDX/issues/1375

**Comment by d0bro** [comment]
I have the same problem. at the same time, pasting a password from the clipboard does not work, although if you turn it 90 °, then everything is OK

- OnePlus 6T (Android 11)
- /e/OS firmware 1.7 
- KeePassDX v. 3.5.0 beta01

**Comment by PYCODR** [comment]
Same here on Samsung A54 5G Android 13, KeePassDX Version 3.5.1

**Comment by J-Jamet** [comment]
Do you still have this kind of problem?

**Comment by PYCODR** [comment]
Turning the device to landscape orientation works, in portrait mode the upper buttons are still not usable. Version 4.05 libre

**Comment by J-Jamet** [comment]
For me, there's only one explanation. A program comes to the foreground at the top of the screen and transparently overlays KeePassDX. Don't know which application it might be?

**Comment by J-Jamet** [comment]
For notch, I thought I read that you could disable it by app on Xiaomi, so that's the solution here.

**Comment by d0bro** [comment]
I don't see any problems anymore
