### ISSUE TITLE
Full qwerty keyboard to be able to write.

### ISSUE THREAD

**Issue by aldomach** [Kunzisoft/KeePassDX#1476]
It would be nice to be able to use the keyboard for typing, in some cases.
Every time I want to look up a password and I have to change the keyboard, I go to the app/web to type the password and I have to go back to the magic keyboard.
With a basic smartphone and with a high level of encryption, more than 2000 passwords. When changing the app and the keyboard to search, the dB closes again. You waste a lot of time on the keyboard

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/528
Linked https://github.com/Kunzisoft/KeePassDX/issues/311
