### ISSUE TITLE
Autofill does not trigfer on username

### ISSUE THREAD

**Issue by theScrabi** [Kunzisoft/KeePassDX#1478]
Use Autofill with chrome or firefox. It will not trigger when clicking in the username field.

1. Enable automatic autofill
2. go to a website that requires login
3. click in the usernamw fiels
4. autofill menu does not ahow up

**Expected behavior**

Show up

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta01]
 - Build: [e.g. FDroid]
 - Language: [e.g. German]

**Android:**

 - Device: [Fairphone 4]
 - Version: [CalyxOS 4.5.0 Android 13]

 - Device: [Galasytab SM-P610]
 - Version: [LineageOS 19 MicroG Android 12]

**Additional context**

 - Browser for Autofill: Fennec Fdroid

**Comment by drujd** [comment]
How is this a Firefox issue when Keepass2Android works perfectly? Keepassdx is the only autofill provider having this problem, at least for me.

**Comment by J-Jamet** [comment]
@drujd Please open a new issue by indicating precisely the browser version, the version of KeePassDX, the URL of the form that causes you problems with a reproduction procedure.
