### ISSUE TITLE
cannot extract attachements 

### ISSUE THREAD

**Issue by grrosminet** [Kunzisoft/KeePassDX#1479]
I cannot store attachments on my phone : the button has no effect

Keepassdx 3.4.5 and 3.5.0 beta from fdroid
On Samsung s10 running Android 12

**Comment by J-Jamet** [comment]
Linked : https://github.com/Kunzisoft/KeePassDX/issues/1401
This is a small bug that has been fixed in the beta version. Just click on the attachment name.
