### ISSUE TITLE
Yubikey: Use for KeepassXC and KeepassDX

### ISSUE THREAD

**Issue by robert-winkler** [Kunzisoft/KeePassDX#1480]
Hi, I'm considering securing my KeePass DB with a Yubikey.
If I do this, could I still sync my DB and open it with KeepassXC (Linux, diverse) and KeepassDX (android e/OS)?
Best, Robert

**Comment by J-Jamet** [comment]
Yes. KeePassXC and KeePassDX uses the Yubikey Challenge-response in the same way. 
https://github.com/Kunzisoft/KeePassDX/wiki/Hardware-Key
https://github.com/Kunzisoft/KeePassDX/issues/8
