### ISSUE TITLE
YubiKey on the NFC is not working if I set default autofill service to "KeePassDX form autofilling"

### ISSUE THREAD

**Issue by lenz1111** [Kunzisoft/KeePassDX#1482]
**Describe the bug**

If autofill service is disabled I can open my KeePass file using YubiKey challenge-response (via NFC).
If I set default autofill service to "KeePassDX form autofilling", restart application, start to unlock my db it stucks on popup:
"Loading database... 
Waiting for the challenge request...."

**To Reproduce**

1. setup unlocking db with YubiKey challenge-response (via NFC)
2. set default autofill service to "KeePassDX"
3. restart KeePassDX app
4. try to unlock db with YubiKey challenge-response (NFC)

**Expected behavior**

Unlocking db with YubiKey (NFC) should work the same if autofill service is set or not

**KeePass Database**

 - Created with: KeePassXC
 - Version: 2.6.6
 - Location: local file
 - Size: 4kb

**KeePassDX:**

 - Version: KeePassDX Pro 3.5.0Beta02
 - Build: free
 - Language: English

**Android:**

 - Device: Samsung Galaxy S10
 - Version: Android 12

**Comment by J-Jamet** [comment]
Thank you. The problem is solved in KeePassDX Pro 3.5.0Beta02

**Comment by lenz1111** [comment]
I confirm it is working now - thanks!
