### ISSUE TITLE
Java.io.filenotfoundException: File not found with OneDrive

### ISSUE THREAD

**Issue by SnurrDass** [Kunzisoft/KeePassDX#1485]
Having a issue with KeepassDX
When i try to open a vault it prompt me:
Java.io.filenotfoundException: File not found

I delete the db location and add the db again. 
The DB is located in my onedrive. I browse to the file and add, enter password and do my thing.

I lock the DB and when I return and try to open the dB I get Java.io.filenotfoundException: File not found. 

I have to manually brows to the DB every time. 

What I have done to ty fixing the issue:
Clear cache/data from app
Move it to another OneDrive folder
Uninstall reinstall app. 

This problem started in late desember 2022

**KeePass Database**

 - Created with: v2 KDBX 4.1
 - Version: [e.g. 2]
 - Location: onedrive
 - File provider: onedrive
 - Size: 11mb
 - Contains attachment: yes, notes

**KeePassDX:**

 - Version: 3.4.5
 - Build: free
 - Language: norwegian

**Android:**

 - Device: Samsung a53
 - Version: 12

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by JanJenicek** [comment]
I am experiencing same issue. Also be warned new entries from KeePassDX are not stored online in my case. So it may lead to permanent data loss.

**Comment by J-Jamet** [comment]
Same problem already covered here, OneDrive does not manage files properly. Changing files with this file manager is like breaking a URI link.

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#file-access-revocation

https://github.com/Kunzisoft/FileSync/issues/3
