### ISSUE TITLE
Lock preferences in settings are not respected

### ISSUE THREAD

**Issue by SaltyCybernaut** [Kunzisoft/KeePassDX#1486]
**Describe the bug**

No matter what setting is set under 'App settings' -> 'Lock' the app will lock exactly 60 seconds after opening a password entry (whether or not the app is idle).

**To Reproduce**

1. Unlock the database.
2. Open a password entry (this bug does not trigger if you are on the 'folder overview page' or the 'search page').
3. Leave the app idle or interact with it or switch to another app or go to the home screen using the home button.
4. Wait 60 seconds
5. Observe the app lock (even if you are in the middle of interacting with it).
6. This happens no matter what Lock settings have been set (unless you set 'Timeout' to less than 60 seconds).

**Expected behavior**

The expected behavior is for the app to not lock while interacting with it and the lock setting specified in settings are respected.

**KeePass Database**

N/A

**KeePassDX:**

 - Version: 3.4.5
 - Build: Free
 - Language: English

**Android:**

 - Device: Pixel 4a
 - Version: 13

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-did-the-app-lock-before-the-timeout-duration-has-elapsed

**Comment by J-Jamet** [comment]
I am sure that if you enter the application without selecting an entry you have no problem. It's just that you have another feature with a shorter timeout.

**Comment by SaltyCybernaut** [comment]
@J-Jamet, thank you. This apparent but was caused by the Magic keyboard timeout setting.
