### ISSUE TITLE
App buttons don't work, no Login possible

### ISSUE THREAD

**Issue by oupLYF4TUCkn7a** [Kunzisoft/KeePassDX#1491]
**Describe the bug**

After a system update on E/OS (v1.7.) all apps function normal just KeepassDX doesn't: I open the app and can select my database, but after this no button works. I can tip in my password, but can't confirm it. So I can't use the app. I tried to reinstall the app but this also didn't work. Autofill doesen't function anymore.

**To Reproduce**

1. Open the app and select the Database
2. Try to click on a button, nothing happens.
3. Type in the password, confirmation is not possible
4. There is no error code

**Expected behavior**

After typing in the password the app should open the database. It should be possible to go to settings or select a key.

**KeePass Database**

 - Created with: KeepassDX 3.4.5
 - Location: Documents
 - Size: 4,83KB

**KeePassDX:**

 - Version: 3.4.5 and 3.5.0 Beta01
 - Build: Free
 - Language: German

**Android:**

 - Device: Fairphone FP3
 - Version: E/OS 1.7

**Comment by J-Jamet** [comment]
Was KeePassDX working well before you upgraded your system?

**Comment by oupLYF4TUCkn7a** [comment]
Yes, everything was working fine...


-------- Ursprüngliche Nachricht --------
Von: "Jérémy JAMET" ***@***.***>
Gesendet: 26. Januar 2023 20:29:56 MEZ
An: Kunzisoft/KeePassDX ***@***.***>
CC: oupLYF4TUCkn7a ***@***.***>, Author ***@***.***>
Betreff: Re: [Kunzisoft/KeePassDX] App buttons don't work, no Login possible (Issue #1491)

Was KeePassDX working well before you upgraded your system?

**Comment by oupLYF4TUCkn7a** [comment]
I enabled the screenshot mode and after this nothing changed, login is not possible...


-------- Ursprüngliche Nachricht --------
Von: "Jérémy JAMET" ***@***.***>
Gesendet: 26. Januar 2023 23:12:21 MEZ
An: Kunzisoft/KeePassDX ***@***.***>
CC: oupLYF4TUCkn7a ***@***.***>, Author ***@***.***>
Betreff: Re: [Kunzisoft/KeePassDX] App buttons don't work, no Login possible (Issue #1491)

There is a security feature that prevents overlays from other programs from being placed on top of KeePassDX views, this prevents user data capture by the application views.
If you enable the screenshot mode (since 3.5.0) and it works, it means that an application is trying to capture KeePassDX events.

**Comment by J-Jamet** [comment]
In this case I don't know, the only data that changed is your OS, not KeePassDX, so I guess there is a bug in your update.

**Comment by oupLYF4TUCkn7a** [comment]
Ok, thank you!


-------- Ursprüngliche Nachricht --------
Von: "Jérémy JAMET" ***@***.***>
Gesendet: 26. Januar 2023 23:41:59 MEZ
An: Kunzisoft/KeePassDX ***@***.***>
CC: oupLYF4TUCkn7a ***@***.***>, Author ***@***.***>
Betreff: Re: [Kunzisoft/KeePassDX] App buttons don't work, no Login possible (Issue #1491)

In this case I don't know, the only data that changed is your OS, not KeePassDX, so I guess there is a bug in your update.

**Comment by oupLYF4TUCkn7a** [comment]
I solved the issue now: When I tap on the back-button, the keyboard will hide and then it is possible to go on all items in the screen. So after I wrote down my password, I don't just tap on "open", I have to tap on the back arrow first and when there ist no keyboard anymore, then I can open the database. To enable Magikeyboard in the system didn't make a difference, even after a restart.
I thank you for the fast communication!


-------- Ursprüngliche Nachricht --------
Von: "Jérémy JAMET" ***@***.***>
Gesendet: 26. Januar 2023 23:41:59 MEZ
An: Kunzisoft/KeePassDX ***@***.***>
CC: oupLYF4TUCkn7a ***@***.***>, Author ***@***.***>
Betreff: Re: [Kunzisoft/KeePassDX] App buttons don't work, no Login possible (Issue #1491)

In this case I don't know, the only data that changed is your OS, not KeePassDX, so I guess there is a bug in your update.
