### ISSUE TITLE
F-Droid version update

### ISSUE THREAD

**Issue by themike10452** [Kunzisoft/KeePassDX#1496]
is the f-droid version getting updated?

**Comment by J-Jamet** [comment]
Yes, why not : https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kunzisoft.keepass.libre.yml
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-are-updates-not-available-at-the-same-time-on-all-stores

**Comment by luk6173** [comment]
yes, sorry my bad ! Thank you
