### ISSUE TITLE
Request for Adding Support for Storing Database File in KeepassDX Data Folder

### ISSUE THREAD

**Issue by armibotexe** [Kunzisoft/KeePassDX#1499]
Dear KeepassDX Team,

I am a long-time user of the KeepassDX app and have found it to be extremely helpful in managing my passwords. However, I have noticed that the database file is stored in the standard /storage/emulated/0/ folder, which makes it accessible to other apps with storage permission.

As a security-conscious user, I am concerned about the potential security implications of this. To mitigate this risk, I would like to request the addition of a feature that allows the database file to be stored in the KeepassDX data folder (Android/data/[package-name]). This will ensure that the file is only accessible to the KeepassDX app, providing an added layer of security for password database.

I understand that this may require some additional development work, but I believe that it will be well worth it to ensure the security of our password data. I would be happy to provide any additional information or assistance that you may need in order to implement this feature.

Thank you for your time and consideration. I look forward to hearing back from you.

**Comment by J-Jamet** [comment]
KeePassDX behaves only as a file editor and uses the storage access framework to access the data provided by the file provider chosen by the user.
If you want to use private storage on the device, you can use an app for this ([Anemo](https://github.com/2bllw8/anemo))
Read this thread for more information: https://github.com/Kunzisoft/KeePassDX/issues/1157

Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/1157 https://github.com/Kunzisoft/KeePassDX/issues/904 https://github.com/Kunzisoft/KeePassDX/issues/133 https://github.com/Kunzisoft/KeePassDX/issues/1376
Linked to https://github.com/Kunzisoft/FileSync/issues/7
