### ISSUE TITLE
Can't unlock db with Yubikey

### ISSUE THREAD

**Issue by nimser** [Kunzisoft/KeePassDX#1504]
**Describe the bug**

I can't get to unlock the db with my password and the Yubikey. It works properly on Linux with KeepassXC.

1. create kdbx4 db with yubikey HMAC-SHA1 auth on keepassXC
2. Install version 3.5.0 of keepassDX on android 13 
3. Install Key Driver 1.7.0 from [the gitlab repo](https://gitlab.com/kunzisoft/android-hardware-key-driver/-/releases)
4. try to import and unlock the db from previously db file. type password, don't select a key file, and select "challenge-response" yubikey auth
5. when clicking "OPEN" first a screen shows up saying `Plug in or put Yubikey on the NFC reader`.
6. 
    a. *if using a USB OTG dongle and inserting my Yubikey*, the screen `Plug in or put Yubikey on the NFC reader` will disappear after about 2 seconds and end with a `Could not read credentials` red message, even in instances where Yubikey was plugged in to start with.
    b. *If using NFC and swiping* (fast, because the `Plug in or put Yubikey on the NFC reader` disappears in less than 2sec), you'll feel a vibration and see a prompt proposing you to select a default app between brave and chrome. The Key Driver won't show here

**Yubikey**
- hardware Yubikey 5 NFC, usb-a 
- slots: slot2 OTP is setup for HMAC-SHA1 challenge-response and works with KeepassXC

**KeePass Database**

 - Created with: keepassXC 2.7.4 on linux

**KeePassDX:**

 - Version: 3.5.0 stable, from F-Droid

**Android:**

 - Device: Samsung S20 FE 5G
 - Version: Android 13

**Comment by J-Jamet** [comment]
Did you select the correct slot?
With the tests I did, I noticed that if the Yubico page was requested it was either that the NFC receiver was not receiving the response correctly, or that the key was not set, or that the slot was not correct.
Note that the driver is still being designed, so it should work but it is in beta.

**Comment by nimser** [comment]
Regarding 3 possible causes of failure:
1. the NFC receiver is recieving the response, as it vibrates 
2. I did select "Yubikey challenge-response" in the dropdown menu and don't have a key file.
3. **I did match solts** between the Key Driver app and Yubikey Manager.

Note that using USB on the phone also fails with the same error. Is that a hint of some kind?
Could that be that the db format expected is not compatible with the default settings in KeepassXC (Argon2d - KDBX4 + AES256-bits)?


For the record, this is what I see:

<img src="/uploads/dbaa2442e92f54979a7ff3d3fc203b24/Screenshot_20230209_214238_Key_Driver.jpg" height=400 />
<img src="/uploads/0fb4b2de3a40f48dc0d2b1086b2ecd02/Screenshot_20230209_214813_Android_System.jpg" height=400 />
<img src="/uploads/0dd88b7a9bbcb9a9bad4d549ee13f91a/Screenshot_20230209_222109_KeePassDX.jpg" height=400 />

**Comment by nimser** [comment]
OK seems that uninstalling the Key Driver 1.7.0 I got from Github, and installing the Google Play Store version instead fixed the issue...

**Comment by notmentaloutlaw** [comment]
> Did you select the correct slot? With the tests I did, I noticed that if the Yubico page was requested it was either that the NFC receiver was not receiving the response correctly, or that the key was not set, or that the slot was not correct. Note that the driver is still being designed, so it should work but it is in beta.

I have this exact problem. I installed from gitlab and whenever I use the nfc it opens up https://demo.yubico.com/yk. Even though I programmed the slots correctly.

**Comment by J-Jamet** [comment]
Seems to be the same bug as https://gitlab.com/kunzisoft/android-hardware-key-driver/-/issues/5 and https://gitlab.com/kunzisoft/android-hardware-key-driver/-/issues/4 ,  as this is a problem of the Key Driver application, I close this thread.
