### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by DanielKonopka** [Kunzisoft/KeePassDX#1510]
How hard would be to implement optional tree view, something like this?

![Screenshot_2023-02-11_15-00-57](https://user-images.githubusercontent.com/28635788/218266657-3140d57c-f753-4f10-8b3a-c8b7b6ad9f71.png)

This could (sort of) enable using KeePassDX as a secure outliner and note-taking app. Something like Orgzly, but with the added benefit of encryption, entry history and file attachments. The way hierarchy navigation works now in KeePassDX makes it hard to see the outline.

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/439
It would be nice to add this fragment for tablets, I agree, we need to study the implementation with the current code.
Please continue the discussion on the main issue.
