### ISSUE TITLE
Database appears slow to unlock.

### ISSUE THREAD

**Issue by johannesrave** [Kunzisoft/KeePassDX#1515]
**Describe the bug**

I am on a Samsung S22 Ultra, and use a keyfile for my database.
It takes about 12 seconds to unlock the database, which is too long for me. 
I'm unsure whether that is expected behaviour, but have read that for the author of the app, the unlock is nearly instantaneous? Would "Advanced Unlock" mitigate my problem, if it were available for keyfiles?

**To reproduce**

Open app.
Unlock using only preset keyfile.
"Retrieving database key" is shown for about 12 seconds.

**Expected behavior**

A very fast unlock using the keyfile.

**KeePass Database**

 - Created with: Unsure, but using it with Windows KeePassXC 2.7.4
 - Version: 2
 - Location: Remote file mirrored to Android FS via Synology Drive.
 - File provider (`content://` URI): ?
 - Size: 101kb
 - Contains attachment: No

**KeePassDX:**

 - Version: 3.5.0 beta1
 - Build: libre
 - Language: English

**Android:**

 - Device: Samsung S22 Ultra
 - Version: 13

**Additional context**

 - Browser for Autofill: Firefox Mobile
 - I tried copying the keyfile to the Downloads folder and using it from there, but same result.

**Comment by malyv** [comment]
In KeePassXC under Database security - Encryption settings is setting named Transform rounds. Similar setting is in KeePassDX. Maybe setting it to a smaller vallue will help...

**Comment by J-Jamet** [comment]
Advanced unlock will not mitigate the problem.
You have defined the security settings for your database, so you need to lower them to decrease the opening time.
I guess you took 1 second from your PC and transferred your base to phone, your phone is only less powerful.

**Comment by johannesrave** [comment]
Thanks to you two, that was indeed my problem.
