### ISSUE TITLE
Database on pCloud failed to open after several time

### ISSUE THREAD

**Issue by globdug** [Kunzisoft/KeePassDX#1517]
**Describe the bug**

I open a database stored in pCloud succesfully, but after several time, when I open the app it tries to open the database from an inexistent folder in Documents/<somenumbers> and I must reopen manually the database from pCloud.

**To Reproduce**

I don't know, I notice this behaviour only when I need to type a password... 😅

**Expected behavior**

I expect that the app open last used database from pCloud.

**KeePass Database**

 - Created with: KeePassXC in Windows (don't remember which version)
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX:**

 - Version: 3.5.0
 - Build: Free
 - Language: Italian

**Android:**

 - Device: Galaxy S20 FE 5G
 - Version: Android 13 One UI 5.1 (this happen also on One UI 5.0)

**Comment by J-Jamet** [comment]
This is not a problem of KeePassDX but of PCloud which invalidates the file from its file provider.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#file-access-revocation
Linked https://github.com/Kunzisoft/FileSync/issues/6
