### ISSUE TITLE
NFC Yubikey Could Not Read Credentials

### ISSUE THREAD

**Issue by emryshsmith** [Kunzisoft/KeePassDX#1519]
when I try to use the Yubikey challenge-response on my Android 7 using NFC I get the error message in KeePassDX "could not read credentials". I cannot use it in USB because the key is not USB-C

the Yubikey is configured correctly because I can use it to open the file on my PC.

The phone pops up a message that the key was sending a URL.

**Comment by J-Jamet** [comment]
Please fill in the bug report correctly with the version information of KeePassDX, KeyDriver and the exact procedure to reproduce the problem.
https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by TyphooN999** [comment]
I have the same problem

Keepass DB Created with: Windows KeePass 2.53.1
Version: 2
Location: GoogleDrive

KeePassDX:
    Version: 3.5.0
    Build: Free
    Language: Polish
    + KeyDriver
    
  
Android:
    Device: Galaxy A53 5G
    Version: 13
	
Yubikey 5C NFC Firmware: 5.4.3 (USB-C)

I get the error message in KeePassDX "could not read credentials"

**Comment by J-Jamet** [comment]
Update KeyDriver to 0.1.8 if it's not already the case.
https://keepassxc.org/docs/#faq-yubikey-no-extra-file KeePassDX uses the same challenge response method as KeePassXC, depending on the plugin you use with KeePass2, this will not work.

**Comment by emryshsmith** [comment]
[This](https://keepassxc.org/docs/#faq-yubikey-incompatible) seems like the more pertinent FAQ entry
