### ISSUE TITLE
Add PIN unlock

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#152]
There are devices which use custom ROMs, which break Fingerprint integration.
Always typing in the password is a pain in certain parts of the boddy, and keeping the master-pass weak is not an option.
We should have an unlock option alternative to fingerprint, so I suggest either PIN unlock or the lock which is used by Android (whichever is easier to implement).
Thank you.

**Comment by Sk1pp3r** [comment]
@J-Jamet Yes, sorry, I could not find my comment in the issues, so I decided to create a separate one =)
Do you have some kind of roadmap or task priority? I just want to now approximate ETA for this PIN to be available (is it like 1 week, 1 month... 10 years xD... ).
Thanks.

**Comment by J-Jamet** [comment]
To be honest, I do not know myself, it depends on the bugs to solve, problems encountered during development and other features to implement. I would say in 1 or 2 months. _(For now, I will refactor the search system to make it better, because the current version adds bugs every time I add a feature.)_

**Comment by R4ygen** [comment]
Hello,
i was right searching for this feature since i don't have a phone with a fingerprint sensor, and found this thread.

I know there's no ETA, so i'm just adding myself to the list of interested users about this feature to hopefully boost the priority a bit =)

**Comment by J-Jamet** [comment]
The system PIN unlock must be tested, the Android Keystore must have special security conditions to be used with this feature. Directly linked to discussion #102
We will therefore see what is the best possible integration.
