### ISSUE TITLE
Samsung Galaxy S23 - Can't Find File On Google Drive

### ISSUE THREAD

**Issue by lisat-hub** [Kunzisoft/KeePassDX#1521]
I just got my Samsung Galaxy S23. I have run into an issue attempting to use KeePaasDX with google drive. When I pick google drive, I go to My Drive and I get the following message: "No element". When I open Google Drive from the google app I can see the kdbx file that it is working file on my previously Samsung Galaxy S9+.

Steps to reproduce:

    Open the app
    Choose "Open file..."
    Choose my google account
    Choose "My Drive"
    Error Message: "No element"

**KeePass Database**

 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX:**

 - Version: 3.5.0

**Android:**

 - Device: Samsung Galaxy S23
 - Version: Android 13 / One UI 5.1

**Comment by J-Jamet** [comment]
Sorry but the problem is clearly with Google Drive, there is nothing to do if there is not even a file to upload. It may not be synced with your cloud yet or simply not the right folder.

**Comment by lisat-hub** [comment]
ok, thank you.
How does it access google drive? Is there some authorization or does it use the file of the smartphone?

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
