### ISSUE TITLE
Autofill with Capital One app

### ISSUE THREAD

**Issue by vertigo220** [Kunzisoft/KeePassDX#1523]
**Describe the bug**

**To Reproduce**

1. Launch Capital One app
2. Long-press in login field and select autofill
3. Nothing happens
4. Or, when it does show, it autofills the password into the username field

**Expected behavior**

KeePassDX should show as an option, and it should autofill the fields properly.

**KeePass Database**

 - Created with: Windows KeePass (probably) 2.51
 - Version: 2?
 - Location: Local storage
 - File provider (`content://` URI): Local storage?
 - Size: ~4.5MB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.5.0 & 3.5.0 BETA01
 - Build: Free?
 - Language: English

**Android:**

 - Device: A71 5G UW
 - Version: 13 (recently updated from 12, more below)

**Additional context**

I've been logging into the Capital One app at least once a month for at least the past few months with KeePassDX, and until now it's worked flawlessly. When trying today, though, it was very problematic. Initially, I would intermittently be given the option to use it when selecting a login field, but once I chose the database entry for Capital One and told it to fill the fields, it only filled the username field with the password and didn't fill the password field at all. After multiple attempts, it then stopped even giving me the option to use KeePassDX, and I tried the "autofill" option instead, but that didn't do anything. Since the last time it worked, I'd updated my phone (12 to 13 and "upgraded" to One UI 5), the Capital One app, and KeePassDX. I uninstalled KeePassDX and reinstalled the previous version, to see if it would start working again, but it did not, which points more to a change in either Android, One UI, or the Capital One app that's preventing KeePassDX from working properly as opposed to a change in this app that broke something. I had to resort to Keepass2Android, which fortunately I hadn't yet uninstalled, in order to be able to login.

**Comment by vertigo220** [comment]
As I mentioned, this worked before and then it suddenly didn't. I'm fairly certain since then it worked again, though earlier it didn't again. So it seems intermittent.

**Comment by J-Jamet** [comment]
Fixed in 4.0.3
