### ISSUE TITLE
Biometric unlock instructions unclear

### ISSUE THREAD

**Issue by tonydiep** [Kunzisoft/KeePassDX#1529]
**Describe the bug**

* Biometric unlock setup instructions unclear.
* UI appears to show checkbox indicating database has biometric data however when opening database UI says database does not have biometric data.
* Makes user think app has a bug. 

**Expected behavior**

App asks for fingerprint if one is required. 

**Android:**

 - Device: one plus nord n100
 - Version: 13

**Additional context**

This can be solved by ux. 
App just needs to check if it has biometric data and ask for it if required. 
Current UI makes it seem like app already has fingerprint but did not save it.

**Comment by J-Jamet** [comment]
> Biometric unlock setup instructions unclear.

https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking : Indicate specifically which part is unclear.

> UI appears to show checkbox indicating database has biometric data however when opening database UI says database does not have biometric data.

There is no checkbox that indicates that a biometric recognition is registered, so there is already a problem here.

> Makes user think app has a bug.

A UX improvement is not a bug

>  App just needs to check if it has biometric data and ask for it if required.

This is already the case, but of course you have to press the fingerprint button to start the biometric workflow.

**Comment by J-Jamet** [comment]
I'll try to make tutorial videos for every interesting feature of KeePassDX. In the meantime, I've simplified the UX a lot: 

![device-2023-07-28-132003](https://github.com/Kunzisoft/KeePassDX/assets/19224038/2fcbd219-7715-416d-a254-6f50c87d7543)

**Comment by J-Jamet** [comment]
The wiki has yet to be updated, but version 4.0.0 makes the process more intuitive.
