### ISSUE TITLE
'Database Opened' dialogue with forced 'Cancel'

### ISSUE THREAD

**Issue by 52fitz** [Kunzisoft/KeePassDX#1532]
3.5.0. libre with Yubikey & fingerprint login: database appears with a dialogue box over it. Text in box is 'Database Opened' and the only escape is to hit a  'Cancel' button.
A red warning bar then appears saying something like, 'Could not open database - action cancelled by user'.
Intermittent, but happening quite frequently.

**Comment by J-Jamet** [comment]
It should not show "Database opened", if it does, the database is open. I don't think KeePassDX is sending this string in the dialog box.
You do not indicate which version of KeyDriver is used.

**Comment by J-Jamet** [comment]
Update KeyDriver to 0.1.8

**Comment by 52fitz** [comment]
Using Key driver 0.17

Not sure how to update via Gitlab, will of course update via Play Store as soon as 0.18 is available.

**Comment by J-Jamet** [comment]
https://gitlab.com/kunzisoft/android-hardware-key-driver/-/releases

**Comment by 52fitz** [comment]
Thanks

17 Mar 2023 1:02:58 am Jérémy JAMET ***@***.***>:

**Comment by 52fitz** [comment]
Forgive my ignorance.
Am I correct to extract the 0.1.8 package files and then run 
app-debug.apk?
Thank you

**Comment by J-Jamet** [comment]
Yes

**Comment by 52fitz** [comment]
Issue solved with upgrade to 0.1.8


18 Mar 2023 7:46:20 am Jérémy JAMET ***@***.***>:
