### ISSUE TITLE
Autofill settings missing on Android 7

### ISSUE THREAD

**Issue by eddieofny** [Kunzisoft/KeePassDX#1533]
Hi, when I go to the settings in KeePass in my phone, the autofill settings just aren't there. I verified this by installing temporarily on my wife's phone (Galaxy S9 running Android 9) and checking the settings. She had the autofill options where they were supposed to be, but I do not. I checked the version number, and we were both running 3.5.0, so I'm left to assume that this is an issue with me running Android 7, although, if I have the latest KeePass release, I'm still unsure why I would be having this issue.

**KeePassDX:**

 - Version: 3.5.0
 - Build: Free
 - Language: English

**Android:**

 - Device: LG K20
 - Version: 7.0

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#why-is-the-auto-fill-not-available-for-android-devices-before-android-80
