### ISSUE TITLE
Automatic Backups files

### ISSUE THREAD

**Issue by IlluminatiWave** [Kunzisoft/KeePassDX#1538]
**Is your feature request related to a problem? Please describe.**
Prevent database corruption

**Describe the solution you'd like**
Create automated backups

**Describe alternatives you've considered**
Make the copy manually...

**Additional context**
The application itself could manage how often the file is backed up (every X days or every Y openings/changes) and how many times it is created (for example, a history of 10 copies at most).

All this would be native to the application, independent of other managers or web clients.

**Comment by J-Jamet** [comment]
This is a feature that must be done at the file layer level. As KeePassDX is an editor, this will not be implemented directly in the software, but there is nothing to prevent us from putting backup routines in FileSync.

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/FileSync/issues/8
