### ISSUE TITLE
Argon2 databases do not decrypt under Android 8

### ISSUE THREAD

**Issue by collectorgeneral** [Kunzisoft/KeePassDX#154]
OS: Lineage OS 15.1 (Android 8.1)
Device: Oneplus One (bacon)
Keepass DX version: 2.5.0 deta11-libre (from f-droid)

Description:
Recently installed Lineage OS 15. Now KPDX does not open my database anymore. Opening an old copy which was AES encrypted works no problem. However, I had changed the encryption to use  ChaCha20 + Argon2 at some point. When using it on the Lineage OS 14 (Android 7.1 based), it worked fine. However, changing to android 8.1 breaks the software.

Here is relevant logcat:
```

07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: Database can't be read
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: java.io.IOException: Hash failed with code=-1796215932
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.crypto.keyDerivation.Argon2Native.nTransformMasterKey(Native Method)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.crypto.keyDerivation.Argon2Native.transformKey(Argon2Native.java:33)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.crypto.keyDerivation.Argon2Kdf.transform(Argon2Kdf.java:102)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.PwDatabaseV4.makeFinalKey(PwDatabaseV4.java:415)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:117)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:77)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.Database.loadData(Database.java:173)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.Database.passUrisAsInputStreams(Database.java:152)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.Database.loadData(Database.java:119)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.Database.loadData(Database.java:107)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at com.kunzisoft.keepass.database.action.LoadDBRunnable.run(LoadDBRunnable.java:71)
07-21 02:20:04.403 22781 22937 E com.kunzisoft.keepass.database.action.LoadDBRunnable: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by collectorgeneral** [comment]
@J-Jamet  Creating any new database with KeepassXC does the job (change encryption to use ChaCha20 + Argon2). Here is an example:
[Passwords.zip](https://github.com/Kunzisoft/KeePassDX/files/2216923/Passwords.zip)

Extract the zip for a kdbx file. Password is: `hunter2`. The database settings are exactly the same as my main database. 512MB, 2 Thread, 1 round encryption. Now I am wondering if any of these settings are related to the issue.

**Comment by J-Jamet** [comment]
OK, I reproduced the problem and actually it comes from the memory you use for the Argon 2 key derivation function. The phone's API can not allocate so much memory at a time in androdi 8 (Maybe a new protection). I advise you to mount the number of rounds and lower the ram for the same level of encryption. (It works with 256 MiB / 3 rounds and 128 MiB / 6 rounds)
I will try on my side to see if I can work around the problem, or put another error message if I can not.

**Comment by collectorgeneral** [comment]
I was just experimenting with that myself, about you were right about the memory. I was suspecting the encryption algorithm but that was not the issue. I am just surprised as it was working fine on the previous version of android, and none of the errors indicated an out of memory exception or something like that. Or maybe android 8 somehow requires different handling of memory? Will be interesting to know.
Since the current best solution is to decrease RAM and increase rounds, I will do just that. I will let you decide when to close this issue.
