### ISSUE TITLE
Unable to modify items

### ISSUE THREAD

**Issue by jivarson** [Kunzisoft/KeePassDX#1540]
After successfully opening the kdbx from a local folder, using password +yubikey, items can't be changed nor crested.

To get it working again one has to remove the "last database" and re-add it.
I initially thought it was a glitch with the cloud-provider but having the same issue storing the file locally. 

 Does KeePassDX work with a cached copy or something?

KeePassDX 3.5.0
Android 13
Google Pixel 7
![Screenshot_20230319-172441](https://user-images.githubusercontent.com/25992469/226190346-c76d3c83-2699-44be-a326-161e2a1db451.png)
![Screenshot_20230319-172548](https://user-images.githubusercontent.com/25992469/226190364-a4f92bc8-ac22-4db1-8a3a-631c5bf4b8eb.png)

**Comment by J-Jamet** [comment]
I can't reproduce the problem, perhaps you have changed the file manager permissions.

**Comment by jivarson** [comment]
> I can't reproduce the problem, perhaps you have changed the file manager permissions.

I can no longer reproduce the problem in version 2.5.1?
