### ISSUE TITLE
Can't activate biometric unlock on Samsung S22 (Android 12)

### ISSUE THREAD

**Issue by Discostu36** [Kunzisoft/KeePassDX#1544]
**Describe the bug**

The smartphone has device lock (PIN) and biometric unlock (face) activated. But I cannot use biometric unlock in KeePassDX. It tells me "Es sind keine biometrischen oder Geräteanmeldeinformationen registriert" ("No biometric or device credentials are registered"). Clicking on the biometric unlock item leads me to the phone settings screen.

I can use biometric unlocking with the same database on another Android 12 device (Fairphone 4)

**To Reproduce**

I followed the steps described in https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

**Expected behavior**

I can use smart unlocking for the database

**KeePass Database**

 - Created with: Windows Keepass 2.x (not sure, I have the database for a long time)
 - Version: 2
 - Location: Nextcloud (synched to device)
 - File provider: `content://org.nextcloud.documents`
 - Size: 1.8 MB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.5.0
 - Build: Free
 - Language: German

**Android:**

 - Device: Samsung Galaxy S22
 - Version: 12

**Comment by J-Jamet** [comment]
If this message is displayed, you have not entered biometric information and activated a secure lock system for your device.
If you have these two conditions, it is possible that your device does not recognize the fingerprint you have registered. In this case, restart your device.
Note that some Samsung devices have a bad implementation of the Keystore for storing keys with fingerprint and do not work properly.

**Comment by Discostu36** [comment]
There is no fingerprint registered, only Face ID. But that should also work, shouldn't it? Device restart didn't change anything.

**Comment by J-Jamet** [comment]
Not necessarily, if your device determines that the face id it handles is not of sufficient security level, it will not recognize it as a valid biometric recognition for the application.

**Comment by J-Jamet** [comment]
The biometric API of your device manages these elements by itself, can you add a fingerprint and retest?

**Comment by Discostu36** [comment]
It does work with fingerprint. So I guess this is not a bug.
