### ISSUE TITLE
Auto Advanced Unlock after app in background

### ISSUE THREAD

**Issue by qoh** [Kunzisoft/KeePassDX#1545]
**Is your feature request related to a problem? Please describe.**
Currently you must always press a button and input your biometric credential every time you normally unlock the database in order to begin an Advanced Unlock session (to remember the database credential temporarily). I'm frustrated with the extra step (that you can even sometimes forget to do) as it feels unnecessary when I would prefer to just always activate Advanced Unlock any time I normally unlock the database.

**Describe the solution you'd like**
I'm suggesting an option, off by default, to activate Advanced Unlock every time you normally unlock the database; without needing to press the button to input your biometric credential first. My understanding is that any device biometric credential is equivalent to any other, so I'd at least like an explanation of what value that step adds.

**Describe alternatives you've considered**
Using a longer Advanced Unlock duration; this seems less secure.

**Additional context**
(none)

**Comment by J-Jamet** [comment]
But the workflow can be improved, currently it works very well if you lock the database by swiping the application from the Android background app list to close it. But if you go through the lock button and come back, biometry is not automatically asked again to prevent the bug of always offering the biometric unlocking. I will put a condition that resets this state if the application is put in the background, I think I had already done so it may be a bug.

**Comment by qoh** [comment]
> Currently it works very well if you lock the database by swiping the application from the Android background app list to close it

I don't know if I'm misinterpreting the existing feature as what I'm looking for, but:
- I have "Auto-open prompt" enabled
- I entirely close KeePassDX (e.g. incl. swiping it from the background app list)
- Open KeePassDX and select a recent database
- Enter my password
- Just pressing *Open* unlocks the database but doesn't seem to activate advanced unlock (no notification; if I return after the lock timeout but before the advanced unlock timeout I have to fully enter my password)
- In order to actually activate advanced unlock I have to press the fingerprint icon above "*Open the advanced unlock prompt to store credentials*" and scan my fingerprint

What I was suggesting was the ability to activate advanced unlock every time without needing to scan your fingerprint every time you manually password unlock the database-- or at least I'm wondering why I need to.

**Comment by J-Jamet** [comment]
In your case, you did not read the associated wiki correctly : https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

**Comment by qoh** [comment]
> In your case, you did not read the associated wiki correctly : https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

I didn't know that page existed, so I suppose that counts as not having read it correctly :sweat_smile: Thanks

I did read through it now though and yet I'm still not entirely sure I understand why I need to input my device biometric on first decrypt (when I'm start the period of advanced unlock being active).
> Indeed, this allows you to use biometric unlocking only if your device has previously been unlocked by a credential only known by the device user (the principle of knowledge, possession and inheritance factors is therefore respected.)
> 
> With the biometric unlocking mode, user authentication is requested from the KeyStore and is therefore less permissive than the device credential unlocking.

Is the biometric input on open (before re-open later) a requirement from Android KeyStore in order to be able to store the necessary key material, or is it KeePassDX making sure that a device owner is currently using the device?

**Comment by J-Jamet** [comment]
If you read the page then you should have understood that the biometric function is not used with the open button. Only with the biometric button. On the other hand, I know that the UX needs to be reviewed, the biometric authentication workflow needs to be rethought.

**Comment by J-Jamet** [comment]
> ... since I don't see what value I'm getting out of having my biometric checked when I just entered the full database password anyway.

This verifies that it was you who performed the action, and links the biometric recognition and password to store an encrypted version in the Keystore for this database.

I've greatly improved the graphical interface and buttons for biometrics, which will be much clearer in version 4.0.0.

**Comment by J-Jamet** [comment]
Linked to : https://github.com/Kunzisoft/KeePassDX/issues/1600
