### ISSUE TITLE
Folder count is misleading

### ISSUE THREAD

**Issue by tingreavinash** [Kunzisoft/KeePassDX#1548]
**Describe the bug**

Suppose parent folder (X) contains child folders (Y and Z) and child folder contains entries (Y > A, B, C and Z > P, Q, R). Then the parent folder (X) shows the count as 0 because its not counting entries recursively in child folders. 

**To Reproduce**

NA

**Expected behavior**
Ideally, the folder count should be (X = 6, Y = 3 and Z = 3). Current behavior is misleading because it gives the impression that folder X is empty.

Sample Visualization: [Link](https://viewer.diagrams.net/index.html?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=keepass%20count%20issue.png#R7Vxdc9o4FP01zOw%2BJONvyGMhSbvTZtMZZqfbvglb2CrGYoUI0F%2B%2Fki1%2FyNjBBGwnqV7Aur6Wpavjc49kwcCcLHcfCVgFD9iD4cDQvN3AvB0Yxmhos09u2CcG62aUGHyCvMSk54Yp%2BgWFURPWDfLgWnKkGIcUrWSji6MIulSyAULwVnab41C%2B6wr48MAwdUF4aP2GPBqIbtlabv8EkR%2Bkd9Y1cWYJUmdhWAfAw9uCybwbmBOCMU2OlrsJDHns0rgk193XnM0aRmBEm1zwY%2Fv58Z9fxo9vt6v5GC0m6Hb4%2BUrU8gTCjejwwHBCVt94jlm1LGDATU44%2F214S8cTvEQuOzEF0Zp9PUzzU%2BzI599fIVnjCPCb%2FxXNcVrjjKQOmYWHhe5D%2BQ4zTDxIrlwcYjIwP8TNI39cXRXtfya1lG482ZA4GoY2wZv4O6kYLFfsbDRbrwo3Fx28zP014X1bNJrzuaZxPJTbqaVtYKOVNEOOy0WbllY94cPhwXhY5PB01pTTosT89WORYuZZhU12NaQOGOstWoYgYqXxNkAUTlcJxreMwJgtoMuQlXR2uKaAUMFJlsajgcJwkvXBhLpnw2HsSPACFs7cOEMTOPzMAlI3EPW5G%2FIE7xGlKPKF6Sfy%2FbhhBndOKULL2v0ECYW72kdez4iEETDES0jJnrmkFwwF96TkK4rbnMlsR9iCAovZKWcBwZ5%2BVnVOMOxAcMwJfGM6B8MBPUa4oogJDbDPueMut44JQ6sHPRGX3OcLxqs0jJDSvRgpsKFYHkcWLrL%2FV1wfF74XC7c7qcSDZWZFRmaI9R0S4SON0Umjm%2FScd7d2OJ%2Fj6DXeEMHF1X6GSI%2BA%2BPC5%2BpxqzBAYAoqe5MZdHgBDBYC%2BAWD3CQCjDcUxBtGCB71WadSkj3MFiMYrvZqDJQr3iWemNp5pvOSghMxvIGTkgXNeIGrOeDhOeCrKSikAK37obmYN1NIsYekvs8wA3IUfc%2FfjhoaIK67Y7gGyeGTVIMqZVrvWbNloxFb9UG8xtTXyrCq9NTJmptOB3qrn51oRZsoaTNcPRZhuVYiwUWsarA0G%2Fogxjyt7IgPC2qmYWDHxG2Dil0wvFRO%2FEyaumg53y8SGU0HF3c%2BOzh2p9mY0VsMZjWH2Oqe13%2Fyc9u0joObR7wYBVhuSaopdFKfWB%2BghoBRVx1rBOBJfpaiqFJWlFNXvq6jMYd%2BKSh%2B%2BCkWV5%2BZru2l2ft152G6Yh%2FVz83B86QdCwL7gsMIooutCzV%2B5oYDDUfUiy31D%2F%2BHz7pbznDs7SNqbwzbr%2BMuRbLchKSaAeGulJDrOkaZSEi9QEseippTEe1IS2TYpmWJ7VBIjpSRaURJOUyVh9Tmjr1qZO5tj%2FoZ0pt5UqxyscrDKwW8gB%2Buj3pNwK%2FuT76Kk23pTdMlZ%2FAi4SkiYj1zoulVImI1sy75Err48EixNRsJNBRCMCiCYrQGhlW1jKRDql3oVEEqUYPSOhFa2r6RIqE94CgklJNi9I6GVt24qOZyKBKN%2FJLSyWKqyw8lIqBKM3SKhlXm7yg6nIsGs2uXaKRLMqqmDWr87f%2F0u%2Bxnu0S05N9WQ6eh3Jq1MHcch9t%2F9CzStFCi1bab1hbZjUVMLbe9qoU0vZUuz74U2o9VZtZpLNV1ytar2pHeqm4xWZ9VqLtUYCVVvwLtFwivZS7dDlAto%2FVrTh6L8PRfUrJRLaF7YFwrlfe41e%2BZzaf7m1Hjj%2FfHnvk2v3hmnlzbSWeV%2Fjkg6IK7KAXlQUbaIlBGhLVeU9PCgokttt0smKyoB9r5w0PurprRilQD7RYLV4qsmVsz%2FeCuhkPzfy8y7%2FwE%3D)

**KeePass Database**

 - Created with: Windows KeePassXC
 - Version: 2.4.7
 - Location: Remote file retrieved with GDrive app
 - File provider (`content://` URI): NA
 - Size: 2mb
 - Contains attachment: No

**KeePassDX:**

 - Version: [e.g. 3.5.0]
 - Build: [e.g. Free]
 - Language: [e.g. English]

**Android:**

 - Device: [e.g. Redmi note 11 pro plus 5G]
 - Version: [e.g. 12]

**Additional context**

NA

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/421
