### ISSUE TITLE
KeePassDX crashes on ChromeOS

### ISSUE THREAD

**Issue by lwbt** [Kunzisoft/KeePassDX#1549]
**Describe the bug**

KeePassDX crashes the entire ChromeOS desktop when it is run either immediately or after a short amount of time after using the app. For more info see Additional context.

**To Reproduce**

1. Install Playstore/Android on Chrome OS
2. Eventually lauch a browser window or some other window
3. Install KeePassDX
4. Launch KeePassDX
5. Wait a bit, ... see a black screen and an all windows are gone

**Expected behavior**

Being able to launch and use the app with a database without experiencing crashes

**KeePass Database**

 - Created with: Linux KeePassXC
 - Version: KDBX4?
 - Location: File shared from an Android smartphone via MTP to a Chromebook.
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`] ? I don't see anything like that, probably because it crashes before I get to the point where this information is stored or visible.
 - Size: [e.g. 150Mo] what is Mo? Millions of objects? My databases are less than 256 kb in size, often less than 10 kb.
 - Contains attachment: [e.g. Yes] Not sure what this means, but yes some of my entries are shown in KeePassXC with the paper clip icon, so they have attachments.

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23] 3.5.1
 - Build: [e.g. Free]
 - Language: [e.g. French] English

**Android:**

 - Device: [e.g. GalaxyS8] ChromeOS Playstore compatibility layer (Samsung Galaxy Chromebook, Asus Chromebook Flip C434T)
 - Version: [e.g. 8.1] 11

**Additional context**

Observed behavior:

It seems to be that running KeePassDX causes ChromeOS to crash. What does that mean? Run KeePassDX on a Chromebook through the Playstore (the compatibility layer for Android Apps on ChromeOS), continue using ChromeOS, either the App directly or using the browser, text editor and so on. After a few minutes your screen will go black, you will eventually get thrown back to the login screen and ChromeOS will tell you in a notification bubble that some apps have crashed and it can try to recover the state of the apps. In my case it brings the browser back up, but definitely not KeePassDX.

This behavior must have been introduced recently. As I don't use ChromeOS my primary OS I can't say when exactly. I had experienced situations where running KeePassDX would almost  immediately crash ChromeOS (e.g. not having I database loaded as far as I can tell), But I don't know how to exactly reproduce this behavior. Sorry that's not concise, but that is what I know for now and I don't want to let this issue go unnoticed and users avoiding to use KeePassDX for that reason.

- Tested with two Chromebooks (both x86_64 Intel architecture) with latest updates applied
- I'm on the beta channel for the app
- I resetted the Playstore cache
- Uninstalling and reinstaling solves situations of immediate crashes, but it will crash again
- KeePassDroid seems to work

**Comment by panther2** [comment]
Not to deny a possible issue, but FWIW

I am using an

outdated  Acer CB5 571 (CB5-571-39VM)
(Core i3, 64bit)

as well as a

brandnew Acer 516 GE (CBG516-1H-530D)
(Core i5, 64bit)

and KeePassDX up to and including 3.5.1 has run fine on those systems.

**Comment by J-Jamet** [comment]
Can you provide the crash report because I have nothing conclusive in the exceptions returned on the monitoring.

**Comment by J-Jamet** [comment]
I can't do anything without a crash report

**Comment by lwbt** [comment]
I'm sorry that I have been unable to provide a crash report. From what I observed and what I described above, it is hard for me and I don't have the time to investigate further how to provide the data you need.

I looked at:

- https://www.chromium.org/chromium-os/packages/crash-reporting/faq/ this gives some insight, but I still don't know what to do, it's not like just run `apport-bug`
- `chrome://crashes` but the crash I just produced is not listed there

I will use KeePassXC Flatpak on the Linux Environment instead, may be that is for the better. It's nothing against you, rather my perceived lack of documentation on the ChromeOS and Android Apps for ChromeOS (Playstore Apps) side.

You may close this bug report.
