### ISSUE TITLE
how to delete the recycle bin ?

### ISSUE THREAD

**Issue by unknowtech** [Kunzisoft/KeePassDX#155]
Bonjour, comment supprimer la corbeille, car j'ai un dossier "recycle bin" impossible a supprimer,
merci d'avance 

Hello, how to delete the recycle bin, because I have a "recycle bin" folder impossible to remove.

**Comment by J-Jamet** [comment]
Ce dossier ne peut pas être supprimé pour le moment, la refactorisation du recyclebin se fera lorsque j'aurai fait le panneau de navigation, le dossier y sera alors migré et un paramètre pour activer ou non la corbeille sera visible. Le développement de l'application est toujours en cours ;)

This folder can't be deleted at the moment, refactoring the recyclebin will be done when I'll make the navigation drawer, the folder will be migrated and a parameter to activate or not the recycle bin will be visible. The development of the application is still in progress;)

Linked to #54

**Comment by J-Jamet** [comment]
Oui, merci,  l'adresse bitcoin est [bitcoin:1DSwXCk7Sob24sNsofywNoRQw2f5Qj5t2F](bitcoin:1DSwXCk7Sob24sNsofywNoRQw2f5Qj5t2F) (les autres moyens de contribuer [https://www.kunzisoft.com/donation.html](https://www.kunzisoft.com/donation.html))

Yes, thank you, the bitcoin address is [bitcoin:1DSwXCk7Sob24sNsofywNoRQw2f5Qj5t2F](bitcoin:1DSwXCk7Sob24sNsofywNoRQw2f5Qj5t2F) (other ways to contribute [https://www.kunzisoft.com/donation.html](https://www.kunzisoft.com/donation.html))

**Comment by J-Jamet** [comment]
Si vous avez une adresse email, je peux vous donner la procédure pour débloquer les thèmes sur KeePass DX version Libre. ([F-droid](https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/))

If you have an email address, I can give you the procedure to unlock the themes on KeePass DX Libre version. ([F-droid](https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/))

**Comment by J-Jamet** [comment]
Same as #213
