### ISSUE TITLE
Deleting entries from the entry itself + from the searched results list

### ISSUE THREAD

**Issue by victorjagu** [Kunzisoft/KeePassDX#1553]
**Is your feature request related to a problem? Please describe.**
Second request :)
No problems :), just willing for an improvement.

**Describe the solution you'd like**
KeePassDX should allow deleting an entry when you are "inside" the entry.

**Describe alternatives you've considered**
1. A button (anywhere) to delete de current entry. This approach will solve also the problem of being unable to delete an entry from the searched results list.
2. If no option can be implemented inside the entry (or, for any reason, not recommended), the option to delete an entry should also be present in the searched results list.

**Additional context**
Right now, if I want to delete an entry I have to search it to know in which folder it is allocated (unless I already remember, of course) and go back to manually find the entry. Then long press it and there it is the delete option.
It should be easier to delete an entry (that's why we've the recicle bin hehe).

**Comment by J-Jamet** [comment]
Duplicate
1. Same as https://github.com/Kunzisoft/KeePassDX/issues/405
2. Same as https://github.com/Kunzisoft/KeePassDX/issues/1308
