### ISSUE TITLE
magikeyboard issue with bancaprogetto.it

### ISSUE THREAD

**Issue by e075e** [Kunzisoft/KeePassDX#1555]
**Describe the bug**

Login to my [Banca Progetto](https://www.bancaprogetto.it/privati) account does not work with magikeyboard (and copy / paste)

**To Reproduce**

1. enable MagiKeyboard
2. disable "automatic action" (do not press enter after filling a field)
3. open https://ihbnext.cedacri.it/home-banking-ng/public/login/?abi=05015&codiceProdotto=default&lang=it
4. share to KeePassDX
5. fill username and passord with the MagiKeyboard
6. remove a character from the passord field (backslash)

A good way to find if the password field will be accepted is to remove a character. If the password will be completely erased, it means the field have been filled, but the system does not recognize it after pressing Login.

**Expected behavior**

Password field submitted with MagiKeyboard are recognized as valid

**KeePassDX:**

 - Version: 3.5.1
 - Build: fdroid
 - Language: Italian

**Android:**

 - Device: Oppo CPH1931
 - Version: 10

**Additional context**

 the site does not allow copy and paste at all, even on desktop with extension [Don't Fuck With Paste](https://github.com/aaronraimist/DontFuckWithPaste)

Using KeePassXC desktop, I found that its MagiKeyboard works only with this custom autotype sequence:
`{USERNAME}{TAB}{PASSWORD}`

No difference between Firefox or Brave

**Comment by J-Jamet** [comment]
It simply seems that a javascript code on the site is preventing the characters from being entered correctly, as if the letters are being replaced on the fly. You should report the problem directly to the associated service.
