### ISSUE TITLE
Email Autofill not working on komga / Android

### ISSUE THREAD

**Issue by leberschnitzel** [Kunzisoft/KeePassDX#1556]
**Describe the bug**

When opening any Komga (https://komga.org/) website on Android, the Email field isn't recognized by KeePassDX to autofill. 

**To Reproduce**

1. You need to have an existing entry for the website in your KeePassDX Database
3. Go to a Komga site (example: https://testkomga.existiert.ch/ )
4. Click in the Email field
5. KeePassDX Autofill doesn't pop up.
6. Click in the Password field
7. KeePassDX Autofill pops up.
8. Klick on the password to fill
9. Email field stays empty, password field gets filled.

**Expected behavior**

Email field and password field get filled.

**KeePass Database**

Not relevant

**KeePassDX:**

 - Version: 3.5.1
 - Build: libre
 - Language: English

**Android:**

 - Device: Pixel 6a
 - Version: CalyxOS 4.8.0, Android Version 13

**Additional context**
Klick on Email - nothing happens:
![image](https://user-images.githubusercontent.com/39628021/233829265-d52e5aa5-6782-4bcb-9839-490630579911.png)
Klick on Password - Popup as expected
![image](https://user-images.githubusercontent.com/39628021/233829348-f977ba49-ff1c-4edf-9a0c-47e8b9aaa79a.png)
Only password is filled:
![image](https://user-images.githubusercontent.com/39628021/233829398-49371a09-1a8d-48fd-9fb7-fb219e322f92.png)

**Comment by J-Jamet** [comment]
I just checked and it works fine for me with https://demo.komga.org/

**Comment by leberschnitzel** [comment]
> I just checked and it works fine for me with https://demo.komga.org/

I just checked it there too, created a new entry:
Same as in the original post. The Password gets filled, the user doesn't. 
as the title says: this is only for android.

**Comment by leberschnitzel** [comment]
I've tested it in Chrome and Brave, I can also test other browsers if neccessary since both are chromium based. 

And yes, the username is correctly in my entry, at least my test would suggest it: 
If I try it in any other login page with the entry of a komga page, it fills user and password as I would expect it. (as example I just tried the entry on https://boardgamegeek.com/ as a random page ^^ )

**Comment by J-Jamet** [comment]
Fixed with : https://github.com/Kunzisoft/KeePassDX/issues/1665#issuecomment-1793425464
