### ISSUE TITLE
Too much "fat" .kdbx even after things are deleted

### ISSUE THREAD

**Issue by serrq** [Kunzisoft/KeePassDX#1559]
Six months ago I saved a heavy database (a zip file backup by SimpleX Chat) as attachment in KeePassDX. It was like 80 mb.

After I delete it, the KeePassDX .kbdx file has lost little weight, so I have a fat  .kbdx with no heavy attachments within. My .kdbx is now about 120mb.

How to slim down it? Does it exists a vacuum function in order to remove the unused database spaces and compress it?

**Comment by J-Jamet** [comment]
Settings - Database settings - Remove unlinked data
