### ISSUE TITLE
Copy Paste of password phrase

### ISSUE THREAD

**Issue by mat-l** [Kunzisoft/KeePassDX#156]
Hey,
In the last version I'm not able to easily copy and paste passwords in Android from Keepass to another App. Is it a bug or did I miss the feature.
Copy of username is possible but as mentioned not the password.
Best
Matl

**Comment by J-Jamet** [comment]
Hello, did you try to activate the copy of the password in the settings ? (Settings - Form filling - Copy of password)

Regards
Jérémy

Le 24 juillet 2018 21:10:42 GMT+02:00, mat-l <notifications@github.com> a écrit :
>Hey,
>In the last version I'm not able to easily copy and paste passwords in
>Android from Keepass to another App. Is it a bug or did I miss the
>feature.
>Copy of username is possible but as mentioned not the password.
>Best
>Matl
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kunzisoft/KeePassDX/issues/156

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mat-l** [comment]
Ahhh great perfect. Thanks for your help and work. 😊
