### ISSUE TITLE
Add ability to open entry instead of just selecting it for autofill

### ISSUE THREAD

**Issue by vertigo220** [Kunzisoft/KeePassDX#1560]
**Is your feature request related to a problem? Please describe.**
Sometimes, I need to fill something other than username/password, and it's currently difficult to do so. If I tap in the box and select autofill with KeePassDX, then search for the entry, all it allows me to do is to select the entry which then auto-fills those fields. In order to view the entry to see other info, e.g. notes, to be able to copy/paste something else, I need to open KeePassDX independently and search for the entry and select it that way.

**Describe the solution you'd like**
I'd like to either be able to long-press an entry when selecting it for autofill or to have a button/icon I can tap in order to open/view the entry instead of selecting it and switching out of KeePassDX and back to the other app. That way I can manually select and copy any additional info then switch back and paste it.

**Describe alternatives you've considered**
Instead of copy/pasting, once text is selected perhaps there could be an option to have KeePassDX autofill that text into the selected box in the other app, which would be more secure than copy/pasting.

**Additional context**
N/A

**Comment by J-Jamet** [comment]
Your comment implies two features: 
 - Autofill, which automatically fills in fields on a form. Here, only the username and password can be detected.
 - The clipboard, which copies any input value. This feature is not recommended because the clipboard is shared by all applications. So your request for functionality is irrelevant.

I am aware that autofill needs to be improved but it is very difficult because each form uses its own formalism.
The solution is to use the Magikeyboard. https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by J-Jamet** [comment]
The selection mode of the autofill is specifically for selecting an entry and filling the form. The register mode to save the form data into an entry.
As the case of filling and reading are processed, the autofill is correctly used.
https://developer.android.com/guide/topics/text/

Copying a field from the input to the clipboard is just technically not autofill.
And to view an entry, just don't use autofill, it's normal. 

What you want in your case is a workaround to autofill that doesn't fill in an unexpected field.

So your need is a simplified search to view an entry from a browser.
Normally the copyable data is in the custom fields and the Magikeyboard is suitable for that,  It allows very well to fill the otp codes.

Notes, as the name implies, are meant to contain notes, not form unlocking data. It is better to use custom fields for that.

If you don't want to use ithe Magikeyboard and want to activate the simple search : disable the keyboard in the device setting and do an accelerated search by doing a "share" from your browser.
