### ISSUE TITLE
Remove the spacing in OTP

### ISSUE THREAD

**Issue by orbitneon** [Kunzisoft/KeePassDX#1577]
OTP code always separated as strings of three digits
890    079
604    021

When I'm trying to remember as
89    00    79
60    40    21

It's bothering most of the time. This does not have to be a feature. Don't force us to remember it the way YOU want. Let our brains do the job of memorizing it as however we find it easy. We don't need technology for that, please spare us.

Change it to normal
8 9 0 0 7 9
6 0 4 0 2 1

**Comment by J-Jamet** [comment]
No need to use a password manager in this case, you should remember all the randomly generated passwords, your brain will be very happy. :D 
Honestly, it's a secondary issue, as the TOTP token can be easily copied to the clipboard or from the Magikeyboard, so there's no need to memorize it. Grouping by 3 or 2 digits is just arbitrary.

https://getaegis.app/ : By 3 digits
https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en&gl=US : By 3 digits

So, by non-standard convention and for overall consistency with other apps, it's 3 digits.
