### ISSUE TITLE
Isolate and highlight text, edit and paste

### ISSUE THREAD

**Issue by nollinvoyd** [Kunzisoft/KeePassDX#1579]
I needed to edit an entry.  I went to "edit" mode.  I wanted to remove some old info, and paste in the new data.  It did not respond to the typical finger press to prompt the "paste" popup option.  Am I doing something wrong?

Also, it's frustrating trying isolate and highlight text.  Any tips?

**Comment by J-Jamet** [comment]
I can't reproduce the problem, I know there are issues with Xiaomi device overlays but that's it. Can you point out all the information in the bug report. https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by nollinvoyd** [comment]
It works now.  Wish I had an explanation.  I tried it several times before I posted without success.  Sorry.
