### ISSUE TITLE
Add to Wiki - I found a way to fix Dropbox sync issues

### ISSUE THREAD

**Issue by imsys** [Kunzisoft/KeePassDX#1580]
I was using the native file manager for Android along with Dropbox, but I was always getting sync issues, but the files would just duplicate, so I would just merge them later on my desktop, an Majaro Linux using the official dropbox app.

So a few days ago I added many new passwords using KeePassXC in the Desktop, and today I couldn't find those entries, even in the "conflicted files" copies. Lucky in their web app there is a way to see the 30 days file history. I saw that my last edit on the desktop with the lost entries was on June 12, I downloaded and merged with the current version. The mobile had overwritten the file on June 15, losing the entries.

After I merged in the desktop, I tried to test it again in the mobile, but I couldn't find the entries in the mobile. I would try to force close the app, and open the database again to check and I couldn't find the entries.

So I was almost going to try a 3rd party app like DropSync, but then I found the solution.

The official app has an option "Make available offline", as soon as I clicked on it, it showed a syncing symbol, and when I opened KeePassDX, it finally was able to show my entries.

It seems their app works in a way that we have to open their app to edit documents and download files, and unless we activate this sync mechanism, it just bugs out and provides a cached file. By the way, I also use a custom file extension to add a bit of obfuscation, that may trigger Dropbox to try to create a preview icon, but I don't think this could be the reason causing the caching.

I could not find this info in the Wiki, nor anywhere else, so I thought I should share it. So maybe this could be added somewhere in the Wiki, maybe in the syncing or in some troubleshooting section.

https://help.dropbox.com/sync/access-files-offline

The file will then show the green mark when activated the "Make available offline", as bellow:
![dropbox-sync1](https://github.com/Kunzisoft/KeePassDX/assets/911254/836fee59-91c5-4006-b312-62d99f1603ed)

![dropbox-sync2](https://github.com/Kunzisoft/KeePassDX/assets/911254/ea0801aa-6aba-44d8-bfe9-8a66e5424794)

**Comment by J-Jamet** [comment]
Thanks, I've just added this doc to the wiki. ;)

**Comment by imsys** [comment]
I will just close the issue, but I will keep testing and see if this completely solve the problem or just partially, and I will report back in a few days.

**Comment by matsgf** [comment]
This saved my sanity! Thanks a million
