### ISSUE TITLE
[Question] Quick unlock and need to use yubikey

### ISSUE THREAD

**Issue by piorkov** [Kunzisoft/KeePassDX#1583]
I just started testing this program instead Keepass2Android. 
In my usage scenario, I use password and yubikey to encrypt the password database.
In keepas2andoird it is possible to unlock the program using biometrics, after first unlocking the database with a password and yubikey. Here, from what I observe, it is possible to complete the password using biometrics, but the yubikey is still required.
I do not know how it is used by others, but, for example, at home I do not always have my yubikey with me, and it would be handy to unlock the base using biometrics or phone credentials.
Is there such a possibility and I can not configure it, or maybe it is not yet implemented or there are some security reasons why there is no plan to implement it?

**Comment by schlotter** [comment]
See also #1501

**Comment by J-Jamet** [comment]
Indeed, the subject has already been discussed.
The Yubikey is only useful for validating the user's presence. If you put biometrics on the Yubikey, it completely breaks the principle, so in that case, you might as well not use Yubikey at all.
However, I'm planning to build a Yubikey emulator into the drivers in case the key is lost.

**Comment by J-Jamet** [comment]
duplicate #1501
