### ISSUE TITLE
Might Keepass self-copy the 2FA token after the autofill has been already pasted?

### ISSUE THREAD

**Issue by serrq** [Kunzisoft/KeePassDX#1588]
Often the third field is the 2FA. It is showed immediately after the two fields required to login (username + password).

So a new field is showed (if success).

Might KeepassDX self copy in copyboard the 2FA token at this point? (if present in entry)

Last step: I will paste the token in the right field on the web or in the targeted app. No spins to search the token within the KeepassDX.

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1347

Comment : https://github.com/Kunzisoft/KeePassDX/issues/553#issuecomment-912936390
