### ISSUE TITLE
fonction for always forget last database opened at start of the app

### ISSUE THREAD

**Issue by inKdahood** [Kunzisoft/KeePassDX#1590]
Hello, first big thanks for that app its really cool to use all work good for me ^^ 
But i have one request, Can you please add a fonction to always go back to start screen and forget last database opened. Actually when i close a database the app start on the last database i opened and ask for it password but i want pick a file at all time i open the app for open a database its already possible ? Or can you PLEASE add it ? 

Ps: if you dont really understand what i am saying tell me i'm french my emglish is not perfect =)

**Comment by J-Jamet** [comment]
"Settings - App settings - Remember databases location" to false

**Comment by J-Jamet** [comment]
What do you mean by "KeePassDX always succesful find it on my phone"?
I've just tested and the key file is no longer saved if this option is disabled.
Afterwards, if you have a file manager that remembers the last location visited. Just visit another location, but it has nothing to do with KeePassDX.

**Comment by J-Jamet** [comment]
You'll need to issue this feature on the Anemo project or make a pull request. Perhaps the limitation also comes directly from the System Files application in this case.
