### ISSUE TITLE
Dopbox sync : Database gets overwritten by empty file

### ISSUE THREAD

**Issue by HifeFish** [Kunzisoft/KeePassDX#1594]
**Describe the bug**

Every now and then, KeepassDX overwrites the database with an empty file. 

**To Reproduce**

I am not sure what triggers the problem. Possibly related to being flushed from memory in the background while trying to generate or save login data entered in Firefox.

**Expected behavior**

Never overwrite the database with an empty file. Possibly one could write a new file before deleting the old one in case a crash occurs while writing the database.

**KeePass Database**

 - Created with: KeepassXC 2.7.5, Ubuntu 22.04
 - Version: 4
 - Location: Remote file retrieved with Dropbox App
 - File provider (`content://` URI): `content://com.dropbox.product.android.dbapp.document_provider.documts/document/LONG ALPHANUMERIC STRING`
 - Size: 1.6MB
 - Contains attachment: No

**KeePassDX:**

 - Version: 3.5.1
 - Build: Free
 - Language: English

**Android:**

 - Device: GalaxyS8+
 - Version: 9

**Additional context**

-

**Comment by J-Jamet** [comment]
The problem comes from Dropbox, which doesn't manage file caches properly.  https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#file-manager-application

Have you contacted the Dropbox team and what did they say about this?

**Comment by J-Jamet** [comment]
There's already a cache that prevents the file stream from being written if an exception is raised. Obviously, this can only work if the Dropbox application manages its errors and raises exceptions.

**Comment by J-Jamet** [comment]
Behavior has been improved with the cache, linked to #1680
