### ISSUE TITLE
Autolock when viewing entries

### ISSUE THREAD

**Issue by Zothoz** [Kunzisoft/KeePassDX#1597]
**Describe the bug**
When I opened the database and open an entry to view the password, it always automatically locks out after few seconds and returns to the unlock screen.
I already tried different settings with screen on and everything, couldn't find a solution.
Screen on activated, Inactivity off or on, no change.
No focus should be lost, at least screen stays the same.
Couldn't find any bug reported here, so it might be something different.

Additional info:
Had both Apps installed, KeePass DX and Keepass2Android, currently disabled Keepass2Android to prevent issues. (K2A worked without this problem)
When leaving the database opened without opening an entry, it keeps it unlocked as expected.
No matter if I touch the screen for it to stay awake or not, it is locking the database when an entry is showed.
Have activated to automatically start in the search field, but even if not searching for something and choosing manually it happens.

**To Reproduce**

1. Open database
2. Open entry (revealing PW not necessary)
3. Wait 5 seconds
4. Database gets locked again

**Expected behavior**

The screen showing the entry and PW should stay open until I close it or in case the inactivity time is over.

**KeePass Database**

 - Created with: KeePass 2.42, using with KeePass XC Version 2.7.5
 - Version: 2 KDBX4.1
 - Location: Remote file retrieved with GDrive app
 - Size: 1MB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.5.1
 - Build: Free
 - Language: German

**Android:**

 - Device: GalaxyS10e
 - Version: 12

**Additional context**

**Comment by Zothoz** [comment]
Tried it with a local copy of the DB, same result.
Also checked if it might have to do with TOTP renewing time, but this is not the case.
Already lost a password today because I was in the process of creating a new entry and when entering additional details after the suggested password it was closed and locked without saving. Had to reset the PW at the website, as I did not remember the cryptic PW of course. 
I love KeePassDX for showing TOTP directly at the search results instead of having inside the entry. But with this issue I might have to use the other app meanwhile.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-did-the-app-lock-before-the-timeout-duration-has-elapsed

**Comment by J-Jamet** [comment]
You must have activated the timeout for the Magikeyboard and/or Clipboard when an entry is visible.

**Comment by Zothoz** [comment]
Thank you very much, that was the issue. I never thought that it would be a keyboard timeout in the background, did not check this setting as I was not aware that this would also affect this timeout behaviour. 
However, as in some other bug report was also written, is there an option to get a dialogue when you have created a new entry to get asked if you want to save before locking the database? This would have helped in the second issue.

**Comment by J-Jamet** [comment]
Discussion about issue 2 : https://github.com/Kunzisoft/KeePassDX/issues/1584
