### ISSUE TITLE
Auto clear clipboard

### ISSUE THREAD

**Issue by sundowndev** [Kunzisoft/KeePassDX#1599]
Thanks for the awesome app.

**Is your feature request related to a problem? Please describe.**
I used to use KeepassXC on desktop and a useful feature it has is that it clears the clipboard automatically after N seconds or after locking the database. This prevents having credentials remaining in the clipboard forever and avoid leaking it by mistake.

**Describe the solution you'd like**
As explained above, it'd be great to clear the clipboard automatically N seconds after copying the username or password. And more importantly clearing it after locking.

**Describe alternatives you've considered**
- Another idea can be to clear the clipboard right after pasting but I don't think it's doable considering Android's security mechanism.
- Making it configurable by user ?

**Additional context**
N/A

**Comment by J-Jamet** [comment]
It's already been implemented from the start, but it's the OS that manages its own clipboard history. So it may not work, but it's inadvisable to use the clipboard anyway, as it's shared between all applications.

https://github.com/Kunzisoft/KeePassDX/wiki

**Comment by sundowndev** [comment]
Oh nevermind, thanks!

**Comment by Nalci** [comment]
Currently I have to use the clipboard in some circumstances e. g. when a TOTP is requested or the Email/Password field isn't detected. There was a warning of course when turning on the copy to clipboard feature.

**Comment by Nalci** [comment]
Oh, I just read about method b on your linked page. I thought I always have to select the magic keyboard, looking for the entry and select it.

Just sharing it with the app makes it more easier to use.

I'm sorry, my bad for not reading correctly. 😅
