### ISSUE TITLE
Resets the advanced unlock expiration

### ISSUE THREAD

**Issue by reagle** [Kunzisoft/KeePassDX#1600]
I'm new to this app and have been trying to setup biometric authentication for a "quick unlock" that then times out after a period. I'm using a Pixel 6a with a fingerprint sensor in the lower third of the screen. I read the wiki and bugs associated with this feature and it took me a very long time to configure this feature.

I believe it's be easier to understand if the text in the app that says "Open the advanced unlock prompt to store credentials" said "Touch here to use alternative (e.g., fingerprint) unlock."

I wasn't sure how to "open the advanced unlock prompt." I don't even think a thumbprint should be used for that button -- I knew my sensor wasn't up there so didn't bother touching it. I kept entering my password and then going into the settings looking for an "associate credential" setting.

**Comment by J-Jamet** [comment]
Yes, you're right, the UX needs to be redone for biometric recognition. I've made a first modification for version 4.0.0 but I'll take your wording into account.

**Comment by J-Jamet** [comment]
I'll look at adding the parameter that resets the advanced unlock expiration timer when the database opens.
