### ISSUE TITLE
More copy buttons for Notes section

### ISSUE THREAD

**Issue by zinalili** [Kunzisoft/KeePassDX#1604]
I keep everything realted to my accounts in KeePass in Notes. For ease of reading purposes, I separate pieces of information by an empty line. Right now in KeePassDX it is easy to copy your username, URL or password, but when it comes to Notes, you can only copy all at once.  If it's not too much work, could you put more copy buttons for Notes? Like in the picture below
![keepassdx notes](https://github.com/Kunzisoft/KeePassDX/assets/13087157/a066e858-f931-488f-a25e-0b18ce734029)

**Comment by J-Jamet** [comment]
This will not be done for several reasons: 
 - The clipboard is shared and not recommended for sensitive information.
 - Notes are free text, so there's no easy way to separate elements within a note.
 - You'll get the behavior you're looking for only by adding information as custom field.
