### ISSUE TITLE
Delete item from search results

### ISSUE THREAD

**Issue by guckuck** [Kunzisoft/KeePassDX#1606]
**Describe the bug**

It is not possible to delete an entry from the search result list. The toolbar at the bottom screen edge does not appear. 

**To Reproduce**

1. Search for an entry
2. Long press on an entry 
3. It vibrates
4. Nothing happens 

**Expected behavior**

The toolbar should appear

**KeePassDX:**

 - Version: 3.5.1
 - Build: free
 - Language: German 

**Android:**

 - Device: Fairphone 4
 - Version: 12

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1263
Will be available in the next beta
