### ISSUE TITLE
Ajust colors of Material Design

### ISSUE THREAD

**Issue by Lyeragain** [Kunzisoft/KeePassDX#1607]
Latest version 4.0.0_ Beta01 has added material design,hopes to have a switch to turn it off，thank you

**Comment by J-Jamet** [comment]
I don't understand the request. We can't remove the Material Design, otherwise there's nothing left to display.

**Comment by Lyeragain** [comment]
ok，So I can only use version 3.5.1, there's no other meaning. I just don't like Material Design. KeepassDX is an excellent software that I have been using for a long time. (This passage was translated using translation software, which may misinterpret my words to some extent. Please forgive me)and Thank you for developing this software

**Comment by Lyeragain** [comment]
Emmm, I don't like the colors of material design. Maybe Google spends a lot of time on material design to make it better, but I don't like the colors of material design, such as in keepassDX-4.0.0_ beta01 There is a theme Classic in . The color of this theme makes me feel physically uncomfortable. I prefer a more pure color rather than the color mixed with other colors. The default theme (Forest) color of 4.0.0 is green mixed with yellow. I prefer the green of 3.5.1 because it is more pure and not mixed with other colors. I want to roast about the color of material design, I really don't like the color of material design (my native language may have a different semantic expression from English, which may make you feel confused. Please forgive me)

**Comment by J-Jamet** [comment]
The colors of the classic theme aren't really Material, I've inherited them from the colors of old KitKat devices when the UX wasn't yet colored. It's a reminder for those who still have old devices.
Maybe the forest light theme isn't right. What do you think of the colors on this page?  https://m3.material.io/components/time-pickers/overview
I can make it clearer. In this case, I went a bit overboard to link the old theme.

**Comment by Lyeragain** [comment]
I think the color on https://m3.material.io/components/time-pickers/overview is very nice, better than the Forest theme. I am currently using the 4.0.0 version of the Simple theme, and I think the blue color in Simple theme is more acceptable to me than the blue color in Classic theme.
The green and yellow colors in the Divine theme are closer to the green and yellow colors in version 3.5.1. I think you could use the Divine theme as the default theme for version 4.0.0.

**Comment by J-Jamet** [comment]
OK, I'm going to change the colors to something brighter and closer to those of the Google overview.
