### ISSUE TITLE
Missing autofill prompt for username on some website

### ISSUE THREAD

**Issue by glemco** [Kunzisoft/KeePassDX#1609]
**Describe the bug**

Autofill works quite well in Firefox for most websites, however on some (e.g. ryanair.com). Only the password is prompted and I need to type/paste the username manually.
I'm not sure if that's a problem with the browser itself, the system or KeepassDX, though..

**To Reproduce**

1. Go to www.ryanair.com
2. Click on the upper left burger menu
3. Try to login
4. See that the username field doesn't prompt anything

**Expected behavior**

Both username and password should have the prompt

**KeePass Database**

 - Created with: KeepassXC on Linux
 - Version: 2 (KDBX 4.1)
 - Location: local folder
 - File provider (`content://` URI): `content://com.android.externalstorage.documents/document/primary:Documents[...]`
 - Size: 180 kB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.5.1
 - Build: Libre (fdroid)
 - Language: Italian

**Android:**

 - Device: Oneplus 8T
 - Version: 12

**Additional context**

 - Browser for Autofill: Fennec 115.2.1

**Comment by J-Jamet** [comment]
Corrected, came from a lock bypass which has just been removed.

**Comment by glemco** [comment]
Great, thanks!
