### ISSUE TITLE
SSH clipboard syncing

### ISSUE THREAD

**Issue by includereserved** [Kunzisoft/KeePassDX#161]
I know this is kind of an obscure feature but it'd be very cool if you could setup SSH servers in the app so when you copy a password you can choose one for it to automatically to log in and copy it to the clipboard with a set command (for instance xclip)

**Comment by J-Jamet** [comment]
I am late in responding to your request, sorry for that.
KeePassDX now only uses connection to separate file managers. So I'm going to check if there are file managers that are compatible with SSH.
