### ISSUE TITLE
[v4.0.0 b01] Autofill passwords not filtered

### ISSUE THREAD

**Issue by luckkmaxx** [Kunzisoft/KeePassDX#1611]
**Describe the bug**

When you choose a user/password for autofill, it shows all passwords of all stored websites.

**Expected behavior**

Show only data asociated with the website.

**KeePassDX:**

 - Version: [e.g. 4.0.0 beta 01]
 - Build: [debug]

**Android:**

 - Device: [PocoF3 Alioth]
 - Version: [13]

**Additional context**

 - Browser for Autofill: [Bromite]

**Comment by J-Jamet** [comment]
I've just checked and there's no problem with the KeePassDX code, it only displays entries that have the domain registered in the entry.
It's surprising that this should happen to you for 4.0.0 beta1, as there's hardly been any autofill code changed since 3.5.1.

**Comment by luckkmaxx** [comment]
> it only displays entries that have the domain registered in the entry.

Yes! That is the question, I have just to notice that all suggestions are from the same main domain. But before 4.0, it only suggests passwords related to exactly subdomain.domain.org

**Comment by J-Jamet** [comment]
App settings - Search - Subdomain search is well activated?

**Comment by luckkmaxx** [comment]
> App settings - Search - Subdomain search is well activated?

wow! 😅 I didn noticed that I had to set subdomain search in current stable version. Im sorry! Thanks for your time. And btw, the new version looks beautiful!

**Comment by luckkmaxx** [comment]
Solved
