### ISSUE TITLE
beta to fdroid?

### ISSUE THREAD

**Issue by zer0fl0w** [Kunzisoft/KeePassDX#1614]
hello jeremy,

will the current beta be pushed to fdroid also?

as of now i do not see it at https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kunzisoft.keepass.libre.yml

i would like to use md3 with follow system but 
it will on only work with playstore-unlocker with github-version.

but i donated not via playstore, only directly to you. so i can use only the fdroid version to unlock the colorthemes with the tappingtrick.

br.

**Comment by J-Jamet** [comment]
> will the current beta be pushed to fdroid also?

Unfortunately not, I've been criticized many times for pushing the beta version on F-Droid, so now there's only the compilation of stable versions.

I'm aware that for donors this isn't very practical and I'm sorry about that, thank you for your support. Just be patient, it won't be long now.

**Comment by zer0fl0w** [comment]
thanks for your quick reply and your continous support.
