### ISSUE TITLE
No option to copy password

### ISSUE THREAD

**Issue by Dogway** [Kunzisoft/KeePassDX#1615]
**Describe the bug**

Can't copy the password as it's missing the copy icon like it does with login, address, etc

**To Reproduce**

1. Open an entry in the database
2. Copy icon is missing for the password and instead an eye icon is present

**Expected behavior**

Expected to copy the password (temporarily as KeePassXC does) via some way in KeePassDX.

**KeePass Database**

 - Created with: KeePassXC 2.7.4
 - Location: local
 - Size: 332Kb
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.5.1 GPlay

**Android:**

 - Device: Xperia 10 IV, Galaxy Tab S7 FE
 - Version: 13

**Additional context**

Many times only the password is asked or required. Or maybe you need to try another login with the same password. Also some APPs don't allow for autofilling since they use their own keyboard and the only way to fill the entries is via copy-paste.

**Comment by J-Jamet** [comment]
This feature has not been changed. "Settings - Form filling - Clipboard trust"
You disabled the feature on the first attempt.
https://github.com/Kunzisoft/KeePassDX/wiki/Clipboard
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1410
