### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#1624]
Hi, thank for the wonderful app, can you give us a tutorial on how to build it, the best thing you can do is to provide a GitHub actions script for testing so we can see what is needed to build the app, I personally love to use GitHub actions to build apps that I use regularly, so I don't rely on the developer.

Thank you for your time and you have all my respect.

**Comment by J-Jamet** [comment]
https://developer.android.com/studio/run
;)
