### ISSUE TITLE
Support for Amaze

### ISSUE THREAD

**Issue by NastyFlytrap** [Kunzisoft/KeePassDX#1626]
**Is your feature request related to a problem? Please describe.**
I just wanna use Amaze as my file explorer but keepassDX doesnt want to work with it

**Describe the solution you'd like**
For keepassDX to be able to use Amaze as its file manager

**Describe alternatives you've considered**
Material files is alright but Amaze is just cooler. Its the daniel and cooler daniel all over again

**Additional context**
It says it doesnt support requests or calls

**Comment by J-Jamet** [comment]
I think what you mean is that Amaze doesn't even support the standard intent for reading and writing files. 
https://developer.android.com/guide/topics/providers/content-providers
Ask this application to become at least compatible with ACTION_OPEN_DOCUMENT
