### ISSUE TITLE
Database opens slower on KeePassDX than on KeePassXC

### ISSUE THREAD

**Issue by PhamHoangLong** [Kunzisoft/KeePassDX#1628]
Hello,

When using Keepassdx creating a database using kdbx 3.1, it very fast and smooth... But when i using kdbx 4.1 (created from keepassxc), your keepassdx working  extremely slow, it need a lot of time to save database and open database. I love your app and want to support you by purchase the pro version app, but this stopped me. Hope you will fix it soon. I'm so tired because of this.
Thank you.

I'm using Samsung Galaxy A8 2018 (Android 9)
Using KDBX 4.1 created by Keepassxc
Using Latest version of Keepassdx from Google Play.

**Comment by J-Jamet** [comment]
It's not a code problem to be solved. You've simply set the KDF too high.
Certainly, if you decrypt a database for several seconds on a powerful PC, and then open it on an old portable device, it's going to take a lot longer to open. The format of the database in .kdbx3 or .kdbx4 only defines the functionalities used.
The solution here is to open your database with KeePassXC, lower the time in Database Settings - Security - Encryption Settings.

**Comment by J-Jamet** [comment]
I've just added the question to the wiki https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-does-my-database-open-slower-on-my-phone-with-keepassdx-than-on-my-pc

**Comment by PhamHoangLong** [comment]
It also extremely slow when saving database, this problem because decryption time ?

**Comment by J-Jamet** [comment]
Yes it's the same thing.
