### ISSUE TITLE
Pressing back does not close the application

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1629]
**Describe the bug**

Pressing back does not close the application or database.

**KeePassDX:**

 - Version: 4.0.0

Following migration to API 33, the backspace button no longer locks the database, even if the setting is activated.

**Comment by rogers1106** [comment]
It does slso not close the app, when the database should not be locked via back-button.
After multiple back I get "advancedunlockmanager not initialized".

**Comment by J-Jamet** [comment]
The new API 33 back system no longer behaves in the same way. I'll try to solve it as soon as possible.
