### ISSUE TITLE
How is there a premium version of software built on gpl3?

### ISSUE THREAD

**Issue by RustoMCSpit** [Kunzisoft/KeePassDX#1633]
sorry a bit confused

**Comment by J-Jamet** [comment]
It's simple: there's no premium version.
Question on wiki page : https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#what-is-keepassdx-pro--contributor-pro

**Comment by J-Jamet** [comment]
The Pro (not premium) version is available to encourage donations of development time. This does not affect any of the application's functionalities, only its visual elements.

**Comment by RustoMCSpit** [comment]
> It's simple: there's no premium version. Question on wiki page : https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#what-is-keepassdx-pro--contributor-pro

so is the source code for the features in the app and can i just fork it?

**Comment by J-Jamet** [comment]
Yes, you can, but as I said, the aim is to help development, it motivates me to deal with anomalies and create new features. You don't even need to make a fork, you can just compile it directly.

**Comment by RustoMCSpit** [comment]
> Yes, you can, but as I said, the aim is to help development, it motivates me to deal with anomalies and create new features. You don't even need to make a fork, you can just compile it directly.

well you shouldnt have to get it through the google store as if you donate directly yoy wont get accesd to the features, if you do a direct donation you shohkd get a code to put into the app.

contribution shouldnt be put under 'contact'

**Comment by J-Jamet** [comment]
Code to be inserted into the application would require a server and web access, which I don't want.
I'm going to improve the website to change the contribution link (which can be translation, pull request or other), why shouldn't it be in contact?

**Comment by RustoMCSpit** [comment]
> Code to be inserted into the application would require a server and web access, which I don't want. I'm going to improve the website to change the contribution link (which can be translation, pull request or other), why shouldn't it be in contact?

donation simply isnt contacting, it should be its own thing in special font
