### ISSUE TITLE
Advanced Unlock Manager not initialized 

### ISSUE THREAD

**Issue by AdriandeLima** [Kunzisoft/KeePassDX#1634]
**Describe the bug**
I updated to the latest playstore update (the material 3 one),and its pretty cool. I am running into an issue now though, that whenever I view an entry, and then back out to the main group list, I get a toast notification saying "Advanced unlock Manager not initialized" I don't know what this is, whether it's a big or a setting I've changed (that I don't know which),but it's quite annoying.

**To Reproduce**
View a database entry
Back out to main group view
Toast appears at the bottom of the screen, covering some elements temporarily 

**Expected behavior**

I expect there to be no toast notification.

**KeePass Database**

 - Created with:  Windows KeePass 2.42
 - Version: 2
 - Location: Remote file retrieved with GDrive app
 - File provider content://com.google.android.apps.docs.storage/document/acc=1;doc=encoded=oNYgDBDgJVHQCHL_TQ16m_sHN8ckwe7xHiSX19D6ysc0E5c9feK-tXfigmUWmFM=
 - Size: 435kb
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4
 - Build: Free
 - Language: English 

**Android:**

 - Device: Pixel 6
 - Version: 13

**Additional context**

It also happens when trying to back out of the database/lock it by pressing the back arrow/back gesture.

**Comment by J-Jamet** [comment]
Thank you, I'll try to fix this.

**Comment by J-Jamet** [comment]
I can't reproduce the problem, can you tell me if it happens every time?

**Comment by J-Jamet** [comment]
I think the problem will be solved once the back is solved too. It happens because the back brings you back to the credentials screen.
