### ISSUE TITLE
Screen does not respond/react anyhow,

### ISSUE THREAD

**Issue by sobeit2020** [Kunzisoft/KeePassDX#1636]
**Describe the bug**

When app is turned on, on screen buttons does not respond anyhow. 
They are frozen, and does not work. Turning on/off the app doenst work. App is out of order. 

I cannot write, use the fingerprint login. 

Restart of the phone is necessary. 

Then app works, but ultimately i need to count it will be down again.
This bug is active since a year at least.

**KeePassDX:**
 - Version: 3.5.1

**Android:**
 - Device: Pixel 6
 - Version: Android 13 >> Graphene

**Comment by J-Jamet** [comment]
Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/1367

KeePassDX is protected against TapJacking : https://developer.android.com/topic/security/risks/tapjacking

You've just added another application that sits on top of the others and tries to capture click events, so you need to disable the application that's doing the overlaying.

You can do this from your device settings in "Display over other apps".

**Comment by J-Jamet** [comment]
I've just updated the wiki : I've just updated the wiki
