### ISSUE TITLE
Cannot unlock themes in the beta.

### ISSUE THREAD

**Issue by ThoriumTextile** [Kunzisoft/KeePassDX#1637]
**Describe the bug**
As title says, I cannot utilize the e-mail procedure to unlock additional themes

**To Reproduce**

1. Go to Appearance 
2. Follow e-mail steps
3. Go back to main screen and return
4. Get warning about needing to purchase the pro version

**Expected behavior**
Additional themes get unlocked

**KeePass Database**

 - Created with: KeepassXC, version unknown.
 - Version: n/a
 - Location: n/a
 - File provider n/a

**KeePassDX:**

 - Version: [4.0.1 beta]
 - Build: [Libre]
 - Language: [English]

**Android:**

 - Device: [Pixel 6]
 - Version: [Android 13]

**Comment by J-Jamet** [comment]
Beta versions are not available on F-Droid, so you'll have to wait for stable version 4.0.X to be compiled by the server.
https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kunzisoft.keepass.libre.yml

**Comment by ThoriumTextile** [comment]
> Beta versions are not available on F-Droid, so you'll have to wait for stable version 4.0.X to be compiled by the server. https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/ https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kunzisoft.keepass.libre.yml

This still doesn't work even with the 4.0 release out on F-Droid.
