### ISSUE TITLE
"KeePassDX keeps stopping" when expecting it's AutoType Dialog to pop-up

### ISSUE THREAD

**Issue by alizair** [Kunzisoft/KeePassDX#1638]
**Describe the bug**

"KeePassDX keeps stopping" when expecting it's AutoType Dialog to pop-up on an app / website configured for autofill _(might be because I am using GrapheneOS on a Pixel 6)_. :

<img src="https://github.com/Kunzisoft/KeePassDX/assets/127934267/89cde307-32e7-47a7-9814-faf3690087d5" width="200"/>

[Android 13 Error.txt](https://github.com/Kunzisoft/KeePassDX/files/12576388/Android.13.Error.txt)

**Note: This occurs only if the database is locked, so if it is unlocked everything works fine and I can see the pop-up.**

**To Reproduce**

1. Go to any app / website of which the url has been added in keepassdx for auto-fill.
2. Click on the password field and wait for the dialog to pop-up. Instead of that dialog popping, "KeePassDX keeps stopping" error shows up.

**KeePass Database**

 - Created with: KeePassDX 4.0.1
 - Version: 4
 - Location: Created Locally
 - Size: Around 36MB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4.0.1
 - Build: Free
 - Language: English

**Android:**

 - Device: Pixel 6 **(GrapheneOS)**
 - Version: 13

**Comment by mjenny** [comment]
It's not related to GrapheneOS. Same here with Pixel 6 Pro on Stock Android.

**Comment by J-Jamet** [comment]
It's strange, I don't see any problems with the emulator and I can't reproduce the problem. I don't know where it's coming from exactly.

**Comment by mjenny** [comment]
I sent you the crash report via the crash screen. Was this of any use?

**Comment by alizair** [comment]
Reproducing the error:

https://github.com/Kunzisoft/KeePassDX/assets/127934267/d61e0504-3496-4e5b-a606-62faaeaf60be

**Comment by J-Jamet** [comment]
Can you tell me if this build works? 
[KeePassDX-4.0.2.zip](https://github.com/Kunzisoft/KeePassDX/files/12579622/KeePassDX-4.0.2.zip)

**Comment by J-Jamet** [comment]
> I sent you the crash report via the crash screen. Was this of any use?

Yes it's very useful, the problem seems to come from the new fillResponse authentication method, which is buggy on several devices but not on emulators, and the deprecated method seems to work, it's really weird.

**Comment by alizair** [comment]
> Can you tell me if this build works? [KeePassDX-4.0.2.zip](https://github.com/Kunzisoft/KeePassDX/files/12579622/KeePassDX-4.0.2.zip)

That works, thank you so much for resolving the issue promptly. We always appreciate FOSS developers for their contribution to the community!

**Comment by J-Jamet** [comment]
Above all, thanks to users like you who report this kind of bug. Here, the problem is clearly in the source code of the autofill service for certain API 33 devices. The worst thing is that we're forced to migrate methods that are deprecated, but as we can see, it doesn't even work properly.

Frankly, if that's the case, why bother updating deprecated functions? I have to say, I'm a bit annoyed...

I'll create a clean tag and build just for this problem. Thank you guys.
