### ISSUE TITLE
Creation of some documents for KeePassDX.

### ISSUE THREAD

**Issue by HarryHeights** [Kunzisoft/KeePassDX#164]
Hello, I'm Harry and creating some copywriting documents for projects that need them is what I do on the open-source community. 
The activities ranges from proofreading an existing document, modifying a document or creating new ones. For your project however, I'd be creating new ones. A privacy policy document and About Us.

The privacy policy document will cover issues of information collection and use when people use your app.

The About Us is like a documented ad. Talks about the project, and benefits users will enjoy when the software is used. This would greatly affect increase in utilization.

I'll love to know if you are interested in this. If yes please reply so I can get to work.

Thanks

**Comment by J-Jamet** [comment]
I do not quite understand what you want to do and the purpose of these new copyright document, if for example a user attacks me in court, I can come back to you to resolve conflicts? For me the current documents are sufficient, I'm wrong?

**Comment by J-Jamet** [comment]
https://www.copyrightservice.co.uk/copyright/miss_spellings

Here I'm doing this app under GPL3 copyleft, which is clearly stated everywhere. If it is to inform the user, it is planned to make slides at the beginning of application with this kind of library : https://github.com/apl-devs/AppIntro

So I would be happy that you help me to do these slides to indicate that no information is retrieved. (But if it's just to make money on Steemit, I absolutely do not agree.)

**Comment by HarryHeights** [comment]
Oh okay

**Comment by J-Jamet** [comment]
I have nothing against Utopian.io on Steemit, on the contrary, it can evolve the open source projects but it is necessary to contribute according to the needs of the projects and not only to recover steem. Here, you closed the issue without even trying to understand the library and without proposing alternative solutions to inform the user, if you are not a developer. It indicates that you only do it for the money ... It's really bad ...

**Comment by HarryHeights** [comment]
Well I closed the issue not necessarily to prove your statement right. I'm a content creator and that's like my real job. If I made a proposal to work on your project, it's because I found need to. The end result is a win win case.

**Comment by HarryHeights** [comment]
Sorry if I've made bad first impressions

**Comment by J-Jamet** [comment]
It's not a big deal, and you're right in a sense it's a win win case, maybe I'm a bit too tough. Do not be discouraged, I just say what I think. After I advise you to expand your skills so that the service you offer is essential and that we come to get you.

**Comment by HarryHeights** [comment]
Yea alright. So the air has been cleared. I'll definitely improve on my skills not because you said so, it's necessary. The world is evolving on daily basis and I don't want to get stuck in same pattern of doing things and get overrun by latest trends. Have a very nice day Jamet.

**Comment by J-Jamet** [comment]
Have a very nice day too. And good luck for the future! ;)
