### ISSUE TITLE
Update Biometric wiki

### ISSUE THREAD

**Issue by Benno-K** [Kunzisoft/KeePassDX#1643]
On my Samsung Note9 running Android 10
4.0.2 was installed by playstore automatic update. After that unlocking per fingerprint was no longer possible. I tried to re-enable it, but did not manage it. I cannot even find a way to invoke fingerprinting. Clicking on the central icon ( which was showimg a fingerprint in previous versions but is now changed ) only invokes the settings. 
Experienced this issue with 4.0.2 and 4.0.0 and found 3.5.1 to be working

**Comment by J-Jamet** [comment]
The biometric unlock button is now at bottom left. The wiki simply needs to be updated.

**Comment by Benno-K** [comment]
Well, I"ve spotted it there before, but I got some error message from Android when I tried. But due to uninstalling 4.0.2 then installing 3.5.1 and after reading this post uninstalling 3.5.1 and then again installing 4.0.2 it works now. Whatever caused my troubles has been cured by this procedure.

**Comment by Oliveinparis** [comment]
The wiki was updated, sorry for ping, but @J-Jamet this issue should be closed.
