### ISSUE TITLE
F-Droid build of 4.x.x failed

### ISSUE THREAD

**Issue by foss-** [Kunzisoft/KeePassDX#1644]
Current version on F-Droid is 3.5.1 (119).

The build for 4.0.2 (125) however failed as per https://monitor.f-droid.org/builds/log/com.kunzisoft.keepass.libre/125#site-footer

Looking forward to the new version on F-Droid.

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/1333

**Comment by foss-** [comment]
Would it make sense to reach out to F-Droid and ask about this? Maybe they encountered a similar situation with another app and have ideas how to tackle the issue?

**Comment by zer0fl0w** [comment]
after reading #1333, it means the fdroid-builds are suspended for now? -.-

**Comment by J-Jamet** [comment]
At the moment, the only possible solution would be to rewrite the entire history of the repo, but I don't really know what the side effects will be (loss of tags, links to commits etc) so I'll have to test with other cloned repos. It's not a trivial operation.

**Comment by zer0fl0w** [comment]
hopefully it works out in the end.

**Comment by J-Jamet** [comment]
At the moment I don't even have a procedure to solve the problem locally. No matter how many times I replace the git blob, the problem reappears, so I'd have to do a rebase, but I have no idea what the hashes of the commits affected by this problem are.

**Comment by zer0fl0w** [comment]
what a nightmare.

**Comment by shuvashish76** [comment]
Now available on Izzy repo https://apt.izzysoft.de/fdroid/index/apk/com.kunzisoft.keepass.free for F-Droid users.
Users can temporarily switch to latest `free` version by simply export-importing [App properties](https://github.com/Kunzisoft/KeePassDX/wiki/Import-and-Export#app-properties).

**Comment by J-Jamet** [comment]
I just added version 4.0.3 to github with the compilation of both versions (Free and Libre). You will normally be able to use [Obtainium](https://github.com/ImranR98/Obtainium). I took the opportunity to update the wiki.

**Comment by zer0fl0w** [comment]
thanks a lot!

**Comment by danyael031** [comment]
There is a [Merge Request](https://gitlab.com/fdroid/fdroid-bootstrap-buildserver/-/merge_requests/29) for fdroid-bootstrap-buildserver titled "gitconfig: set some not critical fsck check to warn", which includes changes for the `duplicateEntries` error. Seems that it could solve the build issue.

**Comment by shuvashish76** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-two-keepassdx-versions-on-izzydroid

**Comment by shuvashish76** [comment]
Neither of them contain _proprietary bits_. See [FAQ](https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-a-libre-and-free-version) for difference.
F-Droid will ofc get the updates when fixed/ready.

**Comment by rigrig** [comment]
That FAQ states that "The Libre version is the version provided to have no proprietary code", so it makes sense to assume the Free version _does_ contain proprietary code.

**Comment by J-Jamet** [comment]
The Free version is intended for proprietary stores and may contain code that is not standardized or promotes non-standardized algorithms (e.g. Steam's TOTP, which is not standardized). There is currently no proprietary code, but this version may contain some.

The Libre version is guaranteed to contain only freely licensed libraries and algorithms.

**Comment by shuvashish76** [comment]
For Izzy users - their scanner didn't suggest any such results for now, [Anti-Features](https://f-droid.org/en/docs/Anti-Features/#NonFreeNet) will be added when necessary.

**Comment by linsui** [comment]
4.0.5 is available in F-Droid.

**Comment by vdbhb59** [comment]
4.0.5 just got successfully built on F-Droid.

**Comment by J-Jamet** [comment]
Nice thank you all.
