### ISSUE TITLE
Please make "enter" when using magikeyboard is optional

### ISSUE THREAD

**Issue by PhamHoangLong** [Kunzisoft/KeePassDX#1646]
Hello,

When using magikeyboard to enter username or password, it's always "enter" after taped button. This so annoying, because some website will cause problems. Please make "enter" feature is optional, i don't want to use it, i want every time i tapping button, it only type data, do not do something else.

Thank you and sorry for my bad english.

**Comment by J-Jamet** [comment]
It's already the case with Settings → Form filling → Magikeyboard settings → Auto key action

https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard
