### ISSUE TITLE
Editing an entry within the KeepassDX app

### ISSUE THREAD

**Issue by nollinvoyd** [Kunzisoft/KeePassDX#1647]
Is this possible? I can't find a way to do

**Comment by rafaelazvdo** [comment]
Yes, just tap on the road and hold, then go to the 3 dots menu and edit, or enter the credential and tap the pencil icon to edit.

**Comment by nollinvoyd** [comment]
> Yes, just tap on the road and hold

Sorry, I don't know what the "road" is

**Comment by rafaelazvdo** [comment]
> > Yes, just tap on the road and hold
> 
> Sorry, I don't know what the "road" is
> 
> 

Sorry, I corrected it now.

**Comment by nollinvoyd** [comment]
Here's what mine looks like

![KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/20844322/851abe2f-93dc-4ec5-9afe-b0cc7227450c)

Is this the version we're talking about/

![KeePassDX3](https://github.com/Kunzisoft/KeePassDX/assets/20844322/2e6ee673-d82e-47ec-9c19-56fee2ea8201)

**Comment by J-Jamet** [comment]
Click the pen icon (writing mode) before opening the database.

**Comment by nollinvoyd** [comment]
@J-Jamet

ok, I see now.  Is there some Faq's page, or manual, that I could have consulted with a detailed explanation on this subject, instead of coming here for help.  A google search didn't result in any answers.

I think KeePassDX is great, but may I offer an observation? 

It's so simple when you finally discover how, but it is not obvious, particularly for an inexperienced dummy like me.  I kept searching for that pencil, and it was right there the whole time.  I think there are those of us that may not recognize it as a pencil, and what that image represents?

![Screenshot_20230920-075134_KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/20844322/7cb0a369-2ffd-498c-84f5-44ed5b021468)

I dunno, instead, maybe the word "Edit" with a line thru it, or "Enable Edit"?.  Something along those lines.

Also, when I open the app, my Biometrics prompt appears.  There is no way to engage the Biometrics,  and also select the pencil, so perhaps most users assume the option is within the database.

> before opening the database.

That's what flipped the light switch.  I finally decoded the explanations.  This is just a random thought, but, just as you have the option to enable screenshots, why not have something that in the settings to "allow editing", or something like that.  If there are security concerns related to this, then have it disable itself when exiting the app.

Just suggestions.  Thanks for listening.

**Comment by shuvashish76** [comment]
Here : https://github.com/Kunzisoft/KeePassDX/wiki

**Comment by J-Jamet** [comment]
Wiki : https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#the-edit-button-is-not-present-why-cant-i-edit-an-entry

The pencil icon is already part of the burger menu (along with the 3 dots). On Android, it depends on the size of your screen. If there's enough room, it uses the icon, otherwise it uses the burger menu. Try it in landscape mode.

**Comment by mystinen** [comment]
Totally missed the icon before _opening_ the database, without which no edit option appears for entries, and had to Google this... 

Just to add a voice to perhaps considering one of the suggestions to make this better somehow. Thanks.
