### ISSUE TITLE
App crash on Android 13

### ISSUE THREAD

**Issue by thelazyoxymoron** [Kunzisoft/KeePassDX#1648]
**Describe the bug**

App crashes when you go to an entry via search box, on Android 13.

**To Reproduce**

1. Click on Search icon at the top.
2. Type any relevant entry's name.
3. Click on any of the entries.
4. The item opens and immediately the app crashes.

**Expected behavior**

App should not crash.

**KeePass Database**

 - Created with: MacOS KeePassXC
 - Version: 2.7.6
 - Location: Local file synced with Mac via Syncthing
 - File provider (`content://` URI): Not sure how to get this. The file is in my internal storage.
 - Size: 1.1MB
 - Contains attachment: No

**KeePassDX:**

 - Version: 3.5.1
 - Build: Free, via Fdroid
 - Language: English

**Android:**

 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**

System: Android 13

**Comment by v2302** [comment]
Might be related to the bug that caused crashes in Android 13 (#1589), which have been fixed since v4.0.0.

Try to download the latest version from the [Github Releases ](https://github.com/Kunzisoft/KeePassDX/releases)(v4.0.2 as of writing) and see if the issue still occurs.

**Comment by thelazyoxymoron** [comment]
Sorry for the late reply. Can confirm that the latest version works. Thanks!
