### ISSUE TITLE
Optimization: do not recalculate the hash on every save

### ISSUE THREAD

**Issue by life00** [Kunzisoft/KeePassDX#1650]
**Is your feature request related to a problem? Please describe.**
Every time when the database is requested to be saved I have an impression that the password hash is recalculated using the configured KDF. I personally have a hardened KDF config and it takes some *noticeable* amount of time to calculate the hash. The problem especially become noticeable when I do modifications to my database, and I am forced to wait after modifying every entry for this unnecessary computation.

**Describe the solution you'd like**
Instead of saving the password to memory I suggest to save the hash that was computed when opening the database (and modifying KDF settings).

**Describe alternatives you've considered**
I do significant modifications while watching something because it takes sooo damn long...

**Additional context**
I do not actually know what is happening in the background, but I believe my guess is correct.

Also if this implementation is intentional then why?  This does not provide any additional security benefits. Only results in inconvenience and unnecessary resource usage.

**Comment by J-Jamet** [comment]
We're not in a client-server context, we need to encrypt all the content, it's not just a hash check. But if you have a technical solution to further improve speed (in addition to the C code for KDF), don't hesitate to make a pull request.

**Comment by life00** [comment]
I am not aware of how internally the format works, and I do not really have time for it. I just wanted to point out my theory. 

If it is not possible to optimize it in the previously mentioned way then the issue is closed.
