### ISSUE TITLE
Autofill quickly disappears

### ISSUE THREAD

**Issue by TippyLion28** [Kunzisoft/KeePassDX#1653]
**Describe the bug**

When tapping the username field of a login form, the Autofill popup appears and then rapidly disappears. Or it only allows me to fill the password field. 

Autofill has always been problematic for me in Kiwi Browser so I thought I'd test it in one of the "native" Autofill browsers to see if I get the same results. While it's more reliable in Fennec than Kiwi, there is still an outstanding issue. 

**To Reproduce**

1. Go to a login page in a browser 
2. Tap the username field
3. The Autofill popup appears briefly then disappears 

**Expected behavior**

I expect Autofill popups to display consistently and reliably

**KeePass Database**

 - Created with: KeepassDX
 - Version: 2
 - Location: Local File
 - File provider (`content://` URI): content://com.android.externalstorage.documents/document/primary:Keepass/keepass.kdbx
 - Size: 1.36MB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.5.1
 - Build: Free
 - Language: English 

**Android:**

 - Device: Poco F1 (beryllium) 
 - Version: LineageOS 20 (Android 13)

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by sergeypdev** [comment]
For me it also flashes a few times before disappearing completely. Android 12 Lineage OS

**Comment by J-Jamet** [comment]
I tried to solve the problem with a lock, but it causes other problems. 
 As the problem comes from the browsers, I can't really solve it from KeePassDX.

**Comment by J-Jamet** [comment]
I've just retested and the problem no longer seems to exist.
