### ISSUE TITLE
How to use magikeyboard ?

### ISSUE THREAD

**Issue by i-panov** [Kunzisoft/KeePassDX#1655]
**Describe the bug**

Autofill does not work for any application or site on my device.  Magikeyboard also doesn't work.

**To Reproduce**

To make it easier to show you, I recorded a video from the screen for you.  For example, I took the Booking application and website.  But I tried it on others too.

https://disk.yandex.ru/i/xdWjdXGuL-M9lA

**Expected behavior**

**KeePass Database**

 - Created with: KeePassDX
 - Version: [e.g. 2]
 - Location: local file
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: no

**KeePassDX:**

 - Version: 4.0.2
 - Build: free
 - Language: Russian

**Android:**

 - Device: Google Pixel 6
 - Version: 13

**Additional context**

 - Browser for Autofill: Chrome 117.0.5938.60

**Comment by J-Jamet** [comment]
The Booking app simply didn't want the autofill to appear. For autofill in other compatible applications, check that the autofill service is enabled by following the wiki.

In any case, the magikeyboard works. But of course you have to use it correctly, clicking 50 times on a notification that's not meant to be clicked won't do anything - that's normal.
You need to change the keyboard by clicking on the little keyboard button at the bottom right of your screen.

Wiki : https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

**Comment by i-panov** [comment]
@J-Jamet Ahh... I didn’t understand how to use it at first. Thanks, it works! Tell me, are there any plans to integrate with cloud storages (for example, DropBox, GoogleDrive, YandexDisk) or at least WebDav? And also, I would really like the favicons to be automatically loaded from websites, is this planned?

**Comment by shuvashish76** [comment]
> Tell me, are there any plans to integrate with cloud storages (for example, DropBox, GoogleDrive, YandexDisk) or at least WebDav?

KPDX is just an offline `.kdbx` file editor nothing more than that. See [Wiki](https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync) for more info.

> And also, I would really like the favicons to be automatically loaded from websites, is this planned?

See #1449, there is a good chance of merger of this PR as the main principle of this project is to offer fully offline experience but nothing decided yet. There are also other possibilities as mentioned in #1651

Please use separate issues/discussions for specific questions.

**Comment by J-Jamet** [comment]
Cloud storage : https://github.com/Kunzisoft/KeePassDX/issues/342 https://github.com/Kunzisoft/FileSync
Icons : https://github.com/Kunzisoft/KeePassDX/pull/1449 https://github.com/Kunzisoft/KeePassDX/pull/1146
