### ISSUE TITLE
Autoill incorrect field 

### ISSUE THREAD

**Issue by notNSANE** [Kunzisoft/KeePassDX#1658]
**Describe the bug**

If I copy paste the pass manually, it works, automatically it doesn't, it's incorrect.

**To Reproduce**

1. Go to https://servicioscorp.anses.gob.ar/clavelogon/menu.aspx
2. Use the automated featured that appears when you click the first text box
3. Select the username and try to login

**Expected behavior**

Correct login.

**KeePassDX:**

 - Version: 2.7.6
 - Build: free
 - Language: english

**Additional context**

 - Browser for Autofill: Vivaldi

**Comment by J-Jamet** [comment]
Fixed with : https://github.com/Kunzisoft/KeePassDX/issues/1665#issuecomment-1793425464
