### ISSUE TITLE
Autofill Not Showing With Florisboard

### ISSUE THREAD

**Issue by seniorm0ment** [Kunzisoft/KeePassDX#1659]
I have Florisboard as my keyboard, and the autofill prompt does not appear.
If I switch to the stock keyboard, it shows up.

Pixel 6 Pro, GrapheneOS Version: 2023100300 
KeepassDX Fdroid 3.5.1, Florisboard Fdroid 0.3.16

**Comment by J-Jamet** [comment]
The code is generic and does not depend on a particular keyboard. It's up to the keyboard to make its code compatible with inline autofill.

**Comment by seniorm0ment** [comment]
Sorry, you're right. I tried with their beta version and it seemed to work.
