### ISSUE TITLE
Why 2 KeePassDX versions on IzzyDroid ?

### ISSUE THREAD

**Issue by not-programmer98** [Kunzisoft/KeePassDX#1664]
Now there are 2 version on fdroid and IzzyOnDroid and it's confusing.
It's an important app which does a critical job and I don't want to lose all of my passwords.

What should a noob do after not receiving updates from fdroid?
I wish you could provide some sort of guide for noobs like me

**Comment by shuvashish76** [comment]
Export-Import your [App properties](https://github.com/Kunzisoft/KeePassDX/wiki/Import-and-Export#app-properties) if you want to switch over to latest `free` (IzzyOnDroid) version.
See [FAQ](https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-a-libre-and-free-version) for difference between `free` vs `libre` version.

**Comment by not-programmer98** [comment]
So basically the libre and free version are the same except that libre is built by fdroid?

**Comment by not-programmer98** [comment]
Is there any thing you wanna add @J-Jamet ?

**Comment by J-Jamet** [comment]
Make backups : https://github.com/Kunzisoft/KeePassDX/wiki/Backup

And help us solve the main problem :D https://github.com/Kunzisoft/KeePassDX/issues/1333

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-two-keepassdx-versions-on-izzydroid
