### ISSUE TITLE
Save a copy to results in empty file with read only mode

### ISSUE THREAD

**Issue by cbiere** [Kunzisoft/KeePassDX#1666]
Using the built-in function "Save a copy to" to create a copy of the database results in an empty file regardless what storage is used ( internal or SDHX card). I tried with two different databases.

1. Unloock a KDBX file with KeePassDX
2. Tap on the three line menu in the upper left
3. Tap on save a copy to and pick whatever folder.
4. Lock the database and inspect the newly created KDBX file: it's zero bytes.

I expected KeePassDX to create an identical copy of the database just like copying the file with a file manager.

**KeePass Database**

 - Created with: KeePassDX or KeePass 2.x on Windows 
 - Version: 2 KDBX 4.0
 - Location: internal storage: /storage/emulated/0
 - File provider (`content://` URI): content://com.android.externalstorage.documents/document/primary:KeePass/KeePass-Database.kdbx
 - Size: 663 kB
 - Contains attachment: very few

**KeePassDX:**
com.kunzisoft.keepass.free
Installed: 12 Oct 2023; 11:30
Installed from Google Play Store

 - Version: 4.0.2
 - Build: Free
 - Language: English 

**Android:**

 - Device: Redmi Note 10 Pro (sweet)
 - Version: Android 13 (SparkOS)

**Comment by risuello** [comment]
I had a similar bug or something like this

**Comment by J-Jamet** [comment]
I just tested on several devices and I have no problems. Does it work with a new database?

**Comment by J-Jamet** [comment]
Several people have also reported the problem to me and have Xiaomi (you are not afraid to choose this type of equipment :D)

**Comment by J-Jamet** [comment]
Hoo I see. This is indeed a bug that needs to be fixed. I'll take care of it and make it a priority.

**Comment by J-Jamet** [comment]
Fixed in develop : #7198ffff4349e128d235b74b5485e97d2f3e8245
