### ISSUE TITLE
Autofill not working on Reddit app

### ISSUE THREAD

**Issue by alexknop** [Kunzisoft/KeePassDX#1667]
**Describe the bug**

I am not getting any inline suggestions to autofill using this app's autofill service.

Getting inline suggestions with another autofill service (keepass2android)
**To Reproduce**

1. Install and go to Reddit application
2. Click on Login
3. No inline suggestion for a Reddit login
4. Try again but using another autofill service. Same database but actually get a suggestion.

**Expected behavior**
Expecting to get inline suggestions on the Google Keyboard

**KeePass Database**

 - Created with: KeepassXC for Linux
 - Version: 2
 - Location: Remote file in Nextcloud (also saved offline)
 - File provider (`content://` URI):
 - Size: 55Kb
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.2
 - Build: Free
 - Language: English

**Android:**

 - Device: TCL Tablet
 - Version: 13

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
duplicate #1572

**Comment by alexknop** [comment]
will close due to duplicate issue being tracked.
