### ISSUE TITLE
Android KeePassDX gets locked often while autolock is diaabled

### ISSUE THREAD

**Issue by surenazatyan** [Kunzisoft/KeePassDX#1672]
**Describe the bug**

Hi good people,  
Android app KeePassDX gets locked quite often.
I  tried to disable auto lock but doesnt seem to help.  I suspect this might be related to having DriveSync affecting ? (Syncing android folder with google drive where keepass db is).
Are there remedies ?

**Expected behavior**

**Android:**

 - Device: Galaxy Zfold5
 - Version: 4.0.2

**Additional context**

android directory that is synced with google drive via drivesync app

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-did-the-app-lock-before-the-timeout-duration-has-elapsed
