### ISSUE TITLE
Layout Problems With Password Generator

### ISSUE THREAD

**Issue by christantoan** [Kunzisoft/KeePassDX#1674]
**Describe the bug**

There's no margin between "Consider characters" and "Ignore characters" field. Also, when activating "At least one character from each" button, the "Exclude ambiguous character" button moves down.

**To Reproduce**

1. Open password generator screen.
2. (For second problem) (De)activate "At least one character from each" button.

**Expected behavior**

There are some margin between "Consider characters" and "Ignore characters" field and when activating "At least one character from each" button, the "Exclude ambiguous character" button doesn't move down.

**KeePass Database**

 - N/A.

**KeePassDX:**

 - Version: 4.0.2
 - Build: Free
 - Language: English

**Android:**

 - Device: OnePlus 7 Pro
 - Version: 11

**Additional context**

Screenshots:
![Screenshot_20231105-135728](https://github.com/Kunzisoft/KeePassDX/assets/7300310/7ab84cc8-0f76-49a8-81f1-58ffd9ce25f6)
![Screenshot_20231105-135732](https://github.com/Kunzisoft/KeePassDX/assets/7300310/0b86e775-9173-4390-8eab-71fb0de3c3a7)

**Comment by J-Jamet** [comment]
The margin has been corrected, but the Toast passing underneath is normal system behavior. This happens because the selected view is too large for your screen.

**Comment by christantoan** [comment]
Wouldn't making them 2 lines in the first place better?

**Comment by J-Jamet** [comment]
It's not how it works : https://m3.material.io/components/chips/overview

**Comment by christantoan** [comment]
I see. Thank you for the information.

**Comment by J-Jamet** [comment]
Actually, the code for chip views is very simple: 
```
                <com.google.android.material.chip.ChipGroup
                    android:id="@+id/password_advanced"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:chipSpacingVertical="16dp"
                    android:paddingTop="@dimen/default_margin"
                    android:paddingBottom="@dimen/default_margin">

                    <com.google.android.material.chip.Chip
                        android:id="@+id/atLeastOne_filter"
                        style="@style/KeepassDXStyle.Chip.Filter"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:checked="true"
                        android:text="@string/at_least_one_char"/>
                    <com.google.android.material.chip.Chip
                        android:id="@+id/excludeAmbiguous_filter"
                        style="@style/KeepassDXStyle.Chip.Filter"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:checked="true"
                        android:text="@string/exclude_ambiguous_chars"/>

                </com.google.android.material.chip.ChipGroup>
```
It's the content of the chips that determines whether or not they are on multiple lines.
