### ISSUE TITLE
FABs Sizes Are Not The Same

### ISSUE THREAD

**Issue by christantoan** [Kunzisoft/KeePassDX#1675]
**Describe the bug**

Lock and "+" FABs' sizes are not the same 

**To Reproduce**

1. Enable "Show lock button" option in App settings.
2. Open the main screen and check the Lock and "+" FABs' sizes.

**Expected behavior**

Lock and "+" FABs' sizes are the same.

**KeePass Database**

 - N/A.

**KeePassDX:**

 - Version: 4.0.2
 - Build: Free
 - Language: English

**Android:**

 - Device: OnePlus 7 Pro
 - Version: 11

**Additional context**

Screenshots: 
![Screenshot_20231105-142849](https://github.com/Kunzisoft/KeePassDX/assets/7300310/755244fa-857f-4c45-ad5d-c0963d02d28b)

**Comment by J-Jamet** [comment]
This is normal, as the lock button is less important than the add button.

**Comment by christantoan** [comment]
Thank you for the confirmation. I've sometimes had problems with other apps due to my screen DPI.
