### ISSUE TITLE
Autofill not working with Instagram

### ISSUE THREAD

**Issue by kleidiss** [Kunzisoft/KeePassDX#1677]
**Describe the bug**

Setting the autofill service as keepasdx and trying to sign in on an android app does not work like other autofilll services 

Clicking on the passowrd field no autofill pop up shoes  , long tapping, and clicking autofill to manually bring up the autofill pop up also doesn't work 

**To Reproduce**

Try and sign in into an android app that isn't  a browser 

**Expected behavior**

The autofill pop-up should appear, and i should be able to sign in the database and choose a password.

**KeePass Database**

 - Created with: [KeepassXC]
 - Version: [e.g. 2]
 - Location: [SyncThing from Windows to Android]
 - Size: [67kb]
 - Contains attachment: [?]]

**KeePassDX:**

 - Version: [4.0.2]
 - Build: [Free]
 - Language: [English]

**Android:**

 - Device: [Galaxy A34]
 - Version: [ONE UI 6 A13]

Example screenshot in browser
![Screenshot_20231105_195832_Kiwi Browser.jpg](https://github.com/Kunzisoft/KeePassDX/assets/124008722/d4c26438-cafd-4f48-9a41-1eb60a21894c)

Meanwhile in any app nothing shows up

**Comment by J-Jamet** [comment]
You're not specific enough about the applications you've tested. In the case of Reddit, the problem has been fixed. 
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1572

**Comment by kleidiss** [comment]
> You're not specific enough about the applications you've tested. In the case of Reddit, the problem has been fixed. Duplicate #1572

I tested it on instagram , spotify and reddit and it didn't work for any of them
I can check more but it seems that the app autofill is totally broken for me

**Comment by kleidiss** [comment]
It doesn't work on google account page either
Clicking the autofill context menu does nothing

**Comment by J-Jamet** [comment]
Fix #1572 will solve the problem at least for Reddit. Other applications will have to be tested with the patch.

**Comment by kleidiss** [comment]
Can you provide a apk of the develop branch if you don't mind

**Comment by J-Jamet** [comment]
I'll be testing on my devices and releasing version 4.0.3 later today anyway.

**Comment by J-Jamet** [comment]
On Reddit it works.
On Twitter, you need to reach the password, which is normal since two-screen authentication is not yet supported.
On Spotify it works if you do a long click and "Autofill", which must be because Spotify hasn't tagged the form fields.
On Instagram it works.

**Comment by kleidiss** [comment]
For me on instagram nothing shows up rven if i select "Autofill"

**Comment by J-Jamet** [comment]
Can you check with the version 4.0.3?

**Comment by kleidiss** [comment]
I did , instagram and reddit are still not working 

May i ask what phone you have , maybe this is a OneUI issue

**Comment by J-Jamet** [comment]
Emulator and many devices. In any case, I can only modify the form recognition algorithm, not the autofill service which is managed by your system. Have you tried restarting your device or changing any developer settings?

**Comment by kleidiss** [comment]
I did a restart but what develoer settings can i change on a smasung device

**Comment by J-Jamet** [comment]
You can check the version 4.0.4

**Comment by sudhirkhanger** [comment]
I am still facing issues with the instagram app on Android.

Username doesn't trigger autofill even after clicking on autofill.

When I click on the password then the keyboard hint shows up but it only fills the password and not the username.

I am on Pixel Fold. Android 15. KeePassDX 4.0.8.
