### ISSUE TITLE
Corrupts database attachments on modification

### ISSUE THREAD

**Issue by collectorgeneral** [Kunzisoft/KeePassDX#168]
I have a database with lots of entries having attached files. I just discovered that when I modified and save the database in KPDX, the resultant database has all its attachments corrupted. I found this when the database size reduced from >1MiB to ~100KiB which I found to be quite odd. My first thought was the my attachments might have been affected, as they are what contribute to most of the database size. And indeed, on inspection, I found my attachments were no longer being displayed. (Surprisingly `logcat` did not seem to indicate any major errors.)

I have attached an example database file (basically my database with all entries stripped out and two dummy entries).
[MyDatabase.KPDX.kdbx.zip](https://github.com/Kunzisoft/KeePassDX/files/2289112/MyDatabase.KPDX.kdbx.zip)
In order to replicate the bug, I did the following steps:
- open database on KPDX by gonig to the app -> open database
- type password `hunter2`

Observe first entry named 'FSF' with the attachment rms-essays.pdf downloaded from [here](https://www.gnu.org/philosophy/fsfs/rms-essays.pdf). KPDX does not yet allow viewing attachments I think, I did this on KPXC.

- Go the first sub-group
- copy the google one and paste in in the same sub group to clone the entry.
- modify the newly cloned entry (I changed the user to `secretid2` and password to `secretpasswd2'.
- after saving observe the database size reduce from >2 MiB to about 100 KiB.

Now try opening the file again. Your PDF viewer should say the file is corrupted.

Until this issue is inspected, I caution users to be careful when modifying databases. I got lucky as I saved my database to a cloud service where I was able to trace back to the most recent robust copy and also determined KPDX to be the source of the corruption. 
Would be glad to help if you need more information.

**Comment by Weishaupt** [comment]
I don't know, if this issue really stems from the usage of the app, but I experienced a similar issue: I attached pictures to four different entries in my database. I later modified the database using KPDX. Now when I open the database using either KeePass or KPXC the attachments were mixed up. Still the same records had attachments, and the file names of the attachments indicated, those are the correct attachments, but the actual pictures were shuffled up. So the attachmend belonging to record A now showed up on record B.
