### ISSUE TITLE
Question for APK Build Libre and Build Free

### ISSUE THREAD

**Issue by franco27** [Kunzisoft/KeePassDX#1681]
Hello,
for the KeePassDX-4.0.3 version, there are two APK files.

Which one should I download and install?
Can you please explain the difference between these two files?

Thank you in advance for your clarification.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-a-libre-and-free-version

**Comment by franco27** [comment]
Thank you very much.

**Comment by io43** [comment]
what happened now the free is on fdroid and up-to-date while the libre is outdated from several months?
