### ISSUE TITLE
Autofill doesn't work in cromite browser

### ISSUE THREAD

**Issue by dmework** [Kunzisoft/KeePassDX#1684]
**To Reproduce**

1. Open cromite browser
2. Open website
3. No autofill popup

**Expected behavior**

work fine With KeepassDX version 3.5.1

**KeePassDX:**

 - Version: [4.0.4]
 - Build: [e.g. Free]
 - Language: [e.g. English]

**Android:**

 - Version: [9]

**Comment by J-Jamet** [comment]
![Screenshot_20231108_190617](https://github.com/Kunzisoft/KeePassDX/assets/19224038/95460444-8b2d-4dde-a053-a6182d438e7f)

Just checked with last release of [cromite](https://github.com/uazo/cromite/releases/tag/v119.0.6045.106-9344cc41d5d85463ee12bc449c72ad335f7545fe) and it works fine.

**Comment by dmework** [comment]
thanks did you check with android 9

**Comment by dmework** [comment]
Sorry my bad it seems that I was block listing keepassDX free version because I was using fdroid version now it's working thanks have a nice day.
