### ISSUE TITLE
KeepassDX 3.5.1 no master key changeable

### ISSUE THREAD

**Issue by benutzer74** [Kunzisoft/KeePassDX#1688]
After opening the databade in KeePassDX 3.5.1 I can't change the password, all master key operations are greyed.
The database was created using KeePassDX around 3-4 years ago and is version V2 - KDBX 4.0.
It opens fine with either password or finger print.
Everything fine, I just can't change the password.

System:
Android 14 with GrapheneOS on a Google Pixel 7a.
KeepassDX 3.5.1 from F-Droid

Thank you for your efforts

**Comment by J-Jamet** [comment]
Modifying the master key is the first option and is always available when the database is open. The next three actions have simply not yet been implemented.
