### ISSUE TITLE
Nextcloud Offline File Takes too Long to Load

### ISSUE THREAD

**Issue by alexknop** [Kunzisoft/KeePassDX#1692]
**Describe the bug**

When offline and unable to reach my Keepass database file stored in Nextcloud, the timeout to fall back to a known offline version is about 45 seconds. This should be shortened if not a near instant adjustment to go to a known offline version. I would understand the timeout if the file was not already synced and saved offline.

**To Reproduce**

1. Have nextcloud client for Android
2. Save Keepass database file offline in Nextcloud so that a local copy is also stored on your device
3. Open this file in KeepassDX and try to unlock while offline
4. Keepass will say "Loading database" for about 45 seconds (too long) before saying "File cannot be synced. Showing latest available version" and then the Database loads fine.

**Expected behavior**

A quicker load of DB

**KeePass Database**
 - Version: 2
 - Location: Retrieved from Nextcloud but file is also saved offline
 - File provider (`content://` URI):(content://org.nextcloud.documents/document/1b3c8a4383b4f5c1e7c29a592e23e4dd%2F29)
 - Size: 52Kb
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.5
 - Build: free
 - Language: English

**Android:**

 - Device: TCL Tablet
 - Version: 13

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
KeePassDX doesn't handle file synchronization, and only uses the file provider's SAF, in this case the NextCloud application.

"File cannot be synced. Showing latest available version" is not a wording contained in KeePassDX but a Nextcloud error. You should therefore simply open this issue in the correct project.

**Comment by alexknop** [comment]
Got it. Will open in Nextcloud
