### ISSUE TITLE
Update version 3.5.1

### ISSUE THREAD

**Issue by Jetrom17** [Kunzisoft/KeePassDX#1694]
I checked on F-droid and didn't receive an update. I have the version 3.5.1. I was not informed of the new update. Luckily I checked manually and saw that there was another build of the app with more updates and features. 

Note: I have already downloaded the new update. I am uninstalling the old stopped application (version 3.5.1) (for version 4.0.5).

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1644

**Comment by Jetrom17** [comment]
> Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1644

Thank you very much for informing me.
