### ISSUE TITLE
Why are there 2 versions of KeePassDX on F-droid?

### ISSUE THREAD

**Issue by muchqs** [Kunzisoft/KeePassDX#1696]
The version I've been using and linked to from KeePassDX homepage is v3.5.1 and haven't been updated in over 7 MONTHS??
Accidentally found another entry on F-droid that's updated to latest v4.0.5 from the Izzyondroid repo.
How come the official entry is still on v3.5.1?

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1644

https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-are-updates-not-available-at-the-same-time-on-all-stores
