### ISSUE TITLE
Biometric unlock only with master key

### ISSUE THREAD

**Issue by LiaraAlis** [Kunzisoft/KeePassDX#1697]
At the moment it is possible to enable biometric unlock when a password is used. But it is not possible when the database is only unlocked with a key file. I think it should be also possible to use biometric unlock when only using a key file. So it could be senseful that the key file is only selected after biometric unlock. If not successful, path to the key file should be empty.

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1315
