### ISSUE TITLE
What is the period for providing pro access to KeePass DX? 

### ISSUE THREAD

**Issue by Mat1RX** [Kunzisoft/KeePassDX#1698]
What is the period for providing pro access to KeePass DX libre?  I made a donation of about 10.5 usd through the monero cryptocurrency, to the address indicated on your website, and sent a link with proof of the transaction to your email address.  No response yet...

**Comment by J-Jamet** [comment]
Contrary to what people might think, developers can have a life, even if they donate their free time to open source projects.
I reply to all the e-mails, but I must already have time to read them, so there's no need to spam my inbox.
I've replied, thanks for the contribution.
