### ISSUE TITLE
Enable scp/sftp sync

### ISSUE THREAD

**Issue by alex9099** [Kunzisoft/KeePassDX#17]
Hi, it would be nice to see scp/stfp sync (or any other kind of sync that does not relly on servers i don't fully control) on this project :)

**Comment by J-Jamet** [comment]
Hello, remote access should not be part of the application. There are many kinds of sync and, in my opinion, it is not the purpose of the app to implement them. 
If you want to add this feature, I can fork the code for a specific mission. (For more information, we can continue the discussion by email : jeremy.jamet@kunzisoft.com)

**Comment by alex9099** [comment]
Syncthing seems to work well, it would be ok if this sync feature was added to keepassDX.

Anyway, thanks for this awsome project ;)
