### ISSUE TITLE
The password vault broke 

### ISSUE THREAD

**Issue by Zaxx69** [Kunzisoft/KeePassDX#1704]
I was using the latest version of keepassdx ,but while using it ,the software completely broke my vault .now whenever i open my vault using my credentials ,it shows an infinite reload page and none of the password is showing up . I tried clearing the cache ,downgrading the app version but nothing worked ,even if i create a new vault ,it doesn't wrok . please help me as all of my passwords are saved in it 

Android 13
Realme 8
Keepassdx latest free version

@J-Jamet sorry for pinging but please help me ,i am little bit scared

**Comment by Oliveinparis** [comment]
Maybe try to open the database with a different app like keepassxc on a computer or keepassDroid for now.

My best guess is that your database is corrupted, but I might be wrong, do you have any backups? I know that the keepaas app on PC has a recovery feature or something, try to look into that.

Best wishes and regularly do backups of your database.

I'm not a developer of this project.

**Comment by Oliveinparis** [comment]
Well as you created a new vault and it doesn't work maybe the files are not corrupted. You wrote that when opening the vault it has an infinite load time, but then write that it shows no passwords? Is the loading very long and it returns no passwords?

Have you tested to open the keyfile in an other app?

And what is the 'newest version' because fdroid doesn't give the newest version.

**Comment by Zaxx69** [comment]
I used my vault password to open the file ,but after opening ,it didn't showed anything except a loading screen
I used two apps keepassdx and another similar one ,which also didn't work ,i also tried degrading the app ,which also didn't work
there were two backups ,and yes both didn't opened 
I even tried to save the file when it was infinitely loading ,and it returned a 0kb file
I used the build from github
After i opened this issue ,about 6 hours later ,i checked again and to my suprise it opened for one last time and i was able to copy every password

**Comment by Oliveinparis** [comment]
Happy to hear that! Maybe you were trying to open the .keyx or another type file rather than the .kdbx?
Have a great day.

**Comment by Zaxx69** [comment]
No it was .kdbx file type ?

**Comment by J-Jamet** [comment]
I think your database is badly formatted. One solution is to use KeePass for PC, open it, export your database in XML format and re-import it into a new database. This should solve the formatting problem. Sorry for the late reply.

**Comment by J-Jamet** [comment]
I'm closing this ticket, there's not much more I can do without information about the base itself.
