### ISSUE TITLE
Inline autofilling not working with fcitx5-android.

### ISSUE THREAD

**Issue by su226** [Kunzisoft/KeePassDX#1708]
**Describe the bug**
After I clicked "Select entry..." in fcitx5-android, still only the "Select entry" button is shown, no password entries available. It only happens with fcitx5-android and KeePassDX, not fcitx5-android with other autofill services (Bitwarden and KeePass2Android tested myself), nor KeePassDX with other input methods (GBoard tested myself).

According to the developer of fcitx5-android, fcitx5-android is compliant to the Android Developer documentation, it *might* be the problem of KeePassDX: https://github.com/fcitx5-android/fcitx5-android/issues/334#issuecomment-1712876567 (Chinese)

![Actual behavior with fcitx5-android](https://github.com/Kunzisoft/KeePassDX/assets/17371317/eb78d857-7e0c-4b5d-84a0-6d05235ae481)

**To Reproduce**
1. Set current keyboard to fcitx5-android.
2. Set autofill service to KeePassDX and enable inline suggestion in both KeePassDX and fcitx5-android.
3. Click a password input.
4. Click the "Select entry..." button and select a entry.

**Expected behavior**
Suggestions shown. (Example with GBoard)

![Expected behavior with GBoard](https://github.com/Kunzisoft/KeePassDX/assets/17371317/1db657fd-00e7-41c2-9b0a-7bd558f66e40)

**KeePass Database**
 - Created with: KeePassXC Linux
 - Version: V2 - KDBX4.1
 - Location: Local file synced with Syncthing app.
 - File provider (`content://` URI): content://com.android.externalstorage.documents/document/primary%3ADocuments%2FKeePass%2Fkeepass.kdbx
 - Size: 321.6KiB
 - Contains attachment: No

**KeePassDX:**
 - Version: 4.0.5
 - Build: Libre (Downloaded from F-Droid)
 - Language: Chinese (Simplified)

**Android:**
 - Device: Redmi K50 Pro
 - Version: Android 13 (MIUI 14.0.13)

**Additional context**
I have enabled the "Display pop-up windows while running in the background" permission and the "Selection mode (Autofill)" UI is shown as expected, only the selected entry not shown in fcitx5-android.

Autofill popup is shown as expected when inline suggestion is turned off.

Might be the same problem with #1702.

fcitx5-android version: 0.0.8-0-g4c839ad [[F-Droid]](https://f-droid.org/zh_Hans/packages/org.fcitx.fcitx5.android/) [[GitHub Releases]](https://github.com/fcitx5-android/fcitx5-android/releases/tag/0.0.8)

**Comment by J-Jamet** [comment]
Linked with https://github.com/Kunzisoft/KeePassDX/issues/1166
It works well with GBoard, which means that KeePassDX is sending the right information.
It seems that only one item is displayed in your keyboard, the same problem is visible on Florisboard.
Apparently the documentation on the subject isn't very good, but there's nothing more I can do.
