### ISSUE TITLE
Remove the "merge, reload" wording in read only mode

### ISSUE THREAD

**Issue by DuckDuckWhale** [Kunzisoft/KeePassDX#1709]
**Describe the bug**

There's a window that pops up when an open file is overwritten saying that I can either merge, reload, or save, but only the reload option is available in read only mode, making it impossible to save the entries in the locally open database.

**To Reproduce**

1. Open database in read only mode without noticing since that's the mode last time
2. Overwrite the file with a slightly different database as an attempt at synchronization
3. Observe a pop up saying the three options
4. Try to find the merge & save options but they aren't there
5. Worry about the safety of my data and scream in desperation trying to find the damn merge button
6. (I managed to hit a condition where a dot appears near the title, which I assume indicates that the database is modified, but I wasn't able to reproduce it. But that's even more frustrating because locking or reloading both warns me that I'm about to lose data, but there's nothing else I could do.)
7. (I tried to save to another file then manually merge the two, but it's clunky and I'm not even sure if this actually saves the current loaded file or the newer overwritten file.)

**Expected behavior**

There should be a button to merge even if it's under read only mode, ideally in the pop up itself.

**KeePass Database**

Will provide if needed.

**KeePassDX:**

 - Version: 4.0.5 from F-Droid
 - Build: libre
 - Language: English

**Android:**

Will provide if needed.

**Comment by J-Jamet** [comment]
> There should be a button to merge even if it's under read only mode, ideally in the pop up itself.

No, it's just a bad wording, it should be just "reload". It is not possible to merge or save a database in read-only mode, because by definition it is read-only.
