### ISSUE TITLE
"Open existing vault" button confusing, and should have other functionality

### ISSUE THREAD

**Issue by Maltimore** [Kunzisoft/KeePassDX#1714]
**Is your feature request related to a problem? Please describe.**
99.999% of the time, I want to open the vault I already have configured. When I start the app, there is a button saying "open existing vault". However, this button does not open my existing vault, but it is for opening a *new* vault. Not only is that confusingly labeled, but the functionality of opening an entirely new vault should be much less prominent. The buttons on the bottom end of the screen are easily reachable for the thumb and most users use their phone with the thumb. So the buttons in the lower part of the screen are the most prominent buttons.

![Screenshot_20231206-125340](https://github.com/Kunzisoft/KeePassDX/assets/10359335/6f448976-1b99-407d-a1bd-d3c8735406f4)

**Describe the solution you'd like**
The button "open existing vault" should open the default configured vault. Adding a new vault should be in the settings, as one almost never adds an entirely new vault.

**Comment by J-Jamet** [comment]
Open existing vault -> Select existing vault

And replace "star" icon by an "open folder" icon

It's ok for you?

**Comment by Maltimore** [comment]
I mean this is purely an ergonomics issue (thanks for putting the label) so there's no clear right and wrong. I think your suggestion is not bad but I would actually change the "open existing vault" button to "open selected vault" and make the default key file preselected. That way it's just one tap to open the vault.

**Comment by J-Jamet** [comment]
Honestly, "open existing vault" is the right designation for me. In any case, you need to select it, as it's not new since the file (so the vault) has already been created, and therefore already exists.
