### ISSUE TITLE
kdbx file with YubiKey challenge-response master key saved by KeePassDX can't be opened by keepassxc

### ISSUE THREAD

**Issue by andyli** [Kunzisoft/KeePassDX#1719]
**Describe the bug**

I have an existing kdbx file. Recently, I enabled YubiKey challenge-response on top of a password, using KeePassXC on Windows. The file can be opened and decrypted by KeePassXC on Windows and KeePassDX on Android, using the same master password and YubiKey. However, once I save it with KeePassDX on Android, even without any changes to the entries, the kdbx file can no longer be decrypted by KeePassXC on Windows, but still decryptable by KeePassDX on Android.

**To Reproduce**

Here is the kdbx file with all passwords removed:
[yubikey-sample-kdbx.zip](https://github.com/Kunzisoft/KeePassDX/files/13690081/yubikey-sample-kdbx.zip)

* "password-only.kdbx": Master password is `test`, no hardware key. Can be opened correctly by KeePassXC on Windows and KeePassDX on Android.

* "password-and-yubikey.kdbx": Created from "password-only.kdbx" but with master key changed to include YubiKey challenge-response, using KeePassDX on Android. The YubiKey's slot 2 was configed as HMAC-SHA-1 challenge-response, with secret key `00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`. The file can be opened correctly by KeePassDX on Android, but not by KeePassXC on Windows.

1. Open "password-only.kdbx" in KeePassDX on Android, password is `test`
2. Go to settings and change master key, input `test` as password, select Yubikey challenge-response.
3. Save the file.
4. Open the file with KeePassXC on Windows, try to decrypted, "invalid credencials" error message will be shown.

**Expected behavior**

kdbx files saved in KeePassDX on Android can be opened and decrypted by KeePassXC on Windows.

**KeePass Database**

 - Created with: probably created by KeePass2 on Windows, many years ago
 - Location: Remote file retrieved with Dropbox app
 - File provider (`content://` URI): `content://com.dropbox.android.FileCache/filecache/xxxxxxxxxxx.kdbx`
 - Size: 17KB
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.5
 - Build: libre
 - Language: English
 - Key Driver version 0.1.7

**Android:**

 - Device: Galaxy S9+
 - Version: 10

**Additional context**
 - YubiKey 5C NFC
 - KeePassXC - Version 2.7.6 Revision: dd21def

**Comment by J-Jamet** [comment]
You are using KeePassDX Version: 4.0.5, upgrade at the latest version 4.0.8

**Comment by J-Jamet** [comment]
Same as https://github.com/Kunzisoft/KeePassDX/issues/1680
