### ISSUE TITLE
KeePassDX and rclone?

### ISSUE THREAD

**Issue by nichdemos** [Kunzisoft/KeePassDX#1726]
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
What I describe here is a form of backup and synchronization, to prevent me from losing my Android passwords if I am stolen or my cell phone has a virus. Would it be possible to use KeePassDX with rclone and thus have a bank of passwords in different places: google-drive, dropbox, meganzco, trezorit etc?

**Describe alternatives you've considered**
- Lightweight vault and password manager for Android, KeePassDX allows editing encrypted data in a single file in KeePass format and fill in the forms in a secure way.

**Additional context**
- [rclone](https://rclone.org/): *"Rclone syncs your files to cloud storage"*
- [x0b/rcx](https://github.com/x0b/rcx): *"Rclone for Android"*

**Comment by exstntlmsnthrp** [comment]
You may consider using keepassdx and [syncthing](https://github.com/syncthing/syncthing-android) together. This is what I do for similar reasons you describe. 

I also use [keepassXC](https://github.com/keepassxreboot/keepassxc) on my computer as it can read the keepassdx database files. So I have syncthing on my phone, my laptop, desktop PC, and my NAS and they all sync an encrypted, updated copy of my keepassdx database. So if my phone or laptop are ever stolen or get malware or die, I still have access to all my passwords. Also, this way I'm not reliant upon a third party SaaS for my password manager.

**Comment by nichdemos** [comment]
Hi @exstntlmsnthrp, how are you? thanks for comment here!

**Comment by exstntlmsnthrp** [comment]
> Hi @exstntlmsnthrp, how are you?  thanks for comment here!
> 
> > Also, this way I'm not reliant upon a third party SaaS for my password manager.
> 
> I understand that we shouldn't depend on SaaS, but I don't have the money.
> 
> ***What do you think of this idea: rclone to password managers?***

This is why I made the recommendation. It does not cost anything. It's open source and free. For what you inquire about, I would recommend syncthing and not rclone. It's much easier.

**Comment by nichdemos** [comment]
Hi @exstntlmsnthrp, how are you?

> This is why I made the recommendation. It does not cost anything. It's open source and free. For what you inquire about, I would recommend syncthing and not rclone. It's much easier.

thanks! thanks for comment!
