### ISSUE TITLE
Biometric selection causing freeze

### ISSUE THREAD

**Issue by btgunter** [Kunzisoft/KeePassDX#1728]
**Describe the bug**

When I select to allow unlocking using the phone's fingerprint reader, then try to type in the password section, the application freezes

**To Reproduce**

1. Open application
2. Select database
3. Type "aaa"
4. Textbox works
5. Click settings
6. Click device unlocking
7. Toggle Biometric unlocking to on (and click ok)
8. Hit back twice to return to password entry
9. Type a character, toggle a switch, etc, and the application freezes 

**Expected behavior**

I should be able to type in a password, or toggle a switch

**KeePass Database**

 - Created with: Windows Keepass 2.7.6
 - Version: [e.g. 2]
 - Location: Phone's SD card
 - File provider (`content://` URI): content://com.android.externalstorage/.documents/9016-4EF8:KeepassXC/keepass.kdbx (Also happens when the file is in the download folder)
 - Size: 20kb
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.5
 - Build: Libre
 - Language: English

**Android:**

 - Device: Galaxy S10e
 - Version: Android version 12

**Comment by J-Jamet** [comment]
The problem comes from the Samsung S10, which offers a buggy API for symmetric keys. The only thing I can suggest is that you update your OS. 
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1269
