### ISSUE TITLE
Provide SHA256 fingerprint of KeePass Apks.

### ISSUE THREAD

**Issue by rakearyo** [Kunzisoft/KeePassDX#1732]
The signature of KeePassDX is useful to verify that the apk hasn’t been compromised in any way. 

Project like Signal or ProtonApps provide the fingerprint. Since KeepassDX is used to manage sensitive data, it could be useful to verify the apk. Ideally, you would post the fingerprint on different places (GitHub, your personal website, twitter, mastodon and so on) so we don’t have to trust the server.

Also, there is a really cool project called AppVerifier (https://github.com/soupslurpr/AppVerifier/commits/master/) which can easily check wether the signature of an application is the right one or not.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/issues/1416
