### ISSUE TITLE
Old version with Nextcloud app

### ISSUE THREAD

**Issue by dupondje** [Kunzisoft/KeePassDX#1741]
**Describe the bug**

I have a keepass file on my Nextcloud instance which is synced with my computer and my phone.
On my computer I use KeepassXC, and KeepassDX on my phone.

Now I already had at least 2 times that when I add an entry in KeepassDX on my phone, the file gets synced with my computer, but some entries are lost.
It seems like KeepassDX still has some older version of the keepass file, and add's the new entry to that one and saves it. Which then overwrites the newer version in Nextcloud. This causes my to lose credentials added since the old/cached version KeepassDX opens.

**To Reproduce**

1. Open keepass file in KeepassDX
2. Add new entry
3. It gets saved
4. Nextcloud syncs it to the Nextcloud
5. Some credentials lost (see above)

**Expected behavior**

Before opening the database, KeepassDX should somehow check if it's the latest version.

**KeePass Database**

 - Created with: KeepassXC
 - Version: 2.7.6
 - Location: Nextcloud
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: 230K
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.5
 - Build: Free
 - Language: Dutch

**Android:**

 - Device: Poco F4 GT
 - Version: 13

**Additional context**

Used K2A before, and never had this issue.

**Comment by J-Jamet** [comment]
KeePassDX doesn't keep any cache, try deleting the NextCloud application cache.

**Comment by RedFox-Fr** [comment]
Hello.

I have the same problem with Nextcloud client 3.28.1 and KeepassDX 4.0.5
Devices are Samsung Galaxy S9+ and Xiaomi 14 Ultra. 

Best regards,

**Comment by J-Jamet** [comment]
In any case, the problem doesn't lie with KeePassDX here, as there is no file cache. You need to open the ticket on the NextCloud project.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
