### ISSUE TITLE
Custom Template moving field up or down (question)

### ISSUE THREAD

**Issue by JackDSRS** [Kunzisoft/KeePassDX#1744]
I successfully figured out template creation and adding fields to copies of templates. Go me!

However, I'd like to move some fields up or down from their positions. Say, I'm using a variation of another existing template and adding an email field. It appears at the bottom of the template. 

I'd like to move it under the username field instead of recreating all the fields in the order I want and deleting the old order.

Or be able to cut and paste the field where I want it.

If I don't like the way a template turns out, I'd like to be able to easily edit it.

I searched the wiki, issues, and discussions and didn't find an answer. I'm not a coder so I don't want to mess with that.

Is there a way to do it or do I have to grind through it? I'm willing to grind my way through, but I'm having to do that with a lot of apps and just had to review over 800 settings on another.

**Comment by J-Jamet** [comment]
Basically, templates are entries like any other, so the issue will be resolved when this issue is resolved: https://github.com/Kunzisoft/KeePassDX/issues/1230

**Comment by JackDSRS** [comment]
Oh, then you can move, close, or delete this issue. Thanks!
