### ISSUE TITLE
Space in search should be interpreted as _another_ substring

### ISSUE THREAD

**Issue by alexanderadam** [Kunzisoft/KeePassDX#175]
Thank you for KeePassDX. I love it!

There's just one small issue that bothers me:
So in case someone has a key like "`abc def ghi jkl`" a search for "`abc ghi`" won't find anything in KeePassDX (it will find something in other KeePass implementations).

Thank you and have a wonderful day!

**Comment by J-Jamet** [comment]
This is not available with a traditional search because items may contain spaces. We would have to implement regexes but this is not urgent at the moment.

**Comment by alexanderadam** [comment]
> This is not available with a traditional search because items may contain spaces.

This is trivial with databases like SQLite but even with a traditional search a search string `"abc def"` would simply become the regex `Regex("abc.*def", IGNORE_CASE, DOT_MATCHES_ALL)` (so the whitespace would be replaced by the match-all-dot and the asterisk for unspecified amount) and it would still find everything that was found before in addition to the new matches.

But of course I'm not Kotlin programmer so I have no clue whether this is much more complicated in Kotlin than in other languages. 😞 

> this is not urgent at the moment.

Well, this issue is open since 2018 so it's obviously not that urgent. 😆

**Comment by J-Jamet** [comment]
Haha, yes I'm reopening the debate because I'm redoing the real time search system with filters, so the regex are forced to adapt to the filters applied with the new model, that's why I bring it up. It wasn't necessarily clear but it allows me to keep track of the issues I looked at.

**Comment by alexanderadam** [comment]
I see. I changed my workflow now anyway since I'm since I started using KeePassDX.
So that on mobile devices I won't type more terms (like in the other KeePass clients) but I try to remember just to type _one_ term and then scroll and search manually through the list of results.

It's obviously much slower to find something but at least I'm not ending up without any results. :laughing:

**Comment by J-Jamet** [comment]
Okay, that's very interesting feedback. I didn't implement the Regex because I wanted to partition the developments but in relation to your usage, I'll look into it further so that I don't have any performance issues for the real-time filters.

(I also have to say that I've been doing a lot of work on the search and I'm getting a little tired of that feature. But at least it is now possible to search in the current group and filter most of the fields.)

**Comment by J-Jamet** [comment]
Now possible to manage regex since version 3.3.0

**Comment by alexanderadam** [comment]
> Now possible to manage regex since version 3.3.0.

I'm running the F-Droid build version 3.3.1 but it doesn't seem to work.
Should the search strings split by spaces per default or do I have to activate anything somewhere?

**Comment by J-Jamet** [comment]
It is the regex search that is implemented, you just have to activate it dynamically. Then you can use it to do your special searches as you said in a previous comment. (ie : _abc.*def_)

**Comment by alexanderadam** [comment]
> It is the regex search that is implemented, you just have to activate it dynamically.

How can I activate it dynamically?

> Then you can use it to do your special searches as you said in a previous comment. (ie : _abc.*def_)

I'm not quite sure whether we have a misunderstanding here. :laughing: 
I was not proposing that someone would like to type regular expressions on a mobile phone. I was just proposing that two words in a search  string, divided by a whitespace should match both. They shouldn't be kept as a single search token but rather as separate ones.

[What I wrote was](https://github.com/Kunzisoft/KeePassDX/issues/175#issuecomment-1029821725)

> a search string `"abc def"` would simply become the regex `Regex("abc.*def", IGNORE_CASE, DOT_MATCHES_ALL)` (so the whitespace would be replaced by the match-all-dot and the asterisk for unspecified amount) and it would still find everything that was found before in addition to the new matches.

Therefore I thought that every time I would type `"abc def"` KeePass could replace whitespaces with `.*`. So that the example string would look like `"abc.*def"`.
Then it could use this String to do a regexp search without having to activate something.

But I just learned [on StackOverflow](https://stackoverflow.com/questions/13911053/regular-expression-to-match-all-words-in-a-query-in-any-order) though that a match all regexp would even work more elegant: _independent_ from their position (I'm not very good with these lookahead statements).

Thus the regular expression could be created like this

1. the search string (i.e.  `"abc def"`) would be splitted by the whitespaces (:arrow_right: `["abc", "def"]`)
2. each string in the array would be surrounded by `(?=.*\b` and `\b)` ((:arrow_right:  `["(?=.*\babc\b)", "(?=.*\bdef\b)"]`)
3. concatenated again to a single string without(!) whitespaces inbetween (:arrow_right:  `"(?=.*\babc\b)(?=.*\bdef\b)"`)
4. prepended by `^` and appended by `.+` (:arrow_right:  `"^(?=.*\babc\b)(?=.*\bdef\b).+"`)

It might look cryptic but according to [this answer](https://stackoverflow.com/questions/13911053/regular-expression-to-match-all-words-in-a-query-in-any-order#answer-13911776) it will match a string independent from the order.

Thus, if your KeePass title is "`Onlinebanking (Superbank)`" you could search for `superbank online` and would still find the correct record.

**Comment by alexanderadam** [comment]
Hello @J-Jamet,

long time no see. 😆 
Could it be that this feature is broken now again?
It used to work but 4.1.7 doesn't seem to have that anymore.

**Comment by J-Jamet** [comment]
Maybe a regression, I did some refactoring and recovered code from an old commit, it may have been skipped. I'm putting the code back.

**Comment by J-Jamet** [comment]
In any case, the search needs to be redesigned and unit tests need to be added because there are issues with the auto searches.

**Comment by alexanderadam** [comment]
@J-Jamet thank you! You're the best! 🙏
