### ISSUE TITLE
Auto-fill not working at all

### ISSUE THREAD

**Issue by brianjmurrell** [Kunzisoft/KeePassDX#1751]
**Describe the bug**

On my Android phone, going to a log in form in Chrome prompts for Google Auto-fill instead of KeePassDX's.  Going to a form that has no account info in the Google Password database produces no kind of auto-fill at all.

**To Reproduce**

1. Go to any website that requires a login
2. Click on login item

**Expected behavior**

Should see KeePassDX auto-fill option

**KeePass Database**

 - Created with: KeePassXC
 - Version: 2.7.6
 - Location: NextCloud
 - File provider: `content://org.nextcloud.documents/document/<uuid/hash/etc>
 - Size: 82KB
 - Contains attachment: Don't know

**KeePassDX:**

 - Version: 4.0.5
 - Build: Play Store
 - Language: English

**Android:**

 - Device: LineageOS
 - Version: 20 (Android 13)

**Additional context**

 - Browser for Autofill: Chome version 120.0.6099.230

Autofill service on phone is set to KeePassDX form autofilling

Given the utter lack of any KeePassDX autofill functionality here I cannot help but think I have some kind of fundamental issue but I don't know what it is.

**Comment by glemco** [comment]
I think that's more of a problem with Chrome.. have you tried other browsers? It works out of the box on Firefox and on Cromite (a bromite's fork, both chromium based) can be enabled in the settings (password manager > enable native autofill).

**Comment by brianjmurrell** [comment]
It does seem to be working better than it was before.  I am still being plagued by #1665 though, as it seems others are also.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#web-browser

Without Play Service, only browsers with native Autofill work.
https://github.com/Kunzisoft/KeePassDX/issues/1665 is another issue
