### ISSUE TITLE
Bring back old layout

### ISSUE THREAD

**Issue by Offerel** [Kunzisoft/KeePassDX#1753]
**Is your feature request related to a problem? Please describe.**
This is not really a problem. Rather, I find the old layout more appealing than the new material layout.

**Describe the solution you'd like**
I would like to have an optional setting to be able to continue using the old layout.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by J-Jamet** [comment]
This isn't possible, as the old theme didn't respect the Material 3 color system, and has been specifically redesigned to meet these constraints: https://m3.material.io/styles/color/system/overview
