### ISSUE TITLE
Removing a file from recents list doesn't remove ⭐

### ISSUE THREAD

**Issue by Fry-kun** [Kunzisoft/KeePassDX#1755]
**Describe the bug**

KPDX attempts to open ⭐d DB even if it's not listed in the recents.

**To Reproduce**

1. Open a DB so it shows in recents
2. Make it ⭐d and remove it from recents
3. Close & reopen the app
4. The DB is still opened by default

**Expected behavior**

If the ⭐d DB is removed from recents, the default behavior on open should revert to showing list of recents.

**KeePass Database**

N/A

**KeePassDX:**

 - Version: 4.0.5
 - Build: Free
 - Language: English

**Android:**

N/A

**Additional context**

https://github.com/Kunzisoft/KeePassDX/discussions/1089#discussioncomment-8267180

In my case, I moved the DB file but forgot to apply the ⭐ to the new location.
* The error message was misleading for this case: "Access to file revoked by file manager"
* The full filename was not visible, so it was hard to figure out the app was trying to open the old file.

**Comment by J-Jamet** [comment]
I'll check, I thought I'd implemented it but there may be a regression here.

**Comment by casch-at** [comment]
Can confirm that bug.
