### ISSUE TITLE
How to disable tutorial educational hints?

### ISSUE THREAD

**Issue by jacklollz2** [Kunzisoft/KeePassDX#1762]
Every time I format my phones or reinstall this app in any way, I get these absolutely annoying popups telling me how to do things, with no way to disable.

**Comment by J-Jamet** [comment]
Wrong, you just don't know how to do it - that's different.

Way to disable : **Settings - Appearance - Educational hints**

If you export the parameters and import them, you won't be bothered anymore.
https://github.com/Kunzisoft/KeePassDX/wiki/Import-and-Export
