### ISSUE TITLE
[question] ProfileInstalled

### ISSUE THREAD

**Issue by m413w4r3** [Kunzisoft/KeePassDX#1763]
Hi, thank you for this nice project <3

I have a question regarding KeePassDX's private storage. I noticed that there is a file named **"ProfileInstalled**" present. 
This file seems to contain information about the package's last update time and the length of the profile file (_/data/misc/profile/cur/<package_name>primary.prof_).

I'm curious about the purpose of this file. Do you have any insights into why it exists and what its function is within KeePassDX?

**Comment by J-Jamet** [comment]
This is not a file created specifically with KeePassDX, it's a profile behavior for Android applications. Take a look at the AOSP project for more information.

**Comment by m413w4r3** [comment]
Ok thanks for the reference and thx again for your work 👍
