### ISSUE TITLE
Brief Password Visibility During Auto-Fill with KeePassDX Keyboard

### ISSUE THREAD

**Issue by maninthemiddle01** [Kunzisoft/KeePassDX#1765]
I've encountered an issue with the KeePassDX keyboard when auto-filling passwords into fields. The password is briefly visible (for about half a second) before it's obscured by the usual bullet points or asterisks. I believe this could be related to the delay in the password field masking the characters as they're entered.

**Steps to Reproduce:**
1. Open an app or website login page.
2. Use KeePassDX auto-fill feature or KeePassDX keyboard to input the password.
3. Observe that the password characters are briefly visible before being hidden.

**Expected Behavior:**
The password should be obscured immediately as each character is entered, with no delay that allows the characters to be visible.

**Actual Behavior:**
The password briefly flash on the screen, fully visible, before being obscured by bullet points or asterisks.

**Possible Solutions:**
- Could there be a setting that adjusts the visibility duration of passwords during auto-fill that I might have overlooked?
- Is there a way to reduce the input delay that causes this brief visibility?

**Additional Information:**
- KeePassDX Version: 4.0.5
- Android Version: LineageOs 20-20240207-NIGHTLY
- Affected Apps: mainly Browser

I understand the password is still secure, but I would prefer it to remain hidden throughout the input process for additional security.
Thank you for your time and for the great work :)

**Comment by J-Jamet** [comment]
This is not KeePassDX behavior. You said so yourself : I believe this could be related to the delay in the password field masking the characters as they're entered.

KeePassDX does not manage the visual behavior of the form to be filled in. And to my knowledge, the keyboard has no option to influence this behavior.

Contact the developers of the application that runs the form rendering engine: your "mainly browser"

**Comment by maninthemiddle01** [comment]
Thanks for the clarification. I understand that KeePassDX does not manage the form's visual behavior, but since the issue is observed when using the KeePassDX keyboard for auto-filling, might there be any scope for addressing how the keyboard dispatches input to ensure immediate masking? Any enhancements in the keyboard auto-fill functionality could potentially minimize this visibility window and improve user's security.
