### ISSUE TITLE
Creating a database without a key or password makes it imposible to unlock

### ISSUE THREAD

**Issue by kylian-002** [Kunzisoft/KeePassDX#1767]
**Describe the bug**

When creating a database and not setting any password or key, it successfully creates. Adding passwords works fine, but after locking, it becomes impossible to unlock it again. The "unlock" option remains greyed out unless you toggle one of the unlock methods, such as the password one. However, when leaving the password blank and not filling in any credentials, you receive the error message "Could not read credentials," even though nothing was initially set. I encountered this issue when I had to quickly save a few passwords and accounts without using a text file, only to later find that I couldn't unlock the database again.

**To Reproduce**

1. create a database,
2. do not set any security method
3. Press ok when it asks "Continue without encryption key"
4. Lock the database
5. open the created database
6. toggle the password option and leave the password blank
7. Press unlock

**Expected behavior**

Unlock the database even when no password is used

**KeePass Database**

 - Created with: GrapheneOS KeePassDX
 - Version: 4.0.5
 - Location: Local downloads folder
 - File provider (`content://com.android.providers.downloads.documents/document/7`)
 - Size: 2.17kB
 - Contains attachment: no

**KeePassDX:**

 - Version: 4.0.5
 - Build: Free
 - Language: English US
 -
**Android:**

 - Device: Pixel 7 Pro
 - Version: 14
 -  (Graphene OS)

**Comment by J-Jamet** [comment]
Settings - App settings - Allow no master key

**Comment by shalva97** [comment]
why is this so confusing? wasted like 20 mins on this

**Comment by J-Jamet** [comment]
Because basically a protected database has a password. Otherwise it's only for testing purposes, so it shouldn't even be an available option.

**Comment by J-Jamet** [comment]
And only pressing the validation button on the keyboard is enough if this setting is not activated.

**Comment by shalva97** [comment]
is not that a bit bad UX? my guess is that new users (including me) who will decide to try this app will just ignore the password. Also the app lets me do that, "continue without encryption key?", yes, why not. but then it unexpected that Unlock button is disabled. Only option here is to google stuff or ask AI for help

**Comment by J-Jamet** [comment]
Yes you are right, it is a minor UX problem, the setting has been added and the button disabled by default historically because users did not understand why they had the possibility to press the button without entering their password. I prefer to focus on the other topics until the app refactoring in version 5.0.0
