### ISSUE TITLE
error with the fingerprint reader and password

### ISSUE THREAD

**Issue by sdrev** [Kunzisoft/KeePassDX#1773]
Hello, I am a user of the application, first of all I would like to congratulate you for this great application and all the effort it entails.

I have changed my mobile phone (Xiaomi Mi 14) and when I enter the password I get the following error (attached image 1), in addition to that it does not allow the use of fingerprint, saying that "Enter the password and then click this button", even if the password is entered (attached image 2).

**Expected behavior**

I was hoping to unlock the file using my fingerprint

**KeePass Database**

 - Created with: Windows keepassxc 2.7
 - Version: 2
 - Location: [Remote file retrieved with GoogleDrive and local
 - Size: 7.94MB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4.0.5
 - Build: Free
 - Language:  Spanish

**Android:**

 - Device: Xiaomi 14
 - Version: 14 UKQ1.230804.001

**Additional context**

 - To open the file I use a 'key file'
 - I have tried reinstalling it from the play store
 - If I unlock the file without the fingerprint it works
 
1:
![Screenshot_2024-02-29-08-34-44-763_com kunzisoft keepass free jpg](https://github.com/Kunzisoft/KeePassDX/assets/9254573/c61302f6-8d03-4c51-bdbe-26c2c462ac0c)

2:
![Screenshot_2024-02-29-10-25-18-194_com kunzisoft keepass free jpg](https://github.com/Kunzisoft/KeePassDX/assets/9254573/66b570fe-a480-480c-9296-35aa4d96b908)

**Comment by J-Jamet** [comment]
Internal Keystore code indicates that the problem is due to the registration of the key in the KeyStore. Have you installed a custom ROM that doesn't have KeyStore write permissions?

**Comment by sdrev** [comment]
I don't think so, The operating system is the one that comes from the factory, the phone is new. I don't know if it could be Xiaomi's HyperOS system, the strange thing is that another application "Kpass"  does work with fingerprint.

**Comment by lbssousa** [comment]
I'm currently having the same problem with a new POCO F6 phone, with HyperOS 1.0.7.0.UNPMXM, Android 14 UKQ1.240116.001.

**Comment by lbssousa** [comment]
Nevermind. I've just rebooted my phone (after eventually disabling extended memory), and surprisingly that problem disappeared.
