### ISSUE TITLE
You need to remember your vault main credential if you use device unlock recognition

### ISSUE THREAD

**Issue by nollinvoyd** [Kunzisoft/KeePassDX#1774]
Samsung galaxy tab s5e

Everything was fine until yesterday.  I can login with the password, but when it comes to biometrics, I can't get beyond this

With "Device unlock link"

![keepass login message](https://github.com/Kunzisoft/KeePassDX/assets/20844322/1c3a8a2e-3da1-485e-9fb0-691856368c9d)

![20240228_115334](https://github.com/Kunzisoft/KeePassDX/assets/20844322/ef3a999a-4b89-41b6-acc1-07063f0c31f9)

"unavailable"?

![Screenshot_20240228-114057_KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/20844322/9014c0d1-55df-4ef8-b569-60f797bb8021)

I tried enabling this, then I couldn't login at all, even after I disabled it.  I had to uninstall and reinstall to get back in, but biometrics still not working.

![Screenshot_20240228-141227_KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/20844322/9d75f53c-0398-42f4-9487-34b7503e4686)

One other thing.  I can't edit this

![20240228_144853](https://github.com/Kunzisoft/KeePassDX/assets/20844322/3cf3aedf-9305-463f-9fe2-bb25411b7d06)

**KeePassDX:**

 - Version: 2.5.6
 - Build: Free]
 - Language: Engilsh

**Android:**

 - Device: Galaxy tab s5e

**Comment by shuvashish76** [comment]
Same heppened with me because my biometric scanner button is broken. Try with other apps (e.g. Aegis) that supports biometric & check if it works.

**Comment by nollinvoyd** [comment]
I have KeepassDX and Keepass2Android installed on both my Samsung phone and tablet.  

The only biometrics problem that I'm aware of with anything on both devices is with KeepassDX on my tablet.  No problem with Keepass2Android on the tablet.  I use the same credentials with all four.  

I do have biometrics enabled in the settings.   I also temporarily tried switching to "Device Credential Unlock" just to see if it would have any effect. 

![Screenshot_20240301_151454_KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/20844322/cac14dc9-94e8-48e8-9e5b-c496d5755b10)

I uninstalled/reinstalled it hoping that might set things right, but no.

I don't understand what "You need to remember your vault main credential if you use device unlock recognition" is supposed to do.  I thought it was just a matter of entering your password, and confirming biometrics going forward, but clicking "ok" on that notification prompts no further actions/optiions.  It just closes the notification popup.

Since KeepassDX is operating as expected on my phone, is there something I can use/ export from there to reset it?

**Comment by nollinvoyd** [comment]
> Seems to be a defect in your OS's biometric API.

Has there been any further progress on this issue?

Can you explain this "defect in your OS's biometric API"  How can it be dealt with?

**Comment by nollinvoyd** [comment]
Now it's also happening with my phone install

![Screenshot_20240310_140456_KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/20844322/a255d9eb-43b8-4753-af47-b9d4f3faffe8)

![Screenshot_20240311_141326_KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/20844322/e4a65393-8679-4e9f-8d31-51b576bde16b)

**Comment by J-Jamet** [comment]
> The only biometrics problem that I'm aware of with anything on both devices is with KeepassDX on my tablet. No problem with Keepass2Android on the tablet. I use the same credentials with all four.

KeePassDX and KeePass2Android don't use the same credential storage methods, KeePassDX uses a symmetrical key system in the Keystore which is very secure but some systems don't work with this method, you just can't enable biometrics.

> I don't understand what "You need to remember your vault main credential if you use device unlock recognition" is supposed to do.

It's just informative

> Since KeepassDX is operating as expected on my phone, is there something I can use/ export from there to reset it?

Nothing to reset, just the toggles.

> Has there been any further progress on this issue?

As far as I'm concerned, there's nothing really wrong with the KeePassDX code at this level, because it works with all other devices and uses the API of the phone or tablet.

> Can you explain this "defect in your OS's biometric API" How can it be dealt with?

You chose your device, so contacting the manufacturer who created the OS is a good start.

> Now it's also happening with my phone install

This is another problem: the .kdbx file is no longer accessible from the file provider.
