### ISSUE TITLE
Database does not auto lock itself after usieing it

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [Kunzisoft/KeePassDX#1777]
**Describe the bug**

Lock - Timeout settings does not work. The database stays open.
(The auto lock time is set to 30 sec.)

**To Reproduce**

1. Login in my browser in a random site
2. I chose my login username.
3. The database does not lock automatically 

**Expected behavior**

To close after the set 30 seconds.

**KeePassDX:**

 - Version: [4.0.5]
 - Build: 
 - Language: [e.g. ENG]

**Android:**

 - Device: ONEPLUS 
 - Version: 11

**Additional context**

 - Browser for Autofill: BRAVE

**Comment by hetszunyukapanyanyimonyok** [comment]
@cbiere Thanks for trying to help! KeepassDx does not ask for any permission on Android 11.(From FDroid)

**Comment by J-Jamet** [comment]
Strangely enough, this behavior works well on my test devices.
The time is approximate depending on the devices to save battery, so there could be several seconds of lag but should still work.

**Comment by hetszunyukapanyanyimonyok** [comment]
As @J-Jamet mentioned that it happens occasionally I thought about it and yes sometimes it works on current build sometimes not.

So I tested it:
1. Opening app from "desktop" and logging in. 
- Database closed itself after the set 30 sec 

2. Opening database from browser with magic-keyboard shortcut(long click space...) Logging in. 
- Database does NOT closes itself.

**Comment by hetszunyukapanyanyimonyok** [comment]
@J-Jamet Thanks for the answer, I will test it and report how did it work.

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/1467, will be fixed in version 1.4.0
