### ISSUE TITLE
Device Unlocking doesn't work anymore for me after upgrading LineageOS to the latest v21 (Android 14)

### ISSUE THREAD

**Issue by bobdig** [Kunzisoft/KeePassDX#1781]
**Describe the bug**

If I enter the password, I get an error message "internal keystore code: -1000 ..." but it opens and saves just fine.
![Screenshot_20240310-104518_KeePassDX](https://github.com/Kunzisoft/KeePassDX/assets/46788742/7791bb74-0de1-449b-ac13-812c242c4d86)
What I can not do is getting Device unlock to work anymore.

Also I noticed that the [wiki page](https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking) is broken.  
**To Reproduce**

**Expected behavior**

Open the database via thumbprint

**KeePass Database**

 - Created with: [KDBX3.1]
 - Version: [2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX:**

 - Version: [4.0.5]
 - Build: [Free]
 - Language: [English]

**Android:**

 - Device: [Google Pixel 4a]
 - Version: [LineageOS21]

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
It's a problem with your OS, the biometrics API doesn't seem to have access to the KeyStore anymore. Please report the problem to LineageOS.

**Comment by nutpantz** [comment]
Same issue fresh install pixel 8 pro i have two thumb prints and this app reports no biometric or device credential enrolled
Oem Google ROM Android 14

**Comment by nutpantz** [comment]
This is the factory Google factory ROM I am using on the flagship Google device. Pixel 8 pro. Android 14
And it fails 
My pixel 6 on Android 13 seems to work fine as I just tested it there.

I'm pretty sure it's not googles failure in this case

**Comment by nutpantz** [comment]
![Screenshot_20240815-081927](https://github.com/user-attachments/assets/6cdf29b2-6cb5-4d36-b0b2-26dda618499f)

**Comment by nutpantz** [comment]
![Screenshot_20240815-082321](https://github.com/user-attachments/assets/76a6809c-b4e9-47de-affa-c1e9f955ac6f)

**Comment by J-Jamet** [comment]
Simple question : what's your device unlock method and do you have a  fingerprint enrolled in your OS?

**Comment by nutpantz** [comment]
My device unlock method is fingerprint i have two fingerprints enrolled.

**Comment by J-Jamet** [comment]
In this case, I don't know, the Keystore must be in an unknown configuration, in any case I can't do anything from the app code.
