### ISSUE TITLE
Autofill not triggered in Brave Browser

### ISSUE THREAD

**Issue by deadcombo** [Kunzisoft/KeePassDX#1783]
**Describe the bug**

Autofill pop-ups are not triggered in Brave browser. The current URL is not detected either while using Magikeyboard.

**To Reproduce**

1. Download Brave browser
2. Click on any login field (such as github.com)
3. No autofill

**Expected behavior**

Autofill pops up

**KeePass Database**

 - Created with: Windows KeePass 4.1
 - Version: 2
 - Location: Local
 - File provider (`content://` URI): content://com.android.externalstorage.documents/document/primary
 - Size: 400KiB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4.0.5
 - Build: libre
 - Language: English

**Android:**

 - Device: Google Pixel 7 Pro
 - Version: 14 QPR2 GrapheneOS

**Additional context**

 - Browser for Autofill: Brave - Nightly 1.65.68, Chromium 122.0.6261.111

There is a related issue in the Brave tracker.
https://github.com/brave/brave-browser/issues/32925

**Comment by J-Jamet** [comment]
Brave refuses autofill and only works in compatibility mode, which means that if the Autofill accessibility service is not present because it uses Google services (as on Graphene OS), there can be no autofill.

https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#compatibility-mode

I can't do anything from KeePassDX. Use a browser with native autofill like DuckDuckGo browser.

**Comment by deadcombo** [comment]
Coincidentally a nightly release of Brave shortly after this got it working.

I had the #enable-autofill-virtual-view-structure flag set and 'Android
Providers' set on the subsequent menu. This yielded no result until now.
With this set autofill in Brave works just as well as in Vanadium.
I haven't followed the matter closely but judging from GrapheneOS chat I
think something changed upstream in regards to autofill.

#enable-show-autofill-signatures may be relevant as well if I understand
the wiki correctly.
My apologies for having missed the wiki page, thank you for replying.
