### ISSUE TITLE
Magikeyboard layout toggle

### ISSUE THREAD

**Issue by chadat23** [Kunzisoft/KeePassDX#179]
I pushed a button on the keyboard and it toggled so that the only available keys are the bottom row (change keyboards, lock the DB, backspace, and enter). Am I missing something or is there no way to get back to the full Magikeyboard keyboard?

**Comment by J-Jamet** [comment]
When only one row is available, it is simply that there is no key available in the keyboard, you must click on the key icon, reconnect and choose one available entry to copied. If you click on the key icon again, lock icon or delete the notification, it erases the existing entry in the keyboard.
