### ISSUE TITLE
'Sign in with KeepassDX' not appearing in many apps (e.g. Naked Wines, Dominos Pizza)

### ISSUE THREAD

**Issue by DrMopp** [Kunzisoft/KeePassDX#1790]
**Describe the bug**

'Sign in with KeepasDX' not activated for certain apps (e.g. Naked Wines, Dominos Pizza and others)

**To Reproduce**
Open  app, 
Tap Login button.  
No 'Login with KeepassDX' appears above keyboard

**Expected behavior**
Open  app, 
Tap Login button.  
'Login with KeepassDX' appears above keyboard

**KeePass Database**
 - Created with: Windows KeePass 2.56
 - Version: 2
 - Location: content://com,android,externalstorage.documents/primary:Documents
 - File provider 
 - Size: 170kB
 - Contains attachment: No

**KeePassDX:**
 - Version: 4.0.5
 - Build: Pro
 - Language: English

**Android:**
 - Device: Galaxy S24+
 - Version:  14

**Additional context**
   Samsung One UI v6.1

**Comment by DrMopp** [comment]
Thanks, checked Keepass2Droid and that is the same in the apps I mentioned either.  Doubt the developers of those apps will be interested.

**Comment by DrMopp** [comment]
I am using the UK and Ireland version.  Opening display prompts for postcode, ignore and tap 'login' top right.  No Login with KeepassDX prompt appears.

**Comment by mnisius** [comment]
@J-Jamet it's amazing that this bug is fixed but when does the new version release ? The last release was in November and this bug is a daily annoyer for every user out there... Sorry for complaining but it's really frustrating and made me think of switching to another app even tho I love keepassdx 🥲

**Comment by J-Jamet** [comment]
> but when does the new version release ? 

When I've completed the corrections for the current version. https://github.com/orgs/Kunzisoft/projects/4

> Sorry for complaining this and https://github.com/Kunzisoft/KeePassDX/issues/1802 are really frustrating and made me think of switching to another app even tho I love keepassdx 🥲

No need to threaten, just change the application if you wish. It's not a priority fix knowing that [Magikeyboard](https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard) offers a complete alternative solution. I'm not going to change the delivery process at the risk of completely breaking the app.

**Comment by mnisius** [comment]
@J-Jamet I apologize if this came out as a threat I was just annoyed at that day because of that bug. I also was not aware there will be a 4.0.6 and thought I have to wait for 4.10.0. So thank you for the release I'm happy to try it out!

**Comment by J-Jamet** [comment]
No worries, I hadn't necessarily planned the version 4.0.6, so it's relevant.
