### ISSUE TITLE
Random crash on database open

### ISSUE THREAD

**Issue by gza** [Kunzisoft/KeePassDX#1791]
**Describe the bug**

After enabling biometric open, opening database works few times then fail with error (see screenshot)

**To Reproduce**

1. install and use it few times
2. then this happen

![Screenshot_20240320-231111](https://github.com/Kunzisoft/KeePassDX/assets/878724/62e04afa-0470-41ae-af7e-b2fe84ddd52c)

when this issue starts, it becomes almost impossible to open the database

**Expected behavior**

Open with Password more than 10 times without issues

**KeePass Database**

 - Created with: KeepassXC Linux
 - Version: 2.7.7
 - Location: Synced with NextCloud
 - File provider (`content://` URI): ?????
 - Size: 197kb
 - Contains attachment:  Yes

**KeePassDX:**

 - Version: 4.0.5
 - Build: Free (F-droid)
 - Language: French

**Android:**

 - Device: Pixel 4a
 - Version: Android13
 - Original ROM : no custom, no boot unlock, no su or whatever hack.

**Additional context**

**Comment by gza** [comment]
I updated the issue because, at first it seemed related to fingerprint. But even after full app data flush and no biometric setup issue happen after few DB open.

**Comment by J-Jamet** [comment]
It seems to come from your file provider, which application do you use to open your file? (The URI is present in the previous screen when you display more information about the filename)

**Comment by gza** [comment]
You are right there is something strange here, url is `content://org.nextcloud.documents/document/xxxxx`

OK, I think I have an explanation : 
When one open a file in google's files app with Nextcloud shortcut on the menu, it will use a kind of Virtual Filesystem. So the app, will not talk to Android File API but with Nextcloud API.

Anyway, this does not seem to be a hard incompatibility (as it works from time to time) and Nextcloud sync is pretty much common use case. Can we consider this as a bug to be fixed ? or is it already identified somewhere (i haven't found obvious related bugs) ?

**Comment by J-Jamet** [comment]
What you call the VirtualFileSystem is the only method used in KeePassDX to access file contents. It's an interface contract, the storage access framework, which is standardized on Android. Most of the time it works fine when it's a local file, but many applications that provide files to synchronize provide a buggy file provider, all explained here : https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
Honestly, I can't do much better at this level except make an application that better handles synchronization with protocols that use specific file transfer APIs.

**Comment by gza** [comment]
Thank you for pointing me the fine doc.
