### ISSUE TITLE
Totally frozen after unlocking 

### ISSUE THREAD

**Issue by MercuryTangent** [Kunzisoft/KeePassDX#1795]
When I open the app I get the option to unlock with my fingerprint, but once I'm signed in I can't interact with anything. It's totally frozen.

**Comment by J-Jamet** [comment]
Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/1636
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-cant-i-press-the-buttons-on-keepassdx-its-like-its-frozen
