### ISSUE TITLE
Samsung Internet Autofill not working

### ISSUE THREAD

**Issue by CodersPlayground** [Kunzisoft/KeePassDX#1797]
Autofill in Samsung Internet browser on Android hasn't worked for a long time. I recently tested bitwarden and autofill does indeed work. Could we try make keepass autofill also work?

**Comment by J-Jamet** [comment]
Please be more precise about the versions of Samsung Internet Browser used, there's still work to be done on Autofill.

**Comment by J-Jamet** [comment]
In any case, the Samsung browser is not compatible with autofill. Please contact Samsung for further information.
