### ISSUE TITLE
Unlocking Vault zero bytes it instead of opening it

### ISSUE THREAD

**Issue by Oclair** [Kunzisoft/KeePassDX#1799]
I use Keepassdx on two android devices as I am now setting up the Grapheneos replacement of the Samsung phone.  On the Grapheneos phone I am using the F-Droid version of both Nextcloud and KeePassDX.  I have had absolutely no issues for a few days.  

Now unlocking my vault on my Grapheneos phone zero bites the file and returns the error message  **"open failed: ENOENT (no such file or directory)".**

Fortunately I have the vault open on my PC and have been editing entries to re write the vault to next cloud.

Note: The Google Play store on my Grapheneos phone was activated today before this new behavior started.

**To Reproduce**
1. Go to KeepassDX
2. Click on Open Existing vault
3. Enter Password
4. error displays:  "open failed: ENOENT (no such file or directory)"
5. file on Nextcloud server now has 0 bytes

**Expected behavior**
1. Go to KeepassDX
2. Click on Open Existing vault
3. Enter Password
4. opens vault
5. file on Nextcloud server has not had its content deleted by opening it on KeepassDX

**KeePass Database**
 - Created with: Windows KeePass XC 2.77
 - Version: [e.g. 2]
 - Location: Nextcloud 3.12.2
 - File provider (`content://` URI): Nextcloud server
 - Size: 644kB
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 405
 - Build: Libre
 - Language: English

**Android:**
 - Device: Pixel 7a running GrapheneOS
 - Version: 2024032100
 - Fdroid Version
 - Google Play services and app is running on device

**Comment by Oclair** [comment]
This bug is related to Nextcloud 3.12.2 client doing this behaviour

**Comment by gitch22** [comment]
THANK YOU! This was driving me crazy.

**Comment by nicolnt** [comment]
Fixed with latest Nexcloud app (3.28.2). I've just tested on my phone.

https://help.nextcloud.com/t/warning-nextcloud-android-client-version-3-28-1-deletes-user-data-revert-back-to-3-28-0-f-droid/187042/8
