### ISSUE TITLE
Keyfile forgotten when locking db

### ISSUE THREAD

**Issue by mase76** [Kunzisoft/KeePassDX#18]
Hi!
Since version 2.5.0.0beta3-libre from f-droid, the keyfile is forgotten when the db gets locked again. The keyfile checkbox isn't even checked then. I have to reselect the keyfile or go back to use the last db file.

**Comment by J-Jamet** [comment]
I'll look to solve the problem. ;)

**Comment by J-Jamet** [comment]
Will be ok in new release 2.5.0.0beta4 ;)

**Comment by mase76** [comment]
From time to time, the default database file or the keyfile is not found. I have to reopen them. Tested with 2.5.0.0beta4.

**Comment by J-Jamet** [comment]
Link to https://github.com/Kunzisoft/KeePassDX/issues/19

**Comment by J-Jamet** [comment]
For files not found, it marks an error message or is it just the opening that does not work?  Do you use a drive with sync ?

**Comment by mase76** [comment]
I get a file not found message.

**Comment by J-Jamet** [comment]
Ok, I found the problem, it's due to a permission exception. I'll manage them better. I close this ticket, I put the information in https://github.com/Kunzisoft/KeePassDX/issues/33
