### ISSUE TITLE
Username is not autofilled anymore

### ISSUE THREAD

**Issue by TheRealEiskaffee** [Kunzisoft/KeePassDX#1801]
**Describe the bug**
Hello,

The autofill for username and password doesnt work correctly. If i press on the username field it happend nothing. If i press on the password field then i can select the entry but if i select this one, it autofill the password field but not the username field. I test it on the edge and Chrome Browser. I can imagine that it comes because Google overwrites with their own password Manager i dont know but i dont use them. My Friend has the same problem. With the same Device.

**To Reproduce**

1. Go to a login page
2. Click on username field (noting happends)
3. Click on password field
4. Select a entry
5. See error

Normally i can select the entry and then it autofill the both fields.

**KeePass Database**

 - Created with: KeePassXC
 - Version: V2 KDBX 4.1
 - Location: Nextcloud app
 - File provider content://org.nextcloud.documents/document/7c33f3721f467384deb917067534e1a3%2F52
 - Size: 738kb
 - Contains attachment:  Yes

**KeePassDX:**

 - Version: 4.0.5
 - Build: free
 - Language: German

**Android:**

 - Device: Samsung Galaxy Note 10 Plus
 - Android 12

**Comment by J-Jamet** [comment]
I've just tested with github.com/login on a chrome with Android 12 and I have no problem. Please indicate at least the form that is causing the issue.
