### ISSUE TITLE
Username not taken over for new entry

### ISSUE THREAD

**Issue by schnillerman** [Kunzisoft/KeePassDX#1802]
**Describe the bug**

Username is not pre-filled when creating a new entry based on a login webpage

**To Reproduce**

- Have a login page open on (any) browser
- Fill in login info (user/pass)
- Be offered the "Save in KeePassDX" in keyboard pane and click it
- Create new entry ("+" button in KeePassDX)
- Have password filled in, but not username

**Expected behavior**

Have both username and password taken over from login page when creating new entry

**KeePass Database**

 - Created with: Android KeePassDX
 - Version: 2
 - Location: local
 - File provider: content://at.bitfire.davdroid.webdav/document/80
 - Size: 30 entries
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.5
 - Build: Free

**Android:**

 - Device: GalaxyS10e
 - Version: 12

**Additional context**

 - Browser for Autofill: Firefox 124.2.0 (Build #2016012559), 7a0e399c7b+
GV: 124.0.2-20240401114208
AS: 124.0

**Comment by J-Jamet** [comment]
Just checked with DuckDuckGo browser and fill.dev form and it works fine.
