### ISSUE TITLE
a security hole

### ISSUE THREAD

**Issue by wfhyu** [Kunzisoft/KeePassDX#1805]
when using kreepass. for Android 4.0.5
if I make à copy of password I see the password in the clipboard even after closing  keepass. So it can be dangers.
password should be cleared.

**To Reproduce**

**Expected behavior**

**KeePass Database**

 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider (`content://` URI): [e.g. `content://com.google.android.apps.docs.storage/5`]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android:**

 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
It's your system that keeps track of clipbloard items, a dialog box explains this in KeePassDX and you have to accept the risks, which you have done. To deactivate the feature, go to  Settings -> Form filling -> Clipboard trust

https://github.com/Kunzisoft/KeePassDX/wiki/Clipboard
