### ISSUE TITLE
KeepassDX doesn't open my .kdbx file

### ISSUE THREAD

**Issue by Zarvis12** [Kunzisoft/KeePassDX#1808]
The KeepassDX app closes the .kdbx file after opening it

I try to open the .kdbx file by entering the password but it returns to the password screen again or it just gets stuck loading. It briefly shows me the groups and passwords inside it and returns to the master password screen.

Tried to open the kdbx file with Keepass2Android app and it opens it just fine. 
Also tried to open the file in the Samsung Galaxy Tab S8 on the KeepassDX app and it opens.

**To Reproduce**

https://github.com/Kunzisoft/KeePassDX/assets/36318260/0b5a36ec-3480-4349-ab16-313590a79ebd

**Additional information**

Previous I used the biometric unlocking to unlock the .kdbx (worked fine) and now with this bug/crash happening I removed it, to see if it works, but it didn't.

**Expected behavior**

I expect to open the database and access my passwords stored in there

**KeePass Database**

 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: on Internal storage
 - File provider - content://com.android.externalstorage.documents/document/primary:Passwords - 2022.kdbx
 - Size: 33.20kb
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.5
 - Build: Free
 - Language: English

**Android:**

 - Device: Samsung F23
 - Version: 14; OneUI 6.0

**Comment by J-Jamet** [comment]
I see two possible problems: 
- Either the system detects a foreground service and kills it immediately for no reason, check that you don't have permissions overridden by the OS.
- Or you've set a timeout somewhere around zero

**Comment by Zarvis12** [comment]
> I see several possible problems:
> 
> * Either the system detects a foreground service and kills it immediately for no reason, check that you don't have permissions overridden by the OS.
> * Or you've set a timeout somewhere around zero
> * Your database is badly formatted. Try exporting it in XML and then re-importing it from a KeePass computer program.

Thanks bro, I have recently installed an app called "Regain" to minimise my phone usage, one of its features is it blocks the notifications and only let's them access at particular hours of the day. It blocked the KeepassDX notifications so the app was not working. Now I have Whitelisted the app, the app is up and working.

**Comment by Zarvis12** [comment]
Resolved
