### ISSUE TITLE
Fingerprint problem on Oreo, after every reboot

### ISSUE THREAD

**Issue by ShiroiKuma0** [Kunzisoft/KeePassDX#181]
- Error : Failed to delete entry: com.kunzisoft.keepass.fingerprint.key

Fingerprint only works when Keepass DX is newly setup. It will open the DB. Then after a reboot: the error: Failed to delete entry: com.kunzisoft.keepass.fingerprint.key
Similar to issue: https://github.com/Kunzisoft/KeePassDX/issues/127

Version: 2.5.0.0beta17-libre and also 2.5.0.0beta17-pro
Device: Samsung Galaxy Note 9
System: Oreo 8.1

It can only be remedied by full uninstall, then removing all fingerprints from device - then setting up fingerprints anew and installing the app.

What's the problem?

**Comment by ShiroiKuma0** [comment]
As a workaround, can I delete the key manually? Where is it? I tried deleting the ones in /data/misc/keystore/user_0/ — no effect. 

Deleting it manually, at least one wouldn't be forced to uninstall / reinstall the app and remove fingerprints and set them up anew.

**Comment by ShiroiKuma0** [comment]
I can't, because it gives the same error: Failed to delete entry: com.kunzisoft.keepass.fingerprint.key

I need to physically delete it, but can't find what to delete.

**Comment by ShiroiKuma0** [comment]
Yes, once I restart — always this error.

**Comment by J-Jamet** [comment]
OK, good to know. May be useful if other people have the problem.

**Comment by hughwilliams94** [comment]
I have had this problem, whilst backing up and restoring from a TWRP nandroid backup after a failed rom flashing, it is combined with the fact that the app somehow seems to have converted itself to a system app i.e. I can't uninstall it via android settings. The above workaround did not work.

**Comment by hughwilliams94** [comment]
Just to add to my comment above. My entire credential system went pretty haywire after restoring from nandroid so I doubt this is a KeepassDX issue. I solved the problem by cleansing all keepass related files from the device including the keystore file. This was not straight forward but seems to have worked.

**Comment by Boggart** [comment]
I had this problem after restoring a twrp data backup, finally fixed it by deleting the keystore file for keepass from "/data/misc/keystore/user_0/". (search for the one with keepass in it's jumbled name)

**Comment by J-Jamet** [comment]
the code has been improved and other tickets have been opened on the subject. I close this one.
