### ISSUE TITLE
It is recommended to add a default field "Package Name" and optimize the novice guidance function

### ISSUE THREAD

**Issue by nichousha123** [Kunzisoft/KeePassDX#1818]
Google Translate

A feature suggestion:
        It is recommended to add a default field "Package Name" in "Add Entry", please see the screenshot.

A novice guide optimization suggestion:
         Add instructions to guide new users to fill in the relevant "Website" and APP "Package Name" when adding their account and password. For example, screenshot like this

Reason for adding: 
         I have been using this client for about 2 months, and I suddenly realized yesterday that I have to add the account URL and app Package Name so that the auto-fill function can be used, or the changed project can be automatically identified and located after switching the keyboard. For example, Facebook's Package Name field and official website are unique in the world and are not subject to language restrictions. For example, if the stored account name uses the Chinese "脸谱", it will not be recognized and cannot be automatically filled. It can be used if the name is changed to "Facebook".

The steps before yesterday were copy➽paste, copy➽paste, and clear the clipboard😂

I hope that these two suggestions of mine can be added to the next version. It is very necessary.

Finally I wish you a happy life

![Screenshot_20240507_133432](https://github.com/Kunzisoft/KeePassDX/assets/147991448/d0357e15-7843-4d8e-8705-90b2bd21ffb0)

**Comment by shuvashish76** [comment]
> Add instructions to guide new users to fill in the relevant "Website" and APP "Package Name" when adding their account and password.

Already available on wiki https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#application
