### ISSUE TITLE
I'm guessing I need to uninstall the Google Play version First?

### ISSUE THREAD

**Issue by leowankerddd** [Kunzisoft/KeePassDX#1819]
I tried upgrading the installed version of keepass DX which came from the Google Play app store and I just tried to install or upgrade it with the version from GitHub. Would I be correct and assuming that the error that I got is pertaining to the fact that I need to remove the Google Play version in order to install the GitHub version?

If I do what happens to automatic updates?

**Comment by deepu2** [comment]
You have to update the app yourself from Github or from something like Obtainium if you go this route. You can also try using f-droid.

**Comment by leowankerddd** [comment]
OK. Not a big deal as this app is not updated as frequently as some of my other apps in the Google Play app store. So long as the app works i'm not very concerned.

Thank you.
