### ISSUE TITLE
Entry selected through the app is not available to Magikeyboard

### ISSUE THREAD

**Issue by juwancase** [Kunzisoft/KeePassDX#182]
When I open an entry through the app, I figured the entry would be available via Magikeyboard. But the entry is only available after I unlock database (through the keyboard) and select the entry again.
It seems like Magikeyboard is not integrated closely to the app.

In Keepass2Android (K2A), after an entry is selected, there is a (optional) notification that the entry is available through its keyboard. Then I go back to browser or some other apps, switch keyboard and enter credentials (through K2A's keyboard).

In this app, the flow is different. I need to switch to Magikeyboard first, unlock database, select entry, and finally enter credentials.

Having to switch the keyboard first can be confusing for first-time users, especially who used K2A before.

As they are not integrated, locking the db through the app doesn't lock the Magikeyboard. This can be partially resolved through "Timeout to clear the keyboard entry" [feature](https://github.com/Kunzisoft/KeePassDX/issues/141). I still expect locking one should lock the other.

**Comment by J-Jamet** [comment]
The magikeybard is still in development. I can add this flow as a parameter to add the selected entry at any time.
I also need to add a session to not add the credentials each time.
