### ISSUE TITLE
Matching against domain goes too far

### ISSUE THREAD

**Issue by cbiere** [Kunzisoft/KeePassDX#1820]
When the setting "Subdomain search" is disabled, entries are suggested that match only the last part of the domain name.

**To Reproduce**

1. Add an entry to the database with the URL https://box.com/ 
2. Add an entry to the database with the URL https://dropbox.com/
3. Browse to https://account.box.com/login
4. Enter a email address as username
5. Use autofill with KeePassDX and see that both dropbox and box are suggested, even though dropbox.com should clearly not match box.com and this is even on account.box.com.

**Expected behavior**

An entry with https://box.com might match any subdomain like example.box.com but not a domain that just has box.com at the end. While enabling the "Subdomain search" setting prevents this from happening, there should be no match because these domains are completely unrelated and it only benefits phishing.

**KeePass Database**

Irrelevant.

**KeePassDX:**

 - Version: 4.0.6
 - Build: Free
 - Language: en

**Android:**

 - Device: sweet
 - Version: 14

**Comment by SuperITMan** [comment]
Same issue here, the autofill provides wrong entries for the following examples :
- 192.168.0.1:
  - 192.168.0.10 entries 
  - 192.168.0.11 entries
  - 192.168.0.1 entries
- mydomain.com:
  - sub1.mydomain.com entries
  - sub2.mydomain.com entries
  - mydomain.com entries

**Comment by J-Jamet** [comment]
A new algorithm will be implemented in version 4.1.0.
Same as https://github.com/Kunzisoft/KeePassDX/issues/1105

**Comment by J-Jamet** [comment]
I've just figured out what's wrong, I've tested it but I don't know why, the SearchHelper line contains \\\ that have been added line https://github.com/Kunzisoft/KeePassDX/blob/ada8f74e2c4f2ac44f96d546b890fd1ab660a0a6/database/src/main/java/com/kunzisoft/keepass/database/search/SearchHelper.kt#L157
Maybe an error of inattention before making the commit but when I remove them it works fine.

**Comment by J-Jamet** [comment]
I've just done the test again and there's no problem. There is no sub-domain to the github login https://github.com/login , I have two entries with URL https://github.com and github.com and both are recognized.

**Comment by J-Jamet** [comment]
I also made sure that it worked properly with https://dropbox.com/ and https://account.box.com/login

**Comment by J-Jamet** [comment]
Indeed, but that's another problem. The resolution of the current issue respects the constraints you put in the first description.

Can you open another dedicated issue for this? Currently the recognition system only does basic string checks without real URL formatting, I have to transform the string in this case and I'm afraid it will slow down the search for many entries. I'll think about it and try to find a solution to also recognize IPs and port numbers.
