### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Kunzisoft/KeePassDX#1821]
On the latest APK, my scanner reports:

```
! repo/com.kunzisoft.keepass.free_129.apk declares intent-filter(s): android.view.InputMethod
! repo/com.kunzisoft.keepass.free_129.apk declares sensitive permission(s): android.permission.QUERY_ALL_PACKAGES
! repo/com.kunzisoft.keepass.free_129.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Can those please be clarified? I assume `InputMethod` is needed for auto-type. For `QUERY_ALL_PACKAGES` I found #996 which is still open, so I assume the reason given there („used to open applications directly from their applicationId from an "AndroidApp" field“) still holds true?

As for `DEPENDENCY_INFO_BLOCK`, this can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by IzzySoft** [comment]
PS: with KeePassDX being [available at IzzyOnDroid](https://apt.izzysoft.de/packages/com.kunzisoft.keepass.free/), maybe you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there, next to the other three? :wink:

**Comment by J-Jamet** [comment]
I haven't changed the permissions since the last version.

> Can those please be clarified? I assume InputMethod is needed for auto-type. For QUERY_ALL_PACKAGES I found https://github.com/Kunzisoft/KeePassDX/issues/996 which is still open, so I assume the reason given there („used to open applications directly from their applicationId from an "AndroidApp" field“) still holds true?

Yes indeed

> As for DEPENDENCY_INFO_BLOCK, this can easily be avoided:

I'll take a look.

**Comment by IzzySoft** [comment]
> I haven't changed the permissions since the last version.

Probably not – but i have extended my scanners since :wink: Details are outlined here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks)

> Yes indeed

Thanks for confirming! I've put that to your app's "green list" with the explanation added:

![image](https://github.com/Kunzisoft/KeePassDX/assets/6781438/189e8281-067c-4296-b568-6bb798faa127)

> I'll take a look.

Thanks! Excluding it for the APK would suffice, in case you think you'll need it for the AAB to upload to Google Play.

That said: Thanks a lot for maintaining your app – I'm one of your happy "users" myself!

**Comment by shuvashish76** [comment]
> I assume `InputMethod` is needed for auto-type.

Auto-type feature of [Autofill service](https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill) feature only not [Magikeyboard](https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard) right? Or required for both?

**Comment by J-Jamet** [comment]
@shuvashish76 android.view.InputMethod  is the Magikeyboard declaration

**Comment by shuvashish76** [comment]
You can close the issue now.
BTW @J-Jamet what do you think about updating wiki/FAQs with explanations for each of the permissions/intents used by KPDX just for transparency?

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#what-are-the-permissions-used-in-keepassdx

**Comment by shuvashish76** [comment]
Permissions are already hyperlinked if you click on "Permissions" from [IzzyOnDroid page of KPDX](https://apt.izzysoft.de/fdroid/index/apk/com.kunzisoft.keepass.free).
Updated the wiki with link to IzzySoft's [article](https://android.izzysoft.de/applists/perms) as he has done really great job by compiling all the sources to a single list.
