### ISSUE TITLE
"No StrongBox available", Biometric-Authentication not working

### ISSUE THREAD

**Issue by NitroxydeX** [Kunzisoft/KeePassDX#1824]
**Describe the bug**

I currently have the problem that I can't unlock my KeePass-Database using Biometric features. Getting different errors on different inputs.

**To Reproduce**

1. Open Database
2. Clicking into the password field generates a popup "No StrongBox available"
3. Trying to press the Biometric button results in "Please type in your password first before pressing this button"

**Expected behavior**

Working App/Biometrics again

**KeePass Database**

 - Created with: Windows KeePass 2.6.6
 - Version: 2
 - Location: Remote file retrieved with Nextcloud app
 - File provider (`content://` URI): content://org.nextcloud.documents
 - Size: 269kB
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.6
 - Build: Free
 - Language: German

**Android:**

 - Device: Samsung Galaxy S24 Ultra
 - Version: Android 14, OneUi 6.1

**Additional context**

Could be related to the latest update of KeePassDX or the latest Android May Security Patch

Already tried to delete cache, delete app-data and reinstalled the app through PlayStore.

**Comment by J-Jamet** [comment]
"No StrongBox available" is not a KeePassDX message. Maybe the biometric API on your devive is broken or the keystore is not available.

**Comment by NitroxydeX** [comment]
The StrongBox message appears when clicking or typing my password in the password field in KeePassDX. So this shouldn't be related to the biometric api at all? Besides that: all other apps have no problem with biometric features.

Is the keystore related to KeePassDX?

**Comment by J-Jamet** [comment]
[What interests me is that StrongBox is an iOS application, so I don't see what a message like this has to do with it.](https://docs.samsungknox.com/admin/fundamentals/whitepaper/samsung-knox-for-android/core-platform-security/knox-vault/)

https://developer.android.com/privacy-and-security/keystore

Looks like another Samsung Keystore bug, they're really not good at following the API rules. https://github.com/Kunzisoft/KeePassDX/issues/1269#issuecomment-1075449893

**Comment by NitroxydeX** [comment]
After reading through the whitepaper and the comments in other issues related to Samsung I tried to give it a shot with deleting all biometric data and re-adding it.

Works for now. Maybe it break again with the next Samsung Patch.

**Comment by arinanto** [comment]
> After reading through the whitepaper and the comments in other issues related to Samsung I tried to give it a shot with deleting all biometric data and re-adding it.
> 
> Works for now. Maybe it break again with the next Samsung Patch.

Sorry for bumping up this closed issue.

That said, is there no any other way than clearing biometric data? All my other apps are working fine. I use Aegis for OTP and other banking and payment apps that use biometrics. They all work, just KeePassDX complaining about StongBox. Clearing this means I have to reconfigure all those apps.

I'm not saying it's KeePassDX's fault though. Just trying to find any other workaround since I really don't want to reconfigure those other apps which are working fine.

**Comment by NitroxydeX** [comment]
> That said, is there no any other way than clearing biometric data? 

A simple phone reboot fixes the problem atm.
The broken strongbox should trigger an automatic reboot by Samsungs protection, but the trigger event is never fired. So you need to manually restart.

**Comment by arinanto** [comment]
> > That said, is there no any other way than clearing biometric data? 
> 
> A simple phone reboot fixes the problem atm.
> The broken strongbox should trigger an automatic reboot by Samsungs protection, but the trigger event is never fired. So you need to manually restart.
> 

Ah, ok. I guess that's why it suddenly fixed itself. I'm doing reboot for other reasons. Thanks, I'll keep this in mind next time it happens again.

**Comment by AntonyARHS** [comment]
"The broken strongbox **should trigger an automatic reboot by Samsungs protection**. So you need to manually restart."

Could you share a link of the documentation mentioning this expected behaviour plz?
