### ISSUE TITLE
regression in 4.0.6: app freezes opening file 

### ISSUE THREAD

**Issue by goodevilgenius** [Kunzisoft/KeePassDX#1829]
****Describe** the bug**

Starting with the newest version, attempting to open a file causes the app to freeze when entering password.

**To Reproduce**

1. Open app
2. Open kbdx file
3. Attempt to enter password
4. App becomes unresponsive

**Expected behavior**

Should be able to enter password (or read fingerprint)

**KeePass Database**

 - Created with: Tested with a new database created in KeepassDX, and my previously functioning file created in KeepassXC
 - Version: 2
 - Location: [e.g. Remote file retrieved with GDrive app]
 - File provider: tried with both local file and stored in Nextcloud
 - Size: Multiple sizes
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.0.6
 - Build: F-Droid
 - Language: English

**Android:**

 - Device: Samsung GalaxyS10e
 - Version: 12

**Additional context**

 - Browser for Autofill: Firefox

Saw behavior both with using auto fill, and opening app directly. 

Also cleared app data and created new file, and still saw this bug.

**Comment by goodevilgenius** [comment]
Additional information: this seems to only happen if biometric unlocking is enabled, even if it hasn't been set for a particular file. 

Also, I mistakenly believed this was only in the latest version, because it was a recent change. However, I tried downgrading and the issue persisted, until I cleared app data and didn't enable biometric unlocking. 

So, it seems to be related to a change in that, rather than the app specifically.

**Comment by J-Jamet** [comment]
This is not a KeePassDX update regression. The problem has been reported on some Samsung devices (specifically on S10). The Keystore on these devices doesn't seem to be handled properly, try to delete a biometric fingerprint and put it back.

Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1269
https://github.com/Kunzisoft/KeePassDX/issues/1269#issuecomment-1075449893

**Comment by goodevilgenius** [comment]
> The Keystore on these devices doesn't seem to be handled properly, try to delete a biometric fingerprint and put it back.

Interesting. Thanks for this. I wonder what changed recently that this suddenly became an issue for me when I've been using it for years without problem.

I'll give this a try.

**Comment by goodevilgenius** [comment]
> Try to delete a biometric fingerprint and put it back.

Thanks for the suggestion. Unfortunately, that didn't help at all. I tried deleting all my fingerprints, and then putting them back in. Once I re-enabled biometrics in KeepassDX settings, it freezes up.

Bummer that Samsung screwed this up, and I can't use it anymore.

**Comment by J-Jamet** [comment]
Maybe a reboot is the solution? https://github.com/Kunzisoft/KeePassDX/issues/1269#issuecomment-1115339395

**Comment by goodevilgenius** [comment]
> Maybe a reboot is the solution? 

Of course that's it. 😆

Thank you. Working with fingerprint again. If it stops working again in six months, I guess I'll know what to do.
