### ISSUE TITLE
Turn the mobile phone installed with KeepassdX into a hardware password manager

### ISSUE THREAD

**Issue by ChrisFerebee** [Kunzisoft/KeePassDX#1834]
My idea is to simulate the Type-C of Android as a computer keyboard interface to enter a password on the computer.

Or send serial data through Type-C. If there is an external hardware device, you will read the serial data and simulate the keyboard interface, and enter the password data into the computer.

The origin of this idea is that I think good Android phones are safer to a certain extent than a computer (such as Pixel+Grapheneos).

In order to prevent the $ 5 wrench attack, key files are needed. Many Linux full encryption only supports the use of passwords and does not support the use of key files. Even if there are key files, it is also a problem to destroy key files in time in emergency situations.

And APPs such as DURESS, SENTRY, WASTED can erase the entire phone in emergency, so that password information can be destroyed in time.

Of course, this is just an immature idea, and it seems to deviate from the positioning of a software password manager, so this is just a suggestion.

**Comment by J-Jamet** [comment]
Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/80
