### ISSUE TITLE
Add configurable timeout for cloud storage (Google Drive)

### ISSUE THREAD

**Issue by JasonKeirstead** [Kunzisoft/KeePassDX#1837]
I use Google Drive as my storage for KeePassDX.

When I have a poor internet connection, KeePass hangs for a very long time trying to download the database when opening. Sometimes, multiple minutes.

This gets to be rather frustrating when I know no changes have been made to the database in a long time.

I wish one could set a timeout after which it would just use the local cached copy of the data.

**Comment by superuser-miguel** [comment]
Since you know you often times have a bad Internet connection, have you considered a local copy of the DB ?

**Comment by J-Jamet** [comment]
KeePassDX doesn't manage download times, it simply opens data through stream channels. Upload your file in advance to Google Drive if you want to have access to it.
