### ISSUE TITLE
Incorrect backup copies

### ISSUE THREAD

**Issue by anrosci** [Kunzisoft/KeePassDX#1838]
**Describe the bug**

on dropbox sometimes backup copies are created with the description conflycted copy and when the app is opened the information is not read because the source file is not updated

**To Reproduce**

**Expected behavior**

**KeePass Database**

 
 - Location: dropbox
 - Size: 53 kb
 - Contains attachment: no

**KeePassDX:**

 - Version: 4.0.6
 - Build: free
 - Language: italiano

**Android:**

 - Device: Honor x7a
 - Version: android 12

**Comment by J-Jamet** [comment]
"On Dropbox" That's it. Now you can open a ticket directly related to the Dropbox application. This is not a problem with KeePassDX. 😉
