### ISSUE TITLE
It asks for some unnecessary Permissions

### ISSUE THREAD

**Issue by lokkyo** [Kunzisoft/KeePassDX#1839]
for example, recording audio.
the problem is this permission isn't shown on F-droid for people to see and then give them the opportunity to decide whether or not to trust or download the app. 

I like the effort into building this android app and would've even appreciated it more if honesty was clear when it comes to asking for many permissions that aren't related to the very purpose of the goal of the app. However, we are left to trust this only open source app and it's taking advantage of the users because they know users don't have many choices to begin with. 

again thanks for allocating your time and expertise to make the app available for free and open source

**Comment by J-Jamet** [comment]
The application does not ask to record the audio. You must be mistaken or have downloaded a trojan.
