### ISSUE TITLE
Yubikey does not work

### ISSUE THREAD

**Issue by strowk** [Kunzisoft/KeePassDX#1841]
**Describe the bug**
Creating new vault with yubikey shows error.

**To Reproduce**

1. Create new vault
2. Select hardware key and yubikey challenge
3. When promted either connect by NFC or plug key in usb (for usb system confirmation is needed)

**Expected behavior**
Create new db accessible by yubikey.

**KeePassDX:**

 - Version: 4.0.6
 - Build: Free
 - Language: English 

**Android:**

 - Device: Galaxy s9
 - Version: 10

**Additional context**

Installed Yubikey driver as promted. Key is default, no changes in it. Tried both Slot 1 and 2, but it never gets to the point of actually pressing yubikey button, so it probably does not matter.
Errors mention something about configuration that is not explained anywhere I could find.

Same key works OK in github 2FA (same phone, used NFC). Tried another key with KeePassDX, same result.

![Screenshot_20240605-051746_Key Driver](https://github.com/Kunzisoft/KeePassDX/assets/25692644/8ea40c7b-6151-4074-bc74-f6ca82957728)
![Screenshot_20240605-051301_Key Driver](https://github.com/Kunzisoft/KeePassDX/assets/25692644/75c19a2c-0d8a-40c9-8702-b5342a77d40c)

**Comment by J-Jamet** [comment]
You're on the wrong project: https://gitlab.com/kunzisoft/android-hardware-key-driver

Check that your key has been set up with the challenge response and that it works with KeePassXC on your PC, it's not the same protocol as opening a 2FA account.

https://www.youtube.com/watch?v=r6Qe9Z-kOH0
