### ISSUE TITLE
"no biometric or device credential is enrolled" using Keypass DX on Samsung Galaxy Tab S9

### ISSUE THREAD

**Issue by stevecoh1** [Kunzisoft/KeePassDX#1843]
1**Describe the bug**

Although I have registered my face in the Tablet's Biometric settings, Keepass DX always gives the "no biometric or device credential is enrolled" message. 

**To Reproduce**

1. Start keepass dx and try to open database
2. See error

**Expected behavior**

Database is unlocked and opened without needing to type password.

**KeePass Database**

 - Created with: [keepassx and opened/added to/changed by several other apps]
 - Version: [4.0.6]
 - Location: [dropbox]
 - 1
 - Size: [e.g. 55KB]
 - Contains attachment: [No]

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android:**

 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
KeePassDX requires level 3 security biometrics. If facial recognition is not recognized by your device's API as a sufficient security biometric, it will not be recognized by the application.
