### ISSUE TITLE
In-app Shortcut to switch TO Magikeyboard 

### ISSUE THREAD

**Issue by benyjr** [Kunzisoft/KeePassDX#1845]
Switching to the Magikeyboard takes too many keystrokes and needs to be as smooth as the process of switching back. 

**Describe the solution you'd like**
A shortcut to switch directly to Magikeyboard when viewing an entry would be a great addition. 

Perhaps in the opposite corner from the lock icon.

**Comment by J-Jamet** [comment]
Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/311
Linked : https://github.com/Kunzisoft/KeePassDX/issues/365
