### ISSUE TITLE
In addition to fingerprint unlocking, add a master key verification function every 3-7 days.

### ISSUE THREAD

**Issue by nichousha123** [Kunzisoft/KeePassDX#1846]
The following content is translated by Google

My encryption scheme:
Password + key file + fingerprint unlock

Detailed description of suggestions:
I use fingerprint unlock every time, which is very convenient, but the master key setting is a bit complicated. I will choose to enter the master key from time to time to remind myself not to forget. It would be great if there was a "master key reminder verification function". After the fingerprint unlock is successful, enter the database. 3 days have passed since the last time the database was opened (the interval is 3-7 days, which can be customized by the user or decided by you. The start time is the last time the database was opened.)

Why is there this suggestion:
1: My Android phone is set to fingerprint unlock. For security reasons, the manufacturer prompts me to enter the digital master key every 3 days.

2: Signal branch Molly-FOSS client, I set the pin code and fingerprint, and every time I open it with fingerprint unlocking, it reminds me to enter the pin code every 3-7 days

So I wonder if keepassDX can add this function?

Looking forward to your reply, thank you
![2024061514470800](https://github.com/Kunzisoft/KeePassDX/assets/147991448/7b4b1234-fb73-41fb-8f4e-d9d2a625a3a6)

**Comment by J-Jamet** [comment]
Already here : https://github.com/Kunzisoft/KeePassDX/wiki/Device-Unlocking#temporary-encrypted-key-memory
