### ISSUE TITLE
I can't open my database on version 4.0.7

### ISSUE THREAD

**Issue by vivadavid** [Kunzisoft/KeePassDX#1848]
**Describe the bug**

I can't open my database.

**To Reproduce**

1. I use my fingerprint or my password to open my database.
2. After some short processing, nothing happens.

**KeePass Database**

 - Created with: Windows KeePass.
 - Version: 2.57 (x64).
 - Location: local.
 - Size:  half a megabyte.
 - Contains attachment: Yes.

**KeePassDX:**

 - Version: 4.0.7.
 - Build: Libre.
 - Language: Spanish.

**Android:**

 - Device: Xiaomi Mi 9T Pro.
 - Version: Android 11.

**Additional context**

After uninstalling 4.0.7 and installing again 4.0.6, I can open my database.

**Comment by Denio-7** [comment]
I second this. All is the same.
Android 9, MIUI Chinese stock, Redmi Note 7 Pro

**Comment by jjo21631** [comment]
Same here. Had to load old version. Play Store version fails, Free fails and Libre fails.

**Comment by J-Jamet** [comment]
@jjo21631 What is your device?

I'll have to find out what the problem is, as I'd tested several versions of Android with no problems.

**Comment by SanskritFritz** [comment]
LineageOS 18.1 (Android 11) here on Galaxy S7. Same problem. I see a pattern here, we use a very old version of Android.

**Comment by jjo21631** [comment]
> @jjo21631 What is your device?
> 
OnePlus N10 5G running Android 11

**Comment by dasima4396** [comment]
Same here!Android 12 huawei.Have to go back to 4.0.6 for it to work

**Comment by nichousha123** [comment]
> Same here!Android 10 huawei.Have to go back to 4.0.6 for it to work And when I put the same database and same version app on my other phone which is android13,everything's normal again. It does have something to do with the Android version

The same 4.0.7 version installation package was installed on two mobile phones.
The first one is currently in use: vivo x60, Android 11, and the database cannot be opened
The second old phone: Huawei nova2, Android 8, everything is normal

**Comment by J-Jamet** [comment]
Thanks @SanskritFritz , it's very useful.

```
06-18 08:40:17.631 E/AndroidRuntime(439): Process: com.kunzisoft.keepass.libre, PID: 439
06-18 08:40:17.631 E/AndroidRuntime(439): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kunzisoft.keepass.libre/com.kunzisoft.keepass.activities.GroupActivity}: java.lang.ClassCastException: android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
06-18 08:40:17.631 E/AndroidRuntime(439): 	at com.kunzisoft.keepass.view.ViewUtilKt.setTransparentNavigationBar(ViewUtil.kt:311)
06-18 08:40:17.631 E/AndroidRuntime(439): 	at com.kunzisoft.keepass.activities.GroupActivity.onCreate(GroupActivity.kt:295)
06-18 08:40:17.635 W/ActivityTaskManager(3768):   Force finishing activity com.kunzisoft.keepass.libre/com.kunzisoft.keepass.activities.GroupActivity
```
There seems to be a graphical bug on some versions of android (a weird cast), especially on version 11 apparently. I'm trying to reproduce the problem on my end by downloading a version of API 30 on my emulator.

**Comment by J-Jamet** [comment]
I've just found it's this code that doesn't work on some versions: 
```
this.window.statusBarColor = obtainStyledAttributes(intArrayOf(R.attr.colorSurface)).use {
                it.getColor(0, Color.GRAY)
            }
```
I'm trying a patch and a redeployment

**Comment by vivadavid** [comment]
Fixed for me on 4.0.8! Thanks!

**Comment by Denio-7** [comment]
Everything is fine in 4.0.8, thanks for the quick fix!

**Comment by SanskritFritz** [comment]
Man that was fixed quickly, thank you!
