### ISSUE TITLE
Change "master" to more inclusive language

### ISSUE THREAD

**Issue by cvni1981** [Kunzisoft/KeePassDX#1849]
Maybe change to "main" or "primary" or "entry" password!
(i posted this issue as a "feature". it didnt really fit so i reposted it)

**Comment by boldcoffee7678** [comment]
@cvni1981, what do you mean by "more inclusive"?  
You know that words change meaning based on context, right?

**Comment by cvni1981** [comment]
this change is unnecessary, sorry for bothering!
