### ISSUE TITLE
The latest version 4.0.7 cannot open the database, downgrading 406 is normal

### ISSUE THREAD

**Issue by nichousha123** [Kunzisoft/KeePassDX#1850]
406 upgraded to 407. After entering the password and opening the key file, clicking the unlock button does not open the database. Please see the video for details. I reinstalled 406 and it returned to normal.

keepassDX
Version: 4.0.7
Build: libre
Language: Chinese

Mobile phone information
Brand: vivo V2046A

Version name: Android 11 Red Velvet Cake

API version: 30

https://github.com/Kunzisoft/KeePassDX/assets/147991448/b8f9380f-7471-48d4-9673-24cdeafdccbf

**Comment by nichousha123** [comment]
After testing, I installed the same installation package on another Huawei phone of mine and it worked fine. It can open

huawei nova2
emui 8.0.0
Android 8.0

**Comment by J-Jamet** [comment]
Same as https://github.com/Kunzisoft/KeePassDX/issues/1848
The Play Store usually lets me see crashes like this. For the moment, I've managed to deal with bugs this way, but an internal log system could make things easier. After that, it's more up to the system to manage log returns, so I'd have to make an easy procedure in the wiki for extracting them.
