### ISSUE TITLE
sandboxie?

### ISSUE THREAD

**Issue by stokebreakup** [Kunzisoft/KeePassDX#1854]
**Is your feature request related to a problem? Please describe.**
Would it be interesting to have a sandboxie on keepassdx?

**Describe the solution you'd like**
[Sandboxie](https://sandboxie-plus.com/Sandboxie) is a sandbox-based isolation software for 32- and 64-bit Windows NT-based operating systems. It creates a sandbox-like isolated operating environment in which applications can be run or installed without permanently modifying the local or mapped drive. An isolated virtual environment allows controlled testing of untrusted programs and web surfing.

**Describe alternatives you've considered**
If someone steals my cell phone, I can download the encrypted file keepass with Google Drive, and I'm safe in the knowledge that my work profile is not the same as the app's profile. This potentially increases security in the event of theft, loss or accident.

**Additional context**
None.

**Comment by J-Jamet** [comment]
Sandboxie is a Windows program, while Android applications are sandboxed by OS design.
