### ISSUE TITLE
"Could not load the database" - just mentioning in case 

### ISSUE THREAD

**Issue by cheesemonkeyboy** [Kunzisoft/KeePassDX#1855]
**Describe the bug**

While I have done my best to make sure my database file is not bad/corrupt/incomplete, hopefully this Bug Report is just some sort of weird problem with my KeePass database file - but I make this report in case I have run across a bug situation on KeePassDX.  THANK YOU for making KeePassDX!

I only use KeePassDX on my Android phone for read-only access to my KeePass databases (plural).  My KeePass databases are modified only by KeePass v1.42 portable running on Windows 10.  One of my databases will not open anymore in KeePassDX = after entering my password (with no required additional keyfile, etc.), I now get "Could not load the database".  This same database file still opens just fine in KeePass v1.42 on Windows 10 where it "came from".  This particular database which will now not open has 72 groups / 950 entries, and is somewhat large at 21.8 MB.  An older archived version of this same database, which again is older, has 73 groups / 951 entries - and my older archived database opens in KeePassDX as expected.

I have tried "Repair Database File" on the database file in KeePass v1.42 portable - still won't open in KeePassDX, but still opens just fine in KeePass v1.42 portable.  All other smaller KeePass databases, other than my "Database.kdb" database, open/function just fine in KeePassDX.

**To Reproduce**

1. Open KeePassDX
2. Click on 'Open existing vault'
3. Go to where my KeePass database file is stored (/storage/emulated/0/Documents/Database.kdb)
4. Carefully enter my password
5. Click on 'Unlock'
6. Receive the error "Could not load the database"

**Expected behavior**

Database opens.

**KeePass Database**

 - Created with: Windows KeePass v1.42
 - Version: portable
 - Location: My KeePass database files are transferred to my Android phone via my own internal FileZilla Server
 - File provider (`content://` URI): Sorry if I do not get this detail correct...  content://com.Icg.Xplore.FileContent/uid/file/%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDocuments%2FDatabase.kdb?size=22921228&time=1717834635000
 - Size: 21.8 MB (22,921,228 bytes)
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4.0.6
 - Build: libre
 - Language: English

**Android:**

 - Device: Pixel 4a
 - Version: Running CalyxOS 5.7.2, Android 14, Platform: May 5, 2024, Kernel: May 5, 2024, Vendor: August 5, 2023, Firmware: August 5, 2023

**Additional context**

 - Browser for Autofill: Autofill never used
 - Android Kernal version: 4.14.340-openela-ab24506000, #1 Mon Apr 1 18:04:07 UTC 2024
 - Android Build number: AP1A.240505.005.24507020

**Comment by cheesemonkeyboy** [comment]
I see that KeePassDX v4.0.8 just came out, addressing:
"Fix graphical bug that prevented databases from being opened on some versions of Android https://github.com/Kunzisoft/KeePassDX/issues/1848 https://github.com/Kunzisoft/KeePassDX/issues/1850"

I am relieved that I'm not the only one having "Could not load the database" issues, and was excited that my freshly reported "Could not load the database" issue would be resolved.

Sadly, after updating my KeePassDX app to v4.0.8, I'm still having the issue reported above...

**Comment by J-Jamet** [comment]
KeePass version 1 support is for compatibility purposes only. Have you tried transforming your database to .kdbx and then trying to open it again with KeePassDX?
Without having the opening logs with your database, it will be very difficult to identify the problem.

**Comment by cheesemonkeyboy** [comment]
> KeePass version 1 support is for compatibility purposes only. Have you tried transforming your database to .kdbx and then trying to open it again with KeePassDX? Without having the opening logs with your database, it will be very difficult to identify the problem.

Hello **J-Jamet**.  Thank you for your reply!  No, I haven't transformed to .kdbx - I have preferred for many years to use 1.x.  As I look at the [Edition Comparison](https://keepass.info/compare.html), I don't remember exactly why I steered away from 2.x - it might have been because I saw .NET.  Anyway, I've never wished I had features found within KeePass 2.x, but maybe I should make the change.  I do prefer the portable version as I can run KeePass from a USB stick if I want or need to...

I am unaware of how to obtain "opening logs".  Please point me in the "opening logs" direction and I'll see what I can grab!

**Comment by J-Jamet** [comment]
You can obtain system logs with a [LogFox](https://f-droid.org/packages/com.f0x1d.logfox/)-type application. The aim is to obtain logs indicating loading and opening exceptions in the KePassDX package.

**Comment by cheesemonkeyboy** [comment]
As my Pixel 4a is not rooted (even though I am running an alternate OS, CalyxOS), LogFox is not run-able on my phone.  The update = after making regular day-to-day changes in my KeePass v1.42 on my PC, now KeePassDX will again open my v1.42 database.  Don't know what the issue was - I kind of suspect it had something to do with the automatic backup of entries (which go into the "Backup" folder in the database).  Nevertheless, this "issue" has self-resolved...

**Comment by Adhjie** [comment]
Sorry for necroing, but this is just as an end note.
since you helped me debug my bug-issue, I need to tell you: you could use ADB with shizuku as a backend for logfox. It works with wireless adb, wired adb using command sent from windows terminal, and last option is root, which is indeed not an option here.

this is solved but I just want to leave a note, here. since logfox helped, I thought I should at least give some info, that it could be use with shizuku on non-rooted phone.
maybe it'll be useful for you in the future when apps that you use have a bug, and you need to debug it again.
links:
https://github.com/RikkaApps/Shizuku
https://shizuku.rikka.app/guide/setup
[Start Shizuku](https://shizuku.rikka.app/guide/setup/#start-shizuku)
    [Start with root](https://shizuku.rikka.app/guide/setup/#start-with-root)
    [Start via wireless debugging](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging)
    [Start by connecting to a computer](https://shizuku.rikka.app/guide/setup/#start-by-connecting-to-a-computer)
(feel free to close this again, I'm just leaving a note.)
