### ISSUE TITLE
What really does the "remove unlinked data" function?

### ISSUE THREAD

**Issue by serrq** [Kunzisoft/KeePassDX#1859]
Because I don't find some data... and I used it in the past (database settings).

**Comment by J-Jamet** [comment]
The KeePass file behaves like a database and can contain data that is not linked to entries. If these data are no longer linked, for example after incorrect formatting or a structural bug, they are no longer needed but take up space. They can therefore be deleted. However, you need to be careful, as some plugins in other applications use unlinked data.
