### ISSUE TITLE
Copy key file to internal storage

### ISSUE THREAD

**Issue by matkam** [Kunzisoft/KeePassDX#186]
Keepass2Android has a feature to "Import key file to internal folder" to prevent other apps from reading the key file. This would be great to have in KeePassDX too.

**Comment by J-Jamet** [comment]
Linked to #133

**Comment by t-m-w** [comment]
(I meant to post this here originally.)

As a workaround, you can store the key file in another app you trust that supports the Storage Access Framework, and then browse to it in KeePassDX. This is better than having it floating around in the Internal Storage area where any app can access it; at least you, the user, have to be proactive about browsing to it in order for another app to have permission to access it. I used Termux for this, but there may be better ideas.

_Originally posted by @t-m-w in https://github.com/Kunzisoft/KeePassDX/issues/133#issuecomment-908831687_

**Comment by J-Jamet** [comment]
The functionality is part of a file manager application. You can continue the discussion in the FileSync project : https://github.com/Kunzisoft/FileSync/issues/7
