### ISSUE TITLE
Can't Download Driver for Yubikey

### ISSUE THREAD

**Issue by lippfi** [Kunzisoft/KeePassDX#1867]
Sorry for creating the issue here; I just don't know how to do it on GitLab.

I was going to try KeePassDX, but I failed because the required driver is missing. The GitLab link to the latest driver release returns a 404 error.

**Comment by J-Jamet** [comment]
It's probably from the new CI/CD, I'll have a look. There's already an associated issue on gitlab.

**Comment by J-Jamet** [comment]
https://gitlab.com/kunzisoft/android-hardware-key-driver/-/issues/14

**Comment by lippfi** [comment]
@J-Jamet  It's been a month and I still want to try KeePassDX :)
Could you please have a look at the gitlab issue?
