### ISSUE TITLE
Can't open database

### ISSUE THREAD

**Issue by PsyNyde** [Kunzisoft/KeePassDX#1873]
**Describe the bug**

Tried keepassvault and opened database with it. not there's an error "can't open database"

**To Reproduce**

- open db with keepassvault and access it.

**Expected behavior**
Being able to open database

**KeePass Database**

 - Created with: keepassdx. (idk the exact version)
 - Version: (not sure)
 - Location: device storage
 - Size: 150KB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4.0.8
 - Build: Libre

**Android:**

 - Version: 12

**Additional context**

 - Browser for Autofill: Firefox

**Comment by J-Jamet** [comment]
KeePassDX is compatible with all KeePass formats, with the original KeePass program and with KeePassXC.
If another fork is not compatible, you need to open a bug on the corresponding project.
