### ISSUE TITLE
Default Password

### ISSUE THREAD

**Issue by Tripp1e** [Kunzisoft/KeePassDX#1881]
**Is your feature request related to a problem? Please describe.**
My Problem is that due to PCloud being a bad service, it revokes file access, so I have to add my database every time, which also requires me to enter the Password and subsequently add biometric unlock to it.

**Describe the solution you'd like**
I want to make this a bit easier by having a default password that keepass tries to use for a newly opened Database and if it works also link biometric unlock to it.

**Describe alternatives you've considered**
I tried to make Keepass use the actual Database file through third party, root explorers, though this didn't work. I also tried just living with it, but with this having to be done multiple times a day every day and me already having paid for this service, I dont think thats the right solution also.

**Additional context**

**Comment by J-Jamet** [comment]
The solution you propose won't work because the problem remains the same: PCloud revokes the link to the database. Ask this service to change its File Provider.

Linked : https://github.com/Kunzisoft/FileSync/issues/6
