### ISSUE TITLE
keepassdx doesnt show additional attributes from keepassxc

### ISSUE THREAD

**Issue by gamgamstylep** [Kunzisoft/KeePassDX#1882]
when i open the keepassdx app (v 4.0.8) and open a keepassxc database (2.7.9)  ((see photo)) with keepassdx no additional attributes are shown (see photo).
When i open the same database with keepass2android (1.09e-r7) (see photo) i can see the additional attributes.

![keepass2android](https://github.com/user-attachments/assets/92bb689d-821a-4e81-b79b-7df25d36710f)
![keepassxc](https://github.com/user-attachments/assets/0ae89793-5c14-4c65-8215-11ec1ed1b295)
![keepassdx](https://github.com/user-attachments/assets/aeae1b50-13e1-4b5b-9650-8f4bcdecba4b)

Thank you.

**Comment by J-Jamet** [comment]
If you're using a Cloud application like Google Drive, delete its cache to be sure you're displaying the right version of the file.
Try manually copying the .kdbx file to the device, and you'll see that it works.

**Comment by gamgamstylep** [comment]
I tried the Same File manually copied. I opened the Same File with keepass2android and keepassdx.  Try to create the additional Attributes with keepassxc on a Computer.

**Comment by J-Jamet** [comment]
Can you upload a test database in this thread that reproduces the problem?

**Comment by gamgamstylep** [comment]
now it is working. dont know why. thanks
