### ISSUE TITLE
Feat: Save a backup to

### ISSUE THREAD

**Issue by VegarRingdalAibel** [Kunzisoft/KeePassDX#1889]
**Is your feature request related to a problem? Please describe.**
When I select `save a copy to` it now adds `_copy` sufix
 
**Describe the solution you'd like**

Would be nice if we had one called `Save a backup to ...`

And this would add iso string and use `backup_` sufix
So instead of `somename_copy` like save does
It would have done something like this:
`somename_backup_2024-08-23T06:42:35.502Z` or just `somename_backup_2024-08-23T06:42:35`
Easier to make and know latest save/backup of database in some secure server/cloud.

**Describe alternatives you've considered**
Adding isostring manually. But chance of typing wrong is high and time consuming

**Additional context**
...

**Comment by VegarRingdalAibel** [comment]
Also when it does `save a copy to..` and `Save a backup to..` it should also use original name, now it always says `keepass`

**Comment by J-Jamet** [comment]
I will simply improve the "save a copy to..." behavior. 😉

**Comment by VegarRingdalAibel** [comment]
Nice, thanks.
Love the application. Thanks for your hard work 🥇 
Using the XC and syncthing with DX app for desktop.
Just amazing been in control of password, 2fa and secrets. (3 dbs...).
