### ISSUE TITLE
Attach and download files

### ISSUE THREAD

**Issue by TobiasDev** [Kunzisoft/KeePassDX#189]
In KeePassXC it looks like I can attach files (and thus encrypt them), I would love to see this functionally in the app as well. So I can download and de-crypt my files from my database.

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/115 ,  https://github.com/Kunzisoft/KeePassDX/issues/183 , https://github.com/Kunzisoft/KeePassDX/issues/187 ,  https://github.com/Kunzisoft/KeePassDX/issues/168

**Comment by J-Jamet** [comment]
- [ ] Attach binary file
 - [ ] Download binary file

**Comment by J-Jamet** [comment]
Hard feature because many databases versions to manage. But should work in version 2.8.3
