### ISSUE TITLE
Top bar bug

### ISSUE THREAD

**Issue by Jhorrin** [Kunzisoft/KeePassDX#1890]
**I can't click on anything in the top bar**

Right after installation, the tutorial walks me through the App and it functions, in that time I can access everything, but right after the tutorial is over, the top bar / buttons stop responding. I can't open any Options, settings or the search tool.

**To Reproduce**

1. Own a Xiaomi 10t Pro phone
2. Install the App
3. Suffer from the Bug

**Expected behavior**

When I press a button in the top(bar), something should happen.

**KeePass Database**

 I only have 1 Database, and it works on my other devices.

**KeePassDX:**

 - Version: from 18.06.24

**Android:**

 - Device: Xiaomi 10t pro
 - Model M2007J3SG
 - MIUI Version 12.0.6.0 (QJDEUVF)
 

**Additional context**

Pepe sad :(

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/1458 https://github.com/Kunzisoft/KeePassDX/issues/1395 & https://github.com/Kunzisoft/KeePassDX/issues/1375 https://github.com/Kunzisoft/KeePassDX/issues/1366

It's an OS issue
