### ISSUE TITLE
[Question/Request] Stop asking to save password for specific apps.

### ISSUE THREAD

**Issue by abhi-k9** [Kunzisoft/KeePassDX#1893]
I'm on version 4.0.8 with Android oneUI 6.1.

The app keeps asking to save password for "Secure Folder" when I don't want it to. There is no option to make it stop. 

Please advice. Thanks!

**Comment by J-Jamet** [comment]
Blocklist should work https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#blocklist
