### ISSUE TITLE
"No memory to load your entire database" I am locked out although I have the keyfile

### ISSUE THREAD

**Issue by serrq** [Kunzisoft/KeePassDX#1895]
I am literally locked out.

**Describe the bug**

Starting from today I receve this warning when I try to unlock my local database as usually.

**To Reproduce**

1. Launch the app
2. Select the right key file
3. Warning about memory

**Expected behavior**

Usually I open my database without hassle.

**KeePass Database**

 - Created with: KeepassDX foss
 - Version: [e.g. 2] maybe 4 i dont remember
 - Location: local in Anemo folder
 - File provider
 - Size: ~60mb
 - Contains attachment: [e.g. Yes] yes

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23] 4.0.8 foss Izzy
 - Build: [e.g. Free] free
 - Language: [e.g. French] EN

**Android:**

 - Device: [e.g. GalaxyS8] OnePlus CPH2399
 - Version: [e.g. 8.1] Android 14

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

![1000118462](https://github.com/user-attachments/assets/0ecc18c7-4162-48e5-9c3e-3d61a1fb74d4)

**Comment by J-Jamet** [comment]
I don't know but 60mb is relatively large database. If you closed Anemo before the full save was performed, the file may have been partially backed up and therefore corrupted.

**Comment by J-Jamet** [comment]
I'm just theorizing, I don't know what happened in your case. Maybe it's entirely something else, like an attachment that didn't save properly in the application. But without reproducing the problem I don't know how to solve it.

**Comment by J-Jamet** [comment]
My first theory is that if you use Anemo and cut the link through SAF by locking access to the storage after a certain period, the kdbx save hasn't had time to take place but this would have to be tested.

**Comment by shuvashish76** [comment]
> I don't know but 60mb is relatively large database.

@serrq I saw one of your previous post in #1559 where you mentioned your database was 130MB.
I don't know what you're storing in your database to make them so large. I've a database with nearly 400entries but the size is less than 100kb _(I don't store files or icons)_. Though you've the option to store files...KeePasss is really not intended for file/disk encryption tool. There are other alternatives specific to file protection e.g. https://cryptomator.org/ , https://veracrypt.fr , https://nuetzlich.net/gocryptfs/ etc. KeePass database is prone to corruption in general when you're using such heavy sized database.

**Comment by shuvashish76** [comment]
KeePass is an excellent option which offers so many free features but to be honest it's a password manager and should be treated as such. For example no harm in storing recovery codes of GitHub as `.txt` file because of less size _(personally I try to avoid storing files, I store them as simple notes (not file) under GitHub entry)_. If you've to store files then I'd say keep them small and simple if possible e.g. OpenPGP `.asc` [public/secret_keys](https://emailselfdefense.fsf.org/en/)

> Do you suggest to relocate all the files attachments in DroidFS (Android)?

Totally up-to your choice and preference :) I've listed some apps [here](https://github.com/offa/android-foss/issues/446), they'll be added to "Android FOSS" list

**Comment by J-Jamet** [comment]
These two tools are not designed for the same purpose. KeePass is designed to manage passwords and authentication systems, to centralize a user's credentials so as to have a single point of entry and unlock numerous services, not to store files.
If you want to store files securely, don't use KeePass but tools like the ones you suggest.
