### ISSUE TITLE
If Chang'an copies the account, it will return to the login interface

### ISSUE THREAD

**Issue by lvluozixuemengyanyan** [Kunzisoft/KeePassDX#1897]
If Chang'an copies accounts, passwords, notes, etc., it will return to the login interface

Below is a reproduced video：
https://drive.google.com/file/d/1rHAClokSCF96cT1aFc1An_UK_f-i12N6/view?usp=sharing

Version: The latest version downloaded from Github
Mobile phone model:VIVO X90
System:OriginOS4

**Comment by J-Jamet** [comment]
It's a problem in your OS that causes the application to crash when the context menu for a text appears. See if you can't update your VIVO.
