### ISSUE TITLE
Accrescent?

### ISSUE THREAD

**Issue by Jeffrey2307** [Kunzisoft/KeePassDX#1918]
hey i would love to see the App on Accrescent Store (which is the most secure and private Store and better solution than Github) maybe you can apply there, because it would be the best and better solution and I would love to see you Guys there

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1566

**Comment by PrivacyAndSecurity** [comment]
I would love to see you there too!
