### ISSUE TITLE
Autofill suggestions do not save if "Write-protected" setting is enabled

### ISSUE THREAD

**Issue by An-anonymous-coder** [Kunzisoft/KeePassDX#1919]
**Describe the bug**

When the "Write-protected" setting is enabled (which opens the database read-only by default), autofill suggestions will not be written to entries.

**To Reproduce**

1. Open KeePassDX
2. Unlock the database
3. Open the hamburger menu on the top left
4. Open "Settings"
5. Go to "App settings"
6. Enable "Write-protected"
7. Go back to settings
8. Go back to the hamburger menu
9. Exit the hamburger menu
10. Tap the "+" on the bottom right
11. Tap "Add entry"
12. Enter a value in the "Password" field
13. Tap the green check mark in the middle to create the entry
14. Open the hamburger menu on the top left
15. Tap "Lock"
16. Exit the KeePassDX app
17. Open an app that will require a password.
For this, I used [Aegis Authenticator](https://getaegis.app/).
19. Tap on the password field to enter a password
There should be an autofill option displayed on your keyboard. For this, I used [HeliBoard](https://github.com/Helium314/HeliBoard).
20. Tap "Sign in with KeePassDX"
21. Unlock the database
22. Select the entry you made previously
A message will display saying "Autofill suggestions added."

While you are able to autofill this one time, it never actually changes the entry to reflect the app as an autofill option, despite saying "Autofill suggestions added." The next time you try to autofill for that app, you will have to repeat step 21, instead of having it automatically suggest an autofill option. 

**Expected behavior**

The entry should be edited to create an autofill option for the app.

**KeePassDX:**

 - Version: 4.0.8
 - Build: com.kunzisoft.keepass.libre (GitHub Releases)
 - Language: English (US)

**Android:**

 - Device: Pixel 8
 - Version: GrapheneOS 2024102100 (Android 15)

**Comment by J-Jamet** [comment]
It's not a bug, if you open a read-only or write-protected database, it's normal for autofill not to save anything in the database. In this case, you need to open it in write mode (with the pencil icon).

**Comment by J-Jamet** [comment]
"Autofill suggestion added" only means that the suggestion has been added and can now be selected. I had added it because in some cases, the autofill suggestion is in the keyboard and the keyboard has closed.
