### ISSUE TITLE
"File not found" after a reboot

### ISSUE THREAD

**Issue by sivaraam** [Kunzisoft/KeePassDX#192]
**Intro**
I heavily rely on the "Use this as default database" feature. Unfortunately it doesn't seem to be resilient to reboot which frustrates me a bit at times especially after the introduction of the Magikeyboard (which is an awesome feature BTW, thanks!). To be honest, I'm using KeePassDX mostly only through Magikeyboard these days.

**The actual issue**
When I reboot my phone and try to access a credential via the Magikeyboard I get the "file not found error". Then I have to open KeePassDX app and re-open the same file and unlock it. Then I have to come back to the place that requires the credentials and re-unlock the file (which is not a nice UX, BTW. But that's for [another issue](https://github.com/Kunzisoft/KeePassDX/issues/193) :-) to access the credential. I find this unnecessary.

**Possible solution**
My gut instinct tells me that there's an open file handle which becomes invalid after a re-boot. The same instinct also tells me this could simply be fixed by attempting to re-open the file once and leave if that fails.

**Side Note**
Thanks for the great app, BTW. I find it to be very useful.

**Environment details**
_App version_: 2.5.0beta17-libre
_Android version_: 5.1.1
_Device_: Samsung Galaxy J1 ace

**Comment by leoj3n** [comment]
I have KeePassDX from F-Droid and experienced a similar issue without phone reboot.

Backing out from the database select in the Magikeyboard shows the original database file and a new entry called just "9" or "7" for instance.

Selecting the original database results in the not found error mentioned in the OP.

Selecting the newly materialized "9" entry loads up the original database.

Have to remove and relink the file next use or continue to get not found.

**Comment by vKnmnn** [comment]
I also use the app from fdroid repos. For me the issue appears whenever the database file gets synced by the nextcloud app. It will also have a number as name.

**Comment by Horlacher** [comment]
I suspect the NextCloud app to only provide a temporary file handler.
It works for me opening the synced file from a file manager:
/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/PathToYourKDBX

**Comment by J-Jamet** [comment]
I agree with @Horlacher , some file providers do not provide persistent links.

**Comment by J-Jamet** [comment]
Linked to #265 
Links are more likely to be kept if you go through the 'Open existing database' button. (and not directly by clicking on the .kdbx file from your file manager)

I close this issue because is the same problem as other linked issues.
