### ISSUE TITLE
Unlocking file via Magikeyboard shouldn't always require password

### ISSUE THREAD

**Issue by sivaraam** [Kunzisoft/KeePassDX#193]
When I've opened the KeePass DB using the KeePassDX app directly it keeps the database open for some item. When I try to access a credential via Magikeyboard in the mean time I'm asked to unlock the database again. I find this redundant and unnecessary. It should be possible bypass the password authentication requirement when the password database is already open in KeePassDX.

**Steps to reproduce**
1. Open KeePassDx
1. Unlock a KeePass database
1. Tap the home button
1. Go to the [sign-in page of GitHub](https://github.com/login)
1. Tap on the username field
1. Switch to Magikeyboard
1. Tap on unlock icon

**Expected results**
As the password database is already unlocked in KeePassDX it should not require unlocking the database again. IOW, it should skip the step and take me to the list of password entries.

**Actual results**
I have to re-unlock the database which is redundant and is unnecessary. Also, after I choose the required credential I'm not taken back to the GitHub log-in page in the browser but to the password list which is weird and I have to manually switch to the browser.

**Environment details**
_App version_: 2.5.0beta17-libre
_Android version_: 5.1.1
_Device_: Samsung Galaxy J1 ace

**Comment by rugk** [comment]
Same, AFAIK this also is the same when you use the Android 8 password autofill feature…

BTW, another way to solve it would be to (optionally) keep the magikeyboard to request the password, but _actually lock_ the database (that is opened in the background), when the user fails to enter the correct password or cancels the password prompt…
This way you get a little more security.

The other way you propose could be the convenience feature. Maybe you can let users use both modes, but the current way is just not useful neither for security nor for convenience. :no_mouth:

**Comment by rugk** [comment]
How did you solve this now?

**Comment by J-Jamet** [comment]
I completely redone the login / logout workflow and the implementation of memory dump methods.
