### ISSUE TITLE
I can't update

### ISSUE THREAD

**Issue by lollita** [Kunzisoft/KeePassDX#1939]
KeePassDX not install from apk and last update in playstor is at 18-06-2024.
How update?

**Comment by AnonymousWP** [comment]
Same, if I try to update through GitHub, which is also Free (just like the Play Store), I get a package conflict.

**Comment by J-Jamet** [comment]
If you have installed the application from two different locations, the signatures will be different. You must therefore uninstall and reinstall. Don't forget to back up your databases and settings.

**Comment by AnonymousWP** [comment]
That's kind of weird, because with some other open-source apps, I can just cross-install, no matter the source and as long the package name is the same. And as far as I know, both GitHub (Free) and Google Play (Free) have identical package names.
