### ISSUE TITLE
Renaming groups does not work

### ISSUE THREAD

**Issue by dead10ck** [Kunzisoft/KeePassDX#194]
When I try to rename a group, nothing happens. I hit OK and the name just stays the same. This is version 2.5.0.0beta17-libre.

**Comment by J-Jamet** [comment]
After several tests, I have not managed to reproduce your problem. Can you tell me what is your device?

**Comment by dead10ck** [comment]
I'm on a Pixel 2.

**Comment by J-Jamet** [comment]
Happens sometimes, I'll look to solve the problem.
