### ISSUE TITLE
Click all the buttons on the KeepassDX software interface, and basically no response

### ISSUE THREAD

**Issue by Eyion** [Kunzisoft/KeePassDX#1941]
**Describe the bug**

1. Open an existing database and click "Set", but there is no response.
2. Open an entry and click "Edit", but there is no response.
3. After clicking all the buttons on the software interface, nothing happens, except for creating a new password vault and opening an existing password vault.

**KeePass Database**

 - Created with: Windows KeePassXC 2.7.8
 - Version: 2 (.kdbx)
 - Location: nutstore
 - File provider (`content://` URI): content://nutstore.android.documents/document/
 - Size: 1.21Mb
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.08 - 4.1.1
 - Build: libre
 - Language: Chinese

**Android:**

 - Device: MI 8
 - Version: Android 10 (MIUI12.5.2)

**Comment by J-Jamet** [comment]
You're using an application that overlays the KeePassDX application, which has security to prevent tapjacking. Remove the overlay application or use screenshot mode.

**Comment by Eyion** [comment]
This question is bothering me. How can I find this application? How can I use the screenshot mode?

**Comment by J-Jamet** [comment]
In most cases, the user has added it himself, for example a blue-light filter. Otherwise, you'll find the screenshot mode in settings - app settings.
