### ISSUE TITLE
Update in Google Playstore?

### ISSUE THREAD

**Issue by SoftwUser** [Kunzisoft/KeePassDX#1943]
In Google Playstore KeePassDX still is on 4.0.8.

When can we expect an update to the current release (4.1.1)?

**Comment by J-Jamet** [comment]
The release is in the beta channel.

**Comment by SoftwUser** [comment]
@J-Jamet 
Thank you - and when do you plan to release a stable release (leave the beta status)?

**Comment by J-Jamet** [comment]
After solving search bugs
