### ISSUE TITLE
Hope to add WebDAV functionality.

### ISSUE THREAD

**Issue by qksska** [Kunzisoft/KeePassDX#1944]
If the data in the cloud drive is modified by another program, KeePassDX still opens the cached data. If WebDAV functionality could be added, it would allow for automatic synchronization. Otherwise, after every modification, one has to open and sync the file using cloud drive software, which is very inconvenient. I hope my suggestion can be seen. Thank you.

**Comment by J-Jamet** [comment]
Wrong project https://github.com/Kunzisoft/FileSync/issues/1
duplicate https://github.com/Kunzisoft/KeePassDX/issues/118

**Comment by J-Jamet** [comment]
> If the data in the cloud drive is modified by another program, KeePassDX still opens the cached data

KeePassDX only opens streams deployed by file providers, there is no cache at this level. This is a well-known issue with the Google Drive application.
You can read the wiki for more information https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
