### ISSUE TITLE
Only manual selection mode

### ISSUE THREAD

**Issue by Johnson-Dick** [Kunzisoft/KeePassDX#1945]
**Describe the bug**

Since the last update (4.1.0), when open any login form via any browser, the autofill form suggests to use manual selection ("sign in with keepassdx" instead of suggesting login/password initially) and brings me to the keepassdx app for entry selection, although the base is unlocked, the manual selection option is turned off in the keepassdx app autofill settings, and there is an entry in my base for the site I try to login, with link field filled in with link that leads to login form of the site I want to login.
Same thing either in pop-up window, or in Gboard or in magickeyboard.
<details>
  <summary>Screenshots</summary> 
<img src="https://github.com/user-attachments/assets/550edd0f-ae79-418e-8c89-9d20424deed7">
<img src="https://github.com/user-attachments/assets/21540c87-3915-459b-9a72-09aad93f5f67">
<img src="https://github.com/user-attachments/assets/ebdc7010-85dd-4886-b972-ddb12873de4f">

</details>

That happens even if I add "AndroidApp" field to the entry and insert "com.android.chrome" there. But if I save an entry for some app, autofill in this app suggests to fill in login/password at the first place, without proceeding to the app needed.

**To Reproduce**

1. Turn on autofill service in app and system settings.
2. Save the login/password data for any domain to the base entry.
3. Turn off manual selection option in autofill settings
4. Unlock the keybase.
5. Go for the domain via any browser.
6. Tap into login form.
7. See the "sign in with keepassdx" instead of login suggestion

**Expected behavior**

1. Go for the domain via any browser.
2. Tap into login form.
3. See the login/password suggestion without proceeding to the keepassdx app, as it was in 4.0.8 app version and as it works with applications excluding browsers.

**KeePass Database**

 - Created with: [KeepassDX 4.0.8]
 - Version: [V2 KDBX 4.0]
 - Location: [local storage]
 - File provider (`content://` URI): [content://com.android.externalstorage.documents/document/primary%3Abackups%2Fkeepass.kdbx]
 - Size: [5.76 KB]
 - Contains attachment: [NO]

**KeePassDX:**

 - Version: [4.1.0]
 - Build: [Free]
 - Language: [ENG]

**Android:**

 - Device: [OnePlus 7t]
 - Version: [12]

**Additional context**

 - Browser for Autofill: [Chrome, Firefox, Opera, Duckduckgo browser, Cemu browser]
 - The application blacklist and the domain black list are empty.
 <details>
  <summary>SettingsScreens</summary> 
<img src="https://github.com/user-attachments/assets/7f2456f8-dc01-4609-b802-d1e0de2684f9">
<img src="https://github.com/user-attachments/assets/f5de2c24-1fb2-44f9-a7a8-1857f4e0105e">
</details>

**Comment by theatischbein** [comment]
I guess it is related to #1940 
For me it helped to remove anything behind the domain.
E.g.
`https://github.com.` -> `https://github.com`

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/1940
