### ISSUE TITLE
Fingerptint could not be used on Xiaomi 14

### ISSUE THREAD

**Issue by TheVscript** [Kunzisoft/KeePassDX#1962]
**Describe the bug**

Moved from Mi 10T to a new phone (xiaomi 14)
each app was synched when initilaised the new phone.

When i try to open my vault i cannot use the fingerptint only the pass phrase.

**To Reproduce**

1. open pp
2. try to login with fingerprint
3. when I click on the mark next to the input box i see the attached message.
![img_20241214_170151](https://github.com/user-attachments/assets/eeb5fbef-d478-44b5-afea-96512586d768)

**KeePass Database**

 - Created with:  Windows KeePass 
 - Version: cannot remeber
 - Location: remote from dropbox
old do not know all the details. on windows 10

**Keepass2Android:**

 - Device: xiaomi 14
 - Version: latest from store

**Additional context**

**Comment by FabiRich** [comment]
I have the same problem, but only after I updated to Android 15. Now using

Xiaomi 14
Hyper OS 2.0.1.0 Android 15
KeepassDX Versions tried with 4.0.8 Google Play
And 4.1.1 Izzy

I receive the error message 
Not implemented (internal Keystore code -100 message: system/security…
