### ISSUE TITLE
Xiaomi 14 fingerprint unlock not working

### ISSUE THREAD

**Issue by FabiRich** [Kunzisoft/KeePassDX#1966]
I have the problem, that I can't set a fingerprint as an unlock option anymore after updating to Android 15. Now using

Xiaomi 14
Hyper OS 2.0.1.0 Android 15
KeepassDX Versions tried with 4.0.8 Google Play
And 4.1.1 Izzy

I receive the error message 
Not implemented (internal Keystore code -100 message: system/security…

**To Reproduce**

1. Go to created database
2. Type password
3. Click on "device unlock method"
4. Receive error message and nothing happens

**Comment by FabiRich** [comment]
I found the error.
After the android upgrade the autofill service had been reset. So I set it again to KeepassDX and did a restart.

Now everything seems fine, closing it then

**Comment by FabiRich** [comment]
Closed

**Comment by bkodera** [comment]
Hi @FabiRich, how do I exactly "reset the autofill" service?
I am running into the same issue but don't know how to resolve it myself.

**Comment by bkodera** [comment]
Thanks! It now works, although there is no real option to reset the autofill service. It seems I also had to temporarily disable other services like Authenticator and Google and re-enable the KeePassDX autofill service.

It hadn't even worked with HyperOS 1 before.

**Comment by FabiRich** [comment]
Awesome, yes there is no real reset option, but only to disable it and then enable it
