### ISSUE TITLE
Phone lock screen after reboot (magikeyboard)

### ISSUE THREAD

**Issue by leoj3n** [Kunzisoft/KeePassDX#198]
Heres an annoying problem...

If your phone is encrypted, and has a lockscreen password, and you restart the phone with the Magikeyboard set as the current keyboard, you will not be able to type in your phone password, and attempting to change the keyboard has no effect, so you are essentially locked out of your phone unless you have a usb keyboard you can plug in using an OTG connector.

**Comment by J-Jamet** [comment]
Hooo thank you for this feedback. This is a real problem, indeed, I'll try to solve this problem. I integrated the keyboard selection by long click in the developments, I'll see if it's OK. Sorry for this issue.

**Comment by J-Jamet** [comment]
Fixed with the long press button in version 2.5.0.0beta18
