### ISSUE TITLE
Delete (duplicated) nb translation

### ISSUE THREAD

**Issue by comradekingu** [Kunzisoft/KeePassDX#199]
https://hosted.weblate.org/projects/keepass-dx/strings/nb/ is duplicated.
It should be deleted before anyone wastes effort thinking it is the real translation for Norwegian Bokmål.
(Edit: The correct one is "nb_NO")

**Comment by comradekingu** [comment]
This will be possible in the next version of Weblate.

**Comment by J-Jamet** [comment]
I'll delete the folder after sunchronizing the server.
