### ISSUE TITLE
Empty password databases from KeepassX are not openable

### ISSUE THREAD

**Issue by anoadragon453** [Kunzisoft/KeePassDX#2]
If you attempt to create a database with an empty password, the app tells you off for it, but then goes ahead and makes the database anyways, which you then cannot open as you're not allowed to open a database without a password or keyfile.

IIRC Keypass *does* support creating and opening databases with a blank password and no keyfile, so ideally your app should allow users to open those databases.

Perhaps instead of preventing them from creating them with empty passphrases, stick a earning on screen that warns them that their data will not be secure, but allow them to create the database anyways.

**Comment by J-Jamet** [comment]
Thanks for your return. I'll follow your advice, display a dialog and leave the possibility to open without password.

**Comment by J-Jamet** [comment]
I added checkboxes to select password and / or keyfile and a dialog when there is an empty password.
Also a new screen for database creation.
I'll put the beta online in the week when I'll have finished the other developments and tested the code.

**Comment by anoadragon453** [comment]
Awesome, will test it out when it's live!

**Comment by J-Jamet** [comment]
Done in **2.5.0.0beta3** but there are a new issue : 
* Empty password with checkbox checked in Keepass DX <=> Empty password with checkbox not checked in Keepass DX <=> Empty password whit checkbox not checked in KeepassX (Linux)
* Empty password with checkbox checked in KeepassX (Linux) cannot be open yet in Keepass DX

It's a little more complicated to solve.

**Comment by anoadragon453** [comment]
Ideally doing the same actions on each client would produce the same outcome. Is there any special reason KeepassX databases with empty passwords can't be opened yet in Keepass DX?

**Comment by J-Jamet** [comment]
It's planed to have the same feature on both, but the methods of creating and opening by encryption must be refactored. I have to look exactly why.

**Comment by anoadragon453** [comment]
Thanks for the info. To be honest it's not the biggest issue in the world right now, but definitely will be a blocker for a niche amount of users so should be fixed at some point :)

**Comment by J-Jamet** [comment]
I understand, that's why I leave the issue open. I try to make the program as stable as possible according to user needs. ;)

**Comment by J-Jamet** [comment]
Fixed in the new version 2.5.0.0beta9 ;)
