### ISSUE TITLE
KeePassDX does not get listed while opening .kdbx/.kdb from within Encdroid.

### ISSUE THREAD

**Issue by ashjas** [Kunzisoft/KeePassDX#201]
I generally also use a 2nd level encryption by putting my keepass db encfs encrypted.
For this purpose, i use encdroid. The issue is that while opening kdbx files from within encdroid app, i dont get the option of KeePassDX app in the open-with prompt. Strangely, all other keepass ports like keepassdroid/keepass2android do get listed.

I am unsure if this issue is related to encdroid app or KeePassDX. But since, other apps show up on the open-with prompt, i think this needs to be handled at KeePassDX side.

I also tried to check sources of Keepassdroid/keepass2android , and their AndroidManifest.xml files seem to be similar in declaring the intent-filters for opening up kdbx files.

Moreover since this is a fork of  keepassdroid, which does get listed, i guess something got changed with this fork down the line, which causes this.

Can you please check? @J-Jamet 
Thanks.

**Comment by J-Jamet** [comment]
Thanks for the feedback, I'll look at why the intent-filter does not work properly in this case.

**Comment by ashjas** [comment]
Any updates on this please?

**Comment by ashjas** [comment]
Thanks for fixing this!:grinning:
