### ISSUE TITLE
lost files kdbx

### ISSUE THREAD

**Issue by bastien625** [Kunzisoft/KeePassDX#203]
the .kdbx files are lost in android : - i didn't install by default on" /emulated/..." - just at DCIM.. I ' ve make the test: 3 x .. and they have dispair always on the  folder : emulated .. (unknow this folder)

**Comment by J-Jamet** [comment]
This is not a problem of KeePass DX.
Your Android device creates symbolic links for security reasons and the /emulated folder is only a visual path that is rebuilt because it points to accessible folders on your device.
I do not understand why you do not use the usual method of your file manager.
