### ISSUE TITLE
Request : Support for One Time Password

### ISSUE THREAD

**Issue by elmatou** [Kunzisoft/KeePassDX#204]
Hi,
thx for your work, finaly a keepass implementation rich featured & nice UI.

One thing missing in keepass core is one time password (OTP, TOTP) support. 
I'm mean being able to store the OTP seed in the database and generate the one time password.

Every service provider push you tu use two factor authentication, and regular databases leak seems to confirm that's 2FA is absolutely necessary.

Several attempt to solve this with keepass, work prety well. KeepassXC add support few months back.

Do you think it could be in the keepasssDX roadmap ?

**Comment by nr458h** [comment]
There is already a request for this topic. Please see #70. As I understood there is first support for attached data necessary, before 2FA can be implemented.

**Comment by elmatou** [comment]
Sorry for the duplicate, I did search trough the issues but didn't find #70.
