### ISSUE TITLE
Add support for Cozy.io cloud integration

### ISSUE THREAD

**Issue by yerbestpal** [Kunzisoft/KeePassDX#207]
[Cozy](https://cozy.io/en/) is a popular cloud storage service and I think it would benefit many users to have you support opening databases stored there.

**Comment by J-Jamet** [comment]
I did not know this cloud, I will watch it. But in any case, no cloud system will be directly integrated with KeePass DX, there are too many and it does not respect the encapsulation systems of Android. The goal would rather be to propose an alternative file manager that could contain the connection codes to the cloud.

**Comment by yerbestpal** [comment]
Hrm, I see. I've found a workaround anyway by opening the database file through the cloud storage app. maybe the issue should be closed now, seeing as how it doesn't seem to serve any need.
