### ISSUE TITLE
Entries and subgroups are not displayed after changing theme

### ISSUE THREAD

**Issue by Grossdm** [Kunzisoft/KeePassDX#208]
**Update**: I updated to KeePassDX Version 2.5.0.0beta18 Build libre.
The problem persists with this newer version.

I am using Version: 2.5.0.0beta17-libre of KeePassDX.

After changing KeePassDX's theme and leaving settings, the overall view appears normal.
However, after opening any group there are no entries or subgroups displayed - it appears that the group is empty.

I found that if I search for an entry, the appropriate matches are displayed. If I select one of the matches, the entry opens properly.
After having searched and opened an entry, KeePassDX seems to behave properly.
That is, groups no longer appear empty.

Despite having backups of my database, this issue did spook me initially. 😲

Thanks for KeePassDX.

Doug®

**Comment by J-Jamet** [comment]
Thank you for the detailed feedback, I will look to correct this anomaly. It may be from a corrupt or improperly formatted entry that prevents the entire list from being displayed in a group. Do you have a database to test the problem?

**Comment by Grossdm** [comment]
Are you suggesting that I create a test database to try to reproduce the behavior?

That sounds like rather logical troubleshooting. ☜(ﾟヮﾟ☜)

**Comment by J-Jamet** [comment]
I only say that it is difficult to solve a problem if I can not reproduce it, so if you have a database without sensitive data that I can use to develop and replicate the issue, it would be easier. The first step is really that I reproduce the problem and with all my tests, everything works fine, What is the model of your device?

**Comment by Grossdm** [comment]
My "Paleophone"  is a Verizon Galaxy Note 3.

[I uploaded some details for you to Mega.](https://mega.nz/#F!D2xQzYjA!_PtpD2ySfGo5UZopst9bfA)

I haven't tried a new, test database yet.

Doug®

**Comment by J-Jamet** [comment]
With new versions, is this problem solved for you?

**Comment by J-Jamet** [comment]
Closed for inactivity
