### ISSUE TITLE
New fingerprint on device breaks keepass DX fingerprint store

### ISSUE THREAD

**Issue by Edwin-VC** [Kunzisoft/KeePassDX#212]
I am a newbie to android and ended Op removing my fingerprint on the device and adding it again. But I could not re-initiate the fingerprint for KeePass DX. Got an error 'could not delete fingerprint'. Reinstalling the app fixed it.

**Comment by J-Jamet** [comment]
Yes it may be a fingerprint problem already deleted, I will try to reproduce the issue to be able to correct it but I do not know if I will be able to because I work on emulator.

**Comment by J-Jamet** [comment]
The problem should be solved with version 2.5.0.0beta23, tell me if it's OK for you?
