### ISSUE TITLE
Unable to empty recycle bin

### ISSUE THREAD

**Issue by OmarEXE** [Kunzisoft/KeePassDX#213]
Hi, I'm running android 7.0 and using KeePassDX version 2.5.0.0beta18
When i try to delete an entry it goes to the recycle bin but there is no option to empty it so when i try deleting them individually from inside the recycle bin they keep coming back. So now the only fix for me is to edit the deleted entries and replace them with blank texts.

**Comment by J-Jamet** [comment]
The recyclebin must be refactored, the bug will be fixed during the code change.
Linked to #155 #91 #54

**Comment by beerisgood** [comment]
Sadly still not fixed yet
