### ISSUE TITLE
fingerprint scanner scans even if i've never set a fingerprint

### ISSUE THREAD

**Issue by RoughCurve** [Kunzisoft/KeePassDX#216]
using lineageOS, on android 7.1.2, the privacy guard says KeePassDX used my fingerprint scanner 200+ times, although I've never used it and not planning to (while the feature is off in the app's settings).

**Comment by J-Jamet** [comment]
Thanks for the feedback, the device should not have access to the fingerprint manager when the setting is off. I will completely remove the initialization for the next version to fix the problem. Sorry about that.

**Comment by J-Jamet** [comment]
The problem should be solved, disabling in settings removes the instance of the object that initializes the fingerprint. It will still need to migrate to AndroidX to use the new API.
