### ISSUE TITLE
Corrupted database

### ISSUE THREAD

**Issue by ciphersimian** [Kunzisoft/KeePassDX#217]
I decided to try out KeePassDX on my new Android 8.0 moto g(6).  I have a very large AES-256 (AES-KDF, 6000 rounds) encrypted KeePass 2.0 (*.kdbx) database (~89MB) which I've been using for a very long time with KeePassDroid first, and eventually Keepass2Android.

Within a day with KeePassDX my database got corrupted due to truncation.  The normally ~89MB was ~64MB after being modified and saved in KeePassDX and could not be opened.  Luckily I had a backup so I only lost the one password I had just added.

My suspicion is that this happened when I was switching activities while the database was being written.  I do this all the time on Keepass2Android due to the length of time it takes to encrypt and write out my very large database.  On KeePassDX however this is apparently a very bad idea.

I definitely won't be using this app anymore as the hassle of a corrupted database is easily the worst thing that can possibly happen to a password store and this situation should be much more defensively coded against.

**Comment by Toorero** [comment]
I think i experienced an issue for the same reason, while adding a password and then switching the app.

Perhaps the error was not a result of the switching. I could imagine it relates to the fact that the db was still open, while using the Auto-Fill feature of Android, so there were two instances trying to access the db. 

Luckily i was still able to open the db via KeePassXC.

The error KeePassDX printed out was:

> Datenbank kann nicht geladen werden **precondition: START_TAG (Position:END_TAG </Binary>@1:54528 in java.io.InputStreamReader@d4ecb0d)**

**Comment by jeisoncp** [comment]
> The error KeePassDX printed out was:
>
>    Datenbank kann nicht geladen werden precondition: START_TAG (Position:END_TAG @1:54528 in java.io.InputStreamReader@d4ecb0d)

That's the same error I got here right now.

**Comment by MikeGolden** [comment]
Same issue here. I switched device recently. Idk if that's the case, but on my previous OnePlus3T i haven't got any issue even once. with my new phone got database corruption(same error message mentioned above)  3rd time during last 2 weeks.

**Comment by J-Jamet** [comment]
I publish the new version tell me if it's ok for you.

**Comment by Toorero** [comment]
Thank you. I think there will be some delay till it's available on F-Droid. Also the error happens occasional. I try my best to reproduce the error and will feed back the moment i can draw myself a conclusion.

Nevertheless thanks for the updated version.
