### ISSUE TITLE
Add mnemonics to generator

### ISSUE THREAD

**Issue by stp-ip** [Kunzisoft/KeePassDX#218]
Even so a password generator makes it more unlikely to type passwords manually or remember them. An option to use mnemonics/passhprases would be great.

Could be using a custom word list or one that is widely used such as [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) or [slip39](https://github.com/satoshilabs/slips/blob/master/slip-0039/wordlist.txt).

Just an idea. Still trying around with KeePassDX as a replacement to my older setup, but I thought it might be a nice idea anyway. Thanks for giving more and awesomely designed options.

**Comment by patarapolw** [comment]
I have tried to create autogenerated mnemonics, but it does work well. Better try to (create and) type your own mnemonics.

If you are looking for a Passphrase-based password generator, it is here -- https://github.com/patarapolw/KeePassDX-diceware

**Comment by J-Jamet** [comment]
Partol did a good job on this feature, but I have to integrate it with application size and integration constraints. It's a big feature, I think about it, it will be integrated with the time.

**Comment by alexmachina** [comment]
Just for the sake of curiosity, what are the complexities of this mnemonics generation exactly?

**Comment by seniorm0ment** [comment]
- Came here to suggest passphrase generation as implemented in KeepassXC as a tab on the generator.

- This alongside visible entropy for the current generated password, as suggested in 

- Also suggest adding a quick refresh button to cycle generated passwords.

**Comment by J-Jamet** [comment]
I just implemented passphrase in the same way as KeePassXC, if improvements are requested (like passphrase with special characters) it will be necessary to open a new issue.

**Comment by strider72** [comment]
Just curious which word list you used.  Standard Diceware? the EFF list?

(and thanks for this feature!)

**Comment by J-Jamet** [comment]
The library used is based on a large EFF list. It is possible to add more dictionaries later but I think it is already good for a start.
https://github.com/GoSimpleLLC/nbvcxz/blob/master/src/main/resources/dictionaries/eff_large.txt

**Comment by rusty-snake** [comment]
Can I manually replace the word list?
