### ISSUE TITLE
Does not start (white screen) after reboot of the phone

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#22]
**Version:** 2.5.0.0beta3-libre
**OS:** Android 7.1.1
**Phone:** Moto E4

The app works fine until a shutdown/reboot of the phone.  Trying to open KeePass DX just results in a white screen and it will not start.  Uninstalling/reinstalling "fixes" this.

Thanks for your work.

**Comment by J-Jamet** [comment]
Hello, is your problem still present ? What's the state of the app before rebooting the phone (in connection view, in modification, in list or in entry ? (It could help me I can't reproduce the problem.)
