### ISSUE TITLE
Focus search field automatically

### ISSUE THREAD

**Issue by msoose** [Kunzisoft/KeePassDX#220]
Just a feature request here.

When opening the application, it would be nice to have the option to automatically focus the search field so the keyboard pops up, ready for input to search -- would eliminate one extra step on finding an entry.

**Comment by J-Jamet** [comment]
I agree, it's beneficial for the UX, I'll try to add this feature for future updates.

**Comment by J-Jamet** [comment]
A setting has been added for this functionality.
