### ISSUE TITLE
Use a clearer monospace font

### ISSUE THREAD

**Issue by 0xdec** [Kunzisoft/KeePassDX#223]
To my eyes, the lowercase "L" in the provided font looks like a "1", so whenever I copy a random password by hand I have to verify that I'm typing the correct characters.

**Comment by J-Jamet** [comment]
Which font do you want to put?

**Comment by DJCrashdummy** [comment]
well... the fist font which comes in my mind for such cases is [FreeMono](https://savannah.gnu.org/projects/freefont/).

**Comment by 0xdec** [comment]
I would personally vote for [Fira Mono](https://mozilla.github.io/Fira/). It's open-source, created by Mozilla, and clearly distinguishes between similar characters.

**Comment by J-Jamet** [comment]
Font replaced by FiraMono-Regular
