### ISSUE TITLE
Please inform about the need instalation of another app (oi file manager)

### ISSUE THREAD

**Issue by sefernet** [Kunzisoft/KeePassDX#224]
The lack of own file manager to access the file database imposes the need of install another app (oi file manager)

Im very disappointed about it...

**Comment by J-Jamet** [comment]
It was chosen to use the normal methods of file management for phones and tablets. 98% of devices now have a file manager to select a file on the device. If there is none, the app leaves the choice to the user to install the one he wants. This also avoids possible security flaws when selecting files (keyfile or .kdbx).
Currently, there is still the folder selection that uses the com.nononsenseapps:filepicker library, but may be modified.
Which solution would bring you satisfaction?
