### ISSUE TITLE
Password display box should be multiline, if the password is long

### ISSUE THREAD

**Issue by patarapolw** [Kunzisoft/KeePassDX#225]
If I generate a passphrase via passphrase method, it is common that the password is very long, like 50 characters, which is secure (the longer the better). However, not every part of the password is shown at once. Have to scroll.

![screen shot 2019-01-16 at 12 50 18](https://user-images.githubusercontent.com/21255931/51229158-f3084780-198d-11e9-931b-48ae36965098.png)

**Comment by J-Jamet** [comment]
I put the password on one line deliberately because on many it removes visibility on the other elements, if there are notes or other entries. Why do you want to see it in full? You copy it manually?

**Comment by patarapolw** [comment]
Yes, I copy it manually, when I am on PC, and I cannot use Keepass desktop for some reasons.
