### ISSUE TITLE
Code differences between F-Droid version and Play Store version?

### ISSUE THREAD

**Issue by Mattrazol** [Kunzisoft/KeePassDX#226]
Hello I was reading the F.A.Q. section of your website and I stumbled across the section where you talk about the differences between the 3 versions of the App. I don't quite get this statement about the libre version:

"it is guaranteed without any proprietary code and is not linked to any closed service."

Does this mean that the Play Store version either the Free or the Pro has some codebase or service differences vs the Libre one? If so which are they?

Thanks in advance for the answer and clarifications..

**Comment by J-Jamet** [comment]
Hello, thank you for your interesting question.
For the moment, there is no difference between Libre, Free and Pro versions code (except for access to the themes). Later, the pro version will offer content to easily fill in entries for the most used commercial services (mainly sign icons and templates for google, amazon ...) but no services in the background of the app.
The Libre version will remain a version without any proprietary content and will not offer basic tools facilitating the recording of commonly used inputs.
It must also be remembered that the APKs uploaded by google are modified by google servers to apply a specific signature and that the applications of the Play Store are monitored by Google, so you have to trust the company Alphabet.
I personally use the Libre version but many people use the versions of the Play Store, it's as you wish.

**Comment by J-Jamet** [comment]
I added the text to the FAQ, I close this ticket.
