### ISSUE TITLE
Mixplorer does not open remote files

### ISSUE THREAD

**Issue by west89** [Kunzisoft/KeePassDX#227]
Hello,
I am having trouble opening my .kdbx database from my Synology Diskstation.
Always when open file can not be streamed.
Awerden.
I also noticed that the Pfad is not correct for the keyfile.

Mixplorer content://com.mixplorer.fileProvider/CEWvRkIDpqtERwAof2IuRCAf2IuRCBOQ-n8%3D.key

Onplus Dateibrowser
content://com.android.externalstorage.documents/document/primary%3AKeepass%2FKeepass.key

Even the manual input of the Pfad does not work    /storage/emulated/keepass/keepass.key

**Comment by J-Jamet** [comment]
What does Pfard and Pfad mean?
For me, it is that your file manager does not provide standardized links, but it is to test.
The link content://com.android.externalstorage.documents/document/primary%3AKeepass%2FKeepass.key seems correct.

**Comment by west89** [comment]
Sorry for the late answer.
For me it looks like there won't be another request to access Synology Diskstation with user and password input.
With Keepas2Android App you crawl a new input and enter your username+password.

**Comment by west89** [comment]
Sorry for the late answer.
For me it looks like there won't be another request to access Synology Diskstation with user and password input.
With Keepas2Android App you crawl a new input and enter your username+password.

**Comment by kronn** [comment]
@J-Jamet Pfad is german and means path. Pfard just seems like a typo (although a very cool sounding one :smile: )

**Comment by J-Jamet** [comment]
I will check the compatibility of MixPlorer and add it to the wiki.

**Comment by J-Jamet** [comment]
I looked at the operation of Mixplorer, and there seems to be no problem for me, if there is a problem I advise you to approach the developer of the application. I added the app to the wiki.
