### ISSUE TITLE
Database name gets scrambled when imported

### ISSUE THREAD

**Issue by w-canvas** [Kunzisoft/KeePassDX#229]
When imported a database created in Keepass2Andtoid the name showed up as "wJ4LI7ZRlNhMFQoPMw==" whith the following address:

> content://com.google.android.apps.docs.storage/document/acc=1;doc=encoded=MhPuos7vB6UWQgTsSIDL429Wm9FoNAf0s8g/wJ4LI7ZRlNhMFQoPMw==

When importing a local backup of the same file the name shows up as "499" whith the following address:

> content://com.android.providers.downloads.documents/document/499

Only when the file is stored locally and has **no underscores** it displays the right name and place:

> content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/backup/passwords/dataBasecloudPasswordsBackUp31ene19

Files created natively show normal names.

Device: Pixel 3 XL
OS: stock Android with ElementalX kernel.
version: 2.5.0.0beta18

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/issues/117
