### ISSUE TITLE
Upstream-update - KeePass 2.2.1

### ISSUE THREAD

**Issue by Dionis0s** [Kunzisoft/KeePassDX#23]
Please update the fork to KeePassDroid (2.2.1).

https://github.com/bpellin/keepassdroid/blob/HEAD/CHANGELOG

Thank you for your great work! :+1:

**Comment by J-Jamet** [comment]
The project is already merged with this version in https://github.com/Kunzisoft/KeePassDX/tree/upstream-update branch. I need to finish other developments to update and publish the new version. ;)

**Comment by J-Jamet** [comment]
Done in 2.5.0.0beta4
