### ISSUE TITLE
Improve Keyboard Change

### ISSUE THREAD

**Issue by theincogtion** [Kunzisoft/KeePassDX#230]
I am really struggling with the "automation  options".

**MagiKeyboard**
If I have KeePassDX opened in in the Background and I open up a specific entry with user name and password I can not use it in MagiKeyboard 
As soon as I am back in the login form magikeyboard must be activated and I have to logon to my keepass database AGAIN and AGAIN select the entry which was already opened up.

**AutoFill**
The auto form filler has basically the same problem: Every time I want to use it I have to enter my password for keepass even if the entry which I want to use is already opened.

Is this behavior by design or is this my failt?

**Comment by J-Jamet** [comment]
The refactoring of connection flows for the recovery of entries is under development and will be available in the next release.

@see https://github.com/Kunzisoft/KeePassDX/issues/195 https://github.com/Kunzisoft/KeePassDX/issues/193 https://github.com/Kunzisoft/KeePassDX/issues/141 
https://github.com/Kunzisoft/KeePassDX/issues/182

**Comment by Wilker-a** [comment]
i am not sure if this is what you are trying to tell, but a button to "send to Keyboard" would be useful in the entry view screen

**Comment by theincogtion** [comment]
> 
> 
> The refactoring of connection flows for the recovery of entries is under development and will be available in the next release.
> 
> @see #195 #193 #141
> #182

Just tested the Keyboard and its not really convincing. I select the entry in KeePassDX, go to the website (by clicking the link from the opened entry) and switch to the MagiKeyboard. Now it jumps back to KeePassDX and again I have to reselect the entry. Why isn't the keyboard just using the already opened entry?

**Comment by J-Jamet** [comment]
I do not understand, I have tested and the option "magikeyboard settings -> Entry Selection" should work. Can you tell me what is your device and version of your Android?

**Comment by theincogtion** [comment]
I was not aware of this option it was disabled by default. Just tested it and worked fine! Thanks a lot.
As soon as TOTP is working this will replace my keepass2android app and I will donate for your effort!

**Comment by J-Jamet** [comment]
The option is not checked by default because people do not use the Magikeyboard. I will try to detect the activation of the keyboard so that the option activates at the same time but I do not know if it is really possible, I will investigate. ;)

**Comment by theincogtion** [comment]
I just installed keyboard switcher. What do I have to change to make sure the keyboard switches as soon as I open up an entry?

**Comment by J-Jamet** [comment]
This is not possible at the moment because the Android operating system does not allow this change by the user. The automatic change of keyboard requires an elevation of the rights ('root' which is very dangerous on a device who manages the passwords). It is possible that I do a little program for those who want this feature but from a security point of view it is very questionable.

Keyboard Switcher is used to change the keyboard more easily for those who can not do it from their main keyboard (for example if the long press on the spacebar does not work) but does not automatically detect entries to change the keyboard .

**Comment by theincogtion** [comment]
Ok I see.
I uses this option: https://play.google.com/store/apps/details?id=keepass2android.plugin.keyboardswap2&hl=en

I had to elevate right via adb:
`pm grant keepass2android.plugin.keyboardswap2 android.permission.WRITE_SECURE_SETTINGS`

**Comment by J-Jamet** [comment]
Ok I will study the question about the security and use of this command with ADB

**Comment by J-Jamet** [comment]
I open a new issue (https://github.com/Kunzisoft/KeePassDX/issues/311) for the keyboard switch feature in order to have a better organization of the tickets. I close this one.
