### ISSUE TITLE
Cannot view notes

### ISSUE THREAD

**Issue by kuba-orlik** [Kunzisoft/KeePassDX#234]
I store some important information about some of my credential in the "Notes field" in KeePassX on my desktop. When viewing the database file with KeePassDX, I can't see the notes.

**Comment by J-Jamet** [comment]
I just retest by creating a database with notes from KeePassX and it works in KeePassDX. Can you attach a test database whose notes can not be read?

**Comment by kuba-orlik** [comment]
In fact I created a test database with notes in KeePassX and it works in KeePassDX. Could there be something wrong with my original database? I've tried repairing it and cloning the password with notes to a new database, but failed to reproduce it. Although it probably falls outside of the scope of this repository, I'd be thankful for any suggestions on what to try next

**Comment by J-Jamet** [comment]
This is probably due to a partial corruption of the database, to know exactly where, it would be necessary to decode your file and check the data tree with a debugger.

**Comment by J-Jamet** [comment]
Without further information, I close this ticket.
