### ISSUE TITLE
Can't copy passwords

### ISSUE THREAD

**Issue by 2011** [Kunzisoft/KeePassDX#235]
I seem to be having the same problem referenced in bugs #148 and #159 (both now closed). The copy button for all passwords in the database is grey, and I can copy the usernames, but not the passwords.

Running 2.5.0.0beta18 Build libre.

**Comment by J-Jamet** [comment]
This is no longer a problem, the feature is grey by default because dangerous. If you pressed "cancel" the first time on the message dialog, the button remains grey and the dialog is not displayed again. But you can reactivate the feature in the settings: "App setting" -> "Clipboard trust"

**Comment by 2011** [comment]
Sorry, didn't know that was the default (also just now found that option in "Form filling" as well as "App settings") - and yes I did know that it was dangerous (I just thought something was broken). Might completely remove the clipboard icon for the password if the trust is turned off (just to make it clearer for the user). I might not even have allowed the username to go through the clipboard (if you have to send the password through the virtual keyboard) it is probably quicker to send the username that way as well rather than go through the clipboard).

Looks like the security for copying and pasting will be improved soon.

https://www.xda-developers.com/android-q-block-background-clipboard-external-storage-permissions-downgrading-apps/

One question about the virtual keyboard. When it is active, I see icons to past the URL, username, and password. Is the fourth one supposed to be notes? When I click on it, I get an (empty) text box popping up on the upper right of the screen, but there is no content in it.

**Comment by J-Jamet** [comment]
The empty box corresponds to the location for displaying custom entries.
