### ISSUE TITLE
Typing password may freeze the app in Android Pie

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#236]
May be due to fingerprint recognition.

**Comment by cslux** [comment]
I can confirm that it is due to the fingerprint recognition. Turning "Fingerprint scanning" off, solves it.

- Android 9
- Huawei P20

**Comment by J-Jamet** [comment]
I added a handler to avoid the trouble but I can not reproduce it. Tell me if it's OK.

**Comment by J-Jamet** [comment]
The new version should solve the problem

**Comment by AlterDepp** [comment]
I have still the same problem with version 2.5.0.0beta22

**Comment by J-Jamet** [comment]
Ok,  the problem is that I can not reproduce the issue. If fingerprint recognition is involved, I think it will be resolved when I upgrade the API but I must already migrate to AndroidX.

**Comment by AlterDepp** [comment]
The problem only exists, if I enable fingerprint recognition.

**Comment by J-Jamet** [comment]
The problem should be solved with version 2.5.0.0beta23, tell me if it's OK for you?

**Comment by AlterDepp** [comment]
Version 23 is not available in F-droid until now.

**Comment by J-Jamet** [comment]
The F-Droid build server can take a week to upgrade an app.

**Comment by rootkiwi** [comment]
Seems like the build is failing on F-Droid:

> 'Build.py failed on server for com.kunzisoft.keepass.libre:2.5.0.0beta23' 

https://f-droid.org/wiki/page/com.kunzisoft.keepass.libre/lastbuild

**Comment by J-Jamet** [comment]
Linked to #347

**Comment by AlterDepp** [comment]
Tried to test version beta23, but I do not know, how to store my fingerprint. The help text says, I should press »Einstellungen -> Sicherheit -> Fingerabdruck«, but I don’t have this. I tried »Einstellungen -> Advanced unlock -> Fingerabdruckscanner«. I turns on, but no dialog to store my fingerprint is shown.

**Comment by Raketenphysik** [comment]
This is quite an old bug report, but I am confronted with the exact same issue running the latest version on an Samsung Galaxy Tab S7 and LineageOS. Typing in the master password the app freezes instantly. Turning of biometric login solved this. Can somebody confirm similar behavior. Please let me know if you need me to provide any further information.

**Comment by J-Jamet** [comment]
From memory, LineageOS has trouble accessing the secure Keystore due to a certificate issue. Can you provide logs with the procedure? https://github.com/Kunzisoft/KeePassDX/wiki/Log

**Comment by J-Jamet** [comment]
And since your problem does not exactly match this issue with the Android version, could you please open a new bug? Thank you.

**Comment by Raketenphysik** [comment]
Thanks for your reply!

-> #2129
