### ISSUE TITLE
Password is pasted into the username field in MyChart app

### ISSUE THREAD

**Issue by camingus** [Kunzisoft/KeePassDX#241]
In the [MyChart](https://play.google.com/store/apps/details?id=epic.mychart.android&hl=en) app KeePassDX pastes the password in both the username and password fields.

**Comment by J-Jamet** [comment]
When are you using the autofill?

**Comment by camingus** [comment]
I'm unsure of what autofill means but I'll describe my experience.

1. I open the app
2. A "sign in with KeePass DX" pop up appears
3. I tap on it
4. I login with my finger print
5. I select my MyChart entry
6. I'm back at the MyChart page with a new popup that contains my MyChart entry with my user name. The username is displayed properly in this pop up
7. I tap on the pop up
8. My password is pasted into the username field.

I'm guessing you're asking this question because it didn't repro for you? I can go back and look at some settings and see if I can find something off about that entry. Also I'm more than willing to collect any information you need. Other than my username and password of course (:

**Comment by nstetter** [comment]
I experience the same problem using Brave Browser.
Just happened as I tried to login to github to post this comment.

0) open github in Brave
1) click username field
2) select 'Fill with KeepassDX'
3) unlock database, select github entry
4) back in brave select 'Fill with KeepassDX' again, now displaying the username
5) password gets pasted in username field and vice versa

**Comment by J-Jamet** [comment]
I improved the autofill recognition algorithm. You will tell me if in version 2.5beta29 the problem is solved for you.
