### ISSUE TITLE
Cannot open database with invalid Auto-Type

### ISSUE THREAD

**Issue by juwancase** [Kunzisoft/KeePassDX#242]
- App version: 2.5.0.0beta18
- Android version: 9
- Database settings:
  - Encryption: ChaCha20
  - Key derivation: Argon2
  - Transform rounds: 12
  - Memory usage: 64MB
  - Parallelism: 4
  - Size: < 210KB
  - Attachments: Cleared (workaround for #183)

The app throws "no tags open" error while opening a database. Using KeePassXC, I found the cause to be a history of an entry. Problem resolved after removing that history.

I restored to that problematic history, I found the custom Auto-Type entry is empty but its radio button is selected. In normal situation, when restoring to a history that doesn't have custom Auto-Type, "Inherit Auto-Type" would be selected instead. So, somehow I have an invalid history with null Auto-Type value?

Anyway, since Auto-Type is not relevant/implemented in this app, perhaps its value can be ignored?

Logcat:
```
W System.err: 	at com.kunzisoft.keepass.database.action.LoadDatabaseRunnable.run(LoadDatabaseRunnable.java:71)
E com.kunzisoft.keepass.database.action.LoadDatabaseRunnable: Could not load your database.
E com.kunzisoft.keepass.database.action.LoadDatabaseRunnable: java.io.IOException: read end tag AutoType with no tags open (position:END_TAG </AutoType>@1:15 in java.io.InputStreamReader@9e0a0e9) 
```

**Comment by J-Jamet** [comment]
Thanks for the detailed feedback,
Yes the value of the autotype is ignored for the moment, I will look to correct this problem as I work on the refactoring of elements and the management of the parameters.

**Comment by J-Jamet** [comment]
The old code did not correctly handle the value of the autotype and the search (no correct management of the null values). I can not test but you will tell me if it is better with version 2.5.0.0beta23.
