### ISSUE TITLE
Won't open in Samsung DeX mode

### ISSUE THREAD

**Issue by yodarunamok** [Kunzisoft/KeePassDX#245]
When attempting to open in on a Samsung Note 9 under DeX I see the error: "KeePass DX can't run in Samsung DeX..." It runs just fine in phone mode, just not in Samsung's desktop experience. Samsung provides some relevant information [here](https://developer.samsung.com/samsung-dex/modify-optimizing).

**Comment by J-Jamet** [comment]
I don't know what Samsung DeX is, and I do not have a device to test, I will document.

**Comment by chris5a** [comment]
I am looking for Samsung DeX integration as well. It would be a great feature to have.
FYI - https://www.samsung.com/global/galaxy/apps/samsung-dex/
It acts like an Android OS when you plug your phone into a monitor instead of just mirroring the phones display.

**Comment by goodevilgenius** [comment]
@J-Jamet There are two main requirements, as detailed in the link in the issue:

It has to be resizable:

```xml
<application android:resizeableActivity="true">
  <activity ... />
</application>
```

It must work with a mouse and keyboard:

```xml
<uses-configuration  android:reqTouchScreen="finger" />

<uses-feature  android:name="android.hardware.touchscreen"  android:required="true" />
```

Even without a Samsung device to test, you can test that it's resizable and works with a mouse and keyboard on just about any recent device.

**Comment by Chugi-vu** [comment]
Way to launch  KeePass DX in Samsung DEX mode
In DEX mode:

1/ Go to setting

2/ Tap on "Samsung Dex"

3/ Tap on "About Samsung Dex"

4/ Tap 5 times on "Samsung Dex Version"

5/ Reboot DEX Mode

6/ In DEX Mode go to setting and tap "Samsung Dex"

7/ Tap "Samsung LABS"

8/ Enable checkbox "Force Resize"

![Screenshot_20200129-205641_KeePass DX](https://user-images.githubusercontent.com/60095740/73385150-afa12280-42dd-11ea-99ba-a409893d0f44.jpg)

**Comment by alexanderadam** [comment]
There must be a way to get this working without going into developer mode.

@J-Jamet did you add

```xml
<uses-configuration  android:reqTouchScreen="finger" />

<uses-feature  android:name="android.hardware.touchscreen"  android:required="true" />
```

like [mentioned above](https://github.com/Kunzisoft/KeePassDX/issues/245#issuecomment-562627088)?
I'm currently using a Samsung S6 Tablet (a recent device) and I have the feeling that the app definition could be the reason for not running in DeX.

Otherwise you can check [things in the Samsung DeX documentation](https://developer.samsung.com/samsung-dex/modify-optimizing.html) and I will test your builds, if you want.

**Comment by J-Jamet** [comment]
> @J-Jamet did you add
```
<uses-configuration  android:reqTouchScreen="finger" />
<uses-feature  android:name="android.hardware.touchscreen"  android:required="true" />
```
> like mentioned above?

No no, I had verified that this code was not present.

You have to test with real compatible devices. For the moment I don't have one so I will leave it to the people concerned for now. ;)

**Comment by alexanderadam** [comment]
I have three different compatible devices available. So I can test any of your builds.

**Comment by J-Jamet** [comment]
I tried, it works but a lot of options are locked in the parameters and I cannot launch DeX mode with this method.
Otherwise you can change the settings in the code and compile KeePassDX to improve what you want! ;)

**Comment by alexanderadam** [comment]
> Otherwise you can change the parameters in the code and compile KeePassDX to improve what you want!

Sure thing.
Is there a Docker container that includes the build chain that I need for creating an apk for KeePassDX?
I'm obviously not a mobile dev so I obviously would prefer a container image that I can cleanly remove afterwards.

And is there any documentation how to build it in general? [The FAQ](https://github.com/Kunzisoft/KeePassDX/wiki/FAQ) and the README doesn't seem to include anything build related and the repository doesn't seem to have any `doc` or `documentation` directory.
So can you please point me to the build instructions?

**Comment by J-Jamet** [comment]
No there is no docker. For the build, the easiest is to use Android Studio as an IDE, it allows you to build easily.
Otherwise I'll look to get a DeX compatible device, which model would you advise me? (just for testing) one with the smallest memory.

**Comment by J-Jamet** [comment]
> Also I'm not sure whether this is helping but Samsung also has an App Testing Guide for windowed / DeX applications.

I have already tested with this method and have no problem, that's why I closed this issue.

**Comment by alexanderadam** [comment]
> For the build, the easiest is to use Android Studio as an IDE, it allows you to build easily.

It seems that [there are a few images and Dockerfiles with Android Studio](https://github.com/search?q=%22android+studio%22+language%3ADockerfile&type=Repositories&ref=advsearch&l=Dockerfile&l=). I will try a few of them in the following days and hopefully I will manage to build a apk.

> I'll look to get a DeX compatible device, which model would you advise me? (just for testing) one with the smallest memory.

According to Samsung "_[All flagship models released after Galaxy S8/S8+](https://www.samsung.com/hk_en/support/mobile-devices/galaxy-s8-what-devices-support-samsung-dex/)_" should support DeX. [Including the Galaxy S9, S10, S20, Note8, Note9 and Note10 series and Galaxy A90 5G](https://en.wikipedia.org/wiki/Samsung_DeX#:~:text=including%20the%20Galaxy%20S9,%20S10,%20S20,%20Note8,%20Note9%20and%20Note10%20series%20throughout%20Android%20Pie.%20The%20Galaxy%20A90%205G%20is%20the%20first%20Galaxy%20A%20phone%20with%20DeX%20support.) As well as the Galaxy Tab S4, S5e and Tab S6.

I'm not sure which of them has the _smallest_ memory (you mean RAM, right?), though. But I believe all of them have at least 4 GB of RAM.

**Comment by alexanderadam** [comment]
@J-Jamet do you know whether there's any possibility to check [what 1Password might have changed to fix the Input Method Service bug](https://mobile.twitter.com/michaelverde/status/1305658074716274688) on Samsung Dex and maybe apply this on KeePass DX as well?

**Comment by J-Jamet** [comment]
> Just to be sure: the lines have to be inserted into the AndroidManifest.xml, right?

No, it is clearly indicated:

"**Do not** explicitly declare the touchscreen support as it may disable the mouse and the keyboard interactions. This explicit declaration is shown in the code below."

> do you know whether there's any possibility to check what 1Password might have changed to fix the Input Method Service bug on Samsung Dex and maybe apply this on KeePass DX as well?

Unfortunately no I can't, I don't have Samsung device and 1Password is not open source so I can't see the code to study how it works.

**Comment by nathaneltitane** [comment]
I'm adding my two cents to this bug thread as Ihave made the transition to keepass after a massive breach report - i am very happy with the application and as someone who uses their Note 10+ as their main and only computer (dev, programming and design) I would greatly appreciate if the application would support being launched on Dex, even if it keeps its phone size and format.

Unfortunately, the Dex xlabs 'force resize' has no effect as of this latest Android/Dex version and makes using the wallet impractical for applications that do not have attributes or triggers for the autofill.

[As a reference, and I do not know if this can help, but here is the official reference lin in making applications Dex compatible without too much change in their code](https://developer.samsung.com/sdp/blog/en-us/2017/05/25/samsung-dex-optimization-of-vnc-client-for-samsung-dex)

Thank you

**Comment by alexanderadam** [comment]
I set the whole Android environment up (Studio, SDK, loading a huge load of dependencies, running into various issues).
Now I can create a build that's starting on an Android Desktop environment (like Samsung DeX), by [removing this](https://github.com/Kunzisoft/KeePassDX/blob/454561c2a1b0e0840f314e7a36344b79959763ca/app/src/main/AndroidManifest.xml#L187-L196):

```xml
        <service
            android:name="com.kunzisoft.keepass.magikeyboard.MagikIME"
            android:label="@string/keyboard_label"
            android:permission="android.permission.BIND_INPUT_METHOD" >
            <meta-data android:name="android.view.im"
                android:resource="@xml/keyboard_method"/>
            <intent-filter>
                <action android:name="android.view.InputMethod" />
            </intent-filter>
        </service>
```

But I don't know whether it's possible to build a workaround by that information, since I have no experience with Android development.

**Comment by J-Jamet** [comment]
Thank you @alexanderadam for your detailed comment.
Now that the problem has been highlighted, a way must be found to remedy it, but it's problematic because this permission is necessary for the use of the Mgikeyboard. I will see if it is possible to remove this feature only for Samsungs in DEX mode, but we have to know how to filter them in the manifest, I don't know if it's possible.

**Comment by alexanderadam** [comment]
Now I got [an official answer from Samsung support](https://forum.developer.samsung.com/t/app-is-not-starting-in-dex-with-bind-input-method-permission/8822/2?u=alexanderadam) ([Jakia.Sultana](https://forum.developer.samsung.com/u/Jakia.Sultana)):

> 3rd-party keyboard is not allowed in Samsung DeX, so following permission will block the app in DeX.
>
> `android:permission="android.permission.BIND_INPUT_METHOD"`

**Comment by J-Jamet** [comment]
Since the problem comes from the Magikeyboard permission, I thought I could make a separate bundle as it will become mandatory soon. The idea would be to download only the Magikeyboard if you need it and not to download it if you are on Samsung. But I still have to study the feasibility, maybe the manifest can't be changed anyway.

**Comment by J-Jamet** [comment]
I also read that enabling developer options on Samsung DeX could make it work but I don't know if it's true. If someone can test it would be nice.

**Comment by alexanderadam** [comment]
> Since the problem comes from the Magikeyboard permission, I thought I could make a separate bundle as it will become mandatory soon. The idea would be to download only the Magikeyboard if you need it and not to download it if you are on Samsung.

I have no experience with Android development or Android bundles but Samsung devices can _switch_ between DeX/Desktop mode and 'regular' mode.
So your mobile phone could be in regular mode all the time. Then you are connecting to a monitor via WiFi or USB-C and then you are using DeX mode.
So it's not per device in general but per current state.

In regular mode KeePassDX is working. So it's like switching to another desktop environment on GNU/Linux or *BSD (in case you are aware of this concept).

Is the concept of bundles allowing to switch a bundle per run?

**Comment by alexanderadam** [comment]
Wow, nice! I'm looking forward to test it once it is available in an F-Droid release! :star_struck: 

Thank you so much @chenxiaolong!

**Comment by J-Jamet** [comment]
A user just told me that Samsung DEX was not working with version 3.4.4. I can't test, so can you tell me if this is the case or just a bad configuration?

**Comment by chenxiaolong** [comment]
Sure, I can give it a try today and debug if needed.

**Comment by chenxiaolong** [comment]
I built the 3.4.4 tag from source (with a different package name so I have a fresh configuration) and I'm not encountering any issues in DeX.

The same limitation from before still applies though: KeePassDX must be run once outside of DeX mode before it will work inside DeX. The Android framework will not allow the `DexModeReceiver` broadcast receiver to run unless the app successfully launches once. I think it might be worth having the user try this.

(Would it be worth adding a FAQ entry for this? Running once outside of DeX is required after initial installation, force stop, or clearing data.)
