### ISSUE TITLE
[Request] App entry aside from website entries

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [Kunzisoft/KeePassDX#246]
There are some apps that require password upon opening (wallet apps, 2FA apps, etc), or something like Solid Explorer wherein you set a Master password that will be used when opening your Google Drive, OneDrive, etc. Currently, what the app can record are **only web site entries**. Apps are not yet supported.

App version: 2.5.0.0beta18

**Comment by J-Jamet** [comment]
I do not understand the request, you can enter any type of data in a KeePass file from the application, not just from the websites.

**Comment by eji30** [comment]
I see. Thank you for the clarification. You may close this now.
