### ISSUE TITLE
[Help] Setting to not always enter the password upon opening the app?

### ISSUE THREAD

**Issue by eji30** [Kunzisoft/KeePassDX#247]
[Disclaimer] I'm new to using KeePass as a password manager.

My problem is everytime I open the app, **or** I open it using the autofill from other apps, it **always** asks for the master password of my default database, **even if I just opened** the database (entered its master password).

Is there any setting to disable this behavior? Basically what I want is for the app to not ask me anymore to enter the master password once I've opened the database, until of course I **manually lock it**, or when I exit the app.

What I've tried is using the setting 'App timeout' under 'App settings', but it seems to not work the way I want.

App version: 2.5.0.0beta18

**Comment by J-Jamet** [comment]
The feature is currently in progress.
