### ISSUE TITLE
S10+ fingerprint not working

### ISSUE THREAD

**Issue by dogredwing1** [Kunzisoft/KeePassDX#249]
Fingerprint login not working on s10+

**Comment by dogredwing1** [comment]
[s10fingerprint.txt](https://github.com/Kunzisoft/KeePassDX/files/3072488/s10fingerprint.txt)

**Comment by J-Jamet** [comment]
Thank you for the logs but the file is much too big (28000 lines to read it is not possible), where is your problem in the file?

**Comment by Grossdm** [comment]
I hope this isn't a frivolous suggestion, but has anyone grepped for fingerprint or KeePass?

**Comment by J-Jamet** [comment]
I completely redid the fingerprint system, it should now work with the S10 +, tell me if it's ok with the version 2.5.0.0beta23
