### ISSUE TITLE
Fingerprint not recognized

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#25]
* Bad dialog when enable fingerprint (API 25 < API 25)
* Samsung in Android 6 doesn't work
* Null pointer when delete an undefined fingerprint

**Comment by vArhont** [comment]
zuk z1 device has problem with fingerprint, os android 8.1

**Comment by J-Jamet** [comment]
Can you tell me in what circumstance it happened?

**Comment by guilherme-sr** [comment]
I have a problem at my Moto G5 Plus (Android 7.0)...

I use the function that I don't have the buttons "Return, Home and Running apps", instead I can control this with the fingerprint sensor (swiping left and right). 

Then when using the fingerprint to unlock my database the KeePass DX just don't read my fingerprint, so I need to click at configs or to select a key file and return, then the buttons "Return, Home and Running apps" show up and KeePass DX can read my fingerprint.

**Comment by J-Jamet** [comment]
Fix in 2.5.0.0beta5
