### ISSUE TITLE
[Feature request] Hide password when opening database

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [Kunzisoft/KeePassDX#250]
Please refer to [this image](https://imgur.com/a/WGLPJMZ) for the context of the issue.

When unlocking a database, there's an option to show/hide the password. My issue is when I show the password, and when I tap on open, sometimes it's slow to open the database, leaving my **password shown until** database is successfully opened. Of course, I need to confirm first if I typed the password correctly that's why I always show the password first.

Currently, this behavior is doable in this steps:
1. Show password
2. Type password
3. Perform **another** tap to hide the password again.
4. Tap Open.

If this **security feature** will be implemented, it will be:
1. Show password
2. Type password
3. Go straight and tap Open, and the hiding of password is **automated** to ensure security.

App version: 2.5.0.0beta18

**Comment by J-Jamet** [comment]
Indeed, it is necessary, I will try to add the feature in the next update.

**Comment by J-Jamet** [comment]
There is an Android bug on the icon that hides the password. It stays active when I hide the password. I wonder if it's not easier to delete the entire text between each opening attempt. This will be more restrictive for people who are mistaken for a letter but it will be visually more secure. What do you think?

**Comment by Wilker-a** [comment]
i think this should be an opt-out setting (to enable the setting if you wish to keep the password on), as longer passwords may take more time  to type.  
but maybe even in this case, still hiding the text altogether (of both fields) to show after the attempt should make sense.
