### ISSUE TITLE
Database closes as soon as I try to view entry

### ISSUE THREAD

**Issue by 2011** [Kunzisoft/KeePassDX#255]
Two devices - a tablet and a phone, both running 2.5.0.0beta18 (from F-droid). Tablet works fine. On the phone, I can open the database (copied from a desktop machine via adb) without any problems, but as soon as I touch any entry in the database, it immediately closes the application, and re-opening it returns me to the "open existing database" / "create new database" screen.

**Comment by J-Jamet** [comment]
This problem is related to a problem with the automatic lock of the database. The issue has normally been fixed in development but I must solve other problems before putting the update online. Thanks for your feedback.
