### ISSUE TITLE
Magikeyboard is not reliable

### ISSUE THREAD

**Issue by sivaraam** [Kunzisoft/KeePassDX#258]
The Magikeyboard seems to be very useful helping me to avoid having to copy the passwords to the clipboard. This is great!

Unfortunately, it does have some issues.
1. When I try to choose a login via Magikeyboard, I unlock the database by entering the password (using normal keyboard) and then choose the login and get back to where I left. I then switch to the Magikeyboard to enter the credentials. In some cases the login don't shown up in the keyboard i.e.,  it just asks me to unlock the database again. This happens even though the notification for the corresponding login shows up. This issue is really annoying. This makes me have to unlock the DB twice or thrice (by entering the password) sometimes to successfully get access to the login via Magikeyboard. Fortunately, this doesn't happen all the time. Unfortunately, I'm not sure specifically when this occurs. It would be nice if there was a way to track this issue down and fix it.

2. Usually when I swipe away the notification about login in Magikeyboard, it goes away. Sometimes when I try to do this I get the "Unfortunately KeePassDX has stopped" message. I'm not sure about the specific cases in which this happens either. Just wanted to point it out.

**App version**: 2.5.0.0beta18
**Android version**: 5.1.1

**Comment by J-Jamet** [comment]
Thank you for the feedback, The connection workflow is being redone to not connect every time, but I can not reproduce the crash you mention, can you upload logs when you have the problem? Thank you
