### ISSUE TITLE
Device as external keyboard to fill forms

### ISSUE THREAD

**Issue by justf0rfun** [Kunzisoft/KeePassDX#259]
Imagined feature: 

1. Connecting the mobile device to a target device like a desktop PC via USB or Bluetooth (mabye even other networking connections).
2. Manually open the login form on the target device.
3. Open KeePassDX on the mobile device.
4. Select the respective KeePassDX entry.
5. Call autotype function.
6. KeePassDX will output the credentials over USB, Bluetooth or whatever like the mobile device was an external keyboard.
7. The target device handles the input like it came from an external keyboard.

With this feature it would be possible to use the mobile device as the only device storing the credential data. Of course a backup should be made, but there would be no need for syncing the credential data over multiple devices anymore. Of course it could be done additionally.

Step 2 could also be automated if URLs are stored in KeePassDX.

I know there are hardware keyboards which encrypt input transfered to the host. I myself have a model (Logitech) which can be connected via USB cable, Bluetooth or 2,4GHz USB-Dongle. It does encrypt connections but I don't know which or all of them and how they do it.

Also I don't know how that corresponds to Magikeyboard and Android handling of input devices. Maybe this could be generalized or consolidated. 

The app "Authorizer" on F-Droid does this, but I did not try it, yet. 
https://f-droid.org/en/packages/net.tjado.passwdsafe/

Also I found an extension to another password manager application, but I have to search it again and I did not try it yet, too.

**Comment by J-Jamet** [comment]
Thank you for the feedback, it's a (good) idea that has already been submitted ;), but I already have to handle bugs and more urgent features. Here is the link to the thread https://github.com/Kunzisoft/KeePassDX/issues/80
