### ISSUE TITLE
Content Provider - Upgrade Search

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#26]
- [x] Solve search when no entry available
~- [ ] Add a content provider (Link to https://github.com/bpellin/keepassdroid/pull/38)~
- [x] Suggest values ​​while typing
- [x]  Less restrictive search

**Comment by alexanderadam** [comment]
I'm not quite sure whether this is the right place but I guess it's at least related: the other KeePass clients support a substring search. So if there is an entry called "foo bar baz" and I search for "foo baz" others will find this entry wheras KeePassDX does not.
Should I open a separate issue for this or is it fine here?

**Comment by J-Jamet** [comment]
That's fine here, I'll add a check line. ;) Thanks

**Comment by alexanderadam** [comment]
I just found out that I already created [an issue for the substring search](https://github.com/Kunzisoft/KeePassDX/issues/175) in 2018!

Sorry! :see_no_evil:
