### ISSUE TITLE
Feature Request: Integration of bugmenot.com

### ISSUE THREAD

**Issue by justf0rfun** [Kunzisoft/KeePassDX#260]
[BugMeNot.com](http://bugmenot.com/) is a service were people can share their login credentials for arbitrary services so that individuals can reuse existing registered user account of others instead of registering themselves. This is for example useful for temporary or one time visits / participation at a specific service.

It would be a nice feature if a user of KeePassDX can check BugMeNot for existing accounts from inside the app for reuse, so that the users don't have to register themselves. 

Unfortunately I can't see that BugMeNot.com has an existing interface to query it's database, yet. So cooperation with BugMeNot.com should be considered.

**Comment by J-Jamet** [comment]
Thank you for the feedback, it's a (good) idea that has already been submitted ;), but I already have to handle bugs and more urgent features. Here is the link to the thread https://github.com/Kunzisoft/KeePassDX/issues/80
