### ISSUE TITLE
Fingerprint Overlay on Galaxy S10 reappearing with 

### ISSUE THREAD

**Issue by alexjung** [Kunzisoft/KeePassDX#264]
When unlocking the database with the fingerprint reader the overlay, which indicates the position of the fingerprint reader, sometimes reappears with the message "Fingerprint operation cancelled". The database is still being unlocked on the first fingerprint reading and the message will disappear after a moment. Not sure if this is a Samsung UI problem but it only happened to me in the KeePassDX app so far. Might be that the fingerprint reader is activated again or something like this. 
If needed I can try to provide screenshots (but with the message disappearing really fast that could prove difficult).

**Comment by J-Jamet** [comment]
The problem should be solved with version 2.5.0.0beta23, tell me if it's OK for you?

**Comment by alexjung** [comment]
Perfect! I have not been able to reproduce the bug since the latest update. Thank you!
