### ISSUE TITLE
Could not find file, try opening from your file browser

### ISSUE THREAD

**Issue by kbd99603** [Kunzisoft/KeePassDX#265]
When trying to log in on any app, I clicked on the popup, Sign in Using KeePass DX, but everytime I do so, it is unable to find my main database file. It suggests I open it up using my file browser, which works, but  obviously can be time consuming. I'm guessing this has something to do with the fact that I transferred the file from KeePassX on my linux computer.
![Screenshot_20190612-200212](https://user-images.githubusercontent.com/33134233/59403950-3b673e00-8d51-11e9-8998-125f66d28b11.jpeg)

**Comment by worldpotato** [comment]
I have the same experience. I have my db at a nexcloud instance. I think it is caused by a slow network connection.

**Comment by mrjpaxton** [comment]
Exact same issue here. I double, triple, and quadruple checked my master password and keyfile, and no dice. I guess I need a backup KeePass program installed then....

**Comment by J-Jamet** [comment]
I added a note in the FAQ : 
Keepass DX uses the default file manager of your device. **If this manager is not connected to your cloud, you need to open your cloud app and select your database file.** The linked file provided by the content provider may have a strange name with series of numbers and letters (like eab4678a-33f1-4890-acba-42f1b5cbac13), *an alias feature is in development for better visibility*.

*Caution*: Some file managers provide "content://" link that break after a single use. For the following uses, you may have an error "Could not find file. Try reopening it from your file browser". In this case, we advise you to open your database from your file manager and not from KeePass DX.
We're thinking about creating or modifying an open source file manager app to make it easier to open remote files with this problem.

**Comment by belzebub40k** [comment]
@J-Jamet I have the same problem and my file manager and the Nextcloud App only provide content:// links. Is there a way to force the correct type of link? I also tried other file managers but couldn't find any that shows my Nextcloud files.

**Comment by J-Jamet** [comment]
I improved the broken link recognition system. In the next version, by default, broken file links will be hidden.
@belzebub40k content:// links are ok, it's the good type.
Note after several tests that the links are more likely to be kept if you go through the 'Open existing database' button. (and not directly by clicking on the .kdbx file from your file manager)

**Comment by leoj3n** [comment]
> Note after several tests, the links are more likely to be kept if you go through the 'Open existing database' button.

Interesting, do you know why that is? Just curious why it makes a difference how db is opened.

Also, I wonder if the problem can't be solved within the Nextcloud app? Do all Android file storage apps work the same way and have this same issue? Or is it just NC?

**Comment by J-Jamet** [comment]
In terms of programming, this is not really a bug but rather a security. It's just that the link provided is only valid for a defined session.
Going through the KeePassDX button, there is a request for intent with a flag to maintain the connection ( FLAG_GRANT_PERSISTABLE_URI_PERMISSION).
The compatibility of the file manager depends on its implementation of this flag, so there is an answer for each app. That's why I'm thinking of making a separate file manager but I haven't finished KeePassDX yet. ^^

**Comment by J-Jamet** [comment]
I added code that checks if a link is still valid and hides it if it is broken. It is possible to redisplay broken links by activating the setting.
