### ISSUE TITLE
Database cannot be loaded - precondition START_TAG (position END_TAG </binary>)

### ISSUE THREAD

**Issue by XploD-Ing** [Kunzisoft/KeePassDX#267]
What I did:
1.) I opened a password protected database
2.) I edited the database (added a value)
3.) I safed it
--> Since then, I cannot open it with keepass DX

I can open the same database using windows Keepass and "Keepass2Android"
I edited the database using the windows Keepass, safed and synchronized it to my android device -> Still can't open it

I uninstalled keepass DX completely -> Same error message
I cleared the app settings -> Same error message

I tried the "Database maintainance" options in Windows keepass -> The size shrunk from 67k to 57k, but it still doesn't open.

I change encryption from default AES to Chacha20 -> Same error message

![576-1024](https://user-images.githubusercontent.com/51950894/59670204-d2058600-91bb-11e9-8282-63d7d765f3a4.jpg)

I really like FOSS, and I would be really sad if keepass DX would not work with my database. How can I help to fix that bug?

I am using a Oneplus 3T with Android 9, Not rooted
Best regards, and thanks for the good work
_X_

**Comment by patrickschneider23** [comment]
@XploD-Ing
