### ISSUE TITLE
Implement a really black theme

### ISSUE THREAD

**Issue by KOLANICH** [Kunzisoft/KeePassDX#27]
Please implement a theme with really black elements occupying large area like backgrounds, stripes and buttons. Under ```black``` I mean ```#000000```.

**Comment by J-Jamet** [comment]
It was planned, but it's cosmetic, I'll put in the pro version for those who do not want to compile themselves.
I'll do a dynamic theme change utility but I have to solve all the bugs before.

**Comment by J-Jamet** [comment]
The new classic black theme is available in the beta9 Pro version.
