### ISSUE TITLE
Database cannot be loaded: Wrong entity type

### ISSUE THREAD

**Issue by elroxar** [Kunzisoft/KeePassDX#270]
When trying to open a KeePassXC Database on my Android with KeePass DX I get the following Error:
`Database cannot be loaded. Wrong event type (position:TEXT ocp90jf4oFb/uDaG...@167:59 in java.io.InputStreamReader@xxxxxxx)` where x is an alphanumeric value changing each time I try to open the database.
The database is synced using a self hosted ownCloud server and downloaded via the NextCloud App for Android.

**Comment by J-Jamet** [comment]
Thanks for the feedback, can you tell me if the problem is also present when you download the file and open it locally?
