### ISSUE TITLE
Cannot load database Stream closed: FTP does not work

### ISSUE THREAD

**Issue by xl32** [Kunzisoft/KeePassDX#272]
I am not able to add kdbx file that is located on remote ftp(s) server (I use it for synchronization between devices).
Steps: 

1. Add existing database, path ftp://name:password@example.com/path/to/db.kdbx;
2. Enter password for database: 123;
3. Observe error message "Cannot load database Stream closed".

**Comment by J-Jamet** [comment]
FTP recognition is not supported yet. Synchronization is planned after the bug fixes.

**Comment by J-Jamet** [comment]
The use of a file manager compatible with FTP is necessary. I close this issue because it corresponds to a need that will not be developed. If you are using a specific file manager and have problems, you can reopen a new issue.
