### ISSUE TITLE
Feature Request - Disable History By Default

### ISSUE THREAD

**Issue by trymeouteh** [Kunzisoft/KeePassDX#276]
For security I think this feature should be disabled by default. If your phone gets stolen and the thief opens the KeePassDX app they will see where your KeePass file is stored on your device. This is especially the case if you rename the extension from kdbx to something else to hide it on your phone.

I do not want this remembering history feature gone, just disable out of the box.

**Comment by J-Jamet** [comment]
You can already disable the history in the options. Disabling it by default would be unwise because the feature is important and useful when multiple files are managed on the same device. Security focuses mainly on file encryption and you can disable history in any case.
