### ISSUE TITLE
Auto search Autofill result by ApplicationId

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#279]
Automatically search for entries with their applicationId during an Autofill request

Previous request:
~Keepass2android can save login entries for apps, and save the app package name in the "KP2A_URL" string field so we can autofill the login details in the same app next time. (Alice Request)~

**Comment by lukengda** [comment]
I would have framed it differently but wanted to propose a new feature in the same realm of this issue. So instead i am posting my thoughts here:

Using the Autofill feature should utilize the app id to search in the url field and possibly as here suggested custom fields like `KP2A_URL`. If there is only one search result, the result should be automatically selected and return the focus to the calling app.

This goes hand in hand with the issue #280 where the content of the share target value would get automatically searched for.

The A+ feature would be to use the url for Browser based autofill. I noticed, that firefox is supported for website autofill. I don't know whether the autofill api allows to get the url from the supported browser.

Is there anything more that i can describe to round of the description or if something is unclear?

**Comment by J-Jamet** [comment]
KP2A_URL is a field which is not generic because directly related to KP2A, I will therefore try to find a more generic method for this request.

**Comment by J-Jamet** [comment]
I am updating the autofill code to automatically propose the username and associated password if an applicationId or web domain is present in entries.
For now, it searches in all form fields, so for example:

-  if an app with applicationId "com.sample.app" is requested and present in an entry field (whatever the label)

- or if the form's url is "https://www.sample.form/form.php", "www.sample.form"   is requested in all fields

the popup is displayed by itself with the corresponding entry/entries (max 6)

Are you okay with this or do I need to do filters to target specific fields? (to reduce the number of proposals, but I don't see any error if I leave the search in all fields)

**Comment by Offerel** [comment]
That would be really nice. With this system, we doesn't need to use specific field names and can re-use fields from other apps like kp2a and others.
