### ISSUE TITLE
When a base is created Argon is not used

### ISSUE THREAD

**Issue by KOLANICH** [Kunzisoft/KeePassDX#29]

**Comment by J-Jamet** [comment]
I'll do as in KeePass XC and leave the possibility to change the encryption and the KDF after creation (in the settings).
Would that be okay with you ?

**Comment by KOLANICH** [comment]
>I'll do as in KeePass XC and leave the possibility to change the encryption and the KDF after creation (in the settings).
Would that be okay with you ?

Yes, it will be OK. I cannot strongly insist on using Argon by default because it is a very young KDF not as well-researched as scrypt is, it is uncertain how much it is really secure.

**Comment by J-Jamet** [comment]
Done in the new version 2.5.0.0beta11, tell me if it's ok for you.
