### ISSUE TITLE
Entry information is not correct

### ISSUE THREAD

**Issue by OmarEXE** [Kunzisoft/KeePassDX#291]
Just updated the app and launched it to see what's new and found out most of my passwords, some usernames and other info gone. I can still use them with  _Magikeyboard_, but when i try to edit them all the fields are empty it's like I'm making a new password. So now i regret updating it and wondering what the hell went wrong?

- **Device:** Huawei    

- **Android:** 8.0.0

- **App version:** version 2.5.0.0beta19

**Comment by J-Jamet** [comment]
Thank you for your return, the code of the application has been completely redone for better performance, maintenance and accessibility, but the code reading databases has not been changed. Can you tell me if you are using a V1 or V2 database? With what type of encryption? Do you have a backup of the database to reproduce the problem? I had tested the application to avoid this kind of case so we must identify the problem with precision to correct it.

**Comment by OmarEXE** [comment]
I'm using V2 database with AES encryption 
Key derivation function: AES KDF
Transformation rounds: 6000
And i don't have any backups so I'm not sure how to reproduce this. New entries and new databases work fine without any issues, it's just this older database that i made before the update.

**Comment by J-Jamet** [comment]
I see, in this case I think it might be a database problem with non-closed XML tags once decrypted or something like that. But to be sure, we need to duplicate the problem to debug it, otherwise It's almost impossible to know where the worry comes from. It is possible to improve the data parser but it has not been changed since the previous version of the application. Do you use a cloud for synchronization? it is possible that part of the file has not been synchronized.

**Comment by OmarEXE** [comment]
The database file is on my phone's local storage so no.

**Comment by ttodo-softserve** [comment]
Same here - strange stuff is that recently added entries are not seen.
Instead you can see a long ID smth-smth-smth- where should be the name 
There is a created date, access date BUT missing (blank field) where username and password should be

If I open it with another program I can see the entries right. The issue came with the update.

**Comment by J-Jamet** [comment]
In this case, it is possible that this is a problem of display.  I redid the interface to show elements in the views from the base. Can you take a screenshot to show the problem?

**Comment by ttodo-softserve** [comment]
What permissions / setting I need to do in order to make screenshots when KeePassDX is open?
Now is forbidden

**Comment by ttodo-softserve** [comment]
As I can't make the screenshot will try to help you with explanation.
In the upper green field I see a key, bellow it an ID in HEX

then gray block without data (here in some entries are seen username and passwords)

below is a block grey with Created, Modified, Accessed - all is seen here.

If I press to edit - it creates a new entry, not shown the current one.

Black theme is used. 

Opening the DB with KeepassDroid shows the entries ok, also the old version of KeepassDX

**Comment by J-Jamet** [comment]
I see, I have other feedback with this kind of problems but I do not see where it comes from. It's annoying, I'm going to look at the code in more detail, it's foolish. Sorry about that.

**Comment by J-Jamet** [comment]
I think I may have an answer, the problem must come from the history of the entries and retrieve an obsolete entry from the history.

**Comment by J-Jamet** [comment]
This is a major bug that I had not seen, I will do my best to solve it as quickly as possible and deploy a new version.

**Comment by J-Jamet** [comment]
Can you tell me if this build solve the problem? 
[KeePassDX-2.5.0.0beta20_build201908161846.zip](https://github.com/Kunzisoft/KeePassDX/files/3510451/KeePassDX-2.5.0.0beta20_build201908161846.zip)

**Comment by OmarEXE** [comment]
Yep this version is working great, i can see all my passwords again. Thank you!

**Comment by J-Jamet** [comment]
Super, that's what I wanted to know, I upload a new version! ;)
