### ISSUE TITLE
Allow for setting default password generation options in settings

### ISSUE THREAD

**Issue by anoadragon453** [Kunzisoft/KeePassDX#3]
8 character length passwords are not very secure. Ideally I'd be able to set it to something longer without having to do so manually every time I create a new password.

You should be able to set default password generation length along with other default generation options in settings.

**Comment by J-Jamet** [comment]
OK for that. Will be in the next beta.

**Comment by J-Jamet** [comment]
Done in **2.5.0.0beta3**
