### ISSUE TITLE
Autofill service not working properly

### ISSUE THREAD

**Issue by lkjasdlfwe** [Kunzisoft/KeePassDX#302]
I just downloaded this app and tried to use autofill service in a couple of apps to see how it works and the results were disappointing. For reddit sync, it straight up does not get triggered when I attempt to add an account. Long pressing and selecting autofill also does nothing.

For my banking app the autofill pop up appears but when I click on it and select the relevant entry it doesn't fill in the data. It gives an autofill pop up again which displays the username of the relevant login entry but upon clicking on it it fills both, the username field and the password field, with my password.

Please note these issues do not occur with Keepass2Android on my phone or KeeWeb on my PC.

**Comment by J-Jamet** [comment]
I have not had time to work on the autofill yet, the current version uses a very basic algorithm and needs to be improved.

**Comment by lkjasdlfwe** [comment]
@J-Jamet Ah okay. Thanks for telling. It is a great app BTW. Somehow opens the database much faster than Keepass2Android. Hope it gets much better. Best of luck!

**Comment by alexanderadam** [comment]
Is there a place where people could write about AutoFill issues?
Like a AutoFill summary issue or so?

**Comment by J-Jamet** [comment]
I can create a github template for Autofill issues. You just have to keep in mind that for the moment, the Autofill service is not finished and it is normal that it is not supported by all the other applications.

**Comment by AoiSeaghdha** [comment]
Effective Autofill seems exciting, so I'll be looking forward to this feature being implemented. No need to rush, though, of course. I'd much rather it be implemented securely and effectively than broken. I'm sure everyone else agrees that taking time with this feature is ultimately for the best.

I'm mostly just worried about the risks associated with autofill, e.g. the hazards raised [here](https://www.xda-developers.com/password-manager-autofill-api-data-leak/) / [here](https://github.com/commonsguy/AutofillFollies/blob/master/WHITE_PAPER.md#security-requirements-of-autofill-services).

**Comment by J-Jamet** [comment]
I improved the algorithm for recognizing forms in web pages. It should be much better from version 2.5beta29.
@AoiSeaghdha I did my best to target the items that are only necessary. There is no problem when TAG autofill are present, but there could be bugs for the recognition of Input in WebView because I retrieve only the first elements. Do not hesitate to send me your feedback
