### ISSUE TITLE
Fdroid Update & Can't opn existing database

### ISSUE THREAD

**Issue by HyknuF** [Kunzisoft/KeePassDX#303]
I have the latest Fdroid version installed. When I try to update manually to the newest beta it wont work. I then have two apps installed separately. Moreover I can't open my exisiting database with the new beta version.

Thx!

**Comment by J-Jamet** [comment]
Updates on F-Droid can take time it's normal. The servers must do the automatic compilation.

Can you be more specific about the versions you use, I have fixed some bugs on version 2.5.0.0beta19, 20 and 21. Now corrected in version 2.5.0.0beta22. (It is recommended to install version 22)

Can you tell me what is the error message present that prevents the opening?

**Comment by HyknuF** [comment]
Installed: Latest Fdroid version: 2.5.0.beta18.

I am used to open my database file through my cloudservice client (which is Teamdrive in my case). That works fine with the beta18. When I try the same way with beta22 an error occurs: "File not found".

I tried to open the local stored temp-database file with beta22 which works fine though.

**Comment by J-Jamet** [comment]
Ho I see, I have not yet created synchronization of remote files and not yet tested the cloud, I open an issue with a summary table of cloud tested.

**Comment by HyknuF** [comment]
Ok nice, thanks!

**Comment by J-Jamet** [comment]
I opened the ticket https://github.com/Kunzisoft/KeePassDX/issues/305, I close this one.
