### ISSUE TITLE
Cloud Synchronization 

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#305]
Issue related to connection procedures for cloud synchronization. Once the tools created and procedures tested, they will be added to the Wiki. 
https://github.com/Kunzisoft/KeePassDX/wiki/Cloud-Synchronization

**Comment by HyknuF** [comment]
Are you going to push another beta to bring back the opportunity as mentioned? Would be great :-)

**Comment by J-Jamet** [comment]
It is obvious that I will update the application, but I want to remain in the procedures of realizations and normal tests. I have preferred to create a wiki to better inform on the subject. ;) The purpose would be to create installation procedures for each server.

**Comment by J-Jamet** [comment]
Feature externalized in the File Sync application. https://github.com/Kunzisoft/FileSync
