### ISSUE TITLE
Can't open kbdx from NextCloud

### ISSUE THREAD

**Issue by gloomytrousers** [Kunzisoft/KeePassDX#308]
As I reported in https://github.com/nextcloud/android/issues/4246 for KeePassDroid, which is awaiting merge of https://github.com/bpellin/keepassdroid/pull/352, KeePassDX does not associate itself with the `application/x-kdbx` MIME type. This means I can't open a password file from the Nextcolud app direct in KeePassDX just by tapping the file.

**Comment by J-Jamet** [comment]
No problem, I add it for the next update. But I thought the mime-type was `application/x-keepass`.  I will add both, but you should know which one is official?

**Comment by gloomytrousers** [comment]
I don't know to be honest - I was just going on what was in the PR I referenced.
