### ISSUE TITLE
Link to github on the website

### ISSUE THREAD

**Issue by BrandonOCasey** [Kunzisoft/KeePassDX#31]
Link to this github repository: https://github.com/Kunzisoft/KeePassDX
on the website: http://www.kunzisoft.com/KeepassDX/

Also the website link for the repo leads to a github 404.

**Comment by J-Jamet** [comment]
It's changed.
Note : The website is only a Markdown Readme javascript parser with two additional links and custom css. I do not have time for a complete site, but maybe later!
