### ISSUE TITLE
Will KeePassXC TOTP Be Removed/Corrupted In KeePassDX?

### ISSUE THREAD

**Issue by trymeouteh** [Kunzisoft/KeePassDX#318]
If I created a KeePassXC database on my computer and added TOTP tokens to certain password and opened the database in KeePassDX on my phone, will it delete or corrupt the TOTP?

**Comment by J-Jamet** [comment]
I have not tested, but you can try on your side! ;) I will treat the subject when I will do the TOTP.

Linked https://github.com/Kunzisoft/KeePassDX/issues/70 #185

**Comment by trymeouteh** [comment]
I understand writing apps it is hard to have an ETA but do you have an ETA on when TOTP support will be added?

**Comment by Bjornskjald** [comment]
As the pull request is open, I guess it will be soon
Also, I was surprised when I noticed "2 days ago" 😄

**Comment by Bjornskjald** [comment]
As for the corruption, nothing becomes corrupted and you can access seed/settings but can't generate a TOTP code.

**Comment by thePanz** [comment]
@J-Jamet should we close this issue? I guess the question has been answered :)
