### ISSUE TITLE
Entry does not show up upon creation

### ISSUE THREAD

**Issue by Wilker-a** [Kunzisoft/KeePassDX#319]
in the current version, `2.5.0.0beta22`, creating an entry does not automatically make it appear on the list unless i reopen the database (by redoing the process of inserting keys and etc.)

**Comment by J-Jamet** [comment]
Thank you for the feedback, I will try to see where the problem comes from, it happens to you every time?

**Comment by Wilker-a** [comment]
i just tried again and apparently not... i thought it was just not reloading but now it is showing on the list.

either the cause is something else or it is just a false alarm..? \^\^'

**Comment by J-Jamet** [comment]
I may have an explanation, when you create an entry, you are sorting by title and your new entry is at the top of the list, you have to move the list to see it.
