### ISSUE TITLE
New German strings for beta22

### ISSUE THREAD

**Issue by wistein** [Kunzisoft/KeePassDX#323]
I found 8 new strings missing in German in the beta22-version.
Attaching a file (xml or txt) didn't work.

    <string name="delete_entered_password_title">Passwort löschen</string>
    <string name="delete_entered_password_summary">Löscht das eingegebene Passwort nach einem Verbindungsversuch</string>
    <string name="lock_database_back_root_title">Drücke Zurück auf der Startseite zum Schließen</string>
    <string name="lock_database_back_root_summary">Schließe die Datenbank wenn auf der Startseite der Zurück-Button gedrückt wird</string>
    <string name="clear_clipboard_notification_title">Beim Schließen löschen</string>
    <string name="clear_clipboard_notification_summary">Die Datenbank schließen, wenn die Benachrichtigung geschlossen wird</string>
    <string name="list_groups_show_number_entries_title">Zeige die Anzahl der Einträge</string>
    <string name="list_groups_show_number_entries_summary">Zeige die Anzahl der Einträge in einer Gruppe</string>

Regards,
wistein

**Comment by Wilker-a** [comment]
is it that you intend to translate? if so, this project uses [Weblate](https://hosted.weblate.org/projects/keepass-dx/strings/de/) for that :3

**Comment by wistein** [comment]
Thank you.
Will try next time.

Now just a correction to the initial comment:
    <string name="keyboard_notification_entry_clear_close_title">Benachrichtigung löschen schließt Datenbank</string>

**Comment by wistein** [comment]
Addon
Here with the string name:
<string name="clear_clipboard_notification_title">Benachrichtigung löschen schließt Datenbank</string>
