### ISSUE TITLE
Cloud storage for opening KDBX

### ISSUE THREAD

**Issue by Suncatcher** [Kunzisoft/KeePassDX#325]
Any reasonable roadmap when the cloud storage will be added to the app? And especially WebDAV.

**Comment by J-Jamet** [comment]
No roadmap, I do my best to manage the features by priority. I intend to use a separate file manager to manage external connections but I have to think about it.

**Comment by J-Jamet** [comment]
Linked to #118

**Comment by Suncatcher** [comment]
Okay, I like your efforts but the WebDAV/Cloud is a feature that is very critical and the only thing that prevents me from moving to your app from Keepass2Android. I like your app more, and can donate to help the development.

**Comment by J-Jamet** [comment]
I understand very well the request but I have to do things in order, if I add now the remote access there will be many other bugs to manage in addition to the current ones. You can use other applications for the moment and migrate once the features are created.
