### ISSUE TITLE
Unable to copy password to clipboard on Google Pixel 3a

### ISSUE THREAD

**Issue by coilheadfred** [Kunzisoft/KeePassDX#328]
Every time I try to copy a password it won't do anything. Did not have this issue on a different device.

**Comment by J-Jamet** [comment]
This bug will be very difficult to solve because I do not have a Google Pixel 3, can you tell me if there is a custom clipboard on your device?

**Comment by J-Jamet** [comment]
You are sure not to have unchecked the setting "App Settings -> Clipboard Trust" ?

**Comment by coilheadfred** [comment]
Yes I am sure. It's turned on. I am not sure why it isn't working. My other keepass app works

**Comment by flocke** [comment]
I just tried on my Pixel 3a to see if I can maybe get a logcat or debug further, big it seems to work for me. I copied and pasted a few passwords and it worked without problems for all of them.

**Comment by coilheadfred** [comment]
Maybe I'll uninstall and install again.

**Comment by J-Jamet** [comment]
This bug is very specific and not reproducible, I close the issue.
