### ISSUE TITLE
Allow exposing username all the time for ease of auto fill

### ISSUE THREAD

**Issue by AkazaRenn** [Kunzisoft/KeePassDX#338]
Like iOS's default behavior, exposing the username and only ask for verification when user choose one, that would make the experience more straightforward.

**Comment by J-Jamet** [comment]
There is a big problem with this request. It is not possible to access the username of the entries without opening the database.

**Comment by AkazaDorian** [comment]
@J-Jamet maybe caching the usernames in another database with a KeepassDX-specific password so it can be opened whenever the app wants?

**Comment by J-Jamet** [comment]
Will not be done, it would be the same as the current behavior with an additional procedure in the connection workflow to unlock the database containing the usernames. So no benefit for huge development constraints.
