### ISSUE TITLE
Allow hiding the logo on auto fill context menu or changing it to a customized one

### ISSUE THREAD

**Issue by AkazaRenn** [Kunzisoft/KeePassDX#339]
![](https://i.imgur.com/Fnn7YnU.png)
The green icon does not fit in most cases in both apps and websites, making it maybe a grey lock icon or something would look much better.

**Comment by AkazaDorian** [comment]
I just got reminded that using the favicon of this website would also be fantastic.

**Comment by J-Jamet** [comment]
The Autofill will be upgraded for the next version, the automatic search will offer entries with the associated icons.
The current KeePassDX icon will only be present if no database is open or no entry is found for the Web domain or the ApplicationId.
