### ISSUE TITLE
Request graceful storage permissions denial handling

### ISSUE THREAD

**Issue by avuton** [Kunzisoft/KeePassDX#34]
I use NextCloud to manage the password files, which it then opens directly with KeePassDX (current version: 2.5.0.0beta4-libre). When I went to open KeePassDX directly to derp around in the application settings, I was asked whether I wanted to allow storage permissions, which I then denied (not that I'm not trusting, I just didn't see the necessity). I'm greeted by it popping back up immediately, then I clicked 'Do not show again', to which the app then locked up (and the system_server shot up to 100% CPU usage). Even a finish() here would be more graceful.

Thanks for your work on this app.

**Comment by J-Jamet** [comment]
I agree with you, the permissions are not done correctly, I'm refactoring them! ;)

**Comment by J-Jamet** [comment]
Fix in 2.5.0.0beta5
