### ISSUE TITLE
Fingerprint don't saved for remote database

### ISSUE THREAD

**Issue by TsSaltan** [Kunzisoft/KeePassDX#340]
I used remote database file on OneDrive. I selected file via android's file explorer. Databases filename showed in KeePassDX as "?RefreshOption=Autorefresh...". I inputed password, pressed on fingerprint, but after closing database, KeePassDX writes that password don't saved.

**Comment by TsSaltan** [comment]
KeePass DX version 2.5.0.0beta23
Android 8.0.0

**Comment by mattes009** [comment]
Seems to be same issue as #341, with local database on Android 9 (S10e) for me.

**Comment by J-Jamet** [comment]
@mattes009 I agree. Fingerprint feature is not directly related to remote feature. I close this issue for a better visibility.
