### ISSUE TITLE
Fingerprint not saving on ASUS Zenfone 3

### ISSUE THREAD

**Issue by Soboy** [Kunzisoft/KeePassDX#341]
I have this issue with about 50% of the apps I use fingerprint unlock on, and unfortunately every KeePass app also fails to save my fingerprint login. When I open the biometric dialogue, a successful scan just closes the dialogue without saving my fingerprint credentials or giving me an error and prompts me to open the biometric dialogue again. 

I know it's not a hardware issue because it works in certain banking apps and OneNote, and it seems like this specific Android version ASUS uses gives developers issues. Any help would be appreciated, it would be so nice to finally have working haha

**Comment by J-Jamet** [comment]
What version of KeePass are you using? What is the error displayed? I redid all the fingerprint workflow in version 2.5.0.0beta23, I can not do better code without being able to test if I do not have the device with the problem concerned.

**Comment by Soboy** [comment]
That's the version I have, I just installed it today from the play store. There's no error, it simply closes the "Save biometric recognition" popup and the banner still says "Open biometric prompt to store credentials." If I get a failed print read, in the popup it says "Not recognized" and under the previous banner it says in italics "Cancel." If I continue to login, close the app and reopen it, it still says that it doesn't have stored credentials yet. I'm happy to provide any more information or testing that I can.

**Comment by J-Jamet** [comment]
OK, The first problem is that there is no error at all. 
It may be impossible to store the hash in the keystore of the device, but in this case, there should be an error displayed. 
Or maybe the keystore is not accessible at all. In this case, the feature will never work.
Do you have any updates available for your phone?

**Comment by Soboy** [comment]
I don't have any updates available, and I'm on android 8.0.0

**Comment by mattes009** [comment]
I'm having the same problem on galaxy s10e. Have to retype password every time as fingerprint does not get saved

**Comment by loukash** [comment]
I'm having this issue on xiaimi redmi 3s.

**Comment by J-Jamet** [comment]
There is a new flow in version 2.5.0.0beta25, tell me if it works for you.

**Comment by mattes009** [comment]
Test with 2.5.0 beta 25 successful! Fingerprint working on Galaxy S10e running  Android 10. Many thanks!

**Comment by fangqifan** [comment]
I'm having this issue on oneplus 7 pro,android 10
