### ISSUE TITLE
The problem with opening the local database

### ISSUE THREAD

**Issue by porsevdv** [Kunzisoft/KeePassDX#344]
Hi bug in version 2.5.0.0beta22, when the database is opened, it writes insufficient memory, but this is not so, there is 1.5 GB of RAM
The base lies on a flash card freely more than 50%

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/256
Try to upgrade to version 2.5.0.0beta23

**Comment by porsevdv** [comment]
And where to download the latest version 2.5.0.0beta22 in the F-Droid

**Comment by porsevdv** [comment]
[https://pasteboard.co/Iz8UPy2.png](url)

**Comment by J-Jamet** [comment]
In this case it is a problem in F-Droid, maybe open a ticket on the corresponding project https://gitlab.com/fdroid/fdroiddata and check why the update does not take place on their servers.

**Comment by porsevdv** [comment]
Thank you very much for your efforts and you can’t just drop the apk files, I even tried under no new version = (

**Comment by J-Jamet** [comment]
I can not create the libre version manually because I do not have the F-Droid certificate, but you can download the free version in the release. https://github.com/Kunzisoft/KeePassDX/releases

**Comment by porsevdv** [comment]
Thank you so much for your work, sorry to spend your time ;-)

**Comment by J-Jamet** [comment]
No problem, tell me if it's ok. ;)

**Comment by porsevdv** [comment]
Updated when connecting to the database gives that the file is damaged, but it is a working pity ....

**Comment by porsevdv** [comment]
https://imgur.com/a/sw0YKi3

**Comment by J-Jamet** [comment]
Thank you for the image. I saw that there were bugs with link checking, I will try to fix that for the next update. But I'm not sure it fits your problem. Do you use a cloud to access your file? Can it be opened with another KeePass application?

**Comment by porsevdv** [comment]
Yes, I can open the base in Kepas2Android, the file is located locally without synchronization across the cloud.
We are waiting for the update ;-)

**Comment by J-Jamet** [comment]
Update is available (linked to https://github.com/Kunzisoft/KeePassDX/issues/347) I close this ticket, please open a new one if there is still a problem.
