### ISSUE TITLE
Cannot remove entry

### ISSUE THREAD

**Issue by ndtoan96** [Kunzisoft/KeePassDX#346]
OS: Android 7.0
Behavior:
When I delete entry, it temporarily disappear but then I save and go back it just returns.

**Comment by J-Jamet** [comment]
Thank you for your feedback, there is a bug with deletion id. I will have to find out why the bug is present, because it is not reproducible every time. Linked to #345

**Comment by J-Jamet** [comment]
I put the bug on hold because I think the problem is related to databases that have multiple identical UUIDs. (https://github.com/Kunzisoft/KeePassDX/issues/297) I improved the recognition and repair of this type of bases. You will tell me if the problem is still present with version 2.5.0.0beta24

**Comment by J-Jamet** [comment]
I solved the problem with the multi selection feature.
