### ISSUE TITLE
Unable to launch main activity from MagiKeyboard

### ISSUE THREAD

**Issue by Dees7** [Kunzisoft/KeePassDX#348]
Can't  open keyboard on MIUI

KeePassDX 2.5.0.0beta23

10-01 15:02:33.935   833   833 I Timeline: Timeline: Activity_launch_request time:325517159
10-01 15:02:33.936  1622 14814 I ActivityManager: START u0 {flg=0x10008000 cmp=com.kunzisoft.keepass.free/com.kunzisoft.keepass.magikeyboard.KeyboardLauncherActivity} from uid 10201
10-01 15:02:33.936  1622 14814 D com.android.server.am.ExtraActivityManagerService: MIUILOG- Permission Denied Activity : Intent { flg=0x10008000 cmp=com.kunzisoft.keepass.free/com.kunzisoft.keepass.magikeyboard.KeyboardLauncherActivity } pkg : com.kunzisoft.keepass.free uid : 10201 tuid : 10028 

![image](https://user-images.githubusercontent.com/14229113/65957976-b02cc800-e467-11e9-8731-5afc2c25dbfc.png)

**Comment by J-Jamet** [comment]
OK, I can not reproduce the problem on my devices, but I added the setting `android:exported="true"`  that should solve the problem.
https://developer.android.com/guide/topics/manifest/activity-element#exported

**Comment by Dees7** [comment]
It works! thank you )
Now i'm on own build app. Will wait update in PlayMarket.

**Comment by Dees7** [comment]
Hello. 
Bug again here

    01-24 12:59:46.513  1608  2720 I ActivityManager: START u0 {flg=0x10008000 cmp=com.kunzisoft.keepass.free/com.kunzisoft.keepass.magikeyboard.KeyboardLauncherActivity} from uid 10280
    01-24 12:59:46.513  1608  2720 D com.android.server.am.ExtraActivityManagerService: MIUILOG- Permission Denied Activity : Intent { flg=0x10008000 cmp=com.kunzisoft.keepass.free/com.kunzisoft.keepass.magikeyboard.KeyboardLauncherActivity } pkg : com.kunzisoft.keepass.free uid : 10280 tuid : 10168
    01-24 12:59:46.875  1608  2720 D ConnectivityService: Returning BLOCKED NetworkInfo to uid=10088
