### ISSUE TITLE
Google Drive size inconsistency

### ISSUE THREAD

**Issue by Suncatcher** [Kunzisoft/KeePassDX#349]
There is a difference of sizes when loading GDrive files from KeePassDX and from GDrive app.
Here is what is showed from your app (522Kb)

![photo_2019-10-01_15-48-47](https://user-images.githubusercontent.com/6388034/65995385-6e9a1e00-e463-11e9-9180-d91cec11e807.jpg)

And here is how it looked from official app (509.7Kb)

![photo_2019-10-01_15-48-45](https://user-images.githubusercontent.com/6388034/65995447-8a052900-e463-11e9-850e-a4ed1eb4b3df.jpg)

I suppose your app loads old (cached?) version of file and because of this throws errors. Whenever I try to load file from recents it doesn't load and require that I reload from browser (how?)

**Comment by J-Jamet** [comment]
The screenshots that you put do not correspond to KeePass DX, but to the file manager of your phone. KeePass DX only uses the content provider of the default file manager or used when opening from the file.
The indicated size is therefore the size indicated by the manager of your phone. For me the file was simply not copied entirely. I keep in ram only the information of an opened database, as soon as it is closed, all the data are removed from the ram. There is no cache strictly speaking.

**Comment by Suncatcher** [comment]
Sorry, I use another app now. Maybe somebody else will be able to confirm the issue.

**Comment by J-Jamet** [comment]
In this case I close the issue, another will be opened when needed.
