### ISSUE TITLE
No memory to load your entire database for GDrive

### ISSUE THREAD

**Issue by Suncatcher** [Kunzisoft/KeePassDX#350]
This is what I get when I try to load Google Drive file

![photo_2019-10-01_15-48-42](https://user-images.githubusercontent.com/6388034/65995643-eff1b080-e463-11e9-91f8-d588633f15b1.jpg)

I don't know whether it is connected to [this issue](https://github.com/Kunzisoft/KeePassDX/issues/349) but I suppose it is.

P.S. I have brand-new device (Xioami Redmi 7) with plenty of memory (64Gb+3Gb RAM) so it is definitely not a memory issue.

**Comment by J-Jamet** [comment]
I think it comes from the formatting of links retrieved by the content manager. (Must be verified) I will try to improve the system when I will do the tests for the clouds.

**Comment by Suncatcher** [comment]
The same bug is observed while loading from local storage. Quitting your app, too many errors. Impossible to work

**Comment by xenithorb** [comment]
Also seeing this with one of my main dbs that is approximately 2mb in size (icons and small attachments mostly). K2A handles it ok.

**Comment by TheLonelyGhost** [comment]
I also observed this on my Essential PH-1 both trying to load from Dropbox and when trying to load from the filesystem. I wonder if it's dependent on some of the content on the KeePass database?

![Screenshot_20191026-222042](https://user-images.githubusercontent.com/1276113/67635005-81ecad80-f898-11e9-9d8d-b257d64a68be.png)
![Screenshot_20191026-222019](https://user-images.githubusercontent.com/1276113/67635009-8913bb80-f898-11e9-9d9c-122d3e30e90a.png)
![Screenshot_20191026-222118](https://user-images.githubusercontent.com/1276113/67635002-77caaf00-f898-11e9-8a2b-b07e6f21026e.png)

**Comment by Suncatcher** [comment]
> that is approximately 2mb in size

my db-file is 500Kb and the same thing. It's size-irrelevant bug.

**Comment by PeteS4** [comment]
I have this problem on and off with a small 70kB database. As a workaround, when I edit the file with another Keepass client (XC mainly) most of the time DX can open it again. I usually just add/remove an empty entry to/from the recycling bin folder.

**Comment by xenithorb** [comment]
I can confirm that after editing the DB with k2a or keepassxc it opens without issue

**Comment by lgrahl** [comment]
This is probably the same issue as #256

**Comment by TheLonelyGhost** [comment]
Can confirm #256 completely coincides with my use case. It also seems to have some better definition of the issue and more leg-work on resolving it.

**Comment by J-Jamet** [comment]
I close this issue and leave #256 open for better visibility.
