### ISSUE TITLE
Biometric Prompt Unavailable

### ISSUE THREAD

**Issue by m1st0** [Kunzisoft/KeePassDX#363]
The biometric prompt even after entering a password doesn't show on my phone, nothing occurs when I click the button.

**Comment by m1st0** [comment]
The biometric prompt even after entering a password doesn't show on my phone, nothing occurs when I click the button.

**Comment by J-Jamet** [comment]
No biometric prompt at all it's very weird. What is the error message displayed when you press the biometric orange button once the password is entered?

**Comment by m1st0** [comment]
No error message was shown. I can record the screen but there is nothing but a highlighting button.

**Comment by J-Jamet** [comment]
It may be from the androidX biometric library used in alpha, I increased version RC01, I hope that it will solve the problem.
https://github.com/Kieun/android-biometricprompt/issues/4

**Comment by m1st0** [comment]
To test, are there builds or build the commit myself?

**Comment by J-Jamet** [comment]
You can build the develop branch if you want. I discovered that on some of my devices the problem comes from the reset of the API, so works the first time but not when we redo a request. I have not solved the problem yet.

**Comment by iheb111** [comment]
same prblm here, fix it soon plz,
my mobile is Samsung Galaxy A50, the sensor is under the screen , idk if this make
thx for this great app

btw can u plz add a testing version in the releases
