### ISSUE TITLE
Magikeyboard: enter tab key after username

### ISSUE THREAD

**Issue by z3ntu** [Kunzisoft/KeePassDX#369]
In Keepass2Android pressing the username button on their keyboard also enters the tab key which makes the focus jump to the next (password) field automatically and you just have to tap the password icon on the keyboard to fill in the password instead of having to manually click the password field.

It would be great if that feature (at least as an option in the settings) would exist in KeePassDX!

**Comment by Wilker-a** [comment]
an option to disable (opt-out) would be best.

the small details are really useful \^u\^

**Comment by J-Jamet** [comment]
I think we have to change 2 things:
 - Change the "validate" button to the "tab" button when there are next fields in the form (like the default keyboard).
 - Automatically activate this button after clicking on a "field" button (if it is activated in the options).

But I don't know how the AOSP keyboard detects to display a "KeyEvent.KEYCODE_TAB" or "KeyEvent.KEYCODE_ENTER" button depending on the cursor.
