### ISSUE TITLE
[Feature Request] Pixel Face Unlock Support

### ISSUE THREAD

**Issue by TheSpad** [Kunzisoft/KeePassDX#375]
As the Pixel 4 doesn't have a fingerprint reader the only biometric option for credential storage is the face unlock. I would find this very useful as my master password is (intentionally) a huge pain to type.

**Comment by J-Jamet** [comment]
Biometric recognition uses the new google API that should recognize the biometric unlock of the device, whatever the type. Not having a pixel 4 I can not test.

**Comment by TheSpad** [comment]
Looks like I was getting a bit ahead of myself based on what I'd read - my Pixel 4 arrived this afternoon and it does indeed work correctly with the Face Unlock :). Cheers.
