### ISSUE TITLE
TOTP Secrets are not validated

### ISSUE THREAD

**Issue by grimpy** [Kunzisoft/KeePassDX#381]
**Describe the bug**
When scanning the tokens given by github/google they are not in base32 format so they are rejected by keepassdx.

When attempting to open an entry with an existing token keepassdx shows `Invalid OTP secret`

**KeePass DX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta24]
 - Build: from github
 - Language: English

I have no idea however in which format they are currently stored in, I see all lowercase latters and some numbers. The github one is 16characters long and the one of google is 32characters long.

FYI: The way they are currently stored work fine for both keepass2android and keepassxc

Any help would be appreciated

**Comment by J-Jamet** [comment]
The keys in base 32 must contain only capital letters from A to Z and numbers from 2 to 7.
https://tools.ietf.org/html/rfc4648
I'm going to watch how github generates his keys.

**Comment by grimpy** [comment]
Thx for the quick reply, yes this indeed fixed it for both github and google

**Comment by Komic** [comment]
It would seem KPDX also chokes on Amazon's 52 characters long secrets, running the 2.5.0.0beta24 build from this repo.

**Comment by J-Jamet** [comment]
Thank you for you feedback @Komic.
For HumbleBundle, It does not provide a key in Base32. For which is valid, it is necessary to add 6 'A' -> AAAAAA at the end of the key. I do not know why they do that,I will change the code to be more lax but it is not very serious from these companies. ^^

**Comment by grimpy** [comment]
@J-Jamet while you are changing the code, google also in certain cases (when requesting to copy the key manually) adds spaces inside the keys, maybe you want to handle this aswell?

**Comment by J-Jamet** [comment]
@grimpy Yes of course, I'm adding that for the copy.

**Comment by Komic** [comment]
> (6 for humble bundle-> AAAAAA, 4 -> AAAA for Amazon).
> I will change the code to be more lax.

sounds great, thanks!

**Comment by J-Jamet** [comment]
6/8 digits works. The update is available.

**Comment by moya2162** [comment]
> Thank you for your feedback @komic. This keys are not in Base32 format. To be valid, it is necessary to add 'A' ( 6 for humble bundle-> AAAAAA, 4 -> AAAA for Amazon) at the end of the key. I will change the code to be more lax.

FYI running 4.0.5 and I had to add AAAA to end of Amazon secret for TOTP to work properly in app.
