### ISSUE TITLE
fingerprinting doesn't work on Samsung Galaxy A50

### ISSUE THREAD

**Issue by MoussaAdam** [Kunzisoft/KeePassDX#382]
**Describe the bug**
clicking the "fingerprint icon" button do nothing
**To Reproduce**
1. Go to Keepass
2. Click on the desired Database
3. Type the password on the text field
4. click the biometric icon on the top righ 
5. nothing happens (except the ripple animation on the button), no dialog appears at all, just nothing happens

**Expected behavior**
a dialog is expected to appear after clicking the biometric icon(just after typing the password) to prove that me is really me, using any biometric unlocking methods like fingerprinting, face unlocking, whatever...

**Screenshots**
what about a video? can i?

**Keepass Database**
 - Created with: [latest KeePass for Android 2.5.0.0beta24]
 - Version: [2.5.0.0beta24]
 - Location: [local]
 - Size: [doesn't matter, I tried a lot of times, with different Databases]
 - Contains attachment: [I will edit the post later and maybe add don't attachment]

**KeePass DX (please complete the following information):**
 - Version: [2.5.0.0beta23]
 - Build: [Free]
 - Language: [English]

**Android (please complete the following information):**
 - Device: [Samsung Galaxy A50]
 - Version: [9 (Android P) ]
 - Browser: [why??]

**Additional context**
is there anyway to debug that on my mobile, I can help with that, or maybe any logs or anything I can send to help fixing that, I will happily help in anyway

**Comment by J-Jamet** [comment]
Thank you for the feedback.
Several people have described this problem. But in all honesty, I do not see where the issue comes from.
Maybe :
 * the Phone KeyStore is not accessible and the key can not be retrieved or created.
 * a biometric element in API is not initialized.
If there is no error message that appears next to the button it is even more problematic. It means that we have to debug it step by step to find out what's wrong. 
I have to reproduce the problem but I do not know how.

**Comment by MoussaAdam** [comment]
i am really willing to help, if u tell me, i will debug it on my mobile, if this is possible, idk mybe samsung have their own proprietary API

**Comment by djohannes** [comment]
On some Samsung devices you have to set the default unlock method to fingerprint, instead of face Unlock as face Unlock isn't safe enough for the KeyStore. I sadly have no Samsung to be able to tell you exactly where you can find this setting.

**Comment by J-Jamet** [comment]
I made better state handling for biometric recognition, and now there is an error display if the keystore can not be initialized properly. I'll have to write a wiki page that explains the error.

**Comment by MoussaAdam** [comment]
@djohannes it's on  
  
Biometrics And Security > Biometrics Preferences > Preferred Biometric

**Comment by J-Jamet** [comment]
I coded a new flow and write better error messages. @MoussaAdam Tell me what the application 2.5.0.0beta25 tell you.

**Comment by MoussaAdam** [comment]
@J-Jamet
sorry for the very late response, everything works alright, thanks to all of u, also its really appreciated that the project is open source

**Comment by J-Jamet** [comment]
Perfect! :)
