### ISSUE TITLE
The revision number is missing

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#384]
The revision number under "about" area is missing.

My device OnePlus 7 (Android 10) and KeePass DX 2.5.0.0beta24

**Comment by J-Jamet** [comment]
Can you upload a screenshot, it may be a problem in a translation file.
You should see "2.5.0.0beta24"

**Comment by filemanagerryess** [comment]
> Can you upload a screenshot, it may be a problem in a translation file.
> You should see "Version 2.5.0.0beta24"

i think the creator was looking for something like this. similar to VLC player for Android
![20191113_203121](https://user-images.githubusercontent.com/57727817/68797472-f5dad400-0654-11ea-81e9-42f3ad3d7230.jpg)

**Comment by J-Jamet** [comment]
There is no need to keepass DX, the version of the Android application follows the code version name.
For the moment the number of the beta increases, and when it will be in production, it will be the version number.
