### ISSUE TITLE
The max history items doesn't work

### ISSUE THREAD

**Issue by ghost** [Kunzisoft/KeePassDX#385]
in the current KeePass DX 2.5.0.0beta24 there is support for history.

But I don't need it and want to disable it. If I want to use it, I should also have an option to save only 1 history after editing. An option should be added how many the number for history should be.

**Comment by J-Jamet** [comment]
The option is available but does not work properly. I will see to correct the problem in the next version.

**Comment by J-Jamet** [comment]
I just solved the problem in the develop branch. Just set the ""Max. history items" to 0.
