### ISSUE TITLE
Magikeyboard: Protonmail web site use case suggestions

### ISSUE THREAD

**Issue by afpp-l** [Kunzisoft/KeePassDX#389]
**Is your feature request related to a problem? Please describe.**
I came across two inconveniences with the Menu that contains TOTP and all additional string fields for the entry:
1. While logging in to Protonmail I need a TOTP token to fill in. When I open this menu on Magikeyboard, I see my string fields first, starting from the last one, and I have quite a few of them. Their titles are of decent length too. TOTP stands first in line but is shown last, as it happens. So scrolling left through all fields is inevitable, but unnecessary.
2. Protonmail allows you to set up an additional "mailbox password". They ask for it after initial login, password and TOTP token. This Magikeyboard Menu ceases to function properly after TOTP. It just becomes empty.

**Describe the solution you'd like**
1.  It is highly likely that usually TOTP is needed quite more often than other fields, so it should be shown first.
2.  Is this a bug? I am not sure. Suggestion is to make it work all the time.

**Comment by J-Jamet** [comment]
Issue already fixed
