### ISSUE TITLE
Implicit Confirmation For Biometrics API / BiometricPrompt

### ISSUE THREAD

**Issue by djohannes** [Kunzisoft/KeePassDX#390]
My feature request is pretty simple: Please enable or give me the option to enable implicit confirmation for biometric unlock.
Here it's perfectly explained:
https://developer.android.com/training/sign-in/biometric-auth#no-explicit-user-action

.. basically all the other password managers I tried do this, and it can get really annoying over time if you always have to hit "Confirm".

If some people don't want this and rather want to keep the confirm button, there is a system wide option to enable it for all apps in the settings.

**Comment by J-Jamet** [comment]
I did not think this confirmation was present because I do not see it on emulator, I will try to set up this feature for the next update.

**Comment by djohannes** [comment]
This confirm button only appears with more passive unlock methods like Face Unlock or Iris Unlock. That's probably why you couldn't see it in the emulator :)

**Comment by J-Jamet** [comment]
Yes that's right, so I put setConfirmationRequired(false) to open a database, but I leave setConfirmationRequired(true) to store a credential. Or do you think it's not necessary for both cases?

**Comment by djohannes** [comment]
I think this would be perfect! :)

**Comment by J-Jamet** [comment]
The update is uploaded, it should work.

**Comment by djohannes** [comment]
@J-Jamet Yes and it works, thank you so much!
