### ISSUE TITLE
Exit a KeePass Database once entered

### ISSUE THREAD

**Issue by SChetwynd** [Kunzisoft/KeePassDX#393]
After unlocking a Keepass database pressing the back button minimizes the app when entering the app again it goes straight to the unlocked database.

As a user I sometimes unlock one database, realize its the wrong one and need to exit it and unlock a different one.

I'm using KeepassDX version 2.5.0beta23 libre build.

**Comment by J-Jamet** [comment]
I just tested the feature by activating the setting "Press 'Back' to lock" and it works well for me.
