### ISSUE TITLE
10% file size reduction after save

### ISSUE THREAD

**Issue by mappu** [Kunzisoft/KeePassDX#396]
**Describe the bug**
Hi - i have a kdbx mostly used with KeePass 2 that is 698 KB.

Today i added a new password using KeePass DX 2.5.0.0B23 (fdroid).

The file size shrunk to 623KB.

It's not clear to me why it shrunk, so i'm worried it might have involved data loss. (I do still have copies of the unmodified file.)

**To Reproduce**
I don't have an isolated reproducer. But it might be possible to reproduce by creating a database in KeePass 2, adding content  then adding more content in KeePass DX

**Expected behavior**
Filesize same or slightly larger

** Keepass Database **
 - Created with: KeePass 2
 - Version: 2
 - Location: Local (syncthing)
 - Size: as above
 - Contains attachment: Probably

**KeePass DX (please complete the following information):**
 - Version: 2.5.0.0beta23
 - Build: Fdroid
 - Language: English

**Android (please complete the following information):**
 - Device: Beryllium
 - Version: 9

**Comment by J-Jamet** [comment]
The downsizing is not necessarily a bug, I constantly optimize the code for the database (by ordering the nodes, managing the compression, and using the adapted version of the base)
Please indicate which data is corrupted by comparing your backup and the new database.

**Comment by TuxoYKT** [comment]
Recently I added a password to my database through KeePass DX. Later when I tried to unlock my database(KP2) this error popped out
[Screenshot_20191128-194334_KeePass_DX](https://user-images.githubusercontent.com/6498761/69800117-80324480-11cc-11ea-8de6-469c406fbb12.png)
> No memory to load your entire database.

and I wasn't able to access it.

Good thing that I had a backup just in case if something goes wrong.  I was able to compare the files. The corrupted file also shrunk in size. From 56,0 KB to 48,0 KB.

Currently I set KeePass DX into read-only mode just to be safe.

**Comment by J-Jamet** [comment]
This problem does not mean that the database is corrupt. Only the parser does not have enough memory to decode it. https://github.com/Kunzisoft/KeePassDX/issues/256
Have you tried to open the database with another program after this message?
I am trying to solve this memory problem which is not easy to solve.

**Comment by TuxoYKT** [comment]
> Have you tried to open the database with another program after this message?

I tried to open my database in both KeePass2 2.43 and KeePassXC 2.5.1 after that.
They both refused to open it.
[KeePass_UL17IBfgOc](https://user-images.githubusercontent.com/6498761/69804001-7f51e080-11d5-11ea-9cc2-90e13ebba1a6.png)
[KeePassXC_HxkOq7Ip51](https://user-images.githubusercontent.com/6498761/69803937-5e898b00-11d5-11ea-8e8e-0e9e08a4633c.png)

**Comment by J-Jamet** [comment]
Okay, thanks for this important information. Do you have files attached to the database?

**Comment by TuxoYKT** [comment]
> Do you have files attached to the database?
Yes, I have some files attached to the database. I may put them somewhere else if the attachments cause the problem.

**Comment by J-Jamet** [comment]
The problem with binaries is that the parser built into Android may not recover them properly. As it is serialized in XML, there may be a memory problem during decryption. I am modifying this part in the code but I recommend not to add big binary files (1Mo +) in a database.
This is only for storing PGP key files or lightweight files. Otherwise, it is better to make a virtual disk with Veracrypt.

**Comment by mappu** [comment]
> The downsizing is not necessarily a bug, I constantly optimize the code for the database (by ordering the nodes, managing the compression, and using the adapted version of the base)
> Please indicate which data is corrupted by comparing your backup and the new database.

Today i loaded both small version and original larger version into KeePass 2 for XML export, diffed the XML, and found no notable changes (many `ExpiryTime` values changed to 2999?). Also all my attachments were correctly preserved.

So I think you are correct, the smaller filesize is probably only caused by the different compression approach.

Sorry for worrying you! For my part this ticket can be closed,

**Comment by J-Jamet** [comment]
The expiration date is not yet managed in the app, so it is set to 2999 to maintain compatibility with the different versions of the database.
I will close this ticket once a note added in the FAQ.
Refer to OOM issue for other issues.
