### ISSUE TITLE
Autofill For Older Android Releases or Devices

### ISSUE THREAD

**Issue by DanTheTechMan** [Kunzisoft/KeePassDX#397]
I have an older phone running Android 7.0, and, for the most part, the app works fine, however, when I try to enable the Autofill feature, I am presented with the following error: 

![KeePassDX_AutoFill_Error_Unsupported Android Version_20191125-1627](https://user-images.githubusercontent.com/12401470/69580014-a7f19480-0fa1-11ea-804c-e2490a4c8514.jpg)

Would it be possible, in the future, to support the Autofill feature on older android devices/releases?

**Comment by J-Jamet** [comment]
No, it is not possible because the service is part of the Android operating system. You have two options: 
- update Android
- use the Magikeyboard that was created expressly for older devices.

**Comment by J-Jamet** [comment]
Note has been added to the wiki. https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill
