### ISSUE TITLE
Application Settings: Password Size should update dynamically

### ISSUE THREAD

**Issue by anoadragon453** [Kunzisoft/KeePassDX#40]
Small nitpick: The white label for the size of your default password in Application Settings doesn't update real-time as you move the slider. It would be much easier to chose a desired option if it updated as the slider was moved.

Thanks!

**Comment by J-Jamet** [comment]
https://developer.android.com/reference/android/support/v7/preference/SeekBarPreference may fix this little issue, I'm waiting for the final version of version 28.
