### ISSUE TITLE
Search does not search sub-folders

### ISSUE THREAD

**Issue by goodevilgenius** [Kunzisoft/KeePassDX#403]
**Describe the bug**

When searching, only entries within a top level folder are found. No entries in sub-folders are listed.

**To Reproduce**
1. Have a top level folder, e.g. "Communication"
2. Have a folder within it, e.g. "Email"
3. Have an entry in the sub-folder
4. Use the search to search for that entry
5. See that it is not listed

**Expected behavior**
All entries should be searched.

** Keepass Database **
 - Created with: KeePassX
 - Version: ?
 - Location: Nextcloud
 - Size: 235K
 - Contains attachment: No

**KeePass DX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: F-Droid
 - Language: English

**Android (please complete the following information):**
 - Device: GalaxyS8
 - Version: 9

**Comment by J-Jamet** [comment]
I have just tested the functionality with several databases and I cannot reproduce the problem. Can you send me a specially created database that contains the issue you are describing?

**Comment by goodevilgenius** [comment]
I'm trying to recreate it with a new file. So far, I'm not able to. I'm only able to see it on my own password file.

But, TBH, I don't even remember what program I originally used to create this file, and I've used it in a dozen different Keepass-compatible programs over the years, and any of them could have modified it in some weird way.

I'll try a few more things.

**Comment by goodevilgenius** [comment]
I've since reorganized my own file, and modified a few settings, in KeePass on my computer, and now when opening in KeePassDX, searching works fine.

So, I guess I'll close this. It was some weird edge case that I can't reproduce and is no longer affecting me.
