### ISSUE TITLE
Incorrect header check

### ISSUE THREAD

**Issue by newhinton** [Kunzisoft/KeePassDX#406]
**Describe the bug**
A database saved by this app produces a file that cannot be opened by other keepass compatible programs (tested keepass2(linux) and keeweb (linux, as well as the nextcloud-keeweb-app))

KeeWeb errors out with 'incorrect header check'

KeePass DX can still open the file properly, other applications not.

**To Reproduce**
1. [PC] Create a database file with keeweb
2. [PC] Sync to nextcloud
3. [App] Setup nextcloud-app and connect to nextcloud
3. [App] Open existing database
3. [App] Select nextcloud as storage, and then find and open the database
3. [App] Save the database
3. [PC] (Wait for sync to finish) Try to open the database

**Expected behavior**
The passwordfile should open and display the passwords

**Keepass Database**
 - Created with:Keeweb 1.12.3
 - Version: 2
 - Location: Remote file retrieved over Nextcloud-App (Not synced, but Nextcloud offers a Filesystem which can be accessed on demand]
 - Size: 100kb
 - Contains attachment: Yes

**KeePass DX:**
 - Version: 2.5.0.0beta25
 - Build: libre

**Android:**
 - Version: 8.1

**Comment by J-Jamet** [comment]
Thanks for the feedback, I need to identify if the problem comes from the attached files (I'm working on it right now) or from any other problem related to synchronization. I'm going to investigate.

**Comment by J-Jamet** [comment]
Is normally the same issue as #412, is resolved in the branch _feature/Stream_Binaries_.
