### ISSUE TITLE
KeyPassDX shows up in Google translate

### ISSUE THREAD

**Issue by DrDustwolf** [Kunzisoft/KeePassDX#407]
**Describe the bug**
It shows up in Google translate for Android

**To Reproduce**
This anything into Google translate

**Expected behavior**
It should just show up when needed

**Screenshots**
![Screenshot_20191213-011503_�bersetzer](https://user-images.githubusercontent.com/14179460/70759842-fc3d9800-1d47-11ea-9343-e12e6cb04501.png)

** Keepass Database **
 - Created with: [Android KeePass]
 - Version: [2.5.0.0beta25]
 - Location: [internal storage]
 - Size: [1,15kb]
 - Contains attachment: [Yes]

**KeePass DX (please complete the following information):**
 - Version: [2.5.0.0beta25]
 - Build: [f-droid Free]
 - Language: [German]

**Android (please complete the following information):**
 - Device: [Lenovo Yoga Tab 3 Plus LTE YT-X703L]
 - Version: [LineageOS 9]

**Additional context**
 - Browser for Autofill: [KeyPassDX App]

**Comment by lukengda** [comment]
I noticed the same behavior for OxygenOS on Android 10!

**Comment by comradekingu** [comment]
@DrDustwolf Does that also happen when logged in with a Google account?
Google Translate does save lookup history now, so maybe this isn't a bug.
Does it paste the password in the field, or does it log in?

**Comment by J-Jamet** [comment]
Normally, version 2.5beta29 should resolve the problem but I cannot guarantee it because I could not reproduce the problem. Can you confirm that the problem is corrected? Thank you
@comradekingu Detection should only be done for the username and password fields of a form. ;)
