### ISSUE TITLE
AutoFill does not work in Hermit Browser

### ISSUE THREAD

**Issue by telepath** [Kunzisoft/KeePassDX#409]
**Describe the bug**
In lite apps created with Hermit, the KeePass DX auto fill button does not appear during login. 
Sometimes the button appears at the very bottom of the screen after switching the devices orientation. 

**To Reproduce**
1. Activate KeePass DX as auto fill service
2. Get Hermit Lite Apps Browser from Play Store https://play.google.com/store/apps/details?id=com.chimbori.hermitcrab
3. Launch Hermit and add a new lite app that requires login, e.g. facebook
4. Tap on the login field
5. The keepass dx button does not appear
6. Hold the login field and select " auto fill" from the menu
7. Button still does not appear
8. Switch orientation of the device
9. SOMETIMES the button appears at the bottom of the screen.

**Expected behavior**
When opening a lite app in Hermit and trying to log in, I expect the auto fill button to appear below the login field. 

**Screenshots**

**KeePass DX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: free
 - Language: English

**Android (please complete the following information):**
 - Device: Galaxy Tab S6
 - Version: 9

**Additional context**
 - Browser for Autofill: Hermit

**Comment by alexanderadam** [comment]
Is this related to #302?

**Comment by J-Jamet** [comment]
Yes, all Autofill bugs are linked, the functionality is not finished.

**Comment by J-Jamet** [comment]
I improved the algorithm for recognizing forms in web pages. It should be much better from version 2.5beta29.

**Comment by KATalyzt75** [comment]
I have the same problem with Facebook Lite.
But the autocomplete option does appear, I click/tap it and it does nothing. I have the application open in the background and the database open and it doesn't allow me :(
