### ISSUE TITLE
HTTPS on your website

### ISSUE THREAD

**Issue by rugk** [Kunzisoft/KeePassDX#41]
http://www.kunzisoft.com/KeepassDX/ should use HTTPS.

➡️ https://doesmysiteneedhttps.com/

And BTW you do not want people to intercept your site and redirect the donation links e.g. to their ones. 😉

**Comment by J-Jamet** [comment]
Yes I completely agree. I'll try to do it quickly.

**Comment by rugk** [comment]
> I'll try to do it quickly.

Okay. Should be [possible with Let's Encrypt](https://www.youtube.com/watch?v=k0g21V4MPns). 😉

**Comment by J-Jamet** [comment]
Done. The links must be updated but HTTPS is functional.

**Comment by rugk** [comment]
Wow, that was indeed fast. 😄
