### ISSUE TITLE
'Android Keepass DX" does not conform to official KeePass non-abuse port naming practice

### ISSUE THREAD

**Issue by ingochris** [Kunzisoft/KeePassDX#411]
```

"KeePass" is the password manager developed by Dominik Reichl. Any software by other developers that is using the name "KeePass" in the software's name without any direct non-numeric prefix/suffix is abusing the name "KeePass" and we do not recommend such software. For example, "KeePassDroid" is ok, but "KeePass Droid" is not.
--
```

As stated here: https://keepass.info/download.html

**Comment by J-Jamet** [comment]
Thank you for this return, I simply had not seen this information. I'm going to contact Dominik for a discussion.

**Comment by J-Jamet** [comment]
I had a discussion with him a few weeks ago, I will replace "KeePass DX" by "KeePassDX" and take the opportunity to make a donation to Dominik for his work. ;)

**Comment by J-Jamet** [comment]
Rename "KeePass DX" to "KeePassDX": 
 - [x] App itself
 - [ ] Play Store
 - [ ] F-Droid
 - [x] https://www.keepassdx.com 
 - [x] Framalibre
