### ISSUE TITLE
Aliased text in entry list

### ISSUE THREAD

**Issue by dantmnf** [Kunzisoft/KeePassDX#414]
**Describe the bug**
Text in entry list are aliased (with sharp edges)

**To Reproduce**
1. Open a non-empty database

**Expected behavior**
Text in entry list should have smooth edges like text in other parts of the app.

**Screenshots**
![Screenshot_20191223-101304](https://user-images.githubusercontent.com/2252500/71331834-c336cc00-256e-11ea-82e9-5b38a94d8bdc.jpg)

** Keepass Database **
 N/A

**KeePass DX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: free
 - Language: Simplified Chinese

**Android (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Version: 10

**Comment by J-Jamet** [comment]
I changed the methods to resize the text. If the problem is still present with you it comes from the font. Can you tell me if there is an evolution with the 2.5beta27 version on your device?

**Comment by dantmnf** [comment]
It looks good on my device now.
