### ISSUE TITLE
Dates are not preserved

### ISSUE THREAD

**Issue by MatMaul** [Kunzisoft/KeePassDX#415]
**Describe the bug**
Looks like the dates are stored in a wrong format, at least for v4 kdbx files.
KeePassXC overrides them with current time when opening a kdbx file modified by KeePassDX.

**To Reproduce**
1. Add an entry to the vault with KeePassDX
2. Open kdbx file with KeePassXC

**Expected behavior**
Dates should be preserved but are overridden by current time, probably because it has been stored in the wrong format.

**KeePass DX**
 - Version: 2.5.0.0beta25
 - Build: Free
 - Language: French

**Android**
 - Device: Pixel 3
 - Version: 10

**Comment by MatMaul** [comment]
Here is the Python code to correctly decode dates in v3/4 kdbx files:
```
import base64
from datetime import timedelta
from datetime import datetime

str_val = "ojWV1Q4AAAA="

bin_val = base64.b64decode(str_val)

int_val = int.from_bytes(bin_val, "little")

refdate = datetime(1, 1, 1, 0, 0, 0)

print(refdate + timedelta(seconds=int_val))
```

**Comment by MatMaul** [comment]
I can probably write a patch if you point me to the code handling serialization/deserialization of those date. I can see DateInstant.getDateTimeString but I am not sure it is the good serialization method, and I can't find the related parsing code.

**Comment by MatMaul** [comment]
I found it there:
https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/database/file/output/DatabaseOutputKDBX.kt#L387

This looks good however at first glance. Hum.

**Comment by MatMaul** [comment]
I am closing for now, it looks like it is actually a bug in KeePassXC or something I don't understand, KeePass doesn't have this problem with the same file.

**Comment by MatMaul** [comment]
Ok so I found the problem and it is KeePassDX :)
There is a CRLF added at the end of the base64-encoded string.
Untested but it seems like changing base64 encoder option to `NO_WRAP` here should fix the problem:
https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/database/element/database/DatabaseKDBX.kt#L565

**Comment by J-Jamet** [comment]
Okay, thanks for the analysis. The `NO_WRAP` parameter was added for other CRLF concerns in the feature/Stream_Binaries.  So the problem will be resolved in the next update.

**Comment by MatMaul** [comment]
Great ! I tested it and I can confirmed it's fixed, thanks.
