### ISSUE TITLE
Crash on entry edit

### ISSUE THREAD

**Issue by shawn1thompson** [Kunzisoft/KeePassDX#418]
**Describe the bug**
When I try to edit an entry, the app crashes.

**To Reproduce**
1. Open an entry (I've tried a few)
2. Click on three dots and edit
3. See error

**Expected behavior**
Be able to edit an entry

**Screenshots**
![Screenshot_20191226-171048](https://user-images.githubusercontent.com/32218754/71493441-4e7cbf80-2804-11ea-9180-c9ac34c225d3.png)

** Keepass Database **
 - Created with: I"m not sure. I've had it for several years.
 - Version: 2
 - Location: Synced with my laptop via Syncthing
 - Size: ~35 kB
 - Contains attachment: no

**KeePass DX (please complete the following information):**
 - Version: 2.5.0
 - Build: Libre
 - Language: English

**Android (please complete the following information):**
 - Device: moto G6
 - Version: 9

**Comment by leogbar** [comment]
Same problem

**Comment by J-Jamet** [comment]
I think it's a read-only problem. Is it possible to modify the kdbx file (copy)? The first step is to reproduce the issue,  get the log and secondly fix the problem.

**Comment by shawn1thompson** [comment]
> I think it's a read-only problem. Is it possible to modify the kdbx file (copy)? The first step is to reproduce the issue, get the log and secondly fix the problem.

KeePassDX has Storage permissions

**Comment by J-Jamet** [comment]
Storage permissions are not involved and are not used (only for compatibility <Android 4), This is not the problem.
I think the problem comes from the content provider of Syncthing, which may be providing a read-only link (to be verified).

**Comment by shawn1thompson** [comment]
In Syncthing, I have the folder my database is in, set to Send & Receive which is described as follows:
>sendreceive
The folder is in default mode. Sending local and accepting remote changes. Note that this type was previously called “readwrite” which is deprecated but still accepted in incoming configs.

**Comment by J-Jamet** [comment]
Linked to #431

**Comment by J-Jamet** [comment]
It seems that some file managers do not take into account the write access request in the intent and the only way is to request write access to KeePassDX (to inherits the rights). So I changed the code to request permissions. (The problem comes, however, from poorly designed separate file managers)

**Comment by J-Jamet** [comment]
Tell me if the problem is solved for you with the new version 2.5.0.0beta26?
