### ISSUE TITLE
Add work profile to access shared files

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#422]
https://developer.android.com/work/managed-profiles

**Comment by ivysrono** [comment]
is there any progress？

**Comment by J-Jamet** [comment]
Not really. What is your need for this feature?

**Comment by ivysrono** [comment]
May help #526

**Comment by J-Jamet** [comment]
I don't see how this helps because it's another feature.
If you want I can do an in-depth study if you have needs for company, I can give you my rates.

**Comment by ivysrono** [comment]
Chinese users use work profile not for the company, but for privacy.

**Comment by J-Jamet** [comment]
The work profile is linked to an entity which applies specific parameters to a profile. I can't know what the restrictions are on your work profile if I don't have any information and if I don't know what you want to do exactly.

**Comment by J-Jamet** [comment]
I just tested [oasisfeng/island](https://github.com/oasisfeng/island) on my phone and see no problem. I am able to open a cloned file manager app with a cloned KeePassDX, creating a file is OK and opening a file is OK.
File sharing is a file manager feature in any case, so nothing to do with KeePassDX. I therefore advise you to see with island if it is possible to share files.
