### ISSUE TITLE
Magikeyboard not working with MIUI

### ISSUE THREAD

**Issue by heta1121** [Kunzisoft/KeePassDX#428]
Magikeyboard won't open the keepass app when I click the key-button. The other buttons work as expected. If I open an entry in the app beforehand the keyboard gives me the option to fill in the username and password as usual, it's just when I try to open the database from the keyboard it is not working.

It has worked before with the same device and database. It might be the miui 11 that broke it.

The form-filling has the same problem but I don't use it.

** Keepass Database **
 - Created with: Windows KeePass
 - Location: stored locally, synced with syncthing

 - Version: 2.5.0.0beta25
 - Build: libre
 - Language: English 

 - Device: xiaomi mi 9t
 - Version: miui global 11.0.3
 - Android 9

![Screenshot_2020-01-10-11-52-55-358_com kunzisoft keepass libre](https://user-images.githubusercontent.com/59729973/72147873-cd92fb80-339f-11ea-93b0-b51911ff84b7.jpg)

![Screenshot_2020-01-10-11-52-51-819_com kunzisoft keepass libre](https://user-images.githubusercontent.com/59729973/72147907-e0a5cb80-339f-11ea-9b99-1c003185e8e9.jpg)

**Comment by 4aHxKzD** [comment]
I have the same problem, also MIUI.

**Comment by Jashooa** [comment]
Same problem here, won't open from magikeyboard or autofill. Using MIUI 11 too.

**Comment by J-Jamet** [comment]
The problem only appears to occur on the MIUI system. But I don't have a Xiaomi device, do you know if it is possible to launch a simulator with this OS?

**Comment by J-Jamet** [comment]
I just saw this post -> https://stackoverflow.com/questions/56295901/miui-permission-denied-activity-keyguardlocked, it seems that a manipulation is necessary on MIUI OS to activate the feature.

**Comment by heta1121** [comment]
That worked! Thanks!

**Comment by J-Jamet** [comment]
Addition of point 2 in the "Activation" section of the Wiki. https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

**Comment by Dees7** [comment]
It doesn't help me. I have 2 devices with Android7.1 with MIUI 9.6 and Android 9 with MIUI10.3.
I tried Disable MIUI optimizations.

**Comment by J-Jamet** [comment]
I don't have a MIUI. But it should work according to user feedback. Have you tried the procedure for Autofill? 
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#set-up

**Comment by heta1121** [comment]
@Dees7 try enabling "display pop-up windows while running in the background" in
manage apps >keepass >other permissions

**Comment by J-Jamet** [comment]
I just improved the wiki.

**Comment by Dees7** [comment]
"Display pop-up windows" helps with Android7.1 with MIUI 9.6. Thanks.
But Android 9 with MIUI10.3 still doesn't
