### ISSUE TITLE
Option to lock database after <minutes> of inactivity

### ISSUE THREAD

**Issue by rugk** [Kunzisoft/KeePassDX#43]
IMHO you should add an option to lock the database after some minutes of inactivity, i.e. 5, 10 or 30 minutes after screen is shut off.

Currently you can only enable to immediately lock the database when the screen is off. IMHO this is not really usable on mobile devices, as the screen is locked very often there. So a timeout to protect the database when your device is stolen/unused for some time, but on the other hand offers a convenient way to use the app, without having to re-enter your (potentially) long password.

**Comment by J-Jamet** [comment]
This is the purpose of the "Application timeout" setting, and it is independent of the screen lock. (So simply  disable the "screen lock" setting). Unfortunately, it didn't work for some cases, so I refactored the code to make it fully usable. I'll add 30 minutes if you want. ;)

**Comment by rugk** [comment]
Ah, okay, maybe 30min would be good, yeah. :smile:

**Comment by J-Jamet** [comment]
Much better implementation of this feature in the new version 2.5.0.0beta7. I open a new issue to add the feature "Wait a few seconds before the lock after the screen turns off." (When manually copying a wifi password for example)
