### ISSUE TITLE
Write failures not properly shown when saving an entry

### ISSUE THREAD

**Issue by Wilker-a** [Kunzisoft/KeePassDX#431]
Version 2.5.0beta25 from F-Droid via Android 5.1.1

**To Reproduce**
use KpDX to open a read-only file using a third party file explorer, and create an entry.

###### * maybe from Android itself might work. i used [Material Files](https://f-droid.org/app/me.zhanghai.android.files) from f-droid.

saving an entry should save and let you know about the progress of it. if any errors occurs, the usual red bad should appear at the bottom like the other errors in the app.

what actually happens is that the progress bar flashes and nothing else happens, and the file is not edited, nor an error about the read-only state (or "failed to read") is shown.

**Comment by J-Jamet** [comment]
Tell me if the problem is solved for you with the new version 2.5.0.0beta26?

**Comment by Wilker-a** [comment]
the update hasn't shown up in F-Droid yet. `unstable updates` is enabled.

**Comment by Wilker-a** [comment]
for saving new entries, edit current ones, creating groups, and save the database via the entry list, it is solved, although only the save database option has the "could not save database" text (others still have the java.io exception text)

the issue persists when editing database settings, such as passwords, compression, names and titles. (my fault, i didn't think of this when first writing this issue).

it likely needs a text for moving entries, too ("you can not move here" can be misleading in this case)

**Comment by J-Jamet** [comment]
Indeed, I tried to resolve the bug quickly but there is more work than I thought. I will try to do a better management of the exceptions raised by the save service.

**Comment by J-Jamet** [comment]
OK, it's solved!
Which text would you like for the error of moving entries?

**Comment by Wilker-a** [comment]
the write failure message should be enough. case-specific errors like moving maybe should be of a lesser priority (as in which text should appear when two conflicts happens at once).

errors from moving would probably need some additional help texts or rephrased strings, too, but that would be something for another issue.
