### ISSUE TITLE
Create new entry with Autofill service

### ISSUE THREAD

**Issue by Vintic** [Kunzisoft/KeePassDX#435]
**Is your feature request related to a problem? Please describe.**
Can't find how to create new entry key when I try to login anywhere. KeyPass is opened in Selection mode.

**Describe the solution you'd like**
Add option: create new key entry in Selection mode. That will auto-fill URL field. And next time login will display automatically this key in autofill option.

**Describe alternatives you've considered**
Previously I used Bitwarden. For the site/app are only displayed keys used previously with it, searching will display all keys.

**Comment by J-Jamet** [comment]
2/ is normally fixed. For 1/ I will try to make it for the next version.

**Comment by J-Jamet** [comment]
I will study this feature.
It would also be good to add the applicationId and web domain fields in existing entries. But we have to check that it does not overwrite data already present.

**Comment by J-Jamet** [comment]
The workflow is still to be studied because it is necessary to filter the elements to be recorded and must not conflict with read-only.

**Comment by J-Jamet** [comment]
OK, this feature is basically the same as #524. To be clearer, I close this discussion, it is possible to deal with the same topic on the other thread.
