### ISSUE TITLE
The service is constantly running (need to close after work)

### ISSUE THREAD

**Issue by OmlineEditor** [Kunzisoft/KeePassDX#438]
**Describe the bug**
if I close the container and then close the program, then one service continues to work and does not close

**To Reproduce**
- I set the settings to not use notification services and turn off all possible third party notifications
- I'm closing the container.
- closing the program
- I look in the program MyAndroidTools which services work?
- I see that the **DatabaseTaskNotificationService** service is working

**Expected behavior**
all services are turned off after work

**KeePass DX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: Free
 - Language: Russian

**Android (please complete the following information):**
 - Device: Lenovo Tab 3
 - Version: Android 6.0

**Screenshots**

![bug](https://user-images.githubusercontent.com/13348933/72985845-f1baf780-3df7-11ea-9a0e-4486f4b9ddc9.png)

**Comment by J-Jamet** [comment]
I just checked and the DatabaseTaskNotificationService service stops alone when it has finished doing the current action. You can see it on line 155. https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/notifications/DatabaseTaskNotificationService.kt
I cannot reproduce your problem. Can you tell me after which action the service remains active in your case? You can check with dev tools build in your phone. https://stackoverflow.com/questions/5523718/how-to-check-all-the-running-services-in-android
(I don't know the MyAndroidTools app, but it seems to display all of the services, not just the ones running.)

**Comment by OmlineEditor** [comment]
I don't see anything in running services that is related to the program even when the program is running and the container is open.
maybe this is just my problem. further study is needed. how else can I check?

**Comment by OmlineEditor** [comment]
I checked by other means the problem is false. please close the ticket.
