### ISSUE TITLE
"App Timeout" not respecting Setting

### ISSUE THREAD

**Issue by TheRoarkster** [Kunzisoft/KeePassDX#444]
**Describe the bug**
In `Settings>App settings>Lock>App timeout`, selecting any time period does not change the settings. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'App settings'
3. Scroll down to 'Lock'
4. Select 'App timeout'
5. Select '5 minutes'
6. Open a database and switch apps, then switch back after less than 5 minutes:  the database will be locked.  

**Expected behavior**
App does not lock for 5 minutes

** Keepass Database **
 - Created with: Linux KeePassXC 2.52
 - Location: Local
 - Size: 1MB

**KeePass DX (please complete the following information):**
 - Version:  3.6.0.0beta25
 - Build: Free
 - Language: English

**Android (please complete the following information):**
 - Device: LGV40
 - Version: 9

**Comment by J-Jamet** [comment]
Just tested and works fine for me, I can't reproduce the problem.
Can you confirm that this is not another setting that prematurely closes the database? :
 * Shutdown screen
 * Closing main notification
 * Closing Keyboard notification
 * Keyboard timeout
 * Closing Clipboard notification
 * Clipboard timeout

**Comment by TheRoarkster** [comment]
Weird.  I can't get it not to timeout -- it is about 1-2 mins, but feels like less.  Essentially, I am using KeePassDX to copy a password into another app.  If I linger on that other app too long, it times out and locks.  

I have "App Timeout" set to 30 minutes.
I have "Screen lock" set to off.
I have "Press 'Back' to Lock" set to off.

I just noticed the "Clear at Closing" setting was set to on.  Will test if that was the problem.  I think it may be.

**Comment by TheRoarkster** [comment]
Yep.  It was the "**Clear at Closing**" setting.
