### ISSUE TITLE
Question: Current best practice - Magikeyboard or Android Autofill service?

### ISSUE THREAD

**Issue by Grossdm** [Kunzisoft/KeePassDX#447]
Please advise what we should use.  I understand that the Autofill service is known not to be at a "release" stage of development, and I am not pestering about this.

My OnePlus 6T is running Android 10 (OxygenOS 10.3.0).
(It updated before I knew of the quirks and restrictions Google added. 😢)

TIA, and thanks for KeePassDX

**Comment by J-Jamet** [comment]
For the moment, I recommend using the Magikeyboard, it is also compatible with old devices. The autofill is under development and uses the system's screen recognition service, it needs to be improved but can be used if it works for your forms. Its improvement depends on the form recognition algorithm and unfortunately, it is not easy to make a generic one.

**Comment by J-Jamet** [comment]
The Autofill algorithm has been updated in the latest versions. I also update the wiki, so I close this issue, you will find all the requested information there.
