### ISSUE TITLE
Custom Special Character Set in Password Generator

### ISSUE THREAD

**Issue by cherryband** [Kunzisoft/KeePassDX#448]
**Is your feature request related to a problem? Please describe.**
Some sites frustrate me with their own special character limitations. While the special character selection in KeePass DX is already quite detailed, sometimes sites don't always follow the same character set.

**Describe the solution you'd like**
If we can add in a 'custom' section in the password generator and let user fill in, user is able to paste in what the website exactly allows.

**Describe alternatives you've considered**
The custom section can work both as a whitelist or blacklist. Another thing to consider is let the user edit 'Special' character set, from the generator itself or through settings.

**Additional context**

**Comment by Ilithy** [comment]
Hi
Excuse me, I would like to know, are you thinking of a section where the user would choose to write the characters he wants to use, automatically excluding all others?

This is an addition to consider indeed, it would allow users to be more flexible on the creation of passwords and avoid the hassle for some sites very limiting in the famous extended characters (I think for example the e-commerce site Rakuten, very annoying on the authorized characters, but there are many others).
