### ISSUE TITLE
Failed to post notification on channel null

### ISSUE THREAD

**Issue by ByteHamster** [Kunzisoft/KeePassDX#45]
I am running version 2.5.0-beta6-Libre on Android 8.1.

When entering the details view of an entry, the app usually shows username and password as notification. It currently just displays a toast message with the text:

> Failed to post notification on channel null

Looks like you have bumped the target sdk version without adding notification channels.

**Comment by J-Jamet** [comment]
You're right, it's due to the new build version of android that no longer accepts notifications from the old version without a channel. I'm recreating the notifications with the new conventions but not yet finished. Sorry about that.
(Link to #https://github.com/Kunzisoft/KeePassDX/issues/21)

**Comment by J-Jamet** [comment]
The bug is now fixed with the new notification in 2.5.0.0beta7 version.
