### ISSUE TITLE
Add color to num chars in password

### ISSUE THREAD

**Issue by lessload** [Kunzisoft/KeePassDX#454]
I found some password manager have this feature that make password easy to read. see in picture
![Capture](https://user-images.githubusercontent.com/60436902/73511508-bd3dd180-43dd-11ea-8c57-e16c6b5b4900.JPG)
   It would be great to have it.
~2. When i press 3dot on top of bar some wrong press to lock buttom. in my opinion it too easy to wrong press but no idea to fix it.~ -> #455

**Comment by ElTopo** [comment]
I also propose that use different color code for special chars (i.e., non 0-9a-zA-Z chars). Here's a screen shot of bitwarden web:
![Screenshot - 2_8_2020 , 1_02_12 PM](https://user-images.githubusercontent.com/217195/74092429-7fdde180-4a78-11ea-8790-6ec37d79778e.png)

**Comment by FlrQue** [comment]
Colorcoding in LastPass:
![obraz](https://user-images.githubusercontent.com/23085743/146367945-d224290b-7220-43f7-80e1-7ed129f3855c.png)
