### ISSUE TITLE
 Rework design to prevent app lock

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#455]
When press 3dot on top of bar some wrong press to lock buttom. (From #454)

**Comment by Ilithy** [comment]
Good morning, sir;
To avoid accidental pressing of the database lock button, one possible way is to move the action of this button to the left icon (non clickable icon) representing an open padlock:

![Screenshot_20200131-140442](https://user-images.githubusercontent.com/36798218/73541923-e1c49880-4433-11ea-9e70-03bce7bac270.jpg)

**Comment by J-Jamet** [comment]
The open padlock for you represents the icon of the group currently open, so it should not be removed. I have to find a trick to make it visible all the time without hindering the pressing of the other buttons.

**Comment by J-Jamet** [comment]
My idea is to put the lock button in the lower left corner, we couldn't not accidentally press it. 
And add a setting if we want to completely remove it from the UI (as there is a mandatory notification with an integrated lock button, the ui button can be optional) What do you think?

**Comment by Ilithy** [comment]
Personally, I think your idea is the right one, placing the button at the bottom is an excellent alternative and makes it easy to access when using the phone with one hand.

Could you create an option in the settings to move this button to the left or right? (For left-handed users, the placement of the button on the left probably makes it less accessible).

**Comment by J-Jamet** [comment]
It is possible to put the button on the right but it requires a lot more work. Indeed, it is necessary to redo the symmetrical views for the add and validate buttons. I open a new issue for symmetry.

**Comment by Ilithy** [comment]
Hello ; Sorry to post this message in this thread, but it's related to the lock button; its presence when editing new entries is problematic (for me); I regularly unintentionally lock my database while I'm in the middle of creating an entry, with all the disruptions it causes; Will it be possible to add an option to hide the database lock button when creating an entry? Thank you.
