### ISSUE TITLE
Hide details/unselect entry when device is locked (with "password" and Magikeyboard is selected)

### ISSUE THREAD

**Issue by mmm4m5m** [Kunzisoft/KeePassDX#457]
**Is your feature request related to a problem? Please describe.**
When device lock is "password" then Magikeyboard could be selected from the lock screen. 
If database autolock is disabled - lock after timeout, lock when screen go off - then stranger could see the last selected entry (and eventually some details).

**Describe the solution you'd like**
If Magikeyboard recognize that device is locked, then it could hide all the information like there is no selected entry.

**Describe alternatives you've considered**
I could not find Magikeyboard setting - "Auto-unselect the (selected) entry after use" - clear the selected entry after it was used. Such setting could be useful in other cases too.

Now I am using "pin" lock because it is using embedded numeric keyboard - there is no option to change input method to Magikeyboard.

Thanks!

**Comment by J-Jamet** [comment]
Hello, I did not quite understand what you mean. But I believe you are talking about a bug that I fixed in version 2.5beta30.

Before the magikeyboard did not recover all the lock events. 
Now the entry is deleted from the keyboard in all lock cases. Can you confirm it?

**Comment by mmm4m5m** [comment]
@J-Jamet 
Hi. Sorry for the delay.

When I set password lock, then I need keyboard to unlock the phone.

When phone is locked, before unlock, I can see the locked screen and the keyboard.
If I select magikeyboard, then the title of last selected (last used) entry is visible.

Checked with Android 9, KeePass version 2.5 added to F-Droid at 2020-05-13.

**Comment by J-Jamet** [comment]
I just tested and I don't have the problem.
Note that it takes at least 6 seconds of device inactivity for the lock request to be received.
This is for ease of manual copying of passwords with a screen that goes out all the time.
Can you retest?

**Comment by mmm4m5m** [comment]
@J-Jamet Sorry. My settings are - never lock the database.
In that case only and if keypass/magikeyboard "KNOWS" that phone is locked.
