### ISSUE TITLE
Choose database screen suboptimal in landscape

### ISSUE THREAD

**Issue by JohnVeness** [Kunzisoft/KeePassDX#458]
The initial screen where you can open a recent database is not great when used in landscape, always requiring scrolling up. Compare what I see in landscape:

![](https://i.imgur.com/l0LpYzO.png)

to portrait:

![](https://i.imgur.com/SirNMI4.png)

**Comment by J-Jamet** [comment]
I updated the layout for better list management, it will be much better in the next version.
