### ISSUE TITLE
Password not deleted from starting Intent

### ISSUE THREAD

**Issue by Kumpewo** [Kunzisoft/KeePassDX#461]
When KeePassDX is started directly via startActivity(intent), the provided password is not removed from this intent. Therefore the database will be unlocked whenever this Activity has to be rebuilt (It's done by using the same intent over and over again.)
Solution: in PasswordActivity.kt (about line 368) add:
        // If Activity is launch with a password and want to open directly
        val intent = intent
        val password = intent.getStringExtra(KEY_PASSWORD)
->    intent.removeExtra(KEY_PASSWORD)

**Comment by J-Jamet** [comment]
I agree, I will modify that.
