### ISSUE TITLE
[Feature request] Search should not search in username

### ISSUE THREAD

**Issue by Salamandar** [Kunzisoft/KeePassDX#462]
If I search "salamandar" on my database I see all the websites with this as a username. Not the login with "salamandar.fr" as URL.

That would be great to select the search field we want.

**Comment by hokonch** [comment]
If using `example@example.com` as username on a lot of website, autofill on `https://example.com/login/` will suggest a lot of candidates.

**Comment by auanasgheps** [comment]
I endorse this request. Would make search much better.

**Comment by J-Jamet** [comment]
Now possible to activate dynamic filters since version 3.3.0

**Comment by Salamandar** [comment]
Thanks !
