### ISSUE TITLE
keepassdx crashing when trying to edit entry

### ISSUE THREAD

**Issue by klic** [Kunzisoft/KeePassDX#465]
**Describe the bug**
Keepassdx crashes when I hit edit to edit a displayed entry

**To Reproduce**

1. Go to some entry
2. Click on three dots
3. select edit (I think it's edit, in German it's bearbeiten)

**Expected behavior**
should allow me to edit the entry

**Screenshots**

** Keepass Database **
 - Created with: DB Version Keepass 2 - KDBX3.1
 - Location: synchronized via nextcloud app
 - Size: 104KB
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta26
 - Build: Free
 - Language: German

**Android (please complete the following information):**
 - Device: FAirphone FP3
 - Version: 9

**Additional context**
Logcat:
02-04 19:53:43.859 12125 13603 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.ClipDescription android.content.ClipData.mClipDescription' on a null object reference
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1956)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at android.content.IClipboard$Stub$Proxy.clearPrimaryClip(IClipboard.java:199)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at android.content.ClipboardManager.clearPrimaryClip(ClipboardManager.java:117)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.kunzisoft.keepass.timeout.ClipboardHelper.cleanClipboard(ClipboardHelper.kt:98)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.kunzisoft.keepass.timeout.ClipboardHelper.cleanClipboard$default(ClipboardHelper.kt:96)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.kunzisoft.keepass.notifications.ClipboardEntryNotificationService.cleanClipboard(ClipboardEntryNotificationService.kt:210)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.kunzisoft.keepass.notifications.ClipboardEntryNotificationService.access$cleanClipboard(ClipboardEntryNotificationService.kt:37)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.kunzisoft.keepass.notifications.ClipboardEntryNotificationService$copyField$1.run(ClipboardEntryNotificationService.kt:194)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at android.content.ClipData.<init>(ClipData.java:749)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.android.server.clipboard.ClipboardService.setPrimaryClipInternal(ClipboardService.java:419)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.android.server.clipboard.ClipboardService$ClipboardImpl.clearPrimaryClip(ClipboardService.java:271)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at android.content.IClipboard$Stub.onTransact(IClipboard.java:72)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 	at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:237)
02-04 19:53:43.859 12125 13603 E AndroidRuntime: 
02-04 19:53:43.859 12125 12125 E AndroidRuntime: FATAL EXCEPTION: main
02-04 19:53:43.859 12125 12125 E AndroidRuntime: Process: com.kunzisoft.keepass.libre, PID: 12125

**Comment by J-Jamet** [comment]
Thank you for this detailed feedback, I will capture the exception raised by the new method which clears the cilpboard. I don't know why she's bugging. I will try to solve the problem for the next version.
