### ISSUE TITLE
KeePassDX crashing while opening ChaCha20 encrypted database with Argon2 KeyDerivation

### ISSUE THREAD

**Issue by Ihon75** [Kunzisoft/KeePassDX#466]
**Describe the bug**
While trying to open my Password-File using a 20  character long PW plus a Key-File KeePassDX is crashing with the error message:
org.xmlpull.v1.XmlPullParserException: unterminated en...

**To Reproduce**
1. Generate a new Database File with KeePass 2.42 using ChaCha20 Encryption and Argon2 KDF.
KDF Parameter: Iterations 4, Memory 4, Parallism: 4
Use a Key-File plus long Password
2. Open new KeePass File with KeePassDX under Android 
3. Enter Password and Key-File location, open file

**Expected behavior**
View the open KeePass Database

**Screenshots**

** Keepass Database **
 - Created with: Windows KeePass 2.42
 - Version: 2]
 - Location: Remote on NextCloud
 - Size: 10 MegaBytes
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: libre
 - Language: English

**Android (please complete the following information):**
 - Device: GalaxyS9
 - Version: Andoid 10, G960FXXU7DTAA/G960FOXM7DTAA/G960FXXU7DTA3

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
Thank you for the feedback,
The app should not crash if there is an XML error, how do you see the error message?
My first intuition is that you have a too large database. Do you have attached files larger than 500KB inside? If so, the Android XML pull parser may not be able to decrypt a large binary file.

**Comment by J-Jamet** [comment]
It may also be a bug in the implementation of algorithms. I have to be able to reproduce the issue to correct it.
If you could give me a database without sensitive data with this problem, it would help me a lot.

**Comment by Ihon75** [comment]
Hi,
sorry, I was absolut busy the last days.
Attached is a DemoDatabase and Key file with the same settings as my master file but without attachments inside. Same error on my mobile.

Password: Kunzisoft/KeePassDX

Best 


[DemoDatabase.zip](https://github.com/Kunzisoft/KeePassDX/files/4237816/DemoDatabase.zip)
Ihon

**Comment by J-Jamet** [comment]
Thank you, it will be very useful for debugging! :)

**Comment by Ihon75** [comment]
It's a pleasure, thank you for KeepassDX

**Comment by J-Jamet** [comment]
I just tested with my devices, I have no worries about opening the database.
But I see you have version 2.5.0.0beta25, I improved and fixed the compression / decompression algorithm in version [2.5.0.0beta26](https://github.com/Kunzisoft/KeePassDX/releases/tag/2.5.0.0beta26), can you tell me if it works with this one? (The version on F-Droid is not up to date)

I can't reproduce your problem, otherwise I am thinking of upgrading the algorithm code of Argon2 with the latest official sources, it may be better for you, but it may take time.

**Comment by J-Jamet** [comment]
Or I have another theory: maybe your NextCloud sync isn't working properly and you're trying to open a half-downloaded file. Can you open your bases locally?

**Comment by Ihon75** [comment]
I downloaded version 2.5.0.0beta26 from Google Play store.
This version is working and can open the database.

The version 2.5.0.0beta25 from F-Droid is not able to open the file, independent if it is opened out of NextCloud or locally stored on an SD Card.

So, thank you problem solved from my point of view
