### ISSUE TITLE
Biometric saving

### ISSUE THREAD

**Issue by ghRegEdit** [Kunzisoft/KeePassDX#467]
A bug with saving a biometric key. I enter the password, I scan the fingerprint, but the biomtry is not saved (I still did not understand how the application saved it before.) If the password is not entered, but with the "Password" checkbox selected, the biometric button is available.

If you enter the password and press the biometrics button and successfully scan the fingerprint, then press the "open" key for some reason. 

Sony Xperia XA2+
Android 8.0

**Comment by J-Jamet** [comment]
There is no bug in the description of your example.

You have to press the button to open the biometric prompt, and after that you can scan.

The checkbox is used to know if you want to save the fingerprint (by entering the password) or use it to directly open the database.
Only checkbox is important because databases can have empty passwords.

https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

**Comment by ghRegEdit** [comment]
1. I enter the password.
2. I press the button "Biometrics"
3. I mark the checkbox "Password"
4. I click to open.
(At this point, the biometric key should be saved? Correct?)
5. Blocking the base.
(The application writes: "The master password has not yet been saved for this database.)

How to save it?

**Comment by J-Jamet** [comment]
This is not the right method.
1. Enter the password (the checkbox is checked)
2. Press button biometric
3. Scan your fingerprint
At this point if the database is open, the fingerprint is saved for the database

To open the database again :
1.Press button biometric
3. Scan your fingerprint

**Comment by ghRegEdit** [comment]
We are talking about the same thing.

Now figured out save:

1. Delete encryption keys.
2. Enter password (Checkbox checked)
3. Press the Biometrics button.
2. Scan the fingerprint
3. Click "Open"
4. Block the base.
5. The next time you log in, the application already requests a Biometric key.

**Comment by J-Jamet** [comment]
No, don't click "open", at point 4 the database is open or there is an error displayed.

**Comment by ghRegEdit** [comment]
Indeed, it opens after scanning itself. Here I was mistaken.

**Comment by J-Jamet** [comment]
I will improve the wiki to avoid confusion.

**Comment by ghRegEdit** [comment]
OK, We hope!
