### ISSUE TITLE
How to set expiry dates for password entries?

### ISSUE THREAD

**Issue by aneeroodh** [Kunzisoft/KeePassDX#470]
I have noticed that password entries can have expiry dates. 

![Screenshot_20200222-121928_VLC](https://user-images.githubusercontent.com/56296535/75088041-cef23f00-556d-11ea-8f7d-5aec2354c376.png)

However, I haven't found a way to set the expiry dates. How to do that? 

I am sorry if this is not an appropriate place to ask such questions.

**Comment by J-Jamet** [comment]
It's the good place.
KeePassDX uses the kdbx file format which is used by other applications. Expiration is an entry metadata, which may be populated in other programs.
It is planned to be able to enter this value in KeePassDX but I did not have time to develop the feature.

**Comment by aneeroodh** [comment]
> It is planned to be able to enter this value in KeePassDX but I did not have time to develop the feature.
Yes, of course, I understand. 

I am new to KeepassDX or any password manager for that matter. 

Under the Other Devices section of the Read Me, you do mention programs like KeePassXC or KeeWeb. And they do what you describe and much more. 

So I have cleverly setup a FTP sync and have solved my problem. 

Thank you for replying Mr. Dev.

**Comment by J-Jamet** [comment]
It is possible to select the expiration date from the 2.5beta29 version of the application.
