### ISSUE TITLE
Add challenge response Yubikey feature compatible to KeepassXC

### ISSUE THREAD

**Issue by ovz93br43v7** [Kunzisoft/KeePassDX#472]
**Is your feature request related to a problem? Please describe.**
Please add a challenge response Yubikey feature compatible to KeepassXC. https://keepassxc.org/

**Describe the solution you'd like**
I want to use my KeepassXC database (which is secured with the challenge response Yubikey feature) with KeepassDX.

**Comment by J-Jamet** [comment]
Duplicate #137 #8 #427
