### ISSUE TITLE
Internal image viewer for attachments

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#473]
Linked to #189 #749

**Comment by OLLI-S** [comment]
Such an internal image viewer would really be fantastic.
So I can open member cards of various shops that I have stored in KeePassDX as attachments.

**Comment by ArminWeb** [comment]
Really would be a handy feature!

**Comment by J-Jamet** [comment]
Initial tests indicate that it will take longer than I thought. I wanted to use the [Loupe](https://github.com/igreenwood/loupe)  library but it is not API14 compatible so I'm trying to modify its source code, however I have some bugs. So I prefer to take care of it quietly in version 2.9.4.

**Comment by J-Jamet** [comment]
I spent a lot of time on this feature. It's not easy to implement at all but I managed to solve all the big problems.
For all image binaries, there will be a preview in the description of an entry and a full screen viewer to be opened to see the image elements in detail.

I merged the code with binary file encryption on the fly, i.e. #749 the displayed images are never decrypted in clear on the disk, the display is done in real time by decrypting streams of temporary encrypted binary files in the views.

For those who want to test, you can compile the branch `feature/Image_Viewer`.
There are still some thread synchronization bugs and views to fix but don't hesitate to give me feedback on it.

**Comment by J-Jamet** [comment]
Merged in `feature/Image_Viewer`

**Comment by J-Jamet** [comment]
Merged in `develop` branch
