### ISSUE TITLE
Can't open database : org.xmlpull.v1.XmlPullParserException

### ISSUE THREAD

**Issue by dbeley** [Kunzisoft/KeePassDX#476]
Hello when opening my database keepassdx throws the following error message :  
org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT  -----BEGIN PG...@106:1 in java.Io.InputStreamReader@88742d7)

As the error may imply, it could be a problem with the parsing of some text entries. I can't really reproduce the error, I've tried with the same database without the attachments that could be problematic (ssh keys) but the error is still happening.

The database opens fine with keepassXC and keepass2android. 

**Screenshots**

![Screenshot_20200301-111649](https://user-images.githubusercontent.com/6568955/75624669-b2ca4f80-5bb6-11ea-8177-a9b0ca805487.jpg)

** Keepass Database **
 - Created with: KeepassXC
 - Version: 2
 - Location: local
 - Size: 800ko
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: F-droid
 - Language: French

**Android (please complete the following information):**
 - Device: LG V30
 - Version: 9.0

**Additional context**
The database is correctly opened by KeepassXC and keepass2android.

**Comment by J-Jamet** [comment]
This issue is normally solved in version [2.5.0.0beta26](https://github.com/Kunzisoft/KeePassDX/releases/tag/2.5.0.0beta26).
Can you test with this one?

**Comment by dbeley** [comment]
Thanks for the very quick answer, I can confirm it's working fine with the latest build 👍
