### ISSUE TITLE
FDroid build not updating

### ISSUE THREAD

**Issue by newhinton** [Kunzisoft/KeePassDX#477]
The current version on F-Droid is 'Version 2.5.0.0beta25'

The latest tagged version is '2.5.0.0beta26'. F-Droid should therefore build the latest version.

(I am aware that this may take a while, but it has been nearly a month)

The fdroid buildlog shows the following:

["could not bring up vm 'builder*default'" ](https://f-droid.org/wiki/page/com.kunzisoft.keepass.libre/lastbuild_26)

also, it seems the metadata in the fdroid data repo is missing: [repo](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.kunzisoft.keepass.libre.txt)

(Linked from [here](https://f-droid.org/wiki/page/com.kunzisoft.keepass.libre))

was this intended, or should i open an issue with fdroid?

**Comment by J-Jamet** [comment]
I just checked, indeed., there is an error with the build on Fdroid, it should be resolved but seems after an error on the current version, fdroid server does not rebuild. You have to open an issue on fdroiddata repo.

**Comment by newhinton** [comment]
Great! I will do that.

**Comment by newhinton** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/1971

**Comment by J-Jamet** [comment]
Thank you. (But the metadata file for keepass dx is here https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kunzisoft.keepass.libre.yml)
