### ISSUE TITLE
KeePassXC seems store TOTP info differently

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#482]
Check how new versions of KeePassXC store TOTP information.

**Comment by MisterY** [comment]
I don't see any option to generate TOTP from an entry set up with KeePassXC. The wiki doesn't help much. Am I missing something? How is TOTP copied? Any option in the included keyboard?

**Comment by J-Jamet** [comment]
KeePassXC, like KeePassDX generates an otp link which contains the parameters of the otp with the secret key in a custom field with the label "otp".
You can modify the otp link by editing the entry.
Then in the entry display screen, the linked token is created.
The generation of the token is done in the keyboard.
If a specific configuration is not recognized by KeePassDX please indicate precisely the TOTP format link.
