### ISSUE TITLE
Title and username of an entry in the entry list is not updated after the entry has been changed

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#487]
**Describe the bug**
The list consists of entries and groups. The title and username of an entry in the  list is not updated after the entry has been changed.

**To Reproduce**
1. Open an entry.
2. Change it's title or username.
3. Save the entry through menu and tap "back" to return to the list.
4. You will see that the entry displays old username and title. But if you go to another group and return back than you will see that the entry shows new title and username.

**Expected behavior**
The entry will display new title and username as soon as it has been changed.

**Keepass Database**
 - Location: Remote file retrieved with GDrive app

**KeePassDX (please complete the following information):**
 - Version:2.5beta28
 - Build: Free
 - Language: russian

**Android (please complete the following information):**
 - Device:Xiaomi Redmi note 8t
 - Version: 9

**Comment by J-Jamet** [comment]
Thank you, indeed, I missed it, it's just a display bug, so no worries about database corruption. The new optimized methods for the display prevents the visual update of an entry, I will solve the problem for the next version.
