### ISSUE TITLE
Damage to database attachments after saving

### ISSUE THREAD

**Issue by ghRegEdit** [Kunzisoft/KeePassDX#489]
1. I make changes to the standard recording field.
2. The record contains an attachment (for example, a text file or * .png QR-code
3. After trying to open the synchronized file through Keypass Pass or KeyPass, they all, in any record become 1 KB in size and do not open, even the text file contains an incomprehensible set of characters.

**Expected behavior**

** Keepass Database **
 - Created with:  KeePass Professional 2.44 
 - Version: [e.g. 2] *.kdbx ( use *.exe file extension instead of *.KDBX)
 - Location: Google Drive
 - Size: ~900 KiB
 - Contains attachment: [e.g. Yes]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta26]
 - Build: [e.g. Free]
 - Language: [e.g. Russian]

**Android (please complete the following information):**
 - Device: Sony Xperia XA2 +
 - Version: Android 8

**Additional context**
 - Browser for Autofill: KeepassXC
- Another soft KeepassXC 2.5.3

**Comment by ghRegEdit** [comment]
https://imgur.com/jyrY1v4 DAMAGE
https://imgur.com/pVeZJIK NORMAL

**Comment by J-Jamet** [comment]
Please update your version to 2.5beta28

**Comment by ghRegEdit** [comment]
Good. I did not know that a new version was released. Thank you. My version database was saved from losing all investments by google version control :-)

**Comment by J-Jamet** [comment]
I understand, it's a good practice! ;)

**Comment by ghRegEdit** [comment]
Yeah, "version control" is Our Everything 😉
