### ISSUE TITLE
Autofill API error should mention Android versions not API versions

### ISSUE THREAD

**Issue by rugk** [Kunzisoft/KeePassDX#49]
I am very sorry but the usual user does not know what "API 25" or so is. If you are lucky they know what Android version 7 or 8 is… :wink: 

So better use these.

**Comment by J-Jamet** [comment]
I know the version and name are better for visibility, but we need to add this information manually for each new version, so it's not maintainable.

**Comment by rugk** [comment]
Hu? Why do you need to add this for each release??

The API/Android version were autofill is supported, is and always will be v25/Android 8 (hope I got the correct numbers here). That is a static string and does not/should not change in the future.

**Comment by rugk** [comment]
Just noticed I did not even mention it was about the autofill API. Sorry, maybe this was what you misunderstood.

**Comment by J-Jamet** [comment]
It's possible but each android system only knows its version number and the name of the predecessors. For each new version, it will be necessary to update the correspondence table in the code, so to maintain it is so annoying. It's simply that. :/ (https://stackoverflow.com/questions/10547818/androidhow-to-find-the-android-version-name-programmatically/13258693)

**Comment by J-Jamet** [comment]
Now I tell myself that I can do the array and put a warning to update it if a feature uses an undeclared version. I'll do that! ^^

**Comment by rugk** [comment]
Yeah, why not just hardcode it, at least for this feature…

**Comment by J-Jamet** [comment]
I'll follow you and write hardcode but it's the first step to the dark side. C8<]

**Comment by rugk** [comment]
LOL, but it is a static error for a static feature, which exists only in a static version, so this seems to be all fine… :smile: 

I don't know if you use that error for a different feature (in a different version?), but there you can do it in a different way. :wink:

**Comment by J-Jamet** [comment]
Feature added ! C8<] -> beta8
