### ISSUE TITLE
back button in add entry screen does not prompt to save before data is lost

### ISSUE THREAD

**Issue by jmichael2497** [Kunzisoft/KeePassDX#490]
**Describe the bug**
back button in add entry screen does not prompt to save before data is lost. during testing i had filled out a full new entry, pressed the back button, and just like KeePassDroid it just goes to prior screen without prompting to save or not.

**To Reproduce**
1. Go to add entry
2. Click on any field and enter something
3. Press the back button

**Expected behavior**
If anything has been entered (or changed while i'm at it), hitting back button should prompt to save or not (which is what KeePass2Android does).

** Keepass Database **
 - Created with: KeePassDX 2.5.0.0beta25
 - Version: 2
 - Location: internal
 - Size: 1.5k
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: Libre
 - Language: English

**Android (please complete the following information):**
 - Device: Galaxy S5
 - Version: 9.0

**Additional context**
 - New user comparing KeePassDroid, KeePass2Android, KeePassDX

**Comment by J-Jamet** [comment]
I will add a dialog which will ask if we are sure we want to exit without saving. I redid the visuals of this screen, the validation button is now a real validation button.
