### ISSUE TITLE
does not accept new key file location during opening when set to remember key file location

### ISSUE THREAD

**Issue by jmichael2497** [Kunzisoft/KeePassDX#491]
**Describe the bug**
does not accept new key file location during opening when set to remember key file location. have to go removed db from recent to forget associated key file location, or turn off remember location setting, before new key file location is accepted.

**To Reproduce**
1. While default settings remember key file location is enabled
2. Go to open recent db
3. Click on file picker to specify different key file location

**Expected behavior**
When I pick a different key file location, it should accept that instead of continuing with the old location.

** Keepass Database **
 - Created with: KeePassDX 2.5.0.0beta25
 - Version: 2
 - Location: internal
 - Size: 1.5k
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.5.0.0beta25
 - Build: Libre
 - Language: English

**Android (please complete the following information):**
 - Device: Galaxy S5
 - Version: 9.0

**Additional context**
 - New user comparing KeePassDroid, KeePass2Android, KeePassDX

**Comment by J-Jamet** [comment]
Thank you for the feedback, I have already fixed similar bugs in development for the 2.5beta29 version, I will verify that it is OK.

**Comment by jmichael2497** [comment]
i switched from libre to free, so i can make sure i'm not reporting old bugs, sorry.

verified works with newer version, thanks.
