### ISSUE TITLE
Version after 2.5.0.0beta26 seem slower

### ISSUE THREAD

**Issue by SpazMahTazz** [Kunzisoft/KeePassDX#494]
My phone isn't the fastest phone in the world (Android ver8.1), but I had a noticeable speed difference when I upgraded to a version higher than 2.5.0.0beta26 (english).

This is in regards to booting the app, going back to the home screen from the default database, and sometimes loading a database. The newer versions of KeePassDX are slower. All my databases are in google drive. Hope I gave enough information.

**Comment by SpazMahTazz** [comment]
Just tried upgrading again from 26 to 27 then to 28 and it hangs on the splash screen of the padlock for about 1 or 2 seconds. Pressing the back button from a database's login screen also takes 1 to 2 seconds.
When I go back to 26 the splash loads in half a second and so does clicking the back button.
I am using a BlackBerry KeyOne, but I'm not knowledgeable enough to compile the code I'm sorry. I can try but how do I do it? Thanks for your super fast reply.

**Comment by J-Jamet** [comment]
OK, in this case, I'm going to make you a version without the "largeHeap" parameter I'm going to upload, tell me if that solves the problem. (It may take time)

**Comment by J-Jamet** [comment]
[KeePassDX_2.5beta29_Test_2020_03_22_11_15.zip](https://github.com/Kunzisoft/KeePassDX/files/4365025/KeePassDX_2.5beta29_Test_2020_03_22_11_15.zip)

**Comment by SpazMahTazz** [comment]
I installed the test but it's still the case.
After going through the tooltips and using the app as normal, it still takes a second to open / go back.
Maybe if more people get the same issue then it could be a higher priority, but if you need me to keep testing for you then feel free to ask me!

**Comment by J-Jamet** [comment]
The problem is that I have no more idea about the problem, without being able to reproduce it with one of my devices, it will be very difficult to debug.

**Comment by J-Jamet** [comment]
I have an idea, it is possible that the methods that check the presence of files can slow down your device. Do you have a lot of databases in the list of recent files?

**Comment by SpazMahTazz** [comment]
I tried this just now on 29 (26 doesn't have this setting as you know), nothing was listed. 26 is still faster. I've been completely uninstalling and reinstalling the apk each time go to a different version so the settings should reset every time.
So speed suddenly is not an issue anymore when I use a local database (tested on a brand new database created after a fresh install of version 29). It is an issue when I connect to the database and key file in my google drive. Hope that is helpful info.

**Comment by J-Jamet** [comment]
Thank you, important information indeed. I have a little idea about the problem, I will try to verify the files in a thread.

**Comment by J-Jamet** [comment]
It's OK in version 2.5beta30. If no more issue like this, the next version is a stable version.

**Comment by SpazMahTazz** [comment]
Well done! It's back to normal. Just tested it 👍
