### ISSUE TITLE
Nextcloud File Upload conflict

### ISSUE THREAD

**Issue by kermit-frog** [Kunzisoft/KeePassDX#497]
**Describe the bug**
When saving the database, nextcloud says "file upload conflict. Pick which version to keep."

**To Reproduce**
1. Unlock database
2. Save database
3. See error

![Screenshot_20200325-204158_cropped](https://user-images.githubusercontent.com/25160261/77578629-296a1c80-6ed9-11ea-8ca5-bdc6cc6a1a29.png)

![Screenshot_20200325-203924](https://user-images.githubusercontent.com/25160261/77578424-d3957480-6ed8-11ea-8bb0-6e243c5abccc.png)

**Expected behavior**
Keepass should save the file to nextcloud without error. 

** Keepass Database **
 - Created with: KeepassDX beta 
 - Version: 2.5beta27
 - Location: nextcloud app v 3.11.0 RC 2
 - Size: 150 kb
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 2.5beta28
 - Language: english

**Android (please complete the following information):**
 - Device: [mi mix 2s]
 - Version: [10]
- Arrow OS

**Additional context**
issue did not occur in previous version of keepassdx.

**Comment by J-Jamet** [comment]
Thank you for your feedback.
There were 2 fixes in version 2.5beta28. The problem can come from the method `UriUtil.isUriAccessible()`.
Can you confirm that the problem disappear when you reinstall the version [2.5beta27](https://github.com/Kunzisoft/KeePassDX/releases/tag/2.5beta27) ?

**Comment by kermit-frog** [comment]
Hi @J-Jamet,

thank you for your prompt answer. 

i hope i did not mess up the versions. what i did now to start clean:
- uninstalled keepassdx 2.5 beta28
- cleared failed uploads in nextcloud app
- made sure my windows keepass database is not in use (exit keepass)
- installed keepassdx 2.5 beta27

as soon as i open my database i get the nextcloud error again. i am not sure anymore which version i had installed before i updatedmy android today, but i mean it was the 2.5 beta28. i tried the beta29 too, without success though. 
my windows version of keepass is 2.44. i did not change anything there.

**Comment by kermit-frog** [comment]
Hi @J-Jamet,

i think i found the solution and i'm sorry for confronting you with this problem.

the problem was the nextcloud app. i downgraded from version 3.11.0 RC 2 to version 3.10.1 and now it works without error message. i tried keepassdx 2.5 beta27, 28 an 29 and everything is fine. 
Sorry, sorry, sorry!

Thank you very much for your immediate reaction. 👍  i will donate now. 💰

**Comment by J-Jamet** [comment]
No problem, don't be sorry, it's always good to have feedback on compatibility with other apps! ;)
And thank you, it's really generous.
