### ISSUE TITLE
Autofill pop up in Google Play

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#499]
Autofill appears in the input field of the Google Play review (Android 10)

**Comment by null-von-sushi** [comment]
[I am the person who caused this issue to open]

When I said the popup shows too much, I meant the google play application, not the website. 
[Zip with screenrecording](https://github.com/Kunzisoft/KeePassDX/files/4383374/20-03-25-20-24-38.zip)

**Comment by J-Jamet** [comment]
Thank you for the precision and the video.
However from a technical point of view, this should not happen. The algorithm should detect autofill fields associated with passwords to display the popup.
And even more bizarre, I can't reproduce the problem on my devices.

**Comment by null-von-sushi** [comment]
> However from a technical point of view, this should not happen

Alas, it happens :D 

If there's anything (not too drastic, like factory resets) I could do to help narrow this issue down, I'd be more than happy to test it.
I think I had this happen even on a previous device however, so it's either something in the application, or something about what I install that may interfere.

Current device is Oxygen OS 10 (Android 10).
Previous device was Lineage OS 16 with Microg and no Google Play. 

Happened on both iirc.

**Comment by J-Jamet** [comment]
Yes it happens, I was just saying that because I did not yet have the solution in mind. ;)
It is possible that the integrated Autofill service (or another module) adds recognized tags (View.AUTOFILL_HINT_PASSWORD) or removes the specific recognition of these tags.

**Comment by null-von-sushi** [comment]
Is there any way I can check this? I am not really a developer I am afraid :S

**Comment by J-Jamet** [comment]
Can you select a dummy entry with username and password to see if it adds text? (I'm not a real developer either you know and I'm always scared, I can see that you are more talented ;))

**Comment by null-von-sushi** [comment]
> (I'm not a real developer either you know and I'm always scared, I can see that you are more talented ;))

Haha, I'm really not. My crowning achievement is a bash script :joy: 
But thanks


Anyways, I had a look, and it does indeed fill in info if I let it. The text field is treated as a Username field it seems.

**Comment by J-Jamet** [comment]
Okay, it is certain that the error comes from my code.
https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/autofill/StructureParser.kt but where exactly I don't know. Can you compile and debug this part to see what is the result in your case?

**Comment by null-von-sushi** [comment]
Yeah, I genuinely don't know how to do that. I mean, I think I can get android studio to maybe compile KeepassDX but, I have no idea how to debug anything, let alone compile a single part of an application only (?).

Sorry...

**Comment by J-Jamet** [comment]
No problem, we will find another way to resolve the bug. I will improve the algorithm and make test packages. ;)

**Comment by null-von-sushi** [comment]
No problem, sorry again.

**Comment by J-Jamet** [comment]
I will fix other problems for version 2.5beta30 and I will upload the new version quickly. I fixed the algorithm, you will tell me if it is better in this version.

**Comment by J-Jamet** [comment]
Can you check if the 2.5beta30 fixes the issue for you?

**Comment by null-von-sushi** [comment]
Well I installed the APK from the releases page and it _seems_ to be fixed. I will report again once the version is added to Google Play / F-Droid. The version on github seems to be `com.kunzisoft.keepass.free` while the one I have installed is `com.kunzisoft.keepass.libre`.
