### ISSUE TITLE
Allow user to specify font of item's comments section

### ISSUE THREAD

**Issue by iegubkin** [Kunzisoft/KeePassDX#5]
Would it be possible to allow the user to specify a font for the comments section of an entry that clearly differentiates similar characters like: l 1, i etc? This has always been a problem in Pellin's version for me. Or, the app itself could simply use a font for the comments section that does a better job distinguishing between similar characters.

Ref: [https://ux.stackexchange.com/questions/79090/what-is-a-sans-serif-font-that-still-clearly-differentiates-similar-characters-l](https://ux.stackexchange.com/questions/79090/what-is-a-sans-serif-font-that-still-clearly-differentiates-similar-characters-l)

Thanks

**Comment by J-Jamet** [comment]
Done in 2.5.0.0beta5
