### ISSUE TITLE
Autofill for apps doesn't work properly with 2.5beta30

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [Kunzisoft/KeePassDX#502]
**Version** :

![2.5beta30](http://imgur.com/a/4sxw0ja).

**Description** :

The "Sign-in with KeepassDX" popup usually appears when focused on most text fields in non-Chrome apps, but it stopped working after the seemingly "upgrade" of the autofill algorithm.

**What I tried** :

Aside from the automatic popup upon text field focus, is long pressing on the field, tap on "Autofill", then nothing happens, in contrast to the expected behavior which is the same as tapping on the sign-in popup, which then opens the KeepassDX app.

**Problem summary**:

1. Sign-in popup not appearing on most apps.
2. Even manually clicking on "Autofill" won't show the KeepassDX app (regardless of lock status).

**Devices tested on:** 

Galaxy Note 8, Galaxy J7 Pro

**Android** :

9.0

**Comment by J-Jamet** [comment]
Can you be more specific about the websites or applications that do not work for you and the browser you are using. Thank you
Because there was a bug in the previous algorithm which made the autofill appear in too many forms.

**Comment by TruthIsIAmIronMan** [comment]
This is just a few of the apps I tested it on:

- Reddit
- Some banking apps
- Facebook
- Tachiyomi (tracking page)
- AnYmeX (myanimelist tracker app)

Note that this are just a few, and it would take me a long time to list everything as I have hundreds of apps installed on my device.

For websites:

- Microsoft account login
- Google account login
- Reddit
- Facebook

Again just a few, but really my main concern is on the apps over websites.

**Comment by J-Jamet** [comment]
Do you have the setting `Display pop-up windows while running in the background` activated, it is an option on some devices.

**Comment by TruthIsIAmIronMan** [comment]
I don't know the setting. Also, had no problems before this version so I don't think it has to do with any similar setting.

**Comment by J-Jamet** [comment]
Okay, I fixed the old algorithm in the last version because the parse of the HTML nodes was not working properly. Now the popup should appear only if there is at least one password field in the form. I will test with the applications you have listed.

**Comment by TruthIsIAmIronMan** [comment]
This is good news. Thank you.

**Comment by J-Jamet** [comment]
OK, so with 2.5beta30:

All the listed sites work with [Lightning](https://f-droid.org/en/packages/acr.browser.lightning/), [FOSS Browser](https://f-droid.org/en/packages/de.baumann.browser/) and default browser in LineageOS. 
If there is a problem on your device for sites, it must come from the WebView of your device or from the browser you are using.

For applications: Tested some and no result, I will debug to find out why.

**Comment by TruthIsIAmIronMan** [comment]
Oh, I forgot to mention that I also tried to restart my phone, and also reinstall then restart again for common troubleshooting but did not succeed resolving the issue.

**Comment by J-Jamet** [comment]
I improved the algorithm with another parser which checks the types of android input. It should work for the next version 2.5beta31. For google login, it only works for the second screen which asks for the password, because I cannot know on the first screen that it is a login form.
