### ISSUE TITLE
Auto search Autofill result by URL

### ISSUE THREAD

**Issue by fajabird** [Kunzisoft/KeePassDX#504]
**Current behavior**
I use Fenec-Browser. Autofill seem to work as I can select KeepassDX from the pop-up in the browser. Problem is, that KeepassDX shows up but does only display the password-groups but does not automatically search for the relevant entries in the database. 

**To Reproduce**
1. Go to URL in browser that matches a URL in one of the entries in your Keepass Database
2. Click on username on the login-page
3. From the popup select fill from KeepassDX
4. Entry with URL is not automatically fetched

**Expected behavior**
I would expect, that when I browse to a specific URL and select KeepassDX to fill the credentials that KeepassDX opens up and automatically searches for the URL in the database to automatically display the relevant result(s). Only if it cannot find any entries it will ask the user for e.g. manually selecting an entry. If it finds multiple entries it will display all results - just like when manually searching for an term. 

** Keepass Database **
 - Created with: [e.g Linux, KeepassXC ]
 - Version: [e.g. 2.5.3]
 - Location: [e.g. Local file, synced to Nextcloud]
 - Size: [e.g. 30KB]
 - Contains attachment: [e.g. No]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta30]
 - Build: [e.g. Free]
 - Language: [e.g. German]

**Android (please complete the following information):**
 - Device: [e.g. Motorola one]
 - Version: [e.g. 9]

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
I understand the need but it is not a bug, it is a request for functionality, so I modified your issue in this way. The other points must first be debugged.
