### ISSUE TITLE
Block timeout is set to never but the app locks DB anyway

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#507]
I am the only person who has access to tmy phone. So I set the Idle time before locking the database to never. But the app locks it randomly anyway. For example, if I unlock the DB before I go sleep then most likely it will be locked when I wake up (after 8 hours). Or it could be locked even faster. I just don't know how to reproduce it.

**KeePassDX (please complete the following information):**
 - Version: 2.5beta30

**Android (please complete the following information):**
 - Device: Xiaomi Redmi note 8T
 - Version: MIUI11, it's based on Android 9

**Comment by J-Jamet** [comment]
There is very little chance of random locking of the app. The lock is always linked to a broadcast request that comes from somewhere.
Are you sure that you are not closing a notification that closes the database, you are not locking the database from the keyboard or you did not activate the lock setting when the screen is turned off?

**Comment by zveber** [comment]
My phone is not connected to a keyboard and I disabled locking when screen is turned off.
And I don't see any notifications from the app (they are enabled but actually I don't like them, they waste screen space).
I'm agree that don't lock DB is not good but It's inconvenient to enter full password every time. I've found #152 and #102 and they  are good ideas. So I rhink I will wait for it. Maybe the issue should be closed.

**Comment by adlisval** [comment]
I have a similar issue. I set the Idle timmer to 1 minute and it just closes while I'm scrolling through the app. It seems the timer doesn't stop when the app is used, and it just closes the app. 

- version 2.5beta30 - from fdroid
- lineageos

**Comment by J-Jamet** [comment]
@adlisval Scrolling the page is simply not part of the events that reset the timer. Opening a new screen resets the timer.

**Comment by adlisval** [comment]
Ah, ok, thanks. Good to know. But it's strange to use the app (scroll through it or whatever), and suddenly the app closes. For me, not using the app is not doing anything in it for X amount of time, then it can close. Otherwise it's like having your OS signing you out while you're scrolling through it's menu...it's a bit strange (imo).
