### ISSUE TITLE
UI Issue - Navigation bar does not match the dark theme

### ISSUE THREAD

**Issue by VinayMichaelSamuel** [Kunzisoft/KeePassDX#510]
**Issue**
I am using the AMOLED theme but the the Navigation bar is the same as the light mode. Here's a screenshot of another app which has the same issue for reference.
![Screenshot_20200408-194559_Habits](https://user-images.githubusercontent.com/59197885/78807976-d95d8080-79d5-11ea-9879-e9eab9d7575f.jpg)

**Expected behavior**
Here's how another open source app is doing this. The navigation bar background changes colour when the theme is changed to match the AMOLED or dark mode colour.
![Screenshot_20200408-014957_Goodtime](https://user-images.githubusercontent.com/59197885/78808073-f8f4a900-79d5-11ea-8016-bef28da62ba2.jpg)

**KeePassDX Version:**
 - Version: 2.5beta30
 - Build: libre

**Android:**
 - Samsung M30s
 - Android Version 9 with One UI

**Comment by J-Jamet** [comment]
Is the problem also present with the night theme?

**Comment by VinayMichaelSamuel** [comment]
> 
> 
> Is the problem also present with the night theme?

Yes. The nav bar doesn't change to match the night theme.

**Comment by J-Jamet** [comment]
Thank you, it was to be sure, I can't actually test on my devices but I know where the problem is coming from, it will normally be resolved for the next version.

**Comment by mobilekosmos** [comment]
We also had this issue, it's only o some devices, like Samsung to name one, it works on Pixels, you need to set android:navigationBarColor in the theme to fix it. Btw. the second screenshot posted by @VinayMichaelSamuel doesn't present the correct colors for dark theme, so don't use it as a rule to how it should be.

**Comment by J-Jamet** [comment]
@mobilekosmos Yes, this is what has already been done, you can see the [commit](https://github.com/Kunzisoft/KeePassDX/commit/b1ec93ceb5b0e428e3f9fe3163d2e026a9e25f34) earlier in the conversation.
