### ISSUE TITLE
App not requesting "display pop-up window in foreground and in background" permission.

### ISSUE THREAD

**Issue by THEDanielCF** [Kunzisoft/KeePassDX#511]
I am unable to get autofill to pop up on screen. I believe my issue is that the app needs the "display pop-up window in foreground and in background" permission but I am unable to enable it. The permissions menu is grayed out and it says "no permissions requested" 
![Screenshot_20200409-001003](https://user-images.githubusercontent.com/12603562/78869020-bb554780-79f8-11ea-8d9e-a080434c3b32.png)

I have root, so I tried to enable it in terminal with this command but that did not prove fruitful.
![Screenshot_20200409-003126](https://user-images.githubusercontent.com/12603562/78869646-bba21280-79f9-11ea-9dbd-462ce221e449.png)

I'd really appreciate advice. Thanks.
    Daniel

**Comment by J-Jamet** [comment]
It is simply because the development of the autofill is not yet finished. It works for some web browsers but not yet for applications. It will normally be ok for the next version. Note that there is no need for permission as it uses the autofill service on your device.

**Comment by THEDanielCF** [comment]
Ah, thanks. I tried it out on firefox and it worked. Thanks for working on this. A free open-source password manager with autofill is something I've been looking for for a while.
