### ISSUE TITLE
TOTP not recognized for 'key=...' scheme

### ISSUE THREAD

**Issue by MisterY** [Kunzisoft/KeePassDX#513]
**Describe the bug**
The OTP is not generated for NextCloud 2FA, scheme is `key=BON4U3IICAQTPIXN`

**To Reproduce**

1. Enable TOTP in NextCloud Settings, copy the key. 
2. Add an entry in KeePassXC, using the `key=` + the above key 
3. Confirm by generating TOTP and verifying in NextCloud
4. Open the entry in KeePassDX, no OTP field recognized.

**Expected behavior**
The OTP field recognized and available for copying.

** Keepass Database **
 - Created with: complicated. Created a reeeealy long time ago, upgraded protocols and settings over time.
 - Version: 2
 - Location: Accessed through SAF/pCloud
 - Size: 680KB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.5.0.0beta30
 - Build: FDroid
 - Language: English

**Android (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - Version: 10

**Additional context**
N/A

**Comment by MisterY** [comment]
NextCloud settings
![image](https://user-images.githubusercontent.com/462445/79044425-5fabd980-7c05-11ea-85af-46dfc35c1e54.png)

**Comment by MisterY** [comment]
This is most likely provided by this extension
https://apps.nextcloud.com/apps/twofactor_totp

**Comment by MisterY** [comment]
The same with the Microsoft 2FA.
`key=ADQPACX5IKF62NR7&size=6&step=30`

**Comment by J-Jamet** [comment]
Thank you for the feedback, indeed, I did not know that this format existed. The problem will be to redo a parser for this format and define the default values.

**Comment by J-Jamet** [comment]
First, I advise you to use the link generation already present to be compatible until the integration in a new app update.

**Comment by J-Jamet** [comment]
It was only a bad parenthesis in a regular expression! :/ Sorry for that

**Comment by MisterY** [comment]
Cool! That's good to hear. Will try out with the next build. Thanks!

**Comment by MisterY** [comment]
Thank you, I can confirm that it works now.
