### ISSUE TITLE
Add KeePassDX Accessibility Service

### ISSUE THREAD

**Issue by jwsp1** [Kunzisoft/KeePassDX#514]
Unfortunately, KeeKaasDX doesn't work for me using Brave Browser (based on Chromium). I've tested several passwordmanager apps and it looks like the only one working reliable for me is Bitwarden. No other app than Bitwarden is using Accessibility Services to scan for Login fields hence this should be the key in order to fix this problem.
I'm not quite sure if it's correct but I read that Google does only allow apps to use Android Accessibility for helping people with disabilities (see https://community.brave.com/t/autofill-not-working-reliably-with-bitwarden-or-keepass2android/70464/22). 
If apps implement it, Google may ban them from PlayStore. Honestly don't know why Bitwarden is allowed to use it. 
But have you considered adding a plug-in that can only be downloaded via F-Droid Store or APK? This should work out with having a "Lite" Version on PlayStore and "Normal" on F-Droid.
Since Bitwarden is Open Source you might want to check out how Bitwarden is using Accessibility Service...

**Comment by J-Jamet** [comment]
It is not planned to use the accessibility service, which is not made for the autofill. It would require too much work for the benefit and the devices below Android 8 are fewer and fewer. In addition, as you point out, the store could refuse it, so need to create a suitable plugin import system. I created the Magikeyboard to overcome this problem.

**Comment by jwsp1** [comment]
I should have said that I'm on Android 9 (Pie). Auto-fill still not working. The keyboard works but is inconvenient IMO. But you did the best :) I understand that this is too much work; I'm just trying to figure out which password manager app I should use.
Hope the Chromium Bug gets fixed soon so I can use KeePassDX. Do you know where I can find the actual issue? Google didn't give me proper results or maybe I didn't see it...

**Comment by J-Jamet** [comment]
In this case it is a standard Autofill bug, you do not need the accessibility service. The autofill has been improved in version 2.5RC1, you should see the popups if the service is activated. If not, the problem is probably with the browser.
