### ISSUE TITLE
KeyStore issue?

### ISSUE THREAD

**Issue by ZJaume** [Kunzisoft/KeePassDX#52]
**Version:** 2.5.0.0beta6-libre
**OS:** LineageOS 14.1 (Android 7.1)
**Device:** Xiaomi Mi5

The app hangs and crashes when selecting the database. I think the last time used I deactivate the fingerprint unlocking for my database. Deleting the app data solved the problem.
[Here](https://pastebin.com/qZ5AhbDr) is the exception catched in logcat.

**Comment by J-Jamet** [comment]
Thx for the reply, very useful with all stacktrace! :) I'm going to capture the exception to avoid the crash, I'll better handle fingerprints errors, but I don't know exactly why it's happening .

**Comment by ZJaume** [comment]
I'm not sure if it is a problem with finguerprint, LOS id having problems with keystore, maybe that. Are you sure?

**Comment by J-Jamet** [comment]
I'm not sure at 100% but logs show me that the exception is thrown during the init of fingerprint. Fingerprint communicates with the keystore to manage the encrypt keys of each fingerprint store. Here the system throw an error and tell "Key permanently invalidated". Keepass DX tries again an init, so communicates with keystore to get the key, but the api already said the problem and stops the app (unfortunately with a crash). (it's my theory, but I'm tired, I'm going to bed! :D)

**Comment by ZJaume** [comment]
Today updated from F-Droid, it seems there is no crash after disabling fingerprint unlocking. Thank you!

**Comment by J-Jamet** [comment]
Happy to hear it ! :)
