### ISSUE TITLE
Editing imported kdbx database

### ISSUE THREAD

**Issue by akaMePs** [Kunzisoft/KeePassDX#522]
As the title suggest, maybe I am missing something, but I wanted to edit some of my entries of my imported database from Keepass on my PC and didn't find any way to do it. Only way to edit is by creating a new database, which seems counterintuitive, because I wanted to edit or add new entries from my imported database. 

Using v2.5RC1

Thank you

**Comment by akaMePs** [comment]
I opened the imported database using another file explorer action on my phone got rid of this issue. I used "Files" instead of "Select" when prompted to open the database using MiXplorer. When importing the database, using "Select" doesn't allow the entries to be edited, while using "Files" allow it.

**Comment by fookinhell** [comment]
I didn't get why my database (imported from nextcloud in mixplorer) wasn't saving, then I saw your issue and your solution, and it works! Thank you for this, it helped me!

**Comment by akaMePs** [comment]
@fookinhell glad I could help you out my friend! 👌
