### ISSUE TITLE
Auto key "Go" action only after password field entry has been filed

### ISSUE THREAD

**Issue by akaMePs** [Kunzisoft/KeePassDX#523]
**Is your feature request related to a problem? Please describe.**

• The auto key "Go" feature after the username field entry has been filed makes the webpage reload, thus canceling the action. 

**Describe the solution you'd like**

• The auto key "Go" feature in the Magikeyboard settings should have an option to work only after the password field entry has been filed, not the username field entry. 

Using v2.5RC1

**Comment by brgrvrm** [comment]
> • The auto key "Go" feature in the Magikeyboard settings should have an option to work only after the password field entry has been filed, not the username field entry.

IMHO, even better use a simulated "Tab" key to automatically jump to the next entry field of the login page (in most cases password entry).

**Comment by J-Jamet** [comment]
The Go button is supposed to adapt to the cursor position. If it is in an area that allows you to enter text after, it is automatically a tab, if it is the end of the form, it is a validation button. But obviously it only works if the form is well done. Which forms are problematic?

**Comment by J-Jamet** [comment]
I just retested, the effect of the Go button seems to have changed, it may have been since the transition to the new API.
