### ISSUE TITLE
Add Credit/Debit card credentials 

### ISSUE THREAD

**Issue by matesurano** [Kunzisoft/KeePassDX#525]
**Describe the solution you'd like**
It would be useful if credit/debit card credentials can be stored in keepass DX with a feature to autofill in required relevant fields. 

**Describe alternatives you've considered**
Many password managers have this feature. 

**Additional context**
App version: 2.5RC1 
Android version: 9 (pie)
Device: Samsung Galaxy s8.

**Comment by J-Jamet** [comment]
This is a difficult feature to implement because there are many different forms on different applications to save new data. But if you are good coder and good in form recognition you can make a pull request.

**Comment by matesurano** [comment]
Hahaha...i have zero knowledge of coding. No big deal if it can't be implemented, i was just asking because i thought atm/debit/credit card data are universal like 1.card number  2.valid upto date 3. name of the card holder and 4. cvv number(on back of the card). But it's ok....may be in future.  Thanks for the quick response.

**Comment by J-Jamet** [comment]
No problem, I keep the issue active until I have time to deal with it. ;)

**Comment by matesurano** [comment]
Nice of you. Thanks a lot. 🙏

**Comment by uduerholz** [comment]
I have started working on this feature. I hope you still accept pull requests for it.

**Comment by J-Jamet** [comment]
Yes of course, if the code is OK I encourage it! :)

**Comment by uduerholz** [comment]
I think the issue can be closed.
