### ISSUE TITLE
feature request: Autofill support work profile

### ISSUE THREAD

**Issue by ivysrono** [Kunzisoft/KeePassDX#526]
We install some apps in work profile by [oasisfeng/island](https://github.com/oasisfeng/island/releases), Keepass2Android support autofill them with [KP2A AutoFillPlugin](https://android.izzysoft.de/repo/apk/kp2a.plugin.AutoFill).
Could you support that?

**Comment by J-Jamet** [comment]
I do not know the application you are talking about and the request related to it.
Autofill is supported but not the Accessibility Service. https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#why-is-the-auto-fill-not-available-for-android-devices-before-android-80-api-level-26

**Comment by ivysrono** [comment]
I'm using Android10, autofill works fine in main profile.
[What is a work profile? - Android Enterprise Help](https://support.google.com/work/android/answer/6191949?hl=en)

**Comment by J-Jamet** [comment]
So what's the problem if it works fine? I do not understand the request.

**Comment by ivysrono** [comment]
It works fine in main profile, however not in work profile.
Any app could be autofilled in main profile could **not** be autofilled in work profile.

**Comment by J-Jamet** [comment]
KeePassDX uses the autofill service of your device, it is your device which takes care of managing the behavior of the autofill according to the profiles. I can't do anything from the KeePassDX code.

**Comment by ivysrono** [comment]
Thank you anyway.

**Comment by ivysrono** [comment]
As you have test https://github.com/oasisfeng/island , does KeePassDX support auto fill apps in island?

**Comment by J-Jamet** [comment]
No, an external app service is never activated (regardless of the application with autofill) in the island profile settings (always returns to none). I therefore recommend that you open an issue on this project to find out what is the reason.

**Comment by J-Jamet** [comment]
https://developer.android.com/reference/kotlin/android/content/pm/CrossProfileApps

**Comment by ivysrono** [comment]
@J-Jamet Would you support `CrossProfileApps` for Android 11+ ?
