### ISSUE TITLE
Sometimes app needs Autofill manual invoking. 

### ISSUE THREAD

**Issue by matesurano** [Kunzisoft/KeePassDX#527]
**Describe the bug**

After not using the app for sometimes,  say an hour,  it needs manual invoking for  autofill prompt like long pressing the entry fields or cleaning the app cache.

**Expected behavior**
Autofill prompt should be automatic as soon  as relevant entry fields are on screen. 

** Keepass Database **

 - Created with: Windows 10 after Merging/synchronizing 2 databases(one imported from desktop chrome csv file and another created in KeePassDX) in Windows KeePass 2.44

 - Version: 2.5RC1 
 - Location: local: interal Storage 
 - Size: 9kb
 - Contains attachment: No

**KeePassDX (please complete the following information):**

 - Version: 2.5RC1 
 - Build:  Free , Google play store 
 - Language: English 

**Android (please complete the following information):**

 - Device: GalaxyS8
 - Version: 9

**Additional context**

 - Browser for Autofill: firefox nightly, OH Browser,  and many others.
Note: Keepass dx is not optimized for battery saving.

**Comment by J-Jamet** [comment]
I cannot change this behavior. This comes from the device's autofill service.
What do you mean by "Keepass dx is not optimized for battery saving.". If you tell me where in the code, I will do the optimization but I noticed that it is simply the verification service of your OS that sees the foreground notification. So it's a false positive, tell me if I'm wrong.

**Comment by matesurano** [comment]
what i meant by "keepass dx is not optimized for battery saving"  is that the background service of keepass dx is not killed by my phone's OS system battery saver, which is good. i just mentioned it to clarify because android kills many apps in the background. And may be you are right, it may be android problem not keepass dx related. Actually I have no knowledge in coding etc. Thanks for the quick response.

**Comment by J-Jamet** [comment]
> keepass dx is not killed by my phone's OS system battery saver, which is good. i just mentioned it to clarify because android kills many apps in the background

Okay, I thought there was a problem there. Indeed, I open a foreground notification to keep the open database active.

Maybe I'm also wrong about the autofill, but I don't know of an option for that. It must be the autofill service which goes to sleep after a certain time and reselecting it manually wakes it up. I will tell you if I find something more in the doc.

**Comment by matesurano** [comment]
Sure thing. You are doing a great job 👍
