### ISSUE TITLE
Autofill doesn't work for in-app purchases

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#529]
When I do a purchase for my Google account in some app the OS asks me to confirm it and then shows me a dialog which shows my account e-mail and asks me to enter it's password. So this is a place where autofill icon must appear but it doesn't.

**KeePassDX (please complete the following information):**
 - Version: 2.5RC1

**Android (please complete the following information):**
 - Device: Xiaomi redmi note 8t
 - Version: MIUI 11, it's based on android 9
![IMG_20200419_201614](https://user-images.githubusercontent.com/744888/79695341-fb30f000-827e-11ea-89a1-e2fecd60aed0.jpg)

**Comment by J-Jamet** [comment]
Thanks for the feedback, I think the problem comes from the fact that there is only one password field and not an identifier field and a password field. The problem will be to debug this form,. :/

**Comment by J-Jamet** [comment]
Can you tell me if it's ok with the version 2.5RC2?

**Comment by zveber** [comment]
It still doesn't work.14:46, 1 мая 2020 г., "Jérémy JAMET" <notifications@github.com>:
Can you tell me if it's ok with the version 2.5RC2?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by zveber** [comment]
It still doesn't work.

**Comment by J-Jamet** [comment]
Okay, thanks for the feedback. I'm going to have to find a way to debug this form.

**Comment by zveber** [comment]
Keepass2android's autofill works with it. Maybe this information will help you somehow.

**Comment by J-Jamet** [comment]
Not really, I'm using a custom algorithm for form recognition, so I need to know what it's made of. If it manages the autofill hints tag, what is the internal name of the EditText field, this kind of element.

**Comment by J-Jamet** [comment]
I improved the algorithm and tested, it works in version 2.6
