### ISSUE TITLE
New icon pack

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#53]

**Comment by justintime4tea** [comment]
How does FontAwesome sound? 
(Like used in KeeWeb on Desktop/Electron/WebApp)

**Comment by justintime4tea** [comment]
I'm actually swapping out with FontAwesome icons now to see what it'd look like.

**Comment by justintime4tea** [comment]
Also adding xhdpi, xxhpdi and xxxhdpi...

**Comment by J-Jamet** [comment]
Thank you I didn't know KeeWeb. The purpose, in the long term, is to propose packs of icons that the user can select. ( And It is true that the vector icons are much better! ) ^^

**Comment by J-Jamet** [comment]
New pack available in version beta9
