### ISSUE TITLE
Autofill doesn't work for andOTP

### ISSUE THREAD

**Issue by niklas-fischer** [Kunzisoft/KeePassDX#530]
When I open andOTP, it no longer shows me the dialog to open Keepass. At this point, the autofill icon usually appears. This behavior was not present in the previous version

**KeePassDX (please complete the following information):**
 - Version: 2.5 RC1.31
 - Build: F-Droid
 - Language: German

**Android (please complete the following information):**
 - Device: OnePlus 7 Pro (LineageOS 17.1)
 - Version: 10.0

**Comment by yaomtc** [comment]
Is there a way I could disable the autofill from asking me about andOTP? I like to use a 4 digit PIN with andOTP. Every time I unlock andOTP, the screen is covered by a "save password to KeePassDX form autofilling?" prompt that I am forced to dismiss.

Sorry if this is off-topic, not sure of a better place for this.

**Comment by J-Jamet** [comment]
I close this issue, discussion here : https://github.com/Kunzisoft/KeePassDX/issues/553

**Comment by J-Jamet** [comment]
@yaomtc Click on "Save" and click on the crossed-out circle button, this will save a blocking configuration.
