### ISSUE TITLE
Unable to read KeeWeb database v4

### ISSUE THREAD

**Issue by Tutul-** [Kunzisoft/KeePassDX#533]
**Describe the bug**
When I try to load a database that is sync using owncloud, the app failed to open it.
The database use AES encryption algorithm with Argon2 for the key derivation (16 iterations, 16MB, 2 threads). The database is compressed using GZip (default with KeePass) and it's detected as kdbx4 by KeeWeb (the desktop app I use).

The error displayed in a red panel is about XML parsing error after successfully open the file (Error about an unexpected token `TEXT Đ[...]` maybe the 'Đ' ???).

**To Reproduce**
1. Create a database using KeeWeb or KeePass
2. After filling it a bit, sync it to a owncloud server
3. Sync it back to the android phone using the official owncloud app
4. Try to open the file

**Expected behavior**
The database completely loaded and ready to use

** Keepass Database **
 - Created with: KeePass (and imported into KeeWeb after but KeePass can still use it)
 - Version: KDBX4
 - Location: Remote file sync on the emulated sdcard using owncloud app
 - Size: 4KB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.5RC1
 - Build: Free (Libre)
 - Language: French

**Android (please complete the following information):**
 - Device: Moto G7 Plus
 - Version: LineageOS 17 (Android 10)

**Additional context**
None

**Comment by J-Jamet** [comment]
We must already verify where the problem comes from:
 - Can you copy the file locally to your phone to open it with an internal file manager.
- Can you try with other encryption algorithms and KDF

**Comment by axylophon** [comment]
I have also an XML parse error.

Occurs when using a keyfile. File created by KeeWeb. Keyfile and database are stored locally on the phone. When opening a database without a keyfile it is working. Storage permissons are ok.

**Comment by Tutul-** [comment]
I doest use a key file!
The simple KeePassDroid is able to open the database and all look fine but lack features KeePassDX provides.

**Comment by J-Jamet** [comment]
@Tutul- You are not answering the questions I asked earlier. Okay, it works with KeePassDroid, but that doesn't tell me where the problem is in KeePassDX.
@axylophon Your problem seems different, please open an other issue for your problem.

**Comment by Tutul-** [comment]
I'm trying with a local fine (the app sync it to be accessible offline) and with a copy send by USB, same error.

Because KeePassDroid/KeePass/KeeWeb works all the time but here it fail for me without key file, and fail for @axylophon with a key file, I assume there is an offset of some byte during the decryption procedure. I'll try with a different algorithm later.

I tested two other F-Droid app (without counting KeePassDroid) and get error too. TinyKeePass said that the database is broken or unsupported, AuthPass display an IOError (permission denied).

Sorry for the delay about the answer, I don't have access to my computer right now.

**Comment by Tutul-** [comment]
I tested with different database.
It seem to work with KDBX3 (AES key derivation algorithm).
By the way, it's KeeWeb that display KDBX3 (AES only) or KDBX4 (Argon2 or AES but the later doesn't work with KeePass).

**Comment by J-Jamet** [comment]
Okay, I will test by creating a database with KeeWeb to see if I can reproduce the problem. It will be easier to debug. It may be related to the argon2 parameters.

**Comment by Tutul-** [comment]
I tested with default and secure parameters, both failed on Android.

**Comment by J-Jamet** [comment]
Indeed, but what seems strange to me is that the database created with KeeWeb and simply saved with KeePass2 without changing any parameters works. There must be a formatting of badly created data that the other parsers ignore.

**Comment by axylophon** [comment]
Therefore I assume both issues are related and we don't need another issue?

**Comment by J-Jamet** [comment]
@axylophon We can stay on this ticket, it's just that it's not related to keyfiles

**Comment by J-Jamet** [comment]
I have just tested previous versions of KeePassDX and the problem comes from version 2.5.0.0beta25, I will look at the commits of this version to see which one adds the bug.

**Comment by Tutul-** [comment]
KeePassDroid can open the file without problems and I didn't see anything wrong inside it. So the "badly created data" hypothesis may be wrong. Probably some extra data ?

**Comment by Tutul-** [comment]
> I have just tested previous versions of KeePassDX and the problem comes from version 2.5.0.0beta25, I will look at the commits of this version to see which one adds the bug.

Is there any way I can help ?

**Comment by J-Jamet** [comment]
After several tests, I found the [commit](https://github.com/Kunzisoft/KeePassDX/commit/64ac3e8f320fc27007e328f6dbe0d03e1de4112d) that was causing the bug.
I will study it in more detail for the revert.
@Tutul- You already helped a lot, I hadn't even seen the bug before today.

**Comment by J-Jamet** [comment]
I just solved the bug, it seems that KeeWeb is adding empty data to the header, that's why I couldn't decipher it. I put back the old descriptor for the header and the problem is corrected. I'll check that it doesn't add a bug for attachments, but it should be fine.

**Comment by Tutul-** [comment]
I'm glad that I helped find that :-)

**Comment by axylophon** [comment]
Nice work!
When will you probably release it? My database is right now unusable.

**Comment by J-Jamet** [comment]
When I have finished the tasks of the current version. https://github.com/Kunzisoft/KeePassDX/projects/15

**Comment by Tutul-** [comment]
In the mean time, you said that a previous commit was the source of the problem. Can you give us the newest version you tried where the problems wasn't there ? So I can use the app waiting for the next release :-)
