### ISSUE TITLE
Show complete titles

### ISSUE THREAD

**Issue by alexanderadam** [Kunzisoft/KeePassDX#534]
**Describe the bug**

If you have entries with long titles it is not often possible to distinguish between them because long titles will just show  en ellipsis in the end.
This is true for the index-/search-/overview-view and even for the detail view.

**To Reproduce**
1. Have entries with long titles
2. Search for them. Good luck!

**Expected behavior**

Having the possibility to see complete titles.

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5RC1]
 - Build: libre
 - Language: English

**Comment by alexanderadam** [comment]
Not being able to distinguish between items is not a bug? :thinking:

**Comment by J-Jamet** [comment]
Yes, because it is possible to put the same name for several different notifications, it is not annoying from a functional point of view. So displaying two identical names is not a bug, it's only visualy annoying if the entry prefixes are long and identical in your case. This may be improved, of course, I await your comments on your ideas for improvement. In all cases, putting the tag "bug" in github does not solve your worries! :D

**Comment by alexanderadam** [comment]
> putting the tag "bug" in github does not solve your worries! :D

I know. I was just curious because imagine having three bank accounts and the bank UI wouldn't be able to show you properly from which bank account your transaction goes. This UI would be non-functional/ not working and therefore I would consider it to be buggy. But I absolutely agree that this semantic question won't solve this issue in any way. :wink: 

> I await your comments on your ideas for improvement.

I guess breaking lines would solve this in most (or even all) cases. But this probably has to be done on search suggestions, overview, detail view and, if possible, in the suggestions. So I guess it would be much to touch.

And a disadvantage might be, that the layout won't be as beautiful because the line height can differ.

**PS:** I probably wrote this on my last issues already but I want to make sure that you remember. I really, really appreciate your efforts and your work around KeePassDX. This is the application that I use every day and it is working great so far. :pray:

**Comment by J-Jamet** [comment]
I displayed the titles on 2 lines, that should be enough. The title in an entry view is still to be modified but I am dealing with this issue in #617
