### ISSUE TITLE
KeepassDX always fills username of an entry 

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#535]
I'm not sure if this a bug or not.

My database file has the default username.  As I understand it must be used when you create a new entry only. But if you try to do this:
1. Fill default username for database. 
2. Create a new entry just for storing some data.  So lt's username and password fields won't be filled. 
3. Save the entry. 
4. Open this entry for editing again  (imagine that you need to modify some data in it). 

The app will fill the username field (though you don't need it at all). 

**KeePassDX (please complete the following information):**
 - Version: 2.5rc1

**Comment by J-Jamet** [comment]
I do not understand the problem.
If you have entered a username to use by default, it is normal for it to be filled in by default when creating a new entry. This is the principle. If you do not want a default username, set the field in the setting empty.

**Comment by J-Jamet** [comment]
Ha yes, I understand what you mean, I just tested, it's a bug. Editing an existing entry without a user name should not be completed during a new edition.
