### ISSUE TITLE
Error message in password dialog is not hidden

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#536]
1. Open some entry for editing.
2. Open password generator.
3. Uncheck all types of used characters.
4. Tap on _Genetate password_. An etror message saying that you must choose at least one type will appear.
5.  Now choose a type and tap on " _Gnerate_ again . A password will be generated but the error message is still displayed.

App version is 2.5rc1.

**Comment by J-Jamet** [comment]
Thank you for the feedback. I will fix this bug for the next version.
