### ISSUE TITLE
not working under Samsung Dex

### ISSUE THREAD

**Issue by corvik** [Kunzisoft/KeePassDX#537]
**Describe the bug**
App is not posible run under samsung dex, its says not supported,  launch under tablet mode.
Even dex labs force resize not help

** Keepass Database **
 - Created with windows keepas 2
 - Version: kdbx4
 - Location:google drive
 - Size: 384kb

**KeePassDX (please complete the following information):**
 - Version: 2.5rc1
 - Build: free
 - Language: czech

**Android (please complete the following information):**
 - Device: samsung tab s6
 - Version: android 10
Dex ver 3.0.01.34

**Additional context**
iam not sure but i think its worked and stoped working, dunno when

**Comment by J-Jamet** [comment]
I can't test because I don't have a Samsung device with this feature. However, I added the prerequisites (linked to https://github.com/Kunzisoft/KeePassDX/issues/245). If someone would debug this feature, that would be nice.

**Comment by corvik** [comment]
maybe this is help, 
[https://developer.samsung.com/samsung-dex/modify-optimizing.html](https://developer.samsung.com/samsung-dex/modify-optimizing.html)

**Comment by J-Jamet** [comment]
I configure the emulator to test on my side. But I have all the prerequisites.

**Comment by J-Jamet** [comment]
I just tested, I have all the prerequisites and it works correctly on the emulator. So maybe the problem is with your device.
![2020-04-30 20-54-57](https://user-images.githubusercontent.com/19224038/80748656-8f277500-8b25-11ea-8f87-1fb81f495d9b.jpg)

**Comment by corvik** [comment]
Dunno what could be wrong.
Tried clear keepassdx cache,  data, reinstall and not helped.
Tried clear dex app cache and data...
![20200430_215321](https://user-images.githubusercontent.com/64494842/80754094-bafb2880-8b2e-11ea-888e-70732a068b5a.png)

**Comment by J-Jamet** [comment]
It may be a memory problem. I made optimizations and I changed libraries. Maybe it will improve compatibility.

**Comment by corvik** [comment]
RC2 still same

**Comment by corvik** [comment]
RC2 still not work.
Looks like its forced disbled. 
Tried start it over Dex MAX apk and still same too.
In tablet mode works like charm.
Tested old versions from  fdroid beta 30 and beta 28 without succes.

**Comment by corvik** [comment]
forced dex developer mode mentioned in #245  enable and disable force resize option and  appk now working in DEX! iam little mad but it works, thanks for help and sorry for  bothering.
