### ISSUE TITLE
Use custom attribute for remembering mobile app rather than URL field

### ISSUE THREAD

**Issue by sycosyth** [Kunzisoft/KeePassDX#542]
Allow custom attributes to be set manually/automatically with a "remember this", that would allow keepassdx to remember what android app an entry is linked to without over writing the URL field used by desktop keepass applications.

As an Example, keepass2android creates and uses a custom attribute "KP2A_URL_1" to store the android app the entry is linked to, not using the URL field that would break desktop authentication. 

It would be very useful to have something like this implemented.

**Comment by J-Jamet** [comment]
The functionality is already implemented with all custom fields. It is recommended to use the ApplicationId label. https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#auto-search
Linked to https://github.com/Kunzisoft/KeePassDX/issues/519
