### ISSUE TITLE
If autofill does not automatically find a match, allow for manual selection, and prompt to "remember this"

### ISSUE THREAD

**Issue by sycosyth** [Kunzisoft/KeePassDX#543]
If autofill does not find a match, and/or as another entry in the autofill menu, allow the user to navigate their database to select an entry manually and perhaps prompt to remember the selection. (would also be useful for the functionality of #542(allowing a custom attribute to remember mobile app instead of URL field).)

**Comment by J-Jamet** [comment]
Duplicate #435
