### ISSUE TITLE
Add ability to show hidden fields

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#545]
Any entry has protected fields (passwords or additional protected fields). It would be convenient to have ability to toggle their's visibility when an entry is in read mode.

**Comment by zveber** [comment]
Oh, sorry, I didn't notice that this feature is already implemented.

**Comment by Wilker-a** [comment]
i think this feature could use an improvement. it would be nice to be able to reveal individual fields instead of either all or none. i think the button to reveal all can stay too, though.
