### ISSUE TITLE
How to transfer key to USB drive?

### ISSUE THREAD

**Issue by KeePassScotland** [Kunzisoft/KeePassDX#547]
Hi, I have a question regarding how to use a keyfile from a USB drive.

My thinking is that it makes sense to secure the KeePass database with a password and keyfile and that it makes sense to store the keyfile on a USB drive.

Does this make sense?

... If so, my question is how do I get the keyfile onto the USB drive?

I have generated a key set using the OpenKeyChain Android app and I have a USB drive that can be mounted and read by my Android phone.

Unfortunately, I can't workout how to transfer the keyfile on to the USB drive? 

Any advise is appreciated.

I have tried to get advise from the OpenKeyChain community but have not had any luck.

Thanks

**Comment by J-Jamet** [comment]
Yes that makes sense.
I do not know OpenKeyChain but just copy the generated file to your USB drive and then open it with KeePassDX.
Note, a KeyFile can be any file, there is a hash made from this file to generate a key.

**Comment by J-Jamet** [comment]
Personally, I generated a random data file as a key file, it works very well.

**Comment by KeePassScotland** [comment]
Really, it can be any file! Okay, that makes things a lot easier. I thought it had to be a gpg crested key! Thanks

On 8 May 2020 19:53:11 BST, "Jérémy JAMET" <notifications@github.com> wrote:
>Yes that makes sense.
>I do not know OpenKeyChain but just copy the generated file to your USB
>drive and then open it with KeePassDX.
>Note, a KeyFile can be any file, there is a hash made from this file to
>generate a key.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kunzisoft/KeePassDX/issues/547#issuecomment-625964335

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KeePassScotland** [comment]
I suppose if it's the hash that's being used then it doesn't matter if its a random file or not, other than you want the file to be unique!

On 8 May 2020 19:55:24 BST, "Jérémy JAMET" <notifications@github.com> wrote:
>Personally, I generated a random data file as a key file, it works very
>well.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kunzisoft/KeePassDX/issues/547#issuecomment-625965266

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by J-Jamet** [comment]
> I suppose if it's the hash that's being used then it doesn't matter if its a random file or not, other than you want the file to be unique!

It's exactly that, the file just shouldn't be changed.
