### ISSUE TITLE
.CSV to .KDBX 

### ISSUE THREAD

**Issue by JavaCoder20** [Kunzisoft/KeePassDX#552]
Hi
I've written an article on how to convert .CSV file to .KDBX here: 
 https://telegra.ph/CSV-to-KDBX-05-07
maybe it can be added to the wiki ?

**Comment by erwincatt** [comment]
Or hard method: https://github.com/Kunzisoft/KeePassDX/issues/505#issuecomment-607368072

**Comment by JavaCoder20** [comment]
yeah i saw that, that's why i wrote this guide a little easier.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/Import-and-Export
