### ISSUE TITLE
Updating KeepassDX breaks auto locking of open db

### ISSUE THREAD

**Issue by frudolph77** [Kunzisoft/KeePassDX#555]
**Describe the bug**
I have updated KeePassDX from beta30 to RC1, a few days ago, afterwards I noticed that the auto locking of the DB isn't working any more. I remember that I faced the same issue when updating from beta29 to beta30.
To fix this issues I've to reinstall KeePassDX.

At least I installed RC2 from GitHub and did successful update to 2.5 stable today, without facing this issue. 

If you wish I could retry this steps with the F-Droid build.

**KeePassDX:**
 - Version: 2.5 beta30
 - Build: the one from F-Droid
 - Language: German

**Android:**
 - Device: Moto G5 Plus
 - Version: 8.1

**Comment by J-Jamet** [comment]
In the RC1 version, there were concerns related to the autolock, which I fixed in the RC2 version, so the concern is normally completely resolved. This came from a lock loop that was called in an activity. I close the issue unless you tell me that it is still present in version 2.5 stable.

**Comment by frudolph77** [comment]
I switched back to the libre build, to get the updates.
First I installed RC2, and test the db locking, which works fine. afterwards I updated to 2.5 and the db locking is still working. So everything is fine now.
Thanks.
