### ISSUE TITLE
QR scan for OTP

### ISSUE THREAD

**Issue by adlisval** [Kunzisoft/KeePassDX#556]
Hi, is there any plan to implement QR scanning for 2FA?

**Comment by Wilker-a** [comment]
sounds like something to be figured using intents and a free program called Binary Eye (if contributing to non copyleft projects isn't an issue, or if adding camera permissions to DX isn't a problem)

**Comment by cagdasb** [comment]
Application named "andOTP" is avaible on f-droid too, but it's not the problem. That application would be better if it supports barcode.

**Comment by AzureCerulean** [comment]
There is also ZXing [https://github.com/zxing/zxing]

zxing/zxing is licensed under the
Apache License 2.0

a share function from the app to KeePassDX would be fine by me or if KeePassDX could call ZXing... or if KeePassDX wanted to incorporate the code altogether.

**Comment by J-Jamet** [comment]
Ideally, I would liked not to directly integrate a library for reading the QR Code, but only calling up applications that are already installed. Unfortunately, there is no generic solution without Play Service to retrieve the value of a QR from another application. So we have to find a way to generalize the process.

**Comment by AzureCerulean** [comment]
https://github.com/zxing/zxing
ZXing ("zebra crossing") is an open-source, multi-format 1D/2D barcode
image processing library implemented in Java, with ports to other languages.

**Comment by flocke** [comment]
I think this could be handled by registering KeePass DX to handle `otpauth://` URLs. That is what's encoded in the QR codes, see here: https://github.com/google/google-authenticator/wiki/Key-Uri-Format

That way one could scan the code with any barcode reader app and the system would suggest KeePass DX as app to handle the scanned link.

**Comment by J-Jamet** [comment]
With next version 2.9.2, it will be possible to retrieve the shared link from a QR code reader. All you have to do is "Share" from your favorite barcode reader.

**Comment by pixeldoc2000** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/OTP#qr-code
