### ISSUE TITLE
Add history of added and removed entries

### ISSUE THREAD

**Issue by djduhds** [Kunzisoft/KeePassDX#557]
It can solve the problem of accidentally remivjng an entry by mustake, please consider adding this feature

**Comment by J-Jamet** [comment]
The demand is strange, I don't know what you mean.

> Add history of removed entries.

The Recycle Bin is there for that

> Add history of added entries.

There for me it is nonsense, how do you make a history of the entries that have just been added?

**Comment by J-Jamet** [comment]
I think you had this bug #559 , it will be solved for the next version.
