### ISSUE TITLE
Notes Titles Show As Random Strings/UUID? Titles Show As URL.

### ISSUE THREAD

**Issue by grravity** [Kunzisoft/KeePassDX#578]
**Describe the bug**
Exported my Bitwarden to KeepassXC on my desktop clients, they show up fine, but on KeepassDX, the titles for notes show up as long, multi-part strings of letters and numbers.

The other issue being, titles show up as URL's and I see no ability to change how this is viewed. Again, this issue does not occur on KeepassXC.

**Expected behavior**
Notes titles show properly, and Titles show as Titles not URL's. Maybe offer the option to change.

**Keepass Database**
 - Created with: KeepassXC 2.5.4, Arch Linux
 - Version: KDBX 4.0
 - Location: Local, Synced with Syncthing
 - Size: Idk.
 - Contains attachment: Idk.

**KeePassDX (please complete the following information):**
 - Version: 2.5
 - Build: libre
 - Language: English

**Android (please complete the following information):**
 - Device: LG-V405TA
 - Version: Android 10

**Comment by J-Jamet** [comment]
When the UUID is displayed, it means that the title or the URL cannot be retrieved from an entry. If there is no title but the URL is present, it is displayed.
It does not mean that these fields correspond to titles.
If you think the fields have been reversed, can you recreate a database without sensitive data that reproduces the problem and upload it. Thank you

**Comment by J-Jamet** [comment]
In the KeePass XML, to my knowledge, there is no title linked to a note, but only to an entry. If so, can you indicate the manual that indicates this data formatting?

**Comment by grravity** [comment]
>In the KeePass XML, to my knowledge, there is no title linked to a note, but only to an entry. If so, can you indicate the manual that indicates this data formatting?
On KeepassXC (Windows and Linux), I can very clearly see proper titles for notes on my database as I mentioned, same with the URL/Title issue, Titles show properly under the title field and URLs show properly under URLs.

On KeepassDX, the same database shows URL's as titles, and the Notes show up as what look to be UUID's (which they don't on KeepassXC).

Now I made a new KeepassXC DB file, and exported it and imported into KeepassDX and the issue is no longer present. It seems it is related to my Bitwarden export, BUT the test database and my Bitwarden Keepass DB entries are inputted the exact same way (unless I'm missing something, but visually they look exact). I ensured I set the proper fields when moving the file over to Keepass (Bitwarden Title > Keepass Title, Bitwarden URL > Keepass URL). 

Not entirely sure what's going on here. Any chance you can create a test Bitwarden and try exporting, then migrating to KeepassXC (adjusting the fields accordingly) then just exporting to KeepassDX? It's most likely something related to that migration.

**Comment by J-Jamet** [comment]
There may be differences in XML formatting or perhaps in the parser or even unsupported characters, I don't know. We have to search and doing it blind can be very long.

> Not entirely sure what's going on here. Any chance you can create a test Bitwarden and try exporting, then migrating to KeepassXC (adjusting the fields accordingly) then just exporting to KeepassDX? It's most likely something related to that migration.

I will not be able to reproduce it either if I do not know what are the elements that cause the problem.
You can try deleting items from your main database and repeat to see exactly where the problem is coming from.

**Comment by grravity** [comment]
Well, I went and made a new test Bitwarden, then migrated it into KeepassXC and imported into KeepassDX, and it was working. I am confused.
I just reimported my primary database, the SAME file into KeepassDX and it seems to be working now? I didn't even resave the file, import a new version or anything, I just removed the DB out of KeepassDX and readded the same file, in the same dir it already had and now everything is fine? 
Not sure what went wrong, but seems to be working now. Sorry for the bother.

**Comment by J-Jamet** [comment]
It's weird indeed. The main thing is that it works properly but I remain doubtful anyway.

**Comment by grravity** [comment]
https://send.firefox.com/download/095ccc45f0ba163f/#9W0PsKXVXHCH0c83gb6vJA
Here are the test files in case you wanted to play around and see, idk. One is the Bitwarden Export, and the other is after migrating into KeepassXC (the same way I did my primary DB)

The passwords on the databases are `Test12345`
The FirefoxSend link expires in 1 day.
