### ISSUE TITLE
Autocopy or totp popup 

### ISSUE THREAD

**Issue by matesurano** [Kunzisoft/KeePassDX#580]
**Is your feature request related to a problem? Please describe.**
No, not a problem but feature request . 

**Describe the solution you'd like**

Is it possible to autocopy and autofill the TOTP codes(just like Enpass)or give a popup notification with copy option also showing time countdown(just like  Dashlane).

**Describe alternatives you've considered**
Already mentioned above. 

**Additional context**
**Describe alternatives you've considered**
Already mentioned.

**Comment by J-Jamet** [comment]
An issue is already open for the autofill: https://github.com/Kunzisoft/KeePassDX/issues/553

The copy from a notification is already present, just activate:
`Settings -> Form Filling -> Clipboard notifications`
It is not necessary to add a counter linked to the token because it is automatically replaced in the clipboard when it expires.

**Comment by matesurano** [comment]
> The copy from a notification is already present, just activate:
> `Settings -> Form Filling -> Clipboard notifications`
Even after enabling this settings, i don't Get any notification for copying TOTP. Here's the Process i did...
I try to log into Google account with firefox browser , i get required Autofill prompts for username and password (KeePassDX fills them, no problem there)in the next window i need to fill the totp code, but i don't get any notification for that. Only ongoing notification is that keepass dx database is open. Another thing to notice is  that if open the Google account link from inside keepass dx,  i start getting all the notifications for username , password , totp. Strange! And btw i didn't enable Magikeyboard, don't like that option.

**Comment by J-Jamet** [comment]
The notification is displayed when you select an entry in the database. This is the normal workflow for copying data. Notifications cannot be linked directly to the autofill.

Here you are asking for a feature related to automatic filling, which is a different feature. For now, the autofill only manages the username and password.
The issue for this functionality already exists, please continue the discussion on the already existing issue for its implementation. #553 

> Another thing to notice is that if open the Google account link from inside keepass dx, i start getting all the notifications for username , password , BUT NOT TOTP. Strange! And btw i didn't enable Magikeyboard, don't like that option.

I just tested, if the OTP is correctly configured for the entry. The notification adds the token to the clipboard. If this is not the case for you, please open a new bug as precisely as possible.
