### ISSUE TITLE
Autofill fills in unwanted fields since version 2.6

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#582]
Since version 2.6, Autofill fills in unwanted fields, this is due to the update of the recognition algorithm. Masks will be added to the recovered fields to correct the problem.

**Comment by mamins1376** [comment]
Also as an example, this affects OpenConnect password fields too which are already filled by the app itself.

This causes really annoying suggestion popup which covers the connect button, and thus leads to accidentally opening the app when you don't need to, and also add the automatic biometric authentication to that.

![What a mess!](https://user-images.githubusercontent.com/10245985/84535698-d3d52d00-acdb-11ea-8845-35155ac91c8c.jpg)

**Comment by J-Jamet** [comment]
As it is a password field, it is normal for the autofill popup to appear.
In all cases, I add a blocklist to version 2.7, you will be able to prevent the autofill for a specific application.
