### ISSUE TITLE
TOTP can not be generated when OTP key ends with %3d

### ISSUE THREAD

**Issue by OLLI-S** [Kunzisoft/KeePassDX#585]
**Describe the bug**
In KeePassXC I added OTP keys for several websites.
Some of them have %3d at the end (several times, like %3d%3d%3d%3d).

KeePassXC and also KeePass2Android can generate the TOTP for these entries.
KeePassDX can not generate the TOTP.

**Expected behavior**
The TOTP should be generated for these entries (maybe you ignore the %3d)

**Keepass Database**
 - Created with: Windows KeePassXC - Version 2.5.4
 - Version: 2
 - Location: Local phone storage
 - Size: 2,21 MB (2.324.623 Bytes)
 - Contains attachment: Yes

**KeePassDX**
 - Version: 2.5
 - Build: Free
 - Language: German

**Android**
 - Device: Samsung Galaxy Note 8
 - Version: 9

**Comment by J-Jamet** [comment]
It is not a valid [ASCII character](https://www.w3schools.com/tags/ref_urlencode.ASP). It matches the `=`, and the `=` is used in the configuration of the [otpauth URL](https://github.com/google/google-authenticator/wiki/Key-Uri-Format).

I will improve the code to remove characters not supported for OTP. In any case, this character is not part of your secret key.

**Comment by J-Jamet** [comment]
Can you indicate the formatting of the OTP field that is problematic in your case? Without real secret key.

**Comment by OLLI-S** [comment]
I searched in KeePassXC for `attr:%3d` and found 4 entries containing "%3d" in the field "otp":

- Ashes of Creation
- Dropbox
- Epic Games
- Humble Bundle

I have to admit that I was using KeePass before I switched to KeePassXC and added most OTP keys in KeePass.
So It  could have been my fault (but I have no idea how this could have happened.

Here are two keys where I replaced real data with an "x" (except the "%3d"):
key=XXXXXXXXXXXXXXXXXXXXXXXXXX%3d%3d%3d%3d%3d%3d
key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%3d%3d%3d%3d

I really don't know how this happened...
