### ISSUE TITLE
Multiple applicationIds for a login

### ISSUE THREAD

**Issue by 0x006F** [Kunzisoft/KeePassDX#592]
**Is your feature request related to a problem? Please describe.**
We can add additional URL patterns to a web-login. But we can't add multiple `applicationId`s to a credential.

**Describe the solution you'd like**
If we could give a feature to add multiple `applicationId`s to a login, that'd be great. For the backward compatibility we could re-use the existing field and use a separator instead.

**Comment by J-Jamet** [comment]
Can you be more specific and indicate a use case. Because the search for webDomain and applicationId works the same way (normally). So I have trouble understanding the request.

**Comment by 0x006F** [comment]
Hey @J-Jamet ,
So, in KeepassXC, we've an option to add alternate we urls to a credentials, right?
For example:
For an entry, I can assign both `https://exampleA.com` and `https://exampleB.com` in it, and if I visit any one of the url, the credentials will pop up.

Just like that, do we have an option to add multiple `applicationId`s? Like `com.appA.org` and `com.appB.org` so that two different apps can access the same credentials?

**Comment by MoussaAdam** [comment]
that would be a nice feature, a use case would be multiple clients for the same service for example in Android you can use Github or gitTouch it make sense to fill the same entry credentials for these different application 

😶 I know having multiple apps serving the same purpose doesn't make much sense

**Comment by J-Jamet** [comment]
> Just like that, do we have an option to add multiple applicationIds? Like com.appA.org and com.appB.org so that two different apps can access the same credentials?

There is no real standard for that feature. Normally there is an applicationId per entry, so I recommend making a custom field "applicationId" but KeePassDX searches in all fields during a search. So you can put a new custom field with the name you want (ie: applicationId2) and put another applicationId in it, that's okay, the search will still be done on this field.

Otherwise you can create a new entry by making symbolic links to the different fields, using the field references. https://keepass.info/help/base/fieldrefs.html

**Comment by J-Jamet** [comment]
The feature is already implemented on a more general level, so I close this issue.

**Comment by 0x006F** [comment]
I understand how search works, but I was hoping to get it auto-suggested the credentials when a form is detected (_just like the existing functionality with `applicationId`_).

**Comment by J-Jamet** [comment]
Magikeyboard and Autofill features use the search. Have you tested? I did it earlier, it works well.
