### ISSUE TITLE
S/.FTP/s Support

### ISSUE THREAD

**Issue by kaaax0815** [Kunzisoft/KeePassDX#595]
**Is your feature request related to a problem? Please describe.**
I have my database and my key on different ftps servers because KeePass supports it natively, but android versions often not. Some have the support but the ui is not that greag

**Describe the solution you'd like**
Please add the option to select a database from a server

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/121

KeePassDX will remain a file editor and will not be a file manager. We must use a third-party file manager application that uses SFTP and integrates with KeePassDX.
I discuss with the creator of "Material Files" and "RCX", the compatibility with these file manager applications will be improved.

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

Please continue the discussion on the issue already opened.
