### ISSUE TITLE
输入界面有点问题

### ISSUE THREAD

**Issue by bigsuprise** [Kunzisoft/KeePassDX#60]
在任何界面新建输入密钥的时候，大概率会触及到返回键，造成无法新建的结果，基本是靠多次重复实验触及才能新建成功，应该是触摸区域的问题。希望可以在下一个版本修复。

**Comment by J-Jamet** [comment]
Sorry but I don't understand what you mean. The add button is a standard floating action button. If you accidentally hit the back button, it's not a design problem. If you are faced with the issue of action problem when the animation is disabled in developer settings, it's corrected in https://github.com/Kunzisoft/KeePassDX/issues/55.
Can you tell me more about the problem in English or French ? Thank you

**Comment by bigsuprise** [comment]
![](https://tecs.ml/image.php?di=RKSH)

as the picture shows , when i click the "添加条目" button there is a high probability that it will fall back to the initial interface. 
if you want more information i can send you a video

**Comment by J-Jamet** [comment]
The image has not been correctly uploaded. Yeah a video will be good. Can you also tell me your Android version and the KeePass DX version.
