### ISSUE TITLE
Softlock with biometric dialog and key file button

### ISSUE THREAD

**Issue by MaSven** [Kunzisoft/KeePassDX#602]
**Describe the bug**
After interaction with the app.It is no longer Possible, to enter the password the lockscreen. 

I tried to log in into an app through keepassdx. Android switched from the app I tried to log in, to keepassdx. I then accidentally clicked on the switch key file dialog. Now the file dialog opens. In the same time, the dialog for biometric login opened. Because of that I could not click on any file because the dialog for biometric log in, all clcks on the screen were blocked. I also could not close the biometric dialog, because the finger scan didn't happen. So I had to reboot. After the reboot. The on screen keyboad 
would not appear on the password dialog to unlock the phone. 

I also attached a logcat output of the boot. 
[log.txt](https://github.com/Kunzisoft/KeePassDX/files/4811369/log.txt)

**To Reproduce**
1. Try to log in into an App with Keepassdx. Keepassdx should be configured to unlock with biometric data
2. Android switches to Keepassdx
3. Click on the very first second on a file dialog
4. The filediaog and the biometric scan dialog should appear.
5. Reboot the Phone
6. on screen keyboard is missing to unlock the phone

**Expected behavior**
I would expect, that the file dialog closes the biometric unlock dialog. Of that the apps waits for the unlock to happen and does not take any inputs till then.

** Keepass Database **
 - Created with Keepassxc 2.5.4
 - Version: Current on Fdroid 2.7
 - Location: Nextcloud media folder
 - Size: 91,6 Kb
 - Contains attachment: No

**Android (please complete the following information):**
 - Device: Fairphone 3
 - Version: 

**Additional context**

**Comment by MaSven** [comment]
After unlocking the phone with an adb shell
```
adb shell
locksettings clear --old <old_password>
```
I think the failure was, that still the magickeyboard war select. Because of this, there was no real keyboard for the password prompt.

**Comment by J-Jamet** [comment]
Thanks for the feedback,
this must be a bug in the automatic opening option of biometric recognition.

> I would expect, that the file dialog closes the biometric unlock dialog. Of that the apps waits for the unlock to happen and does not take any inputs till then.

It should happen, the problem is that I don't manage the biometric prompt dialog, the system does it. And even if I send an opening stop command, this dialog opens anyway. It depends on the device, but the biometric prompt should have a cancel button. Which is the case, on my emulators.

I will try to reproduce the problem, but it will be difficult to debug. What I find odd is especially that it blocks the UI for you and that the keyboard does not appear at startup when it should.

If the Magikeyboard is selected, it should be open. When it is open on the lock, just keep pressing the keyboard swap button to choose another one.

I will do more tests.

**Comment by MaSven** [comment]
> It depends on the device, but the biometric prompt should have a cancel button. Which is the case, on my emulators.

It has but the abort button didn't work at that moment. It was like a deadlock. 

> If the Magikeyboard is selected, it should be open. When it is open on the lock, just keep pressing the keyboard swap button to choose another one.

I could not switch the keyboard because there was no keyboard at all. If you look at the log. There is an error, that the Diag_lib is failing because of error 13. This means I have no permission to open the keyboard i think.

**Comment by J-Jamet** [comment]
I found a simple solution to open the biometric prompt only if the right activity is displayed. It should work, you will give me a feedback with version 2.8.

**Comment by J-Jamet** [comment]
It's normally OK in version 2.8, tell me if it works for you?

**Comment by MaSven** [comment]
Sorry didn't get the message. It seems to work for me.
