### ISSUE TITLE
ClassCastException when trying to open database after Upgade to V2.7

### ISSUE THREAD

**Issue by pm-bernhard** [Kunzisoft/KeePassDX#603]
After Upgrading KeePassDX to version 2.7 I get the error:
"Could not load your database: java.lang.ClassCastException: com.kunzisoft.utils.UnsignedInt cannot be cast to Java.lang.Long"

I installed it from F-Droid on an Android 10 Device.

**Comment by J-Jamet** [comment]
Theoretically, this error should not happen because I never use Java.lang.Long.
I think it must happen on some devices because the toLong() method is not retrieved from the code but from the JDK (which should not happen).
Can you tell me if it works with all the databases you have? Old and newly created?

I think I will not be able to reproduce the problem on my devices but I can modify the name of the method to exclude cases of unwanted inheritance.

**Comment by pm-bernhard** [comment]
I continued testing:
**works:**

- same device, when creating a new database with same password
- copy database to desktop (Linux) and open in KeePassXC 2.5.4

**works not:**

- copy database to other Android 10 Phone open in KeePassDX 2.6

I forgot to mention that i upgraded from Android 9 to Android 10 on the problematic device so it seems a problem unrelated to the KeePassDX version and more related to databases which are created on Android 9 when opening on Android 10

**Comment by J-Jamet** [comment]
[KeePassDX_2.8_Build_2020_07_20_10_59.zip](https://github.com/Kunzisoft/KeePassDX/files/4863049/KeePassDX_2.8_Build_2020_07_20_10_59.zip)

Can you test this build?

**Comment by pm-bernhard** [comment]
> [KeePassDX_2.8_Build_2020_07_20_10_59.zip](https://github.com/Kunzisoft/KeePassDX/files/4863049/KeePassDX_2.8_Build_2020_07_20_10_59.zip)
> 
> Can you test this build?

Sorry, same behaviour. I uninstalled my old KeePassDX version and installed the 2.8 version to get sure to test the correct one.
An other observation: The error-message appears also if i enter an invalid password

**Comment by J-Jamet** [comment]
Can you provide me a test database that does not work with KeePassDX 2.7 without sensitive data.

**Comment by pm-bernhard** [comment]
I managed to create a database with the same problem again (Password is 12345678)
It was created with KeePassDX 2.5.0.0beta11 on Android 8 (API-26) (Genymotion-Emulator)
It fails to open on Android 10 with KeePassDX_2.8
[keepass.kdbx.zip](https://github.com/Kunzisoft/KeePassDX/files/4871454/keepass.kdbx.zip)

**Comment by J-Jamet** [comment]
Sorry, but I can't reproduce the problem with my Android 10 phone. The database you uploaded works without problems with KeePassDX 2.7 and 2.8_Build_2020_07_20_10_59.
So I think there was a problem with your update Android 9 -> Android 10. If it's something else, I don't see.

**Comment by pm-bernhard** [comment]
I can confirm it works on a other Android 10 Phone (Samsung Galaxy S9).
It's not related to an Android Upgrade because it happens on second phone on which i did a clean install of Lineage-17.1 (Build 20200611 Galaxy S4 https://wiki.lineageos.org/devices/jfltexx/).
What both problematic devices have in common is, that they have an 32Bit-Arm Processor. 
I assume Android 10 on 32Bit-ARM is a rarely tested these days.

Do have the ability to test on 32Bit?

I discovered a workaround for my problem in the meantime: Edit&Save the Database with an Non-Android-KeePass version (KeePassXC in my case). So maybe a workaround for other users would be to catch the exception and point it to specific page of the Wiki.

**Comment by J-Jamet** [comment]
Tested your database with:

- Galaxy S2 i9100 - ARM - Android 7.1.2 - KeePassDX 2.8_Last build  -> OK
- Galaxy S1 i9000 - ARM - Android 4.4.4 - KeePassDX 2.8_Last build -> OK
- One Plus One - ARM - Android 9 - KeePassDX 2.7 & 2.8_Last build -> OK

I cannot however test Android 10 on ARM yet but it's not the architecture involved because it works on all my old devices.

Maybe specific Lineage version not working?

**Comment by pm-bernhard** [comment]
After testing again, only one device left on which i can reproduce the behaviour with the corrupt database.
But for this device i have a working workaround.
Thank you very much for your time investigating and supporting me here, i think we should close this issue and blame one weird piece of hardware for not working as we expect :)
