### ISSUE TITLE
TOTP period can not large than 60s

### ISSUE THREAD

**Issue by stscor** [Kunzisoft/KeePassDX#604]
TOTP period can not be set larger than 60s ,like 120s, on the latest version, or it will not work. TotpTray field "TOTP Settings: 120;6" as the same.

**Comment by J-Jamet** [comment]
Indeed, this is a limitation put in place to prevent bugs. I didn't think there were higher TOTP periods. Can you tell me which service you want to use a 120 second TOTP for?

**Comment by stscor** [comment]
Yes, my company's internal OA use 120s.

**Comment by J-Jamet** [comment]
OK, I'm going to change the maximum to 900s is it OK?

**Comment by stscor** [comment]
That's enough.
