### ISSUE TITLE
Question Regarding autofill blocklist

### ISSUE THREAD

**Issue by Cos-mo** [Kunzisoft/KeePassDX#606]
I need some explanation regarding autofill.

I use KPDX 2.7. Browser Firefox (but should not be relevant here)

In the wiki it says below the heading "Blocklist", that I have to click at first the autofill popup (understood so far) and the blocking button. But I cannot see a blocking button. I see the matching entry in the popup and if I tap it the credential get filled into the boxes. I understand that I can create a blocking entry in the settings, but this is obviously more circumstantial.

So What I am doing wrong?

Another question:
If I want to block an app I have to enter the applicationID. But where shall I find it?. To my understanding I can do autofill with apps only after giving the ID into the URL field of the database entry. But how am I supposed to enter it, if I cannot find it? The description in the wiki does not help.
Furthermore I do not understand, why an app should be set into the blocklist at all. Without the ID there is is no autofill for apps and so there should be no need for blocking.

So again: Where is my mistake in understanding.

Regards

**Comment by J-Jamet** [comment]
> In the wiki it says below the heading "Blocklist", that I have to click at first the autofill popup (understood so far) and the blocking button. But I cannot see a blocking button. I see the matching entry in the popup and if I tap it the credential get filled into the boxes. I understand that I can create a blocking entry in the settings, but this is obviously more circumstantial.
So What I am doing wrong?

In this case, the automatic search recognizes entries in the open database. It is a feature that I have just implemented so the workflow is not perfect.

1. You simply close the database before use the autofill and press the block button
2. Or enter the applicationId or webDomain manually.

> If I want to block an app I have to enter the applicationID. But where shall I find it?. 

The applicationId or the webDomain is indicated in white on a green background in the majority of Autofill popups and in the selection mode bar. (ie: with Firefox app URL https://github.com -> _WebDomain_ is `gitlab.com`)

> To my understanding I can do autofill with apps only after giving the ID into the URL field of the database entry.

Not necessarily, you can use the autofill without entering the applicationId or the webDomain by selecting manually the appropriate entry for the autofill. Entered an applicationId or a webDomain allows an automatic search to go faster in the selection.

> But how am I supposed to enter it, if I cannot find it? The description in the wiki does not help.

See the answer above

> Furthermore I do not understand, why an app should be set into the blocklist at all.

The block list is to prevent the autofill popup from appearing on a form you don't want

> Without the ID there is is no autofill for apps and so there should be no need for blocking.

There is no need to have the applicationId to display the popup requesting the autofill. The autofill popup appears when the form is recognized by the recognition algorithm

**Comment by Cos-mo** [comment]
Thanks for answering.

Still there are things not clear to me.

I ensured that the KPDX database is closed.
Next I entered a resource, in this case github. I get the quite normal autofill popup, as been shown here: https://github.com/Kunzisoft/KeePassDX/issues/583. I do not see any block button. Regardless where I click - in the upper line with green background or in the second line with the white background - I get the KPDX page to open my database, just as usual. I checked the autofill settings and there is no ID to be seen.

So I am still in need of some help. Either I do understand wrongly or I do a mistake.

BTW: I think you did a typo, when you wrote gitlab.com for github.com. I think it should be gitlab or github in both places, or am I again on a wrong track?

**Comment by J-Jamet** [comment]
> Next I entered a resource, in this case github. I get the quite normal autofill popup, as been shown here: #583. I do not see any block button. Regardless where I click - in the upper line with green background or in the second line with the white background - I get the KPDX page to open my database, just as usual.

It's normal

![Screenshot from 2020-06-25 13-27-22](https://user-images.githubusercontent.com/19224038/85712396-95327000-b6e8-11ea-903a-5a2298b1595b.jpg)

> I checked the autofill settings and there is no ID to be seen.

You did not press the lock button to the right of the selection mode bar.

![Screenshot from 2020-06-25 13-27-37](https://user-images.githubusercontent.com/19224038/85712629-cb6fef80-b6e8-11ea-8480-61096e696645.jpg)

> BTW: I think you did a typo, when you wrote gitlab.com for github.com. I think it should be gitlab or github in both places, or am I again on a wrong track?

Yes it's a mistake

**Comment by J-Jamet** [comment]
I just updated the wiki, I close the ticket.

**Comment by Cos-mo** [comment]
Thanks for updating the wiki. Finally I was able to make use of the feature.

But with this result I found a visual glitch. This glitch was partially responsible for my inability to follow after the first reply. The problem was, that I could not see the block button and this was, because I could not see the selection mode bar. Only the last picture in the updated wiki did lead me to the right track.

The cause for the problem is my setting to automatically showing the fingerprint sensor, if the database is locked. Out of this reason I saw, when I came to the KPDX screen, this sensor. The sensor looks, as if it is placed in a popup and this popup makes all background of the screen darker, nearly black. So I cannot see (with my old eyes), what is shown there. Only after tapping on "cancel" on the fingerprint popup I saw the selection mode bar and the block button.

As the fingerprint sensor only uses the lower part of the screen and the bar is near the top, you can perhaps change the view and remove the visual glitch.

**Comment by J-Jamet** [comment]
> As the fingerprint sensor only uses the lower part of the screen and the bar is near the top, you can perhaps change the view and remove the visual glitch.

No, because it is not me who manages this view.

**Comment by Cos-mo** [comment]
I feared this.

But I recommend to add a note in the wiki to close the fingerprint popup, if it should open automatically.

**Comment by J-Jamet** [comment]
Done
