### ISSUE TITLE
A kdbx file cannot be opened without a password

### ISSUE THREAD

**Issue by abremora** [Kunzisoft/KeePassDX#607]
**Describe the bug**
A kdbx file without a password cannot be opened. Open button is disabled. When I check the password field checkbox, button is active but an error message appears after clicking the open button. 

**To Reproduce**
1. Create a DB without a password. Ignore the warning. 
2. Lock the db
3. Try to open the db. Even if you check the password field checkbox, DB cannot be opened. An error messages appears.

**Expected behavior**
DB can be opened with the app. A link to the DB should be available in the start page. 

** Keepass Database **
 - Created with: Android KeePassDX
 - Version: 2.7
 - Location: deive
 - Size: 1
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 2.7
 - Build: free
 - Language: German

**Android (please complete the following information):**
 - Device: Honor
 - Version: 10

**Comment by J-Jamet** [comment]
This is not a bug. An empty password is different from no password. Simply activate the setting "Setting -> App settings -> Allow no master key"
