### ISSUE TITLE
Open apps in KeepassDX, quick launch every apps

### ISSUE THREAD

**Issue by Chilled-ops** [Kunzisoft/KeePassDX#609]
Because it can show a app list in KeepassDX, just click them to open apps, and putting bookmarks URL in KeepassDX. KeepasdDX can open the bookmarks and apps also.

I have put all bookmark URL in KeepassDX to manage!

**Comment by J-Jamet** [comment]
Done in version 2.9, it's possible to open external app link from KeePassDX.
