### ISSUE TITLE
Quickly automatical adding the account of the new app

### ISSUE THREAD

**Issue by Chilled-ops** [Kunzisoft/KeePassDX#610]
When I installed Silence app in mobile, the keepassDX cannot automatically add org.smssecure.smssecure of Silence app in KeepassDX, I just remembered writen the long letter org.smssecure.smssecure to add the KeepassDX account.

**Comment by J-Jamet** [comment]
Adding an entry when installing an application is not a good workflow in my opinion.
It makes more sense to add an entry when doing an autofill or when using the browser "share". #435 #524
