### ISSUE TITLE
Question: Subdomain search

### ISSUE THREAD

**Issue by Cos-mo** [Kunzisoft/KeePassDX#614]
KPDX 2.7

I cannot find out, what in the search section of the app settings the subdomain search option is meant to do.

I have in a fresh new test database 3 entries, named one, two, three. For better identification all have a username with the same content as the entry name (one, two, three). Than I added a fictional URL. For one. one.com, for two one.com/eleven, for three one.com/twelve. If I now enter `one` as search expression I get always all 3 entries as result. I thought with the subdomain option set to on I would only get entry one as result, but that is obviously not the idea behind that option.

So I would like to learn, what the purpose of this option really is.

**Comment by J-Jamet** [comment]
It's linked to #584 
An internet domain has a name and an extension (in most cases), when a subdomain is added, it can be used to make another website. (ie: *Main domain* -> `sample.com` | *subdomains* -> `www.sample.com` ; `buy.sample.com ` ; ...)
In the code, only the last two elements of the domain (separated by a dot) are contabilised to define the main domain.

What you're talking about (with `one.com/eleven`) is a page, file or folder `eleven`  in a specific domain `one.com`.

**Comment by Cos-mo** [comment]
Thank you for clearing this. I knew, that I was on the wrong track, but I did not find the right track.

Nevertheless my main question remains.

I have now created 4 entries:
one: one.com
two: www.one.com
three: buy.one.com
four: buy.two.com

Whatever I enter as search term (one, www, buy), I always get the same result, regardless of the setting for subdomain search.

@J-Jamet 
Can you please rephrase this:

> In the code, only the last two elements of the domain (separated by a dot) are contabilised to define the main domain.

I have no idea, what "contabilised" might mean. I used Google translator, which asked me, if I mean "contabilize" and if I confirm, than it tells me, that this is a Romanian (no English) word. If I translate it to German and retranslate to English I get "accounted for". I don't know, if this is, what you mean, but more importantly I cannot detect the sense of the sentence in this context.

**Comment by J-Jamet** [comment]
Yes it's "contabilize". As I said in another issue, the search parameters are active only if you close and reopen a database. I can change this behavior, but it will be at the same time as the creation of the search parameters.

**Comment by Cos-mo** [comment]
Thanks so far, but I am still unable to understand the said sentence.

Also it doesn't help me to understand the identical results in my test as described in my previous comment. I expect different results depending from the subdomain search setting. And of course, if I perform a search inside of the KP database, I must have it open; with a closed database there is no possibility to search.

**Comment by J-Jamet** [comment]
The search for webdomains only concerns searches carried out on this parameter.
For the moment in the application, the only way to do such a search is to use the automatic search of the autofill or the share of a browser.
Manual search is much more lax.
