### ISSUE TITLE
More comfortable settings for the password generator

### ISSUE THREAD

**Issue by Cos-mo** [Kunzisoft/KeePassDX#618]
KPDX 2.7

If you compare the password generator settings in the general app settings and in the edit display for an database entry then you see, that the settings in the general app settings have 2 disadvantages:

1. In the general settings you can change the password length only by moving the slider. In the edit mode for an entry there is additionally the possibility to enter the wanted length by digits. Setting the slider to the right position can be a cumbersome method. So adding the digit method also to the general settings would be a fine enhancement.

2. In the edit mode the password generator dialog shows behind the names of the choices additional the respective chars, e. g. A-Z for upper letters. Especially for special signs and for enhanced ASCII this is extremely helpful to see, which chars get actually used. In the general settings for the same feature those chars do not get displayed. This is a pity and I do not see a valid reason for that. Please add it to the general settings.

**Comment by J-Jamet** [comment]
5bf998468a1bd25c0f9e1298856492581064c7ff
