### ISSUE TITLE
How to use AutoFill?

### ISSUE THREAD

**Issue by markcs** [Kunzisoft/KeePassDX#62]
I've enabled the option to set KeePassDX as the default AutoFill service application.

When I start an app that requires username/password I get the option for AutoFIll, but I can't get the fields filled in unless I copy/paste them into the app.  Shouldn't KeePassDX automatically fill in the user/pass fields without my input?

Also, for a webpage that requires login, I can not get the AutoFill at all.

Advice appreciated!  Thanks

**Comment by J-Jamet** [comment]
For the moment, Autofill works under certain conditions. The user must select the entry to fill username and password in field explicitly defined with android:autofillHints or if contains keywords (here username and password).
Copy/Paste is not the same feature of the app, when the app is started in Autofill mode (after a click on "Sign in with KeePass DX"), each entry becomes a callback function who returns username and password, so we can't do a copy in this mode.

It would be nice to improve the introspection of the views of forms to detect more finely the fields and to improve the system of recovery by research (which I have to do with a content provider https://github.com/Kunzisoft/KeePassDX/issues/26) but it is an enormous amount of work and I must refactor all the old code which can take time.

For my part, my phone is still in marshmallow version so I can only test this feature on emulator. If charitable souls want to help, it would be great! :p

**Comment by TheQwertiest** [comment]
> each entry becomes a callback function who returns username and password

It seems that this only works if the entry selected from the 'main' view, i.e. entries retain the normal 'non-callback' behaviour if clicked from 'search' view.

**Comment by J-Jamet** [comment]
Yeah, I would make a patch if the development is not too long before refactoring the search methods and implementing the Content Provider.

**Comment by J-Jamet** [comment]
I opened a [wiki page](https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill) for autofill (it will be updated later), other issues are open on the subject, I close this ticket.
