### ISSUE TITLE
Simplify text for Magikeyboard Settings > Keyboard change

### ISSUE THREAD

**Issue by chandradeepdey** [Kunzisoft/KeePassDX#624]
I could not decipher what the texts in the new Keyboard change section mean. Especially the first one - "Automatically back to the previous keyboard if the database credentials screen is shown"

**Comment by J-Jamet** [comment]
It means that if your keyboard was the Magikeyboard before displaying the screen to enter the main database password, it will be changed automatically by the keyboard previously selected.
It allows you to return to a standard selection keyboard to type your password.

What sentence do you propose to replace it?

**Comment by chandradeepdey** [comment]
Oh now i get it. I think it should have been "when" or "on" instead of "if". Here are my proposals anyway -

|Previous|New|
|-|-|
|Keyboard change|Auto-change from MagiKeyboard|
|Previous keyboard during database credentials|On the database credentials screen|
|Automatically back to the previous keyboard if the database credentials screen is shown|Switch back to the previous keyboard on the database credentials screen|
|Previous keyboard after form filling|After "Auto key action" is executed|
|Automatically back to the previous keyboard if the form is filling and Go key action is auto activated|Switch back to the previous keyboard after "Auto key action" (see above) is executed|

**Comment by J-Jamet** [comment]
I will add options in the future that may not be automatic.

Maybe:

|Previous|New|
|-|-|
|Keyboard change|Switch MagiKeyboard|
|Previous keyboard during database credentials|Database credentials screen|
|Automatically back to the previous keyboard if the database credentials screen is shown|Switch back to the previous keyboard on the database credentials screen|
|Previous keyboard after form filling|Auto key action|
|Automatically back to the previous keyboard if the form is filling and Go key action is auto activated|Switch back to the previous keyboard after execution of "Auto key action"|

**Comment by chandradeepdey** [comment]
Cool :)
