### ISSUE TITLE
AutoFill return view isn't displayed in 2.5.0.0beta7

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#63]
Due to https://github.com/Kunzisoft/KeePassDX/commit/bd3e5c6917f99ac1008d71c462b817899d1465d8

GOOD TO KNOW : Views for Autofill do not contains AppCompat view and attr attributes! :/

**Comment by justintime4tea** [comment]
Should we use the AppCompat views when they are not Auto fill fields? I think I might need to double check what views I have that can be AppCompat. This makes it compatible on older Android versions, yes?
