### ISSUE TITLE
Feature request: Adding SharePoint integration.

### ISSUE THREAD

**Issue by CaptainPi-PiLabs** [Kunzisoft/KeePassDX#637]
Currently I can't add our organisations KeePass file into the app. I have go into SharePoint to the file directory and open it from there. Would be super useful if it could be added in like how it is done with OneDrive or Google Drive. Loving this app otherwise! Super useful.

**Comment by J-Jamet** [comment]
Thanks for the feedback, but KeePassDX is not responsible for these integrations. This is the job of the file manager, here SharePoint. OneDrive & GoogleDrive take care of the file integration with the system and the recognition of mime types.
You should ask the developers of SharePoint app to integrate your request.
