### ISSUE TITLE
How many versions are avilable ?

### ISSUE THREAD

**Issue by Pranab009** [Kunzisoft/KeePassDX#639]
Hello, developer sir,
How much versions are available?
Make just one version for every platforms.
Like, Simple mobile tools it's fdroid & playstore versions are same.
Not only simple mobile tool but also many apps like, omni notes, alarmio, lighting browser, amaze files, fairemail, music player go & many more...
It is too confusing...
If i download from playstore & fdroid then 2 separate apps are Installed...

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-not-give-direct-access-to-alternative-themes
