### ISSUE TITLE
Add colors for Entry Attributes

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#64]
- [x] Add Foreground Color
- [x] Add Background Color

**Comment by gautierlabarre** [comment]
Hello, 
While I understand this implementation, I think it would be nice to deactivate this in the appearance setting.
The background color makes the second line unreadable. I have to focus to read the username. KeepassDX is really beautiful and all thoses color are killing it (IMHO)

Maybe it would be best to change the background with a simple color on the left (like a left border), or to color the icon ?

Tell me if you prefer I open a new issue.

**Comment by J-Jamet** [comment]
I thought about it, I made several tests on my side by putting just a circular colored background behind the icon, but it has problems for icons that are not unicolor.By simply putting colored lines, it is not visible enough.
And finally the current implementation is the way KeePass and KeePassXC do it, so it's the most suitable. You just have to choose colors that match well together or just don't use them.

**Comment by gautierlabarre** [comment]
Thank you for the quick response.
I understand, how about an option to hide colors then ? That way I can keep them on Keeweb and still have a "clean" UI on Keepass DX ?

**Comment by J-Jamet** [comment]
In each entry, select the color icons and click on the "enable" button to turn it off.

**Comment by gautierlabarre** [comment]
Is there a way to disable it for all entries ? I have like 300 passwords, it'll take me forever. 

Well, I suppose, if I'm the only one feeling that way towards background color line, it's my problem.

Thank you, I'll do that, a few password everyday.

**Comment by J-Jamet** [comment]
Yes, there is a way. If it had been for me, I would have exported in XML and deleted with a handmade script the nodes that correspond to the colors and reimported from the XML.

**Comment by J-Jamet** [comment]
I just checked and KeeWeb seems to use the background color of each entry as the color to tint the icons. This is not very logical, they should have used the foreground color at worst.

**Comment by gautierlabarre** [comment]
You're right, the issue is actually with keeWeb (I'll create an issue).

KeeWeb changes the background color by default (I agree with you, it should be foreground). 
But if I change on KeepassDX to only set the foreground, it also changes the Keeweb color. So KeeWeb actually sets the color depending first on background color, and if none are found, on foreground.

Thank you for your time. I can make this work now :) (I still think a general option to hide color would be beneficial 😛).
