### ISSUE TITLE
Sync conflicts / data loss when cloud is used

### ISSUE THREAD

**Issue by archont00** [Kunzisoft/KeePassDX#650]
**Is your feature request related to a problem? Please describe.**
When using KeePassDX with Nextcloud (NC) storage provider on Android, it may happen that the user looses data.

E.g. in this scenario:
* The phone is offline, KeePass.dbx is synced by NC and this file is open in KeePassDX.
* Add a new item TestDX to the database and save it. NC will try to upload the changed file, but it will fail. However, it will be stored locally for a later upload when connectivity comes back.
* On your other device (e.g. desktop PC with Nextcloud), open the same database and add a new item TestPC. Save the file and let NC sync.
* On the phone, enable the connectivity again. NC will try to re-upload KeePass.dbx and will succeed -> however, it will overwrite the version from your PC!

This may or may not be a bug in NC. Alternative outcome would be a file conflict and a duplicated file, which is a problem anyway - the user will have to try to merge the two database files.

**Describe the solution you'd like**
* KeePass could check if NC can upload changed file and if not, it would keep the changed database file only in its own cache (temporary storage) rather then updating local version in NC.
* When connectivity comes back and NC can check the server version (and possibly sync it to the phone), then KeePassDX would merge the two databases and save it to NC eventually.

**Describe alternatives you've considered**
If the above is not possible, is there some other way how to deal with multiple file versions?

E.g.
* KeePass2Android connects to WebDav NC server itself and always checks if there is a new version before saving changes (it can also merge two db files automatically).
* KeePassXC (desktop app) can watch for changes in the underlying file (Nextcloud synced file storage) and automatically merge any changes if NC downloads a newer file.
* This reasonably minimises the odds of data loss or file duplicates after sync conflicts.

**Comment by Karreg** [comment]
The same issue exists with Google Drive, with the same steps (however, going offline is not required... just changing on PC, then on mobile to overwrite the file instead of syncing).

[This page](https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#compatibility) shoud be updated to make sure that this is published to avoid user data loss.

**Comment by J-Jamet** [comment]
This issue is generalized in issue #840, I'm closing this one.
