### ISSUE TITLE
Plugin Data KeePassXC-Browser Settings are being deleted

### ISSUE THREAD

**Issue by axel-dd** [Kunzisoft/KeePassDX#651]
At the moment I use KeePassDX in read-only mode. Because KeePassDX removes the Plugin Data for KeePassXC-Browser Settings for all entries. It's so annoying. Normally KeePassXC asks only once if the Browser plugin can get access to the password of the website and stores the decision from the user. This plugin data is deleted by KeePassDX for all entries. Would it be possible to leave the plugin data untouched?

![Screenshot_20200803_214512](https://user-images.githubusercontent.com/6698567/89220907-ac5f5a00-d5d2-11ea-9dd7-c5a5b29c39ec.png)

**To Reproduce**
1. Create DB in KeePassXC
2. Create website entry
3. Install the KeePassXC Browser Plugin
4. Use the KeePassXC Browser Plugin to autofill website with the created website entry
5. On First access KeePassXC asks if the plugin can get access to the website password
6. Click Yes and save the anwser for the next time
7. Save and close the DB
8. Open DB in KeePassDX
9. Save DB in KeePassDX
10. Open DB in KeePassXC
11. Use the KeePassXC Browser Plugin to autofill website with the created website entry
12. KeePassXC asks again because ALL KeePassXC-Browser Settings are removed from the all entries.

**Keepass Database**
 - Created with: KeePassXC
 - Version: KDBX4.0
 - Location: local
 - Size: 250 KB
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 2.8.1
 - Build: Pro
 - Language: English

**Android:**
 - Device: MI 9
 - Version: 10 / MIUI 12.0.1

**Comment by J-Jamet** [comment]
I have never used the plugin, so I have to look at the internal workings of it to find out how the data is stored in the database.
If you have the documentation and code link that explains how data is stored from the plugin, that would be a big help.

**Comment by axel-dd** [comment]
maybe this makes it easier to get started...

https://github.com/keepassxreboot/keepassxc/blob/develop/src/browser/BrowserService.cpp#L468
https://github.com/keepassxreboot/keepassxc/blob/develop/src/browser/BrowserEntryConfig.cpp#L83
https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp#L224

**Comment by J-Jamet** [comment]
It is possible that an entry modification will delete the customized data. I have not checked this point, I am making a note for the next version.
Tell me anyway if it works for you on the whole database.

**Comment by J-Jamet** [comment]
OK, I checked, didn't notice any underlying bugs.

**Comment by axel-dd** [comment]
Hey @J-Jamet 
I tested this with KeePassDX Pro v2.8.7.  Everything works great. The custom data is stored perfectly.

Thank you very much for the fix.
