### ISSUE TITLE
Getting Invalid Credentials Error

### ISSUE THREAD

**Issue by rustyred14** [Kunzisoft/KeePassDX#654]
When I enter the password to my .kbdx 4 file i get the error of invalid credentials and i've triple checked the password

**Comment by J-Jamet** [comment]
Have you tried opening it with another application on your computer? KeePass2 or KeePassXC? These software can provide details about database errors.

**Comment by rustyred14** [comment]
so this vault was created in keepass xc on my pc and i also tried it on keepass and it works on pc but when it comes to opening it on my phone with say keepass2android i get invalid credentials there too. 
so i'm not sure if its something with the file or not

**Comment by J-Jamet** [comment]
If other apps say the credentials are invalid then the credentials are really invalid or your file is corrupted. If you think you are in the second case, try to understand why your database is corrupted and restore a backup.
