### ISSUE TITLE
changes of entry title don't appear in history

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#657]
Open some entry for editing, then change it's title and save it. If you change any item of an entry a record about it appears in history. Except for changing of title. But I think it should. Though modify date changees.

KeepassDX version is 2.8.1.

**Comment by J-Jamet** [comment]
Just tested and it works fine. Can you be more specific on the type of database used and the conditions to reproduce the bug.

**Comment by zveber** [comment]
Oh, sorry. It is my misunderstanding of how history works. The last change of an entry is not an element of history but the entry itself. I tried to change the title of an entry more than one time and it is all ok.
