### ISSUE TITLE
Move a group

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#658]
Suppose you want to move a group (I mean an item which can contain other groups and entries). So you do a long tap on it. A panel with actions appears. You can unselect, delete, open or rename it. But there is no button to cut it.

KeepassDX version is 2.8.1.

**Comment by J-Jamet** [comment]
This feature will take significant development time for little benefit, so is not a priority. At the moment, just cut and paste the entries into another group.

**Comment by zveber** [comment]
Thanks for your work. I just tried it and it works with no problem.
