### ISSUE TITLE
Make notes section scrollable when editing [feature request]

### ISSUE THREAD

**Issue by bushrang3r** [Kunzisoft/KeePassDX#676]
Some of the notes of my password entries are pages long and when I edit them, I need to scroll down a long way. The only way to do that is to grab the cursor with your finger and pull it down which is quite difficult to do.
Would it be possible to make the notes section scrollable when editing? 

Thanks for an awesome app! 🙂

**Comment by J-Jamet** [comment]
I just removed the limit on the number of lines, you should see all the text.

**Comment by bushrang3r** [comment]
Thank you sir! 
Much appreciated! 😁😁
