### ISSUE TITLE
Biometric unlocking does not work

### ISSUE THREAD

**Issue by AreYouLoco** [Kunzisoft/KeePassDX#678]
Hi I've tried to update to 2.8.2 from f-droid and I can no longer use my fingerprint to unlock database. When I downgrade to 2.8.1 everything works as expected. Will post a screenshot with error message. Android 8.1 vendor stock.

**Comment by J-Jamet** [comment]
I haven't changed a lot for biometric. Can you tell me what the error message is?

**Comment by J-Jamet** [comment]
I just checked, the code is almost identical, I simply fixed a problem in the display of views when it is deactivated, and the button view. Otherwise it's the same. Have you tested to delete fingerprint keys?

**Comment by AreYouLoco** [comment]
I reinstalled from scratch 2.8.1 and then upgraded to 2.8.2 and it works. Cannot reproduce the bug anymore. Weird. Too bad I dont remember error message. Will check the source for error messages and see which one it was.

**Comment by J-Jamet** [comment]
Error messages can be contained in the API, so not necessarily in the application.
