### ISSUE TITLE
Autofill prompt non working correctly in Firefox Beta

### ISSUE THREAD

**Issue by auanasgheps** [Kunzisoft/KeePassDX#681]
**Describe the bug**

Hi, I have observed a weird behaviour with the autofill prompt when used with Firefox Beta.
I have uploaded a demo video here when you can see what happens: [link](https://imgur.com/a/7gZf18Q)

It will either:
- (Like in the video) prompt appears to be fine, I click it, it does not work. By doing random click appears for a moment being unusable
- prompt flashes, If I'm very lucky I can catch it but usually does not happen.

It happens on all websites I've tested. The one I am showing is a Fritz Router login but does not really matter.

**To Reproduce**
1. Use Firefox Beta from PlayStore
2. Enable Autofill
3. Navigate to a website (e.g. with Facebook I get the same behavior)

**Expected behavior**
The prompt should not flash or disappear or not work.
** Keepass Database **
- Created with: oh man I can't remember it's an old DB
- Version: KDBX 3.1
- Location: Remote File on Google Drive, but retrieved via the system File Manager
- Size: 500 Kb
- Contains attachment: I don't think so

**KeePassDX (please complete the following information):**
 - Version: 2.8.2
 - Build: Free
 - Language: Italian

**Android (please complete the following information):**
 - Device: Xiaomi Redmi Note 8T
 - Version: 9

**Additional context**
 - Browser for Autofill: Firefox Beta 80.0.1-beta2

**Comment by J-Jamet** [comment]
This is because of the latest version of firefox which seems to do an automatic reload of the views when you select a field. There is nothing I can do on my side, I can only tell the autofill service to fill up, but cannot ask to display properly on a changing page.

**Comment by J-Jamet** [comment]
By the way, I just retested and it works fine for me after restarting firefox.

**Comment by auanasgheps** [comment]
> This is because of the latest version of firefox which seems to do an automatic reload of the views when you select a field. 

Thanks for letting me know. Tested with Keepass2Android and actually has the same behavior.

It does not work in my case after restarting Firefox. It's a hit or miss, very rarely works. Might be worth pointing this out somewhere?

Ironically on the same device I have noticed an issue with autofilling on Chrome...

**Comment by J-Jamet** [comment]
Maybe it's coming from the autofill service itself on your Android version.

**Comment by auanasgheps** [comment]
Autofill does not "flash" when using the latest Firefox Nightly. So apparently it's going to be fixed on FF 81.
