### ISSUE TITLE
Cannot click autofill prompt

### ISSUE THREAD

**Issue by auanasgheps** [Kunzisoft/KeePassDX#682]
**Describe the bug**
Hi, I have observed a weird behaviour with the autofill prompt when used on my Redmi Note 8T running Android 9.
You can see the video [here](https://imgur.com/a/biNF9x5).
<blockquote class="imgur-embed-pub" lang="en" data-id="a/biNF9x5"  ><a href="//imgur.com/a/biNF9x5">KeepassDX w/ Chrome on Redmi Note 8T</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

The autofill prompt shows up correctly, but when I click it nothing happens.
I have uninstalled and reset the KPDX but it has not made a difference.

Keepass2Android works fine using the same prompt.

The behaviour is the same with Firefox (Nightly).

**To Reproduce**
1. Install KeepassDX
2. Enable Autofill
3. Browse to a website and try to autofill

**Expected behavior**
The prompt should take me to KeepassDX

** Keepass Database **
- Created with: oh man I can't remember it's an old DB
- Version: KDBX 3.1
- Location: Remote File on Google Drive, but retrieved via the system File Manager
- Size: 500 Kb
- Contains attachment: I don't think so

**KeePassDX (please complete the following information):**
 - Version: 2.8.2
 - Build: Free
 - Language: Italian

**Android (please complete the following information):**
 - Device: Xiaomi Redmi Note 8T
 - Version: 9

**Additional context**
 - Browser for Autofill: Chrome 85.0.4183.81

**Comment by J-Jamet** [comment]
Did you activate the special permission for MIUI devices, as described in the wiki?
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#set-up

**Comment by auanasgheps** [comment]
I was unaware of this option, sorry.
Works beautifully now.
