### ISSUE TITLE
Uploading and deleting attachments at the same time cause incomplete deleting.

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#684]
**Describe the bug**
Even if attachments disappear in an entry screen,  the database may still include the attachments.  There is no way to recover Database performance.

**To Reproduce**
1. Upload a (large) file.
2. Delete the attachment or reupload the file to replace it.
3. Validate and Save
4. The attachment has been deleted apparently, but the database size isn't reduced.

KeePassDX  Version: 2.8.3.

**Comment by J-Jamet** [comment]
OK, I normally fixed the problem in development (will be available in 2.8.4). I also added a setting to delete unlinked data in the database.

**Comment by hokonch** [comment]
Thank you for fixing the issue.
Deleting unlinked data needs manually saving even If autosave is enabled. Is this a designed behaviour?

**Comment by J-Jamet** [comment]
You are right, this is not the appropriate behavior, I will change it.
