### ISSUE TITLE
When opening an entry with no username at the first time, KeePassDX is not operable until pressing the back button.

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#685]
**To Reproduce**
1. Clear app data or reset Educational hints
2. Open an entry which have no username
3. Does not work any buttons on the entry screen

KeePassDX Version: 2.8.3 (not reproducible in version 2.8.2)

**Comment by J-Jamet** [comment]
I cannot reproduce this bug. For me, the education hints load without problem and the screen reacts correctly with all the tests carried out. Can you tell me the type of your device?

**Comment by J-Jamet** [comment]
I just reproduced the problem, it's weird that it doesn't happen all the time. I have tried to debug this problem.
