### ISSUE TITLE
Different channels for each type of notification

### ISSUE THREAD

**Issue by Alexandero89** [Kunzisoft/KeePassDX#688]
OS: Android 10
Keepassdx Version: 2.8.3 (F-Droid)

There is a permanent notification that is telling me the database is open. 
I understand that this is a critical feature for some people. But would it be possible to opt-out this feature? 

I know that I can just disable notifications on Android for some apps, but that would be more of a dirty workaround than a solution. 

Thanks in regard!
By the way: I **really** appreciate your work. Thank you for that!

**Comment by J-Jamet** [comment]
This notification is part of the foreground service and I cannot remove it.
https://developer.android.com/guide/components/services

> I know that I can just disable notifications on Android for some apps, but that would be more of a dirty workaround than a solution.

This is the right solution for what you want. It is not a workaround, since this option is part of the system.

**Comment by hokonch** [comment]
I'm not interested in this feature, but isn't it possible on Android 8.0 or later?
Keepass2Android can turn off only this notification.
![Screenshot_20200917-183209](https://user-images.githubusercontent.com/54430032/93454794-6bb76800-f916-11ea-89d7-5b502851201a.png)

**Comment by J-Jamet** [comment]
https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels

OK, I reopen the issue so that it is an area for improvement. Different channels should be implemented for each type of notification.
