### ISSUE TITLE
Application stops when unlocking the database

### ISSUE THREAD

**Issue by Hund** [Kunzisoft/KeePassDX#692]
**Describe the bug**

The application "stops" (according to Android) when I successfully unlock it.

**To Reproduce**
1. Choose the database.
2. Enter the correct password or use the fingerprint reader to unlock the database.
3. Application then stalls for a second or two and then jumps back to the view where you can choose the database. Unlocking it a second time triggers a dialog from Android that tells you that "Kepassxc keeps closing".

**Keepass Database:**
 - Created with: KeePassC 1.8.0.
 - Version:  KeePass v.1.x
 - Location: Local file.
 - Size: 32.76 kB.
 - Contains attachment: Attachments?

**KeePassDX:**
 - Version: 2.8.3
 - Build: F-Droid
 - Language: English

**Android:**
 - Device: Google Pixel 3a
 - Version: 10

**Comment by J-Jamet** [comment]
Can you provide logs during the crash?
Because I can't reproduce the problem. Thank you

**Comment by hokonch** [comment]
I reproduced this issue.

**Keepass Database**　
[keepassc.kdb.zip](https://github.com/Kunzisoft/KeePassDX/files/5199176/keepassc.kdb.zip)
 - Created with: macOS KeePassC 1.82 (latest) with no editing
 - Version: 1
- Location: Local file
 - Size: 188 B

**Android :**
 - Device: Google Pixel3a
 - Version: 10 & 11

**Comment by J-Jamet** [comment]
Seems to be a loop when check backup. I'll try to fix this issue in the next version
