### ISSUE TITLE
Can't open the database in keepass windows or Linux

### ISSUE THREAD

**Issue by duvamduvam** [Kunzisoft/KeePassDX#694]
Hi,

Since some time, I can't open the database in other keepass soft on my laptop.
The database is shared through nextcloud, I can open it normaly in KeepassDX but not in the other apps.
It saying "not in gzip format", it is quite annoying I can't use my keyword database anymore.

David

**Comment by J-Jamet** [comment]
You did not fill out the bug form. Please indicate the version of KeePassDX used, the version of the database, if it contains attachments and attachment type (compressed or not).

**Comment by duvamduvam** [comment]
Ah, sorry ...
It is version 2.8.2, it doesn't contain attachement apart little pics for categories.
Yes it was compressed, I desactived the compression and it is now working on others keepass soft.
Sorry for disturbing.
