### ISSUE TITLE
painful to create a password

### ISSUE THREAD

**Issue by bigfatfrog67** [Kunzisoft/KeePassDX#695]
If I land on a site where I need to create a  password it is really painful to do this in keepassdx.
I load the app, there is no menu item or button to bring up the password generator!
I have to click the + button to create an entry.
Then I have to click the dice button to generate a password, now I have a password (but I can't see it because of the stupid stars masking it, even though hide passwords is switched off in my settings).
So I now have a password but to copy it I have to:
1. Unmask the password
2. Long click the password (doesn't highlight the whole password)
3. Click ... 
4. Choose select all
5. Choose copy

OMG 😂 my finger's numb, I've lost count of the number of taps that all needed.

Request:
1. Put the dice in the main screen it menu please
2. Unmask passwords as per the settings option
3. Put a copy button next to each password or username field.

**Comment by J-Jamet** [comment]
> Put the dice in the main screen it menu please
Duplicate : https://github.com/Kunzisoft/KeePassDX/issues/518

> Unmask passwords as per the settings option
https://github.com/Kunzisoft/KeePassDX/issues/696

> Put a copy button next to each password or username field.
Already the case.
You have knowingly deactivated this option: Settings -> Form filling ->Clipboard trust

I opened #696 for the second request. The others are duplication and invalid, I close this ticket.

**Comment by bigfatfrog67** [comment]
The clipboard is trusted in my settings. The copy button is present for an existing entry but not while adding a new entry or in the password generator.

**Comment by J-Jamet** [comment]
OK, I add an issue to copy the password from the generator. https://github.com/Kunzisoft/KeePassDX/issues/697

**Comment by bigfatfrog67** [comment]
Thank you 👍😃
