### ISSUE TITLE
Support for TOTP

### ISSUE THREAD

**Issue by Generator** [Kunzisoft/KeePassDX#70]
## Expected Behavior

Able to copy TOTP tokens

## Current Behavior
No support for TOTP, if try to login to an account with TOPT need to use an external app or unable to login.

## Version
KeePass DX: 2.5.0.0beta7-libre
Android: 8.1.0

**Comment by J-Jamet** [comment]
I know this is a requested feature, but I have to prioritize and do things in order to avoid regressions and keep stability, I need to implement the attached file management which is also much requested. If developers want to participate in the development of the TOTP feature, do not hesitate! ;)

**Comment by mrdev023** [comment]
I'm try to implement this. ^^

**Comment by seanlynch** [comment]
For folks looking to back up/sync their TOTP secrets across devices until this is implemented, there's AndOTP, which is also open source. It's really nice not to need to manage backup codes for each site separately. I'd much rather have it integrated into KeePass DX, though. 

I'd post a bounty, but BountySource doesn't expose a UI for requesting refunds on expired bounties, and they charged me a fee to get my own money back after hanging onto my money and earning interest on it for a year.

**Comment by trymeouteh** [comment]
This is the only feature I would like besides file attachments. Once this is added I think KeePassDX will be perfect in my opinion.

**Comment by Komic** [comment]
pretty much the last thing I need from DX, excited! Thanks for your work @J-Jamet!

**Comment by J-Jamet** [comment]
I integrated the code with the current version of the application in the branch "feature/TOTP". I noticed a bug in the parse of the url that prevents decrypting an otpauth link.
Continuing the discussion in the issue #70

**Comment by Offerel** [comment]
Personally I'm using https://github.com/victor-rds/KeeTrayTOTP, but that's only a fork which supports steam variant.

**Comment by J-Jamet** [comment]
@Offerel Yes I think integrate the steam format, but what is needed is to harmonize the formats stored in the database. If there are different methods for each plugin, it will be complicated.

I think, it's best to first integrate the HOTP format and make it compatible with the TOTP.
If a "totp" custom field is present in an entry, it takes precedence over the HMAC fields.
One of the main  problem will be to hide the fields used as OTP parameters in the Magikeyboard/Autofill and refresh an auto generated OTP field.
For the HOTP I was thinking about a manual increment system but it can come later.

**Comment by grimpy** [comment]
I'm using this in combination with keepassxc in the newest version it simply stored an attributed `otp` and stores the full url with settings in there

this is the configuration dialog
![image](https://user-images.githubusercontent.com/143869/68194868-75660480-ffbe-11e9-8ef4-b3715d1016d7.png)


Example how a standard totp is stored
![image](https://user-images.githubusercontent.com/143869/68195032-d097f700-ffbe-11e9-9a97-323816f5f4fa.png)

Example how steam token is stored:
![image](https://user-images.githubusercontent.com/143869/68195184-1654bf80-ffbf-11e9-8f77-ff8863de76d0.png)

**Comment by J-Jamet** [comment]
Thank you @grimpy for screenshots.
I integrated your work, it's a great start. I'm trying to see why I can not parse url otpauth. Maybe the Uri class built in older devices do not recognize it so I change a little your code.
If the plugins work the same way I will focus on this method.

**Comment by rhamzeh** [comment]
@J-Jamet KeepassXC[1] and Keepass2Android[2] implementations may be a helpful reference.

One thing to note, some providers, like Twitter pad the secrets with spaces when being copied, as as most people copy and paste it in, they might not notice the extra spaces at the end. It would be a good idea to trim before saving the totp secret to the database.

Also as these two implementations are compatible with each other, it is better if the KeePassDX is compatible with both.

On the Keyboard side, you may not need to refresh the TOTP, just calculate and insert it when the user presses that button, it does not need to be visible.

[1](https://github.com/keepassxreboot/keepassxc/blob/develop/src/totp/totp.cpp)
[2](https://github.com/PhilippC/keepass2android/blob/master/src/keepass2android/Totp/KeeOtpPluginAdapter.cs)

**Comment by J-Jamet** [comment]
I just finished the feature. It was not easy but I managed several cases.

**Comment by J-Jamet** [comment]
Available in 2.5.0.0beta24 version. If some OTP generation elements do not work. Thanks for opening a new issue. ;)
