### ISSUE TITLE
add attachments file

### ISSUE THREAD

**Issue by zpcol** [Kunzisoft/KeePassDX#700]
is it possible to add attachments in the form of a txt file, keychain or a image to the kdbx database?

**Comment by J-Jamet** [comment]
Since version 2.8.3 yes. There are some small bugs that will be fixed in version 2.8.4 for the upload.

**Comment by zpcol** [comment]
ok, thank you very much, it's not in vain I often suggest to many people to use this application, it turns out that the developer is also friendly. thanks.
