### ISSUE TITLE
Autofill based on domain/url in Firefox for Android 11

### ISSUE THREAD

**Issue by nils-one** [Kunzisoft/KeePassDX#702]
First of all, thank you so much for your great work! 

**Description**
I have a problem with autofill within the firefox browser. It looks like KeePassDX is only looking for the AppID (org.mozilla.firefox) but not for the opened Domain. But I think firefox is offering the domain, because other password apps  i.e. Bitwarden autofills forms based on URL without problems. 

**Steps to reproduce**
1. Open actual Firefox for Android.
2. Go to any webpage with a login form with a matching password and url within opened kdbx database.
3. Click on the autofill overlay.
4. The app looks for an entry with the AppID org.mozilla.firefox

**Expected behavior**
The app should look for the entries with matching urls and not matching AppIDs

**Keepass Database**
 - Created with: KeePassXC 2.6.1
 - Version: 2
 - Location: local (synced via nextcloud app)

**KeePassDX:**
 - Version: 2.8.3
 - Build: Free
 - Language: German

**Android:**
 - Device: Pixel 2
 - Version: 11

**Additional context**
 - Browser for Autofill: Firefox for Android

**Comment by J-Jamet** [comment]
Are you sure you have not activated the accessibility service on Bitwarden?

**Comment by nils-one** [comment]
For autofill, which works like in Bitwarden, would an accessibility service for KeePassDX be required, right?
Ah okay, now I got the problem. So there is no bug this would be a huge feature request, my fault.

**Comment by hokonch** [comment]
I had noticed this issue recently, but I am sure this issue did not exist a few weeks ago.
Perhaps this issue is related to Android 11 because this issue is reproduced even if downgrading Firefox or KeePassDX.

**Comment by J-Jamet** [comment]
Indeed, I also think that it comes from Android 11. Because I have just retested on Android 10 and I have no problem with firefox. I don't have a device with Android 11 yet so I'll have to get one.

**Comment by J-Jamet** [comment]
https://developer.android.com/guide/topics/text/ime-autofill

**Comment by J-Jamet** [comment]
I just tested on Android 11 with Lightning and have no issues so the problem is with firefox. I can't do anything on my side.

**Comment by J-Jamet** [comment]
But you're right, Bitwarden managed to display its popup with the autofill, there must be a trick.

**Comment by J-Jamet** [comment]
OK, I think I found it. It seems that the new version of firefox returns the webDomain several times and the first time it is empty. I will try to improve the algorithm to solve this problem. Sorry for those hasty conclusions.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/issues/1465

https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard
Wiki : **Warning: if you use the button in a web browser, it will be the name of the browser package that will be used and not the URL of the page. For the URL, use method B.**
