### ISSUE TITLE
build-in simple keyboard when open database

### ISSUE THREAD

**Issue by zpcol** [Kunzisoft/KeePassDX#703]
Now there are so many virtual keyboard applications circulating on Android, and we don't know which application is free from the term "key logger".

For added convenience, it's a good idea to add a "built-in simple keyboard" below the "enter password and keyfile" text box like this.

https://virtual-keyboard.js.org

thanks.

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/528

**Comment by zpcol** [comment]
The keyboard I mean like this, is in one "frame / page".
![Screenshot_20200921-123015_Encryption_Manager_Lite](https://user-images.githubusercontent.com/69243210/93738978-63f70c80-fc11-11ea-9307-05ad8b8b3e02.png)
