### ISSUE TITLE
auto create backup database file when autosave

### ISSUE THREAD

**Issue by zpcol** [Kunzisoft/KeePassDX#704]
I see there is an option "auto save database" but there is no feature to automatically create a database backup file when saving.

This is very important because the saving process is not always successful due to many factors.

This screenshot is an example of the features in the titanium backup application.

![Screenshot_20200916-134502_Titanium_Backup](https://user-images.githubusercontent.com/69243210/93301604-e3a46600-f822-11ea-82ad-973df9c814b2.png)

thanks.

**Comment by J-Jamet** [comment]
KeePassDX is intended to be a low level application that uses the storage access framework to back up data.

In its software construction, it is up to the user to set up a backup system. An external automatic backup will require a built-in file manager, which I don't want. https://github.com/Kunzisoft/KeePassDX/wiki/Backup

Or it would be necessary to save the databases in the memory of the app to export them later, it is possible but it is necessary to discuss about it to see the real interest and security issue compared to manual or routine backups.

**Comment by zpcol** [comment]
not a matter of primary importance, but the heart feels comfortable.

btw, there is no explanation on the wiki about encryption, which one do you think is the strongest?

**Comment by J-Jamet** [comment]
> btw, there is no explanation on the wiki about encryption, which one do you think is the strongest?

https://github.com/Kunzisoft/KeePassDX/issues/706

https://en.wikipedia.org/wiki/Advanced_Encryption_Standard
https://en.wikipedia.org/wiki/Twofish
https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant

https://en.wikipedia.org/wiki/Key_derivation_function
https://en.wikipedia.org/wiki/Argon2

You can choose from the existing algorithms the one you want, and adapt the round parameter for the KDF.
Who do you think is the strongest in Expendables?

**Comment by zpcol** [comment]
after i open with an UTF-16 encode, i think the highest number of unread characters is the best.

![20200921_104610478](https://user-images.githubusercontent.com/69243210/93731781-bd067680-fbf8-11ea-941d-3205167f9043.jpeg)

![20200921_104620908](https://user-images.githubusercontent.com/69243210/93731793-cabbfc00-fbf8-11ea-8608-e8e64eed6380.jpeg)

![20200921_104630914](https://user-images.githubusercontent.com/69243210/93731815-eaebbb00-fbf8-11ea-81d1-2db8cc54c74b.jpeg)

**Comment by zpcol** [comment]
before backing up to the cloud, it's good to be encrypted again :)

![20200921_112557242](https://user-images.githubusercontent.com/69243210/93733154-7287f880-fbfe-11ea-87be-d8d571aee775.jpeg)

![20200921_112436980](https://user-images.githubusercontent.com/69243210/93733163-7f0c5100-fbfe-11ea-86ea-40abd2515513.jpeg)

**Comment by J-Jamet** [comment]
Part of external file manager app : https://github.com/Kunzisoft/FileSync/issues/8
