### ISSUE TITLE
File Manager doesn't show enough detail

### ISSUE THREAD

**Issue by RichardMyersGV** [Kunzisoft/KeePassDX#705]
When selecting the Keepass DB using the file selector (and perhaps in other file selection functions), not enough detail is shown to know which file to select. 

Request showing the full name and file extension, or at least a reasonable number of characters us the file extension. 

![Screenshot_20200916-144613_Files](https://user-images.githubusercontent.com/24857791/93396760-050a4f80-f82d-11ea-9051-20624119bc2c.jpg)

Thanks, 
Richard

**Comment by J-Jamet** [comment]
This request is not part of the KeePassDX application.
Try to view the files in detail in the settings of your file manager. If this still doesn't suit you, contact the program's developers or download another file manager.
