### ISSUE TITLE
Follow system dark mode

### ISSUE THREAD

**Issue by Mynacol** [Kunzisoft/KeePassDX#714]
**Is your feature request related to a problem? Please describe.**
KeePassDX does not follow system-wide dark mode.
If I open the app at night, it should use a dark theme, following the system setting.
(Available since Android 10)

**Describe the solution you'd like**
The app should be able to follow the system dark mode.

**Describe alternatives you've considered**
- Offer a single "Theme" which follows the system setting and switches between two predefined themes (Light and Dark, probably)
- Offer the option to follow system theme by selecting a "Light" and a "Dark" theme, between whose is switched based on system settings

**Additional context**
The Android documentation is found [here](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme).

Thanks for maintaining this app!

**Comment by Hund** [comment]
This is a highly appreciated feature. I'm not a dark mode person, but it's nice to have late nights and early mornings when you don't want your phone to function as a flashlight in your face.

**Comment by Ilithy** [comment]
Good idea to improve the user experience 👍
