### ISSUE TITLE
New attachments are empty in KeePass2 but not in KeePassXC

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#715]
This problem is very weird, because it seems that the attachments are attached correctly in the header but they are not correctly decrypted by KeePass2 but clearly visible by KeePassXC. (Note: Also correctly visible in KeePassDX)

Only with KBDX 4.0 databases, KDBX 3.1 uses attachments in the XML and not in the header.

**Comment by J-Jamet** [comment]
[demoErrorKDBX4.zip](https://github.com/Kunzisoft/KeePassDX/files/5276771/demoErrorKDBX4.zip)
password : `secret`

In this example, the entry `My Computer / SSH Key` contains two attachments: _"id_rsa"_ and _"id_rsa.pub"_.
In **KeePass2**, _"id_rsa"_ has the contents of _"id_rsa.pub"_ and _"id_rsa.pub"_ is an empty file.
In **KeePassXC**, both attachments are read correctly.
In both cases, the history is correct.

**Comment by J-Jamet** [comment]
I did a lot of testing, checked the data formatting but still don't understand the problem. If anyone has any advice on empty attachments in KeePass2, this might help.

**Comment by mlunax** [comment]
I don't know what makes this but I want to notice, the otp fields or have the otp url or is empty. 
Trying to use this fields in DX clears the otp url.

**Comment by J-Jamet** [comment]
@mlunax It's another [bug](https://github.com/Kunzisoft/KeePassDX/issues/781), will be fixed in version 2.9.2

**Comment by J-Jamet** [comment]
> (from Dominik)
In your demoErrorKDBX4.kdbx file, the third and the fourth binary content in the inner header are identical. As KeePass assumes that a deduplication has been performed, the fourth binary content is ignored and the indices are interpreted differently from this point on.
I guess it's more likely that an application doesn't perform a deduplication than accidently storing a binary content multiple times in the inner header. Therefore, I've now added support for loading duplicate binary contents for the next KeePass release. With this, your demoErrorKDBX4.kdbx file can now be loaded with KeePass.

It is therefore necessary to remove file duplication in binaries.

**Comment by Vstory** [comment]
This problem is solved, great!
