### ISSUE TITLE
Prevent manual creation of existing field name

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#718]
Prevent the creation of a new custom field in the entry edit screen if a field with the same label is already present

**Comment by hokonch** [comment]
It is likely for a user to try to add the `URL` field as custom fields to support multiple URLs manually. In this case, it is misleading that there can be two `URL` fields on the edit screen.

**Comment by hokonch** [comment]
**Bug**
1. Add entry
2. Add field
3. Input an non-exsiting name for Field name and tap OK
4. The field name already exists.

**Comment by J-Jamet** [comment]
Can you tell me what is your configuration? I will check on my other devices but on my first test I have no problem.

**Comment by J-Jamet** [comment]
OK, I reproduce it, it's on the first creation

**Comment by hokonch** [comment]
The Snackbar prevents you from adding a new field again. How about using Toast?

**Comment by J-Jamet** [comment]
You just have to wait for it to disappear, it is not long and the user will only make the mistake once. I prefer to standardize the errors by prioritizing the display in a snackbar. I may be able to move the error message above the bottombar but honestly that's okay like that.

**Comment by J-Jamet** [comment]
I can solve the SnackBar visual bug with setAnchorView(), but this method is only available in newer versions of the library material.
https://stackoverflow.com/questions/58950234/android-cant-call-setanchorview-on-material-snackbar
