### ISSUE TITLE
Wrong attached files in entries

### ISSUE THREAD

**Issue by Martin1887** [Kunzisoft/KeePassDX#726]
**Describe the bug**
When there are several entries with several attached files the file size is messed among attachments, and downloading a file also downloads another one.

**To Reproduce**
1. Open a database with several entries and several attachments in different entries.
2. Attached files are not correct or the file size is not correct in some files.
3. Downloading a file writes it with the selected name but the content is of another file.

**Expected behavior**
The files are correct in all entries.

** Keepass Database **
 - Created with: Fedora KeePassXC 2.6.1.
 - Version: 2.6.1.
 - Location: Local file.
 - Size: 1.7 MB.
 - Contains attachment: Yes, several.

**KeePassDX (please complete the following information):**
 - Version: 2.8.3.
 - Build: F-droid.
 - Language: Spanish.

**Android (please complete the following information):**
 - Device: Oneplus 6
 - Version: LineageOS 16.

**Comment by J-Jamet** [comment]
The problem is the same as https://github.com/Kunzisoft/KeePassDX/issues/713
and has been resolved.
Please download version 2.8.7
