### ISSUE TITLE
Fingerprint Issue 

### ISSUE THREAD

**Issue by mariusZZ51** [Kunzisoft/KeePassDX#731]
**Describe the bug**
Tried to add fingerprint but don't work at all LG G7/Android 10

**Expected behavior**
IT ASKS ME TO PUT MY FINGER ON THE SCANNER BUT DOESN'T HAVE ANY REACTION

**KeePassDX (please complete the following information):**
 - Version:LAST
 - Build: [e.g. Free]
 - Language: EN

**Android (please complete the following information):**
 - Device:LG G7
 - Version:ANDROID 10

**Comment by J-Jamet** [comment]
Linked to #724

**Comment by J-Jamet** [comment]
Have you tried the test APK in the issue #724?

**Comment by mariusZZ51** [comment]
"no need to scream" !?? hahaha 😆😆😆 nice joke ....
so i think i realised where was issue ..i don't think is in app ! its most likely to be a issue fro Android 10 because i never had such issues with  9 ! and as soon as I updated the phone I've got this not only in Keepass but to unlok the phone itself... so my apologies ! case closed .....

**Comment by J-Jamet** [comment]
No problem. This is a discussion that may be useful for other users, so thank you.
In any case, the fingerprint recognition system will be updated for the next version.
