### ISSUE TITLE
Biometric prompt auto-opened even while unlocking database

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#738]
**Describe the bug**
A very minor bug but may potentially make a database broken.

**To Reproduce**
1. Create a database with long KDF iteration and save its biometric key
2. Enable Auto-open biometric prompt
3. Scan biometric to open the database
4. Switch other screens and back the database credential screen

This bug basically doesn't cause any problems in normal usage. But there were some strange behaviors when scanning biometric more times as a test.
[An example of breaking the database](https://i.imgur.com/1zEPOMU.mp4)

**Expected behavior**
Not open Biometric prompt while unlocking database

**KeePassDX:**
 - Version: 2.8.7
 - Language: English

**Android:**
 - Device: Pixel3a
 - Version: 11

**Comment by J-Jamet** [comment]
I don't think it can do any database corruption, but indeed the biometric entry processing workflow is difficult to manage. Here I just think it's trying to process an open and you stay on the password page, but that doesn't change the integrity of the data.

**Comment by J-Jamet** [comment]
In the video, the issue seems to be the link sharing workflow from a browser during the database opening.

**Comment by J-Jamet** [comment]
Fine, I solved the problem by checking if a task service is in progress and by redirecting to the group activity opened from the selection activity (when the task ends).

**Comment by J-Jamet** [comment]
Tell me if it's OK for you?
