### ISSUE TITLE
Notification closing very slowly when pressing lock button

### ISSUE THREAD

**Issue by ilmoro93** [Kunzisoft/KeePassDX#739]
**Describe the bug**
When I lock an open database from the notification button it takes approximately 5 seconds for the notification to disappear.

**To Reproduce**
1. Unlock a database
2. Open notifications
3. Click ok the lock button ("Blocca" in italian)

**Expected behavior**
Close immediately the notification.

** Keepass Database **
 - Created with: both Windows and Android version
 - Version: 2
 - Location: both local and remote file retrieved with GDrive app
 - Size: any
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.8.7
 - Build: Free
 - Language: Italian

**Android (please complete the following information):**
 - Device: Both Nokia 7 plus and Motorola One Zoom
 - Version: 10

**Additional context**
This happens both with app open and closed. If I am inside the database I can see that the database closes instantly as if I pressed the in-app lock icon. Only the notification stays up a long time.

**Comment by J-Jamet** [comment]
This is a problem that I cannot solve because it is an Android security protection for the foreground service which must remain active for at least 5 seconds.
https://stackoverflow.com/questions/59526254/foreground-service-notification-always-shown-for-at-least-5-seconds

Linked to https://github.com/Kunzisoft/KeePassDX/issues/500

**Comment by J-Jamet** [comment]
Note that in fact, only the notification service remains active during closing, the actions to clear the database are performed on click.

**Comment by ilmoro93** [comment]
Ok, thanks for your quick answer.
