### ISSUE TITLE
Can't use biometric unlock with more than one database

### ISSUE THREAD

**Issue by Smolli** [Kunzisoft/KeePassDX#740]
**Describe the bug**
I have two databases, one private and one for my business account. Both are on different cloud drives, Google Drive and Nextcloud, if this detail does matter in any way. I'm using an Pixel 4xl with Android 11. 

I am using Face Unlock for the databases to unlock and this works fine unless I switch to the other database. I already tried and cleared the biometric data completely from the application. 

Unlocking the first database with Face Unlock works fine. When I'm unlocking the second database biometrical this also works fine. But trying to open the first database again results in the error, that the biometric key can't be read. When I'm removing the key and unlock the database with password and Face Unlock, the second one can't be opened anymore.

**To Reproduce**
1. Open a database with password and Face Unlock
2. Open another database with password and Face Unlock
3. Try to open first database with only Face Unlock

**Expected behavior**
Both databases can be unlocked only with Face Unlock.

**Keepass Database**
 - Created with: Windows KeePass 2.44
 - Version: 2
 - Location: Remote file retrieved with GDrive and Nextcloud app
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 2.8.6
 - Build: libre
 - Language: German

**Android:**
 - Device: Pixel 4xl
 - Version: 11 (September 2020)

**Additional context**
none

**Comment by J-Jamet** [comment]
Indeed it's weird, I'm in the process of implementing the new biometric API. Can you test if this behavior still happens with the APK in this thread? https://github.com/Kunzisoft/KeePassDX/issues/724#issuecomment-701551601
This may be due to the internal biometric system of the Google Drive app which invalidates the biometric keys when using different URIs. (To check)

**Comment by Smolli** [comment]
Hi @J-Jamet,

thanks for the reply. Indeed, the linked APK works! I'm also pretty sure that it worked with an older version.

**Comment by J-Jamet** [comment]
OK, so I think it's coming from the new Android security standards for biometric recognition (new security level implementation). Since it was still on the old API, the keys were invalidated.
Glad it works, the fix will be in the next release.

**Comment by Smolli** [comment]
Thanks. Sounds great!
