### ISSUE TITLE
Warning at emptying the recycle bin is confusing

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#742]
**To Reproduce**
When users want to delete an entry permanently but remain other entries in the recycle bin, they may follow the wrong procedure below.
1. Select an entry in the recycle bin
2. Tap the recycle bin icon at the top
3. Warning `Permanently delete selected nodes?`
4. Choose OK because they want to delete a selected node.
5. All entries will be deleted, not just the selected entry.

**Expected behavior**
Show another warning when emptying the recycle bin.
For example,`All nodes in the recycle bin will be permanently deleted.`

**Comment by J-Jamet** [comment]
You're right, I will change this behavior for the next version.
