### ISSUE TITLE
Biometric unlock database not working after reboot

### ISSUE THREAD

**Issue by naveenjohnsonv** [Kunzisoft/KeePassDX#748]
**Describe the bug**
After setting up biometric, I can unlock via it just fine. But as soon as I reboot, biometric unlocking refuses to work. It shows the error "Failed to obtain information about key". If I try to remove the credential database and add it again by typing in password, biometric input is not requested on clicking the biometric icon, just shows error "Keystore operation failed"
A temporary fix is to reenroll fingerprint in the device settings. After doing that keepassdx works normally, until I reboot.

**To Reproduce**
1. Set up everything including fingerprint
2. Check if everything works
3. Reboot device
4. Try to unlock database via biometric only to find it not working

**Expected behavior** Biometric should work even after a reboot. 

**Keepass Database**
 - Created with: Linux KeePassXC 2.6.1
 - Version:  2.6.1
 - Location: Documents folder, in internal storage.
 - Size: 250KB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.8.7
 - Build: Latest GitHub Release
 - Language: English

**Android (please complete the following information):**
 - Device: Redmi K20 Pro
 - Version: 10

**Comment by J-Jamet** [comment]
The keystore seems not to initialize properly after restarting on your phone. 
Do you have a custom ROM?
Corrections have been made on the biometric recognition and will be applied for version 2.9 but I don't know if that will fix your problem.

**Comment by naveenjohnsonv** [comment]
Yes, custom ROM. I am certain I didn't face this before though. I'll wait for the next release

**Comment by J-Jamet** [comment]
> I am certain I didn't face this before though.

Before which condition? The new custom ROM, specific Android version or specific KeePassDX version?

**Comment by naveenjohnsonv** [comment]
I think it was the custom ROM at fault. Moved to an Android 11 ROM, facing no issues on reboot.

**Comment by J-Jamet** [comment]
Can you tell me if this issue is solved with KeePassDX 2.9.1?

**Comment by naveenjohnsonv** [comment]
That was already solved in my case. The problem I think was that I switched on an option in my custom ROM that allows me to unlock with FP on reboot (while normally you have to unlock with a pin on boot)
