### ISSUE TITLE
Generator password setting can't change when create at create password

### ISSUE THREAD

**Issue by lizard-Szilard** [Kunzisoft/KeePassDX#751]
**Describe the bug**
Setting generator password can't change when create new password not when at app setting.

**To Reproduce**
1. Go to App setting for generate password, set up size password, password character 
2. When create new database the settings generate password can't change e.g size password, which character should uses.

**Expected behavior**
When create new database the setting generator password must can change e.g size password.

**Keepass Database**
 - Created with: [ keepassDx android]
 - Version: [2.8.7]
 - Location: [Remote file retrieved with GDrive]
 - Size: [19.44KB]
 - Contains attachment: [NO]

**KeePassDX (please complete the following information):**
 - Version: [2.8.7]
 - Build: [from play store]
 - Language: [ENGLISH]

**Android (please complete the following information):**
 - Device: [OPPO A37F]
 - Version: [5.1.1 Lollipop]

**Additional context**
 - I hope the keyboard can select a text for copy/paste like google keyboard

**Comment by J-Jamet** [comment]
Sorry, but I don't understand the bug.
I have just tested and by assigning a precise size for the generation of the password, this size is indeed by default when generating an entry. And it is possible to change the value of this size.

> 1.Go to App setting for generate password, set up size password, password character

44 for example

> 2.When create new database the settings generate password can't change e.g size password, which character should uses.

When I create a database and a new entry I select the password generator and it has a size of 44 characters. When I change to 50 and press "Generate password", the size of the generated password is indeed 50.

Sorry, but I don't understand the problem.
