### ISSUE TITLE
Add autofill warning

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#752]
I have completed the big development of this autofill registration feature #524

The question now is how I warn the user about the use of autofill.
Because, to be completely secure, the recorded elements should be [linked to the certificate of the save application](https://developer.android.com/reference/android/service/autofill/AutofillService#package-verification) (wich contains the info form). But in fact, this would prevent the use of autofill for a lot of cases (if the database was already full, if we change browsers, if an application is replaced, etc ...)

So for me the solution is to warn the user when he activates the autofill with a message "Please note that the authenticity of the apps that uses the autofill service cannot be confirmed. Make sure the data is populated in trusted apps."

What do you think?

**Comment by Ilithy** [comment]
Greetings ;

This seems a good idea, and may prevent cases of password theft directly from the device; the warning is clear to me.

Another version (more simple I think):

En ver:
Please note that the use of the Autofill [service] by third party applications cannot be secured [by KeepassDX], make sure you trust the applications using it. 

Fr ver:
Veuillez noter que l'utilisation du [service de] remplissage automatique par des applications tiers ne peut être sécurisé [par KeepassDX], assurez-vous d'avoir confiance dans les applications l'utilisant.

Thanks you.

**Comment by J-Jamet** [comment]
Changes have been added to the wiki.
