### ISSUE TITLE
Open Downloaded Attachments from KeePassDX

### ISSUE THREAD

**Issue by OLLI-S** [Kunzisoft/KeePassDX#754]
In KeePassDX Pro I have some entries with attachments.
Most of them contain scanned cards of shops (like coffee shops, furniture shops, some restaurants).
When I am in one of these shops, I would like to show the card digitally on my phone.

When I unlock my database and open one of these entries, then I can download the scanned card (in PNG format).
The default save folder is the folder of my database.
After downloading the card, I would like to open the attachment with one click (so I don't have so switch apps and search for the file on my phone).

The problem here is that users have a very good usability until they save the attachment.
After saving the attachment they have no easy way of opening it.
Yes, I see a message in the notification centre that I  can open the downloaded attachment but here only KeePassDX Pro is offered and I have no chance to open it.

**Additional ideas:**
* When I have selected an entry with such an attachment and the file is already present in the KeePassDX database folder (where the KDBX file is stored) then opening the attachment without having to download it would be very handy.
* You also should offer a button in KeePassDX that deletes the downloaded file.
When users have downloaded a file that contains private information, they can delete it directly from KeePassDX.

KeePassDX is really good, keep on your fantastic work!

**Comment by J-Jamet** [comment]
> I see a message in the notification centre that I can open the downloaded attachment but here only KeePassDX Pro is offered and I have no chance to open it.

In this case, your phone does not recognize the mime type of the file that is downloaded. It can happen depending on the devices.

> When I have selected an entry with such an attachment and the file is already present in the KeePassDX database folder (where the KDBX file is stored) then opening the attachment without having to download it would be very handy.

It corresponds to the feature : https://github.com/Kunzisoft/KeePassDX/issues/473

> You also should offer a button in KeePassDX that deletes the downloaded file.
When users have downloaded a file that contains private information, they can delete it directly from KeePassDX.

KeePassDX is not a file manager, it is not the one that saves the file to the disk, it is the file manager of your phone. For your feature, I would have to ask for additional permissions to access files on the device, which I don't want for security reasons.

> KeePassDX is really good, keep on your fantastic work!

◕‿◕

I turn the issue into a question. If you want more info on the functionality to see the attachments, we can chat on #473.

**Comment by OLLI-S** [comment]
So here the **Internal image viewer for attachments** (#473) would **solve all the problems**.
@J-Jamet Now you know what to code next.
