### ISSUE TITLE
Passwords unreadable on KeePassX

### ISSUE THREAD

**Issue by geser2008** [Kunzisoft/KeePassDX#763]
I'm running KeepassDX 2.8.7 from F-Droid repository. Also I'm using KeepassX 2.0.3 from Debian Testing. To sync datadase I use Syncthing.

Yesterday I made some new password entries in my keepass DB on the Android phone with KeepassDX. The BD was saved and synced across all my devices. When I opened it today's morning on my PC I found out that passwords in all the entries (the old and the new ones) were unreadable and looked like in the picture attached. They were unusable even through the clipboard. At the same time in KeepassDX all the passwords looked fine and correct.

After that I decided to test my keepass DB on the previous version of KeepassDX (2.8.5). I took the correct DB version from the backup and made some new entries with passwords with KeepassDX 2.8.5. After DB syncing, all the entries looked correct both on my PC in KeepassX and on my Android Phone in KeepassDX 2.8.5.

To Reproduce

    Install KeepassDX 2.8.7.
    Make a new entry with password.
    Save the database.
    Open it on the PC with KeepassX 2.0.3.

Expected behavior

    All the passwords should be correctly readable both in KeepassDX and KeepassX.

Keepass Database

    Created with: KeePassX 2
    Version: KDBX3.1
    Location: local, syncing with syncthing across devices
    Size: 65KB
    Contains attachment: Yes

KeePassDX:

    Version: 2.8.7
    Build: Libre
    Language: Russian

Android:

    Device: Oppo A5 2020
    Version: 10
![Screenshot_20201026_131001](https://user-images.githubusercontent.com/1221343/97158518-5c400000-179b-11eb-8241-a759ba4ddd35.png)

**Comment by J-Jamet** [comment]
Does the problem also occur on KeePass 2 with your database?  (https://keepass.info/download.html)

**Comment by J-Jamet** [comment]
I will try to reproduce the problem but KeePassX has not been maintained since October 2016, so I do not recommend using it.

**Comment by geser2008** [comment]
> Does the problem also occur on KeePass 2 with your database? (https://keepass.info/download.html)

I have tried Keepass2 v.2.45 and KeepassXC v.2.6.1 from Debian Testing Repo and they work as expected, passwords are correct and readable. So it seems to me that smth is not quite right with KeepassX.

**Comment by geser2008** [comment]
> I will try to reproduce the problem but KeePassX has not been maintained since October 2016, so I do not recommend using it.

Heh, then I'd better switch to KeepassXC as it is still developed unlike KeepassX.

P.S. Thank you for paying my attention to that. I've never thought about it, just using the app for years.
