### ISSUE TITLE
Searching shared info from Firefox does not work in a certain situation

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#766]
This issue also reproduces on KeePassDX 2.8.7, and it is probably a
Firefox's bug because it reproduces on KeePass2Android and doesn't
reproduce on Chrome and FOSS browser.

1. Close KeePassDX
2. Share a URL by Firefox to open KeePassDX
3. Open Database and search
4. Share a URL by Firefox to KeePassDX
5. KeePassDX doesn't search the URL

**Comment by hokonch** [comment]
fixed on **`Nightly 201102 17:00 (Build #2015773323)`**

**Comment by J-Jamet** [comment]
Great! Firefox issue, I close this thread.
