### ISSUE TITLE
Auto search for IP address

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#767]
**Describe the bug**
KeePassDX does not support the auto search feature for IP address. For example, this will prevent you from auto-filling credentials to configure a router.

**To Reproduce**
1. Open 1.1.1.1 in your browser
2. Share the address with KeePassDX
3. Auto search for "" instead of "1.1.1.1"

**Comment by hokonch** [comment]
I tested latest develop branch, and this issue probably are not resolved at all. 

For your information, you may need to be aware of a bug that causes it to search for 192.168.1.1 as 1.1 when autofilling because I've seen this bug in K2PA.
(Maybe this issue should have been a feature request. I was going to report this issue without tagging it, so it was simply my mistake to report it as a bug.)

**Comment by J-Jamet** [comment]
I made a correction because before the IP was not registered at all as a search value whereas now it is.
But it is possible that the second problem comes from the option "Search sub domain". I'll check.

**Comment by J-Jamet** [comment]
The problem comes from the subdomain, by filtering the IPs the problem is resolved (when the setting is unchecked).
