### ISSUE TITLE
Font became smaller in version 2.9

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#770]
For some reason I configured my phone to use extra large font size. The problem is that after upgrading to 2.9 font used for groups and entries in entry list became smaller. Other captions (menu for example) still looks good. I've tried to clear app data but the problem still exists.

_KeepassDX_: 2.9 pro from Google Play. 
_Device_: Xiaomi Redmi Note 8T, running on MIUI 11 (it's based on Android 9).

**Comment by J-Jamet** [comment]
Thank you for the feedback, can you tell me which specific option have you activated to change the font size of the elements on your device?

**Comment by J-Jamet** [comment]
So, I can reproduce the problem with the setting `Setting > Display > Text Size` but not with `Additional settings > Accessibility > Display Size`, the problem does not occur.
MIUI 11.0.2 Redmi 6

I will try to let the system manage the size of the text when it is set to `Medium` in `Settings > Appearance > Size of list items` but I do not guarantee the result.

**Comment by zveber** [comment]
Yes,  I've meant `Setting > Display > Text Size`. As I see you can set any size there but it doesn't affect on entry list.

**Comment by J-Jamet** [comment]
Fixed in version 2.9.1 tell me if it's ok. ;)

**Comment by zveber** [comment]
It's ok now. Thanks for fix.
