### ISSUE TITLE
Autofill in Safari

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#776]
With safari on android 10 is not appearing the popup to fill or save the fields, safari is version 12.1.4.3, using it on a Samsung s20 FE 5g. With chrome works fine. Tried to delete cache /data on safari and on your app but no luck

(From Simone)

**Comment by J-Jamet** [comment]
No official Safari package was found.

**Comment by hokonch** [comment]
Guessing from the version 12.1.4.3, safari maybe means Samsung Internet.
Releted: https://github.com/Kunzisoft/KeePassDX/issues/769#issuecomment-721037264

**Comment by J-Jamet** [comment]
Yes it was a user error but the compatibility mode for Samsung browsers is already added.

```
<compatibility-package
    android:name="com.sec.android.app.sbrowser"
    android:maxLongVersionCode="10000000000"/>
<compatibility-package
    android:name="com.sec.android.app.sbrowser.beta"
    android:maxLongVersionCode="10000000000"/>
```
