### ISSUE TITLE
Swipe away the "Database opened" notification to lock it.

### ISSUE THREAD

**Issue by SpazMahTazz** [Kunzisoft/KeePassDX#777]
This used to be possible a while ago, I don't remember the version though but it was early 2020.
Currently the notification stays pinned and you can't swipe it away, but you can press the lock option it has. Would love to see swipe to lock come back as an option in the settings if possible.

**Comment by J-Jamet** [comment]
I would like to keep this functionality but I cannot. This notification is part of a [foreground service](https://developer.android.com/guide/components/foreground-services) (which was not the case before but necessary to keep a link to an open database) and Android does not allow you to close a notification in this way. The code is however present.

https://github.com/Kunzisoft/KeePassDX/blob/1727633f5d71f0e292ef9e4cdc5d7cc0b481cc84/app/src/main/java/com/kunzisoft/keepass/notifications/DatabaseTaskNotificationService.kt#L293

https://stackoverflow.com/questions/12872204/how-to-cancel-a-foreground-service-from-using-the-notification-swipe-dismiss-o#35721582

**Comment by SpazMahTazz** [comment]
That's okay. Thanks for explaining it to me :)
