### ISSUE TITLE
Biometric authentication doesn't work with Paranoid

### ISSUE THREAD

**Issue by TobiPeterG** [Kunzisoft/KeePassDX#778]
Hello guys,

I own a rooted Xiaomi Mi 9, running Paranoid Android, based on Android 10.
I have the biometric authentication method enabled (using fingerprint or face unlock), but when I try to unlock the database with it, just nothing happens. I don't know if logcat/dmesg would help or if there're debugging files of the app itself.
Maybe someone else also already had that issue and knows a solution, but a quick search didn't show any related issues.

I hope you could help me, since it's otherweise a great app!

Thanks in advance!

**Comment by J-Jamet** [comment]
It is possible that the problem stems from the new biometric library added, still in beta.
Have you tried to:
 * Return to the previous screen, wait a few seconds before retrying the fingerprint reading
 * Delete the biometric key in the setting
 * Simply restart the device

If you can open the biometric prompt, there must be an unrecovered event behind it but i don't know where because it worked fine on my devices.

**Comment by J-Jamet** [comment]
Another hypothesis, it is quite possible that the new biometric API recognizes your device as insecure because it is rooted or that it uses an incompatible ROM.

**Comment by TobiPeterG** [comment]
> 
> 
> It is possible that the problem stems from the new biometric library added, still in beta.
> Have you tried to:
> 
>     * Return to the previous screen, wait a few seconds before retrying the fingerprint reading
> 
>     * Delete the biometric key in the setting
> 
>     * Simply restart the device
> 
> 
> If you can open the biometric prompt, there must be an unrecovered event behind it but i don't know where because it worked fine on my devices.

Hi, thanks for you fast reply!

I've tried all of the 3 methods you recommended to work around that, but none of them work unfortunately.
Neither fingerprint nor face unlock work, it recognizes me, but doesn't unlock the databse.

> 
> 
> Another hypothesis, it is quite possible that the new biometric API recognizes your device as insecure because it is rooted or that it uses an incompatible ROM.

That's an interesting idea I admit, but I don't think so since another app uses biometric authentication as well and it works just fine. Also, there's a system app locker which also works and unlocking my device with fingerprint and face unlock works as well without issues.

You mentioned that the integration of the new libs are still in beta.
Do you mean that it's in the beta channel of the app or in beta state in general?
I don't use the beta branch for the app, should I switch to it?

**Comment by J-Jamet** [comment]
> That's an interesting idea I admit, but I don't think so since another app uses biometric authentication as well and it works just fine. Also, there's a system app locker which also works and unlocking my device with fingerprint and face unlock works as well without issues.

In this case, it is necessary to compare the biometric applications which use an internal keystore. Otherwise it can work because there is no need to recover an encrypted key. Does it work with an older version of [KeePassDX (2.8.7)](https://github.com/Kunzisoft/KeePassDX/releases/tag/2.8.7)? 

> Do you mean that it's in the beta channel of the app or in beta state in general?

It's simply the biometric api in beta ->  https://developer.android.com/jetpack/androidx/releases/biometric

- Biometric 1.0.1 in KeePassDX 2.8.7
- Biometric 1.1.0-beta01 in KeePassDX 2.9.1

**Comment by TobiPeterG** [comment]
> 
> 
> > That's an interesting idea I admit, but I don't think so since another app uses biometric authentication as well and it works just fine. Also, there's a system app locker which also works and unlocking my device with fingerprint and face unlock works as well without issues.
> 
> In this case, it is necessary to compare the biometric applications which use an internal keystore. Otherwise it can work because there is no need to recover an encrypted key. Does it work with an older version of [KeePassDX (2.8.7)](https://github.com/Kunzisoft/KeePassDX/releases/tag/2.8.7)?
> 
> > Do you mean that it's in the beta channel of the app or in beta state in general?
> 
> It's simply the biometric api in beta -> https://developer.android.com/jetpack/androidx/releases/biometric
> 
>     * Biometric 1.0.1 in KeePassDX 2.8.7
> 
>     * Biometric 1.1.0-beta01 in KeePassDX 2.9.1

I tried 2.8.7, it doesn't work there either, so the new lib doesn't seem to be the problem. O.o

**Comment by J-Jamet** [comment]
Okay, in this case I think the keystore can't be used properly.
Does it work with KeePassDroid or KeePass2Android?

**Comment by TobiPeterG** [comment]
> 
> 
> Okay, in this case I think the keystore can't be used properly.
> Does it work with KeePassDroid or KeePass2Android?

Ok, I think keystore is really the problem, I tried keepas2android and it showed an error message that the key couldn't be saved.
KeePassDroid just showed the error message "biometric error".

So there seems to be a general problem with biometric authentication with keepass applications. :D

**Comment by J-Jamet** [comment]
Yes, and more generally with applications that require storing secure keys. Unfortunately I can not do anything at this level, you have to look in detail why your ROM does not accept to manage the keystore.

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/215

**Comment by TobiPeterG** [comment]
Okay, thank you, I still wonder though why another app works flawlessly. O.o

**Comment by J-Jamet** [comment]
Which one?

**Comment by unresolvedsymbol** [comment]
I was having this issue on PA Quartz 5 as well. It may come from the Android upstreaming because it was also broken on a mostly AOSP Android 11 ROM as well pre 2.9.2. I suggest you try the new version. (Sadly I can't because my PA dualboot partitions data is corrupt)

**Comment by TobiPeterG** [comment]
> 
> 
> I was having this issue on PA Quartz 5 as well. It may come from the Android upstreaming because it was also broken on a mostly AOSP Android 11 ROM as well pre 2.9.2. I suggest you try the new version. (Sadly I can't because my PA dualboot partitions data is corrupt)

Hey, thanks for testing!
I've asked the ROM maintainer who said that the issue was face unlock, since it's not possible to save the face, fingerprint unlock though should work fine.

**Comment by TobiPeterG** [comment]
> 
> 
> Which one?

Uh sorry, I overlooked your answer.
Traderepublic works without problems, instead of having to enter a PIN the biometric authentication works.

**Comment by J-Jamet** [comment]
Traderepublic seems to be an online application that transmits connection info, no source code available, it must not use the phone keystore.

**Comment by J-Jamet** [comment]
I completely refactored biometric recognition in version 2.9.5, tell me if that solves the problem?

**Comment by TobiPeterG** [comment]
> I completely refactored biometric recognition in version 2.9.5, tell me if that solves the problem?

Wow, thank you very much!
The biometric option still doesn't work, but using the device credentials unlock method works without problem!

Thank you very much!

Maybe the device credential option should be the default one to provide a better out of the box experience?

**Comment by J-Jamet** [comment]
> Maybe the device credential option should be the default one to provide a better out of the box experience?

This is already the case, if the program detects that the device is not compatible with biometric recognition but here it seems not to detect it, I do not know why. In any case, I'm happy that you are satisfied with the new functionality.
