### ISSUE TITLE
Separate icon for FDroid / libre

### ISSUE THREAD

**Issue by justintime4tea** [Kunzisoft/KeePassDX#78]
Since both the Google and FDroid versions can be installed simultaneously it would be helpful for users who do install both to be able to differentiate between the two. This is probably an edge case but I noticed someone mention this in comment of another issue. Perhaps the default "theme" could also reflect this difference so while in the app you know which version you are in.

**Comment by J-Jamet** [comment]
Yes I agree, I thought put different colors for the default theme and the icon:
- Libre: blue
- Free: green
- Pro: purple (to reflect my company)

What do you think about it ?

**Comment by justintime4tea** [comment]
That sounds good! Probably easy to do with flavors, yes? I have only started looking at flavors.

**Comment by J-Jamet** [comment]
Normally yes, I have never used several main icons for an app, but it must be OK. https://stackoverflow.com/questions/22875948/how-to-provide-different-android-app-icons-for-different-gradle-buildtypes

**Comment by justintime4tea** [comment]
Looks like you can do with flavors too:
https://ptyagicodecamp.github.io/how-did-i-set-up-multiple-flavors-for-an-android-app-under-5-minutes.html
