### ISSUE TITLE
Save from selection mode destroys the otp field

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#781]
**Describe the bug**
This will be dangerous if database history is disabled.

**To Reproduce**
1. Set up one-time password for an entry 
2. Tap `Sign in with KeePassDX` in your browser to enter selection mode
3. Select the entry and save the URL
4. You can see the otp field has been deleted and the OTP Token field with blank field value has appeared

**Comment by J-Jamet** [comment]
The problem was with a simple default parameter.
