### ISSUE TITLE
Biometric authentication not working 

### ISSUE THREAD

**Issue by Asherathe** [Kunzisoft/KeePassDX#786]
After updating to KeePassDX version 2.9.1 via f-droid, biometric authentication no longer works on my Samsung Galaxy s6 edge+.  My phone isn't rooted, and everything is stock. When I try to open the database, it says, "No biometric or device credential is enrolled." It was working perfectly before the update. I tried creating a new fingerprint, but it didn't make any difference.

**Comment by J-Jamet** [comment]
This probably comes from the new biometric API. For my part, it worked when restarting the phone. Did you try?
Otherwise it is possible that the phone is no longer recognized as a device with sufficient security to store the key.

**Comment by J-Jamet** [comment]
I upgraded the version of the biometric library in KeePassDX 2.9.2, you will tell me if corrects the problem.

**Comment by unresolvedsymbol** [comment]
Can confirm 2.9.2 fixed the prompt not showing on Android 11.
