### ISSUE TITLE
Can it support WebDav or SFtp or Ftp

### ISSUE THREAD

**Issue by kamitryant** [Kunzisoft/KeePassDX#787]
Local file synchronization is prone to version coverage issues

**Comment by J-Jamet** [comment]
> Can it support WebDav or SFtp or Ftp

The topic has been explained many times and a wiki is available. https://github.com/Kunzisoft/KeePassDX/wiki

The version of KeePassDX does not change the way it uses SAF.

If you are talking about a third party file manager application, you should check the behavior with the developers of the relevant file manager.
