### ISSUE TITLE
 Harmonization of field names

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#789]
Change `WebDomain` by `URL`
Change `ApplicationId` by `AndroidApp`

Linked to https://github.com/keepassxreboot/keepassxc/issues/4317#issuecomment-729638444

**Comment by Ilithy** [comment]
Hello, field harmonization is a great idea, of course, but if you replace ApplicationId by AndroidApp, it won't impact the use of the database on a device under a different OS?

The question may be silly, but I ask myself, sorry and thank you.

**Comment by J-Jamet** [comment]
Normally no, I change the nomenclature because it will separate the iOS and Android applications to make dynamic links (and will be the same as KP2A). But research is still being done on all fields.

**Comment by Ilithy** [comment]
Thank you for the explanation
