### ISSUE TITLE
Can not use search to find text in note

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#790]
English is find
but other language not work (maybe chinese)

(from jelly)

**Comment by Ilithy** [comment]
Hi;

For my part, if I search for a text contained in a note field works perfectly (tested on several entries).
Using the latest version of KeepassDX Pro (2.9.1) on an Android version 10.

Thank you.

**Comment by J-Jamet** [comment]
I cannot reproduce the problem either. If anyone can reproduce it, please indicate all the configuration.

**Comment by J-Jamet** [comment]
No reproduction possible for the moment. I close the issue, if anyone has the problem and describes how to reproduce it I will reopen.
