### ISSUE TITLE
Autofill maximal displayed entries.

### ISSUE THREAD

**Issue by gihucom** [Kunzisoft/KeePassDX#793]
Is there a limit of 6 entries maximal shown on autofill popup for each website.
I have 7 entries but only 6 are shown.
Is this normal behaviour for free f-droid version and i have to buy pro version to see more than 6 entries or is this an issue?

Thank you

**Comment by J-Jamet** [comment]
This is only a maximum value that I found reasonable for display. I will be able to increase the value but I do not see in which case there is need for more than 6 different credentials for the same service. Enlighten me.

**Comment by Ilithy** [comment]
Hi; 
It might be interesting to add an option to allow the user to select the maximum number of entries visible during an autofill search, this would be useful for users with a large password bank and/or when using on a large screen (tablet, remote screen, TV etc), where the display space is not necessarily problematic. Thank you.

**Comment by J-Jamet** [comment]
I am not going to add an option for this as it is an arbitrary data of technical limitation.

> this would be useful for users with a large password bank and/or when using on a large screen (tablet, remote screen, TV etc)

There is no direct relationship with the number of items displayed and the number of characters in the item.
