### ISSUE TITLE
Updating credentials for an entry with Autofill deletes OTP information for that entry

### ISSUE THREAD

**Issue by unilock** [Kunzisoft/KeePassDX#798]
**Describe the bug**
Updating credentials for an entry with Autofill deletes OTP information for that entry.

**To Reproduce**
1. Enable Autofill service.
2. Create an entry with username, password, and TOTP information.
3. Log in to any given app *without* using Autofill service. When prompted, save credentials to the previously created entry.
4. Username and password are updated, but TOTP information disappears.

**Expected behavior**
The entry's username and password would be updated, and the TOTP information would remain intact.

**KeePass Database**
 - Created with: KeePass2 for Windows (version unknown)
 - Version: KeePass 2 - KDBX4.0
 - Location: Remote file retrieved with Nextcloud app
 - Size: 11 KB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.9.2
 - Build: Libre
 - Language: English

**Android (please complete the following information):**
 - Device: Google Pixel 2 XL
 - Version: GrapheneOS RP1A.201105.002.2020.11.07.00 (Android 11)

**Additional context**
 - This may only occur when the OTP information is first created with KeePassXC or some other client (not KeePassDX); I'm not sure if I've tested otherwise, as I believe all of my OTP entries were originally created with KeePass2 / KeePassDX for Windows.

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/781

It's really weird, I'm almost sure I fixed this bug. And I can't reproduce the problem on version 2.9.2 on my side.
Are you sure you haven't tested with an old version and see the bug only now? (because 2.6.2 does not exist)
If the OTP is created with another application nothing should change. Unless you are using a specific plugin that adds information.

**Comment by unilock** [comment]
You're right; I did mean 2.9.2. Edited.
And it looks like it *is* fixed now. My bad for not testing more recently.
Notably, when linking an entry to an Android app, the created field under the entry is now named "AndroidApp" rather than "ApplicationID".
Thanks!
