### ISSUE TITLE
Questions about pro keys

### ISSUE THREAD

**Issue by Ilithy** [Kunzisoft/KeePassDX#802]
Hi,
I "bought" KeepassDX Pro on the Play Store,
but I'd rather use the version available on Github, and apply my pro key to it.

1: Is it possible for you to provide a Pro key that can be used on the Github/F-Droid version once you have purchased the pro version from the Play Store?

2: If it is possible, how many devices can I use this Pro key on?
(Outside the Google play version of course)

3: If this is not possible, will you be able to make the pro version available outside the Play Store in the future?

4: (a little off topic) for monthly donations, is it possible for you to provide bank details, or do we have to do this through PayPal?

I looked at the FAQ beforehand, but it only talks about the Pro version available on the Play Store, and not about the use of the Pro version outside the one after the purchase on the P.S, I preferred to ask the question here, in case I'm not the only one wondering about it.

Thanks a lot.

**Comment by J-Jamet** [comment]
The Play Store manages users who have purchased the pro version directly from its platform, it's automatic. Keep in mind that the pro version is only to help me and that it doesn't contain any extra features (contains only visual elements, completely optional).

> I "bought" KeepassDX Pro on the Play Store,

Thank you for the contribution ;)

> but I'd rather use the version available on Github, and apply my pro key to it.

I don't know what you call the pro key. If you have a certificate, you can use it to compile the app.

1. No, I don't even know what you call a pro key. On github, there are the sources. For the F-Droid version, I can provide the procedure of the themes if requested individually.

2: There is no pro key.

3: Maybe in other stores, such as Amazon or Samsung, in the future, why not.

4: I have not yet set out a direct bank details for donations. For the moment it's Paypal but I'm looking to add other means.

> and not about the use of the Pro version outside the one after the purchase on the P.S

It's normal, this version is only available on the Play Store and helps me with contributions. Later, I would like to integrate icons of services that are not free. And I won't pollute the libre version with these elements.

**Comment by Ilithy** [comment]
Okay, thank you for the clarifications.

**Comment by J-Jamet** [comment]
This is normal, I understand that this is confusing, I just didn't want to integrate an in-app purchase into the APKs of the playstore but it multiplies the number of versions.

**Comment by Ilithy** [comment]
:pensive:

**Comment by J-Jamet** [comment]
(I haven't seen your changes)

> So the Google play version is the only one to have TOTP Steam?

This is the only version that allows you to select it from the list to create a TOTP because it is not a standardized service. But you can read TOTP very well on all versions.

> Can I send you an email to get the manipulation to access the themes in the Github/F-Droid version?

Yes of course it will be with pleasure

**Comment by J-Jamet** [comment]
I don't want to promote services and visuals that are not standardized or not under free license. Steam implemented its own TOTP system with a different algorithm that I implemented manually differently, it confuses everything and I am against this kind of practice.
That's why I also created the Pro version, users want these non-standardized features but it takes a lot more of my free time in design and development.

**Comment by Ilithy** [comment]
Yes I understand better now, thanks for the explanations, and for the time wasted to give them to me. You have a lot of constraints, and so a lot more development work; I wonder, you answered me, it's very nice of you, anyway your Android version of Keepass is by far the best, so I'm not complaining 😉

PS: thanks, I will send you an email shortly.

Good luck and thank you for your work.
