### ISSUE TITLE
biometric

### ISSUE THREAD

**Issue by Sergei-Alekseev** [Kunzisoft/KeePassDX#805]
"biometric prompt is supported, but not set up"
pressing fingerprint button opens "security & locations" system settings page. thats all.
how to set up?
device is redmi 5 plus, android 8.1, miui 11

**Comment by J-Jamet** [comment]
Seriously? I am asked to provide manufacturer support on behalf of Xiaomi?
Not finding a device configuration has never been a bug. Please refer to the manufacturer's manual. I'm nice, but you shouldn't overdo it.

https://www.youtube.com/watch?v=zNUx5gWbtr4

**Comment by J-Jamet** [comment]
Sorry, I'm at my end right now. I will point to ACTION_BIOMETRIC_ENROLL for the next update.

**Comment by J-Jamet** [comment]
ACTION_BIOMETRIC_ENROLL and ACTION_FINGERPRINT_ENROLL does not work correctly on Xiaomi because the settings have been modified by MIUI. 
There is a system crash (not even in KeePassDX) when there is no longer credential device.
Another argument for not using this modified version of Android.
