### ISSUE TITLE
Database cannot be opened when using SyncThing

### ISSUE THREAD

**Issue by unresolvedsymbol** [Kunzisoft/KeePassDX#806]
**Describe the bug**
I'm no longer able to open the database on my desktop after the database is modified in app, the error "Invalid inner header id size" shows.

**To Reproduce**
1. Modify the database in app (add entry etc)
2. Sync across to computer running KeepassXC
3. Attempt to enter credentials

**Expected behavior**
The database should be readable by other apps within the Keepass 2 spec.

**KeePass Database**
 - Created with: Linux KeepassXC
 - Version: 2.6.2
 - Location: File under synchronization with SyncThing, hashes verified between the one that is readable on phone and unreadable on laptop.
 - Size: 16K
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.9.2
 - Build: F-Droid
 - Language: English

**Android (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Version: Android 11 (RevengeOS 4)

**Comment by J-Jamet** [comment]
Did you close the database before synchronization?

**Comment by unresolvedsymbol** [comment]
Yes, saved, locked, and closed app.

**Comment by J-Jamet** [comment]
This error indicates that the header of the file cannot even be read properly so it is possible that the file was not fully formatted (maybe a stream stopped while sending data). 
I haven't tested SyncThing, but had no problem making manual copies.

**Comment by J-Jamet** [comment]
Can you still open the file correctly on KeePassDX? What about KeePass2 and KeePass2Android?

**Comment by unresolvedsymbol** [comment]
As I noted under database location, I verified the MD5s match between the one on my phone and laptop.

**Comment by J-Jamet** [comment]
You mean changing it doesn't make a different MD5? This is really weird.

**Comment by unresolvedsymbol** [comment]
I didn't change it, just open and close the database on the app, same one that can't be read by KeepassXC or gnome-passwordsafe that I just tested, it freezes loading after trying to unlock it.

**Comment by unresolvedsymbol** [comment]
![image](https://user-images.githubusercontent.com/48220091/101283843-ae187480-37a2-11eb-9351-9905fbce546d.png)
And Keepass2 on Linux

**Comment by J-Jamet** [comment]
Can you remake a database (with no real information) with this same behavior so that I can debug it?

**Comment by J-Jamet** [comment]
KeePassX is no longer maintained but I think there will be more information if you try with the official app.

**Comment by unresolvedsymbol** [comment]
It may prove a challenge to create a test database, my real database that this has happened with for the third time has almost 100 entries.

**Comment by J-Jamet** [comment]
Okay, that would be very helpful. If this has happened to you several times, do you know exactly what the condition of the problem was? Adding an entry or an attachment in a particular location?  If your database is old, it is also possible that there are entries without group. Or maybe attachments that didn't attach properly. I'm trying to understand because I did not notify any concerns in my tests and these are the issues to be resolved first.

**Comment by J-Jamet** [comment]
The problem can also simply come from SyncThink, it is necessary to check if in certain cases, the file is not truncated. I haven't studied this app at all, so I don't know how it works internally.

**Comment by J-Jamet** [comment]
> Interestingly, it fixed itself after about 5 minutes without doing anything.

In this case it is pretty sure that SyncThing just hadn't finished fetching the whole file and delivering it to the URI stream.
I can improve the data change detection behavior #794 but otherwise just wait for SyncThing to finish syncing the files.

**Comment by jjakob** [comment]
I don't think #794 will fix this issue, as the problem is with XC reading the file after being saved in DX (so the file on Android is correct but on the other side of Syncthing - Linux - it's not). Possibly improvements when saving the file (flushing the file data stream when saving?) would make a change, if the file is still being held open for writing, or maybe just part of the file is saved immediately, and the rest is being held in a buffer somewhere not flushed to disk until after a timeout?

**Comment by J-Jamet** [comment]
>  Possibly improvements when saving the file (flushing the file data stream when saving?) would make a change, if the file is still being held open for writing, or maybe just part of the file is saved immediately, and the rest is being held in a buffer somewhere not flushed to disk until after a timeout?

I have no idea how SyncThing works, I will try to flush the OutputStream when I test the #794 feature. But there is no reason, the writing is done at once, the stream is opened and closed during a save.

If you want to test on your side, the code is here: https://github.com/Kunzisoft/KeePassDX/blob/0761d356b8f2a0911c400932d5a2642bf5d7217a/app/src/main/java/com/kunzisoft/keepass/database/element/Database.kt#L520
