### ISSUE TITLE
Latest updated messed up biometric on Android 11

### ISSUE THREAD

**Issue by auanasgheps** [Kunzisoft/KeePassDX#812]
**Describe the bug**
Following #779, on my OnePlus 8T running Android 11 lost the ability to unlock with fingerprint.

First of all the transition to the new system was quite messed - I didn't get advanced unlock and got the message "could not access credentials" or something similar. I had to go to KPDX Settings and clear keys to make it kinda _working_

Not really working though, because I am only prompted for the device PIN and not fingerprint. 

However, If in settings I disable "Device Credential Unlocking", I regain fingerprint unlock, so there's something wrong with the new method.

I understand you may not have an Android 11 device as they're very new. I am available If you need to test stuff.

**To Reproduce**
1. Upgrade KPDX to 2.9.3 on OnePlus 8T
2. Unlock a database
3. Only prompted for device PIN and not fingerprint

**Expected behavior**
I am expecting fingerprint to be available just as before.

** Keepass Database **
- Created with: oh man I can't remember it's an old DB
- Version: KDBX 3.1
- Location: Remote File on Google Drive, but retrieved via the system File Manager
- Size: 500 Kb
- Contains attachment: I don't think so

**KeePassDX (please complete the following information):**
 - Version: 2.9.3
 - Build: Free
 - Language: Italian

**Android (please complete the following information):**
 - Device: OnePlus 8T
 - Version: 11

**Additional context**
- Fingerprint unlock was working before the update

**Comment by J-Jamet** [comment]
> First of all the transition to the new system was quite messed - I didn't get advanced unlock and got the message "could not access credentials" or something similar. I had to go to KPDX Settings and clear keys to make it kinda working
Not really working though, because I am only prompted for the device PIN and not fingerprint.

Indeed, there is a problem in the configuration of the settings (simply a bad condition) if you had selected Biometric before the update.
As you say, just deselecting _"device credential unlocking" fixes the issue._
I am correcting it for the next update.

**Comment by auanasgheps** [comment]
My question is: disabling the option is a workaround or a fix? Because in theory it would disable the new feature? It doesn't bother me, though.

**Comment by J-Jamet** [comment]
Normally there is only one available option at a time. But if you upgrade with biometric enabled, there is a bug that displays both options at the same time (which shouldn't happen). I will try to solve this problem by leaving only biometric activated if it was activated before the update or put the device credential by default if it is a new installation.

**Comment by J-Jamet** [comment]
I will reset the value to the default "true" when everyone has already upgraded in one or two versions (the variable will then be available and no longer the default).

**Comment by auanasgheps** [comment]
Thanks for the explanation and the quick action
