### ISSUE TITLE
Show last modification date of the database

### ISSUE THREAD

**Issue by afpp-l** [Kunzisoft/KeePassDX#816]
Long story short. If there's an easy way to show the last modification date of a currently open database, I'd like to ask you to add it in any shape or form. An option in the upper right corner menu would be nice.
Sometimes when I fill in pass on sites they give me "wrong password", so knowing if my database is stale or not is helpful in such cases. I know that I can see the date in a file manager. But having the date at hand is more convenient. Thank you.

**Comment by Ilithy** [comment]
Hello, 

>If there's an easy way to show the last modification date of a currently open database

**it's already the case**  (and it's really nice by the way),
on the database selection screen is displayed, for each one:
The size
The location
The date of last modification
Time of last modification

It's absolutely perfect 😍, you just need to know where to look ;-)

 To access the selection screen: When opening KeepassDX, you must refuse the auto connection _(click anywhere on the screen)_ , and return to the database selection screen _(Back arrow in the top left corner of the screen)_ , On the right, for each database, just click on the expansion arrow, and all this data can be viewed. 

Have a nice day
