### ISSUE TITLE
Database not opening

### ISSUE THREAD

**Issue by carallo** [Kunzisoft/KeePassDX#820]
Hi @J-Jamet , sorry for bothering again! 🤦‍♂️

I was trying the latest 2.9.5 build from github and I couldn't load my database. The app just goes back to main screen and, trying again, it crashes.
I've tried making a new database from within the app and it works, but then, if I edit it from my laptop with keepassXC,  it doesn't work anymore. I have the 2.9.4 fdroid version alongside and it seem to not have any issues.
Also, I THINK, this happens only if I use a key file, but I'm not sure, I need to do more testing.

I've tried to get a log of the crash, I'm not sure it's the right one since it's night and I'm on the phone, I will check better tomorrow, but I'll paste it here in case.
Thank you so much again and look into this with no rush 😉

`12-18 01:28:19.945 W/ActionModeController(10694): Tried to finish a null action mode.
12-18 01:28:19.945 D/DocumentStack(10694): Root changed to: Root{authority=com.android.externalstorage.documents, rootId=primary, title=FP2, isUsb=false, isSd=false, isMtp=false} @ content://com.android.externalstorage.documents/root/primary
12-18 01:28:19.963 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:19.964 D/DocumentStack(10694): Adding doc to stack: DocumentInfo{docId=primary:, name=0, mimeType=vnd.android.document/directory, isContainer=true, isDirectory=true, isArchive=false, isInArchive=false, isPartial=false, isVirtual=false, isDeleteSupported=true, isCreateSupported=true, isRenameSupported=true, isMetadataSupported=false} @ content://com.android.externalstorage.documents/document/primary%3A
12-18 01:28:19.964 D/DirectoryFragment(10694): Showing directory: content://com.android.externalstorage.documents/document/primary%3A
12-18 01:28:19.964 D/DirectoryFragment(10694): Creating new fragment for directory: content://com.android.externalstorage.documents/document/primary%3A
12-18 01:28:20.012 D/DirectoryFragment(10694): Received model update. Loading=false
12-18 01:28:20.015 D/AbstractActionHandler(10694): Creating new directory loader for: content://com.android.externalstorage.documents/document/primary%3A
12-18 01:28:20.086 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:20.086 D/AbstractActionHandler(10694): Loader has finished for: content://com.android.externalstorage.documents/document/primary%3A
12-18 01:28:20.086 I/Model   (10694): Updating model with new result set.
12-18 01:28:20.088 D/DirectoryFragment(10694): Received model update. Loading=false
12-18 01:28:22.990 D/PickerActionHandler(10694): onFinished() [content://com.android.externalstorage.documents/document/primary%3AAzz!.key]
12-18 01:28:23.004 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.053 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.068 D/DocumentsStorageProvider(10266): queryDocument(), id=-1652766488/440
12-18 01:28:23.069 W/Adreno-EGL(11544): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-18 01:28:23.071 D/vndksupport(11544): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
12-18 01:28:23.087 D/DocumentsStorageProvider(10266): queryDocument(), id=-1652766488/440
12-18 01:28:23.107 D/DocumentsStorageProvider(10266): queryDocument(), id=-1652766488/440
12-18 01:28:23.139 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.143 D/NetworkManagement( 2091): oldRule = 0, newRule=0 for uid=10178 on chain 2
12-18 01:28:23.144 D/NetworkManagement( 2091): !!!!! Skipping change
12-18 01:28:23.146 D/DocumentsStorageProvider(10266): queryDocument(), id=-1652766488/440
12-18 01:28:23.161 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.163 D/NetworkManagement( 2091): oldRule = 0, newRule=0 for uid=10178 on chain 2
12-18 01:28:23.163 D/NetworkManagement( 2091): !!!!! Skipping change
12-18 01:28:23.168 D/DocumentsStorageProvider(10266): queryDocument(), id=-1652766488/440
12-18 01:28:23.178 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.202 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.565 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.566 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:23.688 I/LatinIME( 4870): Starting input. Cursor position = 0,0
12-18 01:28:23.742 W/Adreno-EGL( 4870): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-18 01:28:23.748 D/vndksupport( 4870): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
12-18 01:28:24.816 I/keystore(  484): 1 0
12-18 01:28:26.407 D/AndroidRuntime(11544): Shutting down VM
12-18 01:28:26.410 E/AndroidRuntime(11544): FATAL EXCEPTION: main
12-18 01:28:26.410 E/AndroidRuntime(11544): Process: com.kunzisoft.keepass.free, PID: 11544
12-18 01:28:26.410 E/AndroidRuntime(11544): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-18 01:28:26.410 E/AndroidRuntime(11544): Caused by: java.lang.reflect.InvocationTargetException
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at java.lang.reflect.Method.invoke(Native Method)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	... 1 more
12-18 01:28:26.410 E/AndroidRuntime(11544): Caused by: com.kunzisoft.keepass.database.exception.IODatabaseException
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.biometric.AdvancedUnlockFragment.selectMode(AdvancedUnlockFragment.kt:240)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.biometric.AdvancedUnlockFragment.checkUnlockAvailability(AdvancedUnlockFragment.kt:204)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity$onCreate$4.onCheckedChanged(PasswordActivity.kt:182)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity.populatePasswordTextView(PasswordActivity.kt:451)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity.clearCredentialsViews(PasswordActivity.kt:441)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity.clearCredentialsViews$default(PasswordActivity.kt:440)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity.loadDatabase(PasswordActivity.kt:521)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity.verifyCheckboxesAndLoadDatabase(PasswordActivity.kt:502)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity.verifyCheckboxesAndLoadDatabase(PasswordActivity.kt:494)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity.verifyCheckboxesAndLoadDatabase$default(PasswordActivity.kt:491)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.kunzisoft.keepass.activities.PasswordActivity$onEditorActionListener$1.onEditorAction(PasswordActivity.kt:357)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at android.widget.TextView.onEditorAction(TextView.java:6282)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at android.os.Looper.loop(Looper.java:193)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-18 01:28:26.410 E/AndroidRuntime(11544): 	... 3 more
12-18 01:28:26.412 I/LatinIME( 4870): Starting input. Cursor position = 5,5
12-18 01:28:27.230 W/ActivityManager( 2091):   Force finishing activity com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.PasswordActivity
12-18 01:28:27.235 I/Process (11544): Sending signal. PID: 11544 SIG: 9
12-18 01:28:27.252 I/ActivityManager( 2091): Process com.kunzisoft.keepass.free (pid 11544) has died: vis  TOP 
12-18 01:28:27.253 W/libprocessgroup( 2091): kill(-11544, 9) failed: No such process
12-18 01:28:27.253 W/InputDispatcher( 2091): channel 'f566cd0 com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-18 01:28:27.253 E/InputDispatcher( 2091): channel 'f566cd0 com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-18 01:28:27.254 I/WindowManager( 2091): WIN DEATH: Window{f566cd0 u0 com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity}
12-18 01:28:27.254 W/InputDispatcher( 2091): Attempted to unregister already unregistered input channel 'f566cd0 com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity (server)'
12-18 01:28:27.258 I/WindowManager( 2091): WIN DEATH: Window{a152b3e u0 com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.PasswordActivity}
12-18 01:28:27.264 W/SurfaceFlinger(  374): Attempting to set client state on removed layer: com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.PasswordActivity#0
12-18 01:28:27.264 W/SurfaceFlinger(  374): Attempting to destroy on removed layer: com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.PasswordActivity#0
12-18 01:28:27.269 I/Zygote  (  271): Process 11544 exited due to signal (9)
12-18 01:28:27.286 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode
12-18 01:28:27.289 W/ActivityManager( 2091): setHasOverlayUi called on <private info omitted> pid: 11544
12-18 01:28:27.298 W/libprocessgroup( 2091): kill(-11544, 9) failed: No such process
12-18 01:28:27.298 I/libprocessgroup( 2091): Successfully killed process cgroup uid 10278 pid 11544 in 45ms
12-18 01:28:27.302 I/ActivityManager( 2091): Start proc 11782:com.kunzisoft.keepass.free/u0a278 for activity com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity
12-18 01:28:27.369 D/NetworkManagement( 2091): Uid 10091 restricted because of app standby mode`

**Comment by rogers1106** [comment]
Yep, same here. At first everything looks normal, but after selecting my keyfile the fingerprint icon changes to a striked out keypass icon and I have to reselect the database again.

**Comment by J-Jamet** [comment]
Indeed it is annoying, I did not see this bug, it comes from the new biometric system. I had however put the application in beta but I have not had any feedback until now. I will redo a version to correct this problem.

**Comment by carallo** [comment]
> Indeed it is annoying, I did not see this bug, it comes from the new biometric system. I had however put the application in beta but I have not had any feedback until now. I will redo a version to correct this problem.

I'm sorry for that! But please, take your time and sleep! 😉 And if you need some testing I can help you with that ;)

**Comment by J-Jamet** [comment]
It's not your fault, I could have been more vigilant, but it's true that I am tired. Fortunately it's morning at home! ^^

**Comment by J-Jamet** [comment]
[KeePassDX_2.9.5_Test_2020_12_18_10_01.zip](https://github.com/Kunzisoft/KeePassDX/files/5714692/KeePassDX_2.9.5_Test_2020_12_18_10_01.zip)

Tell me if this fix works for you? ;)

**Comment by rogers1106** [comment]
Jep, working. 👍


--
-= Roger Sondermann =-


________________________________
Von: Jérémy JAMET <notifications@github.com>
Gesendet: Freitag, 18. Dezember 2020 10:04
An: Kunzisoft/KeePassDX
Cc: Roger S.; Comment
Betreff: Re: [Kunzisoft/KeePassDX] Database not opening (#820) 

KeePassDX_2.9.5_Test_2020_12_18_10_01.zip
Tell me if this fix works for you? ;)

**Comment by J-Jamet** [comment]
Great, version 2.9.6 is available (soon on the stores)

**Comment by carallo** [comment]
> [KeePassDX_2.9.5_Test_2020_12_18_10_01.zip](https://github.com/Kunzisoft/KeePassDX/files/5714692/KeePassDX_2.9.5_Test_2020_12_18_10_01.zip)
> 
> Tell me if this fix works for you? ;)

Working flawlessly, amazing! 😎

> Great, version 2.9.6 is available (soon on the stores)

Thank you su much! I'm finally in the KeepassDX world, I hope I won't have to bother you again. 😜

Thank you thank you thank you!
