### ISSUE TITLE
Biometric Unlocking not working

### ISSUE THREAD

**Issue by GregCIA** [Kunzisoft/KeePassDX#822]
**Describe the bug**
1.Biometric Unlocking not working
2. Sign in
3. Settings
4. Advanced unlocking
5. Biometric unlocking is on but never had me validate my fingerprint. I have toggled the button on and off but it never allowse to use my finger print to unlock. 

**Expected behavior**
Fingerprint to open the database. 

**KeePass Database**
 - Created with: Windows KeePass 2.45
 - Version: 2.45
 - Location: Dropbox
 - Size: 154kb
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 2.94
 - Build: Libre
 - Language: English

**Android (please complete the following information):**
 - Device: Pixel 4a
 - Version: OS is CalyxOS

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
What is the error message displayed?

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking#errors

**Comment by J-Jamet** [comment]
Without an answer, I can only assume that the problem is with the custom ROM, as is often the case.
