### ISSUE TITLE
Remove storage permission.

### ISSUE THREAD

**Issue by Pranab009** [Kunzisoft/KeePassDX#823]
Run it without storage permission.
Save the password file inside the :
Android folder >>
Keepass dx >> password.
Many other password manager runs without storage permission.

**Comment by J-Jamet** [comment]
Indeed, I intended to do so. I am thinking of completely removing it from Android 29 and leaving it for the versions below because some users could not use their old managers without these permissions.
https://github.com/Kunzisoft/KeePassDX/issues/501

**Comment by J-Jamet** [comment]
If your file manager works without write permissions, feel free to turn them off in the current KeePassDX version.
It's only useful for older managers, as I explained above.

**Comment by Pranab009** [comment]
Thank you for your suggestion.
I try it.
