### ISSUE TITLE
Inline Autofill

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#827]
Integrate inline autofill directly into compatible keyboards.
Compatible from Android 11.
https://developer.android.com/guide/topics/text/ime-autofill

**Comment by auanasgheps** [comment]
Thanks for adding this feature in KeePass! I have an Android 11 device and I'll use this immediately.

**Comment by J-Jamet** [comment]
You're welcome, note that the popup may reappear from time to time if your system's autofill does not recognize suggestions correctly or is not fast enough.
