### ISSUE TITLE
Attachment can't be opened from KeyPassDX - Access violation

### ISSUE THREAD

**Issue by NKnuelle** [Kunzisoft/KeePassDX#837]
**Describe the bug**
I attached a PDF file to an KeePass entry in KeePassDX. If I want to open the PDF from within KeePassDX I get access violation errors in all tested PDF viewers. The error mentions access violations because the file is already opened in another program - but that's not the case. Only KeePassDX is used without any other program accessing the (temporary) attachment.

**To Reproduce**
1. Add PDF attachment to KeePass entry
2. Click on 'open'
3. Standard-App for opening PDF files should open up
4. App shows access violation error

**Expected behavior**
The PDF should open up in the defined PDF-Viewer without error

**KeePass Database**
 - Created with: KeePassXC / KeePassDX
 - Version: 2.6.2
 - Location: Local Filesystem
 - Size: 1,07MB
 - Contains attachment: Yes (PDF)

**KeePassDX (please complete the following information):**
 - Version: 2.6.2
 - Build: Free
 - Language: German

**Additional context**
OS: Windows 10
Tested PDF Viewers: Adobe Acrobat DC, Foxit Reader

**Comment by J-Jamet** [comment]
Version 2.6.2 does not exist.
KeePassDX is not able to open attached PDF files from the application. There is no `Open` button.

The attachment is saved to an external space and you can open it from an external file manager. Just tested with 2.9.8 and works.

**Comment by J-Jamet** [comment]
I think you got confused with KeePassXC, github for this project is [here](https://github.com/keepassxreboot/keepassxc).

**Comment by NKnuelle** [comment]
You're absolutely right. Sorry, I will open up my issue over there.
