### ISSUE TITLE
TOTP Doesn't work with database created from KeepassXC

### ISSUE THREAD

**Issue by antrys** [Kunzisoft/KeePassDX#838]
**Describe the bug**
TOTP codes generated do not work, when database is created with KeepassXC.
**To Reproduce**
1. Save your database on KeepassXC (Linux/Windows)
2. Open Database with KeePassDX (Android) (Database was copied from network share...so it's current.)
3. Copy/paste username/password and TOTP between apps. (In this case "PayPal Here" app on android)
4. TOTP is rejected.  However, if I type in the TOTP given by My KeePassXC into the android app, it works.

**Expected behavior**
Get a Valid TOTP code
**KeePass Database**
 - Created with: KeePassXC 2.6.2 Linux
 - Version: keepass 2 .kdbx
 - Location: Android local filesystem (freshly copied from network share)
 - Size: 330kb
 - Contains attachment: yes

**KeePassDX (please complete the following information):**
 - Version: 2.9.8
 - Build: Free
 - Language: US English
**Android (please complete the following information):**
 - Device: Galaxy A10e
 - Version: Android 10
**Additional context**
 - Browser for Autofill: N/A Paypal Here app.

**Comment by J-Jamet** [comment]
I just checked and the problem cannot be reproduced with a newly created database from KeePassXC.

![TOTP](https://user-images.githubusercontent.com/19224038/103683933-19fd2100-4f8b-11eb-8d1d-424a42a27a2a.jpg)

I advise you to check that the time has not expired and that your clocks are on time and synchronized.

**Comment by J-Jamet** [comment]
It may be related to https://github.com/Kunzisoft/KeePassDX/issues/848. 
If so, will be resolved in version 2.9.9.

**Comment by antrys** [comment]
Cool beans.   Thanks for the heads-up. Looking forward to trying it.  Yeah, my clocks were fine.
Thx.
