### ISSUE TITLE
Icon don't stay in edit screen

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#84]
The icon does not stay in the input edit screen when we switch to landscape.

**Comment by justintime4tea** [comment]
Check out constraint layout! It is the new prescribed method for consistent layout by Google and I love it. Just started using it with Welcome/FirstSetup. Was thinking of going through and updating layouts after the welcome stuff.

**Comment by J-Jamet** [comment]
The constraint layouts are very good but I do not understand how it solves the current problem. We just have to save the object in a bundle to find it in a savedinstancestate after an orientation change.

I know we have to redo many views, and we should have real models but the current problem remains the same with a constraint layout..

**Comment by justintime4tea** [comment]
Ah I see what you meant. I misunderstood, I thought the icon was moved out of view. I interpreted "not there" as not visible but still drawn with text.

**Comment by J-Jamet** [comment]
Ha ok, no worries, I did not understand it destabilized me. :rabbit: I solve the problem in the `feature/IconPackModules` branch and merge it into `develop` in the day.
