### ISSUE TITLE
WebDAV Support for bettter DB Management with NAS

### ISSUE THREAD

**Issue by mayank1470** [Kunzisoft/KeePassDX#843]
**Is your feature request related to a problem? Please describe.**
I would like to see that webdav client support is built into the app, as some users with zeal for open source software would prefere to be able to access their owncloud/nextcloud instance directly from the application and rather not go to their app and sync the files manually.

**Describe the solution you'd like**
I think it would be better to automatically sync the db from the nextcloud/owncloud webdav api rather than manual sync from the apps as user might not remember to sync always and as soon as there is an update from another device or laptop could lead to data loss. 

**Describe alternatives you've considered**
I have been using self hosted nextcloud instance and have my db files there. Every time I make a change in the password store I have to go and sync the files manually from the nextcloud application. It would be better if user is directly accessing the files using webdav api then to save a cache file locally and then whenever connection to instance is available to upload the db directly to the server eliminitaing the need of the manual sync that needs to be done at every change made using the app. Using android file manager to use the nextcloud link randomly gives error (Access to the file revoked by the file manager.)

**Additional context**
Don't have any

**Comment by mayank1470** [comment]
I am a developer myself and would like to contribute in any way I can if decided to implement this or some other feature that excites me :)

**Comment by J-Jamet** [comment]
There is already an open issue on the subject. As explained, I don't plan to integrate transfer protocols in KeePassDX because it is a file editor. But if you want to help for a dedicated application with a content provider, that would be great.

Linked to https://github.com/Kunzisoft/KeePassDX/issues/118

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/794
