### ISSUE TITLE
KeePassDX error unlocking with v2 keyfile, keyx

### ISSUE THREAD

**Issue by dhammel** [Kunzisoft/KeePassDX#844]
Hello,

Im not sure if this is a bug, or just not implemented yet but when my database was encrypted using new v2 keyx file, it just gave an error couldn't read credentials. Switching back to v1 key file, then it could unlock.

To my understanding, keepass can support any file as a key file and not just ones created with keepass, so why would there need to be support for a specific version of keyfile format? I would think it would only need keyfile support itself.

Thank you

**Comment by J-Jamet** [comment]
This is a new KeyFile format that have not yet been implemented. I have to do it, I just haven't had the time, sorry for that.
I'lll be trying to do this for version 2.9.9 of KeePassDX.

You can see the description of the formats in the Key file section of the KeePass website :
https://keepass.info/help/base/keys.html#keyfiles

Here is a copy of email I received from Dominik : 

> KeePass 2.47 will introduce version 2.0 of the XML key file format. The goal is to make it easier to create a backup of a key file on paper. Furthermore, there are changes in the user interface of KeePass that should encourage the correct use of key files. In detail, the following things have been added/changed:
> 
> * Enhanced XML key file format (added hash that allows to verify the integrity of the key; values are now encoded using hexadecimal characters in order to improve the readability).
> * Added command 'Print Key File Backup' (in 'File' -> 'Print').
> * In the dialog that asks whether to print an emergency sheet, there's now an option 'Also print a key file backup' (on Windows), if the master key contains a key file.
> * Added command 'Create Key File' (in 'Tools' -> 'Advanced Tools'), which shows a dialog for creating a new key file (random key) or for recreating a key file from a printed backup.
> * Changed default key file extension from 'key' to 'keyx'.
> * Key file dialogs now only show '*.keyx' and '*.key' files by default.
> * When clicking the key file 'Browse' button in the master key creation dialog and selecting a file that is not an XML key file, KeePass now asks whether to use the file as key file anyway.
> * Improved key file loading/saving error messages.
> 
> It would be great if you could add support for the new format in your port, too. To do this, check whether the format version (in the 'Meta' node) is 2.* and if so, parse the key in hexadecimal (ignoring any whitespace around and between the hexadecimal characters) and verify the hash, if present. The hash is stored in a 'Hash' attribute on the 'Data' node; the value is the hexadecimal encoding of the first 4 bytes of the SHA-256 hash of the key.

**Comment by dhammel** [comment]
Thank you, glad to hear.

Could you explain why it would need to be implemented, like as it supports ANY file to be used as a keyfile, i got curious why it specifically need support for a new version of xml keyfile. I knew argon2id would have to be implemented to be supported, but the way keyfiles as a whole works, i didn't think it would be an issue using it.

**Comment by J-Jamet** [comment]
In fact, there are two things:

1. There is a bug in the XML parser of the key file in KeePassDX, it is too basic, it doesn't check the XML version and recognizes some non-wanted characters (like space) that it encodes (when it shouldn't). https://github.com/Kunzisoft/KeePassDX/blob/d7052bd9e65516c8c34c658a314f7aea04a4de71/app/src/main/java/com/kunzisoft/keepass/database/element/database/DatabaseKDBX.kt#L400
This parser is called when it detects an XML key file, otherwise a hash of the complete file is made when it is another type of file.

2. Version 2 of XML implements a hash that is not yet read and will check the integrity of the XML key.

I am developing a better parser that will do better checks and won't bug anymore.

**Comment by dhammel** [comment]
I just updated KeePassDX to version 2.9.9 with states it has support for xml v2. Therefore, using official KeePass2 2.47 via mono on linux, I had changed the keyfile (keeping master password the same) to the v2 keyfile. Copied it over via usb to my device and tried unlocking with new keyfile v2, and password, it just mentioned error reading credentials. I then reversed it going back to .key and it worked again. Tried changing the credentials directly within KeePassDX to the new v2 keyfile and it worked fine (as well with any future unlocks), when syncthing database over to computer, official keepass errors unlocking it, invalid credentials. So it appears as if it is breaking compatability with any other keepass clients.

Know what may be up with this?

**Comment by J-Jamet** [comment]
OK, I didn't understand why you had this problem and I didn't.

I just understood, on my Linux, KeePass by default is version 2.41, I downloaded version 2.47 just to generate the .keyx key files in version 2 and then I wasn't paying attention, I was testing with my default version.

**But in fact it's not backwards compatible...**

So the .keyx format of version 2 is still recognized as version 1, only the hash is added in version 2 of the keys and I remove the spaces as indicated in the doc but it is no longer the same key format.

Sample keyx V1
```
<?xml version="1.0" encoding="utf-8"?>
<KeyFile>
	<Meta>
		<Version>1.00</Version>
	</Meta>
	<Key>
		<Data>5HesLUUyz11ohuW606nhsxag4tge4/ygsQPCJd765b0=</Data>
	</Key>
</KeyFile>
```

Sample keyx V2
```
<?xml version="1.0" encoding="utf-8"?>
<KeyFile>
	<Meta>
		<Version>2.0</Version>
	</Meta>
	<Key>
		<Data Hash="B469DFAB">
			B60F90FC 319596F9 10D5719C 7B236BA4
			9F18B805 4FCC0E07 229C7F8B 2FB02CED
		</Data>
	</Key>
</KeyFile>
```

I improved the parser which recognizes both formats, but is only compatible up to KeePass2.46.
So for the moment actually, it's not compatible with version 2.47 key files, sorry about that.

Can you test with previous versions of KeePass2 to tell me if it works for you?

**Comment by dhammel** [comment]
To be sure I understand correctly, Want me to test by generating a key v2 with KeePass2 2.47, use that to encrypt database on an earlier version of keepass (such as 2.46) and try unlocking database with KeePassDX?

**Comment by J-Jamet** [comment]
Yes, in order to verify that we have the same behavior, sorry to make you test weird things. :/

**Comment by dhammel** [comment]
No problem, just getting on my computer. Ill test very shortly and let you know

**Comment by dhammel** [comment]
Just finished testing, and yes Im having same behavior. If i use a keyx v2 with a database created/saved with version 2.46 it decrypts  successfully with KeePassDX. Also tested opening it with version 2.47 of KeePass, which fails.

So it does seem its not backwards compatible afterall

**Comment by J-Jamet** [comment]
Ok, I will make a version just for this problem. Once again sorry, I am doing my best to get the feature available quickly.

**Comment by dhammel** [comment]
Ok, thank you. But do take your time, were in no hurry.

**Comment by J-Jamet** [comment]
OK, the problem is normally resolved. If the key file hash is not correct, the database cannot be opened, so be careful of this point.

**Comment by dhammel** [comment]
Ok. When your mention of the keyfile hash, are you basically meanjng to be careful of not altering the contents of the keyfile, same as the official program warns of? Or is it something exclusive to KeePassDX?

**Comment by J-Jamet** [comment]
No it's the same behavior as KeePass2, it just prevents to open the base. It could be more lax because hash could simply be ignored. That's just why I'm notifying it.

**Comment by hokonch** [comment]
When the key and the hash do not match, I think KeePassDX should notify the user as an error message like KeePass and KeePassXC do.

**Comment by dhammel** [comment]
Ok, good to hear. Ill test the fix out sometime later in the day, and can report back if you'd like, otherwise you can close issue if you want. 

Thank you :)

**Comment by J-Jamet** [comment]
@hokonch Yes I am making a new exception.

@dhammel I will try to release the version today or tomorrow if it's ok.

**Comment by dhammel** [comment]
@J-Jamet Whenever your ready, if I want to test it before you make a release I could compile it myself I suppose, but I may just wait.

**Comment by J-Jamet** [comment]
@hokonch It's rather complicated to build a different exception with the current code, it requires refactoring so I'm going to open an other issue for that. I don't think I'll integrate it in the next version.

**Comment by dhammel** [comment]
I tested version 2.9.11 and it indeed is now working.

Thank you for quickly addressing this.
