### ISSUE TITLE
Attachments Format

### ISSUE THREAD

**Issue by giwrgosmant** [Kunzisoft/KeePassDX#846]
**Describe the bug**
My database contain in one entry an attachment .zip file. Whenever I try to export (save) this file in my device, it save it as <name>.zip.a format and I cannot use it.

**Expected behavior**
It should have the <name>.zip format.

**KeePass Database**
 - Created with: Windows KeePass v2.47

**KeePassDX (please complete the following information):**
 - Version: 2.9.8
 - Build: Free (Play Store)
 - Language: Greek

**Android (please complete the following information):**
 - Device: POCO F1
 - Version: 10.0

**Comment by J-Jamet** [comment]
I can't reproduce the problem.
The name of the file is managed by the app in charge of making the backup, in mine, the name to be saved is requested.
Maybe in yours the name already exists and adds the .a at the end.

**Comment by giwrgosmant** [comment]
> I can't reproduce the problem.
> The name of the file is managed by the app in charge of making the save. In mine, the name to be saved is requested.
> Maybe in yours the name already exists and adds the .a at the end.

You are right. I use MiXplorer File Manager and saved via it. I tried with stock and saving properly.
But I don't know why it has that behaviour. I tried with .png image which one other entry has as attachment and it's also add .a and change the format.
The name of the file does not already exists.

**Comment by J-Jamet** [comment]
I think this is a behavior of MiXplorer that allows you to differentiate between files uploaded by their content provider. But I don't know the reason for this, maybe it's a bug or it's intentional, you'd have to ask the creator.

**Comment by giwrgosmant** [comment]
I've reported to the xda thread of MiXplorer [here](https://forum.xda-developers.com/t/app-2-0-mixplorer-v6-x-released-fully-featured-file-manager.1523691/page-1730#post-84321663). Waiting answer from the dev, I will let you know, whenever he reply. In the meantime one guy looked at the logs but cannot figure out if keepassdx or mixplorer adds the .a extension in the file while "save" - "export".

**Comment by giwrgosmant** [comment]
It seems the issue was with MiXplorer.
Dev pushed an update in latest beta and told me to try it. It's working fine now.
