### ISSUE TITLE
Feature Request: Pull down when at the top, open search box

### ISSUE THREAD

**Issue by TobiasDev** [Kunzisoft/KeePassDX#847]
**Is your feature request related to a problem? Please describe.**
Phones are a lot too big for my small hands, so for me to reach the small "Search" icon at the top I need to move the phone around in my hand or use the other hand.

**Describe the solution you'd like**
I would love to have it so if I swipe when I'm already at the top of my Database it opens the searchbox and my keyboard.

**Describe alternatives you've considered**
The other idea would be to do what some other apps have done and move all the buttons to a bottom-bar instead of having them at the top. E.G. Deezer.

**Comment by J-Jamet** [comment]
I don't think swipe down is a good solution as it will be used for merge or reload data, however, the UI needs to be improved to handle one-handed actions. I close this issue. The other related ones remain open.
#575 #634
