### ISSUE TITLE
KeepassDX bugged OTP generation for Playstation(.com)

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#848]
Forwarding from Reddit (I also confirm this issue.)

> [r/KeePass•Posted byu/maulman115](https://www.reddit.com/r/KeePass/comments/kva2ns/keepassdx_bugged_otp_generation_for_playstationcom/)

> KeepassDX bugged OTP generation for Playstation(.com)

> I tried reporting this bug on github but they decided to block it because i used a temp email...

> OTP created by KeepassDX on Android are incorrect while using the same database on KeepassXC on PC gives the correct OTP. This may be due to the shared secret on Playstation being a 100+ digit code.

> I'm on KeepassDX 2.9.8. libre from F-Droid. Would be great if someone could confrm this and file the bug again.

**Comment by J-Jamet** [comment]
Indeed, the problem seems to be related to the size of the secret key, I will do more tests to find out where the problem comes from.

**Comment by J-Jamet** [comment]
The problem was the key padding, I replaced it with an '=' and it works. But I don't know if the steam generation has been broken.
