### ISSUE TITLE
Change the Argon2 memory unit from bytes to MiB

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#851]
**Is your feature request related to a problem? Please describe.**
It makes little sense to adjust memory usage in bytes or KB. Appropriate units make the settings easier to understand.

**Describe the solution you'd like**
Argon2 memory usage is specified as a positive integer in units of MiB. If the number edited on other apps is not an integer multiple of (1024 * 1024), only the integer part is displayed. For example, (1024 * 1024 - 1) will be displayed as 0MiB.

**Comment by hokonch** [comment]
Once the parameter is set to 1024MiB, the GiB unit prevents it from being lowered. It may be better not to add Gigabytes

**Comment by J-Jamet** [comment]
It should in the best case be able to select the unit. But I'm deactivating the Gibibyte first
