### ISSUE TITLE
Requesting for .keyx file support

### ISSUE THREAD

**Issue by yourmentor** [Kunzisoft/KeePassDX#856]
Hello Kuzisoft Team!

I found an important missing feature of KeePassDX when I helped my friend (Linux user) to setup Keepass Database. We set password and Key file (.keyx) in his database using KeepassXC. When we tried to open his Keepass database in his android phone using KeePassDX, it simply didn't open. After half an hour we finally found that  KeepassDX is still not supporting .keyx file. People who uses KeepassDX (in Android) are mostly Linux users and using KeePassXC instead of orginal KeePass. Now KeepassXC generate .keyx file by default from their latest update (v2.6.3). It will surely make problem for new Keepass users. So I request you to implement the support for .keyx file in KeePassDX as soon as possible.

Thank You

**Comment by yourmentor** [comment]
It is fixed.

**Comment by J-Jamet** [comment]
Duplicate to #844 
The feature is under development.

**Comment by yourmentor** [comment]
Sorry for confusion
Keepassdx still not supports .keyx file
