### ISSUE TITLE
Better font for display of entry comments

### ISSUE THREAD

**Issue by engelhro** [Kunzisoft/KeePassDX#86]
The font used to show the comment of entries ist just, well, awful. While I don't mind it being monospaced (although an option to select that would be fine), the actual font used is rather strange.

For example: every **0** (zero) looks like it is crossed through (**~~0~~**).

Is it possible to have a more sensible font default here? Thanks!

**Comment by J-Jamet** [comment]
The option exists and the custom font can be disabled in :
`Settings -> Application settings -> Field Font`
It's the Android monospace font manually modified in runtime for a better visibility of zeros as asked here #56 
(this technique does not import other fonts in the system)
I can disable the default option in the next version.

What do you mean by "more sensible" ?

**Comment by engelhro** [comment]
> The option exists and the custom font can be disabled in : […]

Ah, didn't see that setting before resp. did not associate it with my problem. Thanks for the hint!

> What do you mean by "more sensible" ?

Well, as I said: I can understand the need to better differentiate certain characters (O vs. 0, l vs 1). But there are so many (monospace, but also proportional) fonts that support this – so why of all possibilities chose one that displays the characters as if they were striked through?

That's a rather odd decision, not pleasing the eye at all… So I do not request to change the option you mentioned as new default, but rather question the font selection itself.

**Comment by J-Jamet** [comment]
OK, you're right, I took the first solution I had (which was not necessarily the simplest).
I'm changing the font by Droid Sans Mono Slashed (https://github.com/AlbertoDorado/droid-sans-mono-zeromod).

**Comment by engelhro** [comment]
Sounds good :+1: Thanks for taking care of this.
Shall I close the issue now, or wait for a new beta (or final) to be released?

**Comment by J-Jamet** [comment]
New release available! ;)
