### ISSUE TITLE
Unable to read credentials

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#861]
**Describe the bug**
It seems that since version 2.9.9, the opening of some databases is no longer done correctly.
The cause is still to be determined but it seems to be due to a type of key file.

**Expected behavior**
Correct opening of the database

**KeePass Database**
 - Version: kdbx

**KeePassDX (please complete the following information):**
 - Version: 2.9.9 - 2.9.10

**Comment by J-Jamet** [comment]
Feel free to explain exactly what type of key file you are using because I still haven't reproduced the problem.

**Comment by gianter962** [comment]
25087142 as password
to open try with 2.9.8 or KeePassX 2 for Linux

[database.for.testing.zip](https://github.com/Kunzisoft/KeePassDX/files/5824486/database.for.testing.zip)

**Comment by J-Jamet** [comment]
OK, very helpful, thank you very much. I just understood the problem, it's in conflict with the issue #835. So I did a rollback and used the new hexadecimal method.

**Comment by gianter962** [comment]
Perfect, glad to hearing that. In which update will you insert the hexadecimal method ?

**Comment by J-Jamet** [comment]
The next one, 2.9.11. I check that it does not break anything

**Comment by J-Jamet** [comment]
The new version is uploading, available soon in the store.
