### ISSUE TITLE
Number of entries contained in subgroups

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#874]
Display the number of entries contained in the subgroups. Currently, only the number of entries contained directly (1 level) in the group is displayed.

**Comment by Jrchintu** [comment]
What if we use diffrent colour according to type of entries ? Such as for folder we can use blue and and for entries we can use green ? As many times when there are no entries but only sub-folders inside folder then number of entries display 0 (on folders logo)

**Comment by J-Jamet** [comment]
Linked #1327

Why not different colors, I'll see.
