### ISSUE TITLE
No scrolling with some screens

### ISSUE THREAD

**Issue by manniclick** [Kunzisoft/KeePassDX#876]
If the keyboard is displayed during editing, the entry cannot be scrolled.

**Comment by hokonch** [comment]
It would be nice if the database creation screen could be scrollable as well. Sometimes I accidentally quit the database creation instead of turning off the keyboard, leaving an empty file.

**Comment by J-Jamet** [comment]
Scroll in entry edit screen is done in version 2.9.13

**Comment by J-Jamet** [comment]
I just checked, the creation screen is already scrollable.
