### ISSUE TITLE
KeeTrayTOTP plugin settings are not correctly recognized

### ISSUE THREAD

**Issue by Augures01** [Kunzisoft/KeePassDX#878]
**Describe the bug**
Can't use 7-digit OTP with KeePassDX
Instead of 7-digit, KeePassDX generates 6-digit OTP code
I checked and it's works as expected in Keepass2Android, KeePass for Windows, KeePassXC

**To Reproduce**
1. Open any entry with 7-digit
2. KeepassDX generates 6-digit code (same with OTP fill in magikeyboard)

**Expected behavior**
KeePassDX must generate 7-digit OTP as expected

**KeePassDX (please complete the following information):**
 - Version: 2.9.12
 - Build: Pro
 - Language: Russian

**Android (please complete the following information):**
 - Device: Samsung Galaxy S6 Edge
 - Version: 7.0

**Comment by Augures01** [comment]
If it's important
I get 7-digit OTP from Authy app converted to format compatible with KeePass by using this guide:
https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93

**Comment by J-Jamet** [comment]
I don't understand the bug. I just checked with the otpauth link provided in the github project and the tokens are correctly generated with 7 digits.

**Comment by J-Jamet** [comment]
Please upload a test database which contains entries with random TOTP links which generate tokens with 7 digits on other applications but not on KeePassDX. Because I can't reproduce your problem.

**Comment by Augures01** [comment]
@J-Jamet
[7digit.zip](https://github.com/Kunzisoft/KeePassDX/files/5871113/7digit.zip)
Password for db: 12345

**Comment by Augures01** [comment]
Also noted that my Battle.net 8-digit has same issues
KeePassDX generates 6-digit OTP

I use [KeeTrayTOTP](https://github.com/KeeTrayTOTP/KeeTrayTOTP) plugin in KeePass on Windows to generate OTP

**Comment by J-Jamet** [comment]
The problem does not come from the generation of the token (which works well), but from the recognition of the plugin format. During my tests I was using the otpauth format.

Unfortunately, I couldn't find any documentation that explains the format of this plugin. So I implemented a parser based on the examples I had.
https://github.com/Kunzisoft/KeePassDX/blob/e6b33d60c353fb930c31923e25d341bd52c24e49/app/src/main/java/com/kunzisoft/keepass/otp/OtpEntryFields.kt#L347

Here the format you are using is not recognized because I did not know it could be used like that.
Do you have specific documentation or an exact description that explains all of the use cases for this plugin?

**Comment by Augures01** [comment]
> Do you have specific documentation or an exact description that explains all of the use cases for this plugin?

Sorry, but I'm not a developer of anything and can't help with this :D
Only information that I have is that [KeeTrayTOTP](https://github.com/KeeTrayTOTP/KeeTrayTOTP) is fork that adds Steam token generation in abandoned [TrayOTP plugin](http://sourceforge.net/projects/traytotp-kp2/)
And if I know right, Keepass2Android uses code compatible with KeeTrayTOTP/TrayOTP
Maybe you can find something in K2A repository https://github.com/PhilippC/keepass2android/tree/master/src/keepass2android/Totp

**Comment by J-Jamet** [comment]
Thanks, I also just saw that there is a parser issue, the second Regex element is not fetched and was managed as a type of token and not as the number of digits. I am modifying the code at this level, it will be fixed for the next version.

**Comment by Augures01** [comment]
Ok, thank you
Will wait for next version =)

**Comment by Augures01** [comment]
@J-Jamet 
Seems like it fixed in 2.9.13
Thank you
