### ISSUE TITLE
Automatic copy of TOTP 

### ISSUE THREAD

**Issue by yourmentor** [Kunzisoft/KeePassDX#879]
It would be nice if KeePassDX allows to automatically copies TOTP to clipboard (if available for entry) after autofill. I know we can also fill TOTP using magikeyboard.

This will be an optional feature.

Thanks in advance!

**Comment by J-Jamet** [comment]
This feature is specifically related to #553.
The problem is that I can't use this method because it doesn't work when several OTP elements are returned.
Please read the issue above for more details.
