### ISSUE TITLE
Entry not showing up in KeePassDX

### ISSUE THREAD

**Issue by Flummic** [Kunzisoft/KeePassDX#883]
**My Situation:**
I currently use KeePassXC on my computer and store the Database-File on GoogleDrive. This way I can access the database with KeePassDX on my phone! - So far this has been working fine for me!

A couple of Days ago I had the Database open on both my phone and my pc at the same time and created an entry on my PC. This caused the app to display a notification and I accidentally used the "Phone-Database" to overwrite the change. 
This caused the entry to dissapear in my database, since the new entry was overwritten by my KeePassDX. 
Luckily I was able to restore the entry on my PC by loading a backup-file and saving the database again. 

**Now to the Problem:** 
For some Reason the entry that clearly shows up on my PC (I use it frequently) does not show up on my Phone using KeePassDX even though I opened the correct Databasefile, after clearing the Cashe and even reinstalling the App.
Do you have any idea what could be causing this issue?

I just tried opening the same Database with Keepass2Android and the entry shows up there. 
I also just added another entry on my PC using KeePassXC, which is also not showing up on KeePassDX but it is showing up on Keepass2Android.
It feels like KeePassDX is stuck with the Version of the Database I had when I accidentally overwrote the Database on my phone.
But it's still weird because I'm actively opening the new Database-File using the files-application.
I suspect that KeePassDX has maybe stored the information of the old database somewhere, because I overwrote the database? But I don't really know :)

**Comment by J-Jamet** [comment]
No information contained in a database is kept when the database is closed. 
I think you reopen the database from history with a URI that is associated with Google Drive and it is this application that kept a cache.
Try to delete the data from the Google Drive application.

Linked to https://github.com/Kunzisoft/KeePassDX/issues/873

**Comment by Flummic** [comment]
So I tried doing a quick Screen-Record of me opening the same file stored on Google-Drive in both KeePassDX and Keepass2Android. I used SolidExplorer to access the file and downloaded it fresh to open with both apllications. 
Even though the video is very rough you can see, that Keepass2Android (first open) finds a "Github-Entry" and a "Trilliontreecampaign-Entry" in the Database, while KeepassDX does not. 
**https://drive.google.com/file/d/1Az3EBC7xZ8STCv9n-HbgPL2HBROLB7ak/view?usp=sharing**

I hope that helps a little?
Anyways thank you so much for the quick reply already!

**Comment by Flummic** [comment]
> No information contained in a database is kept when the database is closed.
> I think you reopen the database from history with a URI that is associated with Google Drive and it is this application that kept a cache.
> Try to delete the data from the Google Drive application.
> 
> Linked to #873

I think you were right! I deleted the file in my Drive and saved it again -> now all the entries show up as intended! Thank you for the quick reply!
