### ISSUE TITLE
Fingeprint problem: null

### ISSUE THREAD

**Issue by r0b0** [Kunzisoft/KeePassDX#89]
KeePass DX version 2.5.0beta7-libre from F-Droid
Xiaomi MI A1 on Adroid 8.0
Unlocking the database with a fingerprint does not work any more. It used to work on previous versions on the same device. Message "Fingerprint problem: null" appears briefly at the screen when attempting a fingerprint unlock

**Comment by J-Jamet** [comment]
The refactoring makes the old keystore obsolete and displays a null exception. To solve the problem, the Fingerprint Store must be cleared in
Application settings -> [Fingerprint] Delete encryption keys.
you must then recreate the fingerprints for each password.

**Comment by r0b0** [comment]
Aaah, OK. I deleted the encryption keys. 
But the second part wasn't very discoverable. 
I need to go back to the _Enter password_ screen, enter the password (but do not press OK) and touch the fingerprint sensor. That's finally worked.
Is this how it's really supposed to work?

**Comment by J-Jamet** [comment]
Yes, it's to save the link between the fingerprint and the password.
