### ISSUE TITLE
Huge entries handling

### ISSUE THREAD

**Issue by afpp-l** [Kunzisoft/KeePassDX#892]
My phone with 2gb of ram can't properly open an entry with 400 lines of text in Notes section. The notes are not shown in full but only partially. Plus, I get thrown out of the database when I go back.

**Comment by J-Jamet** [comment]
It is normal for more than 400 lines of text in a note to not be visible at one time. You must select the text at the end to see the rest. I recommend that you decrease the size or make it a separate file.

> Plus, I get thrown out of the database when I go back.

I can't seem to reproduce this phenomenon, when I go back I am back to the content of the group.

**Comment by afpp-l** [comment]
> It is normal for more than 400 lines of text in a note to not be visible at one time.
I understand.

> You must select the text at the end to see the rest.
Maybe put an arrow button there?

> I can't reproduce this phenomenon,
I'm on Android 8 MIUI. The screen turns black on opening the entry. And then black again on going back.
