### ISSUE TITLE
About database issues

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#895]
**Describe the bug**
I copied the .kdbx database file from the PC to the mobile phone. Please note that the database version is KeePass 2-KDBX3.1.
I added an attachment to KeePassDX Pro. As the data was written, KeePassDX executed the save database at this time.
The most important thing is that the database version has become KeePass 2-KDBX4.
When I copied the database file on the mobile phone to the PC, I wrote new data to the database, and then when I copied the database to the mobile phone, all attachments in the database were damaged.

**To Reproduce**
1. I copied the .kdbx database file from the PC to the mobile phone. Please note that the database version is KeePass 2-KDBX3.1 (Size 10M).
2. I added an attachment to KeePassDX Pro. As the data was written, KeePassDX executed the save database at this time (Size 5M).
3. The most important thing is that the database version has become KeePass 2-KDBX4.
4. When I copied the database file on the mobile phone to the PC, I wrote new data to the database, and then when I copied the database to the mobile phone, all attachments in the database were damaged.

**Expected behavior**
Why can't we keep the default database version and have to change the database version?
Don't change the database version!!

**KeePass Database**
 - Created with:  Windows KeePass 2.47 (64 Bit)
 - Version: KeePass 2-KDBX3.1
 - Location: Local Disk
 - Size: 10
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 2.9.13
 - Build: Pro
 - Language: Chinese

**Android (please complete the following information):**
 - Device: Xiaomi Note 3
 - Version: 9

**Comment by J-Jamet** [comment]
Normally, the switch from version 3.1 to version 4 of the database is done automatically only if the KDF is Argon2 but should not corrupt the attachments.

Can you create a test database without sensitive information with the problem and upload it here?

**Comment by J-Jamet** [comment]
Are you sure it's a different problem than https://github.com/Kunzisoft/KeePassDX/issues/715 ?

**Comment by Vstory** [comment]
> Normally, the switch from version 3.1 to version 4 of the database is done automatically only if the KDF is Argon2 but should not corrupt the attachments.

I did not switch the encryption scheme, the default AES-KDF.

![Snipaste_2021-02-19_23-00-17](https://user-images.githubusercontent.com/20795557/108521056-4d5ef980-7306-11eb-9222-dec962cd32b2.png)


> Can you create a test database without sensitive information with the problem and upload it here?

I have not changed the encryption configuration, as mentioned above.

> I copied the .kdbx database file from the PC to the mobile phone. Please note that the database version is KeePass 2-KDBX3.1.
I added an attachment to KeePassDX Pro. As the data was written, KeePassDX executed the save database at this time.
The most important thing is that the database version has become KeePass 2-KDBX4.

**Comment by Vstory** [comment]
> Are you sure it's a different problem than #715 ?

I don't understand this question.

[About database issues
](https://github.com/Kunzisoft/KeePassDX/issues/895)
This problem occurs when KeePass uses the master password + key file as the unlocking method. When only using the master password as the unlocking method, this problem will not occur.

**Comment by Vstory** [comment]
> Normally, the switch from version 3.1 to version 4 of the database is done automatically only if the KDF is Argon2 but should not corrupt the attachments.

You can try to follow the steps I provided, I have successfully reproduced the problem.

**Comment by J-Jamet** [comment]
> I have not changed the encryption configuration, as mentioned above.

I understand, but I was asking if you could upload a test database on github so that I could reproduce the problem. Because I must already be able to understand the issue before I can correct it.

> I don't understand this question.

I'm just asking if this is a different problem than the one described in the issue #715? 
Because a new issue means a different problem.

> You can try to follow the steps I provided, I have successfully reproduced the problem.

Problem is, it's not precise enough, that's why I'm asking you for a test database.
How did you create your database on the PC? Just with KeePass2 and not with KeePassXC or KeeWeb?

> This problem occurs when KeePass uses the master password + key file as the unlocking method. When only using the master password as the unlocking method, this problem will not occur.

It's weird. I do not see at all the link between the use of the key file in the master key, the change of database version 3.1 to 4 and the binary bug.

**Comment by Vstory** [comment]
> Problem is, it's not precise enough, that's why I'm asking you for a test database.
How did you create your database on the PC? Just with KeePass2 and not with KeePassXC or KeeWeb?

I use KeePass portable version to create a database.
[KeePass Portable](https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.47/KeePass-2.47.zip/download)

> It's weird. I do not see at all the link between the use of the key file in the master key, the change of database version 3.1 to 4 and the binary bug.

I don't know this, but it is true.

Test file:
[Test.zip](https://github.com/Kunzisoft/KeePassDX/files/6011112/Test.zip)
This file is a database file and key file created using KeePass portable version.
Password:1234

1.Use KeePass to open the test database；
2.After adding any attachments to the test entry "test11", save the database;
3.Move the above database file to the mobile phone to open it with KeePassDX Pro, and check the database version;
4.Use KeePassDX Pro to open the above test database, add any files, and save the database;
5.Save and refresh the database, repeat it several times, and view the database version. This operation may need to be repeated several times.

If everything is normal, there will be a database version change.You can repeat steps 2~5 continuously, and the final database version will change.

**Comment by J-Jamet** [comment]
> If everything is normal, there will be a database version change.You can repeat steps 2~5 continuously, and the final database version will change.

I have just done this operation 4 times without being able to reproduce the problem. The version of the database remained 3.1 and I manage to open the added binaries (I tried with a png, a jpg, a 10Mo and 10Ko binary file).

If the database version is 4, it's the same problem as issue #715, I can understand that this behavior happens, but the version of the database is not changed without reason.

Depending of official documentation : (https://keepass.info/help/kb/kdbx_4.html)
```
As not all major KeePass ports have finished adding support for KDBX 4 yet, for now KeePass 2.35 saves databases in this new format only when at least one of the following conditions is fulfilled:

AES-KDF is not selected as key derivation function (KDBX 3.1 only supports AES-KDF; any other key derivation function, like for instance Argon2, requires KDBX 4).
A plugin requests to store custom header data in the KDBX file.
A plugin requests to store custom data in an entry or a group.
```

There is no plugin in KeePassDX and I haven't found any bug that changes the database version in KeePassDX yet. It is upgraded only if there is a change of KDF.

**Comment by Vstory** [comment]
> I have just done this operation 4 times without being able to reproduce the problem. The version of the database remained 3.1 and I manage to open the added binaries (I tried with a png, a jpg, a 10Mo and 10Ko binary file).

I can reproduce the problem. I am going to change the encryption method to make the database KeePass 2-KDBX4.

> Depending of official documentation : (https://keepass.info/help/kb/kdbx_4.html)

Thank you, this is very useful, I will directly change the encryption method.

> There is no plugin in KeePassDX and I haven't found any bug that changes the database version in KeePassDX yet. It is upgraded only if there is a change of KDF.

I have checked that after the database version is changed, the encryption method has not changed.

> If the database version is 4, it's the same problem as issue #715, I can understand that this behavior happens, but the version of the database is not changed without reason.

The database version change is not the point, the main reason is that all the attachments can not be read. Garbled.

**Comment by J-Jamet** [comment]
Okay, I'm still working on issue #715 anyway, it must be a binary data formatting not recognized by KeePass2 but I don't know which one, we have to debug KeePass2 to find out why. I asked its creator for help.
