### ISSUE TITLE
Database cannot be opened when using OneDrive

### ISSUE THREAD

**Issue by rafipanoyan** [Kunzisoft/KeePassDX#898]
**Describe the bug**
The database is corrupted as soon as I edit it.

**To Reproduce**
1. Create a new database with KeePass, set the key derivation iteration to 2.000.000
2. Upload this file to Onedrive (only tested on onedrive)
3. Open the file with KeePassDX from the Onedrive Android app
4. Remove en entry and save
5. Try to open the file again in KeePassDX
6. An IOException is thrown in a red snackbar; BadPaddingException.

I have another file throwing a "Hashes didn't match" IOException when I edit it.

**Expected behavior**
The database should be opening as normal

**KeePass Database**
 - Created with: Windows KeePass 2.47
 - Version: 2
 - Location: Remote file retrieved with Onedrive app
 - Size: 2Ko
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.19.12
 - Build: Free
 - Language: French

**Android (please complete the following information):**
 - Device: Nokia 7 Plus
 - Version: 10

**Additional context**
When the file become corrupted for KeePassDX, the Windows version of KeePass can't open it neither

**Comment by J-Jamet** [comment]
I just tested locally, without using OneDrive, and have no problem.
Your concern must come from OneDrive which does not save the entire given file in the stream of its content provider.
Can you try without OneDrive?

**Comment by rafipanoyan** [comment]
Ok you seem to be right, when I download the file locally I don't have any issue editing and opening both files. I should have tested that before opening the issue... 

Thanks for your quick reply !
