### ISSUE TITLE
Database settings not accessable

### ISSUE THREAD

**Issue by SecTec** [Kunzisoft/KeePassDX#9]
Android version: 7.1.2 LineageOS
App version: 2.5.0.0 beta 2 libre from f-droid

I can't open the database settings.

I expect to change the database settings like cipher and iterations of the KDF, but I can't open the database settings. The point in the menu is not touchable and the color of the letters is grey.

I tested this with an database created by Keepass DX.

**Comment by J-Jamet** [comment]
Thanks for the reply. It's a known bug described in the initial project (https://github.com/bpellin/keepassdroid/issues/223), I try to solve a maximum of bugs in this fork, it will normally be set in the production version. Maybe not in the next beta.

**Comment by J-Jamet** [comment]
There is an evolution in the settings with the version 2.5.0.0beta3 but the management of the kdbx V4 must be better managed and requires more time.

**Comment by J-Jamet** [comment]
TODO
- [ ] Setup hashing parameters
- [ ] Setup recycle bin parameters

**Comment by J-Jamet** [comment]
Many changes in version 2.5.0.0beta8 that adds database name, description and transformation rounds management. There is the display of encryption and KDF. 
It's a lot of work to change the encryptions on the fly but it happens.

**Comment by J-Jamet** [comment]
Fixed in the new version 2.5.0.0beta11
