### ISSUE TITLE
not possible to choose a file from Dropbox

### ISSUE THREAD

**Issue by maks** [Kunzisoft/KeePassDX#90]
Thanks for the fantastic work on this project.

This seems to be due to [Dropbox continuing to ignore the need to support SAF](https://stackoverflow.com/questions/23888691/dropbox-not-seen-in-storage-access-framework-implementation) and KeePassDX using SAF.

Would you be open to PRs that would work around this or to add an option to use the Dropbox Chooser SDK?

**Comment by J-Jamet** [comment]
Thanks for your comment.
The problem with dropbox is that it's not an open source cloud. I want to stay in free apps domains only (and if I start with dropbox, I have to implement OneDrive, Google Drive, and all unknown clouds ...)  I prefer to let file managers take care of it.
I have not yet tested with Dropbox and other clouds but SAF may been disabled or enabled in settings.

**Comment by maks** [comment]
Yes I completely understand and agree. Actually the situation is not too bad, as as may be expected, Google Drive app supports SAF properly, it's just Dropbox app that continues not to for some reason. The easy work around for me is just to use drive for syncing the file. I'll close this as on consideration it's not KeepassDX job to work around a failing of the Dropbox app.
