### ISSUE TITLE
Autofill mostly not working with Firefox 85.1.3 (Build# 2015792283)

### ISSUE THREAD

**Issue by ouch67** [Kunzisoft/KeePassDX#902]
The prompts to autofill only occasionally show up.

Running android 11 on a Pixel 3XL.

**Comment by J-Jamet** [comment]
OK, I added the bugged version to the wiki. https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#compatibility-mode
Linked to https://github.com/Kunzisoft/KeePassDX/issues/725
Don't hesitate to do it yourself instead of opening an issue for it. ;)

**Comment by J-Jamet** [comment]
I just tested with an Android 11 emulator and Firefox 85.1.3 and I don't have the problem.
In any case, I advise you to use the inline suggestion.
