### ISSUE TITLE
Do not overlay the database creation screen with the software keyboard

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#903]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/876#issuecomment-767973311
**Is your feature request related to a problem? Please describe.**
https://imgur.com/a/8FZFo5K
The keyboard hides the OK button, so you have to close the keyboard before you press it.
In particular, in gesture navigation, you can close the keyboard by pressing the lower left corner, but if you press it slightly off, the database creation will be canceled and an empty garbage file will be left.

**Additional context**
 - Device: Pixel 3a
 - Version: 11

The keyboard doesn't overlay the screen in my Android emulator.
https://imgur.com/a/CFHY00r

**Comment by J-Jamet** [comment]
It's a non-consistent behavior indeed, because the dialog buttons are managed by the system and they don't behave in the same way depending on the Android version...
I will try to work around this problem by creating custom dialog buttons with themes or by redefining the system's buttons.
