### ISSUE TITLE
Option for continous opening and not closing before closing the app

### ISSUE THREAD

**Issue by Thewisem** [Kunzisoft/KeePassDX#908]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when after some time it locks and when I need it I have to unlock it. I don't have a fingerprint sensor and it's annoying to keep on putting my password every 15 or so minutes.

**Describe the solution you'd like**
For there to be an option to close only after the app closes. 

**Describe alternatives you've considered**

**Additional context**
It should not also close when in the background. It should be opened. It should be an option.

**Comment by J-Jamet** [comment]
I don't understand the request and why the current options are not suitable for you?

If you don't want the database to close after a given time, just change `Settings -> App settings -> App timeout` to `Never`.
Just don't forget to lock your database when you don't use it anymore.

Also be aware that it is possible to use the phone's credentials if you do not have a fingerprint reader.  https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

**Comment by Thewisem** [comment]
Ok thanks

**Comment by Thewisem** [comment]
Really embarassing.
