### ISSUE TITLE
Failed to load database

### ISSUE THREAD

**Issue by TheBlinded** [Kunzisoft/KeePassDX#918]
**Describe the bug**
When I open the database via fingerprint, a database loading error appears... I attach a screenshot at the end of the post.
Error start with: "java.lang.SecurityException: Permission Denial: reading..."

**To Reproduce**
1. Open the app, select database, save the password with footprint
2. Wait one/two days..
3. Open the app, scan the footprint
4. Error... I have to reselect the database...

**Expected behavior**
Opening the database

**KeePass Database**
 - Created with: KeePassXC 2.6.4
 - Location: Remote file located on GDrive retrieved with Oneplus file manager
 - Size: 740KB
 - Contains attachment: No

**KeePassDX Pro:**
 - Version: 2.9.13
 - Language: Italian

**Android (please complete the following information):**
 - Device: OnePlus 8
 - Version: Android 11, Oxygen 11.0.4.4IN21BA

![IMAGE 2021-03-10 18:00:03](https://user-images.githubusercontent.com/5796668/110669488-a9fa5980-81cc-11eb-869b-44967dffccbf.jpg)

**Comment by J-Jamet** [comment]
Access to your database has simply been revoked by your file manager. Simply reopen your file from its location.
Explanations : https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#explanation
Linked to https://github.com/Kunzisoft/KeePassDX/issues/626

**Comment by TheBlinded** [comment]
Yes, I understand, but it is not possible to use any other file manager to open database... There is no option on which file manager to open... Maybe this is a problem with Oneplus Oxygen...

**Comment by TheBlinded** [comment]
I have found that if you don't save the password by fingerprint, the database opens without any problem.

**Comment by TheBlinded** [comment]
> Access to your database has simply been revoked by your file manager. Simply reopen your file from its location.
> Explanations : https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#explanation
> Linked to #626

I have found that if you don't save the password by fingerprint, the database opens without any problem.

**Comment by Ilithy** [comment]
@TheBlinded 
Hi,
if I may add a few things, I use a Oneplus under Oxygen OS (10.3.7),
I have the biometric automatic opening by fingerprint,
I use the basic file manager of Oneplus, and I have not had this problem at any time.
