### ISSUE TITLE
Add Brave Browser as having Native Autofill support in wiki 

### ISSUE THREAD

**Issue by xd003** [Kunzisoft/KeePassDX#921]
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#compatibility-mode

Hereby refering to the table of the compatibility of browsers with autofill , i would like to add that you could add Brave browser there . I am currently on the beta and the autofill is working great . I think its native autofill as its very quick :)

Android 10
Brave Beta v1.22.55

PS - Please change the label of this issue to something more suitable

**Comment by J-Jamet** [comment]
Done :+1:
