### ISSUE TITLE
Copy password icon do not show for long password

### ISSUE THREAD

**Issue by gkrnours** [Kunzisoft/KeePassDX#922]
**Describe the bug**
When password is too long (say 32 characters, company policy), the icon to show the password show up but not the icon to copy the password. This make copying and the password... Awkward. 

**To Reproduce**
1. Create a new entry
2. Create a password of 32 characters 
3. Open the newly created entry
4. Notice the dots for the password take most of the space
5. Notice the copy password icon is missing

**Expected behavior**
The button to copy a password should always be visible. 

**KeePass Database**
 - Created with: KeePassDX 2.9.13
 - Version: KDBX3.1
 - Location: local file
 - Size: 1.3k
 - Contains attachment: No

**KeePassDX**
 - Version: 2.9.13
 - Build: play store? 
 - Language: english

**Android (please complete the following information):**
 - Device: moto g(6)
 - Version: 9

**Comment by J-Jamet** [comment]
I just checked, the view is adaptive and the button well visible with a large password.
This is not a bug, you just disabled the feature `Settings -> Form filling -> Clipboard Trust`.
