### ISSUE TITLE
When editing a database entry, the application automatically returns to the unlock interface

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#936]
**Describe the bug**
When editing a database entry, it automatically returns to the database unlocking interface.

The problem does not appear every time.

**To Reproduce**
1. Unlock the database, search for any content, click any search result, and enter the entry preview interface.
2. Edit the content of the entry, such as changing the password and changing the remarks.
3. For example, in the pop-up window for generating a password, after clicking Generate Password and clicking Accept the password, the problem may occur.
4. This problem does not occur every time, and I cannot confirm the cause of the trigger.
5. When the problem was triggered, I grabbed the logcat log once.
6. attachments
[logcat.txt.zip](https://github.com/Kunzisoft/KeePassDX/files/6188933/logcat.txt.zip)

**KeePass Database**
 - Created with: Windows KeePass 2.47 (64 Bit)
 - Version: KeePass 2-KDBX4.0
 - Location: Local Disk
 - Size: 6.66M
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 2.9.14 
 - Version code: 65
 - Build: Pro
 - Language: Chinese

**Android:**
 - Device: XiaoMi Note 3
 - Version: 9.0

**Additional context**
The database contains many attachments and custom icons.

**Comment by tutyamxx** [comment]
I cam confirm that it happens to me as well 🙈

**Comment by J-Jamet** [comment]
I think this problem is related to themes. But it's to be confirmed, some systems do not correctly handle theme variables.
https://github.com/Kunzisoft/KeePassDX/issues/935

Do you have any themes other than the basic ones (forest) activated? To confirm this theory.

**Comment by tutyamxx** [comment]
If it helps, yea, I think is related to themes because on the default theme (dark or normal) works fine but after I switched to other themes it started doing it.

**Comment by J-Jamet** [comment]
I have created a package for another issue, if you can download it and tell me if the bug is present or not that would be a great help.

https://github.com/Kunzisoft/KeePassDX/issues/933#issuecomment-808464779

**Comment by Vstory** [comment]
> Do you have any themes other than the basic ones (forest) activated? To confirm this theory.

I am not using the default theme.The theme I use: Classic

**Comment by Vstory** [comment]
> I have created a package for another issue, if you can download it and tell me if the bug is present or not that would be a great help.
> 
> [#933 (comment)](https://github.com/Kunzisoft/KeePassDX/issues/933#issuecomment-808464779)

I know, I will test.

**Comment by Vstory** [comment]
After a simple test, the problem did not appear.

**Comment by Vstory** [comment]
@J-Jamet 
In this version, the problem still exists.

![Screenshot_2021-03-30-06-32-33-121_com miui securitycenter](https://user-images.githubusercontent.com/20795557/112908237-c6c9e300-9121-11eb-8372-a924b247fd2a.jpg)

**Comment by Vstory** [comment]
@J-Jamet 
This problem is not a bug, it is a feature.
#936 #951 
It is related to some options of the magic keyboard.

`Autofill -> Magic Keyboard -> Entry -> Entry Selection`

When the item selection option is turned on and a timeout is set to clear the magic keyboard at the same time, the problem will appear when browsing items.

This option appears in the auto-fill setting. When the user enters KeePassDX without auto-fill or magic keyboard, the entry selection should be ignored to avoid this problem.

There is no language switch option in the app, I took a screenshot directly.
The figure shows the magic keyboard setting interface.
![image](https://user-images.githubusercontent.com/20795557/116504631-59a99900-a8eb-11eb-8760-0de2020dfcbb.png)
