### ISSUE TITLE
Export database

### ISSUE THREAD

**Issue by JanuaryLimes** [Kunzisoft/KeePassDX#94]
It would be lovely to be able to export database and save in external storage

**Comment by J-Jamet** [comment]
Exporting the database in a CSV file ? Not a priority I think for a phone, but why not, under what circumstances an export file is needed for you ?

**Comment by JanuaryLimes** [comment]
Not CSV, export to kdbx. For example when I add new entry on my phone I want to export my database and upload it to the cloud so I can easily have access to newly created entry on my computer

**Comment by JanuaryLimes** [comment]
Thank you for information, I guess now this issue is relevant ;)

**Comment by martin3000** [comment]
KeepassDX database files are kdbx? My keepassDx database is a kdb database and cannot be opened with keepass 2.44 for the PC.

**Comment by J-Jamet** [comment]
@martin3000 It is normal, your .kdb file is a format of the version 1 of KeePass for PC, either you must transform it into kdbx with 2.44, or use the version 1.39.
