### ISSUE TITLE
Feature: Let us fill in the credentials before changes of the database are saved

### ISSUE THREAD

**Issue by realpixelcode** [Kunzisoft/KeePassDX#942]
The following situation: You download a new app, let's say Reddit and you have to log in so you click into the respective form. KeePass' auto-type feature recommends choosing an entry from the password database so you do that. And as soon as you select an entry, KeePassDX saves the information that entry x belongs to Reddit. When finished, the credentials are filled into the form.

That procedure might be okay if opening/saving the database doesn't take the device too long but if it does – because you cranked up the iterations like me – then it's very annoying to wait so long for KeePass to finish saving the database.

So please make KeePassDX save the entry/app combination AFTER filling in the credentials. That would be very, very nice.

**Comment by Vstory** [comment]
Silently save in the background.
