### ISSUE TITLE
Can't open keepassdx via magikeyboard

### ISSUE THREAD

**Issue by clock33** [Kunzisoft/KeePassDX#950]
**Describe the bug**
I can't open keepassdx via magikeyboard on redmi 6

**To Reproduce**
1. Go to any website or apps
2. Switch to magikeyboard and press key symbol
3. Nothing happens

**Expected behavior**
Should be able to open keepassdx via magikeyboard

**KeePass Database**
 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android (please complete the following information):**
 - Device: Redmi 6
 - Version: Android 9

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by cloudy-dev** [comment]
You need to allow "Drawing over other apps" and maybe also the popup window permission in the MIUI Settings for this feature to work :)

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard
