### ISSUE TITLE
keepass file size decreased after saving in keepassdx

### ISSUE THREAD

**Issue by JunkyardCat** [Kunzisoft/KeePassDX#959]
**Describe the bug**
I have a keepass file created in keepass desktop ver and when i used that file and saved it in keepassdx the file size seems to be reduced. The only thing i i did was add one entry
**To Reproduce**
1. Create a keepass on desktop
2. Transfer to android
3. open keepass on android
4. Add one entry
5. Save
6. Size is reduced

**Expected behavior**
Size should be more than what it was before

**KeePass Database**
 - Created with: windows 2.x (i forgot as i dont have access to my desktop
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - Size: n/a
 - Contains attachment: n/a

**KeePassDX (please complete the following information):**
 - Version: either 2.9.13 or 2.9.12
 - Build: fdroid
 - Language: english

**Android (please complete the following information):**
 - Device: j7 prime
 - Version: 6 0.1

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
OK, there are two things: 

- You are not up to date. Update your application, if there is a problem, check with the last update if it is not solved.

-  I don't see how reducing the size of the database is a problem. I am constantly optimizing the formatting of the data to reduce the final size without losing data (compression, duplicate removal, reordering for encryption, etc.).
If you want your database to be bigger with each record this is a new feature that is clearly not urgent and clearly I don't see the point.
