### ISSUE TITLE
Add custom icons

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#96]
- [x] Add custom icon in an entry
- [x] Select custom icons from tabs
- [x] Remove custom icons

The download of separate icons will be done from a plugin in order to leave KeePassDX completely offline. The method must be defined.

**Comment by alexanderadam** [comment]
I'm not quite sure whether this could be helpful but there's the SuperTinyIcons project which provides [MIT licensed](https://github.com/edent/SuperTinyIcons/blob/master/LICENSE) [Android Vector Drawables](https://github.com/edent/SuperTinyIcons#scream-if-you-want-to-go-smaller).

**Comment by FreddieOliveira** [comment]
Any progress on this? KeePassDX can successfully display custom icons added using KeePass on computer, but can't set them. Everytime I create a new entry I need to edit it on the computer to add an icon.

**Comment by J-Jamet** [comment]
It's planned but I haven't had time to implement it yet, I think it will be the big feature of the 2.9.13 version.
A user had offered to do it but I didn't hear from him anymore.

**Comment by FreddieOliveira** [comment]
@J-Jamet Thank you. Just tested the feature and it works like a charm!
