### ISSUE TITLE
Empty list after editing or viewing an item

### ISSUE THREAD

**Issue by 0xDD-coder** [Kunzisoft/KeePassDX#961]
**Describe the bug**
Empty list after editing or viewing an item.

**To Reproduce**
1. Open file 'test.kdbx'
2. Type password: 123
3. We see a list of sections called "Web" and "Trash Can". 
4. Open section 'Web'
5. Open item 'Skype' or 'Pinterest'
6. Press Back key
7. See bug: empty list of items
8. Press Back key
9. See bug: empty list of sections
10. Press "..." key
11. Choose "Reload base" item from droplist
12. The list is displayed normally again

**Expected behavior**
Normal list of items. Without rebooting the base after any action. 

**KeePass Database**
 - Created with: Windows 7 64bit KeePassXC 2.6.4
 - Version: KeePass 2 - KDBX4.0
 - Location: local file
 - Size: 3559B or 3.47kB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.9.17
 - Build: Free
 - Language: Russian

**Android (please complete the following information):**
 - Device: Xiaomi Redmi 3S
 - Version: 7.1.2
 - MIUI: 9.6.27

**Attachment:**
Test database with this bug. Usernames and passwords in this base is fake.
[test.zip](https://github.com/Kunzisoft/KeePassDX/files/6312372/test.zip)

**Comment by J-Jamet** [comment]
I just tested with KeePassDX 2.9.17 - Android 11 stock and I have no problem.
Everything works normally, the list of groups and entries is displayed correctly every time with this database.

I don't have your device to test

**Comment by J-Jamet** [comment]
Knowing a bit about how Xiaomi block everything for no reason but love to put ads everywhere: do you have any MIUI specific permissions that you can disable in KeePassDX by any chance?

**Comment by 0xDD-coder** [comment]
Solved.
I go to the **Settings - Developer options - Turn on MIUI optimization** switcher set to off position.
Everything works fine.
