### ISSUE TITLE
Not working with Samsung DeX

### ISSUE THREAD

**Issue by VerbraucherX** [Kunzisoft/KeePassDX#963]
Dear Sir,

**Describe the bug**
If started on Samsung DeX it says "Can not operate with Samsund DeX" (or similar. It's German :-)
Not sure if its a bug or a feature request anyway..

DeX is a nice Android-desktop on Samsung tablets to work with, but without KeePassDX it's not possible to work as productive as it could be. It really would be nice to have access to passwords as with normal Android.

Is there any chance to make KeePassDX work on Samsung DeX?

Thank you very much for any advice,
Peter

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/245
You will find the information in the already opened issue.
