### ISSUE TITLE
The search function is not friendly to Chinese support

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#971]
**Describe the bug**
The search function is not friendly to Chinese support.

**To Reproduce**
1. Unlock the database
2. Click on the search box and enter "领英"
3. Search results do not show entries containing "领英"

**Expected behavior**
The target item is searched normally.

**KeePass Database**
 - Created with: Windows KeePass 2.47 (64 Bit)
 - Version: KeePass 2-KDBX4.0
 - Location: Local Disk
 - Size: 6.64M
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 2.9.19
 - Version code: 73
 - Build: Pro
 - Language: Chinese

**Android:**
 - Device: XiaoMi Note 3
 - Version: 9.0

**Additional context**
- KeePass Windows: normal work.

![Snipaste_DSoftwareKeePassKeePass-dataVisx - 数据库 kdbx - KeePass_2021-04-29_12-42-54](https://user-images.githubusercontent.com/20795557/116503757-6fb65a00-a8e9-11eb-9964-1cfb51c54b81.png)

- KeePassDX Pro: The search is abnormal.

![image](https://user-images.githubusercontent.com/20795557/116503936-d2a7f100-a8e9-11eb-8b66-6213ee1ab88d.png)
![image](https://user-images.githubusercontent.com/20795557/116503961-e18ea380-a8e9-11eb-9731-0101711a74b2.png)

**Comment by J-Jamet** [comment]
OK, thank you for the feedback, I think the problem is with the flatten method, I'll change it to see if it works in a non-Latin alphabet.
https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/utils/StringUtil.kt

**Comment by Vstory** [comment]
> OK, thank you for the feedback, I think the problem is with the flatten method, I'll change it to see if it works in a non-Latin alphabet.
> https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/utils/StringUtil.kt

Ok. Thank you!

**Comment by J-Jamet** [comment]
[KeePassDX-2.9.20_TestA.zip](https://github.com/Kunzisoft/KeePassDX/files/6397409/KeePassDX-2.9.20_TestA.zip)

Can you tell me if this package solved your problem?

**Comment by Vstory** [comment]
> [KeePassDX-2.9.20_TestA.zip](https://github.com/Kunzisoft/KeePassDX/files/6397409/KeePassDX-2.9.20_TestA.zip)
> 
> Can you tell me if this package solved your problem?

The results can be searched, but a significant delay can be felt.

**Comment by J-Jamet** [comment]
OK, that's what I thought, so I'll remove the accent removal feature , it takes too much time and can't be implemented without having a side effect. #945
