### ISSUE TITLE
a problem with saving on google cloud

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#981]
I have a problem with my DB file. I store it on Google Drive. The problem with it is that changes are saved but if I make a copy of it, then I don't see those changes in the copy. 

And often the DB disappears from the list of resent files.

And history of changes says it has been nodified at 30 of march but actually I changed it a few hours ago.

I can't reproduce the problem with a new DB.

Do you know a way to retrieve the last version of DB?

**Comment by J-Jamet** [comment]
This is not a KeePassDX problem, the Google Drive application sometimes seems not to associate correctly the files in its cache. Try to clear the cache of the Google Drive application.

**Comment by zveber** [comment]
Hmmmmm... At last the date of changes is today but I've lost all changes. Damn GDrive... But thanks that you've tried to help anyway.

**Comment by Drarig29** [comment]
I also have a problem with Google Drive. The database isn't sync-ed when I "Save the database". It only saves it locally. I tried to clear the cache of the Google Drive app, but it still doesn't work.

**Comment by Drarig29** [comment]
And in the home page where I can see the database entry, when I show the details of the database, it says it was modified in April (which corresponds to the last sync on Google Drive).

**Comment by Drarig29** [comment]
Ok, thanks for the detailed answer 😄

I figured out it's because my Google Drive app is configured to not upload without Wi-Fi, and I wasn't connected to it. As soon as I enabled the Wi-Fi, it did the sync!

**Comment by J-Jamet** [comment]
Those who have a problem with an out-of-date GoogleDrive file should simply clear the cache of the Google application.
