### ISSUE TITLE
Latest version and changes are missing!

### ISSUE THREAD

**Issue by Konfetti030** [Kunzisoft/KeePassDX#982]
Hi,
My kdbx is stored on my Google drive storage.
In the last days I added some data in my file sorted the passwords a little bit and created also a new folder and cut and copied some passwords in the new folder.
But yesterday I wanted to open the file but error message came up. Something like jave error enoent.
After i saved the file in local storage I could open again but my data is old. New folder missing and all other new entries.
Only thing I did was to update my Mi 9 with a minor update from 12.0.4 to 12.0.5

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/981
