### ISSUE TITLE
can't open if no password or keyfile was set 

### ISSUE THREAD

**Issue by clach04** [Kunzisoft/KeePassDX#985]
**Describe the bug**

**To Reproduce**
1. Launch app for first time
2. Accept all defaults, e.g location downloads folder
3. Do NOT set password or key file
4. Confirm no password
5. Create group, e.g "website"
6. Create entry
7.  Give name
8. Give url
9. Generate password (take defaults)
10. Add custom field, enter email address
11. Save, hit check mark bottom, center
4. Leave phone for a while
5. Come back to try and open default file. Can not hit open, so check password box and do not enter a  password (as there isn't one), click open. Get error

**Expected behavior**

**KeePass Database**
 - Created with: this app. 210.0
 - Version: [e.g. 2] ? Default
 - Location: default, Downloads
 - Size: 1.45Kb
 - Contains attachment: no, custom field yes

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta23] 2.10.0
 - Build: Free
 - Language: [e.g. French] English

**Android (please complete the following information):**
 - Device: GalaxyS9
 - Version: [e.g. 8.1]

**Additional context**
 - keepassdroid fails to open the same file, says a password or key file is required (even though none was specified when creating the file)

**Comment by clach04** [comment]
Keepassdroid will not allow a DB to be created without a password word (or key file). My guess is keepassxc used a password

**Comment by clach04** [comment]
Db created with keepassdroid with a password can be opened by keepassdx

**Comment by J-Jamet** [comment]
There is no bug here : settings - app settings - allow no master key

**Comment by clach04** [comment]
That definitely fixed it for me, thank you! :)

I'm not sure I would have figured this out on my own.

**Comment by J-Jamet** [comment]
Otherwise there is a trick if you don't want to activate the setting. Just select password field to open the keyboard and press the validation button of the virtual keyboard.
