### ISSUE TITLE
Needed some more cloud sync

### ISSUE THREAD

**Issue by selva-1106** [Kunzisoft/KeePassDX#989]
I hate google drive because of their privacy policy. So i use tresorit, Jiocloud, and Mega. But these three cloud storage doesn't have cloud sync feature in Keepassdx. Can you have an future ideas to go with these cloud sync feature..

**Comment by J-Jamet** [comment]
Question already answered many times over and over again. Please read the other issues and the wiki before opening a new one.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
https://github.com/Kunzisoft/KeePassDX/issues/342

**Comment by J-Jamet** [comment]
If you have tested cloud applications that do not work properly. Feel free to add them to the wiki.
