### ISSUE TITLE
add in-line autofill API support for android 11+

### ISSUE THREAD

**Issue by pokegamer5547** [Kunzisoft/KeePassDX#990]
theres's a new API in android 11 or feature which allows autofill possible from keyboard. Its just an API which requires both keyboard and password manager to implement. currently i have only seen bitwarden implemented this.it would be cool if KeePass DX could also support this. i know it has magic keyboard but still atleast implementing this API can make some people feel more convienent when using KeePass DX and some third party keyboards can use it  thanks to this intregation.
https://developer.android.com/guide/topics/text/ime-autofill

**Comment by J-Jamet** [comment]
Already implemented. You didn't look hard.
https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#inline-suggestions

**Comment by pokegamer5547** [comment]
Ah sorry about that, i looked at issues but forgot to look in wiki and faqs.

**Comment by J-Jamet** [comment]
https://github.com/Kunzisoft/KeePassDX/issues/827
