### ISSUE TITLE
KeepassDX database save problem

### ISSUE THREAD

**Issue by pandorblah** [Kunzisoft/KeePassDX#992]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**KeePass Database**
 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android (please complete the following information):**
 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]
Hello respected sir/ma'am
I'm not able to save my database when the file is on sd card of my phone but I'm able to save it when it is in the internal storage
This was not happening for earlier entries which I did, but now I'm not able to save database if the file is in sd card

**Comment by J-Jamet** [comment]
Please fill in the exit form correctly.
In any case, the inability to read a file at a specific location is not a KeePassDX issue but a file manager issue and cannot be solved from KeePassDX. There may be a restriction depending on the memory, I advise you to check the behavior of your device with your manufacturer or the creator of the ROM / OS.

**Comment by pandorblah** [comment]
Ok sir I'll check it out again sir
